### ISSUE TITLE
Cloudflare+Nginx 报 403，无法登录，资源加载异常，IP+端口访问正常

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#10]
![image](https://user-images.githubusercontent.com/75829171/234166266-171a3bb7-07e0-4791-a976-53ac48fbc3b6.png)

cloudflare DNS:
![image](https://user-images.githubusercontent.com/75829171/234166443-72f74f74-c50d-46e3-86a3-6b53dcdb7481.png)
NGINX:
![image](https://user-images.githubusercontent.com/75829171/234166524-07c8465e-ed78-42b0-b049-8a0ca382d38e.png)

**Comment by songquanpeng** [comment]
我调查一下，#5 也是 403，项目本身并没有用到这个状态码。

**Comment by songquanpeng** [comment]
可以试一下我的 Nginx 配置吗：
```conf
        location / {
                client_max_body_size  64m;
                proxy_http_version 1.1;
                proxy_pass http://localhost:3066;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header Accept-Encoding gzip;
        }
```

**Comment by JeazW** [comment]
感谢，实测nginx配置优化后可以解决
