### ISSUE TITLE
通义千问无法返回多样性的结果

### ISSUE THREAD

**Issue by 102757017** [songquanpeng/one-api#1005]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在进行单轮会话时，使用同一个prompt多次调用qwen-turbo/qwen-plus，每次返回的结果都是完全一样的。我已经试过增加top_p，temperature，seed等参数，但是结果还是没有变化。
同一个程序调用gpt3.5-turbo时，更改seed会返回不同的结果。

**复现步骤**
    const completion = await openai.chat.completions.create({
    model: "qwen-turbo",
    messages: [{ role: 'user', 
                 content: `解释'准'这个词的意思，要让6岁儿童可以理解，再用这个词造一个简短句字，句子也要让6岁儿童可以理解。\n
                 用符合JSON5规范的数据进行回复{"explanation":"xx","sentence":"xx"}`}],
    top_p: 0.8,
    max_tokens: 200,
    seed: 999,
  });
**预期结果**
预期更改seed返回不同的结果，实际更改seed每次返回的结果都没变化。

**Comment by songquanpeng** [comment]
已修复，感谢反馈
