### ISSUE TITLE
[feature] 智谱清言大模型流式响应

### ISSUE THREAD

**Issue by QAbot-zh** [songquanpeng/one-api#1006]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
流式响应token计算一直是比较困难的，看智谱的文档，它实际上是带token统计信息的，有没有可能把这个字段加入进去，以获得流式响应中的准确token计算，文档参考：
https://open.bigmodel.cn/dev/api#glm-4

**Comment by songquanpeng** [comment]
智谱的文档我记得之前对接的时候就有坑，实际表现跟文档不一致，不确定目前是什么情况。

**Comment by songquanpeng** [comment]
我看了一下目前 One API 就是用的官方返回的 token 数，如果你的意思是 stream 模式下也返回 usage 相关字段，这个需要后面再看了，目前是想尽量与 OpenAI 保持一致。

**Comment by songquanpeng** [comment]
这个已经支持了哈

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/9b5aa8c1-ac59-479a-82b4-1e5e336de677)
