### ISSUE TITLE
post请求时，模型丢失?

### ISSUE THREAD

**Issue by oyabiubiu** [songquanpeng/one-api#1009]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
post 请求oneapi 接口时，提示 “当前分组 default 下对于模型  无可用渠道 “

我的post请求数据:

{
    "model":"gpt-3.5-turbo",
    "messages": [
        {
             "role": "user", 
             "content": "who are you"
        }
    ],
    "temperature": 0.7,
    "stream":false
}

post返回数据:
{
    "error": {
        "message": "当前分组 default 下对于模型  无可用渠道 (request id: 20240217221420431221851eBgCEaZ1)",
        "type": "one_api_error"
    }
}

查看后台渠道正常，查看日志：

2024/02/17 22:14:20 /build/model/ability.go:31 record not found
[0.337ms] [rows:0] SELECT * FROM `abilities` WHERE `group` = 'default' and model = '' and enabled = 1 and priority = (SELECT MAX(priority) FROM `abilities` WHERE `group` = 'default' and model = '' and enabled = 1) ORDER BY RAND(),`abilities`.`group` LIMIT 1
[GIN] 2024/02/17 - 22:14:20 | 20240217221420431221851eBgCEaZ1 | 503 |    1.291415ms |  我的ip地址 |    POST /v1/chat/completions
[ERR] 2024/02/17 - 22:14:20 | 20240217221420431221851eBgCEaZ1 | 当前分组 default 下对于模型  无可用渠道 
[GIN] 2024/02/17 - 22:16:02 | 2024021722160255351653878fqBDY | 200 |    1.073401ms |  我的ip地址 |     GET /api/about

然后查看数据库
mysql> SELECT * FROM `abilities` WHERE `group` = 'default';
+---------+------------------------+------------+---------+----------+
| group   | model                  | channel_id | enabled | priority |
+---------+------------------------+------------+---------+----------+
| default | gpt-3.5-turbo          |          3 |       1 |        1 |
| default | gpt-3.5-turbo          |          4 |       1 |        2 |
| default | gpt-3.5-turbo-0125     |          3 |       1 |        1 |
| default | gpt-3.5-turbo-0125     |          4 |       1 |        2 |
| default | gpt-3.5-turbo-0301     |          3 |       1 |        1 |
| default | gpt-3.5-turbo-0301     |          4 |       1 |        2 |
| default | gpt-3.5-turbo-0613     |          3 |       1 |        1 |
| default | gpt-3.5-turbo-0613     |          4 |       1 |        2 |
| default | gpt-3.5-turbo-1106     |          3 |       1 |        1 |
| default | gpt-3.5-turbo-1106     |          4 |       1 |        2 |
| default | gpt-3.5-turbo-16k      |          3 |       1 |        1 |
| default | gpt-3.5-turbo-16k      |          4 |       1 |        2 |
| default | gpt-3.5-turbo-16k-0613 |          3 |       1 |        1 |
| default | gpt-3.5-turbo-16k-0613 |          4 |       1 |        2 |
| default | gpt-3.5-turbo-instruct |          3 |       1 |        1 |
| default | gpt-3.5-turbo-instruct |          4 |       1 |        2 |
+---------+------------------------+------------+---------+----------+
16 rows in set (0.01 sec)

数据库是有模型数据的。

好像是丢失了模型字符串。导致后台不能正确匹配数据库

我的部署环境：ubuntu 22.04  docker 方式部署oneapi，连接本地mysql ,网络为host. post测试为vscode的postman插件

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by oyabiubiu** [comment]
![post](https://github.com/songquanpeng/one-api/assets/160333854/a44b1067-a0f2-4263-8a42-5a686806108c)
![mysql](https://github.com/songquanpeng/one-api/assets/160333854/36717678-a7fd-49ae-ba17-1173831feca0)
![qd](https://github.com/songquanpeng/one-api/assets/160333854/8ef9e0f8-4183-48f7-9885-40dc93a82546)

**Comment by songquanpeng** [comment]
你是什么版本呢？
