### ISSUE TITLE
配置 Turnstile后，无法重置密码

### ISSUE THREAD

**Issue by YDPlus** [songquanpeng/one-api#1015]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
系统配置 Turnstile后，重置密码时报错：Turnstile token为空
**复现步骤**
1.登录页面点击“忘记密码”
2.输入邮箱地址后点击“提交”
3.出现报错：Turnstile token为空
**相关截图**
<img width="311" alt="SCR-20240218-ucck" src="https://github.com/songquanpeng/one-api/assets/130046061/71a20750-2465-423f-af05-cd6529fd26e4">

**Comment by YDPlus** [comment]
麻烦告知下用户名，我们为您重置
________________________________
发件人: Wei Wibg ***@***.***>
发送时间: Thursday, March 7, 2024 9:09:34 PM
收件人: songquanpeng/one-api ***@***.***>
抄送: YDPlus ***@***.***>; Author ***@***.***>
主题: Re: [songquanpeng/one-api] 配置 Turnstile后，无法重置密码 (Issue #1015)


同样遇到这个bug，而且开启了Turnstile后还没办法关闭，清空后点击保存没反应。。。

―

**Comment by songquanpeng** [comment]
本周末处理
