### ISSUE TITLE
使用gpt-4-vision-preview模型不能处理几百KB的图片

### ISSUE THREAD

**Issue by gaord** [songquanpeng/one-api#1016]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
通过one-api调用gpt-4-vision-preview，小图片（测试用60KB）可以正常返回。大图片（500KB）出错。

[INFO] 2024/02/18 - 23:17:33 | 202402182317334062916694Mt5vuQ9 | user 1 has enough quota 705424221, trusted and no need to pre-consume   
[ERR] 2024/02/18 - 23:17:35 | 202402182317334062916694Mt5vuQ9 | relay error (channel #3):  (request id: 202402182317334062916694Mt5vuQ9)   
[GIN] 2024/02/18 - 23:17:35 | 202402182317334062916694Mt5vuQ9 | 413 |  2.109733043s |    192.168.65.1 |    POST /v1/chat/completions  

返回的错误：413 Request Entity Too Large。需要设置server对request大小的限制，满足图片编码在request中的长度需求。
同样图片直连openai可以正常返回结果。
**复现步骤**
1，使用one-api渠道访问openai vision模型
2，提交500KB以上图片给模型识别
**预期结果**
根据openai的规格说明，能够支持大尺寸的图片识别。

**Comment by songquanpeng** [comment]
可以给一下你当时调用的请求体么

**Comment by gaord** [comment]
后来发现是nginx默认设置文件太小了。改正以后一切正常。谢谢！
