### ISSUE TITLE
DeepSeek接入oneapi报错

### ISSUE THREAD

**Issue by ZYWNB666** [songquanpeng/one-api#1021]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√ ] 我已确认目前没有类似 issue
+ [ √] 我已确认我已升级到最新版本
+ [ √] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ √] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
DeepSeekAI平台的接口，使用自定义接口或openai接口(代理模型) 接入到oneapi使用和测试都会报错
测试报错400，使用报错422
**应用场景**
DeepSeek

**Comment by xinyin025** [comment]
按照下面这个图设置，在我这里是可以工作。
![1708420744343.png](https://image.dooo.ng/i/2024/02/20/65d46e8bd5727.webp)

**Comment by ZYWNB666** [comment]
![image](https://github.com/songquanpeng/one-api/assets/104631531/264e6499-c951-45e5-8a3f-eb9f1df8d0db)
![image](https://github.com/songquanpeng/one-api/assets/104631531/0b111b5d-15d3-45b4-a227-e0f91b3dd1d3)
我是这么配置的，不知道是哪的问题，有时候行有时候不行的，难道是限流了？

**Comment by songquanpeng** [comment]
测试更新了，现在可以正常测试了

**Comment by xiaozhang959** [comment]
> 测试更新了，现在可以正常测试了

大佬，你有试了是可行得通的吗？  我这边还是报错，测试404，请求无法请求到，但是我在其他api调用可以执行，在one-api里没法正常使用deepseek

**Comment by xinyin025** [comment]
> > 测试更新了，现在可以正常测试了
> 
> 大佬，你有试了是可行得通的吗？ 我这边还是报错，测试404，请求无法请求到，但是我在其他api调用可以执行，在one-api里没法正常使用deepseek

没问题，我的设定依然有效。

**Comment by songquanpeng** [comment]
已经原生支持 deepseek
