### ISSUE TITLE
404 Resource not found error

### ISSUE THREAD

**Issue by shenshanyoumu** [songquanpeng/one-api#1022]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在本地部署的OneAPI 站点创建新的渠道，配置Azure OpenAI，以及选择相应模型。通过postman调用
`
curl --location 'http://{oneAPI_host}/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxx' \
--data '{
    "model": "text-embedding-ada-002",
    "messages": [
        {
            "role": "user",
            "content": "who are founders of Apple"
        }
    ]
}'
`

{
    "error": {
        "message": "Resource not found (request id: 20240221000059395690000bd4GZy0t)",
        "type": "",
        "param": "",
        "code": "404"
    }
}

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by shenshanyoumu** [comment]
解决了，在配置渠道信息时 API版本配置错了

**Comment by songquanpeng** [comment]
好

**Comment by ivanberry** [comment]
> 在配置渠道信息时 API版本配置错了

@shenshanyoumu 你text-embedding-ada-002 配置的是什么版本，我现在这个模型也调用不成功，不过是返回500

**Comment by shenshanyoumu** [comment]
> > 在配置渠道信息时 API版本配置错了
> 
> @shenshanyoumu 你text-embedding-ada-002 配置的是什么版本，我现在这个模型也调用不成功，不过是返回500

Azure OpenAI服务，2023-09-01-preview

**Comment by PannyHuang** [comment]
在执行OpenVoice的demo_part2.ipynb的时候频繁出异常：
<img width="1181" alt="截屏2024-04-19 17 31 32" src="https://github.com/songquanpeng/one-api/assets/4351853/c7505a43-5915-49e1-bb23-8593f693efd8">
执行代码：
<img width="1115" alt="截屏2024-04-19 17 32 01" src="https://github.com/songquanpeng/one-api/assets/4351853/ed58ce02-4249-4c68-9734-ff587d56fdd7">
for循环内最后的time.sleep(5)是我自己加上的，
如果不加上这一行，i=1时就会出异常，
如果加上这一行，i=2是就会出异常
