### ISSUE TITLE
日志里面提示内容不显示了

### ISSUE THREAD

**Issue by katray608** [songquanpeng/one-api#1023]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
docker部署的，从v0.5.10更新到现在版本，把老数据覆盖进来，发现每次请求提示tokens显示为空，不知道哪里问题

**相关截图**
![微信截图_20240221105657](https://github.com/songquanpeng/one-api/assets/65582779/ebe565d0-57ce-41b0-bb4a-e92d5154537c)

**Comment by ye4293** [comment]
现在的版本是测试alpha版本，可能有bug

**Comment by jaydong2016** [comment]
我也有这个 bug

**Comment by QAbot-zh** [comment]
+1

**Comment by songquanpeng** [comment]
感谢反馈，已修复已推送
