### ISSUE TITLE
关于版本升级

### ISSUE THREAD

**Issue by wc2411888** [songquanpeng/one-api#1026]
请问下我去年部署的oneapi服务，现在因为有最新版了，想升级，旧版本连接的mysql的oneapi数据库新版本是否兼容呢，需不需要把mysql的oneapi库清空呢。亦或者旧版本的oneapi服务可以自动升级到新版本吗？

**Comment by QAbot-zh** [comment]
数据库一般情况是兼容的，不用清空

**Comment by songquanpeng** [comment]
看一下这里哈，有些版本确实是不兼容的需要执行脚本修正：https://github.com/songquanpeng/one-api/tree/main/bin

**Comment by songquanpeng** [comment]
除此之外直接更新就好，数据库会自动更新。

**Comment by s337443501** [comment]
@songquanpeng 以后还会再有单文件版本更新吗？就像v0.5.10版本之前那样

**Comment by songquanpeng** [comment]
会有的，目前缺失是因为之前主题更新导致 ci 脚本出 bug 了，打包出来的可执行文件启动后白屏，还未修复。

**Comment by ytrlmy521** [comment]
我直接更新了 镜像版本，部署后 渠道列表直接为空了。从0.6.1.alpha 升级到v0.6.7 
![image](https://github.com/user-attachments/assets/fd4b0a47-0d23-461f-be26-b843cc993272)

![image](https://github.com/user-attachments/assets/409c9457-a7b5-46e4-b644-4d5bb9827442)


升级前：
![image](https://github.com/user-attachments/assets/31fa6c26-67da-444b-b640-2d8a76d24295)


升级后：
所有渠道都没了，图中的频道是新加的。
![image](https://github.com/user-attachments/assets/ec6acbfd-f884-4719-8063-2933ccb9424b)

@songquanpeng

**Comment by QAbot-zh** [comment]
@ytrlmy521 用的什么数据库，怎么升级的，不会覆盖了吧
