### ISSUE TITLE
大佬看看请求超时报错

### ISSUE THREAD

**Issue by katray608** [songquanpeng/one-api#1027]
**问题描述**
本人宝塔面板安装的，安装好后请求api，显示如下报错，本人小白，请大佬赐教

**相关截图**
![微信截图_20240222120605](https://github.com/songquanpeng/one-api/assets/65582779/bf7966a4-4283-45f1-baae-d01b369c2847)

**Comment by QAbot-zh** [comment]
timeout， 网络问题，国内服务器还是国外的，能访问外网吗？

**Comment by katray608** [comment]
> 超时，网络问题，国内的服务器还是国外的，能访问外网吗？

国外服务器，测试过了，服务器能访问外网。

**Comment by QAbot-zh** [comment]
> > 超时，网络问题，国内的服务器还是国外的，能访问外网吗？
> 
> 国外服务器，测试过了，服务器能访问外网。

有终端吗，测测直接post能不能得到响应：
```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-xxxxxxxxxxxx" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'
```

**Comment by katray608** [comment]
> > > 超时，网络问题，国内的服务器还是国外的，能访问外网吗？
> > 
> > 
> > 国外服务器，测试过了，服务器能访问外网。
> 
> 有终端吗，测测直接post能不能得到响应：
> 
> ```
> curl https://api.openai.com/v1/chat/completions \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer sk-xxxxxxxxxxxx" \
>   -d '{
>     "model": "gpt-3.5-turbo",
>     "messages": [
>       {
>         "role": "user",
>         "content": "Hello!"
>       }
>     ]
>   }'
> ```

刚刚捣鼓了下，应该是docker问题，修复了下暂时可以用，感谢大佬
