### ISSUE TITLE
通义千问的max_tokens,temperature,top_p传入的参数没生效

### ISSUE THREAD

**Issue by kuangkuan** [songquanpeng/one-api#1028]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
千问模型的参数没有生效
**复现步骤**
![image](https://github.com/songquanpeng/one-api/assets/30993995/c638d81a-7f5a-4f89-b5a5-b295014257c8)

**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/30993995/31ee9c3c-f597-4ab6-82dc-75873543a5a8)

如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
周末处理哈

**Comment by kuangkuan** [comment]
已经fix了吗

**Comment by songquanpeng** [comment]
处理中
