### ISSUE TITLE
无限额度报用户额度不足

### ISSUE THREAD

**Issue by ilay1678** [songquanpeng/one-api#103]
无限额度报用户额度不足

**Comment by songquanpeng** [comment]
无限额度的只可能是令牌的额度吧？

**Comment by ilay1678** [comment]
明白了，现在的充值是给用户充值额度哈

**Comment by songquanpeng** [comment]
是的，令牌的额度仅供用户设置最大使用量，可以随便改的。

**Comment by ilay1678** [comment]
> 是的，令牌的额度仅供用户设置最大使用量，可以随便改的。

README现在描述有误
`支持兑换码管理，支持批量生成和导出兑换码，可使用兑换码为令牌进行充值。`

可使用兑换码为令牌进行充值

**Comment by songquanpeng** [comment]
忘记更新了，之前确实是为令牌进行充值。
