### ISSUE TITLE
希望可以自行修改模型价格

### ISSUE THREAD

**Issue by Gngzs** [songquanpeng/one-api#1035]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
自定义模型价格，而不是只可以调整倍率
**应用场景**
自定义模型或者及时更新价格

**Comment by songquanpeng** [comment]
倍率实际上就是价格哦，只是单位不一样，这个之后前端会进行优化
