### ISSUE TITLE
希望在某个渠道报错之后，能自动使用其他渠道重试

### ISSUE THREAD

**Issue by coulsontl** [songquanpeng/one-api#1036]
希望在某个渠道报错之后，能自动使用其他渠道重试，连续报错N次之后自动禁用渠道；现在是直接返回错误了

**Comment by songquanpeng** [comment]
有自动重试的哈，我刚刚也正好更新了内置重试，之前是跳转重试

**Comment by coulsontl** [comment]
> 有自动重试的哈，我刚刚也正好更新了内置重试，之前是跳转重试

@songquanpeng 大佬，Docker镜像已更新到最新；现在是只会在当前渠道重试吗？我试了下当前渠道返回429之后并没有切换到其他的可用渠道进行重试
