### ISSUE TITLE
哥，要不这默认端口，您别用3000行吗？

### ISSUE THREAD

**Issue by daiaji** [songquanpeng/one-api#1039]
ChatGPTNextWeb他就用这个，我这又用的pod部署，直接反代到pod内的localhost:3000就行，没必要再用容器的端口映射。
您要不用别的端口？

**Comment by Kadxy** [comment]
你咋不去 next-chat 反馈让他也改个默认端口呢？

**Comment by Passerby1011** [comment]
给我看乐了这个issuse

**Comment by daiaji** [comment]
老实讲恐怕都不愿意放弃兼容性吧😓

**Comment by Kadxy** [comment]
> 老实讲恐怕都不愿意放弃兼容性吧😓

这跟兼容性有任何关系吗🤔

**Comment by daiaji** [comment]
> > 老实讲恐怕都不愿意放弃兼容性吧😓
> 
> 这跟兼容性有任何关系吗🤔

我用podman+systemd单元，假设修改监听端口，端口映射是写死在systemd服务文件里的，你猜更新镜像后会怎么样？😙

**Comment by Passerby1011** [comment]
> > > 老实讲恐怕都不愿意放弃兼容性吧😓
> > 
> > 
> > 这跟兼容性有任何关系吗🤔
> 
> 我用podman+systemd单元，假设修改监听端口，端口映射是写死在systemd服务文件里的，你猜自动更新镜像后会怎么样？
> 
> Docker Compose会自动更新端口映射吗？

那就不用呗，又不是没得选

**Comment by Kadxy** [comment]
> > > 老实讲恐怕都不愿意放弃兼容性吧😓
> > 
> > 这跟兼容性有任何关系吗🤔
> 
> 我用podman+systemd单元，假设修改监听端口，端口映射是写死在systemd服务文件里的，你猜自动更新镜像后会怎么样？
> 
> Docker Compose会自动更新端口映射吗？

你猜猜 fork 是干什么用的😀

**Comment by daiaji** [comment]
这也能ETC？恁🐮逼

**Comment by songquanpeng** [comment]
默认端口没法变了，这是 breaking change
