### ISSUE TITLE
渠道支持指定 model 

### ISSUE THREAD

**Issue by quzard** [songquanpeng/one-api#104]

**Comment by songquanpeng** [comment]
是的，这是接下来要做的。

相关 issue：#17，#72，#85

**Comment by quzard** [comment]
这个比较好实现，加个model表和ApiModel表就可以了。

**Comment by quzard** [comment]
看了下代码，需要在Distribute里读取requestBody的model。根据model再来选取可用的channel

**Comment by songquanpeng** [comment]
是的，之后是在中间件这里完成 channel 的选择。

具体的实现方式可能是拓展 channel 表，而不是额外加表。

我还没决定好到底如何实现。

**Comment by quzard** [comment]
> 是的，之后是在中间件这里完成 channel 的选择。
> 
> 具体的实现方式可能是拓展 channel 表，而不是额外加表。
> 
> 我还没决定好到底如何实现。

扩展channel 表页比较好实现。可以用位运算来实现。sqlite的interger支持32位数字。也就是说做多可以支持32种模型。目前来看完全够用了

**Comment by songquanpeng** [comment]
直接 blob 类型就好，位数不是问题。

之后 channel 整体都是要缓存的，毕竟读多写少，使用还很频繁。
