### ISSUE TITLE
无效的请求

### ISSUE THREAD

**Issue by bite-weldon** [songquanpeng/one-api#1041]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
今早(2024-02-26)，突然发现我们自建的AI总是返回
```
{

  "error": {

    "message": "无效的请求 (request id: 20240226100548830008922uwet62Ci)",

    "type": "one_api_error"

  }

}
```
而且上周五（2024-02-23）还正常使用的，一番查找也没找到问题所在
- 令牌正确
- 额度正常
- 渠道测试正常
- 页面访问正常

注： 我的前端是 ChatGPT Next Web，渠道是azure openai

**复现步骤**
看到容器日志里开始有阶段性报错，429:当前分组负载已饱和，请稍后再试，对于这个问题，我重启了容器再调用还是上面的错误（无效的请求）

**预期结果**
AI 对话恢复正常

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/152843433/92dab81d-d5c2-436e-bec9-91bbf05f05f6)

**Comment by songquanpeng** [comment]
可以发一下对应的请求的请求体吗？

**Comment by bite-weldon** [comment]
{
    "messages": [
        {
            "role": "system",
            "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2024/2/27 09:31:53\n"
        },
        {
            "role": "user",
            "content": "请帮我拟一个500字左右的有关猎人与狼的故事"
        },
        {
            "role": "assistant",
            "content": "\n\n```json\n{\n  \"error\": {\n    \"message\": \"无效的请求 (request id: 2024022617191198674973452109475)\",\n    \"type\": \"one_api_error\"\n  }\n}\n```"
        },
        {
            "role": "user",
            "content": "请帮我拟一个500字左右的有关猎人与狼的故事"
        }
    ],
    "stream": true,
    "model": "gpt-3.5-turbo",
    "temperature": 0.5,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "top_p": 1
}

![image](https://github.com/songquanpeng/one-api/assets/152843433/ca38722c-de04-4c46-b13d-a08e841ba0da)

是这样的吗

另外，我昨天又发现了一个奇怪的现象，我这个AI平台，不是所有用户都请求失败，还有个别的人可以使用，这让我都怀疑是不是上层的前端和底层的新版本不兼容搞的

**Comment by bite-weldon** [comment]
各位，这个单子在我无意间触碰到一个能解决问题的按钮后，就毫无征兆的修复了


![image](https://github.com/songquanpeng/one-api/assets/152843433/ffe411ff-91f6-42c8-810f-d0a0d0d71ab8)

**Comment by bite-weldon** [comment]
可能是前端少了某个token类的参数，在one-api端点击这个聊天按钮后，会自动跳转到聊天页面，然后会带入api-key，手动确认后，就又能正常问答了
