### ISSUE TITLE
ChatGLM调用提示top_p参数错误

### ISSUE THREAD

**Issue by deopllj** [songquanpeng/one-api#1045]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

ChatGLM渠道中，如果传入的top_p是1（例如NextChat的默认值），则报错top_p参数不合法

**复现步骤**
见截图

**预期结果**

问题是由于智谱对于参数的严格检查导致的（必须是Float类型，且取值是（0,1）的开区间），但是其他渠道对于参数（例如整形的1或者0）则没有严格限制。
建议对top_p参数做强制类型转换，并且把1改成0.99， 0改成0.01：
在one-api/relay/channel/zhipu/main.go中，修改：
```go
return &Request{
		Prompt:      messages,
		Temperature: request.Temperature,
		TopP:        request.TopP,
		Incremental: false,
}
```
为：
```go
topPFloat := float64(request.TopP) // 如果需要转换

// 根据条件调整TopP的值
if topPFloat >= 1 {
    topPFloat = 0.99
} else if topPFloat <= 0 {
    topPFloat = 0.01
}

// 然后使用调整后的topPFloat值进行返回
return &Request{
    Prompt:      messages,
    Temperature: request.Temperature,
    TopP:        topPFloat, // 使用调整后的值
    Incremental: false,
}

```

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/59074537/189c8f85-e9bb-4b33-a1f6-6fd97852f4aa)
![image](https://github.com/songquanpeng/one-api/assets/59074537/15d4027c-c008-432a-8634-58e23000adc5)
抓包结果：
![image](https://github.com/songquanpeng/one-api/assets/59074537/5f2946b1-71cb-482d-bcad-a3773e8560ad)

**Comment by LeeSenBLVER** [comment]
正是我想问的！

**Comment by QAbot-zh** [comment]
不只是类型，智谱实际上是开区间，不接受0和1
https://github.com/songquanpeng/one-api/issues/952#issuecomment-1902583334

**Comment by deopllj** [comment]
> 不只是类型，智谱实际上是开区间，不接受0和1 [#952 (comment)](https://github.com/songquanpeng/one-api/issues/952#issuecomment-1902583334)

确实，仔细看了一下官方文档，那这种情况就只能考虑强制把传入的1改成0.99，0改成0.01这样

**Comment by LeeSenBLVER** [comment]
请问 我改完代码，然后按照文档的打包指令打完包，运行时无报错，但也无法访问
![image](https://github.com/songquanpeng/one-api/assets/15902118/4889d954-3d48-483d-be9b-6f882b63427d)
![image](https://github.com/songquanpeng/one-api/assets/15902118/ad34e159-7ed7-4345-8082-32b86484d101)

**Comment by zerotwotnt** [comment]
请问怎么调用glm4的模型呀

**Comment by deopllj** [comment]
> 请问怎么调用glm4的模型呀
智谱官网可以申请api

**Comment by zerotwotnt** [comment]
> > 请问怎么调用glm4的模型呀
> > 智谱官网可以申请api

对，申请了api，就是在oneAPI中怎么配置glm4，因为我看到oneAPI中选择智谱GLM，下面的默认模型应该都是3.5的吧，比如chatglm_turbo,chatglm_pro,chatglm_std这样

**Comment by deopllj** [comment]
> > > 请问怎么调用glm4的模型呀
> > > 智谱官网可以申请api
> 
> 对，申请了api，就是在oneAPI中怎么配置glm4，因为我看到oneAPI中选择智谱GLM，下面的默认模型应该都是3.5的吧，比如chatglm_turbo,chatglm_pro,chatglm_std这样


需要在one-api中手动添加glm-4以及glm-4v模型即可调用

**Comment by zerotwotnt** [comment]
> > > > 请问怎么调用glm4的模型呀
> > > > 智谱官网可以申请api
> > 
> > 
> > 对，申请了api，就是在oneAPI中怎么配置glm4，因为我看到oneAPI中选择智谱GLM，下面的默认模型应该都是3.5的吧，比如chatglm_turbo,chatglm_pro,chatglm_std这样
> 
> 需要在one-api中手动添加glm-4以及glm-4v模型即可调用

能够贴一下图片给我参考一下吗，因为之前我手动添加后调用失败了，感谢大佬！！！

**Comment by QAbot-zh** [comment]
> > > > > 请问怎么调用glm4的模型呀
> > > > > 智谱官网可以申请api
> > > 
> > > 
> > > 对，申请了api，就是在oneAPI中怎么配置glm4，因为我看到oneAPI中选择智谱GLM，下面的默认模型应该都是3.5的吧，比如chatglm_turbo,chatglm_pro,chatglm_std这样
> > 
> > 
> > 需要在one-api中手动添加glm-4以及glm-4v模型即可调用
> 
> 能够贴一下图片给我参考一下吗，因为之前我手动添加后调用失败了，感谢大佬！！！

就添加自定义模型呀，调用失败总有报错吧，看看报错
![image](https://github.com/songquanpeng/one-api/assets/40236765/3a01a046-562d-4747-aa3f-4e9f45714594)

**Comment by zerotwotnt** [comment]
> > > > > > 请问怎么调用glm4的模型呀
> > > > > > 智谱官网可以申请api
> > > > 
> > > > 
> > > > 对，申请了api，就是在oneAPI中怎么配置glm4，因为我看到oneAPI中选择智谱GLM，下面的默认模型应该都是3.5的吧，比如chatglm_turbo,chatglm_pro,chatglm_std这样
> > > 
> > > 
> > > 需要在one-api中手动添加glm-4以及glm-4v模型即可调用
> > 
> > 
> > 能够贴一下图片给我参考一下吗，因为之前我手动添加后调用失败了，感谢大佬！！！
> 
> 就添加自定义模型呀，调用失败总有报错吧，看看报错 ![image](https://private-user-images.githubusercontent.com/40236765/308435290-3a01a046-562d-4747-aa3f-4e9f45714594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTg5NzAsIm5iZiI6MTcwOTExODY3MCwicGF0aCI6Ii80MDIzNjc2NS8zMDg0MzUyOTAtM2EwMWEwNDYtNTYyZC00NzQ3LWFhM2YtNGU5ZjQ1NzE0NTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZmU0NGEwMDQ1OWY3YzBjMjAzMzU3YmQyNTBjNzMxYzg3ZmRkYTkwNGRkNzQ0OWFkYWZmMTM3YWQyNDkzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hhqwa1lPIo6uywJ0w6hOMTDyPlzNTE3B5c9JEh2CaFI)

我试过了，可以使用，非常感谢！！！

**Comment by songquanpeng** [comment]
v0.6.1-alpha.2 已经支持
