### ISSUE TITLE
重试后额度问题

### ISSUE THREAD

**Issue by akaler727** [songquanpeng/one-api#1047]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
请问一下，在中继请求中，额度会先进性预扣减，但是如果请求大模型失败，我看代码就是重定向重试，那么预扣减的额度是不是就没有了，还有就是建议在预扣减时，只扣除redis的值，最后成功后再扣减mysql的数据

**Comment by songquanpeng** [comment]
会返还，并且现在不是重定向了

**Comment by akaler727** [comment]
感谢回复

> 会返还，并且现在不是重定向了

还有个问题想问一下，关于额度如果直接用钱算是不是也可以，请问使用额度是因为有货币汇率的问题吗？

**Comment by akaler727** [comment]
不好意思作者还有个问题就是现在中继请求是不是没有加速率控制？

**Comment by akaler727** [comment]
> 不好意思作者还有个问题就是现在中继请求是不是没有加速率控制？

还有就是为什么中继请求不加上速率控制？

**Comment by songquanpeng** [comment]
麻烦另起issue说明场景
