### ISSUE TITLE
支持 Google PaLM

### ISSUE THREAD

**Issue by AiZyc** [songquanpeng/one-api#105]
https://developers.generativeai.google/guide
最近有开放相关的内测开发权限，如需API密钥我可以提供。

申请入口：https://makersuite.google.com/waitlist
需要将谷歌语言改成英语且IP是美国，即可申请内测

**Comment by songquanpeng** [comment]
Okay，做这个适配会比较有意思。

**Comment by Aiayw** [comment]
可能要一周左右？我好像是十号左右申请的。需要我提供key吗？

**Comment by songquanpeng** [comment]
群里面有一个老哥给了一个 key，我还以为你就是他哈

**Comment by Aiayw** [comment]
哈哈，是的，我以为你没收到，所以通过issue提，就当记录需求了。

**Comment by songquanpeng** [comment]
收到了，我应该回复了。

**Comment by Aiayw** [comment]
嗯嗯，抱歉，是我没留意到信息，翻了一下记录是有艾特我的。

**Comment by songquanpeng** [comment]
参考：
1. https://developers.generativeai.google/api/rest/generativelanguage
2. https://github.com/haibbo/cf-openai-azure-proxy/blob/main/cf-openai-palm-proxy.js
