### ISSUE TITLE
qwen-turbo无法接入chat-next-web中

### ISSUE THREAD

**Issue by 17794** [songquanpeng/one-api#1050]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述** 将百度和讯飞接入后在chatnextweb中都可以正常输出，但是通义千问模型一直转圈无输出，在oneapi模型界面测试通义千问模型是通过的，chatnextweb中无输出的模型是qwen-turbo和qwen-plus，chatnextweb的表现结果为加载很长时间无反应，但经过测试python代码确实可以正常调用qwen-turbo。

**复现步骤** 1. 在one api中配置通义千问模型，并点击测试，测试通过。
2. 在chatnextweb配置转发地址，key以及自定义模型名后选择模型qwen-turbo
3.  询问模型

**预期结果**
正常输出答案
**事实结果**
无法输出

**Comment by zhanghxiao** [comment]
是否是你模型名称错了，我这边可用
![image](https://github.com/songquanpeng/one-api/assets/137479165/61765d75-06f9-44d5-85f1-cf0fc66ae5b4)

**Comment by songquanpeng** [comment]
需要提供报错信息哈

**Comment by songquanpeng** [comment]
无法复现，先关了
![image](https://github.com/songquanpeng/one-api/assets/39998050/8661e4cc-ec60-4e57-ae5f-0b37b7aec80d)

**Comment by cnliucheng** [comment]
> 是否是你模型名称错了，我这边可用
> 
> ![image](https://github.com/songquanpeng/one-api/assets/137479165/61765d75-06f9-44d5-85f1-cf0fc66ae5b4)
> 
> 

我也是这个问题，正确的模型名称是什么呢
