### ISSUE TITLE
请问是否有支持 Mistral 的 La Plateforme 平台的计划

### ISSUE THREAD

**Issue by qingfengfenga** [songquanpeng/one-api#1051]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
支持 Mistral 的 La Plateforme 平台

**应用场景**
支持 Mistral 的 La Plateforme 平台的 Key

**相关URL**

官网
https://docs.mistral.ai/api/

平台
https://console.mistral.ai/

Api文档
https://docs.mistral.ai/api/

**Comment by qingfengfenga** [comment]
> 当然支持，包括其azure版本，不过需要有人提供测试key

我目前可以提供La Plateforme平台的key

Azure的还要看一下我这边能不能开

key怎么给你

**Comment by songquanpeng** [comment]
已经支持
