### ISSUE TITLE
百度的ERNIE-Speed没有数据返回

### ISSUE THREAD

**Issue by cn-hideyoshi** [songquanpeng/one-api#1053]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本 
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
v0.5.12-alpha
百度的ERNIE-Speed没有返回,是否是版本问题
**复现步骤**
将model 改为 ERNIE-Speed 没有数据

**Comment by WestCraneLi** [comment]
请问是怎么解决的，我这里发现用ERNIE-Speed，最终One-Api调用的是ERNIE-4
