### ISSUE TITLE
Azure 通道 stream 模式工作不正常

### ISSUE THREAD

**Issue by songquanpeng** [songquanpeng/one-api#106]
服务端估计是读取完才返回的。

**Comment by ilay1678** [comment]
微软的api就是一段一段返回的，可以参考这里实现打字机效果 https://github.com/haibbo/cf-openai-azure-proxy/blob/b851be3c110356197c6e86b1c452df244a8496df/cf-openai-azure-proxy.js#L82

**Comment by songquanpeng** [comment]
> 微软的api就是一段一段返回的

这个是什么意思？是指 Azure 的流式传输 API 实际上并不是实时的？

**Comment by ilay1678** [comment]
> > 微软的api就是一段一段返回的
> 
> 这个是什么意思？是指 Azure 的流式传输 API 实际上并不是实时的？

https://github.com/stulzq/azure-openai-proxy/issues/26

**Comment by songquanpeng** [comment]
目前看两种说法都有，我是感觉 One API 的流式传输实现应该是没问题的，毕竟绝大部分代码是和 OpenAI 的流式传输功能共用的。

之后有空后我再来调查这个问题。

感谢反馈。

**Comment by songquanpeng** [comment]
基本上可以确认是 Azure 本身的问题。

可以看到其他项目也遇到了同样的问题：
![image](https://github.com/songquanpeng/one-api/assets/39998050/58102df6-49da-46fd-a36e-dc2373003535)

如果后续有变化，欢迎重开 issue。

**Comment by VectorZhao** [comment]
实测该项目的打字效果不错，可以参考一下代码：
[https://github.com/haibbo/cf-openai-azure-proxy](https://github.com/haibbo/cf-openai-azure-proxy)
![image](https://github.com/songquanpeng/one-api/assets/16644993/8bcbf5ec-190e-4c62-8b0e-1321a74bfeb7)

打字效果的心理作用还是挺大的，减少用户心理等待时间，心理上的响应速度变快

**Comment by songquanpeng** [comment]
这不是掩耳盗铃么？我说为什么这个项目可以，原来是故意拆分的。

**Comment by songquanpeng** [comment]
不过你说的确实有一定道理。

**Comment by JiaanT** [comment]
似乎转发Azure的时候因为steam是一整段，OneAPI返回的第一条respond是空的，会导致下游客户端报错。这个返回方式应该和OpenAI保持一致，等收到第一段再respond吧？
