### ISSUE TITLE
/v1/models 不能获取自定义模型？

### ISSUE THREAD

**Issue by bincooo** [songquanpeng/one-api#1060]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如题

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
这个会支持的，我想问一下是什么场景呢？

**Comment by bincooo** [comment]
有些壳子网站没有自定义模型填写，是根据/v1/models 获取...

**Comment by GalileoFe** [comment]
我现在的办法是nginx反向代理的时候自己写一个v1/models 暂时可以这样简单的解决

**Comment by songquanpeng** [comment]
已经支持了

**Comment by bincooo** [comment]
好的，感谢

**Comment by jay-jjwu** [comment]
我测试了还是不行，能请大佬指导一下吗？
![Uploading image.png…]()
