### ISSUE TITLE
仅调用三次，就抛出 `当前分组上游负载已饱和，请稍后再试`

### ISSUE THREAD

**Issue by mkdir700** [songquanpeng/one-api#1061]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

仅调用了三次，就报了 `当前分组上游负载已饱和，请稍后再试`

GLOBAL_API_RATE_LIMIT  和 GLOBAL_WEB_RATE_LIMIT 环境变量未做显式声明，所以值应该是默认值。

**复现步骤**

10 秒内频繁调用超过 3 次。

**预期结果**

**相关截图**

后端日志截图：

![image](https://github.com/songquanpeng/one-api/assets/56359329/1aaea8dd-7f79-420f-a807-f0fcd0270ea0)

后台调用日志：

![image](https://github.com/songquanpeng/one-api/assets/56359329/cb3f8bd1-5ea3-40df-9939-8313c586df1b)

**Comment by mkdir700** [comment]
测试了 OpenAI、Gemini 和 GLM，只有 OpenAI 是这样的情况，连续请求 3 次就超出上游负载了。

**Comment by Kadxy** [comment]
有没有可能是你号的问题，普号 rpm3

**Comment by songquanpeng** [comment]
跟你填入的 key 的速率有关系哈
