### ISSUE TITLE
Model redirection - bug

### ISSUE THREAD

**Issue by comeback01** [songquanpeng/one-api#1062]
I've just installed one api, and everything works fine.

The only thing that doesn't work is "Model redirection".

I've tried several programs and always get an error.

Here's my configuration:

`{
  "gpt-4": "test"
}
`

here's an error message:

`{
  "error": {
    "message": "当前Group default 下对于Model test No available channels (request id: 2024030121582094718622595676243)",
    "type": "one_api_error"
  },
  "provider": "openai",
  "endpoint": "https://libre.***.ch/v1"
}
`
thank you for your help

**Comment by songquanpeng** [comment]
Hi, this means the requested model is rewritten to `test`. In normal case, there is no need to config it.

Btw, the error message here will be fixed, currently it's a mess.

**Comment by comeback01** [comment]
"I know, but I put 'test' to try.

In any case, I want to rename GPT-4 with another name.

How do I do that?"

**Comment by QAbot-zh** [comment]
> "I know, but I put 'test' to try.
> 
> In any case, I want to rename GPT-4 with another name.
> 
> How do I do that?"


Then you should add `test` and `gpt-4` model to the model list and add model mapping as follow :
![image](https://github.com/songquanpeng/one-api/assets/40236765/ef7d9e67-24f4-4101-b2eb-b65523615c9e)

** But keep in mind, this only allows you to access GPT-4 using the model name "test", it does not have the ability to deny direct access to the key using the name "gpt-4". **

**Comment by songquanpeng** [comment]
If you still have questions, feel free to reopen this issue.

**Comment by comeback01** [comment]
"Thank you, it works but not with OpenRouter:"

`{
  "test": "google/palm-2-chat-bison-32k"
}

I think it's because of the slash '/'.

Do you have a solution?

Thank you.`
