### ISSUE TITLE
智普AI的V4版本如何对接?

### ISSUE THREAD

**Issue by fengjisheng** [songquanpeng/one-api#1066]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我已完整查看过项目 README，尤其是常见问题部分
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我看代码已经支持了V4版本, 不知道如何切换到这个版本.

官方通知这些V3模型即将弃用, 并指向新模型, https://open.bigmodel.cn/dev/howuse/model
chatglm_pro -> glm-4
chatglm_std -> glm-3-turbo
chatglm_lite -> glm-3-turbo

也不需要转换message.Role, 和openai接口一样了.

**Comment by songquanpeng** [comment]
把新的模型名称填上就行

**Comment by Shady2333** [comment]
现在one-api默认调用的V1接口吧？我现在对接智谱，都是404，因为智谱现在都是v4接口了，不知道咋搞
