### ISSUE TITLE
自定义接口的 dall-e-3 调用 /chat/completitions 接口

### ISSUE THREAD

**Issue by sherlcok314159** [songquanpeng/one-api#1067]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

我在使用自定义接口的 dall-e-3，后台发现调用的是 `/chat/completitions`接口，这个问题是否是因为自定义接口默认都走 chat?

**Comment by wq290243612** [comment]
+1，我也遇到这个问题。

**Comment by songquanpeng** [comment]
没有复现：
![image](https://github.com/songquanpeng/one-api/assets/39998050/bf4c5e04-680b-4490-915d-ddaf5dffaf68)
![image](https://github.com/songquanpeng/one-api/assets/39998050/79d04dc4-62ce-4288-baa5-e6c3ad19c85a)

**Comment by wq290243612** [comment]
感谢回复，经过核查发现是lobechat和next-web这两个项目总是会在请求地址后面加上/chat/completitions。

**Comment by songquanpeng** [comment]
所以是客户端问题，issue 先关了哈

**Comment by sherlcok314159** [comment]
> 感谢回复，经过核查发现是lobechat和next-web这两个项目总是会在请求地址后面加上/chat/completitions。

那老哥你是怎么解决的呢？

**Comment by wq290243612** [comment]
> > 感谢回复，经过核查发现是lobechat和next-web这两个项目总是会在请求地址后面加上/chat/completitions。
> 
> 那老哥你是怎么解决的呢？

我没解决，改用lobe的dalle3插件了。
