### ISSUE TITLE
Azure OpenAI渠道测试`响应时间`提示错误

### ISSUE THREAD

**Issue by aaro-n** [songquanpeng/one-api#1069]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
已通过docker方式更新one-api版本为0.6.0，在`渠道界面`选择`测试启用渠道`，显示功能正常，但我手动单独测试`响应时间`时，测试`Azure OpenAI`渠道，提示`错误：status code 404: Resource not found`，复制`令牌`里的访问密钥并加`-3`测试Azure OpenAI渠道，这个渠道可以用
**复现步骤**
无
**预期结果**
能正常使用Azure OpenAI渠道
# 日志
## 测试Azure OpenAI渠道响应时间
显示`错误：status code 404: Resource not found`
日志
```
[info] [GIN] 2024/03/03 - 12:44:57 | 2024030312445793970330819146001 | 200 | 57.593326ms | 67.230.xxxx.zzzz | GET /api/channel/test/3
```
openai（渠道1），Googlle Gemini（渠道2），阿里通义千问（渠道4）都有返回信息，Azure OpenAI（渠道3）未有测试信息返回。

**Comment by songquanpeng** [comment]
我目前缺失有效的 Azure 测试 key

**Comment by songquanpeng** [comment]
已获得，已复现

**Comment by songquanpeng** [comment]
已修复，今晚推送
