### ISSUE TITLE
docker-compose启动one-api服务报错：failed to initialize database, got error dial tcp: lookup db on 127.0.0.11:53: server misbehaving

### ISSUE THREAD

**Issue by syusama** [songquanpeng/one-api#1077]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
docker-compose启动one-api服务报错：failed to initialize database, got error dial tcp: lookup db on 127.0.0.11:53: server misbehaving
**复现步骤**
这是我的docker-compose.yml
`version: '3.4'

services:
  one-api:
    image: justsong/one-api:v0.6.0
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3001:3000"
    volumes:
      - ./data/oneapi:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=oneapi:123456@tcp(db:3306)/one-api  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://one-api-redis
      - SESSION_SECRET=123456  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    depends_on:
      - one-api-redis
      - one-api-mysql
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  one-api-redis:
    image: redis:latest
    container_name: one-api-redis
    restart: always

  one-api-mysql:
    image: mysql:8.2.0
    restart: always
    container_name: one-api-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    ports:
      - '3307:3306'
    environment:
      TZ: Asia/Shanghai   # 设置时区
      MYSQL_ROOT_PASSWORD: '123456' # 设置 root 用户的密码
      MYSQL_USER: oneapi   # 创建专用用户
      MYSQL_PASSWORD: '123456'    # 设置专用用户密码
      MYSQL_DATABASE: one-api   # 自动创建数据库`
**预期结果**
启动后one-api服务报错
**相关截图**
如果没有的话，请删除此节。
![1709544722347](https://github.com/songquanpeng/one-api/assets/16223129/c92c64d2-04db-4c4e-88b7-1299c228e2c0)

**Comment by Crush-RY** [comment]
出现了同样的问题，可以告知下如何解决的吗？谢谢！

**Comment by Axe-l** [comment]
SAME

**Comment by anjia1991** [comment]
- SQL_DSN=oneapi:123456@tcp($YOUR_DB_IP:3306)/one-api

**Comment by Cynthia-ly** [comment]
请问该bug如何解决的，为什么已经是closed状态

**Comment by anjia1991** [comment]
> 请问该bug如何解决的，为什么已经是closed状态

SQL_DSN=oneapi:123456@tcp(**_$YOUR_DB_IP_**:3306)/one-api
