### ISSUE TITLE
手动部署后访问出现空白页面

### ISSUE THREAD

**Issue by Narakuuuu** [songquanpeng/one-api#1078]
![image](https://github.com/songquanpeng/one-api/assets/129150191/1a5ab112-ebf7-464e-b32c-7d3bfe348ea7)

**Comment by Narakuuuu** [comment]
求指导

**Comment by MustAPI** [comment]
https://blog.pppfz.com/index.php/archives/28/?scroll=comment-10

**Comment by Yuanlw** [comment]
解决了吗？重新安装试试，我也发现这个问题

**Comment by songquanpeng** [comment]
请问是自己编译的么？

**Comment by lijie97** [comment]
同样有这个问题

**Comment by huxiaochen-corporation** [comment]
我的问题差不多, windows 系统本地编译的, 修改过端口号。能ping通，但是这个网页访问不了。
另外我还没装fastGPT，因此应该不存在端口号冲突。
![image](https://github.com/songquanpeng/one-api/assets/25471026/8a7e6a22-ae26-4726-a974-d0dc5463ccd8)
![image](https://github.com/songquanpeng/one-api/assets/25471026/bd2c79f8-65d0-4f86-82bd-6727c4d5e4f0)
![image](https://github.com/songquanpeng/one-api/assets/25471026/3666e6f3-3380-4431-842b-bd2197e545d9)
![image](https://github.com/songquanpeng/one-api/assets/25471026/3a9a455a-9e27-4391-933a-470ae2fb31c0)

**Comment by huxiaochen-corporation** [comment]
> 请问是自己编译的么？

我的是自己编译的

**Comment by songquanpeng** [comment]
自己编译的话我猜是没有编译打包前端，参考dockerfile看一下编译流程哈

**Comment by songquanpeng** [comment]
看一下这里也可以：https://github.com/songquanpeng/one-api/blob/main/.github%2Fworkflows%2Flinux-release.yml

**Comment by 13829386012** [comment]
@huxiaochen-corporation 请问你解决了吗？我遇到了同样的问题

**Comment by 13829386012** [comment]
@songquanpeng 你好,我也是执行npm run build命令编译打包的，运行./one-api --port 3000 --log-dir ./log后
![run](https://github.com/songquanpeng/one-api/assets/40138671/644c6982-5e0c-4437-8563-583cedf6b322)
卡在token encoders initialized这里
访问http://localhost:3000/是一片空白，要如何解决？
环境是：windows10，公司内部离线环境
花了几天时间还未解决，求助！

**Comment by 13829386012** [comment]
> @songquanpeng 你好,我也是执行npm run build命令编译打包的，运行./one-api --port 3000 --log-dir ./log后 ![run](https://private-user-images.githubusercontent.com/40138671/329978317-644c6982-5e0c-4437-8563-583cedf6b322.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTk3MzksIm5iZiI6MTcxNTY1OTQzOSwicGF0aCI6Ii80MDEzODY3MS8zMjk5NzgzMTctNjQ0YzY5ODItNWUwYy00NDM3LTg1NjMtNTgzY2VkZjZiMzIyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0MDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NWI1OTc2OTRjMGJiZGJjMTUyZGRmYTJhZmNlMTMxN2U5YTNhZjJkOTQwYzhkODM1MDFmMTFhYjM0ZGU5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ua4wn7b5IRKGNezsEcKNBWrq-ksjhwDO4fPRCyQiazQ) 卡在token encoders initialized这里 访问[http://localhost:3000/是一片空白，要如何解决？](http://localhost:3000/%E6%98%AF%E4%B8%80%E7%89%87%E7%A9%BA%E7%99%BD%EF%BC%8C%E8%A6%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F) 环境是：windows10，公司内部离线环境 花了几天时间还未解决，求助！

已经解决！

**Comment by kingkingkids** [comment]
请问怎么解决啊？

**Comment by 13829386012** [comment]
> 请问怎么解决啊？

看下部署文件，有个前端需要启动yarn start，要改一下端口号以免冲突

**Comment by Noahhhhha** [comment]
救命，能不能帮帮，部署文件在哪里~

是说这个吗https://github.com/songquanpeng/one-api/blob/main/.github/workflows/windows-release.yml

我也是执行npm run build命令编译打包的，运行./one-api --port 3000 --log-dir ./log

**Comment by bluesule** [comment]
windows环境手动编译部署，执行npm run build 后报错
![image](https://github.com/user-attachments/assets/90586f8d-0f8e-441b-a47b-d320a46fd999)
查看web/default/package.json 文件可以看到 
![image](https://github.com/user-attachments/assets/1dd86009-73b3-484e-a08d-a5baaba91e42)
手动将web/default/build 文件夹下文件移到 web/build/default 文件夹下即可
