### ISSUE TITLE
国内模型messages.role建议

### ISSUE THREAD

**Issue by fengjisheng** [songquanpeng/one-api#1079]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
大部分国内模型messages.role都已经支持system, 只有少数支持, 某些场景比如角色扮演, 需要系统角色指令 +上下文回答.
看代码部分渠道都做了角色转换, 导致无法锁定系统角色正确的回答问题. 总是跳出规则变成其它不相关的答案.

百度文心, 智普AI V4版, 讯飞星火3.5  这些都已经支持system角色参数.

我觉得有些不支持 system 参数的, 因为是中转系统, 都是API调用,  自己写system转换, 这样灵活些.

**Comment by songquanpeng** [comment]
是的这些当他们支持后需要下掉之前的兼容措施，谢谢反馈今天处理

**Comment by songquanpeng** [comment]
百度文心现在支持了么？为什么我测试还是不行

**Comment by fengjisheng** [comment]
> 百度文心现在支持了么？为什么我测试还是不行

已经支持了. 我看了下官方文档, 不是openai message.role.system 结构, 而是独立参数. 看来还是要做这个兼容.
![image](https://github.com/songquanpeng/one-api/assets/7992420/0e45572a-a92c-4311-8aea-4a033bf51183)

**Comment by songquanpeng** [comment]
好的下次处理

**Comment by songquanpeng** [comment]
修复了哈
