### ISSUE TITLE
Add Support to Claude 3

### ISSUE THREAD

**Issue by JamesFlare1212** [songquanpeng/one-api#1080]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

支持Claude 3系列API，https://twitter.com/AnthropicAI/status/1764653830468428150

文档已经释出，似乎格式有所变动，此外Claude 3支持Vision功能。如果需要API调试我乐意提供

**Comment by lqhl** [comment]
同求。

claude 3 只支持 antropic 的 message API，而 one-api 用的是 text completion API：
https://docs.anthropic.com/claude/reference/migrating-from-text-completions-to-messages

**Comment by ImYrS** [comment]
提供一些信息供开发者和贡献者参考:

- 不支持 Completions API, 要用 [Message API](https://docs.anthropic.com/claude/reference/messages_post) (`/v1/messages`), 但大部分参数跟之前一样.
- Vision 的传参和 OpenAI 有少许区别
- system role 在 Message API 中被移除, 使用 `system: content` 代替 (参考 API 文档).

> [!TIP]
> 贡献者需要 Claude API Key 用于临时调试可[联系我](https://t.me/ImYrS)

**Comment by ahkimkoo** [comment]
+1 期待

**Comment by asakuras** [comment]
同求😊

**Comment by deepziyu** [comment]
目前通过 text completion API 调用 claude3模板报错如下：
```
{
    "error": {
        "message": "\"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead. (request id: 20240305140****************)",
        "type": "invalid_request_error",
        "param": "",
        "code": null
    }
}
```

**Comment by TangSY** [comment]
+1

**Comment by songquanpeng** [comment]
预期周末处理

**Comment by ZhangTianrong** [comment]
> 已经支持

v0.6.1 支持吗？测试似乎还是
```
API Error: Status Code 400, {"error":{"message":"\"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead. (request id: 2024030821332639501441300310184)","type":"invalid_request_error","param":"","code":null}}
```

**Comment by ImYrS** [comment]
> 自定义sonnet模型还是不行呀

更新到 v0.6.2-alpha.2 即可
