### ISSUE TITLE
增加支持 Groq 模型

### ISSUE THREAD

**Issue by jtsang4** [songquanpeng/one-api#1087]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
支持 https://groq.com/ 的模型

**应用场景**
目前 Groq 的模型免费且性能非常好

**Comment by JamesFlare1212** [comment]
groq的API兼容openai格式，渠道API地址写 https://api.groq.com/openai 即可

**Comment by jtsang4** [comment]
> groq的API兼容openai格式，渠道API地址写 https://api.groq.com/openai 即可

👍 确实可以用，估记我昨天测试的时候填错了

**Comment by KrabsWong** [comment]
> groq的API兼容openai格式，渠道API地址写 https://api.groq.com/openai 即可

请问是选择自定义渠道然后设置 baseUrl 为 https://api.grpq.com/openai 吗？
我试了下这个方案，测试接口提示

> 错误：status code 404: The model `gpt-3.5-turbo` does not exist or you do not have access to it.

也尝试了直接选择 openai 的渠道类型，然后代理地址设置为 https://api.groq.com/openai 也是报一样错误。
是不是那里设置不太对呀？

**Comment by jtsang4** [comment]
> > groq的API兼容openai格式，渠道API地址写 https://api.groq.com/openai 即可
> 
> 请问是选择自定义渠道然后设置 baseUrl 为 https://api.grpq.com/openai 吗？ 我试了下这个方案，测试接口提示
> 
> > 错误：status code 404: The model `gpt-3.5-turbo` does not exist or you do not have access to it.
> 
> 也尝试了直接选择 openai 的渠道类型，然后代理地址设置为 https://api.groq.com/openai 也是报一样错误。 是不是那里设置不太对呀？

你需要配置模型为 `mixtral-8x7b-32768` 或 `llama2-70b-4096`。

**Comment by KrabsWong** [comment]
> > > groq的API兼容openai格式，渠道API地址写 https://api.groq.com/openai 即可
> > 
> > 
> > 请问是选择自定义渠道然后设置 baseUrl 为 https://api.grpq.com/openai 吗？ 我试了下这个方案，测试接口提示
> > > 错误：status code 404: The model `gpt-3.5-turbo` does not exist or you do not have access to it.
> > 
> > 
> > 也尝试了直接选择 openai 的渠道类型，然后代理地址设置为 https://api.groq.com/openai 也是报一样错误。 是不是那里设置不太对呀？
> 
> 你需要配置模型为 `mixtral-8x7b-32768` 或 `llama2-70b-4096`。

对的，配置了这个模型。下面截图是尝试的两种方式的配置。
<img width="1118" alt="image" src="https://github.com/songquanpeng/one-api/assets/12368943/04a6ac89-25e4-4c39-8d56-ede692c24df8">

<img width="1144" alt="image" src="https://github.com/songquanpeng/one-api/assets/12368943/3e70f708-789a-4ecb-8496-09bb66f56d54">

**Comment by jiz4oh** [comment]
<img width="550" alt="image" src="https://github.com/songquanpeng/one-api/assets/41264693/7fadb404-2e52-479d-a749-5ae7c0825d32">

@KrabsWong  像这样即可，在使用的时候在对应的客户端填入 custom model name `mixtral-8x7b-32768`

**Comment by KrabsWong** [comment]
> <img alt="image" width="550" src="https://private-user-images.githubusercontent.com/41264693/310386387-7fadb404-2e52-479d-a749-5ae7c0825d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTM2MDQsIm5iZiI6MTcwOTcxMzMwNCwicGF0aCI6Ii80MTI2NDY5My8zMTAzODYzODctN2ZhZGI0MDQtMmU1Mi00NzlkLWE3NDktNWFlN2MwODI1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4MjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmZmOWJhNTAyY2FlMTAwMzU1OWExNzU2MDNmYmUwNTE3Zjg0YzBlMDQyNDk4ZTI4MWI2NjY4NmFjYjA4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJaMmCIR6o9JhTZHG25n_zy34Xe9RGMUmPm5Jj9My_c">
> @KrabsWong 像这样即可，在使用的时候在对应的客户端填入 custom model name `mixtral-8x7b-32768`

明白了，感谢

**Comment by yonmnm** [comment]
> <img alt="image" width="550" src="https://private-user-images.githubusercontent.com/41264693/310386387-7fadb404-2e52-479d-a749-5ae7c0825d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTczNjIsIm5iZiI6MTcwOTg1NzA2MiwicGF0aCI6Ii80MTI2NDY5My8zMTAzODYzODctN2ZhZGI0MDQtMmU1Mi00NzlkLWE3NDktNWFlN2MwODI1ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAwMTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZTI1ZTE4ZTJiZWViYTllNjIyOTI5MDg2NDQ0ZTIzMGU1M2NjYWMxYjA5ZWQ0N2I5YTQ2NGM3YjM4N2IyYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGyOGBoooP7BXdGRDZS7OZ52M_rAhyj-CKvpZXA414k">
> @KrabsWong 像这样即可，在使用的时候在对应的客户端填入 custom model name `mixtral-8x7b-32768`
使用第三方客户端，出现这样的错误：（直接填写Groq的key到客户端就能正常使用）
"error": {
    "message": "`tools` is not supported with this model (request id: 2024030808155972780750603165139)",
    "type": "invalid_request_error",
    "param": "",
    "code": null

**Comment by ImYrS** [comment]
> @jiz4oh 使用第三方客户端，出现这样的错误：（直接填写Groq的key到客户端就能正常使用） "error": { "message": "`tools` is not supported with this model (request id: 2024030808155972780750603165139)", "type": "invalid_request_error", "param": "", "code": null

Groq 使用的 mixtral 和 llama2 不支持插件调用
