### ISSUE TITLE
请求支持星火 function call模式。可以对齐 gpt function 结构。

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#1088]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by yc-2503** [comment]
+1
SemanticKernel 通过 oneapi 调用 星火大模型的时候 KernelFunction 无法触发

**Comment by pangjianxin** [comment]
目前one-api没有对任何一家llm做function call的对接，这是这个伟大项目的一个比较遗憾的地方

**Comment by nathubs** [comment]
很期待支持function callng tool calling
