### ISSUE TITLE
text-davinci-002-render-sha-mobile 不支持，并调用后会导致one-api重启

### ISSUE THREAD

**Issue by ccyuvin** [songquanpeng/one-api#110]
POST /v1/chat/completions

[FATAL] 2023/05/21 - 02:52:29 | [failed to get token encoder for model text-davinci-002-render-sha-mobile: no encoding for model text-davinci-002-render-sha-mobile] 
[SYS] 2023/05/21 - 02:52:30 | One API v0.3.2 started 
[SYS] 2023/05/21 - 02:52:30 | SQL_DSN not set, using SQLite as database 
[SYS] 2023/05/21 - 02:52:30 | REDIS_CONN_STRING not set, Redis is not enabled 

ChatGPT-Next-Web 项目前端可以选择模型text-davinci-002-render-sha-mobile，选择后调用会返回502状态码，并且会自动重启。
![image](https://github.com/songquanpeng/one-api/assets/85599321/d3fadea4-94e0-44ac-835b-4bd29f8f3564)

**Comment by songquanpeng** [comment]
感谢反馈，我调查一下，重启这个肯定是什么地方没做好错误处理。

**Comment by songquanpeng** [comment]
已修复，已推送 `v0.3.3-alpha.1`
