### ISSUE TITLE
【模型重定向】

### ISSUE THREAD

**Issue by Whichbfj28** [songquanpeng/one-api#1108]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [ x ] 我已确认我已升级到最新版本
+ [ x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
 关于模型重定向的，看了一些文章。但是我觉得这逻辑对于很多用户来说都会觉得莫名其妙。
**目前one版本正确使用方式【以gemini为例】假如你的客户端只支持gpt-3.5-turbo，想重定向到gemini**
1、那么渠道的地方，模型写上gpt-3.5-turbo、gemini-pro #【一定要填上gpt-3.5-turbo】
2、重定向代码：
{
  "gpt-3.5-turbo": "gemini-pro"
}

**问题：**
1：既然是编辑渠道信息的，那么模型选项的地方就应该对应这个渠道的模型。比如gemini对应的就是gemini-pro。
2、现在要求模型的地方填写上客户端发送模型gpt-3.5-turbo。这很莫名其妙。【路径变成了：客户端gpt-3.5-turbo---oneapi渠道选项模型gpt-3.5-turbo--oneapi重定向模型到gemini---oneapi的渠道选项模型gemini---google服务器】
3、正常逻辑应该是：客户端gpt-3.5-turbo-----oneapi的gpt-3.5-turbo模型重定向到gemini-----google服务器】

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/47915665/8b739c7a-27d2-40b8-b8bd-78d8b7adbbbd)
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
没看到现在有什么问题，你是想模型列表里不必选择 gpt-3.5-turbo 是么？

**Comment by Whichbfj28** [comment]
是的。因为这个gpt-3.5-turbo这个模型不是 gemini这个渠道拥有的模型。
