### ISSUE TITLE
Model Ratios

### ISSUE THREAD

**Issue by DanFosing** [songquanpeng/one-api#111]
I have a question about model ratios:
var ModelRatio = map[string]float64{
	"gpt-4":                   15,
	"gpt-4-0314":              15,
	"gpt-4-32k":               30,
	"gpt-4-32k-0314":          30,
	"gpt-3.5-turbo":           1,
	"gpt-3.5-turbo-0301":      1,
	"text-ada-001":            0.2,
	"text-babbage-001":        0.25,
	"text-curie-001":          1,
	"text-davinci-002":        10,
	"text-davinci-003":        10,
	"text-davinci-edit-001":   10,
	"code-davinci-edit-001":   10,
	"whisper-1":               10,
	"davinci":                 10,
	"curie":                   10,
	"babbage":                 10,
	"ada":                     10,
	"text-embedding-ada-002":  0.2,
	"text-search-ada-doc-001": 10,
	"text-moderation-stable":  10,
	"text-moderation-latest":  10,
}

For whisper it's a price for minute right? and with text-search-ada, text-moderation it's for token? And second question what is that ada, babbage, curie, davinci models? Are those instructgpt or text models (and if text models why is there already for example text-ada-001 ? Also there is no dall-e pricing and no embedding pricing other than ada-002. And no code cushman pricing and code-davinci pricing (there is only edit pricing)

**Comment by songquanpeng** [comment]
It's doesn't support whisper, text-search-ada and many other models currently. And if you calll the coresponding API, it will tell you it's not implemented.
