### ISSUE TITLE
用阿里的向量模型(text-embedding-v2),在后台使用明细里面没有使用明细记录

### ISSUE THREAD

**Issue by hejuntt1014** [songquanpeng/one-api#1110]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
用阿里的向量模型,在后台使用明细里面没有记录,openai的是有使用记录的
![image](https://github.com/songquanpeng/one-api/assets/19259565/f8e3a3e0-6a3e-4d80-8c93-5efbdb30066e)
![image](https://github.com/songquanpeng/one-api/assets/19259565/dca7d090-c200-4c1d-925b-5b6045690a6f)

请求代码:
curl http://127.0.0.1:5900/v1/embeddings \
  -H "Authorization: Bearer sk-" \
  -H "Content-Type: application/json" \
  -d '{ 
    "input": "The food was delicious and the waiter...", 
    "model": "text-embedding-v2", 
    "encoding_format": "float" 
  }'
请求结果是成功返回了向量数据的,但是后台和logs都没有相关记录,但是如果请求openai的会有记录
![image](https://github.com/songquanpeng/one-api/assets/19259565/2885c6ad-91f3-45de-a54d-ef2db39d3039)

**Comment by ye4293** [comment]
这个是不是默认没有补全 text模型 和openai的一样

**Comment by hejuntt1014** [comment]
> 这个是不是默认没有补全 text模型 和openai的一样

我这里整条消费记录都没有

**Comment by xfworld** [comment]
感觉是不支持

**Comment by fslongjin** [comment]
+1
