### ISSUE TITLE
用messages.stream的方式转发Anthropic的claude key

### ISSUE THREAD

**Issue by xuyang-stack** [songquanpeng/one-api#1115]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望兼容如下调用
import anthropic
client = anthropic.Anthropic(api_key = api_key)
with client.beta.messages.stream(
                        max_tokens=max_tokens,
                        messages=messages,
                        model="claude-instant-1.2", # "claude-2.1"
                        temperature=temperature,
                        top_p=top_p,
                        top_k=top_k,
                    ) as stream:
                        for text in stream.text_stream:
                            print(f"{text}")
**应用场景**
用于原生claude key

**Comment by songquanpeng** [comment]
你应该用 OpenAI 的库进行调用
