### ISSUE TITLE
希望增加日志文件可以选择不添加上启动时的日期，同时支持重新打开日志文件的信号 SIGHUP

### ISSUE THREAD

**Issue by linzeliang1222** [songquanpeng/one-api#1116]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
日志目前是oneapi-yyyyMMdd格式，我觉得可以增加选择不需要后面的日期，因为我发现后面拼接的日期也只是从启动时候生成的，后续都是写入到这个文件，除非重启才会生成当前日期的日志文件，这样来说有点奇怪，因此我想只生成一个 oneapi.log 文件。
**应用场景**
支持由用户手动切割日志，我可以使用logrotate等工具手动切割日志，然后发送 SIGHUP 信号重新打开日志文件。

**Comment by songquanpeng** [comment]
有道理，已经修改了
