### ISSUE TITLE
one-api无法使用阿里的text-embedding-v2

### ISSUE THREAD

**Issue by HelloEveryonehh** [songquanpeng/one-api#1117]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
无法使用text-embedding-v2
**复现步骤**
自己添加模型text-embedding-v2，然后按照openai的embedding格式去curl，把model换成text-embedding-v2，但是返回结果是text-embedding-v1，阿里的后台也显示text-embedding-v1被使用
**预期结果**
使用text-embedding-v2

**Comment by HelloEveryonehh** [comment]
补充一下:当我在渠道中只设置text-embedding-v2，删除text-embedding-v1，通过如下调用，服务器返回的结果是text-embedding-v1，但是one-api的日志显示的是text-embedding-v2
![image](https://github.com/songquanpeng/one-api/assets/110333012/40f8f7fd-7071-476d-b266-c65e7daa3d01)
![image](https://github.com/songquanpeng/one-api/assets/110333012/a50ca364-46be-4e49-9390-8ec0704208a1)
![image](https://github.com/songquanpeng/one-api/assets/110333012/d905f1e3-a763-4cc6-9af1-e17e9b061846)

**Comment by xfworld** [comment]
你用的哪个版本？ 0.6.1 么？

**Comment by HelloEveryonehh** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [songquanpeng/one-api] one-api无法使用阿里的text-embedding-v2 (Issue #1117)




 
你用的哪个版本？ 0.6.1 么？

**Comment by xfworld** [comment]
唉，估计要等下个版本才能修复了

**Comment by zxwmol** [comment]
咨询一下，阿里的通义千问渠道密钥填的啥？使用阿里云官方的大模型服务。
![image](https://github.com/songquanpeng/one-api/assets/38974244/873284b3-8676-468c-9ab4-9d8370bce594)

**Comment by duantuidp** [comment]
> 咨询一下，阿里的通义千问渠道密钥填的啥？使用阿里云官方的大模型服务。 ![image](https://private-user-images.githubusercontent.com/38974244/312777630-873284b3-8676-468c-9ab4-9d8370bce594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTU4NTksIm5iZiI6MTcxMDU5NTU1OSwicGF0aCI6Ii8zODk3NDI0NC8zMTI3Nzc2MzAtODczMjg0YjMtODY3Ni00NjhjLTlhYjQtOWQ4MzcwYmNlNTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEzMjU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YTk0M2E4MTU3ZGMwMjg5OTFiYmY2OGQ3NDAzZWY3MzlmNzNjNmUzZjlhZDdmMjg4YmU3YTcyNTYwNWFhZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nYxToIhfI9z0HV_EisPUSP0OFp7TIWA0I26esDWCgv0)

阿里云控制台那边有
![image](https://github.com/songquanpeng/one-api/assets/127709994/0c92beeb-7e5e-4a8d-9fcc-7783b084773a)

**Comment by c121914yu** [comment]
+1

**Comment by TuShengTao** [comment]
`import os
from dotenv import load_dotenv
import requests

# 加载 .env环境变量
load_dotenv()

class EmbeddingClient:
    def __init__(self, api_key, api_url):
        self.api_key = api_key
        self.api_url = api_url
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": "Bearer {}".format(self.api_key)
        }

    def get_embedding(self, text, model):
        data = {
            "input": text,
            "model": model
        }
        response = requests.post(self.api_url, headers=self.headers, json=data)
        if response.status_code == 200:
            response_data = response.json()
            return response_data["data"][0]["embedding"]
        else:
            raise Exception("Error: {} - {}".format(response.status_code, response.text))


OPENAI_PROXY = os.environ.get('OPENAI_PROXY')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
embedding_client = EmbeddingClient(api_key=OPENAI_API_KEY, api_url=OPENAI_PROXY + "/v1/embeddings")
text = "香蕉"
embedding = embedding_client.get_embedding(text=text, model="text-embedding-v2")
# embedding = embedding_client.get_embedding(text=text, model="text-embedding-ada-002")
print(embedding)
`
> 目前自己这样解决，其他embedding应该也可以

**Comment by HelloEveryonehh** [comment]
> ```python
> import os
> from typing import List, Optional
> 
> from dotenv import load_dotenv
> import requests
> 
> 
> class EmbeddingClient:
>     def __init__(self, api_key, api_url, model):
>         self.api_key = api_key
>         self.api_url = api_url
>         self.model = model
>         self.headers = {
>             "Content-Type": "application/json",
>             "Authorization": "Bearer {}".format(self.api_key)
>         }
> 
>     def embed_query(self, text: str) -> List[float]:
>         data = {
>             "input": text,
>             "model": self.model
>         }
>         response = requests.post(self.api_url, headers=self.headers, json=data)
>         if response.status_code == 200:
>             response_data = response.json()
>             return response_data["data"][0]["embedding"]
>         else:
>             raise Exception("Error: {} - {}".format(response.status_code, response.text))
> 
>     def embed_documents(self, texts: List[str], chunk_size: Optional[int] = 0) -> List[List[float]]:
>         data = {
>             "input": texts,
>             "model": self.model
>         }
>         response = requests.post(self.api_url, headers=self.headers, json=data)
>         if response.status_code == 200:
>             response_data = response.json()
>             result = []
>             for item in response_data["data"]:
>                 result.append(item["embedding"])
>             return result
>         else:
>             raise Exception("Error: {} - {}".format(response.status_code, response.text))
> 
> 
> if __name__ == '__main__':
>     # 加载 .env环境变量
>     load_dotenv()
>     OPENAI_PROXY = os.environ.get('OPENAI_PROXY')
>     OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
>     embedding_client = EmbeddingClient(api_key=OPENAI_API_KEY, api_url=OPENAI_PROXY + "/v1/embeddings", model="text-embedding-v2")
>     text = "香蕉"
>     r = embedding_client.embed_query(text=text)
>     print(r)
> 
>     # texts = ["香蕉", "苹果"]
>     # r = embedding_client.embed_documents(texts=texts)
>     # print(r)
> ```
> 
> > 目前自己这样解决，其他embedding 模型应该也可以

您好，打扰您一下，请问你这个是怎么用呢，我想变成OPENAI格式的API调用text-embedding-v2，需要自己改成API的格式是吗
