### ISSUE TITLE
支持失败重试以应对 connection loss 等问题

### ISSUE THREAD

**Issue by thucsc** [songquanpeng/one-api#112]
[SYS] 2023/05/22 - 05:50:15 | Relay error (channel #1): Post "https://xx.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview": net/http: cannot rewind body after connection loss

**Comment by thucsc** [comment]
> 我检查一下哈。

刷twitter这样的，有非常多的翻译请求的情况

**Comment by songquanpeng** [comment]
是的，讲道理请求过多应该 429，不应该报这个错。

**Comment by songquanpeng** [comment]
之前有可能是 Azure 的问题，请问现在该问题还存在么？

**Comment by thucsc** [comment]
> 之前有可能是 Azure 的问题，请问现在该问题还存在么？

那会不会是我的nginx的设置问题，有没有参考配置

**Comment by songquanpeng** [comment]
README 就有哈。

**Comment by songquanpeng** [comment]
已经支持。
