### ISSUE TITLE
重构后版本出现莫名奇妙的重定向问题

### ISSUE THREAD

**Issue by lfglfg11** [songquanpeng/one-api#1120]
**问题描述**
部署方式：docker部署，mysql数据库方式
遇到回复稍慢的问题，有较大概率出现重试情况，会多次重复请求上游。
确认我的重试次数设置为0且数据库中retry值也为0。
可以排除上游问题，因为我没经过oneapi直接用上游地址没有重试现象，且前端换过其他项目也能复现重试，流式和非流式前端都能复现。
重试时，调用日志只能看到一条记录，但在服务器日志能看到两条请求记录。

**复现步骤**
复杂的问题，需要较长时间回答的问题。

**相关截图**
![8426b5a6678f95a8423b641716047af](https://github.com/songquanpeng/one-api/assets/32725664/08c7ac7f-bfb2-4e5a-99be-4dee1f152424)
![image](https://github.com/songquanpeng/one-api/assets/32725664/b9c0e96b-466e-4531-949c-faeb59beb2e1)
【设置重试及数据库】

![ab9e2d23ada2fa5d80d10b1739f9b68](https://github.com/songquanpeng/one-api/assets/32725664/8d7a2e70-5ac2-4775-afe3-da4819ccf6df)
【服务器日志】

**Comment by songquanpeng** [comment]
那这就很奇怪了，设置为 0 是不会重试的：
![image](https://github.com/songquanpeng/one-api/assets/39998050/a67e1683-5c40-4080-b701-afe6f341c657)

你确定不是上游在重试？

**Comment by lfglfg11** [comment]
是很奇怪，也不知道哪里的问题，但是上游是我自己的，我不经过oneapi直接直连就不会出现重试

**Comment by lfglfg11** [comment]
> 那这就很奇怪了，设置为 0 是不会重试的： ![image](https://private-user-images.githubusercontent.com/39998050/311522449-a67e1683-5c40-4080-b701-afe6f341c657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTAxMTksIm5iZiI6MTcxMDE0OTgxOSwicGF0aCI6Ii8zOTk5ODA1MC8zMTE1MjI0NDktYTY3ZTE2ODMtNWM0MC00MDgwLWI3MDEtYWZlNmYzNDFjNjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNzA0OTJmMDU1MDk5OTRjNTU1MzFmNjk2NTMxZGI4MTQ2ZTNmOTBhODE4NGZmODZkMzJlYmU5MmVmZjA3NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z8sbRCMGvzWp_k0JjnSkvahUd9G7qgshAz29yuHKHRk)
> 
> 你确定不是上游在重试？

我大概找到问题了，因为上游回复内容较多，时间较长，然后oneapi有个超时时间在代码里是60秒，因为不是流式，60秒没返回后就会超时，60秒超时后前端没收到数据就返回错误或重试，能否改一下这个时间？
![image](https://github.com/songquanpeng/one-api/assets/32725664/ff9e2896-89ba-4c40-ad21-5ff2229d3bff)
【oneapi代码】
![image](https://github.com/songquanpeng/one-api/assets/32725664/1bd1e6a2-84e3-404c-8ad2-42bcad766f23)
【54:46秒问的，55:46秒超过1分钟超时，而此时上游还在回答问题还没回答完，系统就超时返回错误了】

**Comment by lfglfg11** [comment]
> 那这就很奇怪了，设置为 0 是不会重试的： ![image](https://private-user-images.githubusercontent.com/39998050/311522449-a67e1683-5c40-4080-b701-afe6f341c657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjY3OTUsIm5iZiI6MTcxMDE2NjQ5NSwicGF0aCI6Ii8zOTk5ODA1MC8zMTE1MjI0NDktYTY3ZTE2ODMtNWM0MC00MDgwLWI3MDEtYWZlNmYzNDFjNjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE0MTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOGEzM2I0NmMwOTU2NWY5NDI5NmE4N2ViYzJlNzcwM2UwZTBiNTY4MjRjNjNmNzNmNWFmMDAyYjQyNGJkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WwLNy2L-daeDp_gUwFvcorbWN04Egq2fJORePjrqZJA)
> 
> 你确定不是上游在重试？

啊，我大概找到问题所在了，不是前端问题也不是上游问题，也不是oneapi的问题，而是NGINX反代问题，域名加了SSL反代到3000端口，NGINX默认超时是60秒……改好后没有重试现象了！
问下大佬，我直接改NGINX和设置环境变量RELAY_TIMEOUT是不是一回事啊？
![image](https://github.com/songquanpeng/one-api/assets/32725664/575e297b-2c8e-4938-9f28-23ba8d22ea99)
