### ISSUE TITLE
请求增加 `重置模型倍率` 选项！

### ISSUE THREAD

**Issue by piwawa** [songquanpeng/one-api#1121]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

在 `运营设置 - 倍率设置 - 模型倍率` 中添加一个按钮，一键重置为默认倍率。

**应用场景**

每次更新后新模型的倍率都没有自动添加，模型倍率还是之前的设置，得手动把倍率一个个填入，非常麻烦，如果能一键更新模型倍率就好了

**Comment by fatwang2** [comment]
+1，好难受

**Comment by songquanpeng** [comment]
新版本已经会自动添加了

**Comment by fatwang2** [comment]
您好，代码更新报错，当然也有可能是我是从sqlite手动迁移到mysql之后，跟新版本的兼容问题。之前的版本都可以使用
```
2024/03/10 16:48:32 /build/model/main.go:91 Error 1170: BLOB/TEXT column 'key' used in key specification without a key length

[1.807ms] [rows:0] ALTER TABLE `channels` MODIFY COLUMN `key` text
```

**Comment by fatwang2** [comment]
> 您好，代码更新报错，当然也有可能是我是从sqlite手动迁移到mysql之后，跟新版本的兼容问题。之前的版本都可以使用
> 
> ```
> 2024/03/10 16:48:32 /build/model/main.go:91 Error 1170: BLOB/TEXT column 'key' used in key specification without a key length
> 
> [1.807ms] [rows:0] ALTER TABLE `channels` MODIFY COLUMN `key` text
> ```

我自己改mysql数据库后解决了
