### ISSUE TITLE
azure openAI 的tts 和 shisper模型404问题

### ISSUE THREAD

**Issue by huanmengmie** [songquanpeng/one-api#1125]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
你好，我使用 V0.6.1版本的docker镜像，配置Azure openAI 的 tts 和 whisper模型，一直提示404。chat模型是可以正常使用的
我查看了项目代码发现是有相关路由的，请问是还不支持Azure openAI的嘛？

**预期结果**
正常使用
**相关截图**
如果没有的话，请删除此节。
**版本信息**
![image](https://github.com/songquanpeng/one-api/assets/26222630/6f944cb1-8661-4e12-8e9d-726febd26bdb)
**个人配置**
![%JC@JNHZ7Z$_3N18AID5$CF](https://github.com/songquanpeng/one-api/assets/26222630/1fb421cd-f133-4be4-9659-6c26e499b6b9)
**测试**
![image](https://github.com/songquanpeng/one-api/assets/26222630/d073ce49-878f-45a0-a740-5274b1293204)
![@C}4C0ADG5HQIF1WA_0E4$H](https://github.com/songquanpeng/one-api/assets/26222630/ac32e38a-fa3a-4a0f-bf74-4f311981181d)

**Comment by huanmengmie** [comment]
我看到 0.5.9版本时支持了 whisper模型，但是我这边测试还是404，api version 确认无误，相关截图如下。
![image](https://github.com/songquanpeng/one-api/assets/26222630/c819dbad-50e4-4f8a-b09d-e8a06bbaf3db)
![image](https://github.com/songquanpeng/one-api/assets/26222630/ffd95166-92b9-4609-9cb3-2a7e3fcd1d79)
![image](https://github.com/songquanpeng/one-api/assets/26222630/e90ae882-2b6c-4e89-8cab-6d3ccd981c01)

**Comment by caoliy3567** [comment]
怎么解决的，大哥，这个问题。

**Comment by koalawangyang** [comment]
我也遇到相同的问题.

INFO:     101.132.57.195:0 - "POST /audio/api/v1/speech HTTP/1.1" 404 Not Found
ERROR [apps.audio.main] 404 Client Error: Not Found for url: https://one-api.****.com/v1/audio/speech
Traceback (most recent call last):
  File "/app/backend/apps/audio/main.py", line 218, in speech
    r.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://one-api.****.com/v1/audio/speech

**Comment by seven-yu** [comment]
问题解决了吗？
