### ISSUE TITLE
建议作者 增加 deepl翻译渠道

### ISSUE THREAD

**Issue by tongxiaofeng1** [songquanpeng/one-api#1126]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
接入deepl 用于翻译，相较于gpt3.5 更便宜，更准确。请作者参考，谢谢
**应用场景**
这个是官网的接入方式 一 ： https://www.deepl.com/docs-api
接入方式二可以参考这个放肆 ：https://github.com/xiaozhou26/deeplx-pro
谢谢🙏

**Comment by songquanpeng** [comment]
已经支持
