### ISSUE TITLE
令牌生成的提交按钮高亮显示

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#113]
![image](https://github.com/songquanpeng/one-api/assets/11790369/266bd106-df3e-4dcf-ae54-945215680d9b)

提交按钮不太显眼，加个颜色应该会好一些

**Comment by songquanpeng** [comment]
颜色调整后就和其他页面不统一了，或许应该换到下一行。

**Comment by songquanpeng** [comment]
其实我感觉还好。

**Comment by Aiayw** [comment]
![image](https://github.com/songquanpeng/one-api/assets/11790369/3adb1798-e9a3-49f3-9d0f-520ed889d029)
这样修改呢？

主要是移动端看着确实有点乱...
![image](https://github.com/songquanpeng/one-api/assets/11790369/757394a2-96aa-4259-a182-79b4fe9fb863)

**Comment by Aiayw** [comment]
还发现一个不太影响的问题，访问 https://openai.justsong.cn/user/add/ 和 https://openai.justsong.cn/token/add 类似这样的参数地址，未登录的情况没有跳转到登录，而是渲染了对应前端页面

**Comment by songquanpeng** [comment]
没有怎么考虑移动端的布局，这样确实会好一些。

之后还是给所有提交按钮换颜色吧。

移动端的样式，尤其是那个表格的样式，需要等主要功能就绪后才有精力去做适配。

**Comment by songquanpeng** [comment]
> 还发现一个不太影响的问题，访问 https://openai.justsong.cn/user/add/ 和 https://openai.justsong.cn/token/add 类似这样的参数地址，未登录的情况没有跳转到登录，而是渲染了对应前端页面

因为我没给加 private 属性，正常情况下不会在未登录的情况下访问到这两个界面。

**Comment by Aiayw** [comment]
嗯嗯，辛苦大佬。
移动端主要是用户使用的更多一点，如果管理员个人使用，倒是不太重要。

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/ff5fef0b-8d3d-41ea-a6e8-359b17201065)

**Comment by Aiayw** [comment]
很棒~

**Comment by songquanpeng** [comment]
那个提交按钮上面的 margin 我又调小了一点，就不贴图了，马上推送。

**Comment by songquanpeng** [comment]
不过你那个布局确实更好看一些。

**Comment by Aiayw** [comment]
那下次推送的时候交换一下布局就行~
确实都挤在一起有点混乱，UI这种迭代都随着功能慢慢改就行，改着改着就好看了。

**Comment by songquanpeng** [comment]
已经改了。
