### ISSUE TITLE
claude-3-opus 不稳定

### ISSUE THREAD

**Issue by QAbot-zh** [songquanpeng/one-api#1133]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
claude-3-opus模型使用不稳定，容易出现提示和补全都为空的情况。
日志没有记录输入输出所以不能排查oneapi这边接收的数据对不对。
![image](https://github.com/songquanpeng/one-api/assets/40236765/5e0664c3-afa2-4f38-a914-d3784742ae5f)

这是oneapi日志里quota为空的记录：
```
[INFO] 2024/03/12 - 22:55:03 | 2024031222550216318868522781478 | user 1 has enough quota 99712153, trusted and no need to pre-consume 
[INFO] 2024/03/12 - 22:55:05 | 2024031222550216318868522781478 | record consume log: userId=1, channelId=4, promptTokens=0, completionTokens=0, modelName=claude-3-opus-20240229, tokenName=克劳德-vercel-nextweb, quota=0, content=模型倍率 7.50，分组倍率 1.00，补全倍率 5.00 
[INFO] 2024/03/12 - 23:06:35 | 2024031223063367478521271128374 | user 1 has enough quota 99712153, trusted and no need to pre-consume 
[INFO] 2024/03/12 - 23:06:37 | 2024031223063367478521271128374 | record consume log: userId=1, channelId=4, promptTokens=0, completionTokens=0, modelName=claude-3-opus-20240229, tokenName=克劳德-vercel-nextweb, quota=0, content=模型倍率 7.50，分组倍率 1.00，补全倍率 5.00 
```

调用方式为 oneapi 转完在 nextweb ui 里调用，控制台抓取数据能看到消息是填充到payload里的：

![image](https://github.com/songquanpeng/one-api/assets/40236765/bb37288e-16e0-45ab-9164-28fe21fcde48)

**Comment by QAbot-zh** [comment]
ps: 不是模型名称调用错误，我在oneapi设置了重定向：
![image](https://github.com/songquanpeng/one-api/assets/40236765/c1c6b75e-8fc8-4d38-b552-41f61e308d67)
即使使用原始名称，第二轮对话仍然出现无法响应，提示和补全为空：
![image](https://github.com/songquanpeng/one-api/assets/40236765/f9e8d547-c571-4e42-91c1-7191c8377791)
![image](https://github.com/songquanpeng/one-api/assets/40236765/6601a539-67b8-4c14-9acf-db25c520348d)

**Comment by songquanpeng** [comment]
麻烦发一下完整的请求体

**Comment by QAbot-zh** [comment]
> 麻烦发一下完整的请求体

这是控制台抓取的payload，跟内容好像没太大关系，问题来了甚至发个 hi 都卡不出来：
```
{"messages":[{"role":"user","content":"hi"}],"stream":true,"model":"claude-3-opus-20240229","temperature":0.5,"presence_penalty":0,"frequency_penalty":0,"top_p":0.99}
```
nextweb 网页截图：
![image](https://github.com/songquanpeng/one-api/assets/40236765/1915fb8c-952d-42e7-857f-1838801cc8f5)

oneapi 日志截图和对应的日志：
```
[INFO] 2024/03/13 - 00:44:21 | 2024031300442124381290622703056 | user 1 has enough quota 99694266, trusted and no need to pre-consume 
[INFO] 2024/03/13 - 00:44:23 | 2024031300442124381290622703056 | record consume log: userId=1, channelId=2, promptTokens=0, completionTokens=0, modelName=claude-3-opus-20240229, tokenName=克劳德-vercel-nextweb, quota=0, content=模型倍率 7.50，分组倍率 1.00，补全倍率 5.00 
```
![image](https://github.com/songquanpeng/one-api/assets/40236765/525362a5-b5c0-4cca-808e-b9e424b19b13)

**Comment by QAbot-zh** [comment]
今天测试未遇到提示和补全为空的情况，多轮对话也正常，暂时认定为是网络因素，后续如果再遇到能稳定触发的情况，我再重开 issue
