### ISSUE TITLE
希望docker部署增加arm64镜像

### ISSUE THREAD

**Issue by AmintaCCCP** [songquanpeng/one-api#114]
如题

**Comment by songquanpeng** [comment]
现在就有哈。

**Comment by AmintaCCCP** [comment]
> 现在就有哈。

啊，我去看看，多谢

**Comment by AmintaCCCP** [comment]
看了一下，最新版的没有arm64的，得拉之前版本
<img width="1378" alt="image" src="https://github.com/songquanpeng/one-api/assets/74942183/bb299709-1d7b-4e90-885f-ec627d9e12d7">

**Comment by songquanpeng** [comment]
正在构建，arm 版本会慢个一个小时。
