### ISSUE TITLE
v0.6.2-alpha.11 对接讯飞星火 websocket: bad handshake

### ISSUE THREAD

**Issue by yc-2503** [songquanpeng/one-api#1140]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
v0.6.2-alpha.11 对接讯飞星火 websocket: bad handshake
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/11872314/b11f6109-976c-4bb5-8aac-586d8aef4aea)

**Comment by Ahrli** [comment]
同上

**Comment by R3dra1n** [comment]
v0.6.2-alpha.16，也是一样

**Comment by yc-2503** [comment]
> 同上
![image](https://github.com/songquanpeng/one-api/assets/11872314/0edfbbd9-f89f-48b9-8bd2-777e3642a845)

V3.5 改成 v3.5

**Comment by yc-2503** [comment]
> v0.6.2-alpha.16，也是一样

![image](https://github.com/songquanpeng/one-api/assets/11872314/dfa887d4-59be-4321-ad8b-85b5015e5bc7)
V3.5 改成 v3.5
