### ISSUE TITLE
v0.6.2-alpha.11 对接 智普 GLM-4 报错 temperature参数非法

### ISSUE THREAD

**Issue by yc-2503** [songquanpeng/one-api#1141]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
v0.6.2-alpha.11 对接 智普 GLM-4 报错，对接GLM-4V没有问题

temperature参数非法。请检查文档。 (request id: 2024031315392281877864286886360)
Status: 400 (Bad Request)
ErrorCode: 1214

**Comment by QAbot-zh** [comment]
temperature 也改成开区间了，看看是不是设置为0或1了
![image](https://github.com/songquanpeng/one-api/assets/40236765/4a8fd3fe-7a3e-4d6c-8b1a-e533611f697a)

**Comment by yc-2503** [comment]
> temperature 也改成开区间了，看看是不是设置为0或1了 ![image](https://private-user-images.githubusercontent.com/40236765/312356868-4a8fd3fe-7a3e-4d6c-8b1a-e533611f697a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDE3MzEsIm5iZiI6MTcxMDM0MTQzMSwicGF0aCI6Ii80MDIzNjc2NS8zMTIzNTY4NjgtNGE4ZmQzZmUtN2EzZS00ZDZjLThiMWEtZTUzMzYxMWY2OTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE0NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YTEyZjM3YTM5YjU3Yjg1ZTQ0YTBlMmJkZjUxZjNkY2Y2ZDU4NmQwZTNiZTIxNjMyNWNhYTJlOTg0MTdlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.311hgZPwQwF20jYLvteAZ9i4DL5J3RQO8GC9vXp2f8A)

确实是这样的，谢谢
