### ISSUE TITLE
百度文心千帆向量模型报错Unsupported openapi method

### ISSUE THREAD

**Issue by q99433** [songquanpeng/one-api#1144]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用的one-api版本是v0.6.2-alpha.11
使用fastgpt对接one-api，one-api配置文心千帆ERNIE-Bot-turbo和Embedding-V1，其中ERNIE-Bot-turbo能正常使用，Embedding-V1无法使用

**复现步骤**
在fastgpt里添加知识库，生成向量的时候提示Embedding API 404，在one-api日志里能看到报错
![image](https://github.com/songquanpeng/one-api/assets/61738634/c7b2f9b7-634e-47b6-99d0-fdf6818e6804)
![image](https://github.com/songquanpeng/one-api/assets/61738634/08928809-054d-4577-b4b2-97105cb73eb5)

{Error:{Message:Unsupported openapi method Type:baidu_error Param: Code:3} StatusCode:200}
![image](https://github.com/songquanpeng/one-api/assets/61738634/f684fff9-b587-4565-9638-5b00bab35936)

**预期结果**
正常应该是能调用接口的

**Comment by q99433** [comment]
<img width="611" alt="image" src="https://github.com/songquanpeng/one-api/assets/61738634/f8c2966b-2728-4355-a848-9f2656cec0b9">
![image](https://github.com/songquanpeng/one-api/assets/61738634/d2c6725d-9266-48fe-80e6-72b0995f65c9)

**Comment by q99433** [comment]
![image](https://github.com/songquanpeng/one-api/assets/61738634/fa89515c-137f-43a3-bf4a-0f08502d03b7)

**Comment by q99433** [comment]
![image](https://github.com/songquanpeng/one-api/assets/61738634/81e8e7ee-17f6-4f1e-89b9-9ac4dd0571c8)

**Comment by ryangsun** [comment]
![image](https://github.com/songquanpeng/one-api/assets/8856760/c7ef34d7-95d7-4f3e-be82-3584896b9a9b)

用python的openai官方包，把embedding模型名称换了，这种方式也不行。
用百度官方案例，调用百度是正常的

**Comment by songquanpeng** [comment]
PR 有人修复了，写了一个 bug 之前

**Comment by hlovingness** [comment]
我最新版本也遇到了这个问题，请问是怎么解决的
