### ISSUE TITLE
最新Docker 版本 配置Azure OpenAI报错

### ISSUE THREAD

**Issue by tyler-whz** [songquanpeng/one-api#1146]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
    最新dokcer版本v0.6.2-alpha.11  安装配置open ai官方key和渠道，测试调用OK 。Azure OpenAI 配置地址key测试失败

**相关截图**
   
<img width="414" alt="截屏2024-03-14 10 54 18" src="https://github.com/songquanpeng/one-api/assets/5018071/ffbb5612-3dcd-4df8-bf43-787593e4a4a2">

等5分钟也是同样失败，其实本key一直在使用，已经好几个月了

如果没有的话，请删除此节。

**Comment by AndyX-Net** [comment]
首先，需要确定一下你是否按照这个说明进行设置？

https://github.com/songquanpeng/one-api/issues/133#issuecomment-1571602271

你可以上传一下你在AOI中模型部署的截图，然后对比一下你在“渠道”里面的截图是否正确。

**Comment by tyler-whz** [comment]
<img width="1228" alt="C6CFD162-899B-40c2-93C9-287BFC4CA6D4" src="https://github.com/songquanpeng/one-api/assets/5018071/45f10f20-a608-46ec-a951-6b314e81aa98">
<img width="1174" alt="截屏2024-03-14 16 03 39" src="https://github.com/songquanpeng/one-api/assets/5018071/e35990fa-1890-4bc1-a40f-9d5c7fe9fa63">

**Comment by AndyX-Net** [comment]
首先需要强调的是，这个“部署名”需要按要求写为跟模型名一样的 “gpt-35-turbo”

![image](https://github.com/songquanpeng/one-api/assets/27819097/a6df020c-b145-4187-bfd8-e91374204a36)

其次，你在ONE-API中要么留“默认API版本为空”，要么设置为最新的“2024-02-15-preview”

然后你在ONE-API里面选自定义模型 gpt-35-turbo就行了。

**Comment by tyler-whz** [comment]
已经OK

**Comment by piwawa** [comment]
> 首先，需要确定一下你是否按照这个说明进行设置？
> 
> [#133 (comment)](https://github.com/songquanpeng/one-api/issues/133#issuecomment-1571602271)
> 
> 你可以上传一下你在AOI中模型部署的截图，然后对比一下你在“渠道”里面的截图是否正确。

![image](https://github.com/songquanpeng/one-api/assets/46926496/f60636bb-4534-4a4f-a8a3-577b4b6334cc)

![image](https://github.com/songquanpeng/one-api/assets/46926496/5bf8f874-8347-4fe6-a1b8-c542cf3e85c4)

为啥我用下面这些模型名调用都没有走这个azure渠道，只有用gpt4-turbo才能调用该渠道。
```
  "gpt-4-0125-preview"
  "gpt-4-turbo-preview"
  "gpt-4"
  "gpt-4-0314"
```

如果我把这四个也加入 `模型` 一栏，调用他们就会报错，只能用gpt4-turbo才正常

```
{
  "error": {
    "message": "The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. (request id: 2024031601021351953666050484769)",
    "type": "",
    "param": "",
    "code": "DeploymentNotFound"
  }
}
```
