### ISSUE TITLE
docker升级后不断重启，无法启动

### ISSUE THREAD

**Issue by Jacky-Bruse** [songquanpeng/one-api#1147]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
docker升级[v0.6.2-alpha.13]之后发现无法启动，查看日志，在出现以下报错之后就不断重启，配置没有修改，报错如下：[failed to get gpt-3.5-turbo token encoder: Get "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken": EOF] 
**复现步骤**
复现
**预期结果**

**Comment by Tarzan999** [comment]
请问怎么解决的？

**Comment by helix-song** [comment]
同问？怎么解决的？

**Comment by XiongjieDai** [comment]
docker下载oneapi这步（docker-compose up -d）的时候梯子挂全局就行了！！！md拿GPT折腾了一晚上
