### ISSUE TITLE
是否能支持如 text-davinci-003 等使用 /v1/completions api 的接口的模型？

### ISSUE THREAD

**Issue by zhiqiangwong** [songquanpeng/one-api#115]
一些模型使用的是旧版的接口，而目前 /v1/completions 接口是不支持的是否那个加上对这个接口的支持?

**Comment by songquanpeng** [comment]
可以给我几个使用该接口的应用的例子么？

**Comment by zhiqiangwong** [comment]
Parameters:
{
  "model": "text-davinci-003",
  "prompt": "Say this is a test",
  "max_tokens": 7,
  "temperature": 0,
  "top_p": 1,
  "n": 1,
  "stream": false,
  "logprobs": null,
  "stop": "\n"
}

Response:
{
  "id": "cmpl-uqkvlQyYK7bGYrRHQ0eXlWi7",
  "object": "text_completion",
  "created": 1589478378,
  "model": "text-davinci-003",
  "choices": [
    {
      "text": "\n\nThis is indeed a test",
      "index": 0,
      "logprobs": null,
      "finish_reason": "length"
    }
  ],
  "usage": {
    "prompt_tokens": 5,
    "completion_tokens": 7,
    "total_tokens": 12
  }
}

**Comment by zhiqiangwong** [comment]
这个接口是3.5之前的gpt模型接口，还有部分细分的模型，资费更为便宜，在某些场景下不需要用到3.5 或者 4，可以使用这个接口性价比更高。如我的应用需要根据用户输入内容识别用户意图，提供了可选项以及用户输入内容给 gpt 从中做出选择，由于调用频率较高，且本身只需要用到语义理解的能力，3.5之前的模型也同样具备，改为这类资费较低的模型性价比较高。

**Comment by songquanpeng** [comment]
了解了。

**Comment by songquanpeng** [comment]
已实现，不过我不明白为什么我的 response 中返回为空：
![image](https://github.com/songquanpeng/one-api/assets/39998050/ba963c0d-03c6-491d-84f0-8d2bd6f30fb4)

如果可以的话，请测试一下能否复现。

**Comment by songquanpeng** [comment]
已推送 v0.4.0-alpha.1
