### ISSUE TITLE
在本地安装ollama，配置在one-api，测试连接时报错。

### ISSUE THREAD

**Issue by hnbzlb** [songquanpeng/one-api#1150]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
one-api采用docker安装 ，ollama与one-api安装在同一个机器上。
在one-api管理渠道中配置渠道，模型为qwen:0.5b-chat，在管理渠道中点击【测试】连接时报错，如下图。

**复现步骤**
**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/728525/2f4c393a-42b5-486e-9d76-a5bce42f53c0)
我验证模型是可以运行。
![image](https://github.com/songquanpeng/one-api/assets/728525/413b0bae-d961-411c-aa87-66345a9d422e)

![image](https://github.com/songquanpeng/one-api/assets/728525/d119ddc4-612a-49e8-b728-7657839036d6)

**Comment by songquanpeng** [comment]
Docker 里安装网络默认是不互通的，建议改成你的公网 ip

**Comment by hnbzlb** [comment]
我在云服务器部署，我觉得应该是可以设置ip的，现在无法设置，我现在使用手动版本安装，是可以了

**Comment by hnbzlb** [comment]
我在云服务器部署，我觉得应该是可以设置ip的，感觉这个IP写死了，我现在服务器，在容器应用内肯定无法访问宿主机的127.0.0.1，只能是IP，现在应用没有地方可以设置。我现在使用手动版本安装，是可以了

**Comment by hnbzlb** [comment]
![Uploading image.png…]()
已解决。

**Comment by hnbzlb** [comment]
![4f61fc1d12ea4f709c4f1e2ae9e6bdd3~noop](https://github.com/songquanpeng/one-api/assets/728525/9993c9dd-1e0b-4629-b7a2-6149f62d16fa)
已解决。

**Comment by sonny-zhang** [comment]
@hnbzlb 你用的公网IP吗？

**Comment by Git0814** [comment]
> 我在云服务器部署，我觉得应该是可以设置ip的，感觉这个IP写死了，我现在服务器，在容器应用内肯定无法访问宿主机的127.0.0.1，只能是IP，现在应用没有地方可以设置。我现在使用手动版本安装，是可以了

你没用docker，直接部署到本地，然后用的公网ip吗

**Comment by XiongjieDai** [comment]
https://github.com/songquanpeng/one-api/issues/1159#issuecomment-2008727516

**Comment by Aaron9168** [comment]
本地用ollama部署的Qwen模型，通过oneapai中转后，有没有办法接入lobechat
