### ISSUE TITLE
文心渠道匹配出错

### ISSUE THREAD

**Issue by tyler-whz** [songquanpeng/one-api#1160]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
   百度文心配置测试成功，打算调用是报错：

org.springframework.ai.openai.api.OpenAiApi$OpenAiApiException: 503 - ResponseError[error=Error[message=当前分组 default 下对于模型 gpt-3.5-turbo 无可用渠道 (request id: 2024031509454592607432640679880), type=one_api_error, param=null, code=null]]
	at org.springframework.ai.openai.api.OpenAiApi$1.handleError(OpenAiApi.java:113) ~[spring-ai-openai-0.8.0.jar:0.8.0]

**复现步骤**
   配置相关KEY秘钥，配置模型转换
   {
       "gpt-3.5-turbo": "ERNIE-3.5-8K"
  }

**预期结果**
   可以调用API

**相关截图**

<img width="580" alt="截屏2024-03-15 09 50 29" src="https://github.com/songquanpeng/one-api/assets/5018071/5891b2a9-5e29-4c6d-8229-1b1d2d78da6e">
<img width="496" alt="截屏2024-03-15 09 49 58" src="https://github.com/songquanpeng/one-api/assets/5018071/602e779b-2132-4b7e-9685-1c388d68277a">
<img width="1224" alt="截屏2024-03-15 09 49 45" src="https://github.com/songquanpeng/one-api/assets/5018071/c0d602fe-8a84-4168-93a1-f95abf6817fb">

如果没有的话，请删除此节。

**Comment by tyler-whz** [comment]
<img width="1081" alt="截屏2024-03-15 09 54 56" src="https://github.com/songquanpeng/one-api/assets/5018071/7dac97b6-d58e-44ee-9623-bc7fad20f249">
<img width="1227" alt="截屏2024-03-15 09 54 34" src="https://github.com/songquanpeng/one-api/assets/5018071/e14d9032-2d29-48da-8488-a6b3c094311a">

**Comment by tyler-whz** [comment]
![Uploading 截屏2024-03-15 10.25.21.png…]()

**Comment by tyler-whz** [comment]
<img width="1036" alt="截屏2024-03-15 10 25 21" src="https://github.com/songquanpeng/one-api/assets/5018071/0b0263c8-bf8b-45f8-94bc-85dd16ed7d5f">

**Comment by cloudtuotuo** [comment]
我也遇到类似问题
![1](https://github.com/songquanpeng/one-api/assets/37918843/7890d7f9-4a76-4fa5-b486-69adc74700da)
![2](https://github.com/songquanpeng/one-api/assets/37918843/6fcf5f1d-9402-4a84-bc56-c7ac00e862d4)

**Comment by c121914yu** [comment]
> **例行检查**
> 
> [//]: # (方框内删除已有的空格，填 x 号)
> + [x] 我已确认目前没有类似 issue
> + [x] 我已确认我已升级到最新版本
> + [x] 我已完整查看过项目 README，尤其是常见问题部分
> + [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
> + [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **问题描述**
>    百度文心配置测试成功，打算调用是报错：
> 
> org.springframework.ai.openai.api.OpenAiApi$OpenAiApiException: 503 - ResponseError[error=Error[message=当前分组 default 下对于模型 gpt-3.5-turbo 无可用渠道 (request id: 2024031509454592607432640679880), type=one_api_error, param=null, code=null]]
> 	at org.springframework.ai.openai.api.OpenAiApi$1.handleError(OpenAiApi.java:113) ~[spring-ai-openai-0.8.0.jar:0.8.0]
> 
> **复现步骤**
>    配置相关KEY秘钥，配置模型转换
>    {
>        "gpt-3.5-turbo": "ERNIE-3.5-8K"
>   }
> 
> **预期结果**
>    可以调用API
> 
> **相关截图**
> 
> <img width="580" alt="截屏2024-03-15 09 50 29" src="https://github.com/songquanpeng/one-api/assets/5018071/5891b2a9-5e29-4c6d-8229-1b1d2d78da6e">
> <img width="496" alt="截屏2024-03-15 09 49 58" src="https://github.com/songquanpeng/one-api/assets/5018071/602e779b-2132-4b7e-9685-1c388d68277a">
> <img width="1224" alt="截屏2024-03-15 09 49 45" src="https://github.com/songquanpeng/one-api/assets/5018071/c0d602fe-8a84-4168-93a1-f95abf6817fb">
> 
> 如果没有的话，请删除此节。

转发两个模型都需要加进去

**Comment by tyler-whz** [comment]
加上转发模型gpt-3.5-turbo  就好了
