### ISSUE TITLE
个人设置里的访问令牌如何使用

### ISSUE THREAD

**Issue by voctot** [songquanpeng/one-api#1161]
目前没有找到使用方法，有没有大佬提点下哇😰

**Comment by AndyX-Net** [comment]
个人令牌就是密码，连接URL地址就是默认的ONE-API地址

以NextChat-WebUI的Docker-compose部署举例，应用One-APi作为Endpoint的效果如下：

services:
  chatgpt-web-nextweb-production:
    image: yidadaa/chatgpt-next-web:latest
    ports:
      - 80:3000
    environment:
      BASE_URL: http://<ONE-API ENDPOINT HERE>:3001    <---One-API连接URL
      OPENAI_API_KEY: sk-qfxxxxxxxxxxxxxxxx    <---访问令牌
    。。。。。。。。。。。。

**Comment by voctot** [comment]
> 个人令牌就是密码，连接URL地址就是默认的ONE-API地址
> 
> 
> 
> 以NextChat-WebUI的Docker-compose部署举例，应用One-APi作为Endpoint的效果如下：
> 
> 
> 
> services:
> 
>   chatgpt-web-nextweb-production:
> 
>     image: yidadaa/chatgpt-next-web:latest
> 
>     ports:
> 
>       - 80:3000
> 
>     environment:
> 
>       BASE_URL: http://<ONE-API ENDPOINT HERE>:3001    <---One-API连接URL
> 
>       OPENAI_API_KEY: sk-qfxxxxxxxxxxxxxxxx    <---访问令牌
> 
>     。。。。。。。。。。。。

谢谢你的回答，我现在大概知道怎么使用了。
