### ISSUE TITLE
Azure OpenAI dall-e-3 404 报错 Resource not found

### ISSUE THREAD

**Issue by ErlichLiu** [songquanpeng/one-api#1164]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
上游渠道配置 Azure OpenAI dall-e-3 ，在通过代码调用生成图片、使用任何第三方套壳客户端生成图片，都遇到 One API 返回的错误 `NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}`

** 问题补充**
这个问题在 2023 年 11 月也被提出来了：https://github.com/songquanpeng/one-api/issues/751 ，我在使用 2023 年版本的 One API 时没有这个问题。似乎是在后续的更新当中又把这个 Merge 给去掉了。

**复现步骤**
1. 升级到最新版本的 One API；
2. 在任何第三方客户端或者通过 OpenAI SDK 调用生成图片；
3. 遇到找不到资源的错误

**预期结果**
可正常生成图片

**Comment by slikyo** [comment]
我也遇到了同样的问题

**Comment by songquanpeng** [comment]
无法复现：
![image](https://github.com/songquanpeng/one-api/assets/39998050/c2660bea-29ba-4831-a2a1-9b794ae4f0fc)

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/93bbfab6-ecda-4230-84cd-b6954b6b5669)
这个不是 One API 的报错哦

**Comment by ErlichLiu** [comment]
> ![image](https://private-user-images.githubusercontent.com/39998050/313468560-93bbfab6-ecda-4230-84cd-b6954b6b5669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzY3OTAsIm5iZiI6MTcxMDY3NjQ5MCwicGF0aCI6Ii8zOTk5ODA1MC8zMTM0Njg1NjAtOTNiYmZhYjYtZWNkYS00MjMwLTg0Y2QtYjY5NTRiNmI1NjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDExNTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWYyMDI0NTZiMGM0YWIyNmJkNDE5OGNlNzA3MzQ2M2EyYmRkNjFkOWIzM2ViZTk2OWZhZmE4MDE1Yjc2YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B-jhHQ5CCBwdTKcjnrbILz5jpxEpXLzkh6FLMFmaZwY) 这个不是 One API 的报错哦

可以贴一下你的 relay/controller/image.go 这个文件路径下的代码吗。我相对比一下，可能是你本地的代码跟目前推到 Main 分支上的代码不一样。我想来对比一下试试看，因为这个问我看之前的 Issue 就被覆盖过。

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/5496120e-dc9c-49c7-8bb1-92640edd176a)

**Comment by ErlichLiu** [comment]
> ![image](https://private-user-images.githubusercontent.com/39998050/313469748-5496120e-dc9c-49c7-8bb1-92640edd176a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Nzc1MTQsIm5iZiI6MTcxMDY3NzIxNCwicGF0aCI6Ii8zOTk5ODA1MC8zMTM0Njk3NDgtNTQ5NjEyMGUtZGM5Yy00OWM3LThiYjEtOTI2NDBlZGQxNzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEyMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NGZkMzUxMDMyYmRhNTI3OTE2MTgzM2M0NDFmNTgyNzhlNDBmNDgyMGI1NDVkZjIzYjZkMTdmMWRkNThiMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kiYdxhtp0nv8q1oe-jZvWytk8m3rS5MdeRWRih2yo7g)

感谢你的截图反馈，我这边刚也做了一些测试，已经可以正常使用了！
测试步骤：
1. 本地拉取最新的版本运行测试，图片可以正常生成；
2. 确保部署在服务上的也是最新的版本，服务器端生成遇到找不到资源的错误；
3. 删除服务器端的原有渠道，重新建立新的渠道，并调高渠道优先级，现在已经可以正常生成图片 @slikyo 可以试试这个方法

可能是缓存等问题导致的。已经没有问题了关闭这个 Issue 了。再次感谢~

**Comment by cuhktsang** [comment]
> > ![image](https://private-user-images.githubusercontent.com/39998050/313469748-5496120e-dc9c-49c7-8bb1-92640edd176a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Nzc1MTQsIm5iZiI6MTcxMDY3NzIxNCwicGF0aCI6Ii8zOTk5ODA1MC8zMTM0Njk3NDgtNTQ5NjEyMGUtZGM5Yy00OWM3LThiYjEtOTI2NDBlZGQxNzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEyMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NGZkMzUxMDMyYmRhNTI3OTE2MTgzM2M0NDFmNTgyNzhlNDBmNDgyMGI1NDVkZjIzYjZkMTdmMWRkNThiMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kiYdxhtp0nv8q1oe-jZvWytk8m3rS5MdeRWRih2yo7g)
> 
> 感谢你的截图反馈，我这边刚也做了一些测试，已经可以正常使用了！ 测试步骤：
> 
> 1. 本地拉取最新的版本运行测试，图片可以正常生成；
> 2. 确保部署在服务上的也是最新的版本，服务器端生成遇到找不到资源的错误；
> 3. 删除服务器端的原有渠道，重新建立新的渠道，并调高渠道优先级，现在已经可以正常生成图片 @slikyo 可以试试这个方法
> 
> 可能是缓存等问题导致的。已经没有问题了关闭这个 Issue 了。再次感谢~

感谢，我重新部署了下，已解决。
