### ISSUE TITLE
Moonshot 自动填充的模型类型错误

### ISSUE THREAD

**Issue by Alwaysbesideyou** [songquanpeng/one-api#1169]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在v0.6.2版本中，Moonshot 自动填充的模型类型错误。在更正模型类型并填入相应的密钥之后，通过测试渠道进行验证时，结果显示【401鉴权失败】。

可能出问题的[相关代码](https://github.com/songquanpeng/one-api/blob/6325c8e0b4b16e8b5bffd8fb0037f241a30716ae/web/berry/src/constants/ChannelConstants.js#L71)
**复现步骤**
【渠道】-【新建渠道】-选择【Moonshot 】-填入【Key】-【提交】
**预期结果**
正确填充，同时能够正常访问渠道。
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/62324232/8aa831f9-0d50-4963-a258-b56501679fa4)

**Comment by songquanpeng** [comment]
已经有 PR 修复了哈

**Comment by songquanpeng** [comment]
更新版本即可
