### ISSUE TITLE
Azure OpenAI 渠道无法重定向！

### ISSUE THREAD

**Issue by piwawa** [songquanpeng/one-api#1174]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
![image](https://github.com/songquanpeng/one-api/assets/46926496/f60636bb-4534-4a4f-a8a3-577b4b6334cc)

![image](https://github.com/songquanpeng/one-api/assets/46926496/5bf8f874-8347-4fe6-a1b8-c542cf3e85c4)

为啥我用下面这些模型名调用都没有走这个azure渠道，只有用gpt4-turbo才能调用该渠道。
```
  "gpt-4-0125-preview"
  "gpt-4-turbo-preview"
  "gpt-4"
  "gpt-4-0314"
```

如果我把这四个也加入 `模型` 一栏，调用他们就会报错，只能用gpt4-turbo才正常

```
{
  "error": {
    "message": "The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. (request id: 2024031601021351953666050484769)",
    "type": "",
    "param": "",
    "code": "DeploymentNotFound"
  }
}
```
**预期结果**
通过重定向设置，将 gpt-4，gpt-4-0314 定向到 gpt4-0314 模型，将  gpt-4-0125-preview，gpt-4-turbo-preview 定向到 gpt4-turbo 模型，其它未导入的模型不要使用该 Azure 渠道。

**Comment by songquanpeng** [comment]
对于 `gpt-4-0125-preview`，部署名称改为 `gpt-4-0125-preview`

**Comment by ManJieqi** [comment]
<img width="570" alt="Snipaste_2024-03-20_15-28-58" src="https://github.com/songquanpeng/one-api/assets/40858189/14b1099a-effd-421c-b789-808c780e0572">
所以
第一，你请求里面有什么，模型那里就要填什么
第二，请求的模型和你部署的不一样，就需要设置重定向
第三，重定向的值和没有重定向的模型都会在发送前删掉点

Azure的api好像就是用部署名作为模型名称的，我觉得要求，部署名和模型名称一致，然后自动删除点，有点把事情弄复杂了，毕竟，自己设置个重定向就行，就是模型倍率需要自己设置一下

不知道对不对

**Comment by piwawa** [comment]
> <img alt="Snipaste_2024-03-20_15-28-58" width="570" src="https://private-user-images.githubusercontent.com/40858189/314409505-14b1099a-effd-421c-b789-808c780e0572.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjIwODIsIm5iZiI6MTcxMDkyMTc4MiwicGF0aCI6Ii80MDg1ODE4OS8zMTQ0MDk1MDUtMTRiMTA5OWEtZWZmZC00MjFjLWI3ODktODA4Yzc4MGUwNTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4MDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzAwYzA3ZWE2YThiMTk5YmQ0ZTlkM2NiZjQwMGQzMWQ5NDAxMWUwNTNiOGI4MmIzZGIwMjBiZDZlMjc2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P54LbZfb15LITUHRuwaaYKq1Qd65hMn5KctPjwoZnSs">
> 所以 第一，你请求里面有什么，模型那里就要填什么 第二，请求的模型和你部署的不一样，就需要设置重定向 第三，重定向的值和没有重定向的模型都会在发送前删掉点
> 
> Azure的api好像就是用部署名作为模型名称的，我觉得要求，部署名和模型名称一致，然后自动删除点，有点把事情弄复杂了，毕竟，自己设置个重定向就行，就是模型倍率需要自己设置一下
> 
> 不知道对不对

我把部署名改了就OK了，也能重定向和正常计费，不知道为啥之前 `gpt4-0314` 无法直接调用也无法重定向。
