### ISSUE TITLE
部分上游接口兼容性问题

### ISSUE THREAD

**Issue by WangEdward** [songquanpeng/one-api#118]
部分第三方接口的兼容性有一些问题，如 api.caipacity.com （ai.ls），即使请求时添加了 `"stream": false`，其仍会使用流式返回数据，是否可以添加数据转换来使返回值的数据格式与用户请求的相同。

**Comment by songquanpeng** [comment]
如果是上游接口的问题，不应该由 One API 进行兼容（除非是 Azure）。

第三方代理的 API 应和 OpenAI 的官方接口保持一致。
