### ISSUE TITLE
M3E模型不能添加

### ISSUE THREAD

**Issue by WHG555** [songquanpeng/one-api#1180]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

# 环境说明

版本：v0.6.3-alpha.1

**问题描述**
# M3E模型不能添加

### M3E模型可以使用
![image](https://github.com/songquanpeng/one-api/assets/26180549/bff7987f-501f-4f8b-a210-1c65aafe68ae)
![image](https://github.com/songquanpeng/one-api/assets/26180549/aa6f1681-8fee-4c6a-82ba-f5be03999e5b)

### OpenAI Embedding-V1测试
这个模型的路径也不对。不能转换路径
![image](https://github.com/songquanpeng/one-api/assets/26180549/45ef7329-a317-4f14-9e80-e85ec114b420)
![image](https://github.com/songquanpeng/one-api/assets/26180549/15b9a94f-cccc-46bc-a5a3-ff0c2d95e319)

**Comment by songquanpeng** [comment]
你是点的测试对吧，测试按钮只支持 chat 模型，正常使用不会出现这种问题

**Comment by WHG555** [comment]
那m3e添加的时候   渠道  那些应该如何选了？

**Comment by songquanpeng** [comment]
如果支持 OpenAI 的请求格式，选自定义就好
