### ISSUE TITLE
希望增加gemini-1.5-pro-latest模型的支持

### ISSUE THREAD

**Issue by katyshawn922** [songquanpeng/one-api#1183]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望增加 gemini-1.5-pro-latest 模型的支持
**应用场景**

**Comment by songquanpeng** [comment]
这个开放了？

**Comment by katyshawn922** [comment]
> 这个开放了？

是的，我的API已经可以使用了

**Comment by catsimple** [comment]
哪来的API？

**Comment by katyshawn922** [comment]
> 哪来的API？

谷歌也放水了一波，之前gemini-1.5-pro申请waitlist的基本上都通过

**Comment by catsimple** [comment]
> > 哪来的API？
> 
> 谷歌也放水了一波，之前gemini-1.5-pro申请waitlist的基本上都通过

我的意思是调用的API是什么？

**Comment by katyshawn922** [comment]
> > > 哪来的API？
> > 
> > 
> > 谷歌也放水了一波，之前gemini-1.5-pro申请waitlist的基本上都通过
> 
> 我的意思是调用的API是什么？

没明白你意思。。iOS上的opencat是支持这个模型了的

**Comment by catsimple** [comment]
> > > > 哪来的API？
> > > 
> > > 
> > > 谷歌也放水了一波，之前gemini-1.5-pro申请waitlist的基本上都通过
> > 
> > 
> > 我的意思是调用的API是什么？
> 
> 没明白你意思。。iOS上的opencat是支持这个模型了的

你要支持这个模型，肯定要调用vertex api
但是我目前**没有发现任何地方能通过api调用gemini1.5pro**的
只能通过ai studio webui交互
所以不排除你说的opencat是通过webui to api实现的

**Comment by katyshawn922** [comment]
> > > > > 哪来的API？
> 
> > > > 
> 
> > > > 
> 
> > > > 谷歌也放水了一波，之前gemini-1.5-pro申请waitlist的基本上都通过
> 
> > > 
> 
> > > 
> 
> > > 我的意思是调用的API是什么？
> 
> > 
> 
> > 没明白你意思。。iOS上的opencat是支持这个模型了的
> 
> 
> 
> 你要支持这个模型，肯定要调用vertex api
> 
> 但是我目前**没有发现任何地方能通过api调用gemini1.5pro**的
> 
> 只能通过ai studio webui交互
> 
> 所以不排除你说的opencat是通过webui to api实现的

应该不是，因为我是通过原来1.0的API去调用的

**Comment by catsimple** [comment]
> > > > > > 哪来的API？
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 谷歌也放水了一波，之前gemini-1.5-pro申请waitlist的基本上都通过
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我的意思是调用的API是什么？
> > 
> > 
> > > 
> > 
> > 
> > > 没明白你意思。。iOS上的opencat是支持这个模型了的
> > 
> > 
> > 你要支持这个模型，肯定要调用vertex api
> > 但是我目前**没有发现任何地方能通过api调用gemini1.5pro**的
> > 只能通过ai studio webui交互
> > 所以不排除你说的opencat是通过webui to api实现的
> 
> 应该不是，因为我是通过原来1.0的API去调用的

你通过1.0的API调用肯定是1.0的模型啊...

**Comment by katyshawn922** [comment]
> > > > > > > 哪来的API？
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 谷歌也放水了一波，之前gemini-1.5-pro申请waitlist的基本上都通过
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 我的意思是调用的API是什么？
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 没明白你意思。。iOS上的opencat是支持这个模型了的
> 
> > > 
> 
> > > 
> 
> > > 你要支持这个模型，肯定要调用vertex api
> 
> > > 但是我目前**没有发现任何地方能通过api调用gemini1.5pro**的
> 
> > > 只能通过ai studio webui交互
> 
> > > 所以不排除你说的opencat是通过webui to api实现的
> 
> > 
> 
> > 应该不是，因为我是通过原来1.0的API去调用的
> 
> 
> 
> 你通过1.0的API调用肯定是1.0的模型啊...

你没理解我的意思啊，我的意思是通过原来的API key，调用gemini-1.5-pro-latest的模型，并没有所谓的1.5专用API key之类的东西
