### ISSUE TITLE
Azure渠道model 去掉TrimSuffix  重写

### ISSUE THREAD

**Issue by lgxisbb** [songquanpeng/one-api#1191]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

期望去掉azure渠道模型自动 TrimSuffix   ,  以所见即所得的方式请求指定部署的模型

**应用场景**

azure 同时部署 xxxx-0301 和 xxxx-0314 情况下  ,  因为 TrimSuffix 的原因 , 自动转发到了 xxxx 模型.   和预期不一致.

https://github.com/songquanpeng/one-api/issues/67
这种场景 , 应该在azure自己部署的时候指定, 而不是通过oneapi来做处理.

**Comment by ManJieqi** [comment]
我也觉得，这个就是要用openai的模型名称，自己写个重定向就行的

**Comment by mogazheng** [comment]
同样的问题，折腾了一个下午，还得看源码才找到这个TrimSuffix的问题
