### ISSUE TITLE
通过调api方式生成的新令牌，返回体中能包含新令牌吗 

### ISSUE THREAD

**Issue by Gijela** [songquanpeng/one-api#1208]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
接口是/api/token。

通过调api的方式去生成新令牌，但是返回体中不包含该令牌，要获得该令牌，我目前只发现能通过get请求去获取令牌列表，然后遍历筛选指定的key和sk-拼接得到令牌。请问有其他方式获得该新令牌吗？为什么不考虑在返回体中添加该令牌呢？是安全问题吗？蟹蟹
**应用场景**

**Comment by songquanpeng** [comment]
已经加上了，之前之所以不返回是因为 One API 自己的前端不使用这个。
![image](https://github.com/songquanpeng/one-api/assets/39998050/e299a20d-dca5-48a0-8855-b1169d28636e)
