### ISSUE TITLE
whisper-1 报错后扣除近$1并且不返还

### ISSUE THREAD

**Issue by wfce** [songquanpeng/one-api#1217]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
whisper-1报错后余额被扣除，日志无记录，每次扣的额度近$1，很多个版本了一直有这个问题
Error code: 500 - {'error': {'message': 'type chat_api_error, code read_response_body_failed, message http2: response body closed (request id: ) (request id: 2024032309565660048718925936232)', 'type': 'one_api_error', 'param': '', 'code': 'request_error'}}

**Comment by songquanpeng** [comment]
已修复
