### ISSUE TITLE
图片生成dall-e-3巨大Bug!引发size not supported for this image model

### ISSUE THREAD

**Issue by Toketec** [songquanpeng/one-api#1224]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
图片生成过程中，系统存在对尺寸的检测，由于尺寸检测默认使用dall-e-3，dall-e-2的key进行匹配，当用户设置模型别名的时候，系统就因为找不到key而提示尺寸不合法报错
**复现步骤**
1、在azure部署模型的时候，使用别名假设dall-e-3的名字为DALLE3
<img width="1121" alt="image" src="https://github.com/songquanpeng/one-api/assets/44367138/447a5c6d-ea5b-4b97-bc16-e368fc6b7aa5">

2、在one-api渠道设置中，添加dall-e-3模型，并设置别名映射关系dall-e-3——>DALLE3
<img width="1247" alt="image" src="https://github.com/songquanpeng/one-api/assets/44367138/938f6189-179b-480a-9c14-1a35b8908eac">

3、正常调用/images/generations，参数中使用模型名dall-e-3
4、报错情况：
<img width="780" alt="image" src="https://github.com/songquanpeng/one-api/assets/44367138/501678f9-dc6e-42e7-92b2-f63beb740ba2">

**预期结果**

**相关截图**
代码中的bug原因和建议修改：修改模型映射转换&验证尺寸的执行顺序，避免用户模型别名被提前映射为图片尺寸验证中不存在的模型。
<img width="1120" alt="image" src="https://github.com/songquanpeng/one-api/assets/44367138/72387a29-0639-4598-af62-b7ca197168b4">
<img width="901" alt="image" src="https://github.com/songquanpeng/one-api/assets/44367138/7a79bb0c-c4db-45ad-bb13-6bb8d1997e91">
<img width="457" alt="image" src="https://github.com/songquanpeng/one-api/assets/44367138/81256935-5eb4-48eb-8a56-6fb7254ce3e0">

如果没有的话，请删除此节。

**Comment by lfglfg11** [comment]
啊，我也一样遇到这个困扰！只有最终走dalle3模型时image接口才正常，渠道里添加的自定义模型就都默认走了Chat接口了，用image接口调用该自定义模型时就会报错size not supported for this image model，自定义模型映射到dalle3才能正常调用image接口！
![image](https://github.com/songquanpeng/one-api/assets/32725664/bc30c1df-189a-4f86-b6b6-edab83752235)

**Comment by lfglfg11** [comment]
希望大佬快点修复吧，隔壁new api无此问题😥

**Comment by lfglfg11** [comment]
@songquanpeng

**Comment by snakeying** [comment]
我在使用cloudflare workers ai的文生图模型（SD）时候也遇到了同样的错误

**Comment by igophper** [comment]
这个不是改顺序的问题，验证图片尺寸按道理来说是不是应该验证最后请求出去的模型的尺寸。
这个可以考虑先判断模型存不存在，存在之后再去判断尺寸存不存在。
当模型不存在时不进行报错。

**Comment by igophper** [comment]
修复这个问题但是会引入另一个问题，就是模型计费问题。因为像真实请求的模型  `DALLE3` 是没法知道它的计费的。这个可能是`DALLE3` 也可能是 `DALLE4`  这个问题的解决办法是去 自定义模型的计费。

**Comment by igophper** [comment]
可以使用 `docker pull igophper/one-api:223efc2` 这个镜像试一下是否还存在问题

**Comment by Laisky** [comment]
@Toketec 现在的问题是，如果映射目标的模型名不是 `dall-e-2/dall-e-3`，计费和数量限制就会完全被绕过，我觉得这可能不是你所希望的改动？

就目前的计费设计来看，如果你希望保留正确的计费，那么目标模型名就必须用 `dall-e-2/dall-e-3`。

**Comment by igophper** [comment]
这个是计费问题，和请求图片没关系。计费的问题需要另开一个issues来讨论，如何确保计费正确。
