### ISSUE TITLE
希望增加通过自定义模型名来轮询不同的国内AI服务商

### ISSUE THREAD

**Issue by hkwz2023** [songquanpeng/one-api#1238]
**应用场景**
国内的AI也很多了，讯飞、阿里、百度、零一万物，也注册了很多api（个人用），但他们各家的模型名都不一样，每次都要选择不同的国内模型名很麻烦。希望通过自定义一个通用的模型名，在后台轮询这些不同的国内渠道。

**Comment by QAbot-zh** [comment]
不是可以通过自定义模型+重定向实现你的要求吗？轮询不同模型的意义是啥，能力参差不齐，不会很影响实际体验？

**Comment by hkwz2023** [comment]
> 不是可以通过自定义模型+重定向实现你的要求吗？轮询不同模型的意义是啥，能力参差不齐，不会很影响实际体验？

我不太会编程……主要是手上的api太多了，而且主要用于搜索数据库，对AI智力要求不高。

**Comment by QAbot-zh** [comment]
不用多复杂的编程，你需要做的就是类似这样，设置一个通用的模型名，然后加入对应渠道的模型里，再加上重定向，这样你就可以通过一个通用模型名称来调用不同的国内渠道了。

![image](https://github.com/songquanpeng/one-api/assets/40236765/f613a32d-2696-4279-ab52-8f37406cf766)

**Comment by hkwz2023** [comment]
> 不用多复杂的编程，你需要做的就是类似这样，设置一个通用的模型名，然后加入对应渠道的模型里，再加上重定向，这样你就可以通过一个通用模型名称来调用不同的国内渠道了。
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/317940871-2cb209a7-63c6-4bd4-927b-56543125a7b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODUzNTcsIm5iZiI6MTcxMTY4NTA1NywicGF0aCI6Ii80MDIzNjc2NS8zMTc5NDA4NzEtMmNiMjA5YTctNjNjNi00YmQ0LTkyN2ItNTY1NDMxMjVhN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA0MDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzN2Y5M2YwYjExNWRiYTY2Mzc1ZGY1NWZiMmFkMzI1MmNmZjY3OWY5ZTI0YmQxOGIyODQ2NjU1MjJmZDgxNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FkUETBaK_9t9V1CCuvG_rygvUP1o1Ko8BrYRf7Eqc9g)

懂了，感谢分享。另外图片里面那个mootshot刚查了一下，200万汉字有点强哦，赶紧去注册了一个^^

**Comment by hkwz2023** [comment]
我发现重定向这个功能也可以给国内模型指定gpt-turbo-3.5，这样连自定义模型名都省了，可以跟普通的gpt-turbo-3.5一起轮询。感谢上面朋友的启发，这个issue自此关闭。

**Comment by chapterv** [comment]
> 不用多复杂的编程，你需要做的就是类似这样，设置一个通用的模型名，然后加入对应渠道的模型里，再加上重定向，这样你就可以通过一个通用模型名称来调用不同的国内渠道了。
> 
> ![image](https://github.com/songquanpeng/one-api/assets/40236765/2cb209a7-63c6-4bd4-927b-56543125a7b0)

能否理解是有多个服务商，比如kimi，豆包，每一个服务商里面都这么配置，kimi里面“国内大模型”映射到 moonshot，豆包里面“国产大模型”映射到 doubao，然后用户调用“国产大模型” one api 就会轮询 moonshot和doubao？那么内部轮询的机制是随机的吗，可以调整吗
