### ISSUE TITLE
openai和claude的参数兼容

### ISSUE THREAD

**Issue by ye4293** [songquanpeng/one-api#1239]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在claude中还保留了参数
![image](https://github.com/songquanpeng/one-api/assets/137054651/9ae72b64-25d8-4c7f-a7ef-4b15ecd4662a)
但是opeani中确实只有topp了，应该修改下textrequest，使得可以兼容claude的topk
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by ye4293** [comment]
![image](https://github.com/songquanpeng/one-api/assets/137054651/d09d1e7b-82a7-4b57-a8e9-1602c392a798)
这是现有的textrequest结构

**Comment by xuyang-stack** [comment]
请问 客户端调用openai 的接口，怎么传入topk ?
