### ISSUE TITLE
请支持阿里千文的FUNCTION调用

### ISSUE THREAD

**Issue by caserzer** [songquanpeng/one-api#1242]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
看了一下具体的代码， 在阿里调用转换的时候会直接忽略FUNCTION 的调用，而且OAI 在content 中允许‘’ 但是 ALI是不允许的，这块是否能直接增加？
![image](https://github.com/songquanpeng/one-api/assets/7637589/8215bc0b-7ace-486d-a809-5e1d4a1e9e5e)

**应用场景**

**Comment by songquanpeng** [comment]
试一下 v0.6.5-alpha 呢？已经适配了。

**Comment by Leo575** [comment]
@songquanpeng 这个有bug吧，看阿里云文档，HTTP调用接口中，tools是parameters子节点，而不是与parameters平行节点。
我尝试改了后就调用正常，目前返回不了tool_calls

![image](https://github.com/songquanpeng/one-api/assets/25657314/dc9bf4cb-cdc8-4aaf-afec-377d0274caba)

![image](https://github.com/songquanpeng/one-api/assets/25657314/232d8d6b-d067-4534-81f9-944fc19b1317)

> 试一下 v0.6.5-alpha 呢？已经适配了。

**Comment by songquanpeng** [comment]
感谢指正，已经修复

**Comment by pangjianxin** [comment]
还是有问题，好像返回的格式不兼容openai的吧
