### ISSUE TITLE
为何对于 Claude 要默认带 max_tokens 参数？

### ISSUE THREAD

**Issue by bbb3n** [songquanpeng/one-api#1245]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

根据 官方文档 ，claude模型调用时必须要带 max_tokens ，不然会报错
注意到咱们在代码中有一段
https://github.com/songquanpeng/one-api/blob/5e81e19bc81e88d5df15a04f6a6268886127e002/relay/channel/anthropic/main.go#L43C2-L45C3

```
if claudeRequest.MaxTokens == 0 {
              claudeRequest.MaxTokens = 4096
}
```

个人感觉，这就很奇怪，作为一个纯粹的中转系统，不应该考虑这个问题
用户不传 max_tokens （可能是忘了，或者没看文档），就应该直接返回报错，他们看了文档自然会懂

如果这样的话，算是为消费者的"一知半解"来买单？

再比如，gpt-4-preview-vision 模型，这个模型也是必须带 max_tokens 参数
只不过，即使不带，OpenAI 也不会报错，只会使得返回 content 说一半就没了
那咱们既然没有给 这个模型 特别判断并设置参数，我觉得 claude 也不应该设置

还是那个原因，作为一个纯粹的中转系统，个人认为不应该。

**Comment by songquanpeng** [comment]
我记得是api要求这样的，我自己当然不想额外加这种判断，如果现在claude 的api情况变了请测试后反馈

**Comment by songquanpeng** [comment]
所以就像你说的，其他都会默认带，oneapi本身也只是提供一个默认值，也不会影响到这种会传递maxtokens的客户端。除此之外，openai格式并不要求，claude要求，那我理解oneapi需要去做这个兼容逻辑。当然，**欢迎继续讨论**。之后也可以考虑做一个开关让用户自己选择。

**Comment by Caixiaopig** [comment]
个人建议：
1. 如果one-api只是一个单纯的转发系统，就原封不动的做mapping转发出去即可；
2. 但是目前的one-api并不是这样的定位，更多的还是一个分发系统，项目介绍中也多次出现“分发”、“分发管理key”，因此就需要一些“防呆”机制在一定程度上提高系统的兼容性和易用性；

综上，我认为此功能有必要保留，以防误解在文档中加入简单的说明即可。
