### ISSUE TITLE
已拉取到最新版本，3.30号的版本 使用讯飞模型报错

### ISSUE THREAD

**Issue by liugy1028** [songquanpeng/one-api#1249]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用讯飞模型v3.5,报错

**复现步骤**
使用3.5，直接调用报错
**预期结果**

**相关截图**
[INFO] 2024/03/31 - 22:37:43 | 2024033122374284902318948826048 | user 1 has enough quota 499999999892452, trusted and no need to pre-consume 
[SYS] 2024/03/31 - 22:37:44 | error reading stream response: websocket: close 1000 (normal): close this ws conn 
[ERR] 2024/03/31 - 22:37:44 | 2024033122374284902318948826048 | panic detected: runtime error: invalid memory address or nil pointer dereference 
[ERR] 2024/03/31 - 22:37:44 | 2024033122374284902318948826048 | stacktrace from panic: goroutine 266 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/songquanpeng/one-api/router.SetRelayRouter.RelayPanicRecover.func2.1()
	/build/middleware/recover.go:18 +0xc5
panic({0xf56e40?, 0x3b1d010?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/songquanpeng/one-api/relay/channel/openai.ErrorWrapper(...)
	/build/relay/channel/openai/util.go:7
github.com/songquanpeng/one-api/relay/channel/xunfei.Handler(_, {{0xc0009803a0, 0xe}, {0xc0000bc500, 0x6, 0x8}, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
	/build/relay/channel/xunfei/main.go:174 +0x64f
github.com/songquanpeng/one-api/relay/channel/xunfei.(*Adaptor).DoResponse(0xc0001185c0, 0xc00012a600, 0x10921cb?, 0xc0008e8340)
	/build/relay/channel/xunfei/adaptor.go:59 +0x186
github.com/songquanpeng/one-api/relay/controller.RelayTextHelper(0xc00012a600)
	/build/relay/controller/text.go:95 +0xd69
github.com/songquanpeng/one-api/controller.relay(0xc0000b2425?, 0x1084d84?)
	/build/controller/relay.go:37 +0x52
github.com/songquanpeng/one-api/controller.Relay(0xc00012a600)
	/build/controller/relay.go:50 +0x145
github.com/gin-gonic/gin.(*Context).Next(0xc00012a600)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/songquanpeng/one-api/router.SetRelayRouter.Distribute.func4(0xc00012a600)
	/build/middleware/distributor.go:83 +0x3b7

**Comment by Linusp** [comment]
和 #1266 一样，我遇到类似问题，在里面有个回复，可以看下

**Comment by liugy1028** [comment]
我测试接口试了下，是使用了role 为system的导致的错误。
