### ISSUE TITLE
请教这个[当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道]是差个啥配置呢

### ISSUE THREAD

**Issue by hlovingness** [songquanpeng/one-api#1250]

**Comment by QAbot-zh** [comment]
意味着你的渠道/上游没有添加这个模型

**Comment by hlovingness** [comment]
不是这样添加吗
![image](https://github.com/songquanpeng/one-api/assets/16331459/a03e6964-ed7f-4478-8dcd-d43c98fa4bd4)

**Comment by QAbot-zh** [comment]
重定向左右的模型名称都要填到支持模型里

![image](https://github.com/songquanpeng/one-api/assets/40236765/bf59ec27-e128-4412-8192-20aa58ea7d6a)

**Comment by hlovingness** [comment]
可以了，感谢

**Comment by Superkevin117** [comment]
可以分享一下解决方式吗
