### ISSUE TITLE
调用后返回tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by xingmolu** [songquanpeng/one-api#1254]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
    "message": "do request failed: Post \"https://hk.xty.app/v1/chat/completions\": tls: failed to verify certificate: x509: certificate signed by unknown authority",

**复现步骤**
本地 docker 部署后正常运行一段时间后出现问题，详细信息见下面截图

**相关截图**

<img width="1157" alt="image" src="https://github.com/songquanpeng/one-api/assets/2590258/4d49adb3-45fb-4542-933a-2ec163761914">

<img width="775" alt="image" src="https://github.com/songquanpeng/one-api/assets/2590258/1ac99862-ce97-4e99-b22d-e3dc0deb6ee3">

<img width="796" alt="image" src="https://github.com/songquanpeng/one-api/assets/2590258/41859256-c9aa-4e85-ae47-206caf671e93">

**Comment by xingmolu** [comment]
问题已解决，是开启了 whistle 导致的。

**Comment by MusicOfWind** [comment]
> 问题已解决，是开启了 whistle 导致的。

怎么操作
