### ISSUE TITLE
请问如何重置root/admin 的密码

### ISSUE THREAD

**Issue by fiadigifrank** [songquanpeng/one-api#1256]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
请问如何重置root/admin 管理者的账号与密码，一阵子没用

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by liuhetian** [comment]
![one-api](https://github.com/songquanpeng/one-api/assets/91518757/a5e9dcb7-7824-4097-978f-935691c560c2)
用root账户登陆，然后修改

**Comment by fiadigifrank** [comment]
抱歉，我可能没表达清楚，我自己是管理者，我自己的管理者的密码忘了（所以后台也登入不进去了）

**Comment by fiadigifrank** [comment]
谢谢。我刚试出来了

**Comment by jiangying000** [comment]
root密码忘了，有推荐的重置方案吗

**Comment by Zhenyi-Wang** [comment]
> 谢谢。我刚试出来了
请问怎么重制的呀？

**Comment by 820678105** [comment]
有一个重置办法，不过把源码拉取下来。
