### ISSUE TITLE
限制注册邮箱域名后缀

### ISSUE THREAD

**Issue by AiZyc** [songquanpeng/one-api#126]
管理员后台可设置指定可注册的邮箱后缀，可防止临时邮箱或僵尸号注册
例如：
![image](https://github.com/songquanpeng/one-api/assets/11790369/51efbcac-51f2-4f01-a7d7-f4f8daa00e7b)

**Comment by songquanpeng** [comment]
Okay

**Comment by Aiayw** [comment]
{"@gmail.com", "@hotmail.com", "@yahoo.com", "@outlook.com", "@icloud.com", "@qq.com", "@163.com", "@sina.com", "@aliyun.com", "@yeah.net", "@live.com", "@126.com", "@foxmail.com", "@139.com", "@sohu.com", "@tom.com", "@vip.qq.com", "@21cn.com", "@189.cn"}
常用邮箱参考。

**Comment by dalaolala** [comment]
这个功能真的非常有必要 特别是api 好多恶意注册的

**Comment by songquanpeng** [comment]
这个已经可以用了
