### ISSUE TITLE
请求支持Open AI的Assistants API

### ISSUE THREAD

**Issue by OpenHuShen** [songquanpeng/one-api#1263]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
支持Open AI的[Assistants API](https://platform.openai.com/docs/assistants/overview/agents)
**应用场景**
微软的guidance框架(https://github.com/microsoft/guidance) 包括很多科研实验是基于Assistants API实现的

**Comment by ye4293** [comment]
pro版本支持了，但是暂时没有计费功能

**Comment by zsychn** [comment]
> pro版本支持了，但是暂时没有计费功能

您好，pro版本是哪个版本
