### ISSUE TITLE
Azure 配置报错：DeploymentNotFound, message The API deployment for this resource does not exist.

### ISSUE THREAD

**Issue by fangconquerord** [songquanpeng/one-api#127]
想用one api 将opeai api转化为azure openai的格式，目前遇到的问题是，执行：docker run -d --restart always -p 3000:3000 -v /home/ubuntu/data/one-api:/data justsong/one-api。后，通过主机ip访问并在渠道页面添加了 azure 和openai的key 各一个，都是测试过可以使用的。 设置令牌之后，使用https://github.com/lss233/chatgpt-for-bot-docs ，无论将 http://主机ip;3000 设置为 api_endpoint还是 proxy。均无法使用，但直接使用渠道页面添加的openai api是可以使用的。请问该如何设置

**Comment by songquanpeng** [comment]
应设置为 API Endpoint，你提到的这个项目貌似没什么热度，不排除项目本身的问题。

另外 One API 是把 Azure 的格式转换为 OpenAI 的格式，而不是反过来。

**Comment by fangconquerord** [comment]
> 应设置为 API Endpoint，你提到的这个项目貌似没什么热度，不排除项目本身的问题。
> 
> 另外 One API 是把 Azure 的格式转换为 OpenAI 的格式，而不是反过来。

是的，我需要的就是将Azure 的格式转换为 OpenAI 的格式，但是目前的情况是，我换了很多个github上面的项目， 都无法使用。
使用格式是：
api_endpoint = "http://主机ip:3000/"
api_key = "令牌中复制"
以这个格式放在很多的项目中都无法运行。
渠道中使用的是openai的api，点击测试，响应时间正常， 弹出页面反馈也正常
azure的api放在渠道中点击测试，响应时间正常， 但会显示 
DeploymentNotFound, message The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
名称为 azure上的部署名， 默认api版本设置2023-03-15-preview
请问，是否存在设置上的错误，该如何检查？

**Comment by songquanpeng** [comment]
设置上有问题，Azure 的部署名有要求的，设置界面有写。

**Comment by fangconquerord** [comment]
弄好了。。原来是 api_endpoint = "http://主机ip:3000/v1"要在后面加一个v1

> 

> #

**Comment by songquanpeng** [comment]
为防止其他人误解，我说明一下，这个是上面所提到的项目的格式要求，一般而言并不需要加 v1
