### ISSUE TITLE
最新版报错，insufficient_user_quota user quota is not enough (request id: 2024040323172594066980027391365)

### ISSUE THREAD

**Issue by okmad** [songquanpeng/one-api#1270]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
到今天上午一直好好的，下午就报错，
使用oneAPI v0.6.4，insufficient_user_quota user quota is not enough (request id: 2024040323172594066980027391365)
 2024040323132569916470074610378 | preConsumeQuota failed: {Error:{Message:user quota is not enough Type:one_api_error Param: Code:insufficient_user_quota} StatusCode:403}
[ERR] 2024/04/03 - 23:13:25 | 2024040323132569916470074610378 | relay error (channel #3): user quota is not enough (request id: 2024040323132569916470074610378)
试过 0.6.1 和0.5.8的版本，都一样的错误。请查。
我是本地电脑部署的，不存在余额不足的情况，也试过将无限余额改为有限，重新拉取docker compose，重启，都不行。

**复现步骤**

**预期结果**

**相关截图**
![屏幕截图 2024-04-03 231615](https://github.com/songquanpeng/one-api/assets/29192430/126e66b9-257e-4163-88ba-9e7dbaf0cb42)
![屏幕截图 2024-04-03 231656](https://github.com/songquanpeng/one-api/assets/29192430/29608365-b67f-4eda-9937-0ee38fdd214a)

**Comment by c121914yu** [comment]
账号余额没改

**Comment by QAbot-zh** [comment]
有没有可能，是你的渠道没有余额了？

**Comment by Linon419** [comment]
解决了吗，我也是偶尔出现这个问题

**Comment by okmad** [comment]
感谢大佬们的答复，我一直没有再用，小白水平不行，感觉这样部署的模型没啥质量可言。

**Comment by hemengjita** [comment]
中转平台的问题，换一个即可 ，我也是 请求频率上限了可能

**Comment by vincent0060** [comment]
> 账号余额没改

从结果反推的逻辑大概是：不管本地部署模型还是外部api免费模型，使用前都应将ticket所属用户的余额改为大于0，方法是
1. 管理员进入用户管理界面查看ticket所属用户的余额
2. 若余额不大于零，则编辑指定用户，设置余额大于0，并保存

![image](https://github.com/user-attachments/assets/24897ade-a362-4392-9476-9dca4707fbc6)

不幸的是，在我使用的版本上`v0.6.9-alpha.2`，编辑用户的余额并提示保存成功后，回到用户列表依然显示余额为0，且再次访问会提示相同的错误。不得已只能先用one-api内置的`root`账号创建ticket，完成技术验证
