### ISSUE TITLE
v1/models 接口返回 unexpected end of JSON input

### ISSUE THREAD

**Issue by RexWzh** [songquanpeng/one-api#1272]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

看仓库今天更新了对模型功能的支持 https://github.com/songquanpeng/one-api/issues/1060 ，开个新 issue 来跟踪测试~

`v1/models` 接口返回 `unexpected end of JSON input`

**复现步骤**

docker 更新到新版或 `v0.6.5-alpha.3` 版会提示这个错误：

```bash
curl --location --request GET 'https://.../v1/models' \
--header 'Authorization: Bearer sk-...' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: ... \
--header 'Connection: keep-alive' \
--data-raw ''
```

返回结果：

```bash
{"error":{"message":"common.UnmarshalBodyReusable failed: unexpected end of JSON input (request id: 2024040414255184119782326932492)","type":"one_api_error"}}
```

docker 日志：
```bash
one-api  | [ERR] 2024/04/04 - 14:27:51 | 2024040414275110400662582560516 | common.UnmarshalBodyReusable failed: unexpected end of JSON input 
one-api  | [GIN] 2024/04/04 - 14:27:51 | 2024040414275110400662582560516 | 400 |    1.117364ms |    209.141.57.3 |     GET /v1/models
```

此外，渠道正常，curl 能调用模型，但调用 v1/models 存在错误，如上。

当前问题可能有关联的 issue：https://github.com/songquanpeng/one-api/issues/66

![image](https://github.com/songquanpeng/one-api/assets/62223937/3e68bafb-13d7-40e4-9118-52c7e5a447c0)

**Comment by songquanpeng** [comment]
fixed
