### ISSUE TITLE
渠道自动禁用邮件通知的问题

### ISSUE THREAD

**Issue by popdo** [songquanpeng/one-api#1276]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

目前自动禁用渠道的判断

```
if strings.Contains(err.Message, "quota") {
		return true
	}
```

用户余额不足时是否也会将渠道禁用，是否会不合理，今天突然收到了上百份`user quota is not enough`自动禁用渠道邮件通知。这里判断的貌似不只是上游或渠道key余额不足，还包含用户的余额不足。

开启redis后，在高并发连续请求下 邮箱通知貌似一直都有bug，会瞬间收到十多二十多份重复的渠道自动禁用通知。不知道其他人是否有同样的情况。

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
这里的判断有问题，误判了，已经修复，感谢反馈

**Comment by songquanpeng** [comment]
v0.6.5-alpha.7
