### ISSUE TITLE
使用官方openai的流式调用方式，但模型返回的响应没有choice部分

### ISSUE THREAD

**Issue by ejie2** [songquanpeng/one-api#1278]
下面是代码中openai调用大模型的方式：
![图片](https://github.com/songquanpeng/one-api/assets/130576603/9b239e4a-4087-46a0-8dcb-c0efad0e500b)
然后是流式接收响应的过程：
![图片](https://github.com/songquanpeng/one-api/assets/130576603/be221b91-2213-4e7a-babf-57993c93b5d2)
最终会导致以下报错：
![图片](https://github.com/songquanpeng/one-api/assets/130576603/7417f7ed-5fa9-4074-845e-aacc16922a24)

**Comment by songquanpeng** [comment]
用的哪一个渠道呢？

**Comment by ejie2** [comment]
用的openai，日志显示如下：
![图片](https://github.com/songquanpeng/one-api/assets/130576603/1745d328-1c3d-4912-8150-47b4c7c088a7)

**Comment by ejie2** [comment]
用fastgpt平台我试了一下是可以的，但是用one api存在问题

**Comment by songquanpeng** [comment]
OpenAI渠道是直接relay的，就是原样转发

**Comment by ejie2** [comment]
日志上的显示是不是代表已经请求数据并且模型已经返回回应了呢

**Comment by ejie2** [comment]
解决了，流式输出时第一个消息为空消息要跳过
