### ISSUE TITLE
include groq in the readme

### ISSUE THREAD

**Issue by MemeFormer** [songquanpeng/one-api#1287]
**"_[Feature]_" Description**

I put it in quotes as it is just a friendly suggestion to include in the readme that this can also be used with groq. 

One would have to actively search in the issues to find that there are two posts buried that lead to the conclusion that groq seems to be supported as well. 

If there is a reason why it is not specifically mentioned, I apologize, and this issue can be ignored and closed without comment. Thank you.

![Uploading Screen Shot 2024-04-07 at 9.18.45 PM.png…]()
#https://github.com/songquanpeng/one-api/issues/1098
#https://github.com/songquanpeng/one-api/issues/1124

*Routine Check**

- [ ] I have confirmed that there are currently no similar issues
- [ ] I have confirmed that I have upgraded to the latest version
- [ ] I have thoroughly reviewed the project README and have determined that the existing version cannot meet the requirements
- [ ] I understand and am willing to follow up on this issue, assisting in testing and providing feedback
- [ ] I understand and agree to the above, and understand that the project maintainers have limited resources, **issues that do not follow the rules may be ignored or closed directly**

**应用场景**

**Comment by manjieqi** [comment]
![image](https://github.com/songquanpeng/one-api/assets/40858189/47e6a481-0eb7-49f0-892b-3b29164c7320)

**Comment by MemeFormer** [comment]
🤓🙈
