### ISSUE TITLE
The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### ISSUE THREAD

**Issue by cwsz06** [songquanpeng/one-api#1294]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
  添加text-embedding-ada-002,就提示报错The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
  不添加就提示 当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道
  
**复现步骤**
已经按照issue反复操作 还是提示该错误。昨天成功过5分钟，然后马上出现该错误
**预期结果**
能够正常运行
**相关截图**
<img width="824" alt="微信图片_20240410143709" src="https://github.com/songquanpeng/one-api/assets/162421651/ecf41868-c0e2-41b2-8d9e-73be957120fb">
![1712731067469](https://github.com/songquanpeng/one-api/assets/162421651/51d4a0b2-b43d-400e-a941-93a11fd447f3)
![image](https://github.com/songquanpeng/one-api/assets/162421651/ec08a8ea-4678-46e9-ae45-62824887f82f)

。

**Comment by cwsz06** [comment]
已解决

**Comment by songquanpeng** [comment]
如果方便的话可以分享一下是如何解决的
