### ISSUE TITLE
Gemini-1.5-pro 接口报错

### ISSUE THREAD

**Issue by chenwynn** [songquanpeng/one-api#1295]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
调用google gemini-1.5-pro 报错

错误：status code 404: models/gemini-1.5-pro is not found for API version v1, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.

**复现步骤**
选择模型gemini-1.5-pro
点击渠道进行测试

**预期结果**
正常返回

**相关截图**
<img width="1365" alt="Screenshot 2024-04-10 at 20 09 58" src="https://github.com/songquanpeng/one-api/assets/7459563/fa93f85b-465b-49ac-8964-56edc78fe524">

如果没有的话，请删除此节。

**Comment by doveppp** [comment]
请问怎么解决的？
