### ISSUE TITLE
登录后带上令牌或渠道请求报错

### ISSUE THREAD

**Issue by luke-zhang580** [songquanpeng/one-api#13]
![image](https://user-images.githubusercontent.com/45325652/234194040-ff6d817b-3382-4696-9ea5-4b0746001345.png)

**Comment by songquanpeng** [comment]
这个不应该啊，请确认令牌是有效的。

另外这个报错信息马上就会得到修改，当前的报错信息不够明确。

**Comment by songquanpeng** [comment]
如果未能解决问题，欢迎重开 issue。

**Comment by luke-zhang580** [comment]
可以了，是我的问题，我以为是使用令牌名。

**Comment by songquanpeng** [comment]
好的，如果还有其他问题，欢迎开新 issue 继续反馈。
