### ISSUE TITLE
频繁出现：负载已满，请稍后再试，或升级账户以提升服务质量。

### ISSUE THREAD

**Issue by zhiqiangwong** [songquanpeng/one-api#130]
后台添加多个渠道后频繁出现报错：负载已满，请稍后再试，或升级账户以提升服务质量。

**Comment by songquanpeng** [comment]
这个是 OpenAI 服务器报了 403，升级账户这个是考虑到后续的用户组加的，目前还没有此功能。

**Comment by songquanpeng** [comment]
用户组功能已经实现。

如果该问题依旧存在，欢迎重开 issue。
