### ISSUE TITLE
请求加入AWS bedrock anthropic claude

### ISSUE THREAD

**Issue by yf319** [songquanpeng/one-api#1300]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
使用aws的key_id和秘钥请求claude
**应用场景**

**Comment by yf319** [comment]
https://github.com/aws-samples/amazon-bedrock-samples/blob/main/introduction-to-bedrock/bedrock_api.py

**Comment by liubo20190515** [comment]
+1

**Comment by liuhetian** [comment]
#749 作者正在开发

**Comment by lp380490944** [comment]
臣附议+1
