### ISSUE TITLE
配置GLM4，status code 401: Header中未收到Authorization参数，无法进行身份验证。

### ISSUE THREAD

**Issue by Essence9999** [songquanpeng/one-api#1301]
**问题描述**
![image](https://github.com/songquanpeng/one-api/assets/66725845/c5a99e38-029c-41c0-b0b1-765c175e7378)

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/66725845/3cf34fe6-fcf0-46bc-96d9-0af20a8a166c)
单独curl测，没有问题
![image](https://github.com/songquanpeng/one-api/assets/66725845/2205efe0-d6ac-4a64-bdfa-ae08ec046d8f)

**Comment by QAbot-zh** [comment]
oneapi 也没说支持glm逆向呀，glm渠道默认是key模式

**Comment by songquanpeng** [comment]
很奇怪，我试了一下拿这个 jwt cookie 请求，结果是 400：
![image](https://github.com/songquanpeng/one-api/assets/39998050/edf01ee7-33f4-4a10-8835-7b58d1559044)

**Comment by songquanpeng** [comment]
issue 先关了，有问题请重开 issue
