### ISSUE TITLE
one-api对接NextChat或者lobe-chat

### ISSUE THREAD

**Issue by zxw186** [songquanpeng/one-api#1303]
在对接NextChat或者lobe-chat页面时你们是怎么对接的可以正常用吗？我v0.6.5-alpha.18这个版本的添加的是讯飞的大模型-》在令牌中占地聊天按钮跳到NextChat页面后需要确认添加预制的设置，后还用配置什么吗？请求指导下。

**Comment by QAbot-zh** [comment]
在oneapi里配置一下设置里的“聊天链接”和“服务器地址”就好，然后从令牌的聊天跳转到nextchat选择确认，就自动填入配置了，当然nextchat默认支持的模型里是没有讯飞的，再到nextchat的设置项里添加讯飞的模型名称就可以调用讯飞了（如果是自己部署的nextchat，也可以通过环境变量添加自定义的模型名称）
![image](https://github.com/songquanpeng/one-api/assets/40236765/1a8b2286-f9f4-47b6-a45c-08a20da10c41)

**Comment by zxw186** [comment]
好的，谢谢！

**Comment by zxw186** [comment]
![1713143118339](https://github.com/songquanpeng/one-api/assets/154959381/982f6b70-9368-4235-b185-75be580f8551)

![1713143041500](https://github.com/songquanpeng/one-api/assets/154959381/2d392a75-3a30-44a2-a6b2-e2f457a385ac)
![1713143222973](https://github.com/songquanpeng/one-api/assets/154959381/5f551abd-c107-48af-a232-ee3d48a16aa9)
再请教下，1.默认支持Azure open ai 吗？2.我添加了聊天链接和服务器地址也不行 3.是只支持open ai吗

**Comment by yongshengma** [comment]
默认支持Azure open ai ，在渠道设置里配置key & endpoint

**Comment by zxw186** [comment]
好的，谢谢发自我的 iPhone在 2024年4月19日，12:19，Yongsheng Ma ***@***.***> 写道：﻿
默认支持Azure open ai ，在渠道设置里配置key & endpoint
