### ISSUE TITLE
ollama的嵌入模型调用错误

### ISSUE THREAD

**Issue by wwjCMP** [songquanpeng/one-api#1305]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
docker部署的。设置如下图，当填入聊天模式的时候，测试没有问题。但填入嵌入模式的时候，有400错误。是ollama那边设置的问题吗？
**复现步骤**

**预期结果**

**相关截图**
![Snipaste_2024-04-13_11-21-11](https://github.com/songquanpeng/one-api/assets/32979859/d9a7e9ae-062d-4385-ab98-959e1c16f6a3)
![Snipaste_2024-04-13_11-12-51](https://github.com/songquanpeng/one-api/assets/32979859/1e731853-d41e-4d8f-a84d-6de56b1d912a)
![Snipaste_2024-04-13_11-13-56](https://github.com/songquanpeng/one-api/assets/32979859/a9224c72-7ca4-472b-a075-95d8188d534c)
![Snipaste_2024-04-13_11-16-54](https://github.com/songquanpeng/one-api/assets/32979859/28022523-d5f4-4f7b-ae6e-ed27e781e957)

https://github.com/songquanpeng/one-api/pull/1221
https://github.com/songquanpeng/one-api/issues/1159

**Comment by songquanpeng** [comment]
目前测试只支持测试聊天模型

**Comment by songquanpeng** [comment]
这个之后优化吧，issue 先留着

**Comment by nigo81** [comment]
同样需要使用ollama的embedding模型nomic。因为使用的mac，使用m3e时只能使用cpu，太慢了，希望能用ollama的nomic模型来作为embedding.

**Comment by songquanpeng** [comment]
> 同样需要使用ollama的embedding模型nomic。因为使用的mac，使用m3e时只能使用cpu，太慢了，希望能用ollama的nomic模型来作为embedding.

这个接口不应该是一样的么？

**Comment by LuckyGJX** [comment]
同样连接拒绝，使用ollama，希望尽快支持～
<img width="1325" alt="image" src="https://github.com/songquanpeng/one-api/assets/40716960/f0917e83-3274-495e-b6d3-e5f8252eee34">

**Comment by RexWzh** [comment]
ollama [文档](https://ollama.com/blog/embedding-models)写了后续会把 embedding 也 OpenAI 化，**OneAPI 完全没必要重复造轮子。**
<img width="665" alt="image" src="https://github.com/songquanpeng/one-api/assets/62223937/1aa7e053-0722-40eb-a91f-c24f8f8d670c">

如果实在急着用，自己手写个 flask。参考个人写过的一段代码，如果懒得改，连同 Ollama 当前的调用方式丢给 GPT 转一下：

```python
from flask import Flask, request, jsonify
from sentence_transformers import SentenceTransformer
app = Flask(__name__)
# 加载模型
model_path = '/sshfs/pretrains/moka-ai/m3e-large'
model = SentenceTransformer(model_path)

@app.route('/v1/embeddings', methods=['POST'])
def get_embeddings():
    data = request.get_json()
    if not all((data, 'input' in data, 'model' in data)):
        return jsonify({"error": "Missing required fields in request body"}), 400
    input_text = data['input']
    # 将单个输入转换为列表
    if isinstance(input_text, str):
        input_text = [input_text]
    # 调用模型获取 embeddings
    embeddings = model.encode(input_text)
    # 构造响应
    embeddings_response = []
    for index, embedding in enumerate(embeddings):
        embedding_dict = {
            "object": "embedding",
            "embedding": embedding.tolist(),  # 将 numpy 数组转换为列表
            "index": index
        }
        embeddings_response.append(embedding_dict)
    # 可选: Token 计数
    response = {
        "object": "list",
        "data": embeddings_response,
        "model": data['model'],
        "usage": {
            "prompt_tokens": sum(len(text.split()) for text in input_text), 
            "total_tokens": sum(len(text.split()) for text in input_text)
        }
    }
    return jsonify(response)

if __name__ == '__main__':
    app.run(debug=True, port=5000, host='0.0.0.0')
```
