### ISSUE TITLE
模型重定向只能保留一个

### ISSUE THREAD

**Issue by iamsad3508** [songquanpeng/one-api#1307]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在渠道的模型重定向添加多个时，会只剩下一个
**复现步骤**
在渠道里面添加 
{
  "gpt-4-turbo": "gpt-4-vision-preview",
  "gpt-4-turbo":"gpt-4-turbo-preview"
}
结果保存后变成这样，不知道是不是我都这个键和值理解错了
{
  "gpt-4-turbo": "gpt-4-turbo-preview"
}

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by QAbot-zh** [comment]
字典的键当然是不能重复的

**Comment by iamsad3508** [comment]
主要我看说明“格式为：api请求模型ID:实际转发给渠道的模型ID，使用JSON数组表示，例如：{"gpt-3.5": "gpt-35"}”
或者另外一个说明"
"gpt-3.5-turbo-0301": "gpt-3.5-turbo',
 "gpt-4-0314": "gpt-4",
"gpt-4-32k-0314": "gpt-4-32k""
都感觉是我请求gpt-35，然后实际请求给openai服务器的是gpt-3.5（毕竟给openai服务器请求gpt-35是不合理的，所以我这么想），希望作者能理解我说什么，先close了

**Comment by QAbot-zh** [comment]
左是用户传入的请求模型，右是给上游的请求模型，左的模型名不能重复，右无所谓

**Comment by RexWzh** [comment]
我添加渠道基本看着提示弄的，不然容易混 🤣 


<img width="757" alt="image" src="https://github.com/songquanpeng/one-api/assets/62223937/13f83f63-c78f-4b97-8496-f6e35ff1eda3">
