### ISSUE TITLE
Google AI studio Gemini-1.5-Pro 的模型名称应该是 gemini-1.5-pro-latest 并且需要使用 v1beta API

### ISSUE THREAD

**Issue by ShinChven** [songquanpeng/one-api#1308]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

Google AI studio Gemini-1.5-Pro 的模型名称应该是 gemini-1.5-pro-latest 并且需要使用 v1beta API

https://github.com/google-gemini/cookbook/issues/52#issuecomment-2053605198

https://ai.google.dev/docs/api_versions

**复现步骤**

**预期结果**

**相关截图**

<img width="1039" alt="image" src="https://github.com/songquanpeng/one-api/assets/3351486/26585b0c-95a3-4df6-a94a-933d5f6ab021">

**Comment by katyshawn922** [comment]
添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有

**Comment by kdkkkd** [comment]
> 添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有

如何使用berry主题啊？

**Comment by ShinChven** [comment]
> > 添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有
> 
> 如何使用berry主题啊？

      - THEME=berry

**Comment by ShinChven** [comment]
> 添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有

感谢

**Comment by plusye** [comment]
> 添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有

默认的主题并没有 🤣

**Comment by kdkkkd** [comment]
> 添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有

直接填版本号就行？还需要修改变量吗？

**Comment by katyshawn922** [comment]
> > 添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有
> 
> 直接填版本号就行？还需要修改变量吗？

填v1beta就可以，模型映射里把gemini-1.5-pro映射到gemini-1.5-pro-latest

**Comment by kdkkkd** [comment]
> > > 添加Gemini渠道时有个版本选项，填v1beta即可，我是berry主题，不清楚其他的有没有
> > 
> > 直接填版本号就行？还需要修改变量吗？
> 
> 填v1beta就可以，模型映射里把gemini-1.5-pro映射到gemini-1.5-pro-latest

好的感谢
