### ISSUE TITLE
It is recommended to archive the repository.

### ISSUE THREAD

**Issue by ukllla** [songquanpeng/one-api#1309]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Refactoring progress is slow, old and new code are mixed, and bugs are repeated.

**预期结果**
Archive the repository

**Comment by songquanpeng** [comment]
I have a full-time job,  already trying to maintain this open source project as much as I can. 

If you find some so-called repeated bugs,  you can submit related issues and wait someone to use their own spare time to fix it.
