### ISSUE TITLE
当前版本的自动重试逻辑不工作

### ISSUE THREAD

**Issue by shuiRong** [songquanpeng/one-api#1314]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
虽然有类似issue，但我都翻看过了，和我这个不一样。

类似issue: 
https://github.com/songquanpeng/one-api/issues/361
https://github.com/songquanpeng/one-api/issues/1048

+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
自动重试机制不能正常工作。

**复现步骤**
稳定复现。

1. 本地起两个模拟 OpenAI Chat 的接口
`http://localhost:3008/v1/chat/completions`
`http://localhost:3009/v1/chat/completions`
返回数据写死就行，其中3008端口程序返回200，3009端口程序返回401。
2. 拉最新版 one-api 代码跑起来。使用上面两个 `http://localhost:3008` `http://localhost:3009` 地址创建两个渠道。
3. 在设置-运营设置-失败重试次数 里把次数设置成2，保存。
4. 生成一个令牌测试用。
5. 在 Postman（接口测试工具）里调用本地的 one-api：http://localhost:3000/v1/chat/completions 
请求体随便写，比如：
```json
{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "You are a helpful assistant.1"
        },
        {
            "role": "user",
            "content": "Hello!"
        }
    ],
    "stream": false
}
```
然后在Postman里测试 one-api 的失败自动重试功能。因为两个渠道是随机响应的，所以可以多试几次。主要是要让 one-api 先请求 3009 那个接口，走重试逻辑。

会在 one-api 控制台看到：
```bash
/Users/xxx/Work/one-api/model/ability.go:37 record not found
[0.681ms] [rows:0] SELECT * FROM `abilities` WHERE `group` = "default" and model = "" and enabled = 1 and priority = (SELECT MAX(priority) FROM `abilities` WHERE `group` = "default" and model = "" and enabled = 1) ORDER BY RANDOM(),`abilities`.`group` LIMIT 1
[ERR] 2024/04/14 - 22:25:40 | 2024041422253575689900005697372 | CacheGetRandomSatisfiedChannel failed: %!w(*errors.errorString=&{record not found}) 
[GIN] 2024/04/14 - 22:25:40 | 2024041422253575689900005697372 | 500 |  5.017596583s |             ::1 |    POST /v1/chat/completions
```

也就是说这个 SQL 没有查询到可用的渠道，所以就不会重试。（明明还有3008端口的渠道）
问题出在：model = "" 和 priority = NULL 上
<img width="821" alt="image" src="https://github.com/songquanpeng/one-api/assets/16076993/1f9ba183-077b-4ef5-80d3-0c27ad4c0508">

如果我手动把 model = "gpt-3.5-turbo"、priority = 0 的话，就能查询到数据，进而可以走完重试流程。
<img width="1293" alt="image" src="https://github.com/songquanpeng/one-api/assets/16076993/2eb43c95-d1d2-4403-aafa-d8c2935bf1d2">

> 重试这里，多说两句留给其他用户看：我这里有两个渠道，请求 3009 渠道出错的前提下，随机（可能是随机）找一个可用渠道，但但观察到仍旧有可能找到当前这个错误的渠道。不是说随机找时就排除了自己。

**预期结果**

上面的SQL语句（GetRandomSatisfiedChannel）可以查询到可用渠道，然后顺利走完剩下的重试逻辑。

**Comment by c121914yu** [comment]
+1正式版无效了，之前alpha还是ok的

**Comment by songquanpeng** [comment]
重新推送了正式版，请等待打包，感谢反馈，确实是最近的一次改动导致的 bug
