### ISSUE TITLE
希望增加cloudflare workers AI的`REST API`透明代理支持

### ISSUE THREAD

**Issue by ZeroDeng01** [songquanpeng/one-api#1322]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望增加cloudflare workers AI的`REST API`请求方式的相关支持，`workers AI`已经支持了大量的模型，其中包括`stable diffusion`等图像相关的api。
**应用场景**
workers AI提供了可观的免费额度。中国境内api访问也比较友好，目前测试延迟都比较低。阿里的stable diffusion申请api有一定的门槛，需要企业用户才能申请，对于不想使用企业身份并且不具备自己部署stable diffusion的用户来说不太友好,而cloudflare比较灵活
开发文档路径：https://developers.cloudflare.com/workers-ai/get-started/rest-api/
支持的模型：https://developers.cloudflare.com/workers-ai/models/

![image](https://github.com/songquanpeng/one-api/assets/19732560/0fc632d7-8b0f-43cb-80dc-4182c82c266a)

**Comment by songquanpeng** [comment]
了解，需要时间处理，期待 PR

**Comment by ccbikai** [comment]
Workers AI 有 playground 了

https://playground.ai.cloudflare.com/

**Comment by carey036** [comment]
在添加渠道的时候好像还是没有选项？是不是忘记添加了
