### ISSUE TITLE
 azure 用stream=True返回报错

### ISSUE THREAD

**Issue by akakenle** [songquanpeng/one-api#1324]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
one api接入微软的azure gpt-4-0125-preview模型是无法支持流式输出
**复现步骤**
completion = client.chat.completions.create(
  model="gpt-4-0125-preview",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ],
  stream=True
)

for chunk in completion:
  print(chunk.choices[0].delta)

**预期结果**
测试代码用的是官方的；微软渠道会报错，官方渠道的就是正常的返回
**相关截图**
![0471726322652a7401366725dddaea93](https://github.com/songquanpeng/one-api/assets/12624481/2ae89c6b-20c0-4ad3-9ed0-d2169cf71f7c)

**Comment by ImYrS** [comment]
报错已经很清晰解释了错误信息 `IndexError` 在 `chunk.choices[0].delta` 只能是 `choices` 为空数组. Azure 接口一直都有这个情况, 做 continue 即可

**Comment by songquanpeng** [comment]
现在当 One API 检测到 choice 为空会直接跳过
