### ISSUE TITLE
0.6.5版本中gpt-4带preview模型的价格不对

### ISSUE THREAD

**Issue by CNWann** [songquanpeng/one-api#1326]
在测试0.6.5的价格中发现，带preview的gpt-4模型价格不对，带turbo价格正常，应该是relay/billing/ratio/model.go文件改动导致的异常。gpt-4中的preview和turbo价格一致，补全倍数应该都是3。

gpt4部分补全倍数代码修改之后测试正常：
![图片](https://github.com/songquanpeng/one-api/assets/26641645/75775ac1-142d-48fb-953b-7d94ff16d193)

![1](https://github.com/songquanpeng/one-api/assets/26641645/e2364752-8603-42ab-9067-d2cd9b1e9491)
![2](https://github.com/songquanpeng/one-api/assets/26641645/c824ccdf-1930-449b-9ce0-ca195357cefb)
![3](https://github.com/songquanpeng/one-api/assets/26641645/9e99557a-6a1a-41fd-9b74-4ac5cb884d19)

**Comment by songquanpeng** [comment]
已经修复，今天之内推送
