### ISSUE TITLE
Azure 渠道测试报错：The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### ISSUE THREAD

**Issue by assez** [songquanpeng/one-api#133]
错误：type , code DeploymentNotFound, message The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

添加后测试老是不成功提示这个

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/de201846-1538-4daf-818a-e42f6bd07f61)

**Comment by songquanpeng** [comment]
已添加图片提示。

**Comment by assez** [comment]
感谢，已成功

**Comment by hehan-wang** [comment]
有些情况没有办法一致怎么办呢？

**Comment by Plandres** [comment]
Azure已更新gpt-35-turbo-16k，添加后出现同样报错，已确认部署名和模型名称相同

**Comment by caixiaomao** [comment]
> Azure已更新gpt-35-turbo-16k，添加后出现同样报错，已确认部署名和模型名称相同

同样报错，确定模型名称和部署名称一致

**Comment by yanxiaochuan** [comment]
16k依旧报错

**Comment by sadlay** [comment]
> 我不太理解为什么需要完全一致，调用Azure服务只需要部署名称吧

**Comment by ivanberry** [comment]
<img width="567" alt="image" src="https://github.com/songquanpeng/one-api/assets/13112910/6bdcc470-cb6c-480c-98c0-2aaaa84772cd">

渠道测试通不过，chat功能提示用不了

**Comment by borlandapple** [comment]
azure的部署里与模型名称保持一致
<img width="1019" alt="image" src="https://github.com/songquanpeng/one-api/assets/23301989/d0e93e7c-e8eb-4e4d-9aa8-fecd270fc1a5">
在oneapi里配置渠道
![image](https://github.com/songquanpeng/one-api/assets/23301989/d702443b-c576-446c-884e-24517c7c4827)
秘钥去azure的开发里找
<img width="1406" alt="image" src="https://github.com/songquanpeng/one-api/assets/23301989/7325cf39-15a6-49ea-b4ca-6ffee788a17f">
然后在fastGPT的config.json里配置azure的openai通道，注意配置文件里model字段与openai是一致的，所以azure的openai与openai你只能保留一个，要不默认用的前面配置的那个model
<img width="408" alt="image" src="https://github.com/songquanpeng/one-api/assets/23301989/6b598c1b-6d28-4017-a20a-766e288244e0">
另外azure的openai好像不支持functionCall，在CQModel里配置为true会报错

**Comment by dimsky** [comment]
这个部署名必须跟模型名一致要求不灵活，如果该模型有多个版本时，却只能添加一个版本（因为部署名是唯一的），如果我需要在该区域下同时添加 1106 和  vision  版本，该怎么办？
![gpt-4](https://github.com/songquanpeng/one-api/assets/3078485/dab69931-ee1e-4c8b-a05e-b6a788d35c55)

**Comment by borlandapple** [comment]
抱歉哈，这个好像是one-api要求的，你添加的时候看看说明，当时我也是搞了好久才试出来




啪嚓
***@***.***



&nbsp;

**Comment by songquanpeng** [comment]
这里之后优化，我先记下了

**Comment by jackfong66** [comment]
> 这里之后优化，我先记下了

大佬，这个兼容了没。

**Comment by warjiang** [comment]
> > 这里之后优化，我先记下了
> 
> 大佬，这个兼容了没。

感觉他们似乎在干重构的事情。

https://github.com/warjiang/one-api/tree/feature/azure-openai 我改了一个版本，可以试试。

使用方式，docker镜像修改为`warjiang/one-api:v1.0.2`
直接在数据库里面修改channel表的config字段，找到azure对应的config字段配置，设置为
```json
{
    "deployment_configs": [
        {
            "model_name": "gpt-3.5-turbo",
            "deployment_name": "deployment-xxx",
            "api_version": "2023-07-01-preview"
        }
    ]
}
```
model_name是前端用户传入的接口调用里面的字段，deployment_name是在azure上面创建模型部署对应的名字。

前端的配置我还没搞，有空加下。

**Comment by warjiang** [comment]
> 这里之后优化，我先记下了

感觉改的有点多，我把loadConfig那边的干掉了，担心不一定符合你们官方团队的想法。要是可以的话，可以帮我review下

**Comment by borlandapple** [comment]
你好：
&nbsp; &nbsp; 不好意思，我对python不是太熟悉，也没有详细去看，我是拿来主义，在验证产品，十分感谢你这样的热心程序员，加油


啪嚓
***@***.***



&nbsp;

**Comment by yuanzhiwei** [comment]
请问一下16k报错是否修复了呀?

**Comment by qingfengfenga** [comment]
实测相同模型部署名称会被覆盖

想问一下，模型部署名称和模型名称必须保持一致的话，同一个模型多个版本怎么办？

**Comment by cwsz06** [comment]
还是会报错

**Comment by huhu415** [comment]
首先我在Azure上部署了一个名称为gpt-4-1106-Preview的gpt4的1106-Preview版本的模型. 所以官网给出的代码是
`curl "https://pay.openai.azure.com/openai/deployments/gpt-4-1106-Preview/chat/completions?api-version=2024-02-15-preview"`
其中gpt-4-1106-Preview就是我自己命名的那个名称. 如下图:
<img width="1512" alt="截屏2024-04-22 14 43 06" src="https://github.com/songquanpeng/one-api/assets/93107032/a73bbe19-48ac-4286-ae71-b65bf2613bc8">

问题是one-api应该怎么去使用这个模型? 
<img width="792" alt="截屏2024-04-22 14 46 45" src="https://github.com/songquanpeng/one-api/assets/93107032/6dc85bf3-5aaf-4eff-b22f-6917c5c680e1">
如图, 只要你的one-api中的‘模型’, 和你自定的名称对上了, 那么就好使了.

**Comment by huhu415** [comment]
外加一点, 希望你自定义的名称, 是从标准名称里面找的, 要不然后期找不到了, 还要再折腾

**Comment by imotai** [comment]
如果强调模型名称和部署名称一致，可以在前端强制校验，让错误更早暴露出来，我自己配置，都是错误了 一遍，然后再回头看提示

**Comment by ljq29** [comment]
现在有个问题，Azure后台可以部署名-模型名不一致，是否oneapi可以支持这种情况？

**Comment by warjiang** [comment]
> 现在有个问题，Azure后台可以部署名-模型名不一致，是否oneapi可以支持这种情况？

I thinks it's ok, maybe I can try it

**Comment by borlandapple** [comment]
抱歉哈，很久不用了，我也没深入研究过，就当时使用的坑发到评论上了


啪嚓
***@***.***
