### ISSUE TITLE
聊天按钮里找不到 ChatGPT next web

### ISSUE THREAD

**Issue by yongshengma** [songquanpeng/one-api#1330]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
聊天按钮里找不到 chatgpt next web (next chat)，以前版本里有。

**复现步骤**

**预期结果**

**相关截图**
![51d8e45fd90ab23e0dbbb2c880dc2ab4](https://github.com/songquanpeng/one-api/assets/17973897/69d1faf4-9b51-404b-b698-4efe8d8a2c64)

**Comment by Towski0804** [comment]
我也一样，你应该部署的是v0.6.6-alpha版本吧

**Comment by songquanpeng** [comment]
直接点聊天按钮就好了，应该是一个 PR 给改掉了，现在下拉框中确实不存在了

**Comment by songquanpeng** [comment]
已经修复
