### ISSUE TITLE
千帆 ERNIE-3.5-8K 返回的错误信息被截断，导致 invalid character 'r' ...

### ISSUE THREAD

**Issue by Lead-NorthStar** [songquanpeng/one-api#1332]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
千帆 ERNIE-3.5-8K 的流式，出错的时候，错误信息被截断，导致错误无法被 json 解析。我看有很多反馈 invalid character 'r' 类似错误的，应该都是同样原因，{"error_code": 被截断成了 r_code":  。

**复现步骤**
让流式聊天出错，其他的模式出错可能也会有同样问题，但还没有世界测试过。
![C88B0436-F08B-4f45-81B0-3DEFC8B3BF17](https://github.com/songquanpeng/one-api/assets/139985926/c62554ef-52ec-4082-ad4d-1e556eaeaab1)

**预期结果**

**相关截图**
![图片](https://github.com/songquanpeng/one-api/assets/139985926/01025061-a086-4ee3-813d-7cf2bda2e240)
![图片](https://github.com/songquanpeng/one-api/assets/139985926/5cd2f967-10a8-4b03-90e5-39687b260d79)

**Comment by QAbot-zh** [comment]
"the role of message with odd index in the messages must be assistant”， 这说的不是你调用的问题吗？历史消息里assistant和user应该交替出现，不要连续使用user

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/79289217-4743-4c72-9340-53d3f4db86ad)
麻烦发一下这里的响应头，我现在手里没有 baidu 的 key，无法自己测试

**Comment by Lead-NorthStar** [comment]
是这个吗？
[{"key":"access-control-allow-headers","value":"Content-Type"},{"key":"access-control-allow-origin","value":"*"},{"key":"appid","value":"45042944"},{"key":"content-length","value":"125"},{"key":"content-type","value":"application/json; charset=utf-8"},{"key":"date","value":"Sat, 20 Apr 2024 03:57:16 GMT"},{"key":"p3p","value":"CP=\" OTI DSP COR IVA OUR IND COM \""},{"key":"server","value":"Apache"},{"key":"x-aipe-self-def","value":"eb_total_tokens:0,prompt_tokens:0,id:as-94i2u77vks"},{"key":"x-baidu-request-id","value":"e95fae01f0e7326f06c910accbdb49b21000079"},{"key":"x-openapi-server-timestamp","value":"1713585436"}]

**Comment by Lead-NorthStar** [comment]
> ![image](https://private-user-images.githubusercontent.com/39998050/324047851-79289217-4743-4c72-9340-53d3f4db86ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODU2MjMsIm5iZiI6MTcxMzU4NTMyMywicGF0aCI6Ii8zOTk5ODA1MC8zMjQwNDc4NTEtNzkyODkyMTctNDc0My00YzcyLTkzNDAtNTNkM2Y0ZGI4NmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDAzNTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MmIwNjYzNjJkMmRiMWIwNjQzMTk0ZGQ1MTQ2NTA1OTYzMjg0MmNlYjZiMGJjZGE5NTg2OTI3MGMyYmM4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xh1RXz-acWBKDluyfel6ewsCLMdTxRvJbPZNml5u6gA) 麻烦发一下这里的响应头，我现在手里没有 baidu 的 key，无法自己测试

是这个吗？
[{"key":"access-control-allow-headers","value":"Content-Type"},{"key":"access-control-allow-origin","value":"*"},{"key":"appid","value":"45042944"},{"key":"content-length","value":"125"},{"key":"content-type","value":"application/json; charset=utf-8"},{"key":"date","value":"Sat, 20 Apr 2024 03:57:16 GMT"},{"key":"p3p","value":"CP=" OTI DSP COR IVA OUR IND COM ""},{"key":"server","value":"Apache"},{"key":"x-aipe-self-def","value":"eb_total_tokens:0,prompt_tokens:0,id:as-94i2u77vks"},{"key":"x-baidu-request-id","value":"e95fae01f0e7326f06c910accbdb49b21000079"},{"key":"x-openapi-server-timestamp","value":"1713585436"}]

**Comment by Lead-NorthStar** [comment]
> "the role of message with odd index in the messages must be assistant”， 这说的不是你调用的问题吗？历史消息里assistant和user应该交替出现，不要连续使用user

我知道是这个导致的错误，但这里说的是百度那边回复的错误信息，被 one-api 服务器接受的时候，前6个字符被截断了，导致错误信息无法被正常解析。

**Comment by songquanpeng** [comment]
> application/json; charset=utf-8 

最新版本试一下呢？修复了这里的检查，兼容了这种 content type

**Comment by songquanpeng** [comment]
issue 先关了，有问题请重开 issue

**Comment by Lead-NorthStar** [comment]
好的，麻烦了
