### ISSUE TITLE
[BUG]  新渠道 Aws Claude 模型支持的一些问题 

### ISSUE THREAD

**Issue by 0x5c0f** [songquanpeng/one-api#1336]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
### 应该是3个问题: 
1.  `Aws Claude` 渠道，在容器镜像 `v0.6.5` 中是无法设置的，只有`latest` 有，不知这个目前是否还处于测试阶段。
2.  在默认主题中，应该还没有完全适配这个渠道，按照界面提示的配置项配之后，仍然提示`渠道名称和渠道密钥`未配置，估计这个是校验的适配问题还未调整(这个我已经清理过浏览器缓存了，目前仍然存在这个问题)。
3. 最后一个是关于`berry`主题的，这个就完全没有 `Aws Claude` 这个渠道了

**复现步骤**
1.   我是容器部署，我固定版本`v0.6.5` 启动，无`Aws Claude`渠道，拉取最新`latest`镜像，存在相关渠道，但`berry`无

**预期结果**

正常配置

**Comment by ye4293** [comment]
berry版本，应该不是作者主要维护的。所以兼容看心情

**Comment by songquanpeng** [comment]
default 修复了，其他主题不是看心情哈，我真的没有多余精力一次改三个前端

**Comment by 0x5c0f** [comment]
> default 修复了，其他主题不是看心情哈，我真的没有多余精力一次改三个前端，期待有人能 PR

这个是我是知道的，我就是想反馈默认主题目前无法使用的问题。
