### ISSUE TITLE
不符合dall-e-3模型参数要求的请求仍会被发送

### ISSUE THREAD

**Issue by manjieqi** [songquanpeng/one-api#1337]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
目前，dall-e-3模型只能画一张图，但是当客户端请求n>1的时候，oneapi还是将请求发送给了azure（并且由于返回是错误代码，oneapi并没有记录），但是azure目前似乎有bug，会对错误响应计费，为了避免恶意请求导致的扣费，建议停止发送n>1的dall-e-3模型请求。

关于有没有扣费的问题，客服调出了请求的响应码和次数，最后是说因为是赠送额度所以无法退费。

**复现步骤**
<img width="600" alt="Snipaste_2024-04-20_10-28-54" src="https://github.com/songquanpeng/one-api/assets/40858189/10b3fe93-604b-46f8-a0e3-db43cf7a1ba6">

**Comment by ye4293** [comment]
这种情况不是属于az的bug吗 不关one的事了呀..

**Comment by manjieqi** [comment]
> 这种情况不是属于az的bug吗 不关one的事了呀..

![image](https://github.com/songquanpeng/one-api/assets/40858189/846c52f8-aff0-49ab-a35d-68aa7f0d08bb)
