### ISSUE TITLE
目前自定义渠道不支持 HTTP 了吗？

### ISSUE THREAD

**Issue by tisfeng** [songquanpeng/one-api#1340]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

我有个 HTTP 的自定义渠道 Base URL  http://xxx:8001 ，之前运行好好的，最近更新镜像后就不行了。

我尝试用 caddy 申请了 HTTPS 证书，Base URL 改成 https://xxx 就可以了。

是项目最近修改了什么吗？

报错信息：
> do request failed: Post "http://xxx:8001/v1/chat/completions": dial tcp 45.xx.xx.158:8001: i/o timeout (request id: 2024042014382141460288990642676)

**复现步骤**

**预期结果**

自定义渠道支持 HTTP 

**相关截图**

## HTTP 报错
<img width="1427" alt="image" src="https://github.com/songquanpeng/one-api/assets/25194972/33dc750a-097f-496a-b1f3-b94e753b41b9">

## HTTPS 正常
<img width="1417" alt="image" src="https://github.com/songquanpeng/one-api/assets/25194972/19a5aaa1-68e3-4ed0-86b5-a1fd1a596a4d">

**Comment by songquanpeng** [comment]
没有这方便的改动，你先用 postman 试一下 http 版本能不能访问哈

**Comment by songquanpeng** [comment]
issue 先关了，有问题请重开 issue

**Comment by tisfeng** [comment]
好像是我的问题，我用另一台机器部署渠道服务，HTTP 没有问题。

可能是因为这个渠道服务和 one-api 都部署在同一台机器上，不知道其中哪个环节出了问题。
