### ISSUE TITLE
关于模型映射关系的bug

### ISSUE THREAD

**Issue by cgf120** [songquanpeng/one-api#1342]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ✅] 我已确认目前没有类似 issue
+ [ ✅] 我已确认我已升级到最新版本
+ [ ✅] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ✅] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ✅] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我的实际模型api返回的models信息 {"object":"list","data":[{"id":"/CohereForAI/c4ai-command-r-plus","object":"model","created":1713621874,"owned_by":"vllm","root":"/CohereForAI/c4ai-command-r-plus","parent":null,"permission":[{"id":"modelperm-c73fbc9b989d4f28a908f707dd92481f","object":"model_permission","created":1713621874,"allow_create_engine":false,"allow_sampling":true,"allow_logprobs":true,"allow_search_indices":false,"allow_view":true,"allow_fine_tuning":false,"organization":"*","group":null,"is_blocking":false}]}]}

我想要显示model用c4ai-command-r-plus 然后做映射如下 

<img width="1188" alt="image" src="https://github.com/songquanpeng/one-api/assets/20335370/c55e563c-d2b9-4619-b9ae-d64c9cfed83b">

测试渠道提示404 

而这样设置就可以正常

<img width="1071" alt="image" src="https://github.com/songquanpeng/one-api/assets/20335370/7a0e4ac5-3305-41d1-88a2-636c260a0ad6">

**Comment by cgf120** [comment]
我看源码里面并没有对这块的处理，我不太懂go语言，但是简单搜索了下
<img width="1001" alt="image" src="https://github.com/songquanpeng/one-api/assets/20335370/b10f53fe-da4c-43e3-af1d-18f56cf53ca5">
这个处理好像并不太对

**Comment by QAbot-zh** [comment]
模型映射前后的模型名称都要填到模型框里才行

**Comment by songquanpeng** [comment]
> 模型映射前后的模型名称都要填到模型框里才行

只有前面的需要哈

**Comment by songquanpeng** [comment]
看起来像是你自己重定向填反了，前面的 key 是用户请求里的模型，后面的是要映射成的值

**Comment by songquanpeng** [comment]
有问题，重开 issue，先关了
