### ISSUE TITLE
v0.6.6-alpha版本中，无法添加AWS Bedrock渠道

### ISSUE THREAD

**Issue by Towski0804** [songquanpeng/one-api#1343]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
添加AWS Bedrock渠道时，已填写全部信息并提交时，得到提示：请填写渠道名称和渠道密钥！
可能是在该渠道下，在表单提交时没有name为key的input。

**复现步骤**
更新到v0.6.6-alpha版本，并添加AWS Bedrock渠道

**预期结果**
成功添加该渠道

**相关截图**
![bedrock](https://github.com/songquanpeng/one-api/assets/49519644/2f34aa43-ccf6-4fea-8c96-c29acfe6e72f)

**Comment by Towski0804** [comment]
<img width="909" alt="image" src="https://github.com/songquanpeng/one-api/assets/49519644/45b81c6b-6a6b-4607-8563-7233a1eac9d5">
看到这里有合并AK SK创建新key，但不知咋无法创建

**Comment by vance19van** [comment]
什么时候可以修复呀

**Comment by songquanpeng** [comment]
今天修复，我测试的时候因为之前是写到key里，所以没测试到这种case

**Comment by songquanpeng** [comment]
v0.6.6-alpha.1 已经修复

**Comment by vance19van** [comment]
还没上传docker嘛

**Comment by vance19van** [comment]
我看到了

justsong/one-api:v0.6.6-alpha.1

**Comment by vance19van** [comment]
感谢大佬

**Comment by zion-c** [comment]
大佬， pro 版的 docker 还没有嘛？
