### ISSUE TITLE
Gemini返回relay error中继错误

### ISSUE THREAD

**Issue by utopeadia** [songquanpeng/one-api#1345]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用v1beta接口接入gemini，最新版本返回relay error，经过日志查询，发现上游gemini正常返回结果，但是one-api没有将中继结果下发，而是提示中继错误。更换new-api等fork项目后发现可以正常使用，且该问题出现在更新latest docker镜像后.
**相关截图**
![da9e97e4d50fa4e8ea28733bcbdb2088](https://github.com/songquanpeng/one-api/assets/98788152/9aa958c5-e156-4019-81c5-46c11b77f856)
![3b8db3a30bc42ef32f8a9bb433fa05f9](https://github.com/songquanpeng/one-api/assets/98788152/41389769-3606-4b4e-b80b-4b7d567b4c0a)

**Comment by manjieqi** [comment]
同样，v1beta是手动数据库加的

**Comment by surfwave** [comment]
same problem

**Comment by Anyfc** [comment]
同样的问题，直连Gemini没有问题，套上oneapi后出现：
```
[ERR] 2024/04/22 - 06:15:16 | 2024042206151621434039839743267 | relay error (channel #6):   
```

**Comment by hpkaiq** [comment]
同样的问题，而且不能回退版本了，数据库会报错。

**Comment by manjieqi** [comment]
> 同样的问题，而且不能回退版本了，数据库会报错。

v0.6.6-alpha

**Comment by hpkaiq** [comment]
> > 同样的问题，而且不能回退版本了，数据库会报错。
> 
> v0.6.6-alpha

感谢，测试可以。

**Comment by chenwynn** [comment]
> > > 同样的问题，而且不能回退版本了，数据库会报错。
> > 
> > 
> > v0.6.6-alpha
> 
> 感谢，测试可以。

请问docker如何安装 v0.6.6-alpha 这个版本？

**Comment by QAbot-zh** [comment]
+1，测试可以，但是请求报reley error
![image](https://github.com/songquanpeng/one-api/assets/40236765/e0a88be4-fd15-4c63-8dab-5b68bb3d3c6a)

**Comment by chenwynn** [comment]
> v0.6.6-alpha

v0.6.6-alpha 貌似确实不报错了

**Comment by SteamFinder** [comment]
> > 同样的问题，而且不能回退版本了，数据库会报错。
> 
> v0.6.6-alpha

0.6.6完美解决

**Comment by iccyuan** [comment]
使用最新的代码还是有问题，"stream":false 是正常的,"stream":true 时会出现
[ERR] 2024/04/25 - 00:45:20 | 2024042500450317166176469786939 | relay error happen, status code is 200, won't retry in this case

**Comment by dirname** [comment]
This issue was introduced by https://github.com/songquanpeng/one-api/pull/1328#discussion_r1573632494, a temporary workaround would be to modify it to

```go
errorHappened := (resp.StatusCode != http.StatusOK) || (meta.IsStream && meta.ChannelType != channeltype.Gemini && strings.HasPrefix(resp.Header.Get("Content-Type"), "application/json"))
```

**Comment by songquanpeng** [comment]
已经修复
