### ISSUE TITLE
尝试接入nvdia中发现报404的问题

### ISSUE THREAD

**Issue by wordkathychen** [songquanpeng/one-api#1346]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在尝试使用英伟达（nvidia）发布的几个大模型的实用过程中发现报404（status code 404）主要模型有：llama3-70b，llama3-8b,mixtral-8x22b-instruct-v01，goole的recurrentgemma等
**复现步骤**
在参考官方示例后分别在自定义、openai、还有ollama的三个渠道进行试验，发现均报404，无法解决
**预期结果**
希望可以有相关大佬或者作者本人进行解答

**Comment by songquanpeng** [comment]
所以你用的是什么 API 提供方呢？麻烦提供一下链接

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/9331a314-78a8-4553-a970-665d0e57d3e2)
![image](https://github.com/songquanpeng/one-api/assets/39998050/25911f9f-d024-4b0f-a97a-1ddd8d36486c)
没有问题哦

**Comment by songquanpeng** [comment]
issue 先关了，有问题请重开 issue

**Comment by liuzj288** [comment]
> ![image](https://private-user-images.githubusercontent.com/39998050/324241524-9331a314-78a8-4553-a970-665d0e57d3e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzUzMjIsIm5iZiI6MTcyMDM3NTAyMiwicGF0aCI6Ii8zOTk5ODA1MC8zMjQyNDE1MjQtOTMzMWEzMTQtNzhhOC00NTUzLWE5NzAtNjY1ZDBlNTdkM2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3NTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OWQ5NGQ0OGNhNTEzMGQ3ZTNiMGIzODU3YmVmM2ZiZTg4MjgzZTI3Y2ViMWI0YTVkZmY5ZTU4YWJmNTBjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-p6TrNvkFUpNw_Am4a4v_l1Hlz-20EGV4Fuq5yGCNo) ![image](https://private-user-images.githubusercontent.com/39998050/324241539-25911f9f-d024-4b0f-a97a-1ddd8d36486c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzUzMjIsIm5iZiI6MTcyMDM3NTAyMiwicGF0aCI6Ii8zOTk5ODA1MC8zMjQyNDE1MzktMjU5MTFmOWYtZDAyNC00YjBmLWE5N2EtMWRkZDhkMzY0ODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3NTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMWRkNmE4MmIyMDA1M2VjZDc5MTBjMDZjODAxNTM0N2I3ODY1ZjE0ZmNmYmM3ZWEzNjgzM2M1MGRlNWQ5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6NJlf210yt3EuDgwDFBxWUADQ7kg8MLwgqihHylnM90) 没有问题哦

确实不能加/v1，加了就报错
![image](https://github.com/songquanpeng/one-api/assets/13833404/09f86e77-5b48-444f-a7c6-d46fc470aeef)
