### ISSUE TITLE
Post "http:127.0.0.1:8000/v1/chat/completions": http: no Host in request URL，，最近使用docker部署的one-api出现这个问题

### ISSUE THREAD

**Issue by YFC0254** [songquanpeng/one-api#1350]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by ye4293** [comment]
你这个url “http:127.0.0.1:8000” 是不是错了。应该是“http://127.0.0.1:8000”

**Comment by songquanpeng** [comment]
issue 先关了，有问题请重开 issue
