### ISSUE TITLE
llama3 返回的响应体中缺少model字段

### ISSUE THREAD

**Issue by AtlasCodeHub** [songquanpeng/one-api#1362]
![image](https://github.com/songquanpeng/one-api/assets/165111395/2d0c15c0-2695-4e0e-8fe7-0bb2df9673ac)

和GPT返回的响应字段不一样
![image](https://github.com/songquanpeng/one-api/assets/165111395/35b8b8e7-ba9d-4825-9245-8565740f66c4)

**Comment by RexWzh** [comment]
你用什么渠道导入的？ vllm 还是 ollama?

**Comment by songquanpeng** [comment]
修复了
