### ISSUE TITLE
claude-3-haiku消息兼容问题

### ISSUE THREAD

**Issue by huxinggg** [songquanpeng/one-api#1374]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
claude-3-haiku的system是单独的，并不在消息列表，并且我以openAI的方式传递messages是报错的，是没有兼容吗？ 那我怎么传claude-3-haiku的system模板
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by QAbot-zh** [comment]
system 单独的？我用OpenAI方式请求claude3都没报错呀，贴下你的请求和报错吧
