### ISSUE TITLE
方便的方式去添加本地embedding

### ISSUE THREAD

**Issue by chuanyue98** [songquanpeng/one-api#1383]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
能够提供一种方法来添加本地的embedding
**应用场景**
例如支持HuggingFace上的开源模型

**Comment by songquanpeng** [comment]
通过ollma不可以吗

**Comment by nongmo677** [comment]
一般的仿openai接口的开源项目都包含embedding内容吧，直接接oneapi的openai渠道类型就好了

**Comment by chuanyue98** [comment]
好的，了解了谢谢

**Comment by SuMiaoALi** [comment]
> 一般的仿openai接口的开源项目都包含embedding内容吧，直接接oneapi的openai渠道类型就好了

亲测过，可以直接通过oneapi调用OpenAI的embedding没错，但是有本地embedding模型需求的话这就行不通拉

**Comment by SuMiaoALi** [comment]
> 好的，了解了谢谢

所以oneapi现在可以支持本地embedding了吗老哥
