### ISSUE TITLE
计费不上，实际有输入输出，但是后台计费输入输出都是0

### ISSUE THREAD

**Issue by akakenle** [songquanpeng/one-api#1391]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x]  我已确认我已升级到最新版本
+ [x]  我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我用litellm的项目聚合了其他模型，litellm输出的接口标准是openai，然后我用oneapi中转，老版本没问题，新版本，出现一些模型计费不到；
老版本具体哪个版本忘了，反正是没有仪表盘功能之前的版本。

**复现步骤**

**预期结果**
计费成功

**相关截图**
![70d87cc6616aa78e694728052e7c6639](https://github.com/songquanpeng/one-api/assets/12624481/3e6db0d7-0a30-4bf3-bd7d-f669811a3950)

![4dab8cb5d3107c9afcf761d455dc6dc6](https://github.com/songquanpeng/one-api/assets/12624481/1896adf6-8010-4446-af2f-a8cfae3ac94b)
![736494c5859d43eb3552b3e99341c
![e7058882b7e4621a864338444fa6d5d6](https://github.com/songquanpeng/one-api/assets/12624481/ccaa9308-4766-402e-a59a-2e574b029176)
1df](https://github.com/songquanpeng/one-api/assets/12624481/a3af3eba-85aa-4c3d-a5c6-0bdc2767ea7f)

**Comment by QAbot-zh** [comment]
你看下你接口返回数据中的prompt_token和completion_token是不是0，非流调用好像直接使用响应中的数据的

**Comment by akakenle** [comment]
> 你看下你接口返回数据中的prompt_token和completion_token是不是0，非流调用好像直接使用响应中的数据的

所以是one API在某个版本中把非流失的token计算去掉了吗？因为我们什么都没动，就是更新版本后就一下模型计费不到了

**Comment by songquanpeng** [comment]
> > 你看下你接口返回数据中的prompt_token和completion_token是不是0，非流调用好像直接使用响应中的数据的
> 
> 所以是one API在某个版本中把非流失的token计算去掉了吗？因为我们什么都没动，就是更新版本后就一下模型计费不到了

不是，是因为上游返回了 usage，但是里面值却是空的

**Comment by songquanpeng** [comment]
我处理一下这个问题

**Comment by songquanpeng** [comment]
已处理，请更新试一下
