### ISSUE TITLE
请求报错：unexpected end of JSON input

### ISSUE THREAD

**Issue by cbangchen** [songquanpeng/one-api#140]
![image](https://github.com/songquanpeng/one-api/assets/11977680/fc2f4568-606a-4270-9f08-072eb5cf7aca)

**Comment by songquanpeng** [comment]
你能直接把请求体贴出来么。

**Comment by cbangchen** [comment]
curl --location 'http://117.50.177.86:3000/v1/chat/completions' \
--header 'Authorization: Bearer sk-kQvcEa4mM2RKlamBCd14E31b771d45Ec9e71BeA828026f03' \
--data '{
    "model": "gpt-3.5-turbo",
    "stream": true,
    "messages": [
        {
            "role": "user",
            "content": "Hello!"
        }
    ]
}'

**Comment by songquanpeng** [comment]
复现不了，我这里正常。用通道测试功能检查一下通道是否 Okay。

![image](https://github.com/songquanpeng/one-api/assets/39998050/dac4ff65-b68c-4c23-8011-325950cb9dc7)

**Comment by cbangchen** [comment]
![image](https://github.com/songquanpeng/one-api/assets/11977680/8c3bf720-5f19-45a5-ade0-e0e6fa416ade)

**Comment by cbangchen** [comment]
有其他影响因素吗，会不会是因为没有配置什么参数

**Comment by songquanpeng** [comment]
不应该哈，使用其他通道试一下如果有的话。

**Comment by cbangchen** [comment]
稍等我试试

**Comment by cbangchen** [comment]
<img width="1271" alt="截屏2023-06-05 16 31 09" src="https://github.com/songquanpeng/one-api/assets/11977680/4bbbf3b4-3aab-4425-8211-4d11d92b6f0a">


<img width="1152" alt="截屏2023-06-05 16 31 21" src="https://github.com/songquanpeng/one-api/assets/11977680/32b79cb7-9fbd-41d4-a0f0-4e3079dd7026">


相同的结果，那么有可能是从oneapi这一层就吐出结果了

**Comment by cbangchen** [comment]
我是使用docker部署的，是不是我需要更新到一个更新的版本

**Comment by songquanpeng** [comment]
更新版本试一下。看报错实际上是在说请求体不是合法的 JSON。

**Comment by cbangchen** [comment]
已经是最新的版本，退回到0.3.2版本问题依然存在。

**Comment by songquanpeng** [comment]
解决了么？



---Original---
From: ***@***.***&gt;
Sent at: 2023年6月5日(Mon) Evening6:44
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 请求报错：unexpected end of JSON input (Issue #140)




 
Closed #140 as completed.

**Comment by cbangchen** [comment]
用postman依然不行，不过用curl又突然可以。不是很明白为什么。不过看起来可以工作。

**Comment by songquanpeng** [comment]
可以看一下 Postman 的 raw request body 吗？

**Comment by RexWzh** [comment]
docker 更新到新版以及 `v0.6.5-alpha.3` 版会提示这个错误：

```bash
curl --location --request GET 'https://.../v1/models' \
--header 'Authorization: Bearer sk-...' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: ... \
--header 'Connection: keep-alive' \
--data-raw ''
{"error":{"message":"common.UnmarshalBodyReusable failed: unexpected end of JSON input (request id: 2024040414255184119782326932492)","type":"one_api_error"}}
```

docker 日志：
```bash
one-api  | [ERR] 2024/04/04 - 14:27:51 | 2024040414275110400662582560516 | common.UnmarshalBodyReusable failed: unexpected end of JSON input 
one-api  | [GIN] 2024/04/04 - 14:27:51 | 2024040414275110400662582560516 | 400 |    1.117364ms |    209.141.57.3 |     GET /v1/models
```
