### ISSUE TITLE
Gemini的流式返回存在问题

### ISSUE THREAD

**Issue by manjieqi** [songquanpeng/one-api#1408]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Gemini仅返回几个字，因为它们把"finish_reason":"stop"作为回答停止的信号
如果openai的返回格式是标准的，那Gemini的流式还需要改一下

**Gemini的回答，可以看见每一个部分都有stop**
<img width="523" alt="Snipaste_2024-05-04_13-13-19" src="https://github.com/songquanpeng/one-api/assets/40858189/603a5b7f-db8f-4da3-bc6a-2aac0bccc7db">

**GPT的回答，仅最后的一个部分有stop**
<img width="494" alt="Snipaste_2024-05-04_13-14-14" src="https://github.com/songquanpeng/one-api/assets/40858189/749c1523-dbc4-462b-8bd8-fa6271151b4a">

**Comment by SLF-Heisenberg** [comment]
我也遇到了 同样的问题 每一次的 调用结果 都是  "finish_reason": "stop" 但是 只有 最后一个包分发完毕的 才是 "stop"
![image](https://github.com/songquanpeng/one-api/assets/52819425/5590b42e-e49f-4836-bf08-d3df22ce9d15)

**Comment by youjin-git** [comment]
这个bug还没修复吗？

**Comment by SLF-Heisenberg** [comment]
看样子还没有解决，bug状态是open

**Comment by RexWzh** [comment]
> 看样子还没有解决，bug状态是open

回退到 v0.6.6-alpha 可以，但会少一些近期更新的东西。项目维护的人好像很少，更新功能的同时，可能会引入一些 bug。

要么另外开个稳定的 one-api 来过渡，或者接入 [litellm](https://github.com/BerriAI/litellm)、[AI-Gateway](https://github.com/Portkey-AI/gateway)

**Comment by SLF-Heisenberg** [comment]
ok 非常感谢~

**Comment by mxdlzg** [comment]
早期的版本应该没有返回FinishReason？所以流不会被截断。
但是在v0.6.7左右的版本修复stream流问题时这部分被修正了https://github.com/songquanpeng/one-api/pull/1382，引入了FinishReason字段。涉及问题https://github.com/songquanpeng/one-api/issues/1345、
https://github.com/songquanpeng/one-api/pull/1328。
但是有个比较尴尬的地方在于，实际上Gemini的API本身就在每个流message中返回STOP（看起来跟早期的Gemini的表现不太一致，不知道为什么会出现这个问题）。

**因为是流式返回，没法准确预知哪个是最后一条message，只能暂时去掉FinishReason字段了。**#1477

**Comment by SLF-Heisenberg** [comment]
> 早期的版本应该没有返回FinishReason？所以流不会被截断。 但是在v0.6.7左右的版本修复stream流问题时这部分被修正了[https://github.com/songquanpeng/one-api/pull/1382，引入了FinishReason字段。涉及问题https://github.com/songquanpeng/one-api/issues/1345、](https://github.com/songquanpeng/one-api/pull/1382%EF%BC%8C%E5%BC%95%E5%85%A5%E4%BA%86FinishReason%E5%AD%97%E6%AE%B5%E3%80%82%E6%B6%89%E5%8F%8A%E9%97%AE%E9%A2%98https://github.com/songquanpeng/one-api/issues/1345%E3%80%81) [https://github.com/songquanpeng/one-api/pull/1328。](https://github.com/songquanpeng/one-api/pull/1328%E3%80%82) 但是有个比较尴尬的地方在于，实际上Gemini的API本身就在每个流message中返回STOP（看起来跟早期的Gemini的表现不太一致，不知道为什么会出现这个问题）。
> 
> **因为是流式返回，没法准确预知哪个是最后一条message，只能暂时去掉FinishReason字段了。**#1477

**您的描述 很有意义，我在尝试把这个 问题 返回给谷歌 ~ 希望会有所答复~**

**Comment by manjieqi** [comment]
ChatGPT NextWeb的请求是这样的：
POST /v1beta/models/gemini-1.5-pro:streamGenerateContent?key=xxxxxxxx
OneAPI的请求是这样的：
POST /v1beta/models/gemini-1.5-pro:streamGenerateContent?alt=sse

怎么拉取请求还没有合并啊
