### ISSUE TITLE
MySQL 连接支持 SSL

### ISSUE THREAD

**Issue by zengboin** [songquanpeng/one-api#141]
有些 MySQL 服务需要用 SSL 链接，现在的好像不支持，希望能加上

**Comment by songquanpeng** [comment]
Okay，之后看一下。

**Comment by songquanpeng** [comment]
我看了下如果要支持的话，貌似修改的代码有点多。

考虑到大部分用户都是使用内网里的数据库，因此目前暂时不打算实现，你可以考虑通过 `?tls=skip-verify` 来取消 SSL 的校验。
