### ISSUE TITLE
支持直接选择分组

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#142]
已更新最新分组
1：在新增用户的时候无法进行选择分组
2：目前分组只能手动进行输入，可以弄一个管理，后台进行新增，然后进行下拉选择，比较方便
3：手动输入也可以，但是在用户管理选择分组的时候，应该是下拉的形式而不是手动输入
![image](https://github.com/songquanpeng/one-api/assets/52068443/e92ba46b-8183-40a6-9ac4-0c42fc9e550b)
4：还有就是新增这个渠道，选择模型的时候，可以让其自动选择更新，而不是进行手动输入
自动填入我的思路提供下：
可以调用 v1/models 这个接口，返回的是这个账号支持的全部model，然后进行自动填充。

**Comment by songquanpeng** [comment]
1. 稍后处理。
2. 这个打算直接前端预定义几个常用分组名。
3. 同上。
4. 什么是自动选择更新？现在可以通过点击快捷按钮进行填充。

**Comment by lmuiotctf** [comment]
这个接口支持查询全部支持的模型，可以在填写key的时候调用下这个口，然后将其补充在支持的模型下
![image](https://github.com/songquanpeng/one-api/assets/52068443/bdf79cb2-d3f0-4458-9722-5209d9f430e5)
