### ISSUE TITLE
exec /one-api: exec format error

### ISSUE THREAD

**Issue by 1152588263** [songquanpeng/one-api#1425]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在甲骨文免费arm架构服务器上部署后日志出现exec /one-api: exec format error
**复现步骤**

**预期结果**

**Comment by portwatcher** [comment]
Why did you mark this as completed? Does one-api support multi-architecture builds now? I still encouter this problem

**Comment by xingpingcn** [comment]
是不是之后的版本都不支持arm了

**Comment by xingpingcn** [comment]
最新版在甲骨文的arm机器上同样报错
