### ISSUE TITLE
undefined Panic detected, error: runtime error: invalid memory addressor nil pointer dereference 不知名原因，偶尔会报错，没排查出来。

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#1428]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
星火和千问遇到，其他暂时没遇到

**复现步骤**

**预期结果**

**相关截图**
<img width="443" alt="a67737060e038e8cf9442947b14fc41" src="https://github.com/songquanpeng/one-api/assets/50446880/45219fe9-d6d7-401e-b224-81d11865df4e">

**Comment by SHMILYWord** [comment]
你引用知识库了吗？不加知识库没有问题，加上知识库检索就会报错。

**Comment by songquanpeng** [comment]
有 id 和相关日志吗？
