### ISSUE TITLE
使用 default 作为分组名时无法限制渠道可用的模型

### ISSUE THREAD

**Issue by songquanpeng** [songquanpeng/one-api#143]
当初实现的时候考虑到从旧版本升级的用户的可用性，使用 default 作为分组名称会导致使用原本的渠道分配策略。

![ATDM`110}N9UL(G%J4D@2(0](https://github.com/songquanpeng/one-api/assets/39998050/b2851ecf-fa49-4e6f-8c68-2aa1afb8daad)

但是这可能会对用户造成困扰，因此有必要提示用户，或者使用其他解决方案。

**Comment by leeileduo** [comment]
https://github.com/labring/FastGPT/issues/2105
