### ISSUE TITLE
为OpenAI 最新的GPT-4o模型提供支持

### ISSUE THREAD

**Issue by HChaZZY** [songquanpeng/one-api#1430]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
OpenAI 于近期更新了[GPT-4o](https://openai.com/index/hello-gpt-4o/)模型，并向所有付费开发者开放其API。
相比于GPT-4 Turbo, GPT-4o能使用更少的Token，便宜50%，速度更快。同时支持语音、图像和文本的同时输入和输出。
希望one-api予以适配。

**应用场景**
在模型选择，能力列表以及API转接中加入对GPT-4o的支持

**Comment by mwnu** [comment]
可以用自定义模型的方式添加，但不知道能不能语音输入和图片、语音输出，没测试成功。

**Comment by RexWzh** [comment]
> 可以用自定义模型的方式添加，但不知道能不能语音输入和图片、语音输出，没测试成功。

没测试成功指的是？

这个项目对 API 支持能力很灵活，我这里测的图文对话是正常的。。。

<img width="483" alt="image" src="https://github.com/songquanpeng/one-api/assets/62223937/893098df-e4ec-478d-b7f3-31551baf34bd">

**Comment by RexWzh** [comment]
不过 gpt-4o 是真的快到飞起。。。。网页端也是肉眼可见的快，像复制粘贴

![essay](https://github.com/songquanpeng/one-api/assets/62223937/e7752150-e37f-42bc-9d6d-d01881515d4f)

**Comment by yaoyi098** [comment]
> mwnu

4o api支持文字图片输入，文字输出。

见API文档
![WXWorkLocal_1715657109492](https://github.com/songquanpeng/one-api/assets/5396539/14f9d6a3-b77d-415a-9c75-3ffd1bcbb192)

你看到的发布会中语音的输入输出是基于4o tts stt 等组合起来的桌面应用。

**Comment by RexWzh** [comment]
我看有[帖子](https://community.openai.com/t/gpt-4o-text-to-speech-and-speech-to-text/744455/6)提到了：


> Audio support is coming in the future, but not available today.
> 音频支持将在未来推出，但目前不可用。

应该还没上线，可以持续关注。

**Comment by awwaawwa** [comment]
GPT-4o 换了词表，本项目应该是得更新一下来支持的吧

**Comment by yaoyi098** [comment]
> GPT-4o 换了词表，本项目应该是得更新一下来支持的吧

不太懂，纯调用api的需要做本地分词和序列化吗？不是只有本地推理才用吗。

**Comment by awwaawwa** [comment]
> > GPT-4o 换了词表，本项目应该是得更新一下来支持的吧
> 
> 不太懂，纯调用 api 的需要做本地分词和序列化吗？不是只有本地推理才用吗。

额度 = 分组倍率 * 模型倍率 * （提示 token 数 + 补全 token 数 * 补全倍率）

不更新词表，token 数就是错的（一般来说是偏高）

**Comment by RexWzh** [comment]
这个号商用的，计费功能，自用影响不大。

https://platform.openai.com/tokenizer

**Comment by yaoyi098** [comment]
> > > GPT-4o 换了词表，本项目应该是得更新一下来支持的吧
> > 
> > 
> > 不太懂，纯调用 api 的需要做本地分词和序列化吗？不是只有本地推理才用吗。
> 
> 额度 = 分组倍率 * 模型倍率 * （提示 token 数 + 补全 token 数 * 补全倍率）
> 
> 不更新词表，token 数就是错的（一般来说是偏高）

哦懂了  计费这块可能回有偏差。

**Comment by ylck** [comment]
> Issue 列表有类似的，你翻一下，你在渠道那手动添加即可。
> 
>     * [强烈希望增加实用功能，谢谢 #1347](https://github.com/songquanpeng/one-api/issues/1347)
> 
> 
> 实测调用方式一样，只是加个模型名称而已
> 
> ![validmodels](https://private-user-images.githubusercontent.com/62223937/330281735-e95d53b0-9c5d-4c29-9c0e-6b8c38f621d1.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzM0NDUsIm5iZiI6MTcxNTY3MzE0NSwicGF0aCI6Ii82MjIyMzkzNy8zMzAyODE3MzUtZTk1ZDUzYjAtOWM1ZC00YzI5LTljMGUtNmI4YzM4ZjYyMWQxLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3NTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDdmODE2ZDNmMTBmYjRhNTBjNGI1MDAyMDZiY2Q0ZjM1YWE3NjNkMzI3NTNjM2UyMWI4MDA3Nzg3MTIyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZTmD_Qr1fGmLDFvsdUHeMynOWhgjTZc9tddc7jrXIYw)

图片里是什么cli?

**Comment by HChaZZY** [comment]
如果需要在one-api中添加对gpt-4o的支持，只需要在模型列表中添加即可。主流OpenAI API 的前端页面已经支持gpt-4o的图形输入。
请注意gpt-4o以及gpt-4o-2024-05-13的补全倍率应设置为3。

**Comment by haso2007** [comment]
怎样设置 补全倍率应设置为3，当然我自用的无什么实际作用。
