### ISSUE TITLE
help！无法调用one-api渠道

### ISSUE THREAD

**Issue by 13829386012** [songquanpeng/one-api#1432]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
用one api连接本地ollama部署好的Qwen4b模型，在one-api渠道测试中是成功的，但是在fastgpt中填入配置地址后，无法调用oneapi,在one-api控制台log中没有fastgpt的请求信息，我不知道哪里设置的有问题，请求协助~
**复现步骤**
如图配置
**预期结果**
Unhandled Runtime Error
AxiosError: timeout of 60000ms exceeded
&
http://localhost:3001/api/proApi/support/user/inform/getSystemMsgModal 500 (Internal Server Error)
**相关截图**
![渠道测试结果](https://github.com/songquanpeng/one-api/assets/40138671/ef403443-3d3b-46c6-8dfa-bf8b7f101db8)
![postman调用也正常](https://github.com/songquanpeng/one-api/assets/40138671/0ee4f980-6d7b-4c3a-97cb-5ada3377b041)
![连接超时报错](https://github.com/songquanpeng/one-api/assets/40138671/84d43cd7-d392-43c4-9a9f-41efb4ba680e)
![envlocal配置](https://github.com/songquanpeng/one-api/assets/40138671/e85b409a-1e73-42c6-9d5f-8fa6b3051796)
![model配置](https://github.com/songquanpeng/one-api/assets/40138671/e5ae95ff-d94a-43f9-9adb-228d58beeec1)

如果没有的话，请删除此节。

**Comment by mxdlzg** [comment]
你pg链接字符串都没改啊
# PG数据库连接参数
PG URL=postgresql:/ /username: password@host : port/ postgres
#商业版地止
