### ISSUE TITLE
浏览器弹出翻译窗口

### ISSUE THREAD

**Issue by by123456by** [songquanpeng/one-api#1433]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
打开oneapi网页会提示翻译
**复现步骤**
打开oneapi网页
**预期结果**
在简体中文环境下不弹窗
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/15666692/bffe8d20-db86-4e9a-bc75-1b48624ecf85)

**修复建议**
将`<html lang="en">`修改为`<html lang="zh-CN">`

**Comment by songquanpeng** [comment]
Thx~
