### ISSUE TITLE
[Feature]   kimi 支持 

### ISSUE THREAD

**Issue by 0x5c0f** [songquanpeng/one-api#1434]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
请求支持`kimi`接入 ，不知道这个算是什么，他好像并没有提供`api`接口，但确实又是一个`ai`,像`bing` 又不太像。 我是在[`openai-translator`](https://github.com/openai-translator/openai-translator)项目看到的相关支持，想着是否能接入到`one-api` 统一管理。 

**应用场景**
毕竟免费，测试也发现他的能力也还是挺不错的。

**参考连接**
> https://github.com/openai-translator/openai-translator/blob/main/docs/kimi-cn.md

**Comment by QAbot-zh** [comment]
有官方 api 的，对应 moonshot 渠道类型
