### ISSUE TITLE
适配 gemini-1.5-flash

### ISSUE THREAD

**Issue by IAn2018cs** [songquanpeng/one-api#1435]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

Gemini 新出的模型，不过这个模型请求路径中没有 `models/ `
<img width="850" alt="image" src="https://github.com/songquanpeng/one-api/assets/18318073/f44d17ff-fb3f-4a89-8d2c-e3cdde1aa221">

**Comment by QAbot-zh** [comment]
补充，v1beta 路径可以直接调用 gemini-1.5-flash-latest，适配的时候可以注意一下差别

**Comment by temberature** [comment]
![image](https://github.com/songquanpeng/one-api/assets/3735863/813fd943-1ee9-4297-bea7-ab3333a6dac8)

**Comment by tisfeng** [comment]
好像不能直接映射模型，gemini-1.5-flash-latest 这种目前只能用于 v1beta，目前 one-api 默认使用的是 v1 版本，如果要用，需要将环境变量 GEMINI_VERSION 改为 v1beta。

**Comment by mxdlzg** [comment]
> 好像不能直接映射模型，gemini-1.5-flash-latest 这种目前只能用于 v1beta，目前 one-api 默认使用的是 v1 版本，如果要用，需要将环境变量 GEMINI_VERSION 改为 v1beta。

berry主题可以设置渠道版本

**Comment by tisfeng** [comment]
这个不错，感觉可以将一些可能需要修改的环境变量拿出来，允许通过 UI 的方式动态修改。
