### ISSUE TITLE
支持豆包系列大模型API

### ISSUE THREAD

**Issue by klb3713** [songquanpeng/one-api#1436]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
申请支持豆包系列大模型API
**应用场景**

**Comment by RexWzh** [comment]
功能请求：**增加一个允许用户提供完整链接的渠道**，版本号用户自定义。

智谱，DeepSeek，豆包等渠道的默认代理地址不以 `v1` 结尾。

严格来说，[OpenAI 风格](https://platform.openai.com/docs/api-reference) 的 API 地址是 https://api.openai.com/v1 ，带上尾巴的版本号。官方 SDK 也是读取环境变量 `OPENAI_API_BESE` ，然后拼接 URI 时不需要带 `v1` 。

**Comment by zsinba** [comment]
+1

**Comment by webtechnic** [comment]
+1

**Comment by shengjidaguai** [comment]
+1

**Comment by TangSY** [comment]
+1

**Comment by fishfree** [comment]
+1

**Comment by lifei1102** [comment]
+1，豆包降价后性价比超高，pro-32k 100万token 才8毛钱

**Comment by RexWzh** [comment]
话说，有用过这个 API 的可以介绍下吗？

看了文档，创建 [API key](https://www.volcengine.com/docs/82379/1263279) 的第三步需要企业认证：

> 1. API key 有效时长由duration_seconds定义，单位为秒；
> 2. AK/SK 可通过[API访问密钥](https://console.volcengine.com/iam/keymanage/) 页面获取；
> 3. Endpoint ID 可通过火山方舟 - [模型推理](https://console.volcengine.com/ark/region:ark+cn-beijing/endpoint?current=1&pageSize=10)获取，格式为ep-xxxxxx；
> 4. resource_ids 支持输入多个 Endpoint ID。

只有个人实名访问不了这里：

<img width="434" alt="image" src="https://github.com/songquanpeng/one-api/assets/62223937/8bdf1956-bb67-47dd-a78a-d96272584cf5">

**Comment by guobaozu** [comment]
那在代码之前，豆包的这样的API调用如何才能使用？
curl https://ark.cn-beijing.volces.com/api/v3/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9" \
  -d '{
    "model": "ep-2024051092-q5c",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "stream": true
  }'

**Comment by RexWzh** [comment]
> 那在代码之前，豆包的这样的API调用如何才能使用？ curl https://ark.cn-beijing.volces.com/api/v3/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9" -d '{ "model": "ep-2024051092-q5c", "messages": [ { "role": "system", "content": "You are a helpful assistant." }, { "role": "user", "content": "Hello!" } ], "stream": true }'


这个和智谱类似，需要 API 鉴权。后缀的话可以直接配个 Nginx 转发。

```conf
server{
    listen 80;
    server_name xxx;
    location /v1 {
        proxy_pass  https://ark.cn-beijing.volces.com/api/v3;
        proxy_ssl_server_name on;
        proxy_set_header Host ark.cn-beijing.volces.com;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

---

官方文档看着有点头大 :roll_eyes: ，又是 AK 又是 SK，身份认证后还要企业认证，有没弄过的可以简单介绍下（

![image](https://github.com/songquanpeng/one-api/assets/62223937/c438dfde-2b33-458f-83e5-95a0d68243ad)

**Comment by guobaozu** [comment]
> > 那在代码之前，豆包的这样的API调用如何才能使用？ curl https://ark.cn-beijing.volces.com/api/v3/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9" -d '{ "model": "ep-2024051092-q5c", "messages": [ { "role": "system", "content": "You are a helpful assistant." }, { "role": "user", "content": "Hello!" } ], "stream": true }'
> 
> 这个和智谱类似，需要 API 鉴权。后缀的话可以直接配个 Nginx 转发。
> 
> ```
> server{
>     listen 80;
>     server_name xxx;
>     location /v1 {
>         proxy_pass  https://ark.cn-beijing.volces.com/api/v3;
>         proxy_ssl_server_name on;
>         proxy_set_header Host ark.cn-beijing.volces.com;
>         proxy_set_header Connection '';
>         proxy_http_version 1.1;
>         chunked_transfer_encoding off;
>         proxy_buffering off;
>         proxy_cache off;
>         proxy_set_header X-Forwarded-For $remote_addr;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
> }
> ```
> 
> 官方文档看着有点头大 🙄 ，又是 AK 又是 SK，身份认证后还要企业认证，有没弄过的可以简单介绍下（
> 
> ![image](https://private-user-images.githubusercontent.com/62223937/331791675-c438dfde-2b33-458f-83e5-95a0d68243ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDg5MDUsIm5iZiI6MTcxNjEwODYwNSwicGF0aCI6Ii82MjIyMzkzNy8zMzE3OTE2NzUtYzQzOGRmZGUtMmIzMy00NThmLTgzZTUtOTVhMGQ2ODI0M2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA4NTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNzc1NDI2YTM3MDkwMTFiZjY5ODE0NzEwOTk0NDFlNDViY2E4Y2M1NjRlMjRmODVmMWJjZTY4MWU1OTVhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6FZG1hVEsY_cZhjOCVxAriYwp5Q87a3CXIZ1F2CqEeE)
> 
> 翻了下文档，发现[这里](https://www.volcengine.com/docs/82379/1263279)贴了在代码生产 API key 的方法。
> 
> > HTTP 获取 API key （不推荐）
> > 如果自己实现代码获取API key，需要用 AK/SK 进行旁路鉴权。代码逻辑可参考[火山签名源码示例](https://www.volcengine.com/docs/6369/185600)
> 
> Ref: [Python 代码](https://github.com/volcengine/volc-openapi-demos/blob/34ec78cc09495fc36ea90ca0e68c9a33a67c0636/signature/python/sign.py#L65)

感谢，已经在botgem上跑通。但是我在oneapi里自定义渠道，最后渠道测试也没问题，在使用的时候补全就是返回空。。。不知道为什么？您有在正常使用这个豆包的API吗？

**Comment by zsinba** [comment]
能正常调用 。 
需要 生成 一个 key，key 是最多 30 天有效期的。 
但是合并 的代码跑第一个调用后，第二个就开始 闪退了。
具体的没有跟。

**Comment by dimsky** [comment]
+1

**Comment by songquanpeng** [comment]
这个肯定会支持，我尽量近期抽空处理，希望能理解最近我个人时间不多

**Comment by Lands-1203** [comment]
+1

**Comment by leavegee** [comment]
+1
