### ISSUE TITLE
无法打开渠道如何重置？

### ISSUE THREAD

**Issue by 13829386012** [songquanpeng/one-api#1439]
![无法获取渠道如何重置](https://github.com/songquanpeng/one-api/assets/40138671/aeecb674-669c-405e-becc-b754bdb64461)
**例行检查**
无法打开渠道如何重置？
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
打开渠道时报错，一直转圈，不知道要怎么样重置
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
看上去像是服务端挂了，看一下服务端日志呢？

**Comment by 13829386012** [comment]
> 看上去像是服务端挂了，看一下服务端日志呢？

服务端日志没有异常，可能是网页缓存的有问题，换了个端口就好了
