### ISSUE TITLE
支持日志删除以及查询

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#144]
目前在日志这边建议
1、新增删除日志操作
2、新增查询模型类型使用日志
3、新增按照用户名进行查询使用日志
![image](https://github.com/songquanpeng/one-api/assets/52068443/29025cad-d758-47f4-9b48-bc83bf37e2b0)

**Comment by lmuiotctf** [comment]
还有就是用户这边，建议体现出来 [用户名]，而不是用户的ID

**Comment by songquanpeng** [comment]
用户名这个就需要连表查询了，会影响性能，而且我感觉意义不大，用户管理页面是可以直接搜索 ID 的。

**Comment by lmuiotctf** [comment]
额度明细点击刷新会出现在页面一直新增，同时最上面一个不是最新的
![image](https://github.com/songquanpeng/one-api/assets/52068443/2131a686-d48e-4912-b071-066f5c9f3d2e)

**Comment by miniers** [comment]
另外日志里能否加上令牌名称呢？用来区分不同令牌的消耗

**Comment by songquanpeng** [comment]
> 额度明细点击刷新会出现在页面一直新增，同时最上面一个不是最新的

这个很奇怪哈，还没有复现，我之后检查一下。

> 另外日志里能否加上令牌名称呢？用来区分不同令牌的消耗

好。

**Comment by Aiayw** [comment]
日志可以在后台可以设置定期删除就更好了，虽然也能通过其他方法定时执行，但是能后台设置更方便简单。
例如设置只保留3天的日志或7天的日志（保留天数由管理员根据服务器和数据库情况自定义）。
我估计大部分用户和管理员应该都不会翻很久以前的日志，反而有潜在的可能影响效率和性能。

**Comment by songquanpeng** [comment]
充值日志还是要保留的，消费日志可以这样搞。

**Comment by Aiayw** [comment]
> 充值日志还是要保留的，消费日志可以这样搞。

嗯嗯。以上想法只针对消费日志。
