### ISSUE TITLE
升级 0.66 版本后，berry主题首页控制台报错（图表无法加载）

### ISSUE THREAD

**Issue by forrany** [songquanpeng/one-api#1445]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
<img width="2512" alt="image" src="https://github.com/songquanpeng/one-api/assets/29779326/716e311a-51ed-4441-ab03-499729967886">

**复现步骤**
docker 升级到 0.66，控制台报错，看报错应该是berry主题下，echarts绘图时 hasOwnproperty 报错
**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by dirname** [comment]
使用 `npm install apexcharts@3.35.3` 低版本即可解决

**Comment by songquanpeng** [comment]
感谢提醒
