### ISSUE TITLE
部署新版本后怎样加入原版本的配置？

### ISSUE THREAD

**Issue by haso2007** [songquanpeng/one-api#1448]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**
现在已更新了gpt-4o,gemini-1.5-flash,我是用docker部署的，重新部署又得重新输入一遍渠道等信息。有没有简单的方法来保存原来的设置在更新时再。

**Comment by ByteMelodist** [comment]
You can use an external database to persistently store data.

**Comment by haso2007** [comment]
thanks for the good idea
