### ISSUE TITLE
Zhipu 渠道 glm-4 模型，流式回答被截断

### ISSUE THREAD

**Issue by glinft** [songquanpeng/one-api#1451]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
用最新openai lib调用one-api服务，智谱glm-4模型。
采用流式回答stream=True；
发现只收到部分响应内容，就被截断。
而one-api日志页面可以查看到相应请求的usage数据。
说明zhipu到one-api这段是正常的（否则取不到usage）
猜测：是不是请求方到one-api的streaming连接断开。

**复现步骤**
偶然连续几个请求出现这种情况。
（请求参数一致）

**预期结果**
完整返回stream响应内容。

**Comment by igophper** [comment]
你好，还存在这个问题吗？时间太久如果没反馈就关掉了
