### ISSUE TITLE
腾讯的混元模型 API 接口更新了

### ISSUE THREAD

**Issue by IAn2018cs** [songquanpeng/one-api#1452]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
适配新的接口请求，相关文档：https://cloud.tencent.com/document/api/1729/105701

**Comment by shown1985** [comment]
接口完全变了似乎

**Comment by ethanzhao2001** [comment]
我也发现改了，想白嫖lite模型，希望尽快适配

**Comment by tisfeng** [comment]
有点坑，因为之前腾讯宣布 lite 模型免费了，所以我最近一直在使用 hunyuan-lite 模型。

直到今天看到【腾讯云】的扣费账单才发现，原来目前 one-api 的腾讯混元渠道不支持 hunyuan-lite 模型，导致我自己添加的自定义模型 hunyuan-lite 实际走的还是 hunyuan-pro 😑

没有仔细看代码实现，但我觉得这种设计不太妥，如果渠道不支持 hunyuan-lite 模型，应该直接报错提示，而不是偷偷改用别的模型，这样很可能会导致一些潜在问题。（希望不是腾讯 API 搞的鬼 😥）

<img width="1109" alt="image" src="https://github.com/songquanpeng/one-api/assets/25194972/e69149d5-81c5-42fb-98cb-dd2fd8cdca23">

<img width="1668" alt="image" src="https://github.com/songquanpeng/one-api/assets/25194972/0f7292e1-e49b-4965-b88c-f25bae40fa0e">
