### ISSUE TITLE
coze渠道无法使用

### ISSUE THREAD

**Issue by sparkssssssssss** [songquanpeng/one-api#1462]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用最新版本,
因为没有说明,参考了官方api,以及个人理解,
https://www.coze.cn/space/73317570xxxx/bot/7372728735xxxx/publish
userid = space后面7xxxxx
模型 = botid = bot后面7xxxxxx
秘钥 = 扣子api

添加one-api后,测试和接口调用均提示,
````
The Bot is not currently published to the corresponding platform
````

官方api只需要秘钥和botid即可,测试没有问题
````
curl --location --request POST 'https://api.coze.cn/open_api/v2/chat' \
> --header 'Authorization: Bearer pat_xxxxxx' \
> --header 'Content-Type: application/json' \
> --header 'Accept: */*' \
> --header 'Host: api.coze.cn' \
> --header 'Connection: keep-alive' \
> --data-raw '{
>     "conversation_id": "123",
>     "bot_id": "7xxxxx",
>     "user": "123333333",
>     "query": "{{yourquery}}",
>     "stream":false
> }'
{"messages":[{"role":"assistant","type":"answer","content":"我不太明确你具体的问题是什么呀，请详细说明一下，以便我更好地为你解答。","content_type":"text"},{"role":"assistant","type":"verbose","content":"{\"msg_type\":\"generate_answer_finish\",\"data\":\"\"}","content_type":"text"},{"role":"assistant","type":"follow_up","content":"你可以回答哪些领域的问题？","content_type":"text"},{"role":"assistant","type":"follow_up","content":"如何提高你的回答准确性？","content_type":"text"},{"role":"assistant","type":"follow_up","content":"你是如何学习和不断提升自己的？","content_type":"text"}],"conversation_id":"123","code":0,"msg":"success"}
````

**Comment by sparkssssssss** [comment]
发现登录后的界面有一个@用户7xxxxxx 尝试使用这个7xxxx作为用户id,结果一样,有成功的朋友指点下吗

**Comment by gzspkgypt** [comment]
国内使用代理地址:https://api.coze.cn
国外使用代理地址:https://api.coze.com
区别:国外可以使用gpt4t,gpt4o,国内不行.
使用HongKong云主机测试可以正常使用https://api.coze.com

**Comment by songquanpeng** [comment]
默认的话是 https://api.coze.com，国服的话改一下端点哈

**Comment by sparkssssssss** [comment]
感谢指点,配置成cn的可以了

**Comment by linxp001** [comment]
coze.cn渠道昨天还能正常使用，配置啥都没改，今天突然开始报错——错误:当前 Bot 未发布到对应渠道
使用postman测试可以正常返回

![image](https://github.com/user-attachments/assets/2bb329fb-5521-41f7-abc5-db4dd59143a7)

![image](https://github.com/user-attachments/assets/7f16e3c8-3ce5-4b71-809a-88bb81decdcc)

![image](https://github.com/user-attachments/assets/f89e9d45-41ef-493a-a823-5d3b41db3686)
