### ISSUE TITLE
无法用阿里的 stable-diffusion-xl wanx-v1 在 open-webui 里生成图片

### ISSUE THREAD

**Issue by mlkt** [songquanpeng/one-api#1467]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

这样配置不对吗？
![image](https://github.com/songquanpeng/one-api/assets/10374085/a36f46a7-24ae-4fa5-8836-ea81ddc312a2)
![image](https://github.com/songquanpeng/one-api/assets/10374085/b445c82f-b73e-4b0d-addd-651dc5e9b3ba)
会显示找不到模型

如果用"stable-diffusion-xl"的名字，然后我自己在渠道里加上 stable-diffusion-xl 
![image](https://github.com/songquanpeng/one-api/assets/10374085/be5569e0-ea49-4e97-96bd-b24a652a6d59)
![image](https://github.com/songquanpeng/one-api/assets/10374085/cc8c5949-551f-436f-83bf-234484497843)
![image](https://github.com/songquanpeng/one-api/assets/10374085/047387d1-b32c-4d42-93b4-01b63f6f944a)
会显示不支持这个图像大小

如果用 wanx-v1，会报这个错
![image](https://github.com/songquanpeng/one-api/assets/10374085/f116ec14-00e7-48ad-935c-edbcf29c21d9)
![image](https://github.com/songquanpeng/one-api/assets/10374085/84260a3f-f969-4e28-84be-1d992a327df5)

**Comment by mo2g** [comment]
已提交 PR，等待更新即可

**Comment by mlkt** [comment]
话说最好不要又搞个映射吧

我刚刚自己修复了一下，另外也修复了无法返回 b64_json 格式导致 open-webui 无法识别的问题，建议用我这个
https://github.com/songquanpeng/one-api/pull/1470
