### ISSUE TITLE
default 主题下无法新增 Coze 渠道

### ISSUE THREAD

**Issue by takestairs** [songquanpeng/one-api#1468]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
one api 直接在VPS上部署，使用 SQlite。一开始的主题是 air，后面听说 default 能用 Coze 渠道(https://www.coze.cn/)，就换了 default，然而并不能新增 Coze 渠道，重启/重下运行文件（保留了 .db 文件）都没能解决。
查看default主题源码，在 `/src/constants/channel.constants.js` 文件中确实有 Coze 的信息，type 为 34。使用 Web API 新建一个 type 为 34 的渠道，仍没有显示有关 Coze 的信息。

**复现步骤**

**预期结果**

**相关截图**
![](https://cdn.jsdelivr.net/gh/takestairs/PicsBed@main/2024_05/202405252312925.png)
![](https://cdn.jsdelivr.net/gh/takestairs/PicsBed@main/2024_05/202405252314964.png)
![](https://cdn.jsdelivr.net/gh/takestairs/PicsBed@main/2024_05/202405252311429.png)

如果没有的话，请删除此节。

**Comment by HelloEveryonehh** [comment]
我也遇到了这个问题
![image](https://github.com/songquanpeng/one-api/assets/110333012/9985d962-07ec-46c1-ac42-1554f82f33c6)

**Comment by takestairs** [comment]
> 我也遇到了这个问题
> ![image](https://github.com/songquanpeng/one-api/assets/110333012/9985d962-07ec-46c1-ac42-1554f82f33c6)
> 

你是用的.cn 还是.com？

**Comment by HelloEveryonehh** [comment]
> > 我也遇到了这个问题
> > ![image](https://private-user-images.githubusercontent.com/110333012/333847095-9985d962-07ec-46c1-ac42-1554f82f33c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI1OTQsIm5iZiI6MTcxNjczMjI5NCwicGF0aCI6Ii8xMTAzMzMwMTIvMzMzODQ3MDk1LTk5ODVkOTYyLTA3ZWMtNDZjMS1hYzQyLTE1NTRmODJmMzNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNDA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTFhZTZhNjIyZmEzMDBlMDk5MTNlNTVkODYxNWZiMzg1OWQ3MDg2MjMwMzRhMzQ3ZjE3MzIxZDhlNzEyNjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s6ZKm1tVdgiwxa5J6fF2t9301n8BpivyyT3IFhalBcY)
> 
> 你是用的.cn 还是.com？

我知道为什么啦，UserID没有填的原因

**Comment by sparkssssssss** [comment]
> > > 我也遇到了这个问题
> > > ![image](https://private-user-images.githubusercontent.com/110333012/333847095-9985d962-07ec-46c1-ac42-1554f82f33c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI1OTQsIm5iZiI6MTcxNjczMjI5NCwicGF0aCI6Ii8xMTAzMzMwMTIvMzMzODQ3MDk1LTk5ODVkOTYyLTA3ZWMtNDZjMS1hYzQyLTE1NTRmODJmMzNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNDA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTFhZTZhNjIyZmEzMDBlMDk5MTNlNTVkODYxNWZiMzg1OWQ3MDg2MjMwMzRhMzQ3ZjE3MzIxZDhlNzEyNjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s6ZKm1tVdgiwxa5J6fF2t9301n8BpivyyT3IFhalBcY)
> > 
> > 
> > 你是用的.cn 还是.com？
> 
> 我知道为什么啦，UserID没有填的原因

请教下,用户id是登录后左下角那个@用户7xxxxxx的数字吗?
我尝试了这个id,space后面的id,都不行,
官方api也不用userid

**Comment by takestairs** [comment]
找到解决方式：
拷贝 .db 后本地运行 one.exe，访问 http://127.0.0.1:3000 后即可添加 Coze 渠道，添加好后再把 .db 传回 VPS。全程default主题。

**Comment by wangkai88** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已确认我已升级到最新版本
> * [x]  我已完整查看过项目 README，尤其是常见问题部分
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **问题描述** one api 直接在VPS上部署，使用 SQlite。一开始的主题是 air，后面听说 default 能用 Coze 渠道([https://www.coze.cn/)，就换了](https://www.coze.cn/)%EF%BC%8C%E5%B0%B1%E6%8D%A2%E4%BA%86) default，然而并不能新增 Coze 渠道，重启/重下运行文件（保留了 .db 文件）都没能解决。 查看default主题源码，在 `/src/constants/channel.constants.js` 文件中确实有 Coze 的信息，type 为 34。使用 Web API 新建一个 type 为 34 的渠道，仍没有显示有关 Coze 的信息。
> 
> **复现步骤**
> 
> **预期结果**
> 
> **相关截图** ![](https://camo.githubusercontent.com/9fbc0cf80a3434e7e3025027156335070de3b65328598785193bc4add1adbefe/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f74616b657374616972732f50696373426564406d61696e2f323032345f30352f3230323430353235323331323932352e706e67) ![](https://camo.githubusercontent.com/53081e157fdadb494c3d1feb9825e3c6c4a5779a53ed95a99071a3ee6eeeaee2/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f74616b657374616972732f50696373426564406d61696e2f323032345f30352f3230323430353235323331343936342e706e67) ![](https://camo.githubusercontent.com/c5a46d6e2905624b08f9063d4d32723d5f426286bcc48af6f2f030790852db09/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f74616b657374616972732f50696373426564406d61696e2f323032345f30352f3230323430353235323331313432392e706e67)
> 
> 如果没有的话，请删除此节。

这个coze的botid 可否模糊匹配一下啊 bot-*
