### ISSUE TITLE
分组倍率设置存在问题

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#147]
设置的倍率是 {"default":1,"Azure":1,"vip":1}

![截图_20230612085331](https://github.com/songquanpeng/one-api/assets/19776350/9c86c5b4-39e7-4a93-9591-42481a579a87)

然后访问
http://ip:3000/api/group/
获取的数据是 
{"data":["default","vip","svip","Azure","azure"],"message":"","success":true}

无cdn

**Comment by songquanpeng** [comment]
已经修复并推送了。

**Comment by aiastia** [comment]
正常。 然后目前好像只有 vip 和svip 才有颜色 自定义的没有颜色

**Comment by EricKong1985** [comment]
想问一下，分组倍率是什么意思？
