### ISSUE TITLE
有人遇到过gemini-1.5-flash返回空包问题吗

### ISSUE THREAD

**Issue by bincooo** [songquanpeng/one-api#1479]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
RT
不稳定，经常没有任何文本内容返回

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by crosspacific** [comment]
有的。
我只能用一些cf worker转换，中转一下

**Comment by bincooo** [comment]
> 有的。 我只能用一些cf worker转换，中转一下

啥意思？是ip的问题？

**Comment by sparkssssssssss** [comment]
阿里的qwen,客户端有些参数不支持,就会返回空包,不知道是不是一个原因

**Comment by crosspacific** [comment]
> > 有的。 我只能用一些cf worker转换，中转一下
> 
> 啥意思？是ip的问题？

我的意思是直接用one-api个1.5flash不行；用其他人搭建的Gemini转OpenAI，放在one-api才能用。

**Comment by igophper** [comment]
你好，还能复现吗？还存在问题吗？时间太久的话没反馈就关掉了
