### ISSUE TITLE
点击测试后，程序直接退出

### ISSUE THREAD

**Issue by LinuxSuRen** [songquanpeng/one-api#1486]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**
镜像版本 `justsong/one-api:v0.6.6`

**预期结果**
正常可用

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/1450685/c4f63af8-5bf5-445a-9783-cb1642bea872)

**Comment by tocer** [comment]
+1

**Comment by igophper** [comment]
具体怎么操作的可以详细说明吗？点击哪里的测试按钮，测试的是什么渠道之类的。

**Comment by igophper** [comment]
复现不了先关了
