### ISSUE TITLE
文心一言 ERNIE-Lite-8K-0922调用失败

### ISSUE THREAD

**Issue by shenhuaxx** [songquanpeng/one-api#1487]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，尤其是常见问题部分
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
文心一言 ERNIE-Lite-8K-0922调用失败
**复现步骤**
配置好文心一言渠道和对应ERNIE-Lite-8K-0922模型后发起调用，请求出现错误
2024-05-30T03:24:52.690211794Z [ERR] 2024/05/30 - 03:24:52 | 202405300324525906842026260034 | relay error (channel #5): parameter check failed, max_output_tokens range is [2, 1024] (request id: 202405300324525906842026260034) 

**预期结果**
应该正常返回结果

**Comment by naaaameeee** [comment]
我刚刚调试通过，你看看有没有参考价值吗
![image](https://github.com/songquanpeng/one-api/assets/99253064/808bf145-d471-4ae5-b9d7-7a2293ab6684)
![image](https://github.com/songquanpeng/one-api/assets/99253064/f99a7279-2a16-4f13-8636-5668ebf6d64a)
![image](https://github.com/songquanpeng/one-api/assets/99253064/b051ab8a-8079-4664-a826-881ca2d3f211)

**Comment by shenhuaxx** [comment]
什么都没改动，今天再次测试结果正常。应该是模型层调整导致。tks。

**Comment by shenhuaxx** [comment]
done
