### ISSUE TITLE
能不能加上tiktoken的离线加载

### ISSUE THREAD

**Issue by moslunix** [songquanpeng/one-api#1488]
配置CACHE实际上调用titoken是不生效的，需要调用titoken的离线加载功能才行，titoken默认是从网络加载库到内存的

**Comment by moslunix** [comment]
或者说一下离线加载那些文件应该怎样命名？

**Comment by c121914yu** [comment]
readme 环境变量有说明，能联网环境下把编码下载下来，然后复制到离线就可以了
