### ISSUE TITLE
v0.6.6 Berry 主题不兼容 页面会白屏

### ISSUE THREAD

**Issue by ShinChven** [songquanpeng/one-api#1489]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

berry 主题下

1. 统计失效
2. 从首页点菜单跳转到任何页面会白屏，报这个错。

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by ShinChven** [comment]
前两天部署了一个latest有很多毛病，不知道0.6.6里面会不会也有，比如渠道新建好，莫名其妙的模型没权限，或者模型不存在。

**Comment by ShinChven** [comment]
<img width="603" alt="image" src="https://github.com/songquanpeng/one-api/assets/3351486/6535b659-5ad9-45f7-814a-e2a654908226">
从首页点令牌，白屏，报这个错。

**Comment by gzspkgypt** [comment]
下载最新的镜像安装就好了，已经修复了。

**Comment by ShinChven** [comment]
确认当前Latest镜像已修复
