### ISSUE TITLE
/v1/embeddings 接口报错 版本 v0.4.2+

### ISSUE THREAD

**Issue by ccyuvin** [songquanpeng/one-api#149]
![A%3XP{IA9~5J5XXI6FLC0 H](https://github.com/songquanpeng/one-api/assets/85599321/a2afefe4-b08c-4982-932f-5ea520564225)

/v1/embeddings 接口报错，试了v0.4.3-alpha.1、v0.4.2版本 都是报错，回退到v0.4.0后正常。

json: cannot unmarshal array into Go struct field GeneralOpenAIRequest.input of type string

**Comment by songquanpeng** [comment]
好的，谢谢反馈，我处理一下。

**Comment by songquanpeng** [comment]
原来 input 可以是一个数组。

**Comment by songquanpeng** [comment]
已修复已推送，期待测试反馈。

**Comment by assert6** [comment]
Completions 里的Prompt 也可能是数组
