### ISSUE TITLE
docker版本dns解析超时

### ISSUE THREAD

**Issue by huge1376** [songquanpeng/one-api#1492]
**例行检查**
![image](https://github.com/songquanpeng/one-api/assets/20366069/f69fa92b-d81b-43e2-abdd-b4544c5c86a3)
[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
第一次pull镜像后启动发现一直重启，检查日志发现如下报错
[FATAL] 2024/05/30 - 16:27:50 | [failed to get gpt-3.5-turbo token encoder: Get "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken": dial tcp: lookup openaipublic.blob.core.windows.net on 127.0.0.11:53: read udp 127.0.0.1:32876->127.0.0.11:53: i/o timeout]
通过已有的Issue配置docker-compose的yml文件如下：
oneapi:
    container_name: oneapi
    image: ghcr.io/songquanpeng/one-api:v0.6.6
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - fastgpt
    restart: always
    environment:
      # mysql 连接参数
      - SQL_DSN=root:mysqlpswd@tcp(mysql:3306)/oneapi
      # 登录凭证加密密钥
      - SESSION_SECRET=oneapikey
      # 内存缓存
      - MEMORY_CACHE_ENABLED=true
      # 启动聚合更新，减少数据交互频率
      - BATCH_UPDATE_ENABLED=true
      # 聚合更新时长
      - BATCH_UPDATE_INTERVAL=10
      # 初始化的 root 密钥（建议部署完后更改，否则容易泄露）
      - INITIAL_ROOT_TOKEN=fastgpt
      - TIKTOKEN_CACHE_DIR=/TIKTOKEN_CACHE_DIR
    volumes:
      - ./oneapi:/data
      - ./oneapi/encode:/TIKTOKEN_CACHE_DIR
在宿主机/oneapi/encode目录放入正常主机缓存好的文件/tmp/data-gym-cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4
重启镜像可解决这个问题。但是当我将版本改为latest以后重新pull ，one-api版本更新为0.6.7-alpha3出现了新的encode报错
[FATAL] 2024/05/30 - xxxx | [failed to get gpt-4o token encoder: Get "https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken": dial tcp: lookup openaipublic.blob.core.windows.net on 127.0.0.11:53: read udp 127.0.0.1:32876->127.0.0.11:53: i/o timeout]
我不知道如何对这个文件重命名，通过宿主机curl https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken
是可以下载到o200k_base.tiktoken这个文件的。
暂时没有看到新的issue，我已经退回了v0.6.6
但在对接通义千问渠道时发现渠道测试报错
do request failed: Post"https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation": dial tcp:lookup dashscope.aliyuncs.com on127.0.0.11:53: read udp
127.0.0.1:49061->127.0.0.11:53:i/o
timeout
因为我在同网段另一台服务器用同样系统、环境部署docker可以测试成功，且那台服务器初始化也没有报错，故怀疑docker镜像存在dns问题，在容器内通过nslookup可以解析dashscope.aliyuncs.com，也可以成功ping通。其他域名也可正常访问。
我因此复测了另一台服务器，也是同样的问题。然后删除这两台虚拟化的服务器重新安装部署配置，同样的步骤结果又会不一样，但经常是dns报错，经过五次重复折腾终于又成功了一次。我实在不太明白bug在哪。

**Comment by weixiewen** [comment]
/tmp/data-gym-cache 目录下cl100k_base.tiktoken  9b5ad71b2ce5302211f9c61530b329a4922fc6a4  
o200k_base.tiktoken  fb374d419588a4632f3f557e76b4b70aebbca790

**Comment by skytodmoon** [comment]
怎么解决的老哥，遇到同样的问题
