### ISSUE TITLE
调用阿里云 通义千问api报错

### ISSUE THREAD

**Issue by xiusidunhuren** [songquanpeng/one-api#1498]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
调用阿里云的通义千问1.5-110B-chat模型，点击测试后返回400 如图所示、
**复现步骤**

**预期结果**

**相关截图**
![2](https://github.com/songquanpeng/one-api/assets/86663794/75b35637-9e4a-4f06-9a08-76d454f5d9f9)
![无标题](https://github.com/songquanpeng/one-api/assets/86663794/e811484a-2c6e-4dbf-b531-242b60d4b258)

如果没有的话，请删除此节。

**Comment by mo2g** [comment]
默认还没有添加 qwen1.5-110b-chat 模型，在选择模型的时候你应该找不到qwen1.5-110b-chat，是自己输入的吧？

**Comment by mxdlzg** [comment]
千问有渠道吧，你自定义渠道肯定不行。
直接在千问渠道加模型就行，或者加映射

**Comment by xiusidunhuren** [comment]
谢谢，已经解决了
