### ISSUE TITLE
docker 版的怎么没有添加渠道的功能？  

### ISSUE THREAD

**Issue by heming79** [songquanpeng/one-api#1500]
**例行检查**
docker run --name one-api -d --restart always -p 3000:3000 -e TZ=Asia/Shanghai -v /home/ubuntu/data/one-api:/data justsong/one-api

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
docker 版的怎么没有添加渠道的功能？  

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/14069019/d1c3d523-912c-4616-9cda-bf698c26cd6f)
如果没有的话，请删除此节。

**Comment by heming79** [comment]
是不是版本不对 
![image](https://github.com/songquanpeng/one-api/assets/14069019/02e80229-3172-4465-8b3f-f2a86d9a94c2)

**Comment by heming79** [comment]
需要用root 123456 设置 。

**Comment by wencan** [comment]
@heming79 
我也遇到了这个问题
进入页面，想都没想，注册个帐号，然后新帐号登录……
还以为是因为自己没氪金……
能不能页面给个提示，登录页面提示有默认root，进去后提示需要root添加渠道
