### ISSUE TITLE
azure openai不稳定，隔一会就报错、过一会又正常，do request failed

### ISSUE THREAD

**Issue by yeqing1a** [songquanpeng/one-api#1507]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
基本上现在是失败一次，过几分钟成功一次，过几分钟又失败一次。。。。
报错：
{
  "error": {
    "message": "do request failed: Post \"https://timye.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-02-01\": dial tcp: lookup timye.openai.azure.com on 127.0.0.11:53: no such host (request id: 2024060423520828503329587692701)",
    "type": "one_api_error",
    "param": "",
    "code": "do_request_failed"
  }
}

oneapi容器日志没有其他异常：

[ERR] 2024/06/04 - 23:35:37 | 2024060423353725868674440005909 | relay error (channel id 1, user id: 1): do request failed: Post "https://timye.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-02-01": dial tcp: lookup timye.openai.azure.com on 127.0.0.11:53: no such host (request id: 2024060423353725868674440005909)
[INFO] 2024/06/04 - 23:35:38 | 2024060423353881258824033554203 | user 1 has enough quota 499999998506883, trusted and no need to pre-consume
[ERR] 2024/06/04 - 23:35:38 | 2024060423353881258824033554203 | DoRequest failed: do request failed: Post "https://timye.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-02-01": dial tcp: lookup timye.openai.azure.com on 127.0.0.11:53: server misbehaving
[GIN] 2024/06/04 - 23:35:38 | 2024060423353881258824033554203 | 500 |   88.396933ms |      172.22.0.1 |    POST /v1/chat/completions
[ERR] 2024/06/04 - 23:35:38 | 2024060423353881258824033554203 | relay error (channel id 1, user id: 1): do request failed: Post "https://timye.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-02-01": dial tcp: lookup timye.openai.azure.com on 127.0.0.11:53: server misbehaving (request id: 2024060423353881258824033554203)
[SYS] 2024/06/04 - 23:35:41 | batch update started
[SYS] 2024/06/04 - 23:35:41 | batch update finished
[SYS] 2024/06/04 - 23:35:51 | batch update started
[SYS] 2024/06/04 - 23:35:51 | batch update finished
[SYS] 2024/06/04 - 23:36:01 | batch update started

**复现步骤**

**预期结果**

<img width="1051" alt="image" src="https://github.com/songquanpeng/one-api/assets/147218308/e7c3b0df-4688-4f32-bd56-40af890ef62e">

**Comment by gzspkgypt** [comment]
我已经稳定使用了3个多月了，没有遇到你描述的问题，可能是配置问题，或者是使用的web壳子问题。

**Comment by ygai002** [comment]
> 我已经稳定使用了3个多月了，没有遇到你描述的问题，可能是配置问题，或者是使用的web壳子问题。

可否咨询一下 one api 中你是如何配置的呢 ？我测试显示资源404了 ，也不知道是哪里的问题。
![image](https://github.com/songquanpeng/one-api/assets/144642992/2c8eac60-03f8-4604-ac05-ae319244e4f4)

**Comment by igophper** [comment]
这个看不出是one-api的问题，可能是网络问题。
