### ISSUE TITLE
测试成功但是聊天还是无法访问

### ISSUE THREAD

**Issue by Mason-zy** [songquanpeng/one-api#1512]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用docker方式部署，渠道选择通义千问的token，测试成功，也创建了令牌，但是似乎无法调用到令牌，还是访问的默认3.5

**复现步骤**
进入令牌的聊天
**预期结果**
无法访问
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/57906530/1a829c2c-3fe7-4ea9-82a7-2e4a6a28c0a4)
![image](https://github.com/songquanpeng/one-api/assets/57906530/dc7ca80c-faff-432c-bade-4fdb0941dacb)
![image](https://github.com/songquanpeng/one-api/assets/57906530/67b02945-5025-4852-bf89-c3f762ce9126)

**Comment by code-october** [comment]
不是，你要在nextchat里选模型啊，3.5是nextchat的默认模型 😂

![Clip_2024-06-07_08-58-49](https://github.com/songquanpeng/one-api/assets/148516338/63e89b21-a94e-422f-83d7-b41f65dcc8ae)

**Comment by ysq5202121** [comment]
打开设置，把阿里的qwen-turbo 添加进去，然后回到聊天界面选择qwen-turbo就可以聊天
![image](https://github.com/songquanpeng/one-api/assets/8586973/de4e2a9a-3b32-4d16-bd27-aff1a38b11a6)

**Comment by Mason-zy** [comment]
> 不是，你要在nextchat里选模型啊，3.5是nextchat的默认模型 😂
> 
> ![Clip_2024-06-07_08-58-49](https://private-user-images.githubusercontent.com/148516338/337487246-63e89b21-a94e-422f-83d7-b41f65dcc8ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjM0OTMsIm5iZiI6MTcxNzc2MzE5MywicGF0aCI6Ii8xNDg1MTYzMzgvMzM3NDg3MjQ2LTYzZTg5YjIxLWE5NGUtNDIyZi04M2Q3LWI0MWY2NWRjYzhhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxMjI2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzEyMjNhN2JjNWFjYzM4MWEwYzIwMmNmOTM0ZjRhNzEyN2JmM2U1NmIzZmMxNDNlYmE2ZTY3ZTQzYjgzOTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O3NRkNicoi0_uNivffY7LCTbUGXGaHdE4QzRS2nKXNs)

谢谢 已解决
