### ISSUE TITLE
域名生成证书失败：Certbot failed to authenticate some domains

### ISSUE THREAD

**Issue by Bennyggcc** [songquanpeng/one-api#1516]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
执行这一步报错sudo certbot --nginx，提示Certbot failed to authenticate some domains (authenticator: nginx).
想问一下是要购买一个新的域名才能进行身份验证吗，还有如果在境外会不会有影响呢？

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/58056333/db12e58a-853d-4579-97c5-f584a434a41a)
![image](https://github.com/songquanpeng/one-api/assets/58056333/19cf1478-f880-4e2a-8221-033268693696)
![image](https://github.com/songquanpeng/one-api/assets/58056333/b7e70aaa-9e58-4eec-959b-c2462c1ce501)

**Comment by code-october** [comment]
你没有换成你的域名吗？你域名添加服务器IP的A记录了吗？
![image](https://github.com/songquanpeng/one-api/assets/148516338/1af921dc-84dc-4aa7-9ba4-66b9e4afedfa)

**Comment by Bennyggcc** [comment]
请问是要在GoDaddy或Namecheap平台上购买域名，然后在DNS 设置中添加服务器IP的A记录吗？下面报错信息中的域名我是输入了在GoDaddy上申请的一个网址名。不好意思小白一个，请问是要怎么操作呢
![1717854183803](https://github.com/songquanpeng/one-api/assets/58056333/750a3f72-ea9a-45a8-8fe5-7a8872b836d2)

**Comment by code-october** [comment]
域名哪里的都行，但是要能够添加A记录解析到你的服务器IP上，添加完才能使用certbot生成证书，像这样：

![image](https://github.com/songquanpeng/one-api/assets/148516338/9b92777c-46c5-43c7-a246-80a677f79399)

**Comment by Bennyggcc** [comment]
佬，还是遇到了点问题，在添加域名时要添加TXT记录验证，我是在github上注册的域名，然后按照网上的一些教程在github page上开启https功能，但是也报错了，不知道我是哪一步出了问题。不知道能不能分享几个您参考过的教程我来学习一下呢，感谢
![image](https://github.com/songquanpeng/one-api/assets/58056333/50780800-e8cc-4bb3-9a6c-75b4a7b45e27)
![image](https://github.com/songquanpeng/one-api/assets/58056333/ba892a44-82f6-4e4b-8d40-8df6c71978ea)
