### ISSUE TITLE
通义千问接口不稳定，时常报错relay error，过一会又恢复正常

### ISSUE THREAD

**Issue by yeqing1a** [songquanpeng/one-api#1519]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
大概每天都会发生几次，oneapi日志：

[SYS] 2024/06/11 - 05:53:53 | batch update started 
[SYS] 2024/06/11 - 05:53:53 | batch update finished 
[INFO] 2024/06/11 - 05:53:54 | 2024061105535470361440389634238 | user 1 has enough quota 499999955267737, trusted and no need to pre-consume 
[ERR] 2024/06/11 - 05:53:54 | 2024061105535470361440389634238 | relay error happen, status code is 400, won't retry in this case 
[GIN] 2024/06/11 - 05:53:54 | 2024061105535470361440389634238 | 400 |   48.060891ms |  101.126.13.246 |    POST /v1/chat/completions
[ERR] 2024/06/11 - 05:53:54 | 2024061105535470361440389634238 | relay error (channel id 2, user id: 1):  (request id: 2024061105535470361440389634238) 
[INFO] 2024/06/11 - 05:53:56 | 2024061105535656616848233924015 | user 1 has enough quota 499999955267737, trusted and no need to pre-consume 
[ERR] 2024/06/11 - 05:53:56 | 2024061105535656616848233924015 | relay error happen, status code is 400, won't retry in this case 
[GIN] 2024/06/11 - 05:53:56 | 2024061105535656616848233924015 | 400 |   28.401502ms |  101.126.13.246 |    POST /v1/chat/completions
[ERR] 2024/06/11 - 05:53:56 | 2024061105535656616848233924015 | relay error (channel id 2, user id: 1):  (request id: 2024061105535656616848233924015) 
[SYS] 2024/06/11 - 05:54:53 | batch update started 
[SYS] 2024/06/11 - 05:54:53 | batch update finished

**复现步骤**
此时换其他内容也是一样的结果，见上述日志

**预期结果**
使用的是oneapi最新版本，希望早日恢复正常

**Comment by Forever-Lyj** [comment]
你好解决了吗？怎么解决的现在还有这个问题
