### ISSUE TITLE
请求接入dify知识库

### ISSUE THREAD

**Issue by Mgrsc** [songquanpeng/one-api#1535]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
请求接入dify知识库

**Comment by brokenman1** [comment]
同求

**Comment by igophper** [comment]
是否方便添加dify知识库的文档链接

**Comment by Mgrsc** [comment]
> 是否方便给出dify知识库的文档链接

好的
https://docs.dify.ai/v/zh-hans

**Comment by igophper** [comment]
指的是 通过api维护知识库吗？ https://docs.dify.ai/v/zh-hans/guides/knowledge-base/maintain-dataset-via-api

**Comment by Mgrsc** [comment]
> 指的是 通过api维护知识库吗？ https://docs.dify.ai/v/zh-hans/guides/knowledge-base/maintain-dataset-via-api是指通过 API 维护知识库吗？ https://docs.dify.ai/v/zh-hans/guides/knowledge-base/maintain-dataset-via-api

不是，是通过api调用编排好的工作流或者agentg或者对话型应用等，你可以注册一个dify云看看https://cloud.dify.ai/，创建一个应用然后点击左侧的访问api，可以看到全部的文档，外部的文档也是指向dify内部查看
![image](https://github.com/songquanpeng/one-api/assets/118801216/ebe3edd0-7e2f-4bb8-ad52-41dfd372026e)

![image](https://github.com/songquanpeng/one-api/assets/118801216/ba635828-a2f6-454a-a77c-00f5c303194c)
![image](https://github.com/songquanpeng/one-api/assets/118801216/e1365ab9-3287-4935-af39-501ac191e0da)

**Comment by igophper** [comment]
重复了，先关了。#1325
