### ISSUE TITLE
docker.io 不能访问

### ISSUE THREAD

**Issue by ChengRuiLiang** [songquanpeng/one-api#1537]
执行 docker-compose up -d ，不能正确拉取docker 容器，计算机不能访问docker，能否提供国内镜像地址

**Comment by wencan** [comment]
因为大家都懂的原因
可以改拉 ghcr.io/songquanpeng/one-api

**Comment by lihaotian2018** [comment]
> 因为大家都懂的原因 可以改拉 ghcr.io/songquanpeng/one-api

这个怎么用。 谢谢

**Comment by QAbot-zh** [comment]
rreadme 里不都有写，你是跑docker-compose的就进docker-compose.yml里修改啊

![image](https://github.com/songquanpeng/one-api/assets/40236765/515099a3-05c1-4b6e-ae3e-f2c9dff0c6f0)
