### ISSUE TITLE
[开源合作] 请求添加VChart引用

### ISSUE THREAD

**Issue by da730** [songquanpeng/one-api#1538]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
Hello，我是前端开源图表库[VChart](https://github.com/VisActor/VChart)团队成员，很高兴看到该项目引用了VChart。
我们的智能可视化组件[VMind](https://www.visactor.io/vmind)也将使用one-api作为LLM访问代理层。
请问能否在one-api项目主页添加VChart链接？VChart也可以在[官网](https://www.visactor.io/vchart)和github主页添加one-api的logo，相互宣传一下，万分感谢！

**应用场景**

**Comment by youjin-git** [comment]
你star太少了，肯定不划算啊

**Comment by xuanhun** [comment]
> 你star太少了，肯定不划算啊

要看长期收益，

**Comment by songquanpeng** [comment]
欢迎 pr
