### ISSUE TITLE
gpt-4o计价存在问题

### ISSUE THREAD

**Issue by nonstopfor** [songquanpeng/one-api#1546]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
gpt-4o在one-api网站上显示的计价有问题
**复现步骤**
使用openai-sb渠道，自定义添加gpt-4o模型
**预期结果**
one-api网站上显示的计价大概是官方价格的8倍左右，但从openai-sb的api上看到的余额是没问题的，说明是one-api的计价出现了问题
**相关截图**
如果没有的话，请删除此节。

**Comment by ye4293** [comment]
你应该确认是不是openaisb有问题。他们的换算制度和one是不一样的，还有就是他们更新到最新的编码器了嘛？

**Comment by nonstopfor** [comment]
openaisb的价格我已确认了没有问题（通过他们的余额查询接口），另外编码器看起来不是主要原因，价格差了大概7-8倍，应该不是由编码器导致的

**Comment by QAbot-zh** [comment]
你看下日志里的模型倍率呢，oneapi 什么版本，要是太早的版本就更新下吧，默认渠道已经有 gpt-4o 了的

![image](https://github.com/songquanpeng/one-api/assets/40236765/0eb85594-ad77-467a-9774-68cfa6085f77)

**Comment by nonstopfor** [comment]
> 你看下日志里的模型倍率呢，oneapi 什么版本，要是太早的版本就更新下吧，默认渠道已经有 gpt-4o 了的
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/341697964-0eb85594-ad77-467a-9774-68cfa6085f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Nzc0NDIsIm5iZiI6MTcxODk3NzE0MiwicGF0aCI6Ii80MDIzNjc2NS8zNDE2OTc5NjQtMGViODU1OTQtYWQ3Ny00NjdhLTk3NzQtNjhjZmE2MDg1Zjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEzMzkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOGE5YTU4ZmNhMGQ3NDA2MDQ5ODIzMmFlMGFmZWU0ODFiZWYyNWJlZmUxOWViNzIxYTY2YWNiMzRmNzU0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XoOd_0JeohVMLpBxmQQcvgHY4bJz-o5mrCmx50MVO2o)

日志里的模型倍率是30，应该有问题。oneapi是最新的0.6.6的版本。我用的渠道是openai-sb那个，默认的还没有gpt-4o

**Comment by QAbot-zh** [comment]
> 日志里的模型倍率是30，应该有问题。oneapi是最新的0.6.6的版本。我用的渠道是openai-sb那个，默认的还没有gpt-4o

不应该啊，你肯定不是最新的，30是设置里没有的模型的缺省倍率，还是更新看看吧。或者手动设置一下，模型倍率2.5，补全倍率3
![image](https://github.com/songquanpeng/one-api/assets/40236765/8f5fd343-c8bd-4fd6-b10f-e5d87d7461da)

**Comment by nonstopfor** [comment]
是最新的啊，我还用--version打印了是0.6.6。如何手动设置呢？我觉得可能就是因为自定义模型默认用了缺省倍率？因为openai-sb的渠道里头默认目前没有gpt-4o

**Comment by QAbot-zh** [comment]
进设置里改：

![Uploading Screenshot_20240622_123355.jpg…]()

**Comment by QAbot-zh** [comment]
进设置里改

![Screenshot_20240622_123355](https://github.com/songquanpeng/one-api/assets/40236765/2beef8e8-ada1-4f24-bf7a-48003861712b)

**Comment by nonstopfor** [comment]
手动设置可以了，感谢！
