### ISSUE TITLE
对于报错传递给上游的转发客户端“xx无可用渠道”应该进行禁用

### ISSUE THREAD

**Issue by ye4293** [songquanpeng/one-api#1548]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
![image](https://github.com/songquanpeng/one-api/assets/137054651/3dff0eb4-deed-4cfc-b3d2-534a5e75573e)
对于这种上游客户端提示的无可用渠道，应该予以禁用。不然会一直进行请求。甚至后期可以细化到某个ability，还可以实现对于某个模型限速的禁用
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by igophper** [comment]
pr中已说明不应该被禁用
