### ISSUE TITLE
令牌可以指定具体的渠道

### ISSUE THREAD

**Issue by 63936** [songquanpeng/one-api#155]
如果多个渠道属于同一个用户组，这个用户组的用户在创建令牌时可以指定具体的渠道

**Comment by songquanpeng** [comment]
超级管理员可以指定通道，主要是为了调试用。

让普通用户可以选择通道有什么意义呢？普通用户根本看不到通道列表。

**Comment by xinebf** [comment]
主要是想，生成给某个app用的令牌只让其用特定的渠道，因为现在用下来发现azure相比openai会过滤内容，所以想让某些app只用azure的渠道，某些app用openai的渠道

**Comment by songquanpeng** [comment]
分组功能可以解决这一点。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月13日(星期二) 下午5:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [songquanpeng/one-api] 令牌可以指定具体的渠道 (Issue #155)





 
主要是想，生成给某个app用的令牌只让其用特定的渠道，因为现在用下来发现azure相比openai会过滤内容，所以想让某些app只用azure的渠道，某些app用openai的渠道

**Comment by 63936** [comment]
是要为不同的app创建不同的账户吗，然后通过不同的用户分组指定不同的渠道？

**Comment by songquanpeng** [comment]
是，你这个需求与设计冲突，不打算实现。

**Comment by songquanpeng** [comment]
也谢谢你的理解
