### ISSUE TITLE
请求增加AWS最新的anthropic.claude-3-5-sonnet-20240620-v1:0模型

### ISSUE THREAD

**Issue by tonyleecn** [songquanpeng/one-api#1555]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
AWS出了最新的anthropic.claude-3-5-sonnet-20240620-v1:0，请求增加这个模型
https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html

**Comment by drkhateeb** [comment]
https://www.anthropic.com/
Meet Claude 3.5 Sonnet
Claude 3.5 Sonnet, our most intelligent AI model, is now available.
update Models

**Comment by shaoyun** [comment]
Add support for Claude Sonnet 3.5 @tonyleecn 
https://github.com/songquanpeng/one-api/pull/1567

**Comment by allen12921** [comment]
@shaoyun 
claude-3-5-sonnet-20240620 在最新版本的v0.6.8-alpha.3不能工作，报错{Message:InvokeModel: operation error Bedrock Runtime: InvokeModel, https response error StatusCode: 400, RequestID: 3bef6f15-f6aa-4fb7-a094-46ca5e31eb75, ValidationException: The provided model identifier is invalid. Type: Param: Code:<nil>} StatusCode:500} 

其它模型claude-3-sonnet-20240229等能正常工作

**Comment by ShinChven** [comment]
@songquanpeng 这个问题并没有修好，这个 issue 是 AWS 渠道的 Claude。实测不通。
