### ISSUE TITLE
千问 stream=true 模式下，工具调用失败

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#1573]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
stream=false模式下正常，stream=true模式下无法正确返回 tool 的响应结构。

**测试例子**

```
{
  "model": "qwen-turbo",
  "temperature": 0,
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "几点了"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "nYGo9W",
        "description": "获取用户当前时区的时间。",
        "parameters": {
          "type": "object",
          "properties": {},
          "required": []
        }
      }
    }
  ],
  "tool_choice": "auto"
}
```

**Comment by dirname** [comment]
目前 Function call 信息暂时不支持增量输出，见 https://help.aliyun.com/zh/dashscope/developer-reference/api-details

**Comment by c121914yu** [comment]
> 目前 Function call 信息暂时不支持增量输出，见 https://help.aliyun.com/zh/dashscope/developer-reference/api-details

oneapi 可以做适配吧，不支持的，默认走非流，按流的格式返回即可
