### ISSUE TITLE
谷歌云的Vertex AI如何接入到one-api

### ISSUE THREAD

**Issue by katray608** [songquanpeng/one-api#1574]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
谷歌云的Vertex AI已经有claude模型，开通后不知道如何配置到one-api，有大佬教下吗

**Comment by hidenmaskvip** [comment]
+1

**Comment by cheng-lf** [comment]
+1

**Comment by HynoR** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已确认我已升级到最新版本
> * [x]  我已完整查看过项目 README，已确定现有版本无法满足需求
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **功能描述** 谷歌云的Vertex AI已经有claude模型，开通后不知道如何配置到one-api，有大佬教下吗

vertex开通模型后需要配置服务密钥，token，配额等，比较麻烦。
而且vertex鉴权也有点麻烦，等待其他大佬填坑，可以试试已经有的转换方案。
我也弄了一个vertex go-SDK转openai的测试，目前gemini 1.5 flash / pro 聊天都没啥问题。
https://github.com/HynoR/VertexAI2OpenAIChat
