### ISSUE TITLE
Coze无法添加

### ISSUE THREAD

**Issue by YFSakura** [songquanpeng/one-api#1577]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
不知道Coze为什么添加后无法跑通，有没有人试过接入成功的，麻烦各位讲一讲具体步骤
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/115632796/00449c64-eeff-4fba-9367-2f3ea0303471)

如果没有的话，请删除此节。

**Comment by YFSakura** [comment]
破案了，只支持国际版的扣子，不支持国行版的

**Comment by sparkssssssss** [comment]
https://github.com/songquanpeng/one-api/issues/1462#event-12973112021

**Comment by QAbot-zh** [comment]
怎么会，我都接入了，你改接口地址了吗，国内版的要用对应的cn域名

**Comment by YFSakura** [comment]
> 怎么会，我都接入了，你改接口地址了吗，国内版的要用对应的cn域名

请问是在代理那里填入国内域名吗，不知道在哪改

**Comment by YFSakura** [comment]
> 怎么会，我都接入了，你改接口地址了吗，国内版的要用对应的cn域名

请问是在代理那里填入国内域名吗，不知道在哪改

**Comment by QAbot-zh** [comment]
就是 API 地址这里
![image](https://github.com/songquanpeng/one-api/assets/40236765/a43aca4c-df43-4a1d-8536-abdece1cf7ec)

**Comment by YFSakura** [comment]
> https://github.com/songquanpeng/one-api/issues/1462#event-12973112021

请问是在代理那里填入国内域名吗，不知道在哪改

**Comment by QAbot-zh** [comment]
> > [#1462 (comment)](https://github.com/songquanpeng/one-api/issues/1462#event-12973112021)
> 
> 请问是在代理那里填入国内域名吗，不知道在哪改

代理？你用的是 newapi 吗？

**Comment by YFSakura** [comment]
> > > [#1462 (comment)](https://github.com/songquanpeng/one-api/issues/1462#event-12973112021)
> > 
> > 请问是在代理那里填入国内域名吗，不知道在哪改
> 
> 代理？你用的是 newapi 吗？

oneapi最后一行那个代理网址，已经解决了，我把com换成了cn
