### ISSUE TITLE
提供国行版coze接入

### ISSUE THREAD

**Issue by YFSakura** [songquanpeng/one-api#1578]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
现在的oneapi上只有国际版的coze接入，无法接入国行版扣子，对国内开发者不方便。
**应用场景**
国内开发者使用扣子的情况更多，加入此功能可以更方便开发

**Comment by sparkssssssss** [comment]
国行版本可以的吧,我0.66都已经接入 了,
https://github.com/songquanpeng/one-api/issues/1462#event-12973112021

**Comment by wangkai88** [comment]
这个coze的botid 可否模糊匹配一下啊 bot-*
