### ISSUE TITLE
model is required

### ISSUE THREAD

**Issue by zhangheng2022** [songquanpeng/one-api#1580]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
{"error":{"message":"model is required (request id: 2024062818153452108536804408087)","type":"one_api_error","param":"","code":"invalid_text_request"}}
**复现步骤**
    const stream = await fetch(
      "https://xxxxxxxx.com/v1/chat/completions",
      {
        method: "POST",
        headers: {
          "Content-Type": "text/event-stream",
          "Authorization": `Bearer ${apiKey}-2`,
        },
        body: JSON.stringify({
          model: "gemini-1.5-pro",
          messages: contents,
          stream: true,
        }),
      },
    );
**预期结果**

**相关截图**
如果没有的话，请删除此节。

好奇怪，我已经设置了model

**Comment by QAbot-zh** [comment]
把 Content-Type 换成 application/json 试试呢

**Comment by zhangheng2022** [comment]
> 把 Content-Type 换成 application/json 试试呢

谢谢，可以了
