### ISSUE TITLE
curl 没问题，但是添加到渠道会报错 ，为什么呢

### ISSUE THREAD

**Issue by tomridder** [songquanpeng/one-api#1582]
curl --request POST \
  --url http://154.40.47.16:8100/v1/chat/completions \
  --header 'Authorization: Bearer 2d6e3049-db21-4e10-adee-74822006a827' \
  --header 'content-type: application/json' \
  --data '{
    "model": "gpt-4",
    "messages": [
        {
            "role": "user",
            "content": "你是谁"
        }
    ]
}'

这个是curl的 命令，可以正常返回结果

但是在渠道填入就报错 ，是不是不支持http，只支持https的

**Comment by QAbot-zh** [comment]
不会，我也有渠道是 http + ip 的形式，能正常使用的，你看看有报什么错？
