### ISSUE TITLE
腾讯混元 的 模型重定向 似乎把模型搞反了

### ISSUE THREAD

**Issue by miaowmint** [songquanpeng/one-api#1584]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
模型重定向里的键是 请求体中的模型名称 值是要映射的模型名称

所以重定向应该是这么写的

```
{
  "hunyuan-lite": "hyl",
  "hunyuan-standard": "hys",
  "hunyuan-pro": "hyp"
}
```

但是在腾讯混元这里，重定向被搞反了

我直接请求 hunyuan-lite 模型 会给我重定向到 hyl 

请求 hunyuan-lite 模型后日志显示 `model ratio not found: hyl `

当我把重定向整个反过来才正常

```
{
  "hyl": "hunyuan-lite",
  "hys": "hunyuan-standard",
  "hyp": "hunyuan-pro"
}
```

**复现步骤**

正常配置腾讯混元模型，配置了重定向

**相关截图**

![image](https://github.com/songquanpeng/one-api/assets/58991169/7a53bc8c-d2b7-409c-93fa-76e652a21801)

![image](https://github.com/songquanpeng/one-api/assets/58991169/e9f2c29a-aa68-40ad-9a4a-40caacd5590c)

![image](https://github.com/songquanpeng/one-api/assets/58991169/bc76f0d9-8243-4ef1-b9b5-436e860d3ba3)

![image](https://github.com/songquanpeng/one-api/assets/58991169/b6908fe1-89e8-46c0-b555-40be939e2213)

![image](https://github.com/songquanpeng/one-api/assets/58991169/2b4e5054-ead4-49a1-bd09-06ff6f06b1f1)

![image](https://github.com/songquanpeng/one-api/assets/58991169/89333d1d-78bc-4af5-ad3a-418f215035df)

**Comment by QAbot-zh** [comment]
> 模型重定向里的键是 请求体中的模型名称 值是要映射的模型名称

one-api 是用来响应用户请求的
这句话的理解是，用户发送请求里的模型名称为键，映射为本渠道能提供的模型

**Comment by QAbot-zh** [comment]
是，我理解你说的简化，我也是出于这个想法使用模型重定向功能的。从逻辑上讲，oneapi 首先获取的是用户的请求模型，然后映射为渠道支持的模型，所以前者为键，后者为值是合理的、也是方便程序实现的。
至于示例，有一种简单的解释，比如你的渠道只有gpt-3.5-turbo，但是你经过重定向，看起来可以提供“全版本”的3.5模型..

**Comment by 1731563584** [comment]
现在这个确实有问题，不知道怎么搞的……看看源码去了
