### ISSUE TITLE
api接口登陆成功后access_token为空,无法获取access_token

### ISSUE THREAD

**Issue by peterwillcn** [songquanpeng/one-api#1589]
**问题描述**
api接口登陆成功后access_token为空,无法获取系统管理的access_token, 因此无法脱离web页面自动化部署后续操作了

**复现步骤**
```
curl -H "Content-Type: application/json"  -X POST -d '{"username": "root", "password": "123456"}'  http://localhost:3600/api/user/login
```

**预期结果**

**相关截图**
![30a1fd530f4a513b795d2b17d5a4be2d](https://github.com/songquanpeng/one-api/assets/323794/558cbd4a-ba4d-4992-b009-3bc1670d27fd)

![4011155632cc725afc6773a5182fbbac](https://github.com/songquanpeng/one-api/assets/323794/ff9610bc-8b32-4ff5-bf90-3b1dcd4b1bb9)

**Comment by igophper** [comment]
access_token 是设置页面生成的，账号密码登录时使用的cookie session
你是想用access_token 吗？ 可以在设置页面搞一个[生成系统访问令牌]。账号密码登录暂时没有返回access_token

**Comment by peterwillcn** [comment]
Fixed https://github.com/songquanpeng/one-api/pull/1591

**Comment by songquanpeng** [comment]
其实这个是有意这样设计的，我想问一下是什么场景需要从这个接口返回 access token？

**Comment by peterwillcn** [comment]
用在全自动化部署场景（例如：获取自动生成fastgpt的docker-compose文件里的environment/CHAT_API_KEY），无需人工去页面获取.

**Comment by peterwillcn** [comment]
您谁说这个INITIAL_ROOT_TOKEN环境变量吗？我测试过不起作用呢.
![image](https://github.com/songquanpeng/one-api/assets/323794/f1c06ecd-0977-4639-bdbb-748662dd0eed)

**Comment by peterwillcn** [comment]
安全，用户名和密码保护着access token呢。
您是说这个INITIAL_ROOT_TOKEN环境变量吗？我测试过不起作用呢.
![image](https://github.com/songquanpeng/one-api/assets/323794/f1c06ecd-0977-4639-bdbb-748662dd0eed)

**Comment by peterwillcn** [comment]
您是说这个INITIAL_ROOT_TOKEN环境变量吗？这是默认使用的令牌，还需curl 无界面注入渠道呢,所以access token是curl必须的参数.

**Comment by peterwillcn** [comment]
> 实际上我理解可以这样搞，用一个环境变量来在初始化的时候固定 root 用户的 access token，你觉得呢？我是感觉这个接口返回 token 有点不安全

可以的，我来加PR 还是你来加，这新加入(ROOT_ACCESS_TOKEN)的环境变量哈。

**Comment by peterwillcn** [comment]
> 实际上我理解可以这样搞，用一个环境变量来在初始化的时候固定 root 用户的 access token，你觉得呢？我是感觉这个接口返回 token 有点不安全

@songquanpeng 是的，curl 无界面注入渠道, 所以access token是curl必须的参数.
我来加PR 还是你来加，这新加入(ROOT_ACCESS_TOKEN)的环境变量哈。

**Comment by peterwillcn** [comment]
好的

**Comment by peterwillcn** [comment]
> 你来吧

DONE https://github.com/songquanpeng/one-api/pull/1598
