### ISSUE TITLE
model ratio not found: Qwen/Qwen1.5-14B-Chat

### ISSUE THREAD

**Issue by Essence9999** [songquanpeng/one-api#1593]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用最新版本docker镜像
oneapi调用第三方api，进行工具调用，oneapi日志提示如下：
![image](https://github.com/songquanpeng/one-api/assets/66725845/0ca257fb-22b4-4374-8ed5-edd1468fa461)

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by HynoR** [comment]
这是你没在运营设置里给这个模型加倍率，由于不是很常见的官口模型默认倍率表里没有，自己加一下就行

**Comment by sdytzjp** [comment]
这个倍率做什么的，如果不加会影响正常使用吗

**Comment by Forever-Lyj** [comment]
你好，我现在是7B的模型有这个问题。请问你解决了吗？我的情况是fastgpt在启动的时候可以正常调用模型，过一段时间后就出现你发的这个问题，后面就一直500和200来回跳。
