### ISSUE TITLE
使用豆包向量模型时报错

### ISSUE THREAD

**Issue by cl165** [songquanpeng/one-api#1594]
在oneapi 配置好豆包模型，fastgpt使用时
1、豆包的语言模型可以使用
2、豆包的向量模型无法使用，报错
<img width="937" alt="image" src="https://github.com/songquanpeng/one-api/assets/6203863/c8718937-2727-4759-8a67-ce654440ffaf">

**Comment by igophper** [comment]
好的，我尝试本地复现一下

**Comment by zpcr7** [comment]
有解决嘛？

**Comment by zpcr7** [comment]
遇到了同样的问题

**Comment by igophper** [comment]
后续会处理

**Comment by cl165** [comment]
> 后续会处理
有时间节点吗？

**Comment by lfglfg11** [comment]
是的，无法使用豆包embedding

**Comment by GrayXu** [comment]
doubao的embedding好像只能用VOLC_ACCESSKEY & VOLC_SECRETKEY，现在的支持只是转发v3

**Comment by zpcr7** [comment]
> doubao的embedding好像只能用VOLC_ACCESSKEY & VOLC_SECRETKEY，现在的支持只是转发v3

VOLC_ACCESSKEY & VOLC_SECRETKEY   没看懂

**Comment by GrayXu** [comment]
> VOLC_ACCESSKEY & VOLC_SECRETKEY 没看懂  
我意思是doubao的embed model和chat model不一样，不支持Bearer token直接调用，得用access key和secret key。可能得按他们sdk重写一遍。
