### ISSUE TITLE
优化移动端渠道、令牌、用户管理界面：字段名称和字段值存在布局问题

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#16]
都是上方区域展示字段名称，下方区域展示字段值，而不是像首页那样左右对应展示：
![d06778bb693af99084548f3c1f0f271](https://user-images.githubusercontent.com/75829171/234432947-7819ea37-5c37-40d8-882d-546e7eaaa9dc.jpg)
![82c2634510dd32961bfe027327fa8a3](https://user-images.githubusercontent.com/75829171/234432971-3f78edf4-c78a-45c8-9bf5-a279eaf16533.jpg)
![200c31a5a893c177f568729dd417156](https://user-images.githubusercontent.com/75829171/234432988-ae9bb07d-1201-4f13-90c6-a7e7d475cbbe.jpg)
首页：
![6a1a61c759b116b147a334786ccdfc2](https://user-images.githubusercontent.com/75829171/234433003-5613a210-9da2-4e90-bb89-2c59446c6bba.jpg)
建议统一改成像首页那样的左右对应显示。

**Comment by songquanpeng** [comment]
这个我之前也想解决来着，但是受限于 Semantic UI 库，不太好搞，目前移动端只能说能用。

**Comment by songquanpeng** [comment]
目前暂时不考虑对移动端的 UI 做更多的适配工作了。
