### ISSUE TITLE
接入豆包的Doubao-embedding，查看日志，报错信息是： DoRequest failed: get request url failed: unsupported relay mode 3 for doubao

### ISSUE THREAD

**Issue by zpcr7** [songquanpeng/one-api#1607]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
接入豆包的Doubao-embedding，查看日志，报错信息是： DoRequest failed: get request url failed: unsupported relay mode 3 for doubao
**复现步骤**
配置如图
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/171773052/8bc6113a-82c1-411b-a2e4-a3f5ffd0a8f6)
**保存信息是**
![image](https://github.com/songquanpeng/one-api/assets/171773052/1f9d4770-f45f-4e56-aecb-884623e98c51)

如果没有的话，请删除此节。

**Comment by igophper** [comment]
重复了 #1594

**Comment by YuChaoM** [comment]
我也遇到这个问题，你是怎么解决的
