### ISSUE TITLE
提交超长数据导致内存和 CPU 占用过高的问题

### ISSUE THREAD

**Issue by dabaisuv** [songquanpeng/one-api#161]
我在使用 One-API 项目时，发现只要调用 API 的时候提交很长的数据（测试时500KB）就会导致内存和CPU占用过高，进而导致响应缓慢。推测是因为服务器花费了大量算力计算token。

**Comment by songquanpeng** [comment]
我先自己测试一下，目前的一个 workaround 是通过 Nginx 配置 client_max_body_size。

**Comment by glzjin** [comment]
发现 tiktoken-go 发了个版本修了内存的问题，我自己更新了下编译了一个做了下对比测试，发现没炸CPU和内存的问题了。

**Comment by glzjin** [comment]
https://github.com/pkoukk/tiktoken-go/releases/tag/v0.1.5

**Comment by songquanpeng** [comment]
可以，方便 pr 么

**Comment by glzjin** [comment]
已提交pr。
