### ISSUE TITLE
tool call 调用oneapi报错，用的是moonshot

### ISSUE THREAD

**Issue by xutengfei** [songquanpeng/one-api#1624]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
oneapi 配置了moonshot，通过api调用tool call 调用agent工具报错

**复现步骤**
调用tool call

**预期结果**
成功调用tool

**相关截图**
<img width="1027" alt="image" src="https://github.com/songquanpeng/one-api/assets/1303119/e3a4399c-0be2-4b38-b3af-18c97b79dd69">

**Comment by dirname** [comment]
你好，请尝试更新到 >= `v0.6.8-alpha.1` 版本
