### ISSUE TITLE
oneapi是否可以改为按照【渠道名称+模型名称】的方式进行模型调用

### ISSUE THREAD

**Issue by sdytzjp** [songquanpeng/one-api#1626]
目前的环境是fastgpt4.8.5 配合oneapi0.6.7一起使用，本地docker环境。
现在的需求是：
1、oneapi上有两个文心一言的渠道（文心一言A、文心一言B）、两个通义千万的渠道（通义千万A、通义千万B），分别是A、B两个部门花钱自己购买的
2、fastgpt上创建的AI应用按照部门区分，如何使用每个部门的fastgpt应用分别调用他们自己购买的渠道。
3、由于fastgpt config.json里面指定的仅仅是模型的名称，跟同一个模型在两个渠道里面都存在，Oneapi在优先级相同的情况下好像是随机的在两个渠道中完成调用
4、是否可以改为按照渠道名称+模型名称的方式进行调用，该如何更改？

**Comment by QAbot-zh** [comment]
1. 管理员的 key 可以指定渠道，如“sk-xxxx-100”，即指定使用 Channel 为 100 的 key
2. 可以通过对渠道内的模型名称重命名，不同部门按照不同的模型名称进行调用

**Comment by sdytzjp** [comment]
> 1. 管理员的 key 可以指定渠道，如“sk-xxxx-100”，即指定使用 Channel 为 100 的 key
> 2. 可以通过对渠道内的模型名称重命名，不同部门按照不同的模型名称进行调用

多谢回复。
第一条不适用我的场景，我只能在fastgpt的docker-compose.yml下配置key，而同一台fastgpt上的多个应用会使用这个key到oneapi上随机选一个渠道调用模型，这个不符合我的要求。

第二条，这个方法，你说的是利用渠道下面的模型重定向改名字吗
![image](https://github.com/songquanpeng/one-api/assets/174102361/08bd32b8-26ec-40ea-8b75-c0b5005c98e2)

**Comment by QAbot-zh** [comment]
是的，键名称是要重定向的名称，像图片中这样就可以传“通义千问”来调用 qwen-max

![image](https://github.com/songquanpeng/one-api/assets/40236765/7abf389e-3ab4-41b6-97dd-3a18b0e144e3)

**Comment by sdytzjp** [comment]
多谢了

**Comment by sdytzjp** [comment]
多谢了

**Comment by chung1912** [comment]
这个场景麻烦的，简单的方法，就是直接docker两个oneapi（比如dockercompose两个oneapi-1和oneapi-2），彻底分开管，这样可以保证任何情况下都不会串门

**Comment by SDAIer** [comment]
fastgpt如何对应两个oneapi，docker compose中fastgpt不是只能对应一个oneapi吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 上午8:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [songquanpeng/one-api] oneapi是否可以改为按照【渠道名称+模型名称】的方式进行模型调用 (Issue #1626)




 
这个场景麻烦的，简单的方法，就是直接docker两个oneapi（比如docker-compose两个oneapi-1和oneapi-2），彻底分开管，这样可以保证任何情况下都不会串门
