### ISSUE TITLE
希望支持讯飞星火Spark4.0Ultra

### ISSUE THREAD

**Issue by qidianlinjin1990** [songquanpeng/one-api#1627]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [×] 我已确认目前没有类似 issue
+ [×] 我已确认我已升级到最新版本
+ [×] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [×] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [×] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望支持讯飞星火Spark4.0Ultra，现在只支持max，pro和lite
**应用场景**
4.0赠送了两百万token

**Comment by manjieqi** [comment]
改成v4.0就行

**Comment by qidianlinjin1990** [comment]
改成4.0用的是spark lite，我早就试过了😅不信你自己试试，看看消耗的是不是spark lite的token😅

**Comment by qidianlinjin1990** [comment]
> 改成v4.0就行

改成4.0用的是spark lite，我早就试过了😅不信你自己试试，看看消耗的是不是spark lite的token😅

**Comment by manjieqi** [comment]
https://console.xfyun.cn/services/bm4，这里看token消耗

https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E，请求地址就选择了模型

**Comment by qidianlinjin1990** [comment]
> https://console.xfyun.cn/services/bm4 这里看token消耗
> 
> https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E 请求地址就选择了模型

我早就试过了，换成4.0消耗的就是spark lite的token，不是ultra的，不用你告诉我方法

**Comment by manjieqi** [comment]
虽然但是，我都测试成功了，而且星火支持模型里都加了4.0。你觉得没支持，不应该找找哪里配置错误吗？

**Comment by qidianlinjin1990** [comment]
> 虽然但是，我都测试成功了，而且星火支持模型里都加了4.0。你觉得没支持，不应该找找哪里配置错误吗？


> 虽然但是，我都测试成功了，而且星火支持模型里都加了4.0。你觉得没支持，不应该找找哪里配置错误吗？

我测试也可以通过，那是因为消耗的是lite，你只是测试了，但是你看消耗的是哪个模型了吗，而且最新版是6月22号发布的吧，而且发布写的也是更新了spark lite，哪些支持4.0了，4.0是6月28日才发布的

**Comment by qidianlinjin1990** [comment]
> 虽然但是，我都测试成功了，而且星火支持模型里都加了4.0。你觉得没支持，不应该找找哪里配置错误吗？

还有不只是我一个人，很多人都是遇到这种问题，4.0测试没有问题，以为用的就是ultra的token，但是当他们回到讯飞的网站看到却是消耗的是lite的token，你到底用没用吗，不会只是在one-api的界面测试了一下吧

**Comment by manjieqi** [comment]
<img width="1280" alt="Snipaste_2024-07-13_17-14-37" src="https://github.com/user-attachments/assets/e82d799b-2972-4f12-8d24-d58b0b8119c0">
<img width="721" alt="Snipaste_2024-07-13_17-15-38" src="https://github.com/user-attachments/assets/49184137-8ddb-4eea-be98-d6229f84912e">
<img width="564" alt="Snipaste_2024-07-13_17-16-31" src="https://github.com/user-attachments/assets/85e28c1f-a01c-4bb9-92ec-f082b1bd0a5a">
<img width="719" alt="Snipaste_2024-07-13_17-15-53" src="https://github.com/user-attachments/assets/49e216fc-f3ed-47f6-bbb1-436694ce9c19">
<img width="635" alt="Snipaste_2024-07-13_17-16-52" src="https://github.com/user-attachments/assets/bb7e693a-9caf-4f04-b0cf-4812283b864f">
<img width="641" alt="Snipaste_2024-07-13_17-16-59" src="https://github.com/user-attachments/assets/f41a68bf-c13b-406e-9d26-e724223a6de5">
<img width="638" alt="Snipaste_2024-07-13_17-17-08" src="https://github.com/user-attachments/assets/6dff11e4-671a-430c-8e70-9c695c46d75a">

嗯，善意提示啊，有人和你说过你让人感觉很自以为是吗，我token消耗的链接都特意找出来了，你还说什么只是...，都说了是通过请求地址区分模型的，希望你能说声谢谢

**Comment by qidianlinjin1990** [comment]
> <img alt="Snipaste_2024-07-13_17-14-37" width="1280" src="https://private-user-images.githubusercontent.com/40858189/348462271-e82d799b-2972-4f12-8d24-d58b0b8119c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjMxMzYsIm5iZiI6MTcyMDg2MjgzNiwicGF0aCI6Ii80MDg1ODE4OS8zNDg0NjIyNzEtZTgyZDc5OWItMjk3Mi00ZjEyLThkMjQtZDU4YjBiODExOWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjJhMWU1NjlhZjMwMDM3NWFhODAzMTkxOWI0MmMxNTQyYzdkMzY5MWRlNmNiODJhNjlmMzA1M2Y2ZmI5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRA3gDyaGogZgKDmooy-j6Jy3FgTDhqNZTWUj3NLovc"> <img alt="Snipaste_2024-07-13_17-15-38" width="721" src="https://private-user-images.githubusercontent.com/40858189/348462287-49184137-8ddb-4eea-be98-d6229f84912e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjMxMzYsIm5iZiI6MTcyMDg2MjgzNiwicGF0aCI6Ii80MDg1ODE4OS8zNDg0NjIyODctNDkxODQxMzctOGRkYi00ZWVhLWJlOTgtZDYyMjlmODQ5MTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZmRmMzQzMmZhMjNlODhlMGY5M2ZiYjJjZTYwZWFmNDdlMTg5ZmY0ZWY3NTc1YzMzMDk1ODliYzcyMmY5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.juzw5ppqDlibhveSoOwULwAi7kVf2VC0XMoC8uwPByA"> <img alt="Snipaste_2024-07-13_17-16-31" width="564" src="https://private-user-images.githubusercontent.com/40858189/348462293-85e28c1f-a01c-4bb9-92ec-f082b1bd0a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjMxMzYsIm5iZiI6MTcyMDg2MjgzNiwicGF0aCI6Ii80MDg1ODE4OS8zNDg0NjIyOTMtODVlMjhjMWYtYTAxYy00YmI5LTkyZWMtZjA4MmIxYmQwYTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYWI1ODQzYTlhYTU1ZDM5ZmZiMjczNWM2Y2EyZTUxYWU2NjQxYjQ1NGE2OWIyNTNiYWJkZDhmZDMzY2IyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BKGxm3LbI88mRcxyKL41v4U3GtMTeHZAKNJ1xckP9JY"> <img alt="Snipaste_2024-07-13_17-15-53" width="719" src="https://private-user-images.githubusercontent.com/40858189/348462297-49e216fc-f3ed-47f6-bbb1-436694ce9c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjMxMzYsIm5iZiI6MTcyMDg2MjgzNiwicGF0aCI6Ii80MDg1ODE4OS8zNDg0NjIyOTctNDllMjE2ZmMtZjNlZC00N2Y2LWJiYjEtNDM2Njk0Y2U5YzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OWM4ZmM2ZDJiZmFmNWJlM2FjOWY0ZDgzMmM4ODE4NWI3OTU2MDI0NmRjZGVmMzZhYzYwZDM3OTk4Y2IwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AgGbfvlgcdxiWCXYQdSvqllOEdHGcOqVzX_2JwAaZrE"> <img alt="Snipaste_2024-07-13_17-16-52" width="635" src="https://private-user-images.githubusercontent.com/40858189/348462306-bb7e693a-9caf-4f04-b0cf-4812283b864f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjMxMzYsIm5iZiI6MTcyMDg2MjgzNiwicGF0aCI6Ii80MDg1ODE4OS8zNDg0NjIzMDYtYmI3ZTY5M2EtOWNhZi00ZjA0LWIwY2YtNDgxMjI4M2I4NjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNWU2YjUzZTlhNWFkMGU1YWUyYWZjNzExYmIzMThiZTdiODBhMmUyYTgwZTQyOGE0M2EwMDdiNGRmYzhjMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vhe5AiHQwPMaVn9Ra4UDucwObdGW-_zGWPSOpH5nbsY"> <img alt="Snipaste_2024-07-13_17-16-59" width="641" src="https://private-user-images.githubusercontent.com/40858189/348462311-f41a68bf-c13b-406e-9d26-e724223a6de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjMxMzYsIm5iZiI6MTcyMDg2MjgzNiwicGF0aCI6Ii80MDg1ODE4OS8zNDg0NjIzMTEtZjQxYTY4YmYtYzEzYi00MDZlLTlkMjYtZTcyNDIyM2E2ZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMTZlOTYyZTk3MDE5NzU5YzA2MzNjMzViZDRjN2QwZmU1OGExNzE3YTQ3ZjgwYTBkZmZlYWQ1NDA3ODQ0YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YtNB03QuOYQAJiK-kmTVTi6-PembgO4DXyCp3V4CKMM"> <img alt="Snipaste_2024-07-13_17-17-08" width="638" src="https://private-user-images.githubusercontent.com/40858189/348462318-6dff11e4-671a-430c-8e70-9c695c46d75a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjMxMzYsIm5iZiI6MTcyMDg2MjgzNiwicGF0aCI6Ii80MDg1ODE4OS8zNDg0NjIzMTgtNmRmZjExZTQtNjcxYS00MzBjLThlNzAtOWM2OTVjNDZkNzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZjg3OGZmZGU2NDA1MmIwNDhkNjdhOWZmYTY0ZDRiNjIzMGU2YzhiNGNjOWFhNzFlOThlMDM3ZTRlNDk1MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fh43a-nQF9z9r34iOIShHXzYh1u1vR8X93vvMQh67Lg">
> 嗯，善意提示啊，有人和你说过你让人感觉很自以为是吗，我token消耗的链接都特意找出来了，你还说什么只是...，都说了是通过请求地址区分模型的，希望你能说声谢谢

ok，我试一下，感谢，我才看到0.6.8beta版，我用的还是0.6.7，感谢了，是我的问题🥺大佬别生气🥺
