### ISSUE TITLE
Service 的启动时间过长

### ISSUE THREAD

**Issue by vaayne** [songquanpeng/one-api#1638]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我使用 Google Cloud Run 部署服务，我发现 One-API 的启动时间很长，下面的截图是 6s，本地测试加上 Redis 和 MySQL 更是达到了 10s

**复现步骤**
正常启动服务

**预期结果**
启动时间 1～2s

**相关截图**
<img width="792" alt="image" src="https://github.com/user-attachments/assets/1dbc66ec-0737-4989-8317-667166dfbcb2">

**Comment by vaayne** [comment]
这个不是一个 bug 是个 enhancement，但是我不能修改 tag 了

**Comment by manjieqi** [comment]
docker部署的v0.6.8-alpha.5也有这个问题，而且渠道页面排版有问题
