### ISSUE TITLE
记录用户请求总次数

### ISSUE THREAD

**Issue by jwdstef** [songquanpeng/one-api#165]
**功能描述**
首先感谢群主开源这么好用的项目，希望群主可以加入一个比较常用的功能：在用户管理里面加入调用次数统计，这样方便管理员查看用户的请求频率。
![image](https://github.com/songquanpeng/one-api/assets/3320789/cf421cbc-67ad-44c3-bc12-66cb0c6c7d73)

**Comment by songquanpeng** [comment]
好，之后和消耗额度数统计并实现。

相关 issue：#102，#137
