### ISSUE TITLE
Doubao-embedding无法使用

### ISSUE THREAD

**Issue by shuker2024** [songquanpeng/one-api#1653]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Doubao-embedding报错无法使用
**复现步骤**
添加豆包模型，大模型使用正常，Doubao-embedding模型报错

**错误日志**
Embedding Error eY [Error]: 500 get request url failed: unsupported relay mode 3 for doubao (request id: 2024071511522583480788606643038)
at eV.generate (/app/projects/app/.next/server/chunks/5832.js:15:67761)
at av.makeStatusError (/app/projects/app/.next/server/chunks/5832.js:15:79337)
at av.makeRequest (/app/projects/app/.next/server/chunks/5832.js:15:80260)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async c (/app/projects/app/.next/server/chunks/88788.js:35:1395)
at async y (/app/projects/app/.next/server/chunks/88788.js:6:19568)
at async Promise.all (index 0)
at async u (/app/projects/app/.next/server/chunks/18592.js:280:25170)
at async /app/projects/app/.next/server/chunks/18592.js:282:3244
at async r (/app/projects/app/.next/server/chunks/18592.js:129:14995) {
status: 500,
headers: {
'content-length': '190',
'content-type': 'application/json; charset=utf-8',
date: 'Mon, 15 Jul 2024 11:52:25 GMT',
'x-oneapi-request-id': '2024071511522583480788606643038'
},
error: {
message: 'get request url failed: unsupported relay mode 3 for doubao (request id: 2024071511522583480788606643038)',
type: 'one_api_error',
param: '',
code: 'do_request_failed'
},
code: 'do_request_failed',
param: '',
type: 'one_api_error'
}
error => 500 get request url failed: unsupported relay mode 3 for doubao (request id: 2024071511522583480788606643038)
[Error] 2024-07-15 11:52:25 500 get request url failed: unsupported relay mode 3 for doubao (request id: 2024071511522583480788606643038)
{
message: '500 get request url failed: unsupported relay mode 3 for doubao (request id: 2024071511522583480788606643038)',
stack: 'Error: 500 get request url failed: unsupported relay mode 3 for doubao (request id: 2024071511522583480788606643038)\n' +
' at eV.generate (/app/projects/app/.next/server/chunks/5832.js:15:67761)\n' +
' at av.makeStatusError (/app/projects/app/.next/server/chunks/5832.js:15:79337)\n' +
' at av.makeRequest (/app/projects/app/.next/server/chunks/5832.js:15:80260)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async c (/app/projects/app/.next/server/chunks/88788.js:35:1395)\n' +
' at async y (/app/projects/app/.next/server/chunks/88788.js:6:19568)\n' +
' at async Promise.all (index 0)\n' +
' at async u (/app/projects/app/.next/server/chunks/18592.js:280:25170)\n' +
' at async /app/projects/app/.next/server/chunks/18592.js:282:3244\n' +
' at async r (/app/projects/app/.next/server/chunks/18592.js:129:14995)'
}

**Comment by igophper** [comment]
重复了 #1594
