### ISSUE TITLE
whisper 模型渠道选择问题

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#1655]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**版本**

0.6.7-pro。看了下0.6.8没有whisper变更，暂未测试。

**问题描述**
我尝试在 whisper 中，填写一个不存在的模型（渠道中不存在），并不会提示渠道不存在，而是继续往某个渠道发送，并在 retry 后抛错（错误时间非常长）。而且，使用重定向也是没有办法解决的，我增加了一个 `whisper-1-test` 的自定义模型，并重定向到 `whisper-1`，发现没有生效。

错误信息：

```json
{
    "error": {
        "message": "type one_api_error, code request_error, message type , code DeploymentNotFound, message The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. (request id: 2024071602312361803367579358858) (request id: 2024071602312360508547783018562)",
        "type": "one_api_error",
        "param": "",
        "code": "request_error"
    }
}
```

**复现步骤**

发出一个 whisper 模型请求，修改 model 为不存在的渠道。

```bash
curl --location --request POST 'https://xxxxx/v1/audio/transcriptions' \
--header 'Authorization: Bearer sk-xxxx' \
--form 'model="whisper-1-test"' \
--form 'file=@"/xxx/1721096684585.mp3"'
```

**预期结果**

直接提示，渠道不存在

**相关截图**
如果没有的话，请删除此节。

**Comment by sdytzjp** [comment]
我测试的效果是无论model使用什么名字都会去找whisper-1

**Comment by deadnessking** [comment]
tts-1似乎也有类似的问题

**Comment by William-715** [comment]
> 我测试的效果是无论model使用什么名字都会去找whisper-1

是的，最新版本还是有这个问题。
