### ISSUE TITLE
coze.cn渠道昨天还能正常使用，配置啥都没改，今天突然开始报错——错误:当前 Bot 未发布到对应渠道

### ISSUE THREAD

**Issue by linxp001** [songquanpeng/one-api#1656]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
coze.cn渠道昨天还能正常使用，配置啥都没改，今天突然开始报错——错误:当前 Bot 未发布到对应渠道
使用postman测试可以正常返回
**复现步骤**
![image](https://github.com/user-attachments/assets/f79de798-6140-4881-bba1-70198a5f3c26)
![image](https://github.com/user-attachments/assets/1114ba95-74f4-4345-8db8-873ca9f118d6)

**预期结果**
可以正常返回coze.cn请求结果
**相关截图**
![image](https://github.com/user-attachments/assets/e98ede3f-f9c2-47fa-ad2e-6faa917e34a7)

如果没有的话，请删除此节。

**Comment by yanickxia** [comment]
coze 应该是访问的 coze.com  ，和 cn 是分来的感觉

**Comment by linxp001** [comment]
解决了，不应该使用别名测试。

**Comment by wangkai88** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已确认我已升级到最新版本
> * [x]  我已完整查看过项目 README，尤其是常见问题部分
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **问题描述** coze.cn渠道昨天还能正常使用，配置啥都没改，今天突然开始报错——错误:当前 Bot 未发布到对应渠道 使用postman测试可以正常返回 **复现步骤** ![image](https://private-user-images.githubusercontent.com/75927451/348932189-f79de798-6140-4881-bba1-70198a5f3c26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTU1NTYsIm5iZiI6MTcyNjU1NTI1NiwicGF0aCI6Ii83NTkyNzQ1MS8zNDg5MzIxODktZjc5ZGU3OTgtNjE0MC00ODgxLWJiYTEtNzAxOThhNWYzYzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA2NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYjRjZDkyNGRiODdhOTgyNzIyNzViYzZmMzQ2OGViOTZiZWZjZjU2MjBkMzgzNzBhZWJiY2VhZjVmYzM3ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRjGNXRNlDMXVW3sxqtPSLAb1XzU5SgeiZTuFfv6RZg) ![image](https://private-user-images.githubusercontent.com/75927451/348932228-1114ba95-74f4-4345-8db8-873ca9f118d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTU1NTYsIm5iZiI6MTcyNjU1NTI1NiwicGF0aCI6Ii83NTkyNzQ1MS8zNDg5MzIyMjgtMTExNGJhOTUtNzRmNC00MzQ1LThkYjgtODczY2E5ZjExOGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA2NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4OGE3NDJkM2JhMDhlMTQ3OWY3YWZmNzkyMzUzMDRmMjNlY2YxNDYyOTMxZTI3YTliYWNmZTE4OTJmMDNjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUwVtG9wtC4o8O2fuq-bmGp0NsugifU0f2SRESrlrMs)
> 
> **预期结果** 可以正常返回coze.cn请求结果 **相关截图** ![image](https://private-user-images.githubusercontent.com/75927451/348932264-e98ede3f-f9c2-47fa-ad2e-6faa917e34a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTU1NTYsIm5iZiI6MTcyNjU1NTI1NiwicGF0aCI6Ii83NTkyNzQ1MS8zNDg5MzIyNjQtZTk4ZWRlM2YtZjljMi00N2ZhLWFkMmUtNmZhYTkxN2UzNGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA2NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTIwMjA2MTNlMDc3ODBlNjQ5MDVhZjYzNGVkNmY4MzU3MzlmZmI1OTJlNzJjYmI4MzdiZGY4NThiNDlmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EUsjb1s3E4Yw9ROG5Fc7VJA5gC4UkIrsErynv7xKouE)
> 
> 如果没有的话，请删除此节。

这个coze的botid 可否模糊匹配一下啊 bot-*
