### ISSUE TITLE
Prompt 也可能是数组

### ISSUE THREAD

**Issue by assert6** [songquanpeng/one-api#166]
[https://github.com/songquanpeng/one-api/issues/149](https://github.com/songquanpeng/one-api/issues/149)
Prompt 也可能是数组
![image](https://github.com/songquanpeng/one-api/assets/28561563/3f57ed2d-2452-45e5-aed6-7b31ea797476)
![image](https://github.com/songquanpeng/one-api/assets/28561563/47b66501-5cef-4667-ba1f-39392b65fbe8)
![image](https://github.com/songquanpeng/one-api/assets/28561563/535f4044-01a4-47bd-b3e4-34d414934eb0)

**Comment by songquanpeng** [comment]
盲猜没有测试，如果要支持多类型，prompt 的类型需要是 any：
![image](https://github.com/songquanpeng/one-api/assets/39998050/e69d7d70-cb9b-4b84-b230-b983179e973f)
