### ISSUE TITLE
关于讯飞星火Spark 4.0 Ultra和Spark Pro-128k两个模型调用失败的疑问

### ISSUE THREAD

**Issue by NJYZ-96** [songquanpeng/one-api#1669]
目前one-api版本：0.6.7
1：讯飞星火似乎是通过接口地址中的版本号来确定具体模型的，那么是否一个渠道只能对应一个星火模型，想要多个模型就要建多个渠道？
2、Spark Pro-128k这个模型我在讯飞的文档中没有找到版本号，请求地址是：wss://spark-api.xf-yun.com/chat/pro-128k 那么我版本号应该填写什么？我测试不填的话是默认走的Spark Lite通道；
3、one-api 0.6.7版本是不支持Spark 4.0 Ultra模型吗？我模型版本那填的v4.0，但测试报错，错误：xunfei empty response detected；我看https://github.com/songquanpeng/one-api/issues/1627 这个议题里面有人是可以用Spark 4.0 Ultra的，是我哪里错了吗？

**Comment by QAbot-zh** [comment]
我看帖子那个人用的不是 0.6.8 beta 才可以的吗

![image](https://github.com/user-attachments/assets/5bd0821a-1b22-4df4-abc9-508b492ab0e7)

**Comment by QAbot-zh** [comment]
升级到0.6.8就好了，实测填v4.0可以调用 ultra

**Comment by NJYZ-96** [comment]
> Spark Pro-128k

好的，那我等待正式版推送好了，

请问Spark Pro-128k这个模型你知道它的接口版本是什么吗？我在星火的文档里没看到

**Comment by NJYZ-96** [comment]
> 升级到0.6.8就好了，实测填v4.0可以调用 ultra

好的，那我等待正式版推送好了，

请问Spark Pro-128k这个模型你知道它的接口版本是什么吗？我在星火的文档里没看到

**Comment by QAbot-zh** [comment]
不得不说星火接口真是异常混乱，人家是版本+chat，它是chat+模型，one-api 应该还没适配，没找到对应的实现

![image](https://github.com/user-attachments/assets/accec8c6-9ca2-4e90-850a-6c98f6fa81df)

**Comment by huluohu** [comment]
确实，讯飞的这个接口设计真的超级业余，跟个裹脚布似的。
