### ISSUE TITLE
官方 demo 无法测试成功

### ISSUE THREAD

**Issue by songquanpeng** [songquanpeng/one-api#168]
从原 issue #164 中复制而来：

![image](https://github.com/songquanpeng/one-api/assets/40910637/9c931342-ac84-4818-9c93-4419018cb4e2)
好几个官方demo都跑不了诶 啊这

> 所以是哪几个跑不了？如果是用到了未实现的 API 确实可能出错。
> 
> 但是我看最后的那个报错，报错信息应该是“无效的 token”，这个是你传入的 One API 令牌有问题。

同一个令牌 在跑model list的时候没问题，别的测了几个都不行。
最关键的 https://api.openai.com/v1/completions，跑不起来

_Originally posted by @Ikaros-521 in https://github.com/songquanpeng/one-api/issues/164#issuecomment-1593121031_

**Comment by songquanpeng** [comment]
@Ikaros-521 新 issue 在这里，留言可以订阅。

官方 demo 列表：https://platform.openai.com/examples

**Comment by Ikaros-521** [comment]
插眼

**Comment by ChangeYu0229** [comment]
有Q群吗

**Comment by ChangeYu0229** [comment]
有创建接口地址的教程吗~

**Comment by songquanpeng** [comment]
> 有Q群吗

Demo 站首页。

**Comment by songquanpeng** [comment]
貌似是这样用的：
```python
import openai

#将这里换成你在aiproxy api keys拿到的密钥
openai.api_key = "ap-xxx"
#这里将官方的接口访问地址，替换成aiproxy的入口地址
openai.api_base = "https://api.aiproxy.io/v1"
#请求chat接口，调用gpt3.5模型
res = openai.ChatCompletion.create(
    max_tokens=1000,
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hi"}],
)
print(res)
```

Ref: https://docs.aiproxy.io/openai/sdk#开始聊天

**Comment by songquanpeng** [comment]
经过 @Ikaros-521  确认，是其使用的问题，One API 工作正常。

**Comment by Ikaros-521** [comment]
正常配置  
![image](https://github.com/songquanpeng/one-api/assets/40910637/388bc716-1a3a-491e-a642-6b19342a8d28)

测试 + 余额  
![image](https://github.com/songquanpeng/one-api/assets/40910637/475636e3-e514-45ab-bc23-3201fbae51fd)

创建测试令牌，注意！额度多给点，达芬奇3官方demo测一次要140左右的额度！额度不等于美刀  
![image](https://github.com/songquanpeng/one-api/assets/40910637/0e6b1341-059d-4777-82df-93476dd6c78a)

根据文档做了nginx转发，如果没有的话，默认的3000端口，自行适配  
![image](https://github.com/songquanpeng/one-api/assets/40910637/7692bde8-57a7-43f5-afbc-304a7a5359d6)
```
import os
import openai
openai.api_key = "生成的令牌"
openai.api_base = "http://服务器IP地址:3000/v1"
#openai.api_base = "https://openai.justsong.cn/v1"
#openai.api_base = "https://api.openai.com/v1"

resp = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "hi"}]
)
resp = resp['choices'][0]['message']['content']

print(resp)
```

![image](https://github.com/songquanpeng/one-api/assets/40910637/49533812-9633-4cf7-8c90-25e099a0d923)
```
import os
import openai
openai.api_key = "生成的令牌"
#openai.api_base = "https://openai-pag.wangzhishi.net/v1"
openai.api_base = "http://服务器IP地址/v1"

try:
    # print(openai.Model.list())

    response = openai.Completion.create(
        model="text-davinci-003",
        prompt="Say this is a test",
        max_tokens=7,
        temperature=0
    )
    print(response)
    print(response.choices[0].text)
except Exception as e:
    print(f"Error: {e}")
```
