### ISSUE TITLE
流式响应不符合openai标准格式

### ISSUE THREAD

**Issue by NiceToMeetYou2** [songquanpeng/one-api#1688]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
流式响应不符合openai标准格式。
对于chat/completions接口的调用，
非流式时，其结果在choice中的message字段，
流式时，其结果在choice中的delta字段。
虽然两者结构是相同的，但adaptor在作转换时没有进行区分，可能会导致使用异常。

**复现步骤**

**预期结果**
以下是正常的流式响应
![截图 2024-07-24 14-45-28](https://github.com/user-attachments/assets/fe130410-ae75-4f44-ac95-534602f504b0)

**相关截图**
如果没有的话，请删除此节。

**Comment by NiceToMeetYou2** [comment]
@songquanpeng

**Comment by WaitFFly** [comment]
解决了吗，豆包流式返回最后一个响应中choices是空的，one-api对此没有进行处理，导致会有空指针异常

>

<img width="552" height="385" alt="Image" src="https://github.com/user-attachments/assets/c476440f-a958-42c7-b0a3-7cc3d138995a" />
