### ISSUE TITLE
不定期出现 model_not_found 错误

### ISSUE THREAD

**Issue by CNWann** [songquanpeng/one-api#169]
使用0.4.3版本，接口返回会不定期出现model_not_found
error.log中有The model: `gpt-4` does not exist的记录

![图片](https://github.com/songquanpeng/one-api/assets/26641645/634c6b11-94ae-43e0-bda4-709bfbb23e91)

![图片](https://github.com/songquanpeng/one-api/assets/26641645/05408d31-de85-4791-b87b-613082b7dda4)

**Comment by songquanpeng** [comment]
你的 ID 为 2 的渠道支持 gpt-4 吗？

**Comment by CNWann** [comment]
支持的，用的同一个key，在linux中使用while死循环curl请求接口出现的这个错误

**Comment by songquanpeng** [comment]
这个报错并不是 One API 的报错，上游通道是哪一家？

**Comment by CNWann** [comment]
![图片](https://github.com/songquanpeng/one-api/assets/26641645/605a09d2-acbc-4d6d-a81e-3390b4b372cf)

**Comment by songquanpeng** [comment]
我指的是 ID 为 2 的通道是哪一家呢？我感觉

> 这个报错并不是 One API 的报错，上游通道是哪一家？

说错了，还真是 One API 的报错，2333

**Comment by CNWann** [comment]
> 这个报错并不是 One API 的报错，上游通道是哪一家？

用的自定义渠道，用同样的死循环方式测试了五分钟过，渠道那边是正常的

**Comment by songquanpeng** [comment]
Okay，测试脚本如果方便的话发一下我试一下，这个是接口 `/v1/models/:model` 报的错。

**Comment by CNWann** [comment]
测试脚本如下：

while true
do
time curl https://ONEAPIURL/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer ONEAPIKEY" -d '{"model": "gpt-4","messages": [{"role": "user", "content": "say test"}]}'
done

**Comment by songquanpeng** [comment]
> Okay，测试脚本如果方便的话发一下我试一下，这个是接口 `/v1/models/:model` 报的错。

不过我看这个既然是 Relay  错误，所以这个有可能不是 One API 的报错，而是正好用了一样的报错信息，因为估计别人也用了 GitHub Copilot 来协助实现。

**Comment by songquanpeng** [comment]
你可以直接测试你的 ID 为 2 的渠道试一下吗？

**Comment by CNWann** [comment]
刚通过查询数据库发现，渠道ID2是3.5的key，并没有配置gpt4模型，在调用的gpt4的时候应该不会轮询到这个渠道才对

![图片](https://github.com/songquanpeng/one-api/assets/26641645/92569119-180c-4aaa-a5f6-b3de000f69a9)

**Comment by songquanpeng** [comment]
你是不是指定渠道了？

**Comment by CNWann** [comment]
请求的时候没有指定，用的是one api子帐号创建的key

**Comment by songquanpeng** [comment]
试一下这个：`select * from abilities where channel_id=2`

**Comment by CNWann** [comment]
渠道分组和用户分组都是default，请求是用的curl https://ONEAPIURL/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer ONEAPIKEY" -d '{"model": "gpt-4","messages": [{"role": "user", "content": "say test"}]}'

![图片](https://github.com/songquanpeng/one-api/assets/26641645/6f90a177-cfcd-4cca-88c4-1971fdd85498)
![图片](https://github.com/songquanpeng/one-api/assets/26641645/2bf8bdfa-a3f6-4600-bfc1-b298c7634a72)

**Comment by CNWann** [comment]
abilities 有显示gpt4

![图片](https://github.com/songquanpeng/one-api/assets/26641645/f1baeb7a-7044-4f36-930b-15a6a8686328)

**Comment by songquanpeng** [comment]
可以进行渠道编辑页面重新提交一下，然后再执行上面 SQL 吗？

**Comment by songquanpeng** [comment]
我刚刚测试了一下，确实是调用了不支持 gpt-4 的通道的报错：
```
{
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": "",
        "code": "model_not_found"
    }
}
```

**Comment by CNWann** [comment]
可能是我添加渠道的时候模型没关联好，我去删掉重新添加一遍

**Comment by songquanpeng** [comment]
这个很奇怪，直接点提交也应该会重建 ability 记录的。

我感觉有可能是并发出现的问题，你是不是之前不小心把 gpt-4 加进去点了提交然后又立即改了？

**Comment by CNWann** [comment]
我预计可能是这种场景：ID2的渠道之前是gpt4测试，后面改成了gpt3并去掉了gpt4的模型，channels表中有更新，abilities表没更新过来

**Comment by songquanpeng** [comment]
很奇怪哈，除非你用程序来改的，手动修改应该不会出现这种并发问题。

**Comment by songquanpeng** [comment]
暂时先关了，如果有其他人能复现我再调查一次。

**Comment by CNWann** [comment]
thx，应该是我操作的问题，清空渠道重新添加后，测试目前正常

**Comment by limboys** [comment]
测试 30并发就下会出现model丢失的情况
![img_v3_02g3_cce4e915-d318-4940-9b6d-119c3538700g](https://github.com/user-attachments/assets/9f6bc9b2-8429-4c82-ae72-e4188db0dbd8)

**Comment by sunqb** [comment]
同样出现了高并发下 model 丢失的情况。

**Comment by sunqb** [comment]
> 同样出现了高并发下 model 丢失的情况。

原因是多渠道的模型映射问题，后面再有谁遇到可以参考一下。多个渠道配置了大小写不敏感的同样的模型映射的，导出出问题，起名字的时候区分下即可。
