### ISSUE TITLE
为Ollama渠道添加context window和max tokens相关Options参数

### ISSUE THREAD

**Issue by MotorBottle** [songquanpeng/one-api#1691]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
为Ollama渠道添加两个新的可选参数
***模型回答token数参数***
为Ollama渠道添加`max_tokens`参数，对应ollama本身的`num_predict`参数。
***上下文大小参数***
经我测试，如不设定上下文参数，ollama将采用默认参数，多数模型的默认上下文只设定为1024/2048 tokens，远小于很多模型的实际上下文能力，也不足以满足很多类型的任务。因此需要在Ollama渠道请求中添加`num_ctx`参数来设定ollama模型的context window，openai本身并没有设置context window的参数，因此无直接对应的参数，需要另行增加。

Ollama官方文档内容：
```
parameter num_ctx <int>          Set the context size
parameter num_predict <int>      Max number of tokens to predict
```

**应用场景**
使用ollama渠道时设置对应的上下文窗口大小以及输出token限制。

**Comment by SDAIer** [comment]
为什么oneapi增加了num_ctx参数后也没有生效，使用0.6.9-alpha
curl --location --request POST 'http://172.22.1.39:3001/v1/chat/completions' \
--header 'Authorization: Bearer sk-fastgpt' \
--header 'Content-Type: application/json' \
--data '{ 
"model": "qwen2.5:32b", 
"stream": false, 
"temperature": 1, 
"max_tokens": 2000, 
"num_ctx": 120000, 
"messages": [
{
"role": "user",
"content": "你是谁"
}
]
}'

ollama日志显示ctx_szie还是默认的8192
