### ISSUE TITLE
 通义千问VL：qwen-vl-v1模型，curl报错url error

### ISSUE THREAD

**Issue by sdytzjp** [songquanpeng/one-api#1698]
通义千问VL：qwen-vl-v1模型，通过oneapi渠道测试成功。

使用CURL命令测试，提示URL错误（img图片的连接是可以打开的
）。针对多模态模型后面的地址对吗：/v1/chat/completions

curl --location --request POST 'http://172.16.1.219:3001/v1/chat/completions'
--header 'Authorization: Bearer sk-fastgpt'
--header 'Content-Type: application/json'
--data '{
"model": "qwen-vl-v1",
"max_tokens": 400,
"messages": [
{
"role": "user",
"content": [
{"image": "https://q8.itc.cn/c_lfill,w_640,h_426,g_face/images03/20240727/f2b8942be4c74a7b94e55f6b900632aa.jpeg"},
{"text": "这是什么?"}
]
}
]
}'

{"error":{"message":"url error, please check url！ (request id: 2024072620311947445322302636794)","type":"upstream_error","param":"400","code":"bad_response_status_code

**Comment by Louis9966** [comment]
请问答主解决了吗？我也遇到了同样的问题

**Comment by gaord** [comment]
同样的错误。使用qwen-plus文本模型没有问题。版本是0.6.7.
curl --location --request POST 'https://localhost:3001/v1/chat/completions' \
--header 'Authorization: Bearer sk-xxxx \
--header 'Content-Type: application/json' \
--data-raw '{
  "model": "qwen-vl-plus",
  "stream": false,
  "temperature": 0.6,
  "max_tokens": 2000,
  "messages": [
    {
      "role": "user",
      "content": "需要一个笑话"
    }
  ]
}'
{"error":{"message":"url error, please check url！ (request id: 2024091322403281567925483608254)","type":"upstream_error","param":"400","code":"bad_response_status_code"}}%

**Comment by gaord** [comment]
![image](https://github.com/user-attachments/assets/a47db57d-643c-46a6-8641-d00a022256de)
研究了代码，发现通义千问的渠道实现比较初略，只有文本的，没有图片的；其他的大部分渠道都是这么实现的。因为各个渠道的接口基本上是openai规格的，要使用各个渠道的多模态模型能力，可以使用自定义渠道避免这个问题。因为自定义渠道实现的比较早，也比较完整。
如上图添加新的渠道就可以工作了。

**Comment by sdytzjp** [comment]
端口号写错了，应该是onepai的3003



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月13日(周五) 晚上10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [songquanpeng/one-api]  通义千问VL：qwen-vl-v1模型，curl报错url error (Issue #1698)




 
同样的错误。使用qwen-plus文本模型没有问题。版本是0.6.7.
 curl --location --request POST 'https://localhost:3001/v1/chat/completions' 
 --header 'Authorization: Bearer sk-xxxx 
 --header 'Content-Type: application/json' 
 --data-raw '{
 "model": "qwen-vl-plus",
 "stream": false,
 "temperature": 0.6,
 "max_tokens": 2000,
 "messages": [
 {
 "role": "user",
 "content": "需要一个笑话"
 }
 ]
 }'
 {"error":{"message":"url error, please check url！ (request id: 2024091322403281567925483608254)","type":"upstream_error","param":"400","code":"bad_response_status_code"}}%

**Comment by sdytzjp** [comment]
> curl --location --request POST 'http://172.16.1.219:3001/v1/chat/completions'
> --header 'Authorization: Bearer sk-fastgpt'
> --header 'Content-Type: application/json'
> --data '{
> "model": "qwen-vl-v1",
> "max_tokens": 400,
> "messages": [
> {
> "role": "user",
> "content": [
> {"image": "https://q8.itc.cn/c_lfill,w_640,h_426,g_face/images03/20240727/f2b8942be4c74a7b94e55f6b900632aa.jpeg"},
> {"text": "这是什么?"}
> ]
> }
> ]
> }'
很棒。

**Comment by cmdhh** [comment]
> ![image](https://private-user-images.githubusercontent.com/9567937/367486717-a47db57d-643c-46a6-8641-d00a022256de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODEwMTQsIm5iZiI6MTcyNzE4MDcxNCwicGF0aCI6Ii85NTY3OTM3LzM2NzQ4NjcxNy1hNDdkYjU3ZC02NDNjLTQ2YTYtODY0MS1kMDBhMDIyMjU2ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMTIyNTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTNlYTM2MDEwMzE5YmYwMGI2MTNjNTNlYTY1MzFiNTYwMWQ0M2U4ZGQwMWViNzdlZDI0OTFlYzAwMzQ4YTdmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MXekk_1PYumRYt9SULgHzEimIrPkwLWyYjPBHeIw4K0) 研究了代码，发现通义千问的渠道实现比较初略，只有文本的，没有图片的；其他的大部分渠道都是这么实现的。因为各个渠道的接口基本上是openai规格的，要使用各个渠道的多模态模型能力，可以使用自定义渠道避免这个问题。因为自定义渠道实现的比较早，也比较完整。 如上图添加新的渠道就可以工作了。

不错

**Comment by wwek** [comment]
> ![image](https://private-user-images.githubusercontent.com/9567937/367486717-a47db57d-643c-46a6-8641-d00a022256de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTQzMjQsIm5iZiI6MTcyNzE5NDAyNCwicGF0aCI6Ii85NTY3OTM3LzM2NzQ4NjcxNy1hNDdkYjU3ZC02NDNjLTQ2YTYtODY0MS1kMDBhMDIyMjU2ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMTYwNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWNlMzJmNjAzMTI4OTJkZjBiY2RjNmYxOGVjNmI0N2RjZTBjN2RlOTVhNDNlMjcyZmRmODE3NGJiNDIzNzA4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RmKgwKqk6FI9SkIA6utn5mys8T_SnzFxDbX9gWLRLvw) 研究了代码，发现通义千问的渠道实现比较初略，只有文本的，没有图片的；其他的大部分渠道都是这么实现的。因为各个渠道的接口基本上是openai规格的，要使用各个渠道的多模态模型能力，可以使用自定义渠道避免这个问题。因为自定义渠道实现的比较早，也比较完整。 如上图添加新的渠道就可以工作了。

感谢可以工作

**Comment by sunqb** [comment]
> > curl --location --request POST 'http://172.16.1.219:3001/v1/chat/completions'
> > --header 'Authorization: Bearer sk-fastgpt'
> > --header 'Content-Type: application/json'
> > --data '{
> > "model": "qwen-vl-v1",
> > "max_tokens": 400,
> > "messages": [
> > {
> > "role": "user",
> > "content": [
> > {"image": "https://q8.itc.cn/c_lfill,w_640,h_426,g_face/images03/20240727/f2b8942be4c74a7b94e55f6b900632aa.jpeg"},
> > {"text": "这是什么?"}
> > ]
> > }
> > ]
> > }'
> > 很棒。

感谢
