### ISSUE TITLE
希望渠道和令牌增加模型维度的设置

### ISSUE THREAD

**Issue by hhz-saner** [songquanpeng/one-api#17]
如下例子
openai 渠道 支持 GPT-3.5
openai-sb 渠道 支持  GPT-3.5 GPT-4

my 令牌 支持 GPT-3.5 GPT-4
other 令牌 支持 GPT-3.5

**Comment by songquanpeng** [comment]
好提议，之后在渠道表中加个字段

**Comment by qyhfrank** [comment]
有什么进展吗？

**Comment by songquanpeng** [comment]
渠道最近会增加分组功能，可以进行细粒度的控制。

**Comment by qyhfrank** [comment]
好的，期待您的进展
