### ISSUE TITLE
项目内定义的google gemini模型和服务商提供的不一致

### ISSUE THREAD

**Issue by longkeyy** [songquanpeng/one-api#1704]
**问题描述**
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/d00126bf-0889-4b79-9a46-30431710dbeb">

**预期结果**

<img width="880" alt="image" src="https://github.com/user-attachments/assets/85c258bb-ca30-4f1e-a1f8-e5d8833e3cfc">

**Comment by QAbot-zh** [comment]
具体渠道填写以供应商提供的名称为主
