### ISSUE TITLE
可以将 http://localhost:3000/ 改为 https://localhost:3000/吗？

### ISSUE THREAD

**Issue by Cuanmaomao** [songquanpeng/one-api#1711]

**Comment by SpiralTower** [comment]
如果服务器是本地的，可以自签一个ssl证书的，如果有公网ip，可以签ip ssl证书

**Comment by MotorBottle** [comment]
caddy做一下反代即可

**Comment by yongshengma** [comment]
> caddy做一下反代即可

放在公网上，这样是不是就不用花钱买证书了？

**Comment by MotorBottle** [comment]
> > caddy做一下反代即可
> 
> 放在公网上，这样是不是就不用花钱买证书了？

你把域名指向运行服务的ip，caddy会自动帮你获取ssl证书，免费的

**Comment by MotorBottle** [comment]
https://blog.motorbottle.site/archives/168
写了个Caddy的教程，你们参考一下吧
