### ISSUE TITLE
模型重定向后测试的显示问题

### ISSUE THREAD

**Issue by meethuhu** [songquanpeng/one-api#1719]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
`v0.68-alpha.6` 版本使用模型重定向后，在web页面进行连通性测试时显示`404`错误，但是不影响正常使用，日志里面的状态码为`200`

`v0.67` 不会出现这个错误

**预期结果**
🫳🐛

**相关截图**
![image](https://github.com/user-attachments/assets/71ded5eb-1373-439f-9ab0-6b3bad14e4f7)
![image](https://github.com/user-attachments/assets/96890332-2bb3-48d6-b259-93ca845ff3b9)

**Comment by meethuhu** [comment]
更新了正式版0.68问题依旧存在

**Comment by darkelfzdy** [comment]
确实，0.68正式版还存在这个问题，不过不影响使用，只是测试渠道不正常
