### ISSUE TITLE
后台设置中存在存储型XSS漏洞

### ISSUE THREAD

**Issue by huamang** [songquanpeng/one-api#1727]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
openai后台设置中，存在存储型XSS漏洞
**复现步骤**
在后台，编辑公共、首页、关于、页脚，都允许使用html代码，但是未对html进行实体化编码，导致出现XSS漏洞。
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/8aa80310-5887-4598-8490-f924168fa4ae">
这里插入一个xss payload后保存：<img src=xxx:x onerror=javascript:alert(1)>
<img width="814" alt="image" src="https://github.com/user-attachments/assets/f5c13d94-a9ea-4de1-a069-81f50973bd96">
访问首页，触发xss漏洞：
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/0776c5db-f2da-48e0-96f1-a154bc7af6ca">

**修复建议**
在内容存储进入数据库前，对内容进行html实体化编码，修复建议：controller/option.go:36 `UpdateOption`函数中添加实体化编码
```go
option.Value = template.HTMLEscaper(option.Value)
```

**Comment by paned0e3cc** [comment]
别水垃圾洞好吧，后台权限，本来就支持html，方便直接管理员diy html ;）

**Comment by huamang** [comment]
> 别水垃圾洞好吧，后台权限，本来就支持html，方便直接管理员diy html ;）

感谢您的关注，对开源项目提issue并不是为了获取什么利益，只是刚好工作中遇到了，顺手提了一下意见：

**Comment by huamang** [comment]
> 别水垃圾洞好吧，后台权限，本来就支持html，方便直接管理员diy html ;）

感谢您的关注与批评，不过本人为开源项目提issue并不是为了谋求利益，只是在工作中恰好遇见，顺手提的一个小建议，仅此而已😄：
1. 对于这个功能点来说，的确是需要能够解析html标签与样式，但是您如果查询一下我的修复建议中：`template.HTMLEscaper`这个函数，就可以知道这个函数并不影响html标签的解析与展示，只是对于内容进行实体化安全编码，并不会破坏原有的 HTML 结构。
2. 对于漏洞点来说，的确不容易触发，需要有管理员的权限。但是XSS漏洞存在即合理，仍然算一个安全隐患。

**Comment by LeoQuote** [comment]
个人认为这不算一个漏洞，该接口仅供管理员使用，并不是注册账号就可以拿到的权限。
原样输出给了管理员更大的自由，可以使用js 加载动态内容，综合来看这个功能是给管理员窃取用户信息制造了便利，但同时也方便管理员在不更改源代码的情况下提供更多功能，我觉得是有更多正向作用的功能。

**Comment by seven-yu** [comment]
从安全角度看，xss问题是客观存在的，这个不能因为功能使用范围小就忽视
代码上，有既满足功能又安全的方案：用 https://github.com/microcosm-cc/bluemonday 对输入做处理

问题提得很好，不认为这是在水洞，是一个 「能促进项目变得更好」的有效问题
