### ISSUE TITLE
使用文档中的docker 方法部署以后，任何人可以随意注册新的账户并且增加新的key。这个属于安全漏洞吗？

### ISSUE THREAD

**Issue by jiangying000** [songquanpeng/one-api#1734]

**Comment by QAbot-zh** [comment]
不属于。
1. 允不允许新用户注册，这是可以在设置里调整修改的
2. 新账号没有额度，即使创建了无限额度的key也调用不了

![image](https://github.com/user-attachments/assets/a955750d-b7b6-4634-9ef4-133ae170ef7c)

**Comment by jiangying000** [comment]
> 不属于。
> 
> 1. 允不允许新用户注册，这是可以在设置里调整修改的
> 
> 2. 新账号没有额度，即使创建了无限额度的key也调用不了
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/a955750d-b7b6-4634-9ef4-133ae170ef7c)
> 
> 

新的账户如果没有额度，那怎样才能给他额度呢？是要root用户操作才行嘛？

**Comment by QAbot-zh** [comment]
> > 不属于。
> > 
> > 1. 允不允许新用户注册，这是可以在设置里调整修改的
> > 2. 新账号没有额度，即使创建了无限额度的key也调用不了
> > 
> > ![image](https://private-user-images.githubusercontent.com/40236765/357035027-a955750d-b7b6-4634-9ef4-133ae170ef7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjI4OTEsIm5iZiI6MTcyMzUyMjU5MSwicGF0aCI6Ii80MDIzNjc2NS8zNTcwMzUwMjctYTk1NTc1MGQtYjdiNi00NjM0LTllZjQtMTMzYWUxNzBlZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA0MTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZTNkN2IyNTk0MzU1MjVkMDgxMmMyNjkxNGI4N2M3NzUzNzZmNjE3YTNkYzVmMTU2Njg3NTg1ZGM3N2ZmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UF886AUqe3DKTfPBt2gt3sbCzQh9Te1-cqv9W2gIi4)
> 
> 新的账户如果没有额度，那怎样才能给他额度呢？是要root用户操作才行嘛？

可以root提升用户额度，也可以通过兑换码形式发放额度

**Comment by jiangying000** [comment]
> > > 不属于。
> 
> > > 
> 
> > > 1. 允不允许新用户注册，这是可以在设置里调整修改的
> 
> > > 2. 新账号没有额度，即使创建了无限额度的key也调用不了
> 
> > > 
> 
> > > ![image](https://private-user-images.githubusercontent.com/40236765/357035027-a955750d-b7b6-4634-9ef4-133ae170ef7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjI4OTEsIm5iZiI6MTcyMzUyMjU5MSwicGF0aCI6Ii80MDIzNjc2NS8zNTcwMzUwMjctYTk1NTc1MGQtYjdiNi00NjM0LTllZjQtMTMzYWUxNzBlZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA0MTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZTNkN2IyNTk0MzU1MjVkMDgxMmMyNjkxNGI4N2M3NzUzNzZmNjE3YTNkYzVmMTU2Njg3NTg1ZGM3N2ZmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UF886AUqe3DKTfPBt2gt3sbCzQh9Te1-cqv9W2gIi4)
> 
> > 
> 
> > 新的账户如果没有额度，那怎样才能给他额度呢？是要root用户操作才行嘛？
> 
> 
> 
> 可以root提升用户额度，也可以通过兑换码形式发放额度

了解了，感谢
