### ISSUE TITLE
前端界面自适应问题

### ISSUE THREAD

**Issue by how1ewu** [songquanpeng/one-api#174]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
前端界面表单自动换行
**预期结果**
![image](https://github.com/songquanpeng/one-api/assets/98788152/73a88d75-4aca-49f8-a24d-74d71e3ec987)

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/98788152/1565eed6-1506-4a5e-aa07-70f4ea671cdc)

**Comment by songquanpeng** [comment]
已经推送，现在表格采用 small & compact 模式。
