### ISSUE TITLE
接入 智谱清言的api 失败

### ISSUE THREAD

**Issue by cmdhh** [songquanpeng/one-api#1751]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ✓ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ✓ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ✓ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ✓ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用智谱清言的api 加上key，点击测试，返回404，
但是我使用本地qwen模型 和 gpt3.5的中转api都能成功，下面有相关截图

**预期结果**
测试成功

**相关截图**
![捕获11](https://github.com/user-attachments/assets/90934f0f-98ab-4d7e-b8c0-f57d3bc7863f)

这是测试本地模型成功的截图
![捕获12](https://github.com/user-attachments/assets/1d60054b-88cf-4d4d-8495-194d683568d9)

**Comment by cmdhh** [comment]
![捕获11](https://github.com/user-attachments/assets/374c6879-3f54-4d2c-91ae-b8694a56f7a6)
我用apipost测试了，我智谱清言的api和key是没问题的

**Comment by QAbot-zh** [comment]
有智谱类型，怎么还用 openai 呢，它们的路径补全不一样

**Comment by cmdhh** [comment]
> 有智谱类型，怎么还用 openai 呢，它们的路径补全不一样
![Uploading 捕获11.PNG…]()
我之前也是用智谱类型，但是没成功，给我整不会了，我看见本地模型用openai没报错，我就试了试

**Comment by QAbot-zh** [comment]
那奇怪了，我这边很正常，连新出的glm-4-long都可以用

**Comment by cmdhh** [comment]
> 那奇怪了，我这边很正常，连新出的glm-4-long都可以用

主要是日志也没看见问题，寄了

**Comment by QAbot-zh** [comment]
选智谱渠道的时候，你接口地址空着了吗

**Comment by cmdhh** [comment]
> 选智谱渠道的时候，你接口地址空着了吗

这个代理吗，填了的
![捕获17](https://github.com/user-attachments/assets/8e318ec2-e1cc-442b-849f-c71a345e5056)

**Comment by QAbot-zh** [comment]
空着，别填它，要填也只填这部分：https://open.bigmodel.cn

**Comment by cmdhh** [comment]
> https://open.bigmodel.cn

6,可以了，谢谢。有没有二维码，给你发个红包

**Comment by QAbot-zh** [comment]
不客气，下次遇到别人不懂操作的时候也给别人提个醒就好啦 😘

**Comment by hongmin118** [comment]
nice~
