### ISSUE TITLE
请问这个程序的数据是本地安全的吗？

### ISSUE THREAD

**Issue by OreoProMax** [songquanpeng/one-api#1755]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
不好意思我不太了解，我想把这个项目部署在公用服务器上，但是只我自己使用。我也不会告诉其他人root密码之类的。那么其他人有可能从本地存储的数据中读出密码或者令牌等信息吗？

**Comment by QAbot-zh** [comment]
公用服务器？有点难哦，不管是docker还是环境变量，数据库的连接信息总是暴露的（对服务器所有者而言）

**Comment by OreoProMax** [comment]
> 公用服务器？有点难哦，不管是docker还是环境变量，数据库的连接信息总是暴露的（对服务器所有者而言）

好吧，看起来数据库连接信息似乎只能写到.env文件中读取，那肯定是不安全了

**Comment by ByteMelodist** [comment]
你是服务器安全的第一责任人 不要指望任何应用层的安全措施 管好自己的ssh key 及时更新系统和应用的安全补丁 怎么会泄露呢

**Comment by OreoProMax** [comment]
> 你是服务器安全的第一责任人 不要指望任何应用层的安全措施 管好自己的ssh key 及时更新系统和应用的安全补丁 怎么会泄露呢

不是哥，我问的就是把它布到其他人的服务器上安不安全，你给我来一句我是服务器安全的第一责任人，还让我管好自己的SSH密钥，直接给我整不会了😅下次能好好看看issue详情再回答吗
