### ISSUE TITLE
余额查询不正确

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#177]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
余额 查询显示4.88 刀
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。
![截图_20230619114626](https://github.com/songquanpeng/one-api/assets/19776350/f8b81647-029c-4821-a56e-ac9709885af9)
![截图_20230619113853](https://github.com/songquanpeng/one-api/assets/19776350/d4e984d5-a58d-4545-b610-ad06e0b24bbd)

**Comment by songquanpeng** [comment]
我听说是 API 限制 7 天内的查询，忘记来源了。

**Comment by songquanpeng** [comment]
经群友测试，现在已经没问题了。
