### ISSUE TITLE
支持在令牌维度设置允许的模型

### ISSUE THREAD

**Issue by songquanpeng** [songquanpeng/one-api#178]
这将有助于用户为令牌设置细粒度的限制。

**Comment by mrhaoji** [comment]
+1 实用的功能

**Comment by lipanpan-hub** [comment]
+1 这功能很有必要

**Comment by tisfeng** [comment]
期待这个功能 😶

**Comment by songquanpeng** [comment]
已经支持

**Comment by popdo** [comment]
在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。

**Comment by Caixiaopig** [comment]
> 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。

你部署两套也可以解决，一套内网一套外网

**Comment by popdo** [comment]
> > 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。
> 
> 你部署两套也可以解决，一套内网一套外网

我的用户是企业，企业不一定是在内网使用，公司服务器中搭建的chat项目或者公司内网中运行的Ai项目

**Comment by Caixiaopig** [comment]
> > > 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。
> > 
> > 
> > 你部署两套也可以解决，一套内网一套外网
> 
> 我的用户是企业，企业不一定是在内网使用，公司服务器中搭建的chat项目或者公司内网中运行的Ai项目

可以寻求公司IT的帮助，在网络策略上做一些限制。

**Comment by mrhaoji** [comment]
> 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。

这个需求在下游是企业客户时是高概率存在的，令牌分配给某个项目之后，不排除被有心之人拿去私下使用，除了帮忙捞运行日志还不太好排查。

**Comment by popdo** [comment]
> > > > 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。
> > > 
> > > 
> > > 你部署两套也可以解决，一套内网一套外网
> > 
> > 
> > 我的用户是企业，企业不一定是在内网使用，公司服务器中搭建的chat项目或者公司内网中运行的Ai项目
> 
> 可以寻求公司IT的帮助，在网络策略上做一些限制。

下游企业key分发给员工，员工有了key可以在任何地方使用。企业限制网络策略没有意义。除非企业自己再搭建一套oneapi自己在再做限制，但很多企业并没有懂技术的人员。限制key的ip可以最直接的限制员工滥用额度。

**Comment by popdo** [comment]
> > 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。
> 
> 这个需求在下游是企业客户时是高概率存在的，令牌分配给某个项目之后，不排除被有心之人拿去私下使用，除了帮忙捞运行日志还不太好排查。

是的，目前碰到好几个都是有这种需求的。

**Comment by songquanpeng** [comment]
berry主题还没更新此功能

**Comment by songquanpeng** [comment]
> 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。

已经支持了，现在可以设置单个网段限制了

**Comment by popdo** [comment]
> > 在令牌维度什么时候能支持IP、ip段限制。很多企业给员工分发了key，只希望员工在公司可以使用。
> 
> 已经支持了，现在可以设置单个网段限制了

感谢大佬，我本地测试添加编辑令牌填写ip网段一直无法通过验证

```go
func IsValidSubnet(subnet string) error {
	_, _, err := net.ParseCIDR(subnet)
	return fmt.Errorf("failed to parse subnet: %w", err)
}
```

貌似原因是这里的验证始终返回的是错误。

另外是否可以支持填写多个ip或网段，逗号分割。

**Comment by songquanpeng** [comment]
我已经修复了，你更新

**Comment by songquanpeng** [comment]
v0.6.5-alpha.11，你说的多个网段的支持也已经支持了

**Comment by tisfeng** [comment]
你好，请问具体如何设置令牌支持的模型？没看到文档介绍，在令牌管理页面，也没相关的设置界面 🤔

<img width="594" alt="image" src="https://github.com/songquanpeng/one-api/assets/25194972/33212ad7-03d8-47f5-954c-d7684d767518">

**Comment by tisfeng** [comment]
哦，没问题了，原来是 air 主题没有更新 🥲

<img width="1193" alt="image" src="https://github.com/songquanpeng/one-api/assets/25194972/9247edde-a904-48f7-9223-b95d7c66d221">
