### ISSUE TITLE
考虑分开计算提示和补全的额度消耗

### ISSUE THREAD

**Issue by syx0310** [songquanpeng/one-api#179]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
目前部分模型的的input与output的价格不同  
例如GPT-4

Model | Input | Output
-- | -- | --
8K context | $0.03 / 1K tokens | $0.06 / 1K tokens
32K context | $0.06 / 1K tokens | $0.12 / 1K tokens

因此是否可以考虑增加分开计算input与output的功能
**应用场景**
更加精准地压低价格/控制成本

**Comment by songquanpeng** [comment]
有考虑到这一点，不过倍率是硬编码的。

**Comment by songquanpeng** [comment]
那个地方都是提示的倍率，补全倍率是硬编码在代码里的。

**Comment by songquanpeng** [comment]
先关了哈，如果有问题再开

**Comment by ceeim** [comment]
> 那个地方都是提示的倍率，补全倍率是硬编码在代码里的。

咨询一下现在 output 的倍率是如何计算？默认的倍率设置应该是 input 倍率，output 是按官方价格计算吗？如果可以分开设置是挺好的，想可以知道 input 消耗多少，output 消耗多少。就像这样：
![image](https://github.com/songquanpeng/one-api/assets/18570103/961cddda-b7a0-4051-b6c6-a313cc3e089e)
