### ISSUE TITLE
登录过期后账号显示还是未注销状态，容易让人迷惑

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#18]
![image](https://user-images.githubusercontent.com/75829171/234454769-2a009550-be22-410d-9a7d-2ed23e094136.png)
建议过期后访问直接跳转登陆界面
![image](https://user-images.githubusercontent.com/75829171/234454956-fa85f37d-a9fc-4172-8dd4-d2a0dd84b08c.png)

**Comment by songquanpeng** [comment]
Okay，这个好搞

**Comment by songquanpeng** [comment]
已解决。

**Comment by songquanpeng** [comment]
已解决。

**Comment by JeazW** [comment]
👌多谢~
