### ISSUE TITLE
gpt-4o-mini使用日志计费不正确

### ISSUE THREAD

**Issue by miracletiger** [songquanpeng/one-api#1800]
**问题描述**
gpt-4o-mini的日志中详情模型倍率好像不对
消费 | gpt-4o-mini | 1251 | 102 | $0.093420 | 模型倍率 30.00，分组倍率 1.00，补全倍率 3.00
-- | -- | -- | -- | -- | --
消费 | gpt-4o-mini | 1251 | 102 | $0.093420 | 模型倍率 30.00，分组倍率 1.00，补全倍率 3.00
-- | -- | -- | -- | -- | --

设置里倍率看着设置过了
  "gpt-4-turbo-preview": 5,
  "gpt-4-vision-preview": 5,
  "gpt-4o": 2.5,
  "gpt-4o-2024-05-13": 2.5,
  "gpt-4o-mini": 0.075,
  "gpt-4o-mini-2024-07-18": 0.075,
  "hunyuan": 7.143,
  "llama2-70b-4096": 0.32,
实际应该没这么高

**相关截图**
![image](https://github.com/user-attachments/assets/5578d979-d99c-402d-928a-71bdd1d43f6e)

**Comment by QAbot-zh** [comment]
你的模型倍率设置没生效啊，保存、重启试试

![image](https://github.com/user-attachments/assets/62797d02-dadb-49c3-a27b-c5cfb1b9f365)

**Comment by miracletiger** [comment]
我更新了下可以了
