### ISSUE TITLE
如何绑定[令牌]和[渠道]，以实现客户端相同模型，实际映射成不同模型

### ISSUE THREAD

**Issue by Cool-PKY** [songquanpeng/one-api#1828]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述*

不同客户端，输入**同一模型**，不同令牌，命中与令牌绑定的指定渠道，**实际映射到不同模型**。

**应用场景**

> 客户端1模型处只能填入[gpt-3.5]，简单应用，需要映射使用[qwen-plus]模型
> 客户端2模型处也只能填入[gpt-3.5]，复杂应用，需要映射使用[qwen-max]模型

one api 配置
【令牌1】->【渠道1】{“gpt3.5”; "qwen-plus"}
【令牌2】->【渠道2】{“gpt3.5”; "qwen-max"}

客户端1填写令牌1，gpt3.5，映射到qwen-plus
客户端2填写令牌2，gpt3.5，映射到qwen-max

**Comment by QAbot-zh** [comment]
【令牌-渠道id】

**Comment by Cool-PKY** [comment]
> 【令牌-渠道id】

嗯，看到其他issue里面提到过了。 “**管理员**用户可以用  【令牌key-渠道id] ， 实现令牌和渠道的绑定"。 这里已经可以实现我的诉求了。
好奇问一嘴，那普通用户呢？

**Comment by QAbot-zh** [comment]
普通用户没有渠道可以选啊，渠道本身也是管理员可见的内容
