### ISSUE TITLE
能不能补充接口加密，防止被人直接打掉

### ISSUE THREAD

**Issue by cbangchen** [songquanpeng/one-api#183]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**

能不能补充接口加密，防止被人直接打掉

**应用场景**

接口安全

**Comment by songquanpeng** [comment]
什么接口加密？

**Comment by cbangchen** [comment]
密钥对 https://cloud.tencent.com/document/product/628/11819 类似这种

**Comment by cbangchen** [comment]
就是URL签名

**Comment by songquanpeng** [comment]
官方接口没有这个吧？要保持一致的。

**Comment by songquanpeng** [comment]
抓包为什么能拿到密钥？如果你没启用 HTTPS 的话，加了这个一样有问题。

问题不成立哈。

**Comment by cbangchen** [comment]
one-api是中间一层，只需要保持接口参数基本一致，或许可以考虑可选的加密方式。

**Comment by songquanpeng** [comment]
启用 HTTPS 后是无法被中间人拿到密钥的。

**Comment by cbangchen** [comment]
我理解https不做双端校验的话，也是不防中间人的。

**Comment by songquanpeng** [comment]
我不理解的是，中间人没有服务器上的 SSL 证书要如何冒充服务器。

**Comment by songquanpeng** [comment]
目前绝大部分的 API 都没有启用这东西吧。

**Comment by cbangchen** [comment]
这里没有说冒充服务器的，主要是担心服务器被攻击。因为https单向校验只客户端校验服务端ssl证书，而服务端不校验客户端证书，因为是单向所以没有。攻击的时候可以以客户端的角色去攻击服务器。这个时候服务器是没有太多防护的。就是一个普通请求的端口而已。

**Comment by cbangchen** [comment]
ddos是另外的攻击手段了。那种的话应该说要用防火墙来处理，这里没有讨论ddos的。

**Comment by songquanpeng** [comment]
那是在担心爆破密钥？

**Comment by cbangchen** [comment]
假如用ddos的话，我理解是达到一定的阈值才会被认定为攻击的。这对于大部分的接口都是没有什么问题，被打再处理就行，不过因为openai的请求一般资费稍微贵一点，所以才有这个请求。

如果重放攻击，或者模拟请求攻击的话，其实不需要太多请求量就可以把资费打满了。

类似腾讯云的网关校验都会做参数加密，其实就是把请求加密，让攻击者无法简单的复现请求来攻击服务器。如果是ddos即便请求失败也是可以打，只是消耗服务器性能和流量。而我这里主要是指的让不是来自开发者的请求本身就会失败掉。会安全点。

只是一个建议而已。先讨论到这里。感谢您的时间。

**Comment by cbangchen** [comment]
加上时间戳的思路是正确的，不过参数如果裸露不免会被修改。需要有加密，攻击者才无法简单修改参数。

补充时间戳参数应该在加密之前，这个目的是为了防止重放请求攻击。简单来说是加密为了防止参数被修改，而时间戳防止重放。配合使用才能最终解决问题。

**Comment by songquanpeng** [comment]
为什么参数会被修改呢？配合 HTTPS 不是可以防止篡改？

**Comment by cbangchen** [comment]
很抱歉，刚刚看到消息。

是的，https可以做的是通信过程中的安全，也就是传输过程中的对称加密，密钥安全的话，请求就无法被修改。不过这里说的是攻击者可以伪装成正常的请求端口，从一开始就模拟与服务器进行链接，对服务端进行请求。

https如果没有做双向校验且没有做加密的话，是和http区别不大的。这个是我的一个个人理解。

**Comment by songquanpeng** [comment]
我的理解是在请求体里加入明文时间戳配合 HTTPS 是可以避免请求重发攻击的。

**Comment by cbangchen** [comment]
想请问下，如果攻击者试图用类似postman的方式和oneapi建立连接，可以成功建立吗。

**Comment by songquanpeng** [comment]
当然可以，目前只通过 token 来鉴权。

**Comment by cbangchen** [comment]
那么这时候，加上时间戳的参数，我想也是可以的。再写个脚本，每秒执行请求100次，就已经是一个基本的攻击了。

**Comment by songquanpeng** [comment]
之后会加速率限制。

Token 不会被拿到，他只能通过重发来重发整个请求，服务端校验时间戳，丢弃与当前时间偏差过大的。

**Comment by cbangchen** [comment]
为什么认为token不会被拿到呢

**Comment by songquanpeng** [comment]
因为有 HTTPS

**Comment by cbangchen** [comment]
http不做双向校验，还是可以拿到参数的呀。

**Comment by songquanpeng** [comment]
如果客户端做了服务端的校验，在请求时会用服务端的公钥进行加密，在对应的私钥没有泄露的情况下，攻击者无法解密请求体。

**Comment by cbangchen** [comment]
您这里说的客户端校验服务端，不过我前面一直想说的是，客户端就是攻击者的端口设备。这种情况下，服务器不设防，依赖攻击者自己来做这种安全性校验，想必效果比较不理想。

**Comment by songquanpeng** [comment]
恶意的客户端所使用的 key 必须是有效的，请求会消耗对应的额度。

**Comment by cbangchen** [comment]
可以理解您的意思，就是说正常的客户端，校验服务端证书，保证不被中间人。然后token不外泄的话，模拟请求就没有基础了。还有一个小小的问题，想请教下，客户端对于服务端的一个校验问题，因为说现在默认的校验就是对于ca机构的校验，本身是没有涉及证书的内容校验的，而一旦对证书内容做校验，也就意味着服务端一旦更换证书变得困难。

**Comment by cbangchen** [comment]
这个怎么处理呢

**Comment by songquanpeng** [comment]
不会的，根证书不会轻易改变，服务端变更证书客户端可以根据信任链检验服务端的身份信息。

**Comment by cbangchen** [comment]
好的明白了。如果说根证书不轻易改变，这个结论是可以理解的。感谢👍

**Comment by songquanpeng** [comment]
是的，根证书一般在操作系统中内置。

**Comment by songquanpeng** [comment]
那么这个 issue 就先关闭了。
