### ISSUE TITLE
返回大量数据的时候有超时问题：日志显示扣费但是请求是返回的超时

### ISSUE THREAD

**Issue by Ikaros-521** [songquanpeng/one-api#184]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
请求问题数据量大，需要返回大量数据的时候有超时问题，日志显示扣费了，请求是返回的超时
**应用场景**
返回大数据量情况

**Comment by songquanpeng** [comment]
应该选 bug 模板。

**Comment by Ikaros-521** [comment]
www   叫bug多难听
![GCK}BDF QT9MRB97K_ Y{EL](https://github.com/songquanpeng/one-api/assets/40910637/74961056-287a-4e0b-a6b3-f2f2c8964cfe)

**Comment by songquanpeng** [comment]
返回体是什么样的？

**Comment by Ikaros-521** [comment]
> 返回体是什么样的？

同事测的，没法复现了，难绷

**Comment by songquanpeng** [comment]
日志显示扣费说明 One API 已经处理完请求了，而且 One API 没有设置超时时间。

所以应该检查 Nginx 之类的网关有没有设置超时时间。

如果问题依旧存在，欢迎重开 issue。
