### ISSUE TITLE
k8s多个pod部署，似乎存在session的问题

### ISSUE THREAD

**Issue by zzy5066** [songquanpeng/one-api#1848]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
多个pod部署的情况下，已按多服务器部署的规则，设置了ENV，如下：
        - name: node_type
          value: master
        - name: SESSION_SECRET
          value: random_string
但是，前端url登录后，访问就会出现类似下面的问题【单pod不存在这个问题】:
<img width="972" alt="image" src="https://github.com/user-attachments/assets/976fd909-8e9d-4d79-9371-1f7e8801c933">

**复现步骤**
多个pod的情况下，在UI点击几下必现

**预期结果**
多pod也可以正常使用

**相关截图**
如果没有的话，请删除此节。

**Comment by zzy5066** [comment]
跟进了下pod的logs，当出现此错误的时候，控制台报错是:  [sessions] ERROR! securecookie: the value is not valid

**Comment by zzy5066** [comment]
感谢大神帮忙，此问题已解决，同时附带ENV的设置，帮助其他人：
        env:
        - name: SQL_DSN
          valueFrom:
            secretKeyRef:
              key: database_url
              name: oneapi-db-mysqlconn-sercret
        - name: TZ
          value: "Asia/Shanghai"
        - name: node_type
          value: 'master'
        - name: SESSION_SECRET
          value: 'c2VjcmV0LWtleQ=='
        - name: GLOBAL_WEB_RATE_LIMIT
          value: '6000'
        - name: GLOBAL_API_RATE_LIMIT
          value: '6000'
        - name: FRONTEND_BASE_URL
          value: 'https://xxxxxxx.com'

**Comment by c121914yu** [comment]
解决的话，麻烦自行 close 下哈，作者看到这么多 issue 点进去会头大哈哈。

**Comment by zzy5066** [comment]
已解决
