### ISSUE TITLE
支持单独查询创建的令牌余额

### ISSUE THREAD

**Issue by zhaogeblog** [songquanpeng/one-api#186]
**例行检查**
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
目前在第三方查询余额网站，查询新创建的令牌，会显示总账号的额度。
是否可以在后台增加设置，支持查询单个令牌的余额。

**应用场景**
更方便用户查询统计额度

**Comment by songquanpeng** [comment]
之后加一个选项可以切换，到底 API 返回令牌额度还是用户额度。

**Comment by songquanpeng** [comment]
已实现。

**Comment by maple-zhou** [comment]
你好，请问是如何实现通过令牌查询令牌额度的？提到的 “第三方查询余额网站” 是指什么？谢谢！
