### ISSUE TITLE
fastgpt调用ollama的qwen2.5:3b提示失败，oneapi测试正常，工作流调试也正常

### ISSUE THREAD

**Issue by yixiuquan** [songquanpeng/one-api#1879]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
FastGpt V4.8.11，oneapi 0.6.8。ubuntu docker 安装的ollama，ollama运行的qwen2.5:3b。
fastgpt调用ollama的qwen2.5:3b提示失败，而oneapi测试正常，工作流调试也正常
**复现步骤**
1、oneapi中添加qwen2.5:3b的渠道
2、fastgpt中config.local.json中增加qwen2.5:3b的模型配置
3、创建应用、工作流并使用qwen2.5:3b
4、应用测试聊天报错LLM model response empty
5、工作流调试一步步走，可以正常走通
**预期结果**
都应该调用走通
**相关截图**
![553a21f4881d7a981f04e58c138aed0](https://github.com/user-attachments/assets/252579f8-5247-4c19-affd-3de4df2cc79d)
![d56f7e2fec9fd689d13f916de2d4495](https://github.com/user-attachments/assets/d096dc55-9797-4ef3-84bf-fc56e8fc2d81)
![image](https://github.com/user-attachments/assets/5022fac6-ca33-45d9-a96c-9ac700eea838)
![image](https://github.com/user-attachments/assets/950f36b9-1517-4a0d-a496-7bf193b8a47f)
![image](https://github.com/user-attachments/assets/80d7af12-d8fa-434b-81ff-f727b4510706)
fastgpt调用ollama报错后台日志：
![image](https://github.com/user-attachments/assets/b48fc8d6-31aa-4f26-a3d4-1b707b196ee5)
go工作流调用成功fastgpt后台日志：
![image](https://github.com/user-attachments/assets/42a3af7a-d122-4352-8753-29c5df9bf2cb)

**Comment by yixiuquan** [comment]
oneapi日志：调用qwen2.5失败:
![image](https://github.com/user-attachments/assets/4d993359-66cb-4b00-824d-a50bd709c376)
工作流调用成功：
![image](https://github.com/user-attachments/assets/07b960f3-f149-4d5a-8f42-97bdbb2bdd12)
![image](https://github.com/user-attachments/assets/4bdb825e-29d4-4a8c-870b-475c8bcc0415)

**Comment by yixiuquan** [comment]
尴尬  提错位置了

**Comment by ViKingQ** [comment]
解决了吗？我要遇到同样的问题
