### ISSUE TITLE
[openai] Error: 'NoneType' object has no attribute 'content'

### ISSUE THREAD

**Issue by dq7532183** [songquanpeng/one-api#1884]
oneapi从0.6.7升级到v0.6.9-alpha.2,报错了
dify使用oneapi作为代理
data: {"event": "error", "conversation_id": "86cdf666-8b91-4eff-a03d-3373ee5f49ef", "message_id": "40a6d00e-20a7-41d7-b0d3-2bb400514bb4", "created_at": 1729499511, "code": "completion_request_error", "status": 400, "message": "[openai] Error: 'NoneType' object has no attribute 'content'"}

**Comment by dq7532183** [comment]
> oneapi从0.6.7升级到v0.6.9-alpha.2,报错了 dify使用oneapi作为代理 data: {"event": "error", "conversation_id": "86cdf666-8b91-4eff-a03d-3373ee5f49ef", "message_id": "40a6d00e-20a7-41d7-b0d3-2bb400514bb4", "created_at": 1729499511, "code": "completion_request_error", "status": 400, "message": "[openai] Error: 'NoneType' object has no attribute 'content'"}

**Comment by ykangw** [comment]
在Dify遇到了相同的问题。请问是怎么解决的？
