### ISSUE TITLE
关于使用问题

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#19]
我手动部署了成功之后，我用post工具来调用接口会出现错误
POST：ip:3000
![image](https://user-images.githubusercontent.com/52068443/234467659-2182fcd5-11e5-40b1-ba20-74401a9105c5.png)

**Comment by lmuiotctf** [comment]
![image](https://user-images.githubusercontent.com/52068443/234467755-29a783e8-0d51-4588-a07c-87cd1fece424.png)

**Comment by songquanpeng** [comment]
URL路径正确吗？



---Original---
From: ***@***.***&gt;
Sent at: 2023年4月26日(Wed) Noon12:09
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 关于使用问题 (Issue #19)




 
我手动部署了成功之后，我用post工具来调用接口会出现错误
 POST：ip:3000

**Comment by lmuiotctf** [comment]
URL如下图
![image](https://user-images.githubusercontent.com/52068443/234467964-ef1756c8-1f6c-41e5-aa6d-41f13db01229.png)

**Comment by conversun** [comment]
看正确的:
![nMdNPN](https://img.trackcloud.top/uPic/nMdNPN.png)

**Comment by lmuiotctf** [comment]
![image](https://user-images.githubusercontent.com/52068443/234468259-55bc2d6d-774c-4123-a80a-8c577d0ff7b7.png)
okk和openai一致，但是hui会出现这样的error

**Comment by songquanpeng** [comment]
token错了，你应该点击复制复制token，你填入的那个是token的名字



---Original---
From: ***@***.***&gt;
Sent at: 2023年4月26日(Wed) Noon12:14
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 关于使用问题 (Issue #19)




 

 okk和openai一致，但是hui会出现这样的error

**Comment by songquanpeng** [comment]
#13 一样的情况。
