### ISSUE TITLE
使用anthropic pythonsdk请求返回404

### ISSUE THREAD

**Issue by jlu3389** [songquanpeng/one-api#1900]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
测试claude-3-5-sonnet-20241022时没有问题，但使用anthropic的pythonsdk 请求确是404
nthropic.NotFoundError: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/messages)', 'type': 'invalid_request_error', 'param': '', 'code': ''}}

**复现步骤**
import anthropic
response = client.messages.create
请求。
**预期结果**
200,
**相关截图**
![image](https://github.com/user-attachments/assets/7fd3c4f9-97df-49f1-9bba-f63e7beba607)

已确认请求模型没有拼写错误。

非常感谢。

**Comment by QAbot-zh** [comment]
经过 oneapi 中转出去都是 OpenAI 格式调用

**Comment by jlu3389** [comment]
> 经过 oneapi 中转出去都是 OpenAI 格式调用

你好。所以你的意思是，我应该使用openai的sdk来请求？

**Comment by QAbot-zh** [comment]
> > 经过 oneapi 中转出去都是 OpenAI 格式调用
> 
> 你好。所以你的意思是，我应该使用openai的sdk来请求？

对的，只需要更换对应的 model ，就可以请求任意 oneapi 转发后的模型，all in one

**Comment by chenzikun** [comment]
有很多第三方工具使用的是客户端是指定的，并不能随意更改，希望支持使用原生地址的方式去访问大模型

**Comment by jlu3389** [comment]
> > > 经过 oneapi 中转出去都是 OpenAI 格式调用
> > 
> > 
> > 你好。所以你的意思是，我应该使用openai的sdk来请求？
> 
> 对的，只需要更换对应的 model ，就可以请求任意 oneapi 转发后的模型，all in one

收到，非常感谢。
