### ISSUE TITLE
Coze文件支持

### ISSUE THREAD

**Issue by marvinli001** [songquanpeng/one-api#1913]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
Coze渠道希望能支持Filebox文件传入的api功能，文件通过coze api上传到coze file 内
**应用场景**
对coze模型也支持从one api请求并且传入文件

**Comment by A1KESH1** [comment]
已经支持文件了吗？

**Comment by AuditAIH** [comment]
@marvinli001 你好 请问这个支持了吗，可以在coze里面上传文件给大模型分析吗？如果能提供解答方案或coze的API ，将不胜感激 谢谢
