### ISSUE TITLE
请求chatgpt-4o-latest模型报无可用渠道

### ISSUE THREAD

**Issue by Alcatraz-Zhang** [songquanpeng/one-api#1918]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用v0.6.8默认主题，且在exe和docker平台上都存在相同问题。在请求chatgpt-4o-latest模型时报无可用渠道错误
**复现步骤**
在v0.6.8，exe版本，创建只有一个chatgpt-4o-latest模型的OPENAI渠道，使用chatgpt-4o-latest测试该渠道，报“无可用渠道”错误
**预期结果**
报“无可用渠道”错误
**相关截图**
![Snipaste_2024-11-08_17-31-08](https://github.com/user-attachments/assets/beec420d-e84f-43e9-bf41-e861de93b20e)
![Snipaste_2024-11-08_17-32-48](https://github.com/user-attachments/assets/32499af7-9dff-481e-b068-c70f9f8e4152)

**Comment by xyfacai** [comment]
检查你渠道配置里的模型前后是否有看不见的空格、换行

**Comment by Alcatraz-Zhang** [comment]
> 检查你渠道配置里的模型前后是否有看不见的空格、换行

检查过了没有，而且我是从测试模型下拉框里选的模型，理论上和渠道配置里面是一样的
