### ISSUE TITLE
希望能支持添加one-api的接口和余额

### ISSUE THREAD

**Issue by woodchen-ink** [songquanpeng/one-api#192]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
![image](https://github.com/songquanpeng/one-api/assets/95951386/8bf551bd-0d02-4aab-9766-119eba2823fe)
有客户问我，他们自己搭建使用我们的代理可不可以
**应用场景**
类似于分销

**Comment by songquanpeng** [comment]
不懂，分销让他们直接搭建一套 One API 代理你的不可以吗？

**Comment by woodchen-ink** [comment]
> 不懂，分销让他们直接搭建一套 One API 代理你的不可以吗？

是的，就是代理我的，但是以OPENAI的方式添加渠道，不支持余额查询

**Comment by songquanpeng** [comment]
支持哦：
![image](https://github.com/songquanpeng/one-api/assets/39998050/0c0d4cc4-c2d0-4832-8cfb-df02f5da6d92)
