### ISSUE TITLE
新建渠道加一个预设提示功能

### ISSUE THREAD

**Issue by pptomtiger** [songquanpeng/one-api#1920]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
在新建渠道的时候，加一个预设系统提示词功能
**应用场景**
每个独立的渠道，自定义定向模型，适应不同的业务场景，不同的业务场景需要不同的预设系统提示词，这样返回的内容就是相关提示词的要求内容。当然预设系统提示可以默认空白。

**Comment by songquanpeng** [comment]
![d27d495e0fa9eb42bd784d6dda8f510d](https://github.com/user-attachments/assets/3ad39a39-a88c-444b-907b-0b6b360d7e39)

**Comment by ArcaneWhispers** [comment]
提示词这个功能是前端的事情，渠道中就不应该存在这个功能。有心之人会利用这个功能做假模型骗钱，现在已经有部分中转站利用提示词假冒cluade模型。
