### ISSUE TITLE
v0.6.10-alpha.6 编辑已有渠道或创建渠道报错

### ISSUE THREAD

**Issue by huangyafei** [songquanpeng/one-api#1928]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [ x ] 我已确认我已升级到最新版本
+ [ x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

docker 部署，使用 SQLite 数据库。

升级到 v0.6.10-alpha.6 后：

1. 编辑已有渠道，在底部点击「提交」，报错：UNIQUE constraint failed: abilities.group, abilities.model, abilities.channel_id
2. 新增渠道，在底部点击「提交」，报错：UNIQUE constraint failed: abilities.group, abilities.model, abilities.channel_id

报错后，刷新页面，能看到编辑或新增的内容已经保存了，并且在渠道列表页测试正常。但无法通过 API 调用模型。

**Comment by ZhangTianrong** [comment]
我也遇到了同样的问题，而且并不止是出现在 `v0.6.10-alpha6`, 回退到 `v0.6.10-alpha5` 仍然有次问题。检查日志后发现是默认模型列表中存在重复，导致无法添加，例如对于 Claude 渠道，默认模型如下：
![image](https://github.com/user-attachments/assets/ab34ef84-1e5b-490d-bcb8-cd17d17e7f65)
其中 `claude-3-5-haiku-20241022` 出现了两次，删除后即可添加渠道。
