### ISSUE TITLE
错误响应问题

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#193]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在请求 oneAPI 时，错误响应码均为200，这和 openai 的接口不一致。在 node stream 中，捕获这个错误比较麻烦，不知道是否有意向增加状态码错误响应。

**复现步骤**
使用 openai node sdk， stream 请求时，凭证错误，无法被 catch 捕获。需要进入手动解析 chunk 后才能获取到 error。

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
Okay，如果可以的话，可以告诉我 OpenAI 的对应不同错误的对应响应码是什么样的，我会很乐意保证与官方 API 的一致性。

**Comment by c121914yu** [comment]
> Okay，如果可以的话，可以告诉我 OpenAI 的对应不同错误的对应响应码是什么样的，我会很乐意保证与官方 API 的一致性。

常见的就是 401 与403，其他状态码印象中都是个通用的 500，然后加上对应的 error message 。
具体的错误码我觉得不是很关键，关键是非 200 响应。让请求进入 catch 阶段，而不是继续正常执行下去。

**Comment by songquanpeng** [comment]
Okay

**Comment by songquanpeng** [comment]
已经修复，已经推送了新版本。

**Comment by c121914yu** [comment]
大佬，申请了 qq 群，通过下。 改天聊点项目问题，我已经推荐自己的项目 [FastGpt](https://github.com/c121914yu/FastGPT) 去使用 oneapi 管理 key，不需要再自己造一便轮子。

**Comment by songquanpeng** [comment]
没看到哦，你备注了吗？15级以上都是自动通过的。

**Comment by songquanpeng** [comment]
项目互加友链搞不？
