### ISSUE TITLE
请问会新增支持推特的Grok的api吗

### ISSUE THREAD

**Issue by JamesRay0713** [songquanpeng/one-api#1939]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by jamesljl** [comment]
Grok-2 可以使用自定义渠道，因为 它是全兼容 OpenAI 的接口的。 BaseUrl 填 https://api.x.ai

**Comment by Deyong888** [comment]
自定义渠道，BaseUrl 填 https://api.x.ai/没有用，错误：http status code: 403

**Comment by valleyUp** [comment]
> 自定义渠道，BaseUrl 填 [https://api.x.ai/没有用，错误：http](https://api.x.ai/%E6%B2%A1%E6%9C%89%E7%94%A8%EF%BC%8C%E9%94%99%E8%AF%AF%EF%BC%9Ahttp) status code: 403

我是直接用了openai的接口baseurl换成那个https://api.x.ai

**Comment by Jamesun921** [comment]
用自定义和openai渠道，都实验过了，实际在cline调用api的时候都是403错误 403 Provider API error: bad response status code 403 (

**Comment by Jamesun921** [comment]
另外：直接在cline调用grok，要使用openai兼容，url是 https://api.x.ai/v1，可以正常使用

**Comment by poplar-young** [comment]
同样，用自定义和openai渠道，都实验过了，grok报403错误

**Comment by kitaev-chen** [comment]
xAI支持出错，默认去找全局key或者啥了，总之调用就是“503: 当前分组 default 下对于模型 grok-2 无可用渠道”。渠道测试倒是没问题。
