### ISSUE TITLE
apikey存在泄露风险

### ISSUE THREAD

**Issue by vzep** [songquanpeng/one-api#1943]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [ x ] 我已确认我已升级到最新版本
+ [ x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

apikey存在泄露风险，请查看源码，查询余额都是采用第三方代理请求，apikey可能会被记录。

[controller/channel-billing.go](https://github.com/songquanpeng/one-api/blob/main/controller/channel-billing.go#L196C10-L196C65)

https://github.com/songquanpeng/one-api/blob/6ab87f8a08e2c0502691daafabb7076661b05de7/controller/channel-billing.go#L176

https://github.com/songquanpeng/one-api/blob/6ab87f8a08e2c0502691daafabb7076661b05de7/controller/channel-billing.go#L196

[relay/channeltype/url.go](https://github.com/songquanpeng/one-api/blob/main/relay/channeltype/url.go#L6)

https://github.com/songquanpeng/one-api/blob/6ab87f8a08e2c0502691daafabb7076661b05de7/relay/channeltype/url.go#L6

还有很多就不一一描述

**复现步骤**

**预期结果**

**Comment by liangyuanpeng** [comment]
感谢信息，刚开始看oneAPI,这个信息很重要但README.md似乎没有声明

**Comment by QAbot-zh** [comment]
你理解错了，那是渠道类型对应的查询接口，你不用那个类型就不会调用到

![image](https://github.com/user-attachments/assets/4ecc7457-42e8-41e2-b9a6-7e7d047132ef)

**Comment by vzep** [comment]
> 你理解错了，那是渠道类型对应的查询接口，你不用那个类型就不会调用到
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/389362224-4ecc7457-42e8-41e2-b9a6-7e7d047132ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mjg4MTgsIm5iZiI6MTczMjUyODUxOCwicGF0aCI6Ii80MDIzNjc2NS8zODkzNjIyMjQtNGVjYzc0NTctNDJlOC00MWUyLWI5YTYtN2U3ZDA0NzEzMmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5NTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWEyOGQ4OTZmMzFmOGEzMDA3OTA1MzlmMTZlMGJlNzJhYjJmMTVlZGI2MDRiZDU2M2FjZjliOWMxZjdkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4LPD7GGI_5DIyc94lqoaGUJPgMLOkYtnio12_uIQI7Y)

大概看了一下是渠道代理，我觉得[CHANNEL_OPTIONS ](https://github.com/songquanpeng/one-api/blob/main/relay/channeltype/url.go)数据结构为
`{ key: 1, text: 'OpenAI', value: 1, color: 'green', url: 'https://api.openai.com' }`
更合理，直观展示方便其他人立刻理解，没必要抽象出来单独放到一个[url.go文件](https://github.com/songquanpeng/one-api/blob/main/relay/channeltype/url.go)
具体代码运行逻辑没细看，可能存在渠道请求接口切换为proxy接口操作，待核实。

**Comment by QAbot-zh** [comment]
那不是接口 proxy，只是提供 api 的供应商罢了（类似于 openrouter 之类的），逻辑自己看，这部分代码没有所谓泄露问题
