### ISSUE TITLE
使用dockerfile进行构建镜像遇到No such file or directory报错

### ISSUE THREAD

**Issue by 121818** [songquanpeng/one-api#1964]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
执行RUN go build -trimpath -ldflags "-s -w -X 'github.com/songquanpeng/one-api/common.Version=$(cat VERSION)' -extldflags '-static'" -o one-api 步骤报No such file or directory，直接打开github.com/songquanpeng/one-api/common.Version访问也是Not Found

**相关截图**
![image](https://github.com/user-attachments/assets/1e383b49-acac-47bf-9ac1-b412608ebed6)

**Comment by EmilyLiu03** [comment]
我在执行Dockerfile时也遇到了同样的输出，请问是如何解决呢？

<img width="870" alt="Image" src="https://github.com/user-attachments/assets/900773ad-d768-47b8-ae96-3ce7211487dd" />

**Comment by EmilyLiu03** [comment]
> 我在执行Dockerfile时也遇到了同样的输出，请问是如何解决呢？
> 
> <img alt="Image" width="870" src="https://private-user-images.githubusercontent.com/188282538/405091877-900773ad-d768-47b8-ae96-3ce7211487dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NDQwMDUsIm5iZiI6MTczNzQ0MzcwNSwicGF0aCI6Ii8xODgyODI1MzgvNDA1MDkxODc3LTkwMDc3M2FkLWQ3NjgtNDdiOC1hZTk2LTNjZTcyMTE0ODdkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyMVQwNzE1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2M1YTAyZTE3NDhjODdjNWJiNmI4M2VkZTkwZWNjNzBjYzFjNjZhMWQwYjQ2ODUzNjNhNDIzZTlmNzUwNDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f_5mmnszym4tQ4pckUSNTAH1TDb87zU3BSUurLVG4OU">

这个报错可以忽略，不影响构建。
