### ISSUE TITLE
支持 `/v1/audio` 接口

### ISSUE THREAD

**Issue by songquanpeng** [songquanpeng/one-api#197]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
包含两个子接口，详见：https://platform.openai.com/docs/api-reference/audio

**应用场景**
可用于语音识别。

**Comment by mmwong1984** [comment]
還沒, @ckt1031 都表示有一定的難度

**Comment by ckt1031** [comment]
解決了上傳問題, 一切就可以了
甚至可以直接支持所有文件操作的API

目前我不太懂得怎樣直接在上傳文件中讀取元數據, 然後有一些內存飆高的問題

**Comment by aiastia** [comment]
> 解決了上傳問題, 一切就可以了 甚至可以直接支持所有文件操作的API
> 
> 目前我不太懂得怎樣直接在上傳文件中讀取元數據, 然後有一些內存飆高的問題
> 
> 讀取元數據的目的是為了獲取檔案的音頻時間, 進行計費

用FFMpeg 怎么样

**Comment by roamerxv** [comment]
程序没有任何变化，原来用的是 openai 的 key。 whisper 和chat 都没有问题。
现在改用了 one-api 的令牌，
chat 没有问题，并且在 ope-api 的日志里面也成功记录了信息
但是调用 whipser 接口 出现 503 错误。
改回 openai 的key 又一切正常。
应该是 one-api 支持的 whipser 还是有问题吧

**Comment by songquanpeng** [comment]
你渠道加 whisper 了么

**Comment by roamerxv** [comment]
搞定了。确实是 渠道没有加入 whisper 的模型。
