### ISSUE TITLE
status code 404: models/gemini-2.0-flash-exp is not found for API version v1

### ISSUE THREAD

**Issue by kaikanertan** [songquanpeng/one-api#1977]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
status code 404: models/gemini-2.0-flash-exp is not found for API version v1, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods
**复现步骤**
测试连接
**预期结果**
可以连通

**Comment by QAbot-zh** [comment]
请自行切换为 v1beta 版本

**Comment by wyangx** [comment]
> 请自行切换为 v1beta 版本

我将代理地址设置为 https://generativelanguage.googleapis.com/v1beta 貌似不起作用

**Comment by QAbot-zh** [comment]
> > 请自行切换为 v1beta 版本
> 
> 我将代理地址设置为 https://generativelanguage.googleapis.com/v1beta 貌似不起作用

不是这么换的，使用环境变量切换：

![image](https://github.com/user-attachments/assets/d7faa248-37c6-43dc-b1dc-d4942de5a382)

或者 berry 主题可以直接设置：

![image](https://github.com/user-attachments/assets/e7dd4237-c456-4a6c-8e53-12cdbbd0f1ec)

**Comment by kaikanertan** [comment]
> > > 请自行切换为 v1beta 版本
> > 
> > 
> > 我将代理地址设置为 https://generativelanguage.googleapis.com/v1beta 貌似不起作用
> 
> 不是这么换的，使用环境变量切换：
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/395004732-d7faa248-37c6-43dc-b1dc-d4942de5a382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDAzMDksIm5iZiI6MTczNDAwMDAwOSwicGF0aCI6Ii80MDIzNjc2NS8zOTUwMDQ3MzItZDdmYWEyNDgtMzdjNi00M2RjLWIxZGMtZDQ5NDJkZTVhMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDEwNDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmM1OTE2ODliNTJmZTAxNTcyZTRhYTE3Zjk0ODI5YjAyMTY4YmIyNGRmMmNhZjY4YjUwYzk4ZWJlMGUzMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0HI2MJVF2x1e6pMxckQu1f8niRsqW5S4-LMdcjQqwR4)
> 
> 或者 berry 主题可以直接设置：
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/395004789-e7dd4237-c456-4a6c-8e53-12cdbbd0f1ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDAzMDksIm5iZiI6MTczNDAwMDAwOSwicGF0aCI6Ii80MDIzNjc2NS8zOTUwMDQ3ODktZTdkZDQyMzctYzQ1Ni00YTZjLThlNTMtMTJjZGJiZDBmMWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDEwNDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMGIyNTRmMjkxY2I5ODFjYzllMjIxNGRlMzVmNTQwMmYzZjJjMmJjNGJlOGJkNzJlYjk0YWQzNWNiMzBiMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SDGfrDOsXw_s9Wd8h10GIaWT-C2kD5OHaK04dB0J90Y)

是的，设置环境变量：GEMINI_VERSION为v1beta后，可以连通和使用。

**Comment by LidoCKT** [comment]
请问一下如果docker运行的话如何把变量放进去

**Comment by happyTonakai** [comment]
> 请问一下如果docker运行的话如何把变量放进去

restart

**Comment by woaisikongshan** [comment]
填上apikey和模型名称就行了，虽然测试是错的，但是实际上是可以调用的

**Comment by kotonohakatsura** [comment]
问了好多大模型终于搞明白怎么改compose了
首先要自己创建一个docker-compose.yml文件，内容如下

version: '3.8' # 指定 compose 文件版本 (可选，但推荐)

services:
  one-api:
    image: justsong/one-api  # 指定要使用的镜像
    container_name: one-api # 设置容器名称，与之前保持一致
    platform: linux/amd64    # 指定平台，适配 M 系列 Mac (如果不需要可以移除)
    ports:
      - "3000:3000"         # 端口映射 (格式 "宿主机端口:容器端口")
    volumes:
      - ~/one-api-data:/data # 数据卷挂载 (格式 "宿主机路径:容器路径")
                              # 注意: '~' 代表你的用户主目录
    restart: always         # 设置重启策略
    environment: # <-- Add this section
      - GEMINI_VERSION=v1beta

然后在该目录下用docker-compose up -d命令启动，就可以在one-api中配置gemini2.5pro了
