### ISSUE TITLE
希望增加对Gemini 2.0的支持

### ISSUE THREAD

**Issue by norsizu** [songquanpeng/one-api#1979]
目前使用Gemini 2.0会报错gemini-2.0-flash-exp is not found for API version v1
查了一下在线文档，2.0用的API版本应该是v1alpha了，希望能添加支持，多谢。

**Comment by mxdlzg** [comment]
设置环境变量使用v1beta。或者用berry主题

**Comment by yanjian1978** [comment]
> 设置环境变量使用v1beta。或者用berry主题
如何设置？

**Comment by mxdlzg** [comment]
> > 设置环境变量使用v1beta。或者用berry主题
> > 如何设置？

https://github.com/songquanpeng/one-api/issues/1977#issuecomment-2537773773

**Comment by yanjian1978** [comment]
> > > 设置环境变量使用v1beta。或者用berry主题
> > > 如何设置？
> 
> [#1977 (comment)](https://github.com/songquanpeng/one-api/issues/1977#issuecomment-2537773773)

成功了，谢谢

**Comment by norsizu** [comment]
> > > 设置环境变量使用v1beta。或者用berry主题
> > > 如何设置？
> 
> [#1977 (comment)](https://github.com/songquanpeng/one-api/issues/1977#issuecomment-2537773773)

多谢，我还想请教一下，我使用的是fastgpt集成的one-api，而且是docker部署的，该怎么修改环境变量呢

**Comment by mxdlzg** [comment]
> > > > 设置环境变量使用v1beta。或者用berry主题
> > > > 如何设置？
> > 
> > 
> > [#1977 (comment)](https://github.com/songquanpeng/one-api/issues/1977#issuecomment-2537773773)
> 
> 多谢，我还想请教一下，我使用的是fastgpt集成的one-api，而且是docker部署的，该怎么修改环境变量呢

docker支持直接传环境变量的。参考https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/

**Comment by jinjunliu** [comment]
但这样的话Gemini 1.5的版本应该就用不了了。。

**Comment by norsizu** [comment]
> 但这样的话Gemini 1.5的版本应该就用不了了。。

是的，是这样

**Comment by mxdlzg** [comment]
> 这个原作者似乎挺久没更新了，我用了这个fork版的能用Gemini 2.0: https://github.com/Laisky/one-api

其实只要切v1beta就行，模型直接在模型那里输字符串点添加就ok。2.0跟1.5在api调用上没什么区别，只是名字不一样，如果有api兼容问题我后面会看情况提PR。

**Comment by jinjunliu** [comment]
> > 这个原作者似乎挺久没更新了，我用了这个fork版的能用Gemini 2.0: https://github.com/Laisky/one-api
> 
> 其实只要切v1beta就行，模型直接在模型那里输字符串点添加就ok。2.0跟1.5在api调用上没什么区别，只是名字不一样，如果有api兼容问题我后面会看情况提PR。

是的，但是这样就没法同时用1.5了，2.0毕竟还是实验版，我还想同时保留用1.5

**Comment by mxdlzg** [comment]
为什么不能用1.5？添加2.0又不会影响1.5

**Comment by jinjunliu** [comment]
> 为什么不能用1.5？添加2.0又不会影响1.5，v1beta里1.5pro和1.5flash都有的

这样啊，我还以为v1beta里没1.5. 那这确实很容易切。
