### ISSUE TITLE
支持glhf.chat的api

### ISSUE THREAD

**Issue by liuzj288** [songquanpeng/one-api#1981]
试了下自定义渠道添加提示404报错

https://glhf.chat/users/settings/api

API Details

Base URL:

https://glhf.chat/api/openai/v1

Note that model names will need to be appended with "hf:". For example, hf:meta-llama/Llama-3.1-405B-Instruct.

**Comment by QAbot-zh** [comment]
复用 openai 格式就好了：

![image](https://github.com/user-attachments/assets/c9a07c68-f0a6-4003-aa8e-55bfcfeed1ae)

**Comment by liuzj288** [comment]
> 复用 openai 格式就好了：
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/395753005-c9a07c68-f0a6-4003-aa8e-55bfcfeed1ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNTgzMDAsIm5iZiI6MTczNDE1ODAwMCwicGF0aCI6Ii80MDIzNjc2NS8zOTU3NTMwMDUtYzlhMDdjNjgtZjBhNi00MDAzLWFhOGUtNTViZmNmZWVkMWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA2MzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNWUxYTA4NzJjZWVmZWE0N2U3NTIxNzI5ZGQyZGI3YmZiMGUxYmRkYWM1MjkyMGZkNzJmM2VmZWYwMzI5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4KRzg3f0l_eUdpZmeCEAFJqc8pK0BKvuBHuO4T1gJQ8)

咦，原来不用加/v1啊
