### ISSUE TITLE
在哪里可以配置ServerAddress?

### ISSUE THREAD

**Issue by momomobinx** [songquanpeng/one-api#1991]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
在令牌页面点击聊天，填写的地址是localhost:3000, 应该可以配置成最终前端页面的地址
**应用场景**
用户直接在令牌界面点击聊天即可开始不用再手动更改默认的地址

**Comment by QAbot-zh** [comment]
这都没进设置找找吗

![image](https://github.com/user-attachments/assets/6864168d-294b-4c3a-ac59-175a412eb254)

**Comment by momomobinx** [comment]
一直想着部署的时候就在配置文件里面配置(滑稽。)
