### ISSUE TITLE
请求适配一下gemini-2.0-flash-thinking

### ISSUE THREAD

**Issue by QAbot-zh** [songquanpeng/one-api#1993]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
 gemini-2.0-flash-thinking-exp 模型**非流调用**时会返回两个 text ，一个是思考过程，一个是回复内容，当前项目在**非流调用**的时候会丢失第二个 text：

只有英文的思考过程：
![image](https://github.com/user-attachments/assets/27011a35-ecc0-4b84-8781-2bc2fefc6c31)

实际包含两个text：
![image](https://github.com/user-attachments/assets/11f56475-78be-428a-b7dd-8569c5dcdc19)

可以参考：https://github.com/Calcium-Ion/new-api/commit/9a54b345c5d83be8d0f0e83ce42ae10e42e2c2f2

**Comment by sandycs-protoss** [comment]
这个不好弄。因为流式传输的接口，没有将思考和回答区分的很明确
流式传输不是每一个chunk的parts都有两个部分
只有在思考和回答的交界处“有可能”会出现两个部分
最好的做法是thinking模型不支持流式，再按你说的区分

**Comment by QAbot-zh** [comment]
> 这个不好弄。因为流式传输的接口，没有将思考和回答区分的很明确 流式传输不是每一个chunk的parts都有两个部分 只有在思考和回答的交界处“有可能”会出现两个部分 最好的做法是thinking模型不支持流式，再按你说的区分

你理解错我的意思了，我不是要区分流式里的思考和回复，是要防止非流的回复被吞了

**Comment by sandycs-protoss** [comment]
哦我没看到你强调非流了
非流确实有清晰的两个部分
流很难处理

**Comment by QAbot-zh** [comment]
@songquanpeng @mxdlzg 

抱歉打扰了，实测 gemini 类型的**流式**在思考和回复的交界处有两个 text ，经查当前的[处理](https://github.com/songquanpeng/one-api/blob/main/relay/adaptor/gemini/main.go#L185)会导致“交界处”丢失一个 text 字段（回复开始的第一个 text）从而表现为“回答吞字”

![image](https://github.com/user-attachments/assets/ea48588f-462d-4f60-9e6c-95092aa99efe)

![image](https://github.com/user-attachments/assets/46d55b37-0ec5-46dd-a1f3-3104f91db5c6)

oneapi 流式调用，“回答吞字”：
![Clip_2024-12-22_23-22-33](https://github.com/user-attachments/assets/43cb6e1d-d3b3-4d3c-b27f-8f6e8e5ef49a)

预期的流式调用：
![Clip_2024-12-22_23-15-28](https://github.com/user-attachments/assets/53192bc0-3e93-4e04-95e4-4121317faceb)
