### ISSUE TITLE
.net core客户端openai-dotnet访问oneapi接口报错

### ISSUE THREAD

**Issue by wdqzdd** [songquanpeng/one-api#1998]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
![image](https://github.com/user-attachments/assets/becb7444-4166-49ed-9a55-280f18a8d94c)

使用.net core客户端访问报错
'<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

https://github.com/openai/openai-dotnet
`ApiKeyCredential apiKeyCredential = new ApiKeyCredential(llmModel.Token);
            OpenAIClientOptions openAIClientOptions = new OpenAIClientOptions();
            openAIClientOptions.Endpoint = new Uri(llmModel.BaseUrl);

            ChatClient client = new(model: llmModel.Model, apiKeyCredential, openAIClientOptions);

            List<ChatMessage> chatMessages = new List<ChatMessage>();
            if (!string.IsNullOrWhiteSpace(model.System))
            {
                chatMessages.Add(ChatMessage.CreateSystemMessage(model.System));
            }
            if (!string.IsNullOrWhiteSpace(model.User))
            {
                chatMessages.Add(ChatMessage.CreateUserMessage(model.User));
            }
                

            ChatCompletion completion = await client.CompleteChatAsync(chatMessages);

            var llmResult = completion.Content[0].Text;`

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by QAbot-zh** [comment]
你把整个 completion 打印出来看看接收到了什么内容

**Comment by wdqzdd** [comment]
> 你把整个 completion 打印出来看看接收到了什么内容

ApiKeyCredential apiKeyCredential = new ApiKeyCredential(llmModel.Token);
OpenAIClientOptions openAIClientOptions = new OpenAIClientOptions();
openAIClientOptions.Endpoint = new Uri(llmModel.BaseUrl);

ChatClient client = new(model: llmModel.Model, apiKeyCredential, openAIClientOptions);

List<ChatMessage> chatMessages = new List<ChatMessage>();
if (!string.IsNullOrWhiteSpace(model.System))
{
    chatMessages.Add(ChatMessage.CreateSystemMessage(model.System));
}
if (!string.IsNullOrWhiteSpace(model.User))
{
    chatMessages.Add(ChatMessage.CreateUserMessage(model.User));
}
ChatCompletion completion = null;
try
{
    completion = await client.CompleteChatAsync(chatMessages);
}
catch (Exception e)
{

    await Console.Out.WriteLineAsync(e.ToString());
}



var llmResult = completion.Content[0].Text;

![image](https://github.com/user-attachments/assets/029202a3-12f2-448f-a6b2-e0541319c8ee)
我看了下输出的内容是一个你们的网页。

**Comment by QAbot-zh** [comment]
base_url 加 /v1 了吗

**Comment by wdqzdd** [comment]
> base_url 加 /v1 了吗

加了v1确实可以了。感谢。
