### ISSUE TITLE
如何基于宝塔进行部署？

### ISSUE THREAD

**Issue by hieivip** [songquanpeng/one-api#2]
![image](https://user-images.githubusercontent.com/54146330/233897937-6ffed216-a974-4684-8ba1-9e97877f5fdc.png)
这样是不是更简单一些，dock 不太会用

**Comment by songquanpeng** [comment]
首先据我所知宝塔是支持部署 Docker 镜像的。

其次，这个截图里的内容：
1. 项目执行文件：release 页面下载 one-api 后，给执行权限：`chmod u+x one-api`，放到一个合适的地方。
2. 项目名称：One API
3. 项目端口：3000
4. 执行命令：one-api

**Comment by songquanpeng** [comment]
不过我没用过宝塔哈，所以如果不行的话请继续反馈。

**Comment by songquanpeng** [comment]
如果仍有问题欢迎重开 issue。
