### ISSUE TITLE
存在跨域问题

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#20]

**Comment by songquanpeng** [comment]
已修复，已推送版本 `v0.1.4-alpha`。

**Comment by songquanpeng** [comment]
啊这，我再看一下。

**Comment by lmuiotctf** [comment]
has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by songquanpeng** [comment]
已再次修复，`v0.1.4-alpha` 已重新打包。

**Comment by lmuiotctf** [comment]
已经ok，已经可以，虽然这样不安全

**Comment by songquanpeng** [comment]
好的。
