### ISSUE TITLE
服务突然死掉没有访问

### ISSUE THREAD

**Issue by bian1721** [songquanpeng/one-api#2001]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
[SYS] 2024/12/27 - 11:17:40 | memory cache enabled 
[SYS] 2024/12/27 - 11:17:40 | sync frequency: 600 seconds 
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/songquanpeng/one-api/model.InitChannelCache()
	/build/model/cache.go:196 +0x78e
main.main()
	/build/main.go:75 +0x556

**复现步骤**
正式机正常登录
**相关截图**
![image](https://github.com/user-attachments/assets/00366a5c-db32-48a1-b3cb-2777bcc0bbed)

如果没有的话，请删除此节。

**Comment by A1exMinatoooo** [comment]
我也遇到了这个问题，请问是怎么解决的？

**Comment by HotelEnglish** [comment]
我今天添加渠道的模型时，有一个无法添加，试了两次，网站就崩溃了，就出现了这个提示。请问是怎么解决的？

**Comment by yan123yan** [comment]
> 我今天添加渠道的模型时，有一个无法添加，试了两次，网站就崩溃了，就出现了这个提示。请问是怎么解决的？

同样的情况

**Comment by lwdnxu** [comment]
相同的问题，为什么这个issue被关了
