### ISSUE TITLE
Billing相关API显示令牌额度

### ISSUE THREAD

**Issue by 13597440473** [songquanpeng/one-api#202]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
接口查询额度返回参数存在误差，4.2是剩余额度，总额应是5
![image](https://github.com/songquanpeng/one-api/assets/49380801/91696daf-b141-4514-9c77-21ff1ec2a175)
![image](https://github.com/songquanpeng/one-api/assets/49380801/be27db50-961f-49e3-bbe2-a521998261a4)

**复现步骤**
oneapi生成令牌，使用接口/dashboard/billing/subscription查询额度

**预期结果**
Billing相关API显示令牌额度查询接口返回值与openai接口返回值含义一致

**Comment by songquanpeng** [comment]
订阅总额处显示用户的剩余额度更加直观。

除非有的客户端自己减了一下，算出了剩余额度。

如果有这样的情况，欢迎列出来。
