### ISSUE TITLE
缓存导致令牌可超额使用。

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#204]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
令牌额度已用完的情况可以继续超额使用一段时间，账户余额同样。
**复现步骤**
创建一个1000额度的令牌，然后消耗掉，超过自己设定的同步时间后，再去使用还是可以继续用，大概持续五分钟后令牌失效
**预期结果**
账户余额或令牌余额小于请求预扣费额度则请求失败。
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/11790369/87d2da62-b398-42ad-8bdf-f6a3ab6fc1af)

![image](https://github.com/songquanpeng/one-api/assets/11790369/2859bb39-0b10-4467-98a9-981a79bb81d3)

![image](https://github.com/songquanpeng/one-api/assets/11790369/69352b4a-09c6-40d3-90ef-94a6ee7dfd26)

**Comment by songquanpeng** [comment]
现在每次消费后都会从数据库拉去最新余额更新缓存。
