### ISSUE TITLE
支持讯飞星火大模型

### ISSUE THREAD

**Issue by zhangdszq** [songquanpeng/one-api#206]
**例行检查**
+ [- ] 我已确认目前没有类似 issue
+ [- ] 我已确认我已升级到最新版本
+ [-  ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ - ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
是否可以支持讯飞星火大模型？ 可以提供内测 API key~

**Comment by songquanpeng** [comment]
可以支持，但是目前需要先等更高优先级的事项完成。

**Comment by zhangdszq** [comment]
> 可以支持，但是目前需要先等更高优先级的事项完成。

好的 谢谢：）

**Comment by songquanpeng** [comment]
可以提供一下 key 么，最近有适配的打算

**Comment by songquanpeng** [comment]
进群后私聊我，不要公开

**Comment by songquanpeng** [comment]
已支持
