### ISSUE TITLE
增加性能模式

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#207]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
用于接入第三方项目，仅用 key 池功能。不需要 token 计算，不需要额外的读写库操作。

**应用场景**

**Comment by lmuiotctf** [comment]
这个可以加个读写库的开关，关闭则不需要读写

**Comment by c121914yu** [comment]
> 这个可以加个读写库的开关，关闭则不需要读写

没用，这个不是写库占cpu，而是token计算

**Comment by c121914yu** [comment]
![1688364947280](https://github.com/songquanpeng/one-api/assets/50446880/1dbd0129-1d2b-4cea-8ca5-74ef7622ff55)
![1688364958318](https://github.com/songquanpeng/one-api/assets/50446880/525f6042-59b4-494d-bb96-ade792aed870)
高并发情况下，高 token 计算时（10个1w计算）导致 cpu 突然上升

**Comment by c121914yu** [comment]
> ![1688364947280](https://user-images.githubusercontent.com/50446880/250472624-1dbd0129-1d2b-4cea-8ca5-74ef7622ff55.jpg) 
![image](https://github.com/songquanpeng/one-api/assets/50446880/0d52b50c-3cd8-4e7c-b91e-0bc10e959bde)

高并发情况下，高 token 计算时（10个1w计算）导致 cpu 突然上升

**Comment by lmuiotctf** [comment]
目前我2h2G，并发同时请求2000多个没啥问题

**Comment by c121914yu** [comment]
> 目前我2h2G，并发同时请求2000多个没啥问题

你试试mock一下多token，

**Comment by lmuiotctf** [comment]
目前都是用户在用，我没有进行多token测试哈

**Comment by c121914yu** [comment]
> 目前都是用户在用，我没有进行多token测试哈

之前只有4k模型时候，我也没遇到这个问题，16k的高token并发后，经常导致cpu不稳

**Comment by lmuiotctf** [comment]
那这个确实，升级了16K之后，或者你直接回滚早期的代码，早期是没有进行token计算，只是统计请求次数而已哈

**Comment by c121914yu** [comment]
> 那这个确实，升级了16K之后，或者你直接回滚早期的代码，早期是没有进行token计算，只是统计请求次数而已哈

或者统一采用估值模式，FastGpt 之前也是精确计算，性能很差，改成估算后1c完全支撑了并发，误差不超过10个token

**Comment by songquanpeng** [comment]
所以只需要加一个计算 token 方式的模式切换就好了，这里就是最主要的计算密集的地方。

**Comment by mrhaoji** [comment]
感觉如果误差小的话加一个估算模式比较折中，毕竟不算 token 按 key 计费的大功能就没了，站长提供服务没那么方便了

**Comment by songquanpeng** [comment]
加了一个配置项：
![image](https://github.com/songquanpeng/one-api/assets/39998050/5cbe50d4-539f-414c-8e81-dc359a10fe46)

启用之后会通过字节数乘以一个系数来估算 token，如果有更好的方法请告知我。
