### ISSUE TITLE
支持 ChatGML

### ISSUE THREAD

**Issue by haihaimx** [songquanpeng/one-api#211]
**例行检查**
+ [y] 我已确认目前没有类似 issue
+ [y] 我已确认我已升级到最新版本
+ [y] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [y] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
能不能增加支持chatgml
**应用场景**

**Comment by songquanpeng** [comment]
这种应该用一个 API 适配项目结合自定义渠道功能实现。
