### ISSUE TITLE
text-embedding-ada-002模型无效

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#214]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
已填入全部的模型，但是在请求的时候显示无可用渠道
**复现步骤**
采用的是POSTMAN接口请求工具进行测试
**预期结果**
理论上应该是支持该接口/v1/embeddings
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/52068443/f63fb8e4-2f67-491c-9c37-b8fa2e6bc814)

**Comment by songquanpeng** [comment]
用户所在分组有这个模型吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月29日(星期四) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [songquanpeng/one-api] text-embedding-ada-002模型无效 (Issue #214)





 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，尤其是常见问题部分
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
问题描述
 已填入全部的模型，但是在请求的时候显示无可用渠道
 复现步骤
 采用的是POSTMAN接口请求工具进行测试
 预期结果
 理论上应该是支持该接口/v1/embeddings
 相关截图

**Comment by lmuiotctf** [comment]
帮我关闭下，我忘记修改sql
