### ISSUE TITLE
管理用户界面下新增用户指定可用的渠道

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#215]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
希望在管理用户界面下新增用户指定可用的渠道。
![image](https://github.com/songquanpeng/one-api/assets/52068443/bf29ea03-1057-4646-8207-ee8d7c9f0a8e)

**应用场景**
这样管理员可进行绑定用户进行使用的渠道，可进行区分开来3.5和4.0的key。不然用户都是在渠道管理里面随机使用，有的4.0不让某些用户进行使用。

**Comment by songquanpeng** [comment]
不是有分组功能吗？

**Comment by lmuiotctf** [comment]
哎呀我去，我又忘记了，分组这个没怎么用起来，收到~！！
