### ISSUE TITLE
接口请求失败，报404错误

### ISSUE THREAD

**Issue by JunTsao** [songquanpeng/one-api#216]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

使用docker部署，完成后发现接口调用失败
使用GET方式打开 192.168.1.100:3000/v1 应显示：
`{
    "error": {
        "message": "API not found: GET:/v1",
        "type": "one_api_error",
        "param": "",
        "code": "api_not_found"
    }
}`

实际显示：
`Sorry, Page Not Found`

是我哪里操作步骤不对吗？

**Comment by songquanpeng** [comment]
我没看出有什么问题，显示 Sorry, Page Not Found 完全有可能是因为你的客户端。
