### ISSUE TITLE
命令行类客户端使用流会报错：无效令牌。

### ISSUE THREAD

**Issue by SunnyGPT** [songquanpeng/one-api#219]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
命令行使用流会提示无效令牌，非流不会

**复现步骤**
![image](https://github.com/songquanpeng/one-api/assets/126902077/8837bc5b-dd2c-41d7-a7fc-b8a0e621c8c2)
![image](https://github.com/songquanpeng/one-api/assets/126902077/12861ad5-62d3-4cf6-92fa-6e08c3544fbf)

**预期结果**
修复
**相关截图**
如果没有的话，请删除此节。

**Comment by SunnyGPT** [comment]
已经修复。

**Comment by songquanpeng** [comment]
所以问题出在哪里呢？
