### ISSUE TITLE
允许以账号为单位设置初始次数

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#22]
1.测试发现普通用户新建令牌次数为零，是否会考虑以账号为单位有初始次数，可以是10次或者20次，由管理员配置。
![image](https://user-images.githubusercontent.com/75829171/234540326-f725d36d-2e3c-4089-b945-0c234bfb612e.png)
2.新普通用户令牌ID不是从1开始的，显然显示的是数据库主键ID，小问题。

**Comment by songquanpeng** [comment]
1. 这个可以支持。
2. 主键 ID 这个，之后直接隐藏掉算了。

**Comment by JeazW** [comment]
> 1. 这个可以支持。
> 2. 主键 ID 这个，之后直接隐藏掉算了。

初始次数最好是绑定邮箱之后才有，或者直接在注册时需要邮箱验证。
建议在注册和登录还有验证邮箱时引入验证码，可以用程序自己生成验证码，或者也使用极验验证行为验证码，都可以，三方验证码可以在后台配置接口。

**Comment by songquanpeng** [comment]
已支持为新用户设置初始配额，可在系统配置页面设置该值。新版本 `v0.1.5` 已推送。
