### ISSUE TITLE
请求支持 /v1/engines/text-embedding-ada-002/embeddings

### ISSUE THREAD

**Issue by playniuniu** [songquanpeng/one-api#222]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

使用 langchain 做私有化知识库的时候，需要用到 embeddings 的模型，改模型会请求 /v1/engines/text-embedding-ada-002/embeddings 接口

**应用场景**

通过 langchain 进行私有化知识库的 embbeding

**Comment by songquanpeng** [comment]
好的

**Comment by playniuniu** [comment]
> 好的

我已经提了 pull requests，请您审核一下

**Comment by songquanpeng** [comment]
这两天有点忙哈，我会尽快检查 & 测试。

**Comment by songquanpeng** [comment]
我看了一下文档，好像这个接口已经被废弃了：https://platform.openai.com/docs/deprecations

![image](https://github.com/songquanpeng/one-api/assets/39998050/2767abb1-82c4-4d2a-9030-23d5cd7a2c18)

**Comment by songquanpeng** [comment]
目前不考虑支持已经废弃的接口。

**Comment by songquanpeng** [comment]
相关 PR 已合并。
