### ISSUE TITLE
新版更新余额问题

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#225]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
点击更新所有渠道余额时，请求失败。提示网关超时。但是单个测试的话，一两秒就出结果了。
并且接口失败后，loading动画一直在。

**复现步骤**

**预期结果**
点击更新所有渠道余额 - 等待接口返回 - 更新结果。
如果确实是由于账单接口问题，单个余额测试应该也无法通过。

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/50446880/325a6cd3-d9e9-4139-98de-aec7582eb697)
![image](https://github.com/songquanpeng/one-api/assets/50446880/d2f7bf15-807e-4d84-83c5-d77616e95e63)

如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
好的，我忙完后看一下。

**Comment by songquanpeng** [comment]
是这样的，余额更新是挨个更新的，不是并发的，所以是有可能会超时。

页面超时其实无所谓哈，因为如果有问题会发邮件。
