### ISSUE TITLE
令牌额度耗尽后还能用

### ISSUE THREAD

**Issue by Ackites** [songquanpeng/one-api#227]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
版本：v0.4.9-alpha.1

令牌额度耗尽后还能用，初始设置较低额度，比如10，然后再使用，会出现负的情况，第一次请求这是正常情况，但是接下来的请求不应该拒绝吗，但是还是还可以使用。

**复现步骤**
初始设置较低额度，比如10，第一次请求完毕会出现负的情况，但是当额度为负值后，还是可以进行请求而不是拒绝。

**预期结果**
额度为负值后拒绝请求

**Comment by songquanpeng** [comment]
无法复现。
