### ISSUE TITLE
令牌创建初始额度设置问题

### ISSUE THREAD

**Issue by Ackites** [songquanpeng/one-api#228]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
版本：v0.4.9-alpha.1

令牌创建初始额度设置为0，后面再把额度增加上，这时候会发现即使有额度，也还是用不了，一直提示额度已耗尽。

**复现步骤**

**预期结果**

**相关截图**

**Comment by songquanpeng** [comment]
你是不是没有启用？

**Comment by Ackites** [comment]
> 你是不是没有启用？

不，我又测试了一下，确实是有这个问题，编辑加额度后，启用了，然后使用还是会提示该令牌额度已用尽，然后状态会自动变为已耗尽，额度实际上是有的，再次启用也没法用

**Comment by songquanpeng** [comment]
我又试了一次，还是没法复现。

方便的话发视频吧。
