### ISSUE TITLE
渠道分页数据刷新不显示

### ISSUE THREAD

**Issue by Ackites** [songquanpeng/one-api#229]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
版本：v0.4.9-alpha.1

如图：
![Q7XHX@F1_8FSS_5M_FL@HOR.png](https://s2.loli.net/2023/07/01/oTqu2ycxRhpXkbP.png)

点击刷新后：
![2.png](https://s2.loli.net/2023/07/01/ub68sjxJSWnaMPz.png)

数据直接不显示了。

**复现步骤**

**预期结果**

**Comment by songquanpeng** [comment]
已修复。
