### ISSUE TITLE
使用 MySQL 5.7 启动报错：Error 1170: BLOB/TEXT column 'key' used in key specification without a key length

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#23]
怎么PR给你

**Comment by lmuiotctf** [comment]
只有我用GO部署嘛 哈哈哈

**Comment by songquanpeng** [comment]
Docker 的话主要是更新很方便，如果用 MySQL & Redis 的话，应该配合 Docker Compose 使用。

而 One API 里面需要设置环境变量的也主要就这两个。

**Comment by lmuiotctf** [comment]
目前还不是采用MYSQL吧，看了下是SQLite，有计划把微信公众号合并到这里嘛

**Comment by songquanpeng** [comment]
1. 可以用 MySQL 的，详见 README。2. 那个的话没用计划合并，搞成单独的服务好一些。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月26日(星期三) 晚上9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [songquanpeng/one-api] 支持从工作根目录读取 .env 文件 (Issue #23)





 
目前还不是采用MYSQL吧，看了下是SQLite，有计划把微信公众号合并到这里嘛

**Comment by songquanpeng** [comment]
配置环境变量 `SQL_DSN` 就好，MySQL 是原本就支持的，不过未测试可能会有问题。

本项目基于我的模板项目 gin-template，对于 MySQL 的支持也是继承于该项目。

**Comment by lmuiotctf** [comment]
确实，启动之后可能是我的库5.7版本过低。报错

**Comment by songquanpeng** [comment]
可以看一下报错信息吗？

**Comment by lmuiotctf** [comment]
CREATE TABLE `tokens` (`id` bigint AUTO_INCREMENT,`user_id` bigint,`key` longtext,`status` bigint DEFAULT 1,`name` varchar(191),`created_time` bigint,`accessed_time` bigint,`expired_time` bigint DEFAULT -1,`remain_times` bigint DEFAULT 0,`unlimited_times` boolean DEFAULT false,PRIMARY KEY (`id`),INDEX `idx_tokens_name` (`name`),UNIQUE INDEX `idx_tokens_key` (`key`))
[FATAL] 2023/04/26 - 14:19:54 | [Error 1170: BLOB/TEXT column 'key' used in key specification without a key length]

**Comment by songquanpeng** [comment]
Okay，有时间处理一下这个问题。

**Comment by lmuiotctf** [comment]
辛苦

**Comment by songquanpeng** [comment]
已修复，版本 `v0.1.6-alpha` 已推送，期待反馈。

**Comment by lmuiotctf** [comment]
MySQL测试下已经🆗
![image](https://user-images.githubusercontent.com/52068443/234778126-76d55c7e-c973-48c5-a707-01e47994d4f3.png)

**Comment by lmuiotctf** [comment]
目前问题

**Comment by songquanpeng** [comment]
可以看一下报错信息吗？我现在没有 MySQL 环境可以测试。

**Comment by lmuiotctf** [comment]
我刚刚改了这两张表就可以，报错是：id没有值，没有自动递增
![image](https://user-images.githubusercontent.com/52068443/234780822-ab7ae949-6aad-4330-98bc-d1cb6a91c771.png)

**Comment by songquanpeng** [comment]
我记得另一个项目里是可以自动递增的，不然主键冲突肯定会报错的。

我回去之后有了 MySQL 环境后再测试一下。

**Comment by lmuiotctf** [comment]
目前普通用户可以自己创建令牌，但是超级管理员应该可以查看到普通用户创建的令牌。（目前管理员仅能看到自己）
逻辑应该是普通用户仅有创建令牌的功能，但是没有权限进行设置次数和到期时间，这两个应该交给管理员来控制

**Comment by lmuiotctf** [comment]
不好意思刚刚页面没有刷新，应该卡bug了（刚刚普通用户居然可以输入次数，现在不可以了）
![image](https://user-images.githubusercontent.com/52068443/234782667-80c8d19c-f06a-4b28-be7b-849fa81ef306.png)

**Comment by songquanpeng** [comment]
见 #9

**Comment by songquanpeng** [comment]
应该是你刚刚登录了管理员账户，这个就算他能输入后端也不会给改的。

**Comment by lmuiotctf** [comment]
超级管理员应该可以查看到普通用户创建的令牌。（目前管理员仅能看到自己）
我觉得这点可以加上，超管支持查看所有的令牌

**Comment by songquanpeng** [comment]
感觉管理员管理用户的令牌意义不大哈，如果用户有问题可以直接封禁用户的。

不过我突然意识到令牌校验时并没有检查用户的状态，导致用户被禁用后令牌还能用。

**Comment by lmuiotctf** [comment]
这个可以进行优化下

**Comment by songquanpeng** [comment]
Okay，不过管理员管理用户令牌这个，应该单独开一个 issue，和当前 issue 主题关系不大不方便归档哈

**Comment by songquanpeng** [comment]
> 目前问题：渠道和令牌表id没有自增，会报错，记得改下

MySQL `8.0.27` 未能复现。

**Comment by songquanpeng** [comment]
如果新版本依旧有问题，欢迎重开 issue。
