### ISSUE TITLE
令牌过期时间设置问题

### ISSUE THREAD

**Issue by Ackites** [songquanpeng/one-api#230]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
版本：v0.4.9-alpha.1

令牌初始创建设置过期时间，过期后，重新编辑设置为永不过期，但无法重新启用，一定需要设置一个过期时间才能启用。

![3.png](https://s2.loli.net/2023/07/01/fUJ8nwA4lVQyYK6.png)

而且即使设置了一个过期时间后，再次启用，该令牌还是无法使用，会一直提示该令牌已过期，且状态会变为已过期。

![4.png](https://s2.loli.net/2023/07/01/tN1rRUAZ9KoyMc2.png)

**复现步骤**

**预期结果**

**相关截图**

**Comment by songquanpeng** [comment]
这个确实，近期处理。

**Comment by songquanpeng** [comment]
已修复。
