### ISSUE TITLE
页面访问控制

### ISSUE THREAD

**Issue by Ackites** [songquanpeng/one-api#231]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
版本：v0.4.9-alpha.1

系统在已登录的情况下，在地址栏直接输入地址，还可以访问登录页面和注册页面，而不是进行页面跳转，可以进行二次登录。

![2023-07-01 013819.png](https://s2.loli.net/2023/07/01/fezdIik3vTEaGoY.png)

**复现步骤**

**预期结果**

**相关截图**

**Comment by Ackites** [comment]
而且普通用户以直接在地址栏输入地址的方式，可以访问管理员才能看到的页面，虽然没有权限，但是不是有点不太好

**Comment by songquanpeng** [comment]
正常情况下用户不会看到的，而且数据不会被未授权用户获取到。
