### ISSUE TITLE
希望{"error":{"message":"无可用渠道","type":"one_api_error"}} 支持自定义提示词

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#232]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望在这个无可用渠道的提示中后台支持自定义提示词
**应用场景**
这样可以提示更多的信息。
![image](https://github.com/songquanpeng/one-api/assets/52068443/6441563d-18d4-41e8-b386-b63dff27a204)

**Comment by songquanpeng** [comment]
没看出来有多大意义。
