### ISSUE TITLE
bug：渠道、兑换等地方，在非第一页点刷新，页面会空白

### ISSUE THREAD

**Issue by woodchen-ink** [songquanpeng/one-api#233]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
![image](https://github.com/songquanpeng/one-api/assets/95951386/e151a525-d287-4e5b-99b3-64cf8dfac6ee)

**复现步骤**
渠道、兑换等地方，在非第一页点刷新，页面会空白
**预期结果**
正常刷新

**Comment by woodchen-ink** [comment]
0.4.8版本

**Comment by songquanpeng** [comment]
和 #233 重复，先关了哈
