### ISSUE TITLE
添加模型api key 的調用百分比

### ISSUE THREAD

**Issue by mmwong1984** [songquanpeng/one-api#234]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
添加模型api key 的調用百分比
例如 Api key A: 70 percent
Api key B: 25 percent
Api key C: 5 percent
**应用场景**
不再隨機抽key

**Comment by songquanpeng** [comment]
意义不大，用完自动禁用就行。

之后会加入重试，所以那一次用不了的也会得到解决。

更何况，不是所有人都用的这种 key。
