### ISSUE TITLE
SYNC_FREQUENCY not set, Redis is disabled 

### ISSUE THREAD

**Issue by shixinzi** [songquanpeng/one-api#235]
docker 部署的，redis服务也启动了，哪地方禁用的

**Comment by songquanpeng** [comment]
报错信息已经告诉你了。

**Comment by BonderTam** [comment]
如果你是用docker-compose.yml 来启动容器， 除了 .env 中要有 SYNC_FREQUENCY=60
docker-compose.yml 中也要记得加上：
![1719214120417](https://github.com/songquanpeng/one-api/assets/249648/036c7785-6f6b-4b25-9d2b-293e0df2f633)
然后终于有了：
![image](https://github.com/songquanpeng/one-api/assets/249648/b4a55159-8a89-458b-af2f-cb6d6f6e4549)

。。。此处省略一万字。。。
