### ISSUE TITLE
{"error":{"message":"该令牌状态不可用","type":"one_api_error"}}

### ISSUE THREAD

**Issue by APPX-Studio** [songquanpeng/one-api#239]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
<img width="585" alt="image" src="https://github.com/songquanpeng/one-api/assets/49307767/67312b49-f6c1-43bf-a81e-52069a443293">

**复现步骤**

**预期结果**

**相关截图**
<img width="1000" alt="image" src="https://github.com/songquanpeng/one-api/assets/49307767/d798708e-1cd7-4179-be43-ff6053898531">

 我的客户端提示这个错误 本地测试

**Comment by APPX-Studio** [comment]
请问本地base url 是不是 http://locahost:3000 或者

**Comment by songquanpeng** [comment]
是你的部署地址。

所以你的令牌状态是什么？
