### ISSUE TITLE
在 Web 端增加一个对话页面

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#24]
消费该账号对应的次数，直接在应用内使用；而令牌则专门作为其他应用调用的key，（类似官网了），这个功能不需要做得太复杂，可以做成一个简单的demo；另外有位置放置已经部署的其他应用的导航或者超链接，点击跳转后粘贴令牌进行使用。
想法有点乱，如果有这方面的考虑可以参考下。

**Comment by songquanpeng** [comment]
现在可以自定义首页了。对话页面目前不考虑做了，目前已经有很多优秀的项目了，部署后在首页或关于页面给出链接即可。
