### ISSUE TITLE
对于负载均衡的优化建议

### ISSUE THREAD

**Issue by Huiyicc** [songquanpeng/one-api#244]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
支持在渠道中设定key的频率限制,更好的配合负载均衡.
例如:列表中有3个$5 gptkey,2个$120key,5刀的qps为3,120刀为3000,如果5刀的id比较靠前的话那么很容易会触发5刀的限制而不是负载到120刀上面

**Comment by songquanpeng** [comment]
重复 #187
