### ISSUE TITLE
支持自定义模型

### ISSUE THREAD

**Issue by mmwong1984** [songquanpeng/one-api#247]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ //] 我已确认目前没有类似 issue
+ [ //] 我已确认我已升级到最新版本
+ [ //] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [// ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [// ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
我自己做了一个反代bard api, 不过one api不支持自定义模型, 求支持
**应用场景**
可以自己增加自定义模型

**Comment by songquanpeng** [comment]
模型映射功能不能满足需求么？

**Comment by mmwong1984** [comment]
什麼東東

**Comment by mmwong1984** [comment]
不懂得用

**Comment by mrhaoji** [comment]
> 模型映射功能不能满足需求么？

模型映射应该满足不了他需求

他意思是，他自己有自定义模型，比如市面上非 OpenAI 的模型 Bard 、 Claude 那些
甚至还有本来就做大模型的，有自己命名的模型

开放自定义模型还好，关键问题可能在计费那边

**Comment by songquanpeng** [comment]
自定义模型要接入则需要使用 OpenAI 的接口协议，模型映射功能可以将用户的对于 OpenAI 系列模型的请求映射成自定义模型的请求。

之后可以加入自定义模型列表。

**Comment by songquanpeng** [comment]
所以模型映射功能能解决问题么？

**Comment by mmwong1984** [comment]
不能，回應和返回都是跟openai一樣的

**Comment by mmwong1984** [comment]
模型映射怎麼用

**Comment by mmwong1984** [comment]
希望能盡快解決

**Comment by songquanpeng** [comment]
这是一个重复的 issue #276

**Comment by twpengit** [comment]
> 所以模型映射功能能解决问题么？

请问模型映射功能有使用说明吗?
