### ISSUE TITLE
按照步骤在Zeabur部署后无法访问

### ISSUE THREAD

**Issue by mu-bibai** [songquanpeng/one-api#248]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
按照步骤在Zeabur部署后无法访问
**复现步骤**
以下是build logs
11:58:18[3/3] STEP 12/12: ENTRYPOINT ["/one-api"]

11:58:18[3/3] COMMIT asia-east1-docker.pkg.dev/zeabur-prod/zeabur-images/service-64a4e2dcf3520b9c04e68a4d:deployment-64a4e75f1042ca2ae10fab89

11:58:18--> Pushing cache [asia-east1-docker.pkg.dev/zeabur-prod/zeabur-images/service-64a4e2dcf3520b9c04e68a4d]:ad98abe24e5888506ca50d143bf39b4211024c4aea13cc34b01722d8be72680d

11:58:19--> 04e0ac177378

11:58:19Successfully tagged asia-east1-docker.pkg.dev/zeabur-prod/zeabur-images/service-64a4e2dcf3520b9c04e68a4d:deployment-64a4e75f1042ca2ae10fab89

11:58:3204e0ac1773784cbca208ded9297bc698fd6adc1078b0eadbb491076cf581784c
**预期结果**
Runtime logs

11:58:37[SYS] 2023/07/05 - 03:58:37 | One API  started 

11:58:37[SYS] 2023/07/05 - 03:58:37 | using MySQL as database 

11:58:37[SYS] 2023/07/05 - 03:58:37 | database connected 

11:58:372023/07/05 03:58:37 /build/model/main.go:63 SLOW SQL >= 200ms

11:58:37[263.701ms] [rows:0] CREATE TABLE `channels` (`id` bigint AUTO_INCREMENT,`type` bigint DEFAULT 0,`key` varchar(191) NOT NULL,`status` bigint DEFAULT 1,`name` varchar(191),`weight` bigint,`created_time` bigint,`test_time` bigint,`response_time` bigint,`base_url` longtext,`other` longtext,`balance` double,`balance_updated_time` bigint,`models` longtext,`group` varchar(32) DEFAULT 'default',`used_quota` bigint DEFAULT 0,`model_mapping` varchar(1024) DEFAULT '',PRIMARY KEY (`id`),INDEX `idx_channels_key` (`key`),INDEX `idx_channels_name` (`name`))

11:58:38[SYS] 2023/07/05 - 03:58:38 | database migrated 

11:58:382023/07/05 03:58:38 /build/model/main.go:16 record not found

11:58:38[14.244ms] [rows:0] SELECT * FROM `users` ORDER BY `users`.`id` LIMIT 1

11:58:38[SYS] 2023/07/05 - 03:58:38 | no user exists, create a root user for you: username is root, password is 123456 

11:58:38[SYS] 2023/07/05 - 03:58:38 | REDIS_CONN_STRING not set, Redis is not enabled 

12:29:46[SYS] 2023/07/05 - 04:29:46 | One API  started 

12:29:46[SYS] 2023/07/05 - 04:29:46 | using MySQL as database 

12:29:46[SYS] 2023/07/05 - 04:29:46 | database connected 

12:29:46[SYS] 2023/07/05 - 04:29:46 | database migrated 

12:29:46[SYS] 2023/07/05 - 04:29:46 | REDIS_CONN_STRING not set, Redis is not enabled 

12:34:18[SYS] 2023/07/05 - 04:34:18 | One API  started 

12:34:18[SYS] 2023/07/05 - 04:34:18 | using MySQL as database 

12:34:18[SYS] 2023/07/05 - 04:34:18 | database connected 

12:34:19[SYS] 2023/07/05 - 04:34:19 | database migrated 

12:34:19[SYS] 2023/07/05 - 04:34:19 | REDIS_CONN_STRING not set, Redis is not enabled 
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/69948498/5db308e4-b147-490c-a4aa-f557b7ff2245)
![image](https://github.com/songquanpeng/one-api/assets/69948498/9acc0813-bb7f-4d79-9e72-2d7a60a064d3)
变量已定义端口为3000

如果没有的话，请删除此节。

**Comment by LeslieLeung** [comment]
设置完变量后需要redeploy才能生效。

**Comment by mu-bibai** [comment]
redeploy后可以访问。
挺奇怪的，我修改变量后确实重新部署过，但是再次重新部署就好了，谢谢。
