### ISSUE TITLE
无效的请求头：http2: invalid Connection request header

### ISSUE THREAD

**Issue by luke-zhang580** [songquanpeng/one-api#25]
{"error":{"message":"Get \"https://api.openai.com/v1/models\": http2: invalid Connection request header: [\"upgrade\"]","type":"one_api_error"}}

**Comment by songquanpeng** [comment]
请问用的是最新版本吗？这个问题现在已经不会出现才对。

**Comment by luke-zhang580** [comment]
使用的是一小时之前发布的那个镜像，上午还可以的。

**Comment by songquanpeng** [comment]
好的，我检查一下。

**Comment by luke-zhang580** [comment]
我的配置：location / {
      proxy_http_version 1.1;
      proxy_pass http://ws;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header  X-Real-IP  $remote_addr;
      proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;
      proxy_buffering off;
      client_max_body_size  64m;
    }

**Comment by songquanpeng** [comment]
可以试一下删掉：`proxy_set_header Connection upgrade;` 吗？

**Comment by luke-zhang580** [comment]
试过，还是同样的错

在 2023年4月26日星期三，JustSong ***@***.***> 写道：

**Comment by songquanpeng** [comment]
这是我的完整配置，我测试了一下线上环境，没有复现该问题：
```
server{
        server_name openai.justsong.cn;

        location / {
                # gzip off;
                client_max_body_size  64m;
                proxy_http_version 1.1;
                proxy_pass http://localhost:3000;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header Accept-Encoding gzip;
                # chunked_transfer_encoding off;
                # proxy_cache off;
                proxy_buffering off;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/openai.justsong.cn/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/openai.justsong.cn/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

Nginx 版本：`nginx version: nginx/1.18.0 (Ubuntu)`

如果方便的话希望可以用我的配置再试一下。

**Comment by songquanpeng** [comment]
如果问题依旧存在，欢迎重开。
