### ISSUE TITLE
AutoGPT 上代理失败

### ISSUE THREAD

**Issue by liaokaime** [songquanpeng/one-api#250]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√ ] 我已确认我已升级到最新版本
+ [√] 我已完整查看过项目 README，尤其是常见问题部分
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当我尝试使用autogpt项目并配置OpenAI API时，我无法通过该代理项目正常访问OpenAI。我得到的错误消息是"openai.error.AuthenticationError: Incorrect API key provided: sk-jN22x***************************************06D5. You can find your API key at https://platform.openai.com/account/api-keys.". 我已经检查过我提供的API密钥，并且我确定这是正确的。

**复现步骤**
在autogpt项目中配置OpenAI API
配置如下：
OPENAI_API_KEY=sk-jN22x***************************************06D5
OPENAI_API_BASE_URL=https://oioi.cc
运行项目，收到错误消息"openai.error.AuthenticationError: Incorrect API key provided: sk-jN22x***************************************06D5"

**预期结果**
正常执行AutoGPT

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/27792976/f9af2081-4b6d-40d4-ae35-220bac437778)

**Comment by songquanpeng** [comment]
密钥错误，要么你的渠道配置有问题，要么你没有走oneapi的中转
