### ISSUE TITLE
注册邮箱验证 INVALID HEADER   Missing required header field: "Date"

### ISSUE THREAD

**Issue by zcsos** [songquanpeng/one-api#251]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

注册邮箱验证时发送的邮件无法成功递出：

The message WAS NOT relayed to:
 <[xxx@xxx.com](mailto:xxxl@xxx.com)>:
  555 5.5.0 Bounce, id=555555-02 - BAD HEADER

 INVALID HEADER   Missing required header field: "Date"

注：自建邮箱
oneapi：v0.4.9-alpha.5 
docker部署

**复现步骤**
<img src="https://share.onesec.fun/share/202307081015742.png"/>
<img src="https://share.onesec.fun/share/202307081016512.png"/>
<img src="https://share.onesec.fun/share/202307081016194.png"/>

邮件内容：
The message WAS NOT relayed to:
 <[xxx@xxxx.com]>:
  554 5.6.0 Bounce, id=557641-04 - BAD HEADER

This nondelivery report was generated by the program amavisd-new at host
[mail.xxxx.com]. Our internal reference code for your message is
557641-04/KqxFuByb-N85

INVALID HEADER

 Missing required header field: "Date"

Return-Path: <[xxx@xxxx.com]>
From: OneAPI<[xxx@xxxx.com]
Subject: =?UTF-8?B?TW96emll6Yd+B6YKu5Lu2?asnmnqwnads=

Reporting-MTA: dns; [mail.xxxx.com](http://mail.xxxx.com/)
Received-From-MTA: dns; [mail.xxxx.com](http://mail.xxxx.com/) ([127.0.0.1])
Arrival-Date: Sat,  8 Jul 2023 02:12:39 +0000 (UTC)

Original-Recipient: rfc822;[test@xxxx.com]
Final-Recipient: rfc822;[xxx@xxxx.com]
Action: failed
Status: 5.6.0
Diagnostic-Code: smtp; 554 5.6.0 Bounce, id=557641-04 - BAD HEADER
Last-Attempt-Date: Sat,  8 Jul 2023 02:12:39 +0000 (UTC)
Final-Log-ID: 557641-04/KqxFuCyb-N85

**预期结果**

**Comment by zcsos** [comment]
> 没提供复现过程，怎么测试？

抱歉，已更新邮箱配置及注册过程
配置完成后，所有注册邮件都无法成功发出

**Comment by songquanpeng** [comment]
目前暂不考虑支持自建邮件服务，推荐使用现成的服务

**Comment by tiefengsun** [comment]
自建的邮件服务器目前还不支持吗？

**Comment by YOMIkio** [comment]
> 自建的邮件服务器目前还不支持吗？

pr #742 已经提交，修复了这个
