### ISSUE TITLE
非 Stream 返回时，没有配置 Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#252]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
非 Stream 返回时，没有配置 Access-Control-Allow-Origin

![b4f606f1bc299a657c497811f00646c](https://github.com/songquanpeng/one-api/assets/50446880/743e098e-278f-497a-9b2f-de9ed6780490)

**复现步骤**

**预期结果**
Access-Control-Allow-Origin = “*”

**Comment by songquanpeng** [comment]
为什么我这里是正常的呢？
![image](https://github.com/songquanpeng/one-api/assets/39998050/49a8ebcb-0b88-4d9f-bc36-82c8c823a1fd)

**Comment by c121914yu** [comment]
确实无法复现。下次出现在看了
