### ISSUE TITLE
有没办法增加bing、midjourney相关代理项目的接口

### ISSUE THREAD

**Issue by mwnu** [songquanpeng/one-api#254]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by songquanpeng** [comment]
如果有官方 API，会考虑支持。
