### ISSUE TITLE
可以添加pengzhile/pandora的这个吗？

### ISSUE THREAD

**Issue by happytimek002** [songquanpeng/one-api#256]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by songquanpeng** [comment]
不可以，除非其支持标准的 OpenAI API。

**Comment by xhacker5000** [comment]
在对面的issue里好像有人成功接入了
https://github.com/pengzhile/pandora/issues/1084
