### ISSUE TITLE
请给出在配合ChatGPT Next Web使用时的具体操作步骤

### ISSUE THREAD

**Issue by C-Dragon8** [songquanpeng/one-api#257]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

您好！在配合ChatGPT Next Web使用时应该如何通过docker进行部署呢？BASE_URL应当如何设置？API-KEY是不是复制自己新建的令牌就可以？

docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY="sk-xxxx" \
   -e CODE="页面访问密码" \
   --net=host \
   -e PROXY_URL="http://127.0.0.1:7890" \
   yidadaa/chatgpt-next-web

通过ChatGPT Next Web给出的部署方法，并将PROXY_URL修改为了自己的地址、用户名及密码，仍然提示错误。

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/6ae86d80-a585-4d7d-94f8-092558d5464e)

**Comment by C-Dragon8** [comment]
好的，那么API-KEY是不是复制自己新建的令牌就可以？

**Comment by songquanpeng** [comment]
我是感觉你可以先试一下再问问题

**Comment by C-Dragon8** [comment]
试了，仍然报错

**Comment by songquanpeng** [comment]
报错应该贴出报错信息

**Comment by C-Dragon8** [comment]
已部署成功，多谢！

**Comment by songquanpeng** [comment]
不妨说一下是怎么解决的，方便后面的人参考

**Comment by C-Dragon8** [comment]
报错的原因：在ChatGPT Next Web的设置页面，我在“接口地址”处一直用的你的部署地址`https://openai.justsong.cn`。
我心里一直默认这样部署是正确的（可能是“使用方法”那一节看太快了），试了几次我才发现这样不符合逻辑，是错误的。所以我把接口地址改为了我自己的地址，API KEY也是自己地址生成的令牌，这样才正确。
