### ISSUE TITLE
令牌混乱

### ISSUE THREAD

**Issue by wzunjh** [songquanpeng/one-api#260]
多个用户同时操作时，令牌会显示其他用户名下的令牌

**Comment by songquanpeng** [comment]
额，复现过程呢，结果截图呢

**Comment by wzunjh** [comment]
普通用户登录之后如果管理员在线的话可以直接看到管理员的令牌
普通用户刷新以后即可看到管理员名下的令牌，如图
![T$UI6}Z~K9}3Y8 AS1`DDQL](https://github.com/songquanpeng/one-api/assets/120587094/77c16f01-a52e-429f-ad4f-4d724a4e6934)
管理员的令牌
![image](https://github.com/songquanpeng/one-api/assets/120587094/3d6d9e97-81ac-4362-adba-70ae95b3939f)

**Comment by wzunjh** [comment]
管理员刷新甚至可以看到其他另一个用户名下的令牌，自己的令牌消失了
![FUJKW`XKWG@~H1ME8NBSJB9](https://github.com/songquanpeng/one-api/assets/120587094/0c312540-4ca2-4db4-83dc-20e4c1e6a5f4)

**Comment by wzunjh** [comment]
解决了，关闭nginx反向代理的缓存就可以了
