### ISSUE TITLE
zeabur部署后出现：Or this service is not listening on the port of environment variable $PORT. Please contact the service owner to fix this issue.

### ISSUE THREAD

**Issue by Newaiguy** [songquanpeng/one-api#267]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by ErikaAlkane** [comment]
我也有同样的问题。我的PORT值是3000
![Snipaste_2023-07-11_09-54-55](https://github.com/songquanpeng/one-api/assets/126934423/11bcbf00-f2e7-41ad-aa2e-441a694dde6c)

**Comment by songquanpeng** [comment]
服务会监听 PORT 环境变量。

Zeabur 部署方式是别人 PR 的，我自己没用过，根据已有 issue 自行检查或群里问。

**Comment by surfboy2000** [comment]
0.5版本遇到这个问题，之前没有
