### ISSUE TITLE
请求兼容 /v1/engines/text-embedding-ada-002/embeddings 

### ISSUE THREAD

**Issue by axdlee** [songquanpeng/one-api#269]
**功能描述**
使用langchain的OpenAIEmbeddings时，如果使用one-api的域名作为openai_api_base则会一直报错API not Found /v1/engines/text-embedding-ada-002/embeddings ,如果 使用官方的openai_api_base是可以正常使用的。
好像官方会对这个已弃用的端口（/v1/engines/text-embedding-ada-002/embeddings）进行向前兼容。
参考：
https://github.com/openai/openai-python/issues/397
https://github.com/abetlen/llama-cpp-python/issues/136

**Comment by adevjoe** [comment]
确实，我这也有这种情况

**Comment by songquanpeng** [comment]
既然官方做了兼容，那确实有必要，#222 已重开，此 issue 重复故关闭

**Comment by songquanpeng** [comment]
相关 PR 已合并。
