### ISSUE TITLE
支持 token 类型的渠道

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#27]
在渠道中使用token，对外仍提供令牌，新建一个令牌指向token渠道。
使用token需要unofficial api。
一个主用token的项目可以用来参考：https://github.com/pengzhile/pandora

**Comment by songquanpeng** [comment]
这个有点意思，可以考虑支持。

**Comment by JeazW** [comment]
另外使用token相当于使用网页版，回答的质量略高于api

**Comment by songquanpeng** [comment]
该渠道意义有限，没办法并发且可靠度不足，暂不考虑。
