### ISSUE TITLE
增加 账号封禁 触发禁用KEY条件

### ISSUE THREAD

**Issue by fengjisheng** [songquanpeng/one-api#271]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我已完整查看过项目 README，尤其是常见问题部分
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

目前看接口触发自动禁用的条件是"insufficient_quota"  和 "invalid_api_key"
希望可以再加一个"account_deactivated"

账号已封禁的提示: 
code: account_deactivated
message: This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.

**Comment by songquanpeng** [comment]
好的

**Comment by ohblue** [comment]
请增加一个触发条件：当账户状态是deactivated的时候
测试结果返回错误如下：
```
{
    "message": "type invalid_request_error, code account_deactivated, message Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com.",
    "success": false,
    "time": 0.073
}
```

**Comment by kaqijiang** [comment]
groq 组织被封 希望增加禁用渠道
错误：status code 400: Organization has been restricted. Please reach out to support if you believe this was in error.
