### ISSUE TITLE
Azure gpt-35-turbo-16k 渠道测试报错

### ISSUE THREAD

**Issue by Plandres** [songquanpeng/one-api#273]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Azure OpenAI已更新gpt-35-turbo-16k模型，和OpenAI官方名称相比同样少个小数点，添加渠道时会报错，我已确认“模型部署名称和模型名称保持一致”

错误：type , code DeploymentNotFound, message The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

**Comment by songquanpeng** [comment]
周末处理

**Comment by songquanpeng** [comment]
群友反馈正常，如有问题群里讨论看一下是不是配置问题。
