### ISSUE TITLE
支持 ChatGLM2 API

### ISSUE THREAD

**Issue by pepsigold** [songquanpeng/one-api#274]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
清华开源了https://github.com/THUDM/ChatGLM2-6B 模型，但是他的api是没有任何鉴权的，所以放在公网上，或者与小伙伴一起使用有一些风险，故，能不能集合chatglm2本地模型，通过您这套api，分发给小伙伴们使用。这样既可以保证鉴权使用，又可以有效管理key。

**应用场景**
基于chatglm的文本生成及对话。
因为我们学校不允许用代理出国，怕触及校规，所以我们自己部署了chatglm使用。

感谢分享这么棒的应用。

**Comment by songquanpeng** [comment]
会支持的，如果方便的话可以给出 API 文档 & 链接，以及测试环境，这将加快适配。

**Comment by songquanpeng** [comment]
已经支持，
![image](https://github.com/songquanpeng/one-api/assets/39998050/2ae7f66e-cead-4a8a-9301-2c6bf932e0a5)

**Comment by pepsigold** [comment]
> 已经支持， ![image](https://user-images.githubusercontent.com/39998050/253731235-2ae7f66e-cead-4a8a-9301-2c6bf932e0a5.png)
接入本地的chatglm2 ，接口是官方 openai_api.py ，这个该怎么接入啊？谢谢
https://github.com/THUDM/ChatGLM2-6B/blob/main/openai_api.py
