### ISSUE TITLE
支持自定义模型名称

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#276]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
目前只能选择 openai 的几个模型，希望加入一个自定义模型名。
比如我现在已经做好一个 chatglm 的接口，希望直接接入进来，就可以直接写 chatglm。

目前仅能通过找一个text-ada-001之类没用过的模型做映射，有点奇怪。

**应用场景**

**Comment by songquanpeng** [comment]
Okay，周末我看一下怎么实现好一些

**Comment by songquanpeng** [comment]
已经支持。

**Comment by mrhaoji** [comment]
> 好像没有啊 @songquanpeng 版本：v0.4.9

升到 [v0.4.10-alpha.5](https://github.com/users/songquanpeng/packages/container/one-api/109842512?tag=v0.4.10-alpha.5)
