### ISSUE TITLE
stream 模式下，字符串的兼容性问题。

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#277]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
对于 stream 响应的容错性不足，对于下图的 stream 响应似乎会报错：[SYS] 2023/07/12 - 15:58:34 | error unmarshalling stream response: invalid character 'd' after top-level value 

![image](https://github.com/songquanpeng/one-api/assets/50446880/a2360d37-e370-4685-a1eb-a5adc1e83c4d)
![image](https://github.com/songquanpeng/one-api/assets/50446880/f11a5f4b-29d0-48c7-8ccd-43f0cbacb79d)

**复现步骤**

**预期结果**

应该可以正常解析，没有 content 字段的内容直接忽略。

**相关截图**
如果没有的话，请删除此节。

**Comment by mrhaoji** [comment]
我这边也能复现这个问题，不过为什么 delta 里面偶尔会出现没有 content 键的情况呢？

**Comment by songquanpeng** [comment]
没有 content 也不应该反序列化错误才对

**Comment by mrhaoji** [comment]
我还发现一种情况会返回 invalid character 'd' after top-level value 这个错误

就是上游渠道那边在下游传参是 stream: false 非流的时候，进行了流式返回，就也会有这个错误

**Comment by mrhaoji** [comment]
官方的我都遇到过，只是再次请求又好了

**Comment by songquanpeng** [comment]
实测没有 content 并不会导致序列化错误，问题出在其他地方。

**Comment by songquanpeng** [comment]
我今天添加 ChatGLM2 支持的时候也发现了这个问题，目前应该已经解决，问题在于有些实现的分隔符不是两个换行，而是一个，就会导致解析出错，现在 One API 已经对此做了兼容处理。

**Comment by c121914yu** [comment]
> 我今天添加 ChatGLM2 支持的时候也发现了这个问题，目前应该已经解决，问题在于有些实现的分隔符不是两个换行，而是一个，就会导致解析出错，现在 One API 已经对此做了兼容处理。

是的。sse中，应该是先进行2个换行拆分，再进行1个换行。

**Comment by songquanpeng** [comment]
目前的实现是直接用一个换行进行拆分，然后丢弃掉无效的部分。

**Comment by c121914yu** [comment]
> 目前的实现是直接用一个换行进行拆分，然后丢弃掉无效的部分。

感觉可能会埋坑。
标准sse中是包括event name和data。最好还是能完整解析，防止以后会出现event name的情况。

fastgpt 中是先对\n\n进行拆分，然后再对\n进行拆分，从中解析name和data进行完整转发。(name可以不存在)

**Comment by songquanpeng** [comment]
如果 OpenAI 的返回体格式变了，那到时候再处理吧，现在应该是没什么问题的
