### ISSUE TITLE
支持保存会话信息

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#28]
如果做的话，至少需要两张表，一个聊天室表，一个聊天内容表。
数据库可能也要换。

**Comment by songquanpeng** [comment]
聊天室指的是什么？如果只是想保存用户的请求数据和返回内容的话，需要一个会话表和一个消息表。

**Comment by JeazW** [comment]
就是这个意思哈哈，我说的大白话，行话应该就是会话表和消息表了😅

**Comment by songquanpeng** [comment]
现在是已经支持 MySQL 的状态，配置 `SQL_DSN` 环境变量可以指定使用哪一个数据库，详见 README。
