### ISSUE TITLE
针对用户组功能的增强

### ISSUE THREAD

**Issue by 6bf3803cb456** [songquanpeng/one-api#280]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
对用户组的完全自定义（能覆盖默认的default、vip、svip分组），可以配合倍率精细控制用户组属性区别，并且支持通过消费累计或兑换码提升用户组。
**应用场景**
自定义用户组：将默认用户组定义为用户、会员、高级会员、超级会员、合作商、管理员等，替换原有用户组，配合分组倍率设定。
用户组提升：用户消费累计10w令牌（或者货币）后升级成会员，会员消费15w令牌（或者货币）后高级会员，以此类推。可以一次性通过兑换码提升会员组，兑换码可以设定时效（按天、周、月、季、年等或者终身）。

**Comment by songquanpeng** [comment]
可以使用系统访问 token 自行实现。

**Comment by lipanpan-hub** [comment]
我还以为可以自己创建用户组 我在运营设置里面通过 通过修改分组倍率字符串 搞一堆用户组 结果出现一堆问题 gg了
