### ISSUE TITLE
更新0.4.9后/v1/embeddings 接口无法使用了

### ISSUE THREAD

**Issue by hbytw** [songquanpeng/one-api#282]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
更新0.4.9后/v1/embeddings,
**复现步骤**
0.4.9访问此接口直接显示页面。
**预期结果**
0.4.8访问此接口显示{"error":{"message":"API not found: GET:/v1/embeddings","type":"one_api_error","param":"","code":"api_not_found"}}
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/43083918/5193091b-e18c-4426-80c9-255f261cd509)

如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
我看看，我记得我测试过的



---Original---
From: ***@***.***&gt;
Sent at: 2023年7月15日(Sat) Evening8:01
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 更新0.4.9后/v1/embeddings 接口无法使用了 (Issue #282)




 
例行检查
  
 我已确认目前没有类似 issue
 
[ x] 我已确认我已升级到最新版本
 
[ x] 我已完整查看过项目 README，尤其是常见问题部分
 
[x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
 
[x ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
问题描述
 更新0.4.9后/v1/embeddings,
 复现步骤
 0.4.9访问此接口直接显示页面。
 预期结果
 0.4.8访问此接口显示{"error":{"message":"API not found: GET:/v1/embeddings","type":"one_api_error","param":"","code":"api_not_found"}}
 相关截图
 
 
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
这个接口直接访问就是这样的，需要是 POST 方法。

我刚刚测试了一下，是 Okay 的：
![image](https://github.com/songquanpeng/one-api/assets/39998050/9b222c9b-aea2-4ab5-ae05-6b6b71534700)

**Comment by hbytw** [comment]
那就神奇了  我在试试
