### ISSUE TITLE
OhMyGPT无法使用啊

### ISSUE THREAD

**Issue by zq535228** [songquanpeng/one-api#283]
![image](https://github.com/songquanpeng/one-api/assets/45892397/0802433d-f714-4b4b-abc7-1fbe50f30775)

![image](https://github.com/songquanpeng/one-api/assets/45892397/53029360-4b59-409d-bdf1-b59b0968ed9f)

**Comment by songquanpeng** [comment]
尚未实现是对方没有额度查询接口。
