### ISSUE TITLE
支持智谱 AI

### ISSUE THREAD

**Issue by ccyuvin** [songquanpeng/one-api#289]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
智谱AI的API文档地址：
https://open.bigmodel.cn/doc/api

**应用场景**
ChatGLM直接通过API接口就能调用，价格还算可以接受。个人用户直接注册也可以获得API权限，希望能支持国产大模型发展。

<html>
<body>

模型 | 说明 | 单价
-- | -- | --
ChatGLM-Pro | 适用于对知识量、推理能力、创造力要求较高的场景，比如广告文案、小说写作、知识类写作、代码生成等。 | 0.01元 / 千tokens
ChatGLM-Std | 适用于需要兼顾效果和成本的场景，比如新闻写作、企业内部知识库、摘要生成、垂直检索等。 | 0.005元 / 千tokens
ChatGLM-Lite | 适用于对反应速度和成本比较敏感，且任务较为简单的场景，比如聊天、客服、分类、提取等。 | 0.002元 / 千tokens

</body>
</html>

**Comment by lipanpan-hub** [comment]
![Snipaste_2023-07-18_11-16-32](https://github.com/songquanpeng/one-api/assets/47287977/7dc99643-6f8c-40fc-b7e6-a28ff9850f19)

确定这个东西能用吗?

**Comment by lipanpan-hub** [comment]
我又试了一下确实可以了 还挺不错的  刚才应该是我刚注册系统没反应过来

**Comment by songquanpeng** [comment]
这个在计划内

**Comment by songquanpeng** [comment]
已经支持

**Comment by zkewind** [comment]
但是还不支持embedding接口对吧？什么时候能够支持呢？
