### ISSUE TITLE
使用 MySQL 搭建报错

### ISSUE THREAD

**Issue by ilay1678** [songquanpeng/one-api#29]
[SYS] 2023/04/27 - 01:46:40 | One API v0.1.5 started 
[FATAL] 2023/04/27 - 01:46:40 | [Error 1170: BLOB/TEXT column 'key' used in key specification without a key length] 

2023/04/27 01:46:40 [31;1m/build/model/main.go:61 [35;1mError 1170: BLOB/TEXT column 'key' used in key specification without a key length
[0m[33m[4.126ms] [34;1m[rows:0][0m CREATE TABLE `tokens` (`id` bigint AUTO_INCREMENT,`user_id` bigint,`key` longtext,`status` bigint DEFAULT 1,`name` varchar(191),`created_time` bigint,`accessed_time` bigint,`expired_time` bigint DEFAULT -1,`remain_times` bigint DEFAULT 0,`unlimited_times` boolean DEFAULT false,PRIMARY KEY (`id`),UNIQUE INDEX `idx_tokens_key` (`key`),INDEX `idx_tokens_name` (`name`))

**Comment by ilay1678** [comment]
看到刚提交的修复了

**Comment by songquanpeng** [comment]
好的，不过并没有完整测试，期待反馈。

**Comment by ilay1678** [comment]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = ? ORDER BY tokens.id LIMIT 1' at line 1
SELECT * FROM `tokens` WHERE key = '123456' ORDER BY `tokens`.`id` LIMIT 1

**Comment by songquanpeng** [comment]
Okay，收到

**Comment by songquanpeng** [comment]
已推送，`v0.1.6-alpha.1`。

我现在手头没有 MySQL 环境，只在 SQLite 测试了一下，如果方便的话麻烦测试一下，谢谢。

**Comment by songquanpeng** [comment]
另外，貌似你填成令牌的名字而非 key 了，这个 key 都是生成的 UUID 随机字符串。

不过和 MySQL 报错没有关系。

**Comment by ilay1678** [comment]
> 另外，貌似你填成令牌的名字而非 key 了，这个 key 都是生成的 UUID 随机字符串。
> 
> 不过和 MySQL 报错没有关系。

123456是我随机改的 
![1EF37E2F](https://user-images.githubusercontent.com/7021399/234750473-a3d12467-7269-4422-ae7b-935d322b5766.png)

**Comment by songquanpeng** [comment]
哈哈哈，因为之前碰到两个人把 key 填成名字了。

**Comment by ilay1678** [comment]
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = ? ORDER BY tokens.id LIMIT 1' at line 1 SELECT * FROM `tokens` WHERE key = '123456' ORDER BY `tokens`.`id` LIMIT 1

经测试已修复

**Comment by songquanpeng** [comment]
谢谢，原因在于 `key` 是 MySQL 的关键字，而 GORM 对此没有任何警告和特殊处理操作。
