### ISSUE TITLE
密码重置链接点击无反应

### ISSUE THREAD

**Issue by JC0v0** [songquanpeng/one-api#290]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
![QQ图片20230717175322](https://github.com/songquanpeng/one-api/assets/108552928/a1423530-ddde-48b6-bd63-73b8278f8758)

如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
你好歹把链接贴出来啊。。。



---Original---
From: ***@***.***&gt;
Sent at: 2023年7月17日(Mon) PM5:54
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 密码重置链接点击无反应 (Issue #290)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，尤其是常见问题部分
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
问题描述
 
复现步骤
 
预期结果
 
相关截图
 
 
如果没有的话，请删除此节。

**Comment by JC0v0** [comment]
> 

这没链接啊，这“此处”点着没反应

**Comment by JC0v0** [comment]
这是登陆界面的重置密码功能

**Comment by songquanpeng** [comment]
盲猜你后台没配置域名，我指的是邮件这个链接的地址贴出来

**Comment by JC0v0** [comment]
> 盲猜你后台没配置域名，我指的是邮件这个链接的地址贴出来

已解决，原因是未正确配置域名
