### ISSUE TITLE
渠道检测和自动禁用有问题

### ISSUE THREAD

**Issue by woodchen-ink** [songquanpeng/one-api#292]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
开启渠道自动检测，和检测失败自动禁用，会经常因为官方问题错误禁用。
例如：
1. 通道「4」（#3）已被禁用，原因：type server_error, code , message That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID db0b90f2f2bbdxxxxxxxx in your message.)
2. 通道「5刀」（#90）已被禁用，原因：invalid character 'A' looking for beginning of value
**复现步骤**

**预期结果**
进行返回错误判断，以上错误情况不会禁用渠道。

**Comment by songquanpeng** [comment]
周末处理
