### ISSUE TITLE
宝塔部署试了好久一直提示mysql链接失败

### ISSUE THREAD

**Issue by danggerenba** [songquanpeng/one-api#296]
<img width="1133" alt="image" src="https://github.com/songquanpeng/one-api/assets/119066997/3b3bf9f5-bfd6-452b-bea4-f8905b5da457">
<img width="795" alt="image" src="https://github.com/songquanpeng/one-api/assets/119066997/12612a75-a195-41e5-b07b-144dd0d3daa7">
容器能运行 但对应的myql里没有数据

**Comment by songquanpeng** [comment]
使用上的问题应该去群里问，这不是 bug
