### ISSUE TITLE
使用https://xxx.xxx/api/openai 这样的接口时候会报错  

### ISSUE THREAD

**Issue by luxl-1379** [songquanpeng/one-api#298]
都是报key不正确，好像默认了官方的，type invalid_request_error, code invalid_api_key, message Incorrect API key provided: 1. You can find your API key at https://platform.openai.com/account/api-keys

**Comment by songquanpeng** [comment]
报错很明显了，检查你的渠道密钥配置

**Comment by luxl-1379** [comment]
是的 因为没有设置密钥 密钥为空时使用正常，添加渠道时候密钥必须要填写 可以设置密钥非必填吗

**Comment by songquanpeng** [comment]
密钥为空怎么请求上游服务？

**Comment by luxl-1379** [comment]
有挺多 就是白嫖的一些QAQ， 比如 https://chat-gpt-next-web-ottaliam.vercel.app/api/openai
这地址直接不需要密钥可以使用 填上密钥就报错了
