### ISSUE TITLE
修改用户组不生效

### ISSUE THREAD

**Issue by AiZyc** [songquanpeng/one-api#302]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
后台修改用户组不生效或偶尔生效。
疑似缓存问题导致。

**复现步骤**
环境：docker部署，外接MySQL，开启了Redis，后台修改了用户组后，没有生效，重启容器后生效。

**预期结果**
修改后根据缓存同步时间生效。

**Comment by songquanpeng** [comment]
Okay

**Comment by GFDYMS** [comment]
不只是这个问题，貌似缓存机制有问题。修改渠道或者令牌后，redis缓存一直不刷新

**Comment by songquanpeng** [comment]
开了定期刷新么

**Comment by GFDYMS** [comment]
开了。SYNC_FREQUENCY=60

**Comment by songquanpeng** [comment]
有些缓存是硬编码的过期时间（1 个小时），现在已经修改成跟随 SYNC_FREQUENCY 了
