### ISSUE TITLE
加个functioncall功能吧,  别人起的gpt4镜像站都没有这功能

### ISSUE THREAD

**Issue by Naist4869** [songquanpeng/one-api#303]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
https://platform.openai.com/docs/api-reference/chat/create#chat/create-function_call
**应用场景**
不搞他们也没有这功能卖.大佬更新了小站才能用😭
https://www.ai-buy.store 
https://openai.yangcs.net 
https://api.rcouyi.com

**Comment by songquanpeng** [comment]
重复 #160

**Comment by Naist4869** [comment]
// https://platform.openai.com/docs/api-reference/chat

type GeneralOpenAIRequest struct {
	Model       string    `json:"model,omitempty"`
	Messages    []Message `json:"messages,omitempty"`
	Prompt      any       `json:"prompt,omitempty"`
	Stream      bool      `json:"stream,omitempty"`
	MaxTokens   int       `json:"max_tokens,omitempty"`
	Temperature float64   `json:"temperature,omitempty"`
	TopP        float64   `json:"top_p,omitempty"`
	N           int       `json:"n,omitempty"`
	Input       any       `json:"input,omitempty"`
	Instruction string    `json:"instruction,omitempty"`
	Size        string    `json:"size,omitempty"`
}
代码里没找到哪个地方有添加functions 和function_call字段

**Comment by songquanpeng** [comment]
还没实现呢，我指的是 issue 重复
