### ISSUE TITLE
百度文心一言

### ISSUE THREAD

**Issue by haihaimx** [songquanpeng/one-api#305]
例行检查

[ 1] 我已确认目前没有类似 issue
[1 ] 我已确认我已升级到最新版本
[ 1] 我已完整查看过项目 README，尤其是常见问题部分
[ 1] 我理解并愿意跟进此 issue，协助测试和提供反馈
[ 1] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
问题描述
百度的弄完会报这个.
{
"error": { “错误”：{
"message": "the length of messages must be an odd number",
“消息”： “消息的长度必须是奇数”，
"type": "baidu_error", “类型”： “baidu_error”，
"param": "", “参数”： “”，
"code": 336003 “代码”：336003
}
}
复现步骤
已更新至最新版本 系统 ubuntu-22.04 docker 部署和二进制部署都试过 都是这样 获取的access_token应该也是正确的 下边测试了
预期结果

![14d9e492d1abfd47cc44740d121bc58](https://github.com/songquanpeng/one-api/assets/82726312/4f498933-1198-4095-a9b9-03010cddf71d)
![836b7270aac7e1e421e9dfe013d9e0c](https://github.com/songquanpeng/one-api/assets/82726312/5641d26e-b6c2-4a6c-987e-c23541866b65)

**Comment by songquanpeng** [comment]
贴出来你的请求体

**Comment by haihaimx** [comment]
{"messages":[{"role":"system","content":"\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: ERNIE-Bot-turbo\nCurrent time: 2023/7/23 10:36:24\n"},{"role":"user","content":"你好"}],"stream":true,"model":"ERNIE-Bot-turbo","temperature":0.5,"presence_penalty":0,"frequency_penalty":0,"top_p":1}

是这个吗

**Comment by haihaimx** [comment]
大佬要不我发您地址看看

**Comment by songquanpeng** [comment]
不能有这个 system

**Comment by haihaimx** [comment]
还真是
![微信截图_20230723104220](https://github.com/songquanpeng/one-api/assets/82726312/502209d5-3167-4212-bc8d-d037dd576bd6)

**Comment by haihaimx** [comment]
大佬这个怎么解决啊

**Comment by songquanpeng** [comment]
客户端取消注入系统 prompt

**Comment by haihaimx** [comment]
好嘞好嘞谢谢！！！！1！
