### ISSUE TITLE
Linux 部署报错：PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows

### ISSUE THREAD

**Issue by songquanpeng** [songquanpeng/one-api#32]
作为新手想用这个项目练手一下如何部署项目到linux服务器，但是我碰到了一点问题想来请教一下，就是我部署的时候运行./one-api --port 3000 --log-dir ./logs 显示    [root@VM-4-9-centos wwwroot]# ./one-api --port 3000 --log-dir ./logs
-bash: ./one-api: cannot execute binary file   然后我通过  [root@VM-4-9-centos wwwroot]# file ./one-api 发现它显示
./one-api: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows     也就是说生成的二进制文件是只能Windows执行，请问这是什么原因？感谢感谢！

_Originally posted by @Chenm4 in https://github.com/songquanpeng/one-api/issues/11#issuecomment-1525187657_

**Comment by songquanpeng** [comment]
@Chenm4 提问发单独的 issue 哈

**Comment by songquanpeng** [comment]
完整的报错信息发一下，用的是哪一个版本也发一下。

**Comment by songquanpeng** [comment]
我试了一下，运行没有问题，我怀疑你下错文件了，下图中第一个是 Linux x86 架构的可执行文件：
![image](https://user-images.githubusercontent.com/39998050/234815131-3abf2268-e864-4006-a1ae-287c053ce999.png)

**Comment by Chenm4** [comment]
> 我试了一下，运行没有问题，我怀疑你下错文件了，下图中第一个是 Linux x86 架构的可执行文件： ![image](https://user-images.githubusercontent.com/39998050/234815131-3abf2268-e864-4006-a1ae-287c053ce999.png)

噢噢我一开始在Windows中通过源码编译执行了这个命令然后再把项目发送到服务器，应该是在Windows上通过go mod download的时候识别为windows然后我没删除one-api就发到linux上了。
我现在通过release已经部署成功了，感谢感谢
