### ISSUE TITLE
[功能请求+BUG]上游有可能混用API类型和模型（本项目就是如此），因此建议可以指定渠道的API类型

### ISSUE THREAD

**Issue by imldy** [songquanpeng/one-api#321]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

我的上游渠道使用 OpenAI 接口规范下的的`chat/completion`接口提供了Claude网页版模型，名为`claude-2-web`。（上游为OhMyGPT）

目前代码根据模型前缀判断了API类型。正常没问题，但只是上游可能会想这样混用API和模型。

https://github.com/songquanpeng/one-api/blob/bc2f48b1f290ceadcf3edfa99a48aeaedf3a0a3d/controller/relay-text.go#L88-L89

目前通过OpenAI接口提供别的模型的不在少数，甚至本项目就是这样。

因此建议上游渠道可以指定API类型。

**复现步骤**

通过openai接口提供claude开头的自定义模型，即可复现。

**Comment by songquanpeng** [comment]
确实哦，但是也只能通过模型名称来区分，因为不能改 API 的格式。

你有什么具体的想法吗？

**Comment by songquanpeng** [comment]
已修复，已推送 v0.5.1-alpha
