### ISSUE TITLE
调用azure接口返回内容不正确

### ISSUE THREAD

**Issue by miracletiger** [songquanpeng/one-api#323]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
2023-07-25 10:04:00.649 | ERROR    | __main__:<module>:13 - error:HTTP code 200 from API (<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="OpenAI 接口聚合管理，支持多种渠道包括 Azure，可用于二次分发管理 key，仅单可执行文件，已打包好 Docker 镜像，一键部署，开箱即用"/><title>One API</title><script defer="defer" src="/static/js/main.e8559218.js"></script><link href="/static/css/main.44582e8c.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>)

**复现步骤**
import openai
import time
from loguru import logger
# Set OpenAI API key
openai.api_key = "sk-xx"
openai.api_base = "http://xxx:3000"
try:
    response = openai.Completion.create(engine="gpt4", prompt="Hello, GPT-3!", max_tokens=500, temperature=0.5)
    logger.info(response)
    chat_response = response["choices"][0]["text"].strip()
    logger.info("Bot: " + chat_response)
except openai.error.APIError as error:
    logger.error("error:%s" % error)
**预期结果**
输出聊天结果
**相关截图**

如果没有的话，请删除此节。

**Comment by glzjin** [comment]
```python
import openai

openai.api_key = 'sk-****' # 令牌处创建，获得
openai.api_base = 'https://xxxxx/v1'
openai.api_type = 'openai'

messages = [{"role": "user", "content": "你是谁"}]
response = openai.ChatCompletion.create(
    model='gpt-4',
    # model='gpt-4-32k',
    # model='gpt-3.5-turbo',
    # model='gpt-3.5-turbo-16k',
    # model='gpt-3.5-turbo-0301',
    # model='gpt-3.5-turbo-0613',
    # model='gpt-3.5-turbo-16k-0613',
    # model='gpt-4-0613',
    # model='gpt-4-32k-0613',
    # model='gpt-4-0314',
    # model='gpt-4-32k-0314',
    messages=messages
)
print(response['choices'][0]['message']['content'])
```

这样调用，可以。

**Comment by miracletiger** [comment]
>

**Comment by miracletiger** [comment]
感谢答复
import openai
openai.api_key = "sk-xx"
openai.api_base = "http://xx:3000"
openai.api_type = 'openai'
try:
    messages = [{"role": "user", "content": "你是谁"}]
    response = openai.ChatCompletion.create(
        # model='gpt4',
        # model='gpt-4-32k',
        model='gpt-3.5-turbo',
        # model='gpt-3.5-turbo-16k',
        # model='gpt-3.5-turbo-0301',
        # model='gpt-3.5-turbo-0613',
        # model='gpt-3.5-turbo-16k-0613',
        # model='gpt-4-0613',
        # model='gpt-4-32k-0613',
        # model='gpt-4-0314',
        # model='gpt-4-32k-0314',
        messages=messages
    )
    print(response['choices'][0]['message']['content'])
except openai.error.APIError as error:
    logger.error("error:\n%s" % error)

不过这样似乎还是不行 ，还是报错 ”2023-07-25 10:40:53.113 | ERROR    | __main__:<module>:24 - error:
HTTP code 200 from API (<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="OpenAI 接口聚合管理，支持多种渠道包括 Azure，可用于二次分发管理 key，仅单可执行文件，已打包好 Docker 镜像，一键部署，开箱即用"/><title>One API</title><script defer="defer" src="/static/js/main.e8559218.js"></script><link href="/static/css/main.44582e8c.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>)“
我用的是azure的api，不知道是不是哪儿要设置下，接口应该是通的，我用chenzhaoyu94/chatgpt-web部署可以使用，但是直接后端接口调用就报这个错了无法获得返回的结果，我用的jupyter

**Comment by glzjin** [comment]
api_base 后面可有加 v1 ?

**Comment by miracletiger** [comment]
import requests

# 定义 API 地址和请求参数
api_url = "http:// xx:3000/v1/chat/completions"
api_key = "sk-xx"
model = "gpt-3.5-turbo"
prompt = [
    {
        "role": "system",
        "content": "You are a helpful assistant."
    },
    {
        "role": "user",
        "content": "Who won the world series in 2020?"
    },
]
headers = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {api_key}",
}

# 定义请求体
data = {
    "model": model,
    "messages": prompt,
    "temperature": 0.5,
    "max_tokens": 2000,
}

# 发送 POST 请求
response = requests.post(api_url, headers=headers, json=data)
print(response)
# 输出生成的文本
# print(response.json()["choices"][0]["text"].strip())
print(response.json())
print(response.json()["choices"][0]["text"].strip())
这样就可以正常返回了
<Response [200]>
{'id': 'chatcmpl-7g3Tv1XikORBog0A0jUzoTrjkPXvf',
 'object': 'chat.completion',
 'created': 1690257515,
 'model': 'gpt-35-turbo',
 'choices': [{'index': 0,
   'finish_reason': 'stop',
   'message': {'role': 'assistant',
    'content': 'The Los Angeles Dodgers won the World Series in 2020.'}}],
 'usage': {'completion_tokens': 13, 'prompt_tokens': 29, 'total_tokens': 42}}

**Comment by songquanpeng** [comment]
这个不是 One API 的 bug，是使用问题

**Comment by sailaoda** [comment]
> ```python
> import openai
> 
> openai.api_key = 'sk-****' # 令牌处创建，获得
> openai.api_base = 'https://xxxxx/v1'
> openai.api_type = 'openai'
> 
> messages = [{"role": "user", "content": "你是谁"}]
> response = openai.ChatCompletion.create(
>     model='gpt-4',
>     # model='gpt-4-32k',
>     # model='gpt-3.5-turbo',
>     # model='gpt-3.5-turbo-16k',
>     # model='gpt-3.5-turbo-0301',
>     # model='gpt-3.5-turbo-0613',
>     # model='gpt-3.5-turbo-16k-0613',
>     # model='gpt-4-0613',
>     # model='gpt-4-32k-0613',
>     # model='gpt-4-0314',
>     # model='gpt-4-32k-0314',
>     messages=messages
> )
> print(response['choices'][0]['message']['content'])
> ```
> 
> 这样调用，可以。

您好，我和您完全一样的代码，api_tpye 是 azure，但是 报错 python3 xapi.py
Traceback (most recent call last):
  File "/Users/yesai/Projects/python-test/xapi.py", line 9, in <module>
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: 未提供令牌 (request id: 202310251258146391150009FEXjJT6)
