### ISSUE TITLE
支持文心千帆的 Embedding 接口

### ISSUE THREAD

**Issue by shendengnian** [songquanpeng/one-api#324]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**fastgpt知识库不支持调用Embedding-V1**

**复现步骤**
用的是fastgpt的项目，是能正常调用ERNIE-Bot-turbo对话的，但是我也想用fastgpt的知识库训练文心的Embedding-V1，不知道怎么设置，请问大佬们有方案吗？

![](https://files.mdnice.com/user/33461/d2efe495-e6a8-4662-aa76-5038e95060b1.png)
![](https://files.mdnice.com/user/33461/a8b95f46-5777-4145-a920-8fc5e21c2b3e.png)

**预期结果**
能够使用fastgpt的知识库训练文心千帆的Embedding-V1文本表示

**Comment by songquanpeng** [comment]
百度的embedding还没支持



---Original---
From: ***@***.***&gt;
Sent at: 2023年7月25日(Tue) Noon12:19
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] fastgpt知识库对接文心千帆遇到的问题 (Issue #324)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，尤其是常见问题部分
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
fastgpt知识库不支持调用Embedding-V1
 
复现步骤
 用的是fastgpt的项目，是能正常调用ERNIE-Bot-turbo对话的，但是我也想用fastgpt的知识库训练文心的Embedding-V1，不知道怎么设置，请问大佬们有方案吗？
 

 
 
预期结果
 能够使用fastgpt的知识库训练文心千帆的Embedding-V1文本表示

**Comment by songquanpeng** [comment]
周末处理

**Comment by muzibaby** [comment]
我更新了 .2 tag ，但是关联知识库的时候，依然提示如下错误：
the length of messages must be an odd number

**Comment by songquanpeng** [comment]
把原始的 request 贴过来

**Comment by shendengnian** [comment]
> 周末处理

你好，通义千问对接了text-embedding-v1了吗？

**Comment by muzibaby** [comment]
就是 fastgpt 过来的请求，配上知识库就会有问题，不配是正常的
 Regards,
Vigo Song  
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月28日 20:20 |
| 收件人 | songquanpeng/one-api ***@***.***> |
| 抄送人 | vigo ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [songquanpeng/one-api] 支持文心千帆的 Embedding 接口 (Issue #324) |

把原始的 request 贴过来

**Comment by songquanpeng** [comment]
已经支持 Embedding-V1

**Comment by muzibaby** [comment]
创建渠道 模型需要映射？
 Regards,
Vigo Song  
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月29日 12:15 |
| 收件人 | songquanpeng/one-api ***@***.***> |
| 抄送人 | vigo ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [songquanpeng/one-api] 支持文心千帆的 Embedding 接口 (Issue #324) |

已经支持 Embedding-V1

**Comment by songquanpeng** [comment]
nope
