### ISSUE TITLE
本地部署无法读取环境变量

### ISSUE THREAD

**Issue by Pessimisticc** [songquanpeng/one-api#325]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
宝塔Go项目管理部署 手动构建后端部署无法读取环境变量的Redis配置信息
go1.20.6
**复现步骤**
![image](https://github.com/songquanpeng/one-api/assets/47294782/e748d159-975f-4664-b284-44c4dd0c7880)

**预期结果**
环境变量存在，仍然无法读取Redis配置信息
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/47294782/afa229b7-a406-4734-a3b4-c59fea57d6bb)

**Comment by lihongjie224** [comment]
宝塔面板读取root用户环境变量有问题，可以尝试将环境变量放在/etc/environment

**Comment by songquanpeng** [comment]
这个不是 One API 的问题
