### ISSUE TITLE
兼容文心一言不支持 system role

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#328]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
文心一言的官方 API 比较垃圾和反人类。
1. 传入的数组必须是基数
2. 没有 role: system 

**改进方式**
将 system 自动转化成 user, 并在后面补一个 assistant（content可以加一个简单的字符跳过 百度的空判断）。
这样不管是基数还是偶数个system，最终都能成功请求。

**应用场景**

**Comment by shendengnian** [comment]
确实，我不会golang，只能在fastgpt里做个兼容来判断，那样有点不友好

**Comment by songquanpeng** [comment]
周末处理

**Comment by captain-miao** [comment]
真的很恶心，都是 AI 了还这么严格的消息格式，提供一段 Python 代码

```python
        prompt_msgs = []
        if model in CN_BAIDU_MODELS:
            role = 'user'
            for i, message in enumerate(messages):
                content = message.get('content', '')
                if not content:
                    continue

                prompt_msgs.append({'role': role, 'content': content})
                role = 'assistant' if role == 'user' else 'user'

            if len(prompt_msgs) % 2 == 0:
                prompt_msgs.append({'role': 'user', 'content': '谢谢'})
```

**Comment by songquanpeng** [comment]
已修复，稍后推送

**Comment by songquanpeng** [comment]
已推送
