### ISSUE TITLE
以 token 数为单位计算配额

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#33]
由于次数太泛，毕竟有的用户一次返回超级多得字数，所以加入token来计算会，将来会有计划嘛？

**Comment by songquanpeng** [comment]
有计划的。

**Comment by songquanpeng** [comment]
已实现，不过当前对于 stream 格式的返回，我直接是通过 bytes 数乘以一个系数来估算的，系数之后可以自己配置。

**Comment by songquanpeng** [comment]
已支持配置系数。

**Comment by songquanpeng** [comment]
已更换 token 计算方式。

**Comment by lmuiotctf** [comment]
所以目前这个额度是以token为计算方式，不是以请求成功为基准了嘛？
建议在新建渠道的时候新增一个选项（是否以token为计算标准、保留原来的请求次数额度）
![image](https://user-images.githubusercontent.com/52068443/235127464-26f096dd-798d-4728-942f-80809f68061c.png)

**Comment by songquanpeng** [comment]
次数的话保留意义不大，如果一个用户带了很多历史信息，还是只算一次，但是实际消耗的 token 很多。

**Comment by lmuiotctf** [comment]
嗯嗯 所以目前情况是：stream：true的时候开启token计算？

**Comment by songquanpeng** [comment]
非 stream 模式下 OpenAI 的 API 会直接返回 token 数，不需要自己计算。

**Comment by songquanpeng** [comment]
这个还好吧，他不充值的话下次就没法请求了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月28日(星期五) 晚上6:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [songquanpeng/one-api] 以 token 数为单位计算配额 (Issue #33)





 
可以，但是超了变负数这个应该无法进行控制（哈哈哈哈哈）

**Comment by lmuiotctf** [comment]
对了，好像充值链接时没有在接口进行返回
![image](https://user-images.githubusercontent.com/52068443/235129379-f4f29f9d-74ae-4844-8b1d-ff7d697ab68a.png)
![image](https://user-images.githubusercontent.com/52068443/235129398-53a99171-2210-4be9-9889-285f8c8f5a28.png)

**Comment by songquanpeng** [comment]
我感觉不应该在 API 的返回内容里放充值链接吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月28日(星期五) 晚上6:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [songquanpeng/one-api] 以 token 数为单位计算配额 (Issue #33)





 
对了，好像充值链接时没有在接口进行返回

**Comment by lmuiotctf** [comment]
这个确实，接口返回放充值链接不得行

**Comment by songquanpeng** [comment]
> 这个确实，接口返回放充值链接不得行，期待下次优化！ 希望实现： 站点名字支持后台配置

新需求请单开一个 issue，不然不方便我归档。
