### ISSUE TITLE
当前分组负载已饱和，请稍后再试，或升级账户以提升服务质量

### ISSUE THREAD

**Issue by Ivesfsy** [songquanpeng/one-api#330]
{
  "error": {
    "message": "当前分组负载已饱和，请稍后再试，或升级账户以提升服务质量。",
    "type": "billing_not_active",
    "param": "",
    "code": "billing_not_active"
  }
}

**Comment by Ivesfsy** [comment]
使用宝塔搭建的

**Comment by fengjisheng** [comment]
同问, 这个问题不知道是什么原因报错的?
