### ISSUE TITLE
支持 360 智脑 

### ISSUE THREAD

**Issue by thinker007** [songquanpeng/one-api#331]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
目前360智脑也开放了API 申请，在国内模型中评估下来效果也还可以。
API本身跟openai 兼容性较高。

建议支持。

API 申请链接：https://ai.360.cn/open

**应用场景**

**Comment by songquanpeng** [comment]
如果可以的话私聊我 key

**Comment by thinker007** [comment]
> 如果可以的话私聊我 key

API本身有免费额度，可以直接去 https://ai.360.cn/open 申请。

**Comment by songquanpeng** [comment]
等人提供 key 吧

**Comment by thinker007** [comment]
> 等人提供 key 吧
如何私聊你，有微信群或者邮箱么？

**Comment by songquanpeng** [comment]
有 QQ 群，你提 issue 的过程中应该看到了已经

**Comment by thinker007** [comment]
![image](https://github.com/songquanpeng/one-api/assets/1329869/6a1fbcb4-2f25-4238-a747-996625e0fc82)
得益于 360智脑 跟openai 的API 的全兼容特性，可以直接按照openai的类型添加，比较tricky 也是可用的，期待官方有更好的支持。

**Comment by songquanpeng** [comment]
可以，我试一下

**Comment by songquanpeng** [comment]
申请不给过

**Comment by glzjin** [comment]
实测，确实，直接加自定义渠道就行。流和非流对话都完全OK的。
计费也完全没问题。
![image](https://github.com/songquanpeng/one-api/assets/7975407/1639e24d-e770-4341-8c5e-ef83728dfb0c)


![image](https://github.com/songquanpeng/one-api/assets/7975407/33283a5f-b244-468b-b80b-b2df31261b1b)

**Comment by thinker007** [comment]
那就请 @songquanpeng 官方抓紧支持了~ 估计也就是加个专门配置的事情。

**Comment by TangSY** [comment]
看到这条其实挺为作者感到心累，三周前就有人催支持360，结果到现在一直没人愿意提供 key 测试，着急白嫖又不愿意提供测试 key，自己该代码呗。开源不易，好好珍惜吧～

**Comment by thinker007** [comment]
> 看到这条其实挺为作者感到心累，三周前就有人催支持360，结果到现在一直没人愿意提供 key 测试，着急白嫖又不愿意提供测试 key，自己该代码呗。开源不易，好好珍惜吧～

额，我其实通过qq给到了作者api key的，不过看上面回复 作者应该是已经是拿到测试账号了，key的问题不存在了。
开源的确不易，白嫖的多，愿意贡献的少。
目前看上去大部分情况都是作者在免费做贡献 所以也体现出作者的可贵 可敬。

**Comment by songquanpeng** [comment]
阿哲，我前几天搜没搜到，然后群里问也没有响应

**Comment by songquanpeng** [comment]
又试了一下，是藏到更多里面了

**Comment by thinker007** [comment]
@songquanpeng 看到更新了 感谢您👍🏻
