### ISSUE TITLE
ChatGPT-Next-Web 使用oneapi报错

### ISSUE THREAD

**Issue by Pa5sw0rd** [songquanpeng/one-api#332]
+ [√] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我已完整查看过项目 README，尤其是常见问题部分
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/tree/main)项目也是最新的，使用oneapi会报错，使用官方api正常
已修改base_url，一直使用自己的反代

**报错内容**
```
TypeError: A request with a one-time-use body (it was initialized from a stream, not a buffer) encountered a redirect requiring the body to be retransmitted. To avoid this error in the future, construct this request from a buffer-like body initializer.
```

**复现步骤**
![image](https://github.com/songquanpeng/one-api/assets/39618181/00f811eb-b4df-47e8-9578-4ff98b5c6e85)

**预期结果**
正常回复

**Comment by lipanpan-hub** [comment]
部分模型报错 还是 所有模型 都会报错?

**Comment by Pa5sw0rd** [comment]
> 部分模型报错 还是 所有模型 都会报错?

使用3.5，换模型也会，[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/tree/main)使用vercel部署

**Comment by Pa5sw0rd** [comment]
> 使用3.5，换模型也会，[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/tree/main)使用vercel部署

暂时不知道是哪里的问题

**Comment by ckt1031** [comment]
其實是因為ChatGPT Next Web會輸出
event: .....
的流數據, 導致解析錯誤

**Comment by songquanpeng** [comment]
这就很离谱了，我一直用的就是这个。

如果可以的话，提供一下服务端的相关报错日志。

**Comment by songquanpeng** [comment]
这貌似都不是 One API 的报错
