### ISSUE TITLE
支持 openrouter 

### ISSUE THREAD

**Issue by lipanpan-hub** [songquanpeng/one-api#333]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
openrouter 提供了丰富的模型 和 可靠的接口 可以作为一个渠道加入到oneapi

**相关资料**
官网地址: https://openrouter.ai
接口文档: https://openrouter.ai/docs
体验地址: https://www.omnimodel.chat/zh
可以通过google账号进行注册 注册之后送一定量的免费额度 可以用于调试  我也可以提供调试所需要的key(我qq群id是ls)

**应用场景**
提供渠道冗余 分担负载压力 保证服务

**Comment by songquanpeng** [comment]
配合自定义渠道 + 自定义模型名称 + 模型映射就可以用了。

**Comment by lipanpan-hub** [comment]
文档里面 要求提供 HTTP-Referer
```python
import openai

openai.api_base = "https://openrouter.ai/api/v1"
openai.api_key = $OPENROUTER_API_KEY

response = openai.ChatCompletion.create(
model="openai/gpt-3.5-turbo", # Optional (user controls the default)
messages=[...],
headers={ "HTTP-Referer": $YOUR_SITE_URL, # To identify your app
          "X-Title": $YOUR_APP_NAME },
)
reply = response.choices[0].message

```
我尝试使用自定义渠道 和自定义模型 进行请求测试得到的 返回是:
```json
{
	"error": {
		"message": "Please set an \"HTTP-Referer\" header with the URL of your app",
		"code": 400
	}
}
```

**Comment by songquanpeng** [comment]
怎么说呢，不想给第三方的小众站点进行单独的适配了，ROI 太低

**Comment by lipanpan-hub** [comment]
好的 先做更加重要的功能吧  后面有机会再说吧

**Comment by glzjin** [comment]
> 好的 先做更加重要的功能吧 后面有机会再说吧

https://github.com/songquanpeng/one-api/issues/340#issuecomment-1661685578 基本上算支持了，做了个反代 + 修了下没usage的非流计费。

**Comment by songquanpeng** [comment]
已经支持了

**Comment by sapipoZZZ** [comment]
![image](https://github.com/songquanpeng/one-api/assets/19617283/df43fa9d-d41c-429f-b34b-0d9bb996517d)
我今天部署了v0.5.4发现还是有问题呢
