### ISSUE TITLE
失败没有重试

### ISSUE THREAD

**Issue by GitWingSky** [songquanpeng/one-api#335]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
失败没有重试
**复现步骤**
渠道里有2个渠道，一个渠道噶了，另一个渠道是好的。请求的时候会出现噶了的返回
**预期结果**
失败重试，通过好的那个渠道返回正常信息
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/25954832/86b37336-d6b8-4cdb-828b-842e61a80415)

**Comment by songquanpeng** [comment]
启用了么



---Original---
From: ***@***.***&gt;
Sent at: 2023年7月29日(Sat) Evening6:05
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 失败没有重试 (Issue #335)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，尤其是常见问题部分
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
问题描述
 失败没有重试
 复现步骤
 渠道里有2个渠道，一个渠道噶了，另一个渠道是好的。请求的时候会出现噶了的返回
 预期结果
 失败重试，通过好的那个渠道返回正常信息
 相关截图

**Comment by GitWingSky** [comment]
2个渠道都启用了

**Comment by songquanpeng** [comment]
重试启用了么



---Original---
From: ***@***.***&gt;
Sent at: 2023年7月29日(Sat) Evening6:08
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 失败没有重试 (Issue #335)




 
2个渠道都启用了

**Comment by GitWingSky** [comment]
> 启用了么
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2023年7月29日(Sat) Evening6:05 To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [songquanpeng/one-api] 失败没有重试 (Issue #335) 例行检查 我已确认目前没有类似 issue 我已确认我已升级到最新版本 我已完整查看过项目 README，尤其是常见问题部分 我理解并愿意跟进此 issue，协助测试和提供反馈 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 问题描述 失败没有重试 复现步骤 渠道里有2个渠道，一个渠道噶了，另一个渠道是好的。请求的时候会出现噶了的返回 预期结果 失败重试，通过好的那个渠道返回正常信息 相关截图 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

两个渠道都启用了的
