### ISSUE TITLE
支持openrouter.ai

### ISSUE THREAD

**Issue by 52eraja** [songquanpeng/one-api#340]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
openrouter.ai Google: PaLM 2 Bison 暂时免费，由于申请不到Google PaLM API，希望可以支持一个openrouter api，谢谢。
**应用场景**

**Comment by songquanpeng** [comment]
#333

**Comment by glzjin** [comment]
实测可以配置一下 Caddy 或者其他的反向代理比如  Nginx，让 Caddy 来反代 OpenRouter，加上那边需要的两个头：

1. Caddyfile

```
openrouter-api.*.com {
    tls /etc/caddy/ssl/*.com_server.crt.pem /etc/caddy/ssl/*.com_server.key.pem
    reverse_proxy https://openrouter.ai {
        header_up Host openrouter.ai
        header_up HTTP-Referer "https://oneapi.*.com"
        header_up X-Title "One API"
    }
}
```

2. 然后这样配置即可。

![image](https://github.com/songquanpeng/one-api/assets/7975407/3165b4dd-5ae9-4898-b4f3-c182a8363e54)

3. 实测可行。

![image](https://github.com/songquanpeng/one-api/assets/7975407/019526e6-e599-4893-8fe2-02c5699127ba)

**Comment by glzjin** [comment]
但好像自定义通道的stream才计费，非stream的自定义模型不计费。

**Comment by glzjin** [comment]
尝试着修了下非流模式下的计费 https://github.com/songquanpeng/one-api/pull/352

![image](https://github.com/songquanpeng/one-api/assets/7975407/82f85eb6-690d-4ad8-80a9-35ad145a9bdc)

**Comment by songquanpeng** [comment]
为避免误导，我这里补充一下，不计费是因为没有返回 usage，正常的渠道都会返回这个，而不是因为是自定义模型

**Comment by songquanpeng** [comment]
等周末有时间再处理了



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月2日(Wed) Evening9:04
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 支持openrouter.ai (Issue #340)




 
尝试着修了下非流模式下的计费 #352

**Comment by glzjin** [comment]
> 为避免误导，我这里补充一下，不计费是因为没有返回 usage，正常的渠道都会返回这个，而不是因为是自定义模型

确实，就是因为没usage。

**Comment by songquanpeng** [comment]
之后有时间还是支持一下吧

**Comment by songquanpeng** [comment]
已经支持

**Comment by andrsted** [comment]
请问，我用宝塔面板按上述方式搭建了ngnix的反向代理，可以使用openrouter.ai。如何使输出为流式输出呢？

**Comment by songquanpeng** [comment]
不需要按上述方式了，你直接用 One API 就好了

**Comment by andrsted** [comment]
> 

原来如此。我直接选的openrouter通道，测试不通过。然后我就搜的这个方法。
现在发现只是测试不通过，还能用哈哈。
大佬那我通道直接选openrouter的话，如何配置成流式输出呢？
