### ISSUE TITLE
使用 OpenAI Max 接口调用报错：http: invalid Read on closed Body

### ISSUE THREAD

**Issue by aohun** [songquanpeng/one-api#35]
![image](https://user-images.githubusercontent.com/37433539/235287191-b0d1c660-1f0c-4aee-bec3-1c1399ef2313.png)
是否是包装之后请求参数不符合openaimax的格式？
单独使用openaimax调用是没问题的

**Comment by songquanpeng** [comment]
感谢反馈，我调查一下。

**Comment by songquanpeng** [comment]
很离谱，线上环境正常，线下测试确实是这样，仍在调查。

**Comment by songquanpeng** [comment]
你是在本地测试的吗？我发现我一台电脑上 Okay，另一个不行，初步判断是本地的网络问题。

**Comment by hhz-saner** [comment]
我这两个渠道 openai-sb api2d 也是这样的

**Comment by aohun** [comment]
服务器上，IP加端口调用one api



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JustSong ***@***.***&gt;
发送时间: 2023年4月29日 14:38
收件人: songquanpeng/one-api ***@***.***&gt;
抄送: aohun ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [songquanpeng/one-api] 使用 OpenAI Max 接口调用报错：http: invalid Read on closed Body (Issue #35)





 
你是在本地测试的吗？我发现我一台电脑上 Okay，另一个不行，初步判断是本地的网络问题。

**Comment by songquanpeng** [comment]
已定位到问题。

**Comment by songquanpeng** [comment]
已修复，已推送版本 `v0.2.1-alpha`。

**Comment by songquanpeng** [comment]
稍微解释一下为什么有时候是 Okay 的。

如果你用的令牌是有配额限制的令牌，不会报错；使用无配额限制的令牌，则会出现该问题。

出现问题的原因在于过早地关闭了用户的 HTTP 请求的请求体，导致在使用其请求体向服务器发送内容时 body 已被关闭。

而使用无配额限制的令牌时，body 被替换为 `c.Request.Body = io.NopCloser(bytes.NewBuffer(requestBody))`，对其进行 close 并没有实际作用，因此此时不会报错。
