### ISSUE TITLE
docker更新版本遇到的问题

### ISSUE THREAD

**Issue by shendengnian** [songquanpeng/one-api#350]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

我是用宝塔的docker管理器部署oneapi项目的，每次我输入 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR 命令同步更新官方的镜像的时候，都会导致当前版本的数据全部恢复成初始状态。

**预期结果**

输入 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR 同步更新版本的时候，能保留当前版本的用户数据，还有key配置这些

**Comment by songquanpeng** [comment]
建议先学一下docker，不会的话就老实用readme里的命令
