### ISSUE TITLE
支持MiniMax模型

### ISSUE THREAD

**Issue by streamsc** [songquanpeng/one-api#354]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
MiniMax是国内大模型领域的独角兽、目前已提供大模型开放平台。
https://api.minimax.chat/document/guides/chat-pro?id=64b79fa3e74cddc5215939f4

**应用场景**
向量接口、chat接口

**Comment by glzjin** [comment]
用了个比较 Dirty 的方式来支持。https://github.com/glzjin/ChatProxy-MiniMax 在作者支持之前可以先看看这里。

**Comment by songquanpeng** [comment]
第一步需要有人提供 key 给我：
![image](https://github.com/songquanpeng/one-api/assets/39998050/e19ba621-ca47-4dec-a0da-ee2a3b56052f)

**Comment by woodchen-ink** [comment]
> 第一步需要有人提供 key 给我： ![image](https://user-images.githubusercontent.com/39998050/258637915-e19ba621-ca47-4dec-a0da-ee2a3b56052f.png)

我申请了，已私发作者

**Comment by songquanpeng** [comment]
@chikasaki 已跟进该问题，请勿提交重复 PR

**Comment by c121914yu** [comment]
滴滴，进度如何？

**Comment by angular-moon** [comment]
进度如何？

**Comment by tisfeng** [comment]
关注一下，MiniMax 效果还不错。

**Comment by mattliu007** [comment]
持续关注

**Comment by songquanpeng** [comment]
已经支持
