### ISSUE TITLE
讯飞星火认知模型配置未成功

### ISSUE THREAD

**Issue by VectorZhao** [songquanpeng/one-api#357]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
讯飞星火认知模型，利用chatgpt-web项目进行访问，借助项目里面的gpt4模型访问讯飞模型，做了如下配置：

![image](https://github.com/songquanpeng/one-api/assets/16644993/857a3b7a-b414-46c7-a59f-53df6c8d2017)
![image](https://github.com/songquanpeng/one-api/assets/16644993/81b9d685-4421-45dd-9f43-41bbb608af6d)

请帮忙看一下哪里出错了，谢谢！

**复现步骤**

**预期结果**
成功调用讯飞星火模型
**相关截图**
见问题描述。

**Comment by glzjin** [comment]
模型那把gpt-4填进去试试。

**Comment by VectorZhao** [comment]
我把选择模型那里的sparkdesk删掉，选择了gpt4，一样的错误提示

**Comment by glzjin** [comment]
两个都要保留。

**Comment by aabao325** [comment]
是hostUrl的问题，但是修改了也还是运行有问题，不太懂
hostUrl := "wss://spark-api.xf-yun.com/v1.1/chat"

**Comment by VectorZhao** [comment]
> 两个都要保留。
sparkdesk和gpt4都保留，还是一样的错误

**Comment by glzjin** [comment]
手工在 Postman 之类的工具里发包下，看看报错，或者 docker logs 看看后端有什么信息没。

**Comment by glzjin** [comment]
```
POST /v1/chat/completions HTTP/1.1
Host: xxx
Content-Type: application/json
Authorization: Bearer sk-xxxx
Content-Length: 158

{
    "messages": [
        {
            "role": "user",
            "content": "你是是谁？"
        }
    ],
    "stream": false,
    "model": "gpt-4"
}
```

**Comment by VectorZhao** [comment]
> 手工在 Postman 之类的工具里发包下，看看报错，或者 docker logs 看看后端有什么信息没。
docker log
```
[SYS] 2023/08/04 - 17:19:34 | relay error (channel #14): websocket: bad handshake 
[GIN] 2023/08/04 - 17:19:34 | 500 |  1.292997714s |  129.150.54.130 | POST     "/v1/chat/completions"
```

**Comment by glzjin** [comment]
配置界面 镜像那里 确定没填过的哈？

**Comment by songquanpeng** [comment]
为什么你要搞一个模型重定向？客户端请求的时候直接使用讯飞的模型名称

**Comment by VectorZhao** [comment]
> 为什么你要搞一个模型重定向？客户端请求的时候直接使用讯飞的模型名称

?你在chatgpt-web里面能直接选讯飞的模型名称？
