### ISSUE TITLE
如果自定义渠道未返回prompt_tokens、completion_tokens、total_tokens字段，是否就无法计费？

### ISSUE THREAD

**Issue by zhuxindong** [songquanpeng/one-api#358]
如题，我自定义的渠道无法返回prompt_tokens、completion_tokens、total_tokens字段，是否就无法计费？

**Comment by glzjin** [comment]
Sodayo。https://github.com/songquanpeng/one-api/pull/352

**Comment by songquanpeng** [comment]
并且是非 stream 模式

**Comment by songquanpeng** [comment]
#352 solved
