### ISSUE TITLE
自动重试功能不起作用

### ISSUE THREAD

**Issue by LNpks** [songquanpeng/one-api#361]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
有两个渠道，当1渠道出现问题时，还是会返回1渠道的错误，多次提问后才有可能返回2渠道的正常信息。

**复现步骤**
在设置里将失败重试次数设置为5，渠道内开启两个渠道，其中一个渠道故障，另外一个渠道可用。

**预期结果**
返回渠道2的正确信息

**Comment by songquanpeng** [comment]
目前的自动重试是随机重试，五次随机不太可能一直随机到错误的吧

**Comment by GtxFury** [comment]
> 目前的自动重试是随机重试，五次随机不太可能一直随机到错误的吧

请问意思是不能完全避开错误的渠道吗，用了自动重试还是概率随机到错误的渠道？

**Comment by songquanpeng** [comment]
1. 首先，渠道错误不意外着永久性的错误，否则你应该启用失败时自动禁用。
2. 其次，当前的实现是重定向，这意味不能控制不去使用某个渠道。

在大部分场景下，这种随机重试已经 Okay 了。

**Comment by GtxFury** [comment]
> 1. 首先，渠道错误不意外着永久性的错误，否则你应该启用失败时自动禁用。
> 2. 其次，当前的实现是重定向，这意味不能控制不去使用某个渠道。
> 
> 在大部分场景下，这种随机重试已经 Okay 了。

感谢 还有个问题就是渠道报错400或者429 请求频繁可以暂时避开这个渠道吗，怀疑是程序没有把这类报错当做是错误，导致自动重试不起作用

**Comment by songquanpeng** [comment]
你的怀疑是不成立的，如果能找出不能正确处理的例子稳定复现后提 issue

**Comment by webpon** [comment]
+1, 5刀普通号限速后根本没有自动重试

**Comment by webpon** [comment]
没有没有报任何的错误信息，导致我这里无法捕获错误从而重试

**Comment by kuangxiaoye** [comment]
> 目前的自动重试是随机重试，五次随机不太可能一直随机到错误的吧

非常感谢，更新最新版后，尝试重试机制后发现非常实用！

**Comment by kuangxiaoye** [comment]
> 你的怀疑是不成立的，如果能找出不能正确处理的例子稳定复现后提 issue

不过还是提一个小小的想法，群佬。

重试在应对渠道参差的情况下非常友好！比如某个渠道到rate limte，就可以自动重试可用渠道。

但是，有些致命错误是没有必要重试的，比如用户直接输入了10000个字符。我在日志中发现，这种错误依然重试

谢谢群佬

**Comment by kuangxiaoye** [comment]
> > 你的怀疑是不成立的，如果能找出不能正确处理的例子稳定复现后提 issue
> 
> 不过还是提一个小小的想法，群佬。
> 
> 重试在应对渠道参差的情况下非常友好！比如某个渠道到rate limte，就可以自动重试可用渠道。
> 
> 但是，有些致命错误是没有必要重试的，比如用户直接输入了10000个字符。我在日志中发现，这种错误依然重试
> 
> 谢谢群佬

这个需求比较个性化，还是自己改一下吧 感谢群佬
