### ISSUE TITLE
希望增加用户组请求次数限制功能（有偿）

### ISSUE THREAD

**Issue by B3nDan** [songquanpeng/one-api#362]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

现在已知可以统计用户的请求次数
能否增加一个次数设定，达到设定次数后
自动禁用用户

**应用场景**

实现 按次数 供给使用

**Comment by B3nDan** [comment]
作者不愿做，谁可以实现，有偿

**Comment by songquanpeng** [comment]
怎么说呢，这个需求属于定制需求，绝大部分人都不会用到这个，一味的加功能只会导致系统变得复杂难以维护难以理解
