### ISSUE TITLE
添加的自定义模型无法再v1/models接口中返回

### ISSUE THREAD

**Issue by zhuxindong** [songquanpeng/one-api#366]
在渠道添加自定义模型后，v1/models接口不会返回添加的自定义的模型，而是依旧返回了写死的https://github.com/songquanpeng/one-api/blob/main/controller/model.go#L56 模型列表。

希望v1/models接口能够返回添加的自定义模型

**Comment by songquanpeng** [comment]
会解决该问题。

**Comment by hanckjt** [comment]
这个问题还没解决呢？还是获取不到自定义的模型。

**Comment by songquanpeng** [comment]
已经支持了
