### ISSUE TITLE
企业微信消息推送、定时测试、定时检查余额

### ISSUE THREAD

**Issue by xyfacai** [songquanpeng/one-api#367]
**例行检查**

 我已确认目前没有类似 issue
 我已确认我已升级到最新版本
 我已完整查看过项目 README，尤其是常见问题部分
 我理解并愿意跟进此 issue，协助测试和提供反馈
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
1. 添加企业微信消息推送，可自定义推送的markdown格式以及内容
2. 可开启定时测试、定时检查余额

**应用场景**
开启定时测试、检查余额，可推送至企业微信，更方便检查 api key 的状态以及余额

**Comment by songquanpeng** [comment]
暂时不打算直接对接企业微信，后面考虑对接 https://github.com/songquanpeng/message-pusher ，不过邮件其实已经足够，ROI 不高。
