### ISSUE TITLE
令牌计算不正确

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#37]
我发送了一句话 （12个中文 消耗了 网站显示 用了2k的令牌。我用 openai token 计算也才26个

**Comment by aiastia** [comment]
1、另外删除 令牌后  额度 视乎虚无了… 
2 删除token 没二次确认 …

**Comment by songquanpeng** [comment]
1. 我也感觉令牌的消耗有点问题。
2. 删除令牌后按理说无法使用了才对？难道你删完之后还可以用啊》
3. 二次确认这个之后加上。

谢谢反馈，稍后处理。

**Comment by aiastia** [comment]
视乎是夹带了上下文 😅> 我发送了一句话 （12个中文 消耗了 网站显示 用了2k的令牌。我用 openai token 计算也才26个

**Comment by aiastia** [comment]
> 删除令牌

1。3.5好像是计算发送和上次回复(如果有）的吧。感觉 是吧回复的也计算进去了 
2。应该是不能用 ，不过目前系统是有兑换按钮 目前如果 删除 了 兑换的次数不就找不回来了 🤔

**Comment by songquanpeng** [comment]
1. 是的，会把上下文算进去的，OpenAI 也是这样计费的，所以如果上下文很长是有可能一次消耗很多的。
2. 是哦，删除后应该把剩余次数返还给用户，我忘记考虑这一点了。

**Comment by mashihua** [comment]
不知道支不支持 stream 方式的 token 计算，如果没有的话，看看这个 https://github.com/pkoukk/tiktoken-go

**Comment by songquanpeng** [comment]
我再次测试了一下，token 计算是正确的。
命令 ChatGPT 返回我们的输入，这样可以固定其输出。stream 模式和非 stream 模式下的 token 数一致：
![image](https://user-images.githubusercontent.com/39998050/236095901-5b2f0928-f27d-4fae-9ed8-9ac5dc231984.png)

**Comment by songquanpeng** [comment]
删除时返还剩余额度已实现。

**Comment by sunqb** [comment]
@songquanpeng 我看到用tiktoken计算的，为啥我计算“树叶为什么是绿色的”是13。但是日志里面是20？

**Comment by sunqb** [comment]
> [@songquanpeng](https://github.com/songquanpeng) 我看到用tiktoken计算的，为啥我计算“树叶为什么是绿色的”是13。但是日志里面是20？

看源码看到了https://github.com/pkoukk/tiktoken-go/issues/6。忽略吧。
