### ISSUE TITLE
使用zeabur更新失败

### ISSUE THREAD

**Issue by Pa5sw0rd** [songquanpeng/one-api#371]
15:07:21#0 building with "default" instance using docker driver

15:07:21

15:07:21#1 [internal] load build definition from Dockerfile

15:07:22#1 transferring dockerfile: 1.60kB done

15:07:22#1 DONE 0.0s

15:07:22

15:07:22#2 [internal] load .dockerignore

15:07:22#2 transferring context: 2B done

15:07:22#2 DONE 0.0s

15:07:22

15:07:22#3 [internal] load metadata for docker.io/library/golang:latest

15:07:24#3 ...

15:07:24

15:07:24#4 [internal] load metadata for docker.io/library/node:16

15:07:24#4 DONE 2.3s

15:07:24

15:07:24#5 [internal] load metadata for docker.io/library/alpine:latest

15:07:24#5 DONE 2.5s

15:07:24

15:07:24#3 [internal] load metadata for docker.io/library/golang:latest

15:07:24#3 DONE 2.5s

15:07:24

15:07:24#6 [stage-2 1/4] FROM docker.io/library/alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a

15:07:24#6 resolve docker.io/library/alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a 0.0s done

15:07:24#6 ...

15:07:24

15:07:24#7 [internal] load build context

15:07:24#7 transferring context: 774.49kB 0.0s done

15:07:24#7 DONE 0.1s

15:07:24

15:07:24#6 [stage-2 1/4] FROM docker.io/library/alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a

15:07:24#6 sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a 1.64kB / 1.64kB done

15:07:24#6 sha256:c5c5fda71656f28e49ac9c5416b3643eaa6a108a8093151d6d1afc9463be8e33 528B / 528B done

15:07:24#6 sha256:7e01a0d0a1dcd9e539f8e9bbd80106d59efbdf97293b3d38f5d7a34501526cdb 1.47kB / 1.47kB done

15:07:24#6 sha256:7264a8db6415046d36d16ba98b79778e18accee6ffa71850405994cffa9be7de 0B / 3.40MB 0.1s

15:07:24#6 sha256:7264a8db6415046d36d16ba98b79778e18accee6ffa71850405994cffa9be7de 2.10MB / 3.40MB 0.3s

15:07:24#6 sha256:7264a8db6415046d36d16ba98b79778e18accee6ffa71850405994cffa9be7de 3.40MB / 3.40MB 0.3s done

15:07:24#6 extracting sha256:7264a8db6415046d36d16ba98b79778e18accee6ffa71850405994cffa9be7de

15:07:25#6 extracting sha256:7264a8db6415046d36d16ba98b79778e18accee6ffa71850405994cffa9be7de 0.1s done

15:07:25#6 DONE 0.6s

15:07:25

15:07:25#8 [builder 1/6] FROM docker.io/library/node:16@sha256:6cd6581a9ae814ebbc8077afd63ecbf4d37f9b59ac9d9304a1b5a9e743ac13e0

15:07:25#8 resolve docker.io/library/node:16@sha256:6cd6581a9ae814ebbc8077afd63ecbf4d37f9b59ac9d9304a1b5a9e743ac13e0 0.0s done

15:07:25#8 sha256:a21a68db680698eb1a863e229f81f70975f7ff6231e4d3ae755cf82f77bbac67 7.24kB / 7.24kB done

15:07:25#8 sha256:9918064ebccea7fc961fe71dad46105b217763b4b1b3a9dfa7bee2ab29d2039b 49.28MB / 50.50MB 0.6s

15:07:25#8 sha256:6cd6581a9ae814ebbc8077afd63ecbf4d37f9b59ac9d9304a1b5a9e743ac13e0 776B / 776B done

15:07:25#8 sha256:83e822fa0a8094738dcaed855466cccae8d6599d55409e2befaa2040e27ead15 2.00kB / 2.00kB done

15:07:25#8 sha256:2345e1e5f82d8963240db3c8e8ccfd431d0962d14219e24bbcc756ef217bba48 9.44MB / 17.58MB 0.6s

15:07:25#8 sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c 0B / 51.87MB 0.6s

15:07:25#8 sha256:2345e1e5f82d8963240db3c8e8ccfd431d0962d14219e24bbcc756ef217bba48 17.58MB / 17.58MB 0.7s

15:07:25#8 sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c 5.24MB / 51.87MB 0.7s

15:07:25#8 sha256:9918064ebccea7fc961fe71dad46105b217763b4b1b3a9dfa7bee2ab29d2039b 50.50MB / 50.50MB 0.7s done

15:07:25#8 sha256:2345e1e5f82d8963240db3c8e8ccfd431d0962d14219e24bbcc756ef217bba48 17.58MB / 17.58MB 0.8s done

15:07:25#8 sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c 32.51MB / 51.87MB 0.9s

15:07:25#8 extracting sha256:9918064ebccea7fc961fe71dad46105b217763b4b1b3a9dfa7bee2ab29d2039b

15:07:25#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 0B / 191.90MB 0.9s

15:07:25#8 sha256:24d744d599278585b9ad9ab702beb416d3f6eac9c4dee355921d3aee6045e706 0B / 4.21kB 0.9s

15:07:25#8 sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c 46.14MB / 51.87MB 1.0s

15:07:25#8 sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c 51.87MB / 51.87MB 1.1s

15:07:25#8 sha256:24d744d599278585b9ad9ab702beb416d3f6eac9c4dee355921d3aee6045e706 4.21kB / 4.21kB 1.0s done

15:07:25#8 sha256:0ed2ac5774c00e61286b9bd72324a242b0352f6ed54157ad6ccf4969e41d2418 0B / 34.79MB 1.1s

15:07:25#8 sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c 51.87MB / 51.87MB 1.1s done

15:07:25#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 17.83MB / 191.90MB 1.2s

15:07:25#8 sha256:c91e125a2c9469eb928e0a1507c0bbf008dd732affbe83742dc395c235ac8a08 0B / 2.27MB 1.2s

15:07:25#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 31.46MB / 191.90MB 1.3s

15:07:25#8 sha256:0ed2ac5774c00e61286b9bd72324a242b0352f6ed54157ad6ccf4969e41d2418 6.18MB / 34.79MB 1.3s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 46.97MB / 191.90MB 1.4s

15:07:26#8 sha256:0ed2ac5774c00e61286b9bd72324a242b0352f6ed54157ad6ccf4969e41d2418 19.92MB / 34.79MB 1.4s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 60.82MB / 191.90MB 1.5s

15:07:26#8 sha256:0ed2ac5774c00e61286b9bd72324a242b0352f6ed54157ad6ccf4969e41d2418 32.51MB / 34.79MB 1.5s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 73.40MB / 191.90MB 1.6s

15:07:26#8 sha256:0ed2ac5774c00e61286b9bd72324a242b0352f6ed54157ad6ccf4969e41d2418 34.79MB / 34.79MB 1.5s done

15:07:26#8 sha256:73ea6c88f52c01224892776f5f08b4ff2c56f0459b203497fedf117ffb99748b 0B / 451B 1.6s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 110.10MB / 191.90MB 1.8s

15:07:26#8 sha256:c91e125a2c9469eb928e0a1507c0bbf008dd732affbe83742dc395c235ac8a08 2.27MB / 2.27MB 1.7s done

15:07:26#8 sha256:73ea6c88f52c01224892776f5f08b4ff2c56f0459b203497fedf117ffb99748b 451B / 451B 1.8s done

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 126.88MB / 191.90MB 1.9s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 138.87MB / 191.90MB 2.0s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 154.14MB / 191.90MB 2.1s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 167.77MB / 191.90MB 2.2s

15:07:26#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 179.31MB / 191.90MB 2.3s

15:07:27#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 191.90MB / 191.90MB 2.4s

15:07:27#8 sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 191.90MB / 191.90MB 3.0s done

15:07:28#8 extracting sha256:9918064ebccea7fc961fe71dad46105b217763b4b1b3a9dfa7bee2ab29d2039b 3.6s done

15:07:29#8 ...

15:07:29

15:07:29#9 [stage-2 2/4] RUN apk update     && apk upgrade     && apk add --no-cache ca-certificates tzdata     && update-ca-certificates 2>/dev/null || true

15:07:29#9 0.286 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz

15:07:29#9 0.520 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz

15:07:29#9 1.010 v3.18.2-594-g7843f08683d [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]

15:07:29#9 1.010 v3.18.3-1-g2df25494364 [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]

15:07:29#9 1.010 OK: 20063 distinct packages available

15:07:29#9 1.457 OK: 7 MiB in 15 packages

15:07:29#9 1.555 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz

15:07:29#9 1.875 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz

15:07:29#9 2.412 (1/2) Installing ca-certificates (20230506-r0)

15:07:29#9 2.461 (2/2) Installing tzdata (2023c-r1)

15:07:29#9 2.615 Executing busybox-1.36.1-r2.trigger

15:07:29#9 2.621 Executing ca-certificates-20230506-r0.trigger

15:07:29#9 2.687 OK: 11 MiB in 17 packages

15:07:29#9 DONE 4.2s

15:07:29

15:07:29#8 [builder 1/6] FROM docker.io/library/node:16@sha256:6cd6581a9ae814ebbc8077afd63ecbf4d37f9b59ac9d9304a1b5a9e743ac13e0

15:07:29#8 extracting sha256:2345e1e5f82d8963240db3c8e8ccfd431d0962d14219e24bbcc756ef217bba48

15:07:29#8 extracting sha256:2345e1e5f82d8963240db3c8e8ccfd431d0962d14219e24bbcc756ef217bba48 0.6s done

15:07:30#8 extracting sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c

15:07:33#8 extracting sha256:947969e624beff93eed664f9f52a08712f3d1e12cadbdf929ff928f93d2c383c 3.0s done

15:07:33#8 extracting sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669

15:07:34#8 ...

15:07:34

15:07:34#10 [builder2 1/6] FROM docker.io/library/golang@sha256:bc5f0b5e43282627279fe5262ae275fecb3d2eae3b33977a7fd200c7a760d6f1

15:07:34#10 resolve docker.io/library/golang@sha256:bc5f0b5e43282627279fe5262ae275fecb3d2eae3b33977a7fd200c7a760d6f1 0.0s done

15:07:34#10 sha256:c0a97f921be39c0e7e73e34e3d4deb2765eace407c212fd0d3b277a8cd989a96 1.58kB / 1.58kB done

15:07:34#10 sha256:99f8cec02f0a61df4f8a8998eb5b658b8dd23738d59fdb8eb9f0314175d45764 6.86kB / 6.86kB done

15:07:34#10 sha256:bc5f0b5e43282627279fe5262ae275fecb3d2eae3b33977a7fd200c7a760d6f1 2.36kB / 2.36kB done

15:07:34#10 sha256:785ef8b9b236a5f027f33cae77513051704c0538bff455ff5548105c954c3b1c 49.56MB / 49.56MB 2.4s done

15:07:34#10 sha256:5a6dad8f55ae6c733e986316bd08205c8b2c41640bf8d08ff6e9bbcb6884304f 24.03MB / 24.03MB 2.2s done

15:07:34#10 sha256:bd36c7bfe5f4bdffcc0bbb74b0fb38feb35c286ea58b5992617fb38b0c933603 64.11MB / 64.11MB 3.2s done

15:07:34#10 extracting sha256:785ef8b9b236a5f027f33cae77513051704c0538bff455ff5548105c954c3b1c 3.4s done

15:07:34#10 sha256:f9e56f8fc7184d9d3111c02d7ad7d3e3e6cddfd6c0f8bde653720b14d76a3233 100.22MB / 100.22MB 4.5s done

15:07:34#10 sha256:9e59e6b803ed24f34e9d1001d46221a69fa46b48d7d007de7d32fc07d031a408 92.27MB / 92.27MB 4.6s done

15:07:34#10 sha256:5e649a4c4e0bfd0c56b695ffd1199960a518ec1f7fdb98dc7ad345dc0c5b0f6f 156B / 156B 3.6s done

15:07:34#10 extracting sha256:5a6dad8f55ae6c733e986316bd08205c8b2c41640bf8d08ff6e9bbcb6884304f 0.8s done

15:07:34#10 extracting sha256:bd36c7bfe5f4bdffcc0bbb74b0fb38feb35c286ea58b5992617fb38b0c933603 3.1s

15:07:34#10 extracting sha256:bd36c7bfe5f4bdffcc0bbb74b0fb38feb35c286ea58b5992617fb38b0c933603 3.2s done

15:07:34#10 extracting sha256:9e59e6b803ed24f34e9d1001d46221a69fa46b48d7d007de7d32fc07d031a408

15:07:38#10 extracting sha256:9e59e6b803ed24f34e9d1001d46221a69fa46b48d7d007de7d32fc07d031a408 3.3s done

15:07:38#10 extracting sha256:f9e56f8fc7184d9d3111c02d7ad7d3e3e6cddfd6c0f8bde653720b14d76a3233

15:07:43#10 ...

15:07:43

15:07:43#8 [builder 1/6] FROM docker.io/library/node:16@sha256:6cd6581a9ae814ebbc8077afd63ecbf4d37f9b59ac9d9304a1b5a9e743ac13e0

15:07:43#8 extracting sha256:87da2254b9de06a71bc1828dec0a28f6a16af7cade75310533cf5cff9ac7e669 8.3s done

15:07:43#8 extracting sha256:24d744d599278585b9ad9ab702beb416d3f6eac9c4dee355921d3aee6045e706 done

15:07:43#8 extracting sha256:0ed2ac5774c00e61286b9bd72324a242b0352f6ed54157ad6ccf4969e41d2418 1.6s done

15:07:43#8 extracting sha256:c91e125a2c9469eb928e0a1507c0bbf008dd732affbe83742dc395c235ac8a08 0.1s done

15:07:43#8 extracting sha256:73ea6c88f52c01224892776f5f08b4ff2c56f0459b203497fedf117ffb99748b done

15:07:43#8 DONE 19.2s

15:07:43

15:07:43#10 [builder2 1/6] FROM docker.io/library/golang@sha256:bc5f0b5e43282627279fe5262ae275fecb3d2eae3b33977a7fd200c7a760d6f1

15:07:43#10 extracting sha256:f9e56f8fc7184d9d3111c02d7ad7d3e3e6cddfd6c0f8bde653720b14d76a3233 5.6s done

15:07:43#10 ...

15:07:43

15:07:43#11 [builder 2/6] WORKDIR /build

15:07:47#11 ...

15:07:47

15:07:47#10 [builder2 1/6] FROM docker.io/library/golang@sha256:bc5f0b5e43282627279fe5262ae275fecb3d2eae3b33977a7fd200c7a760d6f1

15:07:47#10 extracting sha256:5e649a4c4e0bfd0c56b695ffd1199960a518ec1f7fdb98dc7ad345dc0c5b0f6f done

15:07:47#10 DONE 22.9s

15:07:47

15:07:47#12 [builder2 2/6] WORKDIR /build

15:07:48#12 DONE 0.8s

15:07:48

15:07:48#11 [builder 2/6] WORKDIR /build

15:07:48#11 DONE 4.5s

15:07:48

15:07:48#13 [builder 3/6] COPY ./web .

15:07:48#13 DONE 0.1s

15:07:48

15:07:48#14 [builder2 3/6] COPY . .

15:07:48#14 DONE 0.1s

15:07:48

15:07:48#15 [builder 4/6] COPY ./VERSION .

15:07:48#15 DONE 0.0s

15:07:48

15:07:48#16 [builder 5/6] RUN npm install

15:08:18#16 29.78 npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

15:08:18#16 29.79 npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

15:08:19#16 30.76 npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0

15:08:19#16 31.01 npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

15:08:21#16 33.04 npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.

15:08:29#16 41.30 npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

15:08:37#16 49.45 

15:08:37#16 49.45 added 1453 packages, and audited 1454 packages in 49s

15:08:37#16 49.45 

15:08:37#16 49.45 233 packages are looking for funding

15:08:37#16 49.45   run `npm fund` for details

15:08:37#16 49.46 

15:08:37#16 49.46 6 high severity vulnerabilities

15:08:37#16 49.46 

15:08:37#16 49.46 To address all issues (including breaking changes), run:

15:08:37#16 49.46   npm audit fix --force

15:08:37#16 49.46 

15:08:37#16 49.46 Run `npm audit` for details.

15:08:39#16 DONE 51.3s

15:08:39

15:08:39#17 [builder 6/6] RUN REACT_APP_VERSION=$(cat VERSION) npm run build

15:08:40#17 0.812 

15:08:40#17 0.812 > react-template@0.1.0 build

15:08:40#17 0.812 > react-scripts build

15:08:40#17 0.812 

15:08:42#17 3.147 Creating an optimized production build...

15:08:46#17 7.275 One of your dependencies, babel-preset-react-app, is importing the

15:08:46#17 7.275 "@babel/plugin-proposal-private-property-in-object" package without

15:08:46#17 7.275 declaring it in its dependencies. This is currently working because

15:08:46#17 7.275 "@babel/plugin-proposal-private-property-in-object" is already in your

15:08:46#17 7.275 node_modules folder for unrelated reasons, but it may break at any time.

15:08:46#17 7.275 

15:08:46#17 7.275 babel-preset-react-app is part of the create-react-app project, which

15:08:46#17 7.275 is not maintianed anymore. It is thus unlikely that this bug will

15:08:46#17 7.275 ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to

15:08:46#17 7.275 your devDependencies to work around this error. This will make this message

15:08:46#17 7.275 go away.

15:08:46#17 7.275   

15:09:24#17 44.37 

15:09:24#17 44.37 Treating warnings as errors because process.env.CI = true.

15:09:24#17 44.37 Most CI servers set it automatically.

15:09:24#17 44.37 

15:09:24#17 44.37 Failed to compile.

15:09:24#17 44.37 

15:09:24#17 44.37 [eslint] 

15:09:24#17 44.37 src/App.js

15:09:24#17 44.37   Line 32:10:  'userState' is assigned a value but never used                                                                                  no-unused-vars

15:09:24#17 44.37   Line 33:10:  'statusState' is assigned a value but never used                                                                                no-unused-vars

15:09:24#17 44.37   Line 86:6:   React Hook useEffect has missing dependencies: 'loadStatus' and 'loadUser'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/ChannelsTable.js

15:09:24#17 44.37   Line 21:18:   Missing '()' invoking a constructor                                                                              new-parens

15:09:24#17 44.37   Line 97:6:    React Hook useEffect has a missing dependency: 'loadChannels'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

15:09:24#17 44.37   Line 102:5:   Expected a default case                                                                                          default-case

15:09:24#17 44.37   Line 251:34:  Array.prototype.sort() expects a value to be returned at the end of arrow function                               array-callback-return

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/Footer.js

15:09:24#17 44.37   Line 28:6:   React Hook useEffect has a missing dependency: 'remainCheckTimes'. Either include it or remove the dependency array                                                                    react-hooks/exhaustive-deps

15:09:24#17 44.37   Line 40:13:  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank

15:09:24#17 44.37   Line 47:13:  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/GitHubOAuth.js

15:09:24#17 44.37   Line 8:24:   'setSearchParams' is assigned a value but never used                                                                              no-unused-vars

15:09:24#17 44.37   Line 10:10:  'userState' is assigned a value but never used                                                                                    no-unused-vars

15:09:24#17 44.37   Line 12:10:  'processing' is assigned a value but never used                                                                                   no-unused-vars

15:09:24#17 44.37   Line 12:22:  'setProcessing' is assigned a value but never used                                                                                no-unused-vars

15:09:24#17 44.37   Line 46:6:   React Hook useEffect has missing dependencies: 'searchParams' and 'sendCode'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/LoginForm.js

15:09:24#17 44.37   Line 13:24:  'setSearchParams' is assigned a value but never used                                                             no-unused-vars

15:09:24#17 44.37   Line 14:10:  'submitted' is assigned a value but never used                                                                   no-unused-vars

15:09:24#17 44.37   Line 16:10:  'userState' is assigned a value but never used                                                                   no-unused-vars

15:09:24#17 44.37   Line 30:6:   React Hook useEffect has a missing dependency: 'searchParams'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/LogsTable.js

15:09:24#17 44.37   Line 16:7:    'MODE_OPTIONS' is assigned a value but never used                                                           no-unused-vars

15:09:24#17 44.37   Line 49:10:   'searching' is assigned a value but never used                                                              no-unused-vars

15:09:24#17 44.37   Line 143:6:   React Hook useEffect has a missing dependency: 'refresh'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

15:09:24#17 44.37   Line 145:9:   'searchLogs' is assigned a value but never used                                                             no-unused-vars

15:09:24#17 44.37   Line 164:9:   'handleKeywordChange' is assigned a value but never used                                                    no-unused-vars

15:09:24#17 44.37   Line 177:30:  Array.prototype.sort() expects a value to be returned at the end of arrow function                          array-callback-return

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/OperationSetting.js

15:09:24#17 44.37   Line 77:5:  Expected a default case  default-case

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/OtherSetting.js

15:09:24#17 44.37   Line 40:6:  React Hook useEffect has a missing dependency: 'getOptions'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

15:09:24#17 44.37 

15:09:24#17 44.37 src/components/PasswordResetConfirm.js

15:09:24#17 44.37   Line 3:32:   'showInfo' is defined but never used                                                                             no-unused-vars

15:09:24#17 44.37   Line 3:54:   'showSuccess' is defined but never used                                                                          no-unused-vars

15:09:24#17 44.37   Line 20:24:  'setSearchParams' is assigned a value but never used                                                             no-unused-vars

15:09:24#17 44.37   Line 28:6:   React Hook useEffect has a missing dependency: 'searchParams'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

15:09:24#17 44.37 

15:09:25#17 44.37 src/components/PasswordResetForm.js

15:09:25#17 44.37   Line 13:28:  'setTurnstileEnabled' is assigned a value but never used  no-unused-vars

15:09:25#17 44.37   Line 14:28:  'setTurnstileSiteKey' is assigned a value but never used  no-unused-vars

15:09:25#17 44.37 

15:09:25#17 44.37 src/components/PersonalSetting.js

15:09:25#17 44.37   Line 4:42:  'showNotice' is defined but never used  no-unused-vars

15:09:25#17 44.37 

15:09:25#17 44.37 src/components/RedemptionsTable.js

15:09:25#17 44.37   Line 2:31:  'Message' is defined but never used                                                                                 no-unused-vars

15:09:25#17 44.37   Line 4:32:  'showInfo' is defined but never used                                                                                no-unused-vars

15:09:25exit status 1

15:09:25#17 44.37   Line 70:6:  React Hook useEffect has a missing dependency: 'loadRedemptions'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

15:09:25#17 44.37   Line 75:5:  Expected a default case                                                                                             default-case

15:09:25#17 44.37 

15:09:25#17 44.37 src/components/RegisterForm.js

15:09:25exit status 1

15:09:25#17 44.37   Line 27:3:  React Hook useEffect contains a call to 'setShowEmailVerification'. Without a list of dependencies, this can lead to an infinite chain of updates. To fix this, pass [] as a second argument to the useEffect Hook  react-hooks/exhaustive-deps

15:09:25#17 44.37

**Comment by qingju32** [comment]
同样部署失败

**Comment by Selenium39** [comment]
+1

**Comment by RIERS** [comment]
+1

**Comment by ckt1031** [comment]
在npm部署命令前可以添加  `DISABLE_ESLINT_PLUGIN='true'` 臨時解決問題, 但是這個會關掉所有警告, 請小心使用

https://github.com/facebook/create-react-app/issues/10021#issuecomment-859813945

**Comment by Pa5sw0rd** [comment]
> 在npm部署命令前可以添加 `DISABLE_ESLINT_PLUGIN='true'` 臨時解決問題, 但是這個會關掉所有警告, 請小心使用
> 
> 所有的代碼警告會在ci環境下標示為錯誤並且自動退出, ZeaBur應該是剛剛更新了這個設定設置了環境`CI=true`
> 
> [facebook/create-react-app#10021 (comment)](https://github.com/facebook/create-react-app/issues/10021#issuecomment-859813945)

zeabur在哪里修改这个，环境变量么

**Comment by Pa5sw0rd** [comment]
谢谢大佬

**Comment by Cherry291** [comment]
同样部署失败，zeabur添加哪个环境变量

**Comment by songquanpeng** [comment]
我已经修复了该问题
