### ISSUE TITLE
希望统一流的返回格式

### ISSUE THREAD

**Issue by isdkz** [songquanpeng/one-api#372]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
有一些项目是通过 finish_reason 的值是否为 stop 来确定流什么时候结束的，而 one-api 中智普ai返回的只有最后一个有 finish_reason 这个属性，文心一言则是所有的 finish_reason 属性的值都是 stop 

**预期结果**
openai：
[![pPVvjFH.png](https://s1.ax1x.com/2023/08/08/pPVvjFH.png)](https://imgse.com/i/pPVvjFH)

**相关截图**
智普ai：
[![pPVxkTg.png](https://s1.ax1x.com/2023/08/08/pPVxkTg.png)](https://imgse.com/i/pPVxkTg)

文心一言：
[![pPVxmpn.png](https://s1.ax1x.com/2023/08/08/pPVxmpn.png)](https://imgse.com/i/pPVxmpn)

**Comment by songquanpeng** [comment]
已合并，已修复
