### ISSUE TITLE
error unmarshalling stream response: invalid character 'r' looking for beginning of value 

### ISSUE THREAD

**Issue by codesdevs** [songquanpeng/one-api#375]
error unmarshalling stream response: invalid character 'r' looking for beginning of value 
请问这是什么问题？gpt模型可以，其他的都不行

**Comment by glzjin** [comment]
其他的是什么模型。。。。什么配置。。。什么操作。。。得说清楚呀。。。

**Comment by songquanpeng** [comment]
盲猜渠道配置错了，如果不是，重开issue

**Comment by Gavincent1** [comment]
> error unmarshalling stream response: invalid character 'r' looking for beginning of value 请问这是什么问题？gpt模型可以，其他的都不行

解决了吗？我也是这个问题

**Comment by ExpressGit** [comment]
error unmarshalling stream response: invalid character 'r' looking for beginning of value

nodejs 访问 oneapi 文心 ERNIE_Bot接口 报错

**Comment by kitaev-chen** [comment]
> error unmarshalling stream response: invalid character 'r' looking for beginning of value
> 
> nodejs 访问 oneapi 文心 ERNIE_Bot接口 报错

嗯，目前只有文心看到这个报错。
