### ISSUE TITLE
一口氣出4個建議

### ISSUE THREAD

**Issue by mmwong1984** [songquanpeng/one-api#379]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
- 為每個用戶(分類)建立速率限制，防止濫用
- 提供測試模式，方便管理員測試渠道
- 移除api key長度限制
- 為網站提供一個中英文的語言選擇器，而不是兩個網站，一個中文，一個英文
**应用场景**
防止濫用，等

**Comment by ckt1031** [comment]
如果要實現語言選擇器, 即代表要重構前後端所有代碼

*感覺ROI不大, 意義不大*

**Comment by mmwong1984** [comment]
你都知我既情景啦

**Comment by ckt1031** [comment]
API KEY 的長度是數據庫Schema的問題, 在官方渠道, 無須進行更改, 不對小眾鏡像站作兼容

**Comment by mmwong1984** [comment]
………
你認真？

**Comment by ckt1031** [comment]
測試模式：你可以參考 README, `Bearer sk-xxxxxxxxxx-[頻道ID]` 對個別頻道進行測試
如果你想測試批量頻道, 請創建個別帳號, 自行進行分組

**Comment by mmwong1984** [comment]
有咩？
我陣係唔知wor

**Comment by mmwong1984** [comment]
因矛盾而關閉，自行跟 @ckt1031 討論

**Comment by songquanpeng** [comment]
第一个已经有相关issue了，这个在计划内，其他的我认同@ckt1031

**Comment by mmwong1984** [comment]
非常同意，但是我不懂code
呵呵
明白你家的不耐煩

**Comment by songquanpeng** [comment]
难道我还要先给你道个歉吗？离谱

**Comment by mmwong1984** [comment]
ze怎麼理解為這樣呢？

**Comment by songquanpeng** [comment]
开源项目，不能指望来个人提个需求我就得照做吧，我得考虑roi吧，考虑项目的发展方向和后续的可维护性吧，项目维护到现在已经花费我很多精力了，本来就是免费使用，再冷嘲热讽合适么

**Comment by mmwong1984** [comment]
我什麼時候冷嘲热讽呢
只是說你們
- 理由合理
- 實現有困難
沒有啦！

**Comment by mmwong1984** [comment]
不是

**Comment by mmwong1984** [comment]
對我來說是類似逗號或是句號的意思

**Comment by jaydong2016** [comment]
哈哈，这就是因为香港人不懂内地人的语气词导致~
