### ISSUE TITLE
支持给用户、用户组或者 key 指定渠道

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#38]
如题

**Comment by songquanpeng** [comment]
确实，不同的渠道质量不一样，我想想怎么实现好一些。

**Comment by aiastia** [comment]
> 确实，不同的渠道质量不一样，我想想怎么实现好一些。
有些想法 
1创建令牌的时候选择需要使用的渠道，（默认新添加的渠道是否自动添加 进令牌 和 删除的渠道的自动删除从令牌移除 。 在后台配置）
2渠道能指定 是使用3.5 还是4还是两者  还有调用的倍率？ 不同渠道的计算视乎不一样。
3把token 总数  放 在用户上 （这样解决删除令牌  兑换的次数就没了的 尴尬情况） 充值兑换是 在用户id 上  令牌只显示调用不同渠道 实际 使用的 和算上倍率后的？
4渠道 能显示所有的消耗（有趋势图感觉更棒了）

**Comment by songquanpeng** [comment]
v0.4.0 已经实现了分组功能。

**Comment by zktadmin** [comment]
现在分组只有默认、default、vip、svip，最好可以自定义分组，创建令牌可以选择到不同的分组。  
我可以把azure的放在一个分组，官方原生的一个分组、或者把相同的模型放在一个分组中。创建的令牌选择对应的分组！
