### ISSUE TITLE
全局api请求频率限制是多少？

### ISSUE THREAD

**Issue by CharwinYAO** [songquanpeng/one-api#381]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
默认的api请求频率限制是多少？
我看代码里面common/constants.go里是3分钟180次。要怎么提高呢？

**相关截图**
![Screenshot_20230810_120457_com huawei browser](https://github.com/songquanpeng/one-api/assets/48556254/916a2c3e-fe44-4dc3-9392-6589974c38c8)

**Comment by songquanpeng** [comment]
目前没有限制

**Comment by CharwinYAO** [comment]
> 

好的。那图中的GlobalApiRateLimitNum是代表什么的限制？

**Comment by CharwinYAO** [comment]
> 目前没有限制
好的。那图中的GlobalApiRateLimitNum是代表什么的限制？

**Comment by songquanpeng** [comment]
私有api
