### ISSUE TITLE
前端列表渲染

### ISSUE THREAD

**Issue by JC0v0** [songquanpeng/one-api#382]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
点击下一页，一直增加列表
**复现步骤**
**预期结果**

**相关截图**
![MVD2T8U1R~2TUG3CSU`V1 M](https://github.com/songquanpeng/one-api/assets/108552928/4b8ba409-9eb6-4f49-a668-7b62fb90d02e)
![7P$}M1P{P$79}AKV{ %QPKB](https://github.com/songquanpeng/one-api/assets/108552928/21bc5c8a-9c49-4432-b9c8-cfc161bcc523)

**Comment by songquanpeng** [comment]
Okay

**Comment by songquanpeng** [comment]
跟 #287 重复哈，先关了，以那个 issue 为准。
