### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by codesdevs** [songquanpeng/one-api#385]
<img width="872" alt="image" src="https://github.com/songquanpeng/one-api/assets/58060741/74ca729a-be59-4f72-8da3-b73fad3f300a">
<img width="994" alt="image" src="https://github.com/songquanpeng/one-api/assets/58060741/8c8a4290-fc7e-4294-b6c5-47454c85370d">

**Comment by songquanpeng** [comment]
无法复现，看报错是没提供模型参数，如果问题依旧存在重开 issue
