### ISSUE TITLE
关闭了密码登录  root也没办法登录了....

### ISSUE THREAD

**Issue by hhfmiirvaxb943** [songquanpeng/one-api#386]
关闭了密码登录  root也没办法登录了....

**Comment by caotao94** [comment]
+1

**Comment by caotao94** [comment]
我把db文件下下来，sqllite把值置true就可以了

**Comment by songquanpeng** [comment]
已经加了提示

**Comment by leoncool23** [comment]
> 我把db文件下下来，sqllite把值置true就可以了

我也遇到这个问题了，root无法登录，提示关闭了密码登录 
请问下载哪个文件？ 我用的是宝塔 docker部署的。
