### ISSUE TITLE
版本 `v0.2.1-alpha` 版本令牌没有次数显示了

### ISSUE THREAD

**Issue by hbytw** [songquanpeng/one-api#39]
充值也充不上，编辑修改保存也没有，调用提示 request to https://www.xxx.ml/v1/chat/completions failed, reason: getaddrinfo ENOTFOUND xxxx

**Comment by songquanpeng** [comment]
从 `v0.2.0` 开始次数就被废弃了，现在配额的单位是 token，见 `v0.2.0` 的更新日志。

**Comment by songquanpeng** [comment]
另外这个调用报错看上去是 Node.js 的报错，看上去并不是系统本身的问题。
