### ISSUE TITLE
实现 https://api.openai.com/api/v1/chat/completions  get 接口 做到更好兼容性。

### ISSUE THREAD

**Issue by thinker007** [songquanpeng/one-api#390]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
![image](https://github.com/songquanpeng/one-api/assets/1329869/28f690e2-4033-4b55-b3e6-7241e9c02418)
按照上图返回结果，部分客户端会以此来检测api url 配置是否正确。
**应用场景**

**Comment by songquanpeng** [comment]
哪些客户端会这样呢？

**Comment by thinker007** [comment]
> 哪些客户端会这样呢？

配错了，请忽略
