### ISSUE TITLE
本地大模型配置的说明文档

### ISSUE THREAD

**Issue by bruceye777** [songquanpeng/one-api#391]
[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
目前官方支持多种大模型，但是都是非本地部署的大模型，我看了下以前的issue，说是可以通过自定义渠道实现，

**预期结果**
官方能否给出一个具体的例子，说明如何添加本地部署的大语言模型，多谢！

**Comment by glzjin** [comment]
看起来得写个 proxy。

**Comment by songquanpeng** [comment]
如果本地部署的模型支持 OpenAI 格式的接口，那就用自定义渠道设置 base url 即可，否则需要 adaptor 转换为 OpenAI 格式。
