### ISSUE TITLE
局域网环境部署one-api和Chatgpt-next-web，使用ip访问，Chatgpt-next-web发送到oneapi后，无返回消息

### ISSUE THREAD

**Issue by junmingzha** [songquanpeng/one-api#394]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

局域网环境，两个linux虚拟机(10.0.202.100, 10.0.202.101)，一个(10.0.202.100)docker部署one-api,  另一个docker(10.0.202.101)部署Chatgpt-next-web, one-api配置了令牌，Chatgpt-next-web配置url: http://10.0.202.100:3000和令牌, 在Chatgpt-next-web输入信息，一直等待，无返回。 one-api的日志可以看到以下内容，应该是调用了openai的接口，但为什么Chatgpt-next-web没返回？
[GIN] 2023/08/11 - 23:09:27 | 204 |      30.227µs |      10.1.1.204 | OPTIONS  "/dashboard/billing/usage?start_date=2023-08-01&end_date=2023-08-12"
[GIN] 2023/08/11 - 23:09:27 | 204 |      126.25µs |      10.1.1.204 | OPTIONS  "/dashboard/billing/subscription"
[GIN] 2023/08/11 - 23:09:27 | 200 |    3.569038ms |      10.1.1.204 | GET      "/dashboard/billing/usage?start_date=2023-08-01&end_date=2023-08-12"
[GIN] 2023/08/11 - 23:09:27 | 200 |   10.093449ms |      10.1.1.204 | GET      "/dashboard/billing/subscription"
[GIN] 2023/08/11 - 23:09:34 | 204 |      17.922µs |      10.1.1.204 | OPTIONS  "/v1/chat/completions"
[GIN] 2023/08/11 - 23:09:34 | 200 |    141.8763ms |      10.1.1.204 | POST     "/v1/chat/completions"

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
你应该贴 ChatGPT Next Web 的控制台报错，另外这个看上去并不是 One API 的问题

**Comment by songquanpeng** [comment]
仍不能解决提供更多信息后重开 issue
