### ISSUE TITLE
在zeabur的平台上部署更新失败后回滚导致"无效的令牌"

### ISSUE THREAD

**Issue by Cherry291** [songquanpeng/one-api#395]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当前版本：0.5.1
在zeabur更新部署失败后，我回滚到前一个可用版本，这也导致了one-api服务的重新启动，我前端的Web GPT Next就报错“令牌无效”，重新输入也无效，必须重新开一个浏览器或者把密码删掉，重新再输入，之前记住访问密码的用户都误以为密码改了，没有修改密码，不清空重新输入或者清除缓存重新输入密码就始终“无效令牌”
<img width="861" alt="1a211388adeecbc7a34ca04eb6237df" src="https://github.com/songquanpeng/one-api/assets/71474660/c418576a-d9eb-40c4-9b9e-b195d321b6cf">

**复现步骤**
之前任意一个已经保存访问密码的用户，都会出现“无效的令牌”，影响较大，不知道是系统重新启动导致的，还是更新失败回滚导致的，回滚应该是和之前情况一样的
**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
所以是数据库数据丢了么？

**Comment by songquanpeng** [comment]
都不是，数据丢了没有？你看一下之前的令牌还在不在，我只想确认这一点

**Comment by Cherry291** [comment]
之前的令牌和渠道都在，我的管理员账号也还能登录，进去还是和之前一样的

**Comment by songquanpeng** [comment]
那这看起来并不是 One API 的问题，你说的那个什么访问密码是客户端行为

**Comment by songquanpeng** [comment]
只要令牌正确 One API 就会给出响应

**Comment by Cherry291** [comment]
令牌是保存在vercel环境变量 一直没变 目前解决是让用户重新换一个浏览器 还是同样的访问密码 或者之前页面把密码先清理 访问一下 提示令牌无效 重新再输入回去 就可以恢复正常访问了，每一个用户都这样子换浏览器或者 清空访问密码访问一下触发一次真正的无效，再重新把访问密码又输回去就能解决 这个影响比较大

**Comment by songquanpeng** [comment]
这个看上去不是 One API 的问题，既然令牌没变为什么会报错令牌无效？

**Comment by Cherry291** [comment]
![image](https://github.com/songquanpeng/one-api/assets/71474660/6de83629-4dc9-4e9d-8319-2bf551159553)
重新尝试了如果访问密码错误是的在vercel的提示是这个错误，但是目前来说是报的令牌无效，切换新的浏览器访问就没问题了，令牌无效的错误提示应该来自oneapi后端

**Comment by songquanpeng** [comment]
抓包看一下 ChatGPT Next Web 发送的请求里带的令牌到底是不是 One API 的令牌
