### ISSUE TITLE
文心千帆的向量模型接口问题（请求input是数组报错）

### ISSUE THREAD

**Issue by LiZhouYan** [songquanpeng/one-api#397]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
文心千帆的向量模型接口问题（请求input是数组报错）
one-api的向量接口入参的input可以是字符串或者数组，但是针对文心千帆做的兼容有问题，只有字符串的可以使用但是数组的不可以使用，报错信息：
{
	"error": {
		"message": "embeddings max batch size is 16, and can not be 0",
		"type": "baidu_error",
		"param": "",
		"code": 336003
	}
}
文心千帆自己的向量接口Embedding-V1也是支持的
参考地址：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/alj562vvu
**复现步骤**
复现方式，在one-api向量接口
curl --request POST \
  --url http://127.0.0.1:3000/v1/embeddings \
  --header 'Authorization: Bearer sk-xxxx' \
  --header 'Content-Type: application/json' \
  --header 'content-type: application/json' \
  --data '{
    "model":"text-embedding-ada-002",
    "input":[
        "nihao",
        "sss"
    ]
}'
**预期结果**

{
    "object":"list",
    "data":[
        {
            "object":"embedding",
            "index":0,
            "embedding":Array[1536]
        },
        {
            "object":"embedding",
            "index":1,
            "embedding":Array[1536]
        }
    ],
    "model":"text-embedding-ada-002-v2",
    "usage":{
        "prompt_tokens":3,
        "total_tokens":3
    }
}
**相关截图**
如果没有的话，请删除此节。

**Comment by LiZhouYan** [comment]
类似其他issues只要文心千帆与知识库相结合有问题的，都是有涉及到向量接口的问题

**Comment by songquanpeng** [comment]
okay，最近处理

**Comment by igophper** [comment]
> okay，最近处理

看一下是这样吗

**Comment by songquanpeng** [comment]
稍等哈，在 de 其他地方的 bug

**Comment by songquanpeng** [comment]
已经合并了
