### ISSUE TITLE
令牌消耗统计不准确/误差

### ISSUE THREAD

**Issue by AiZyc** [songquanpeng/one-api#399]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，尤其是常见问题部分
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
较高并发请求的情况下，令牌的统计消耗错误，实际使用和记录值有偏差。

**复现步骤**

用下面的Python脚本进行测试请求。
```python
import time
import requests
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor

def send_request(api_key, delay, base_url, timeout):
    url = f"{base_url}/v1/chat/completions"  # 构建完整的URL

    headers = {
        'Authorization': f'Bearer {api_key}',
        'Content-Type': 'application/json',
    }

    data = '{"messages":[{"content":"echo hi","role":"user"}],"model":"gpt-3.5-turbo","stream":false,"max_tokens":1}'

    time.sleep(delay)
    
    start_time = time.time()

    try:
        response = requests.request("POST", url, headers=headers, data=data, timeout=timeout)
        end_time = time.time()
        response_json = response.json()  
        # 检查是否包含id字段
        if 'id' not in response_json:
            raise ValueError("响应中没有id字段")
        id = response_json['id']  # 获取id内容
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # 获取当前时间
        print(f"{current_time} - 状态码：{response.status_code}, ID：{id}")  # 实时打印时间、状态码、响应ID和内容

        latency = end_time - start_time  # 计算延迟
        return (True, latency)
    except (requests.exceptions.RequestException, ValueError) as err:
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # 获取当前时间
        print(f"{current_time} - 请求失败，错误：{err}")
        return (False, float('inf'))  # 如果请求失败，返回无穷大作为延迟

def main():
    api_key = "sk-yp0"  # 你的API密钥
    num_requests = 500  # 要发送的请求数量
    num_threads = 30  # 并发线程数
    request_rate = 10  # 每秒的请求次数
    base_url = "http://127.0.0.1:3000"  # 你的API接口域名
    timeout = 10 # 请求超时时间（秒）

    delay = 1 / request_rate

    results = [] 
    with ThreadPoolExecutor(max_workers=num_threads) as executor:
        futures = [executor.submit(send_request, api_key, delay, base_url, timeout) for _ in range(num_requests)]

    # 计算所有请求的平均延迟
    for future in futures:
        results.append(future.result())

    successful_requests = [result[1] for result in results if result[0]]
    failed_requests = len(results) - len(successful_requests)

    if successful_requests:  
        avg_latency = sum(successful_requests) / len(successful_requests)
        print(f"平均延迟： {avg_latency} 秒")
    else:
        print("所有请求都失败了。")

    print(f"成功的请求次数： {len(successful_requests)}")
    print(f"失败的请求次数： {failed_requests}")

if __name__ == "__main__":
    main()

```
**预期结果**

在并发的情况下，正确统计消耗情况，并与多个位置显示数据相符合。

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/11790369/fbdf3c49-5fc0-4f1f-bb05-6ff587538f75)

![image](https://github.com/songquanpeng/one-api/assets/11790369/3c92c362-0f93-4763-b329-a3910714caba)

![image](https://github.com/songquanpeng/one-api/assets/11790369/0d2ac183-3686-46aa-ab24-62c1e57f1fad)

![image](https://github.com/songquanpeng/one-api/assets/11790369/97a82ae7-aa7a-429a-8136-fc195392fd68)

![image](https://github.com/songquanpeng/one-api/assets/11790369/191dacd1-bdec-411d-8e63-06675e227be0)

**Comment by songquanpeng** [comment]
更新时已加锁。

**Comment by songquanpeng** [comment]
这种递增应该是原子的，所以 MySQL 下应该不会有问题。

Ref: https://stackoverflow.com/questions/52777969/mysql-update-tabel-set-count-count-1-concurrent-issue

至于 SQLite，其只有表级锁，高并发情况下会出现 database is locked 错误，导致两个表不一致。

不过目前也不能完全确定，抽个时间写个脚本试一下。

**Comment by songquanpeng** [comment]
更新：update 默认都是已经加了排他锁，SQLite 不一致的原因主要是数据库被锁导致 error 没有更新成功。

**Comment by chikasaki** [comment]
这里无论是mysql还是sqlite，在update时数据库引擎都会加锁。
1. 这里mysql在innodb引擎下加的是行锁，而sqllite锁粒度是基于“页”的，在锁粒度上sqlite比mysql要粗，所以从结果来讲，并发场景下sqlite出现冲突的概率更高
2. 对于mysql，在执行sql时如果发现待更新记录有上锁，会默认等待一段时间，此时间在innodb引擎下是通过innodb_lock_wait_timeout这个参数来控制的，默认是50s。对于sqllite也有类似的参数（busy_timeout），但是这个参数默认是0。也就是sqlite发现更新时记录被上锁了就直接返回error了。
3. 基于以上两个结论，在使用mysql时就算有并发冲突，因为有个默认等锁时间所以总能更新上。而使用sqllite时一旦冲突就会失败，而作者源码在更新失败时又没有进行重试，因此只有在sqlite场景下会出现这个问题

要验证也很简单，在更新处加行日志，看下sqlite场景下是否频繁出现“database is locked”错误就可以了
