### ISSUE TITLE
令牌支持次数和时长限制

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#4]
目前的项目可以用来做官方接口代理，apikey负载均衡，应用授权管理。能否再给token加个次数和时长的控制，丰富加强一下授权这方面的功能。

**Comment by songquanpeng** [comment]
可以的，实际上我之前就有打算，感谢建议，近期实现。

**Comment by songquanpeng** [comment]
已实现，已推送新版本 `v0.1.2-alpha.1`，期待测试和反馈。

**Comment by JeazW** [comment]
感谢
