### ISSUE TITLE
默认root用户编辑自身信息无权限

### ISSUE THREAD

**Issue by aohun** [songquanpeng/one-api#40]
![image](https://user-images.githubusercontent.com/37433539/235386534-66d9d188-22f4-4198-b525-8911ea304480.png)
提示无法获取比自身登记更高的权限，使用的是系统默认的root账号，为超级管理员

**Comment by aohun** [comment]
已通过修改role判断代码，自行处理了

**Comment by songquanpeng** [comment]
编辑自己的信息应该使用个人设置里面的入口。



---Original---
From: ***@***.***&gt;
Sent at: 2023年5月1日(Mon) AM9:04
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 默认root用户编辑自身信息无权限 (Issue #40)




 

 提示无法获取比自身登记更高的权限，使用的是系统默认的root账号，为超级管理员
