### ISSUE TITLE
【百度文心千帆】支持填写secretKey|apiKey，兼容accessToken，支持自动刷新accessToken

### ISSUE THREAD

**Issue by igophper** [songquanpeng/one-api#401]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
【百度文心千帆】支持填写secretKey|apiKey，兼容accessToken，支持自动刷新accessToken #400 
**应用场景**

![image](https://github.com/songquanpeng/one-api/assets/34326532/5c7565a0-b0cb-45e6-bf3a-9abb45fc3d20)

**Comment by temberature** [comment]
直接accessToken 是不支持了吗 ：）

<img width="285" alt="image" src="https://github.com/songquanpeng/one-api/assets/3735863/142b5b1f-2658-4689-bc16-cabbb375d672">
