### ISSUE TITLE
使用PostgreSQL，无法添加令牌

### ISSUE THREAD

**Issue by gptvpn** [songquanpeng/one-api#403]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用PostgreSQL，从Mysql迁移数据库过来，原来Key无法使用，显示Key错误，添加新Key也添加不了，报错见下面截图。
![QQ图片20230812224546](https://github.com/songquanpeng/one-api/assets/137971746/6b3b9308-42c1-4041-a1e1-229544c37849)

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
复现不了哈，估计是数据迁移的问题。
![image](https://github.com/songquanpeng/one-api/assets/39998050/d9cde9c8-42fe-4527-85cc-37c037ef81b3)

![image](https://github.com/songquanpeng/one-api/assets/39998050/292098a1-61a4-42df-82c9-3f2a6a6e257d)
