### ISSUE TITLE
渠道全部被自动关闭

### ISSUE THREAD

**Issue by Cherry291** [songquanpeng/one-api#411]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

今天提问的时候 出现“当前分组 default 下对于模型 gpt-3.5-turbo 无可用渠道”，进入后台查看 所有渠道自动关闭了，同时显示超高延迟，然后手动打开渠道解决，为什么会自动关闭全部的渠道呢？

**复现步骤**

**预期结果**

**相关截图**
![d3fe7b04efa8ff9ac71be0813e4eb6d1](https://github.com/songquanpeng/one-api/assets/71474660/2fb31f37-2a95-4a0f-b4d6-19b5d90d1782)
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
你开启了定期测试，然后延迟超过了后台设置的阈值，就给禁用了。

而且你没有配置 SMTP 和邮箱地址，导致报警邮件没收到。

**Comment by Cherry291** [comment]
![image](https://github.com/songquanpeng/one-api/assets/71474660/878c9331-badc-4d8e-bcff-5ee4a36c73bb)
但事实上 我没有设置延迟超时关闭渠道

**Comment by popdo** [comment]
同样问题。未设置关闭，但自动关闭了
