### ISSUE TITLE
国产大模型 Token计算存在BUG

### ISSUE THREAD

**Issue by ClarenceDan** [songquanpeng/one-api#415]
目前实测发现：
1. 文心一言、通义千问均存在token计算bug
2. bug同时出现在提示部分和补全部分
3. chatglm没有补全部分，不确定是否为bug
截图如下：
![image](https://github.com/songquanpeng/one-api/assets/48417261/3f06ccfc-805d-4da3-8574-42685276a71d)
chatglm截图如下：
![image](https://github.com/songquanpeng/one-api/assets/48417261/5fae3104-8a01-4854-9fa1-0fa8527d017a)

**Comment by glzjin** [comment]
![image](https://github.com/songquanpeng/one-api/assets/7975407/459a083c-96ce-415d-86b0-d71c62adbc96)

![image](https://github.com/songquanpeng/one-api/assets/7975407/dfa81135-de3a-4b59-bab9-8f7891beff6a)


官方接口是累加，usage对于stream取最后一个就行。

One-API 里是直接加起来了。


![image](https://github.com/songquanpeng/one-api/assets/7975407/8a59f03f-e46a-46c0-8b18-9c767ebf4fa9)


所以会这样。

**Comment by glzjin** [comment]
百度的也是这样。

![image](https://github.com/songquanpeng/one-api/assets/7975407/ba53c3a3-c33c-4ff8-93d4-85cc1e60b2ec)

![image](https://github.com/songquanpeng/one-api/assets/7975407/8ae99abb-3abd-4d82-939d-26b3fd880ca3)


![image](https://github.com/songquanpeng/one-api/assets/7975407/ab23cdd9-00b5-4d73-a4b2-2fd0612f7c2f)

**Comment by songquanpeng** [comment]
怪不得呢，感谢，我还没来得及排查这个问题

**Comment by songquanpeng** [comment]
明天处理

**Comment by songquanpeng** [comment]
#444 已合并
