### ISSUE TITLE
ChatGPT next web控制台无返回问题

### ISSUE THREAD

**Issue by junmingzha** [songquanpeng/one-api#416]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
局域网环境， 一个linux虚拟机(10.0.238.49)，部署one-api（端口4000）和部署Chatgpt-next-web(端口3000)  one-api配置了令牌h和渠道（使用代理10.0.202.100）, Chatgpt-next-web配置url: [one-api: http://10.0.49:4000和令牌], , 在Chatgpt-next-web输入信息，一直等待，无返回。 one-api的日志可以看到以下内容，应该是调用了openai的接口，但为什么Chatgpt-next-web没返回？
**复现步骤**

**预期结果**

**相关截图**
1. openapi的日子
![image](https://github.com/songquanpeng/one-api/assets/28426742/86302e2a-e8b5-445e-9285-064a34a647f2)
2. chatgpt next web的前端
![image](https://github.com/songquanpeng/one-api/assets/28426742/25ca4aa8-5698-4844-8290-5d4f3e0080bb)

![image](https://github.com/songquanpeng/one-api/assets/28426742/aa02e333-ec07-4217-ab3d-df9af9f6f468)

3. one-api的抓包结果

![image](https://github.com/songquanpeng/one-api/assets/28426742/339993af-39b3-4163-ae8e-deeaa6ba3983)

**Comment by igophper** [comment]
大概率你的one-api渠道配置出问题了

**Comment by junmingzha** [comment]
一些是渠道配置的截图，这个apikey和代理是可以使用的，我直接使用在chatgpt-next-web上是可以的
![image](https://github.com/songquanpeng/one-api/assets/28426742/d2f8271b-31b1-48e9-a1c3-249ae7ba9696)
![image](https://github.com/songquanpeng/one-api/assets/28426742/2f5fc064-ddcd-494f-8308-c988129089d5)
![image](https://github.com/songquanpeng/one-api/assets/28426742/45b65251-eb58-4606-a5d4-9639106cc6ce)

![image](https://github.com/songquanpeng/one-api/assets/28426742/2d73fcd8-8980-4bc4-a212-2a06518182d0)

**Comment by igophper** [comment]
好的，大概率是设置了代理导致的，晚点看一下。
你可以在one-api的机器上设置http_proxy和https_proxy试试看先

**Comment by junmingzha** [comment]
@igophper 非常非常感谢，问题解决了。您可以关闭这个issue了

**Comment by songquanpeng** [comment]
确实描述有问题，我本来想改的，但是忘掉了

**Comment by songquanpeng** [comment]
考虑到有 placeholder，一般也不会认错，先不改了

**Comment by lin-1259** [comment]
> @igophper 非常非常感谢，问题解决了。您可以关闭这个issue了

遇到同样问题了  大佬怎么解决的
