### ISSUE TITLE
增加自定义的header

### ISSUE THREAD

**Issue by sapipoZZZ** [songquanpeng/one-api#421]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
我有部分接口（如openRouter）使用需要特殊的header（如下图），是否可以支持自定义的header设定？
![image](https://github.com/songquanpeng/one-api/assets/19617283/06beaccf-0893-4792-8622-8abd6ead8b97)

**应用场景**

**Comment by igophper** [comment]
感觉可以在添加渠道的时候，在 模型重定向 的下面加上一个框框填写 自定义header

**Comment by songquanpeng** [comment]
你直接 Nginx 添加就好了

**Comment by sapipoZZZ** [comment]
> 你直接 Nginx 添加就好了

其实我所有的渠道都可以通过nginx配置搞定，那么这个开源项目是否还有必要性？

**Comment by songquanpeng** [comment]
拿你用 Nginx 试试呗。

我之所以说这个用 Nginx 加 Header 搞定，是因为已经之前有人试过了可行而且也不麻烦，其他通道都没有自定义 Header 的操作为了这个渠道单独加一个功能怎么看都不合适。
