### ISSUE TITLE
渠道编辑代理字段，更新失败

### ISSUE THREAD

**Issue by igophper** [songquanpeng/one-api#423]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
之前填写了代理字段，现在想删除，将代理字段清空，前端还是传递了代理字段，导致无法清空该字段
**复现步骤**
填写渠道代理后尝试删除代理字段
**预期结果**
代理字段正常清空
**相关截图**
<img width="1406" alt="image" src="https://github.com/songquanpeng/one-api/assets/34326532/4066c7b1-1930-45f7-a1d5-4d6f6515f2a0">

**Comment by songquanpeng** [comment]
gorm 忽略了空值，这个周末处理
