### ISSUE TITLE
使用text-embedding-ada-002知识库向量化时候  JSON 解码错误

### ISSUE THREAD

**Issue by luxl-1379** [songquanpeng/one-api#432]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
发送向量化数据时候会报这个错误，
relay error (channel #371): invalid character 'U' looking for beginning of value 
还有
relay error (channel #366): json: cannot unmarshal bool into Go struct field TextResponse.error of type controller.OpenAIError
换为使用官方的没有问题。

直接使用text-embedding-ada-002对话是可以 就是知识库向量化发送的信息报这个错误

**Comment by songquanpeng** [comment]
所以解决了吗？怎么解决的

**Comment by luxl-1379** [comment]
是因为渠道的问题，使用官方的渠道没有问题，使用的中转的是不支持这个text-embedding-ada-002模型

**Comment by songquanpeng** [comment]
那就不要在渠道设置里添加改模型



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月21日(Mon) AM10:42
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 使用text-embedding-ada-002知识库向量化时候  JSON 解码错误 (Issue #432)




 
是因为渠道的问题，使用官方的渠道没有问题，使用的中转的是不支持这个text-embedding-ada-002模型
