### ISSUE TITLE
Azure gpt-35-turbo-16k、gpt-4 等新模型测试报错：The API deployment for this resource does not exist

### ISSUE THREAD

**Issue by caixiaomao** [songquanpeng/one-api#434]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
azure 模型部署：
![image](https://github.com/songquanpeng/one-api/assets/5171685/2499256f-4132-42d8-aea0-ef35a79525d7)

测试报错：
![image](https://github.com/songquanpeng/one-api/assets/5171685/a67b1554-2520-4870-aa37-16225c7f7396)

**Comment by glzjin** [comment]
模型选上0613的版本。

**Comment by caixiaomao** [comment]
> 模型选上0613的版本。

请问是这个吗，还是一样的错误 
![image](https://github.com/songquanpeng/one-api/assets/5171685/7be94154-f19d-4985-95b6-7a6fed4e75ee)

**Comment by songquanpeng** [comment]
模型测试需要部署 gpt-3.5，这个之后加一下提示

**Comment by caixiaomao** [comment]
> 模型测试需要部署 gpt-3.5，这个之后加一下提示

哦哦，明白了，谢谢 😃

**Comment by caixiaomao** [comment]
@haymaicc 是的，默认是使用gpt-3.5 来测试的
