### ISSUE TITLE
[疑问]在error.log中有这个的报错信息，请问是什么原因？

### ISSUE THREAD

**Issue by jinghai** [songquanpeng/one-api#437]
[SYS] 2023/08/18 - 00:17:40 | failed to get token encoder for model chatglm2-6b-32k: no encoding for model chatglm2-6b-32k, using encoder for gpt-3.5-turbo 
[SYS] 2023/08/18 - 00:36:22 | failed to get token encoder for model Qwen-7B-Chat: no encoding for model Qwen-7B-Chat, using encoder for gpt-3.5-turbo 
[SYS] 2023/08/18 - 00:39:43 | failed to get token encoder for model Qwen-7B-Chat-VLLM: no encoding for model Qwen-7B-Chat-VLLM, using encoder for gpt-3.5-turbo 
[SYS] 2023/08/18 - 00:47:38 | failed to get token encoder for model ERNIE-Bot-turbo: no encoding for model ERNIE-Bot-turbo, using encoder for gpt-3.5-turbo 
[SYS] 2023/08/18 - 00:48:32 | failed to get token encoder for model SparkDesk: no encoding for model SparkDesk, using encoder for gpt-3.5-turbo

**Comment by songquanpeng** [comment]
这些没问题，是因为国产模型的模型名称  tiktoken 不识别

**Comment by Gavincent1** [comment]
解决了吗？

版本：v0.5.7-alpha.1版本中还是会出现这个问题

**Comment by songquanpeng** [comment]
这就不是报错

**Comment by Gavincent1** [comment]
> 这就不是报错

大佬，能帮忙解释一下这个错误吗？渠道我反复检查了，设置应该是没有问题，不知道为什么就是调用不成功

**Comment by Gavincent1** [comment]
> 这就不是报错

大佬有没有成功的案例设置让我们参考一下？
