### ISSUE TITLE
群成员很...

### ISSUE THREAD

**Issue by mmwong1984** [songquanpeng/one-api#441]
有问QQ群里可不可以发广告，问了才发
然后yolo踢了我
是不是有什么问题啊
+1问题还是广告问题
😑😑😑

**Comment by mmwong1984** [comment]
@yangfan-sys 恨你們
（如果taf错不好意思啊）

**Comment by songquanpeng** [comment]
应该问管理员，而不是信群友



---Original---
From: "Samantha ***@***.***&gt;
Sent at: 2023年8月18日(Fri) Noon1:43
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 群成员很... (Issue #441)




 
@yangfan-sys 恨你們
 （如果tag错不好意思啊）

**Comment by mmwong1984** [comment]
加回我吧

**Comment by mmwong1984** [comment]
fung

**Comment by mmwong1984** [comment]
🥹🥹

**Comment by mmwong1984** [comment]
![Uploading Screenshot_2023-08-18-13-45-53-958_com.tencent.mobileqq.jpg…]()

**Comment by songquanpeng** [comment]
没看到加群申请啊

**Comment by mmwong1984** [comment]
![Screenshot_2023-08-18-13-45-53-958_com tencent mobileqq](https://github.com/songquanpeng/one-api/assets/103017331/f7f6676e-ec8b-4981-8615-f7d92bbf254a)

**Comment by AiZyc** [comment]
重新申请，且后续不要刷屏+发广告。

**Comment by songquanpeng** [comment]
你去message pusher群，然后我拉你进来

**Comment by mmwong1984** [comment]
嗚嗚嗚

**Comment by mmwong1984** [comment]
群号哪里啊

**Comment by AiZyc** [comment]
One API 交流群
群号 828520184

Message Pusher 交流群
群号 824572304

**Comment by AiZyc** [comment]
关闭issue吧 无关问题~

**Comment by mmwong1984** [comment]
生气
