### ISSUE TITLE
当返回出错，oneapi不会返回

### ISSUE THREAD

**Issue by LanQian528** [songquanpeng/one-api#443]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当上游返回出错消息时，oneapi开启了stream就不会返回任何消息，而是直接关闭连接，正常来说应该返回一个出错消息才对，不返回消息会导致前端网页不会停止获取（貌似是不规范的错误消息，规范的错误消息不知道会不会触发）
**复现步骤**
请求fakeopen的代理时出现的问题，会导致前端网页一直获取而不主动断开
**预期结果**
能正常返回错误消息
**相关截图**
![73028ae76c5d840b9fd5c5226d555ce0](https://github.com/songquanpeng/one-api/assets/5499636/5a5cd3a5-6baf-4b0e-9702-5eb3700d6a90)

**Comment by songquanpeng** [comment]
上游是什么渠道？

**Comment by LanQian528** [comment]
> 上游是什么渠道？

fakeopen的逆向，以下是返回结果

![image](https://github.com/songquanpeng/one-api/assets/5499636/12ee7b3f-6243-4581-bca9-de0f23eb7aaa)

**Comment by LanQian528** [comment]
貌似已经于PR https://github.com/songquanpeng/one-api/pull/422 中修复

**Comment by songquanpeng** [comment]
好的，感谢反馈
