### ISSUE TITLE
令牌查询余额，支持按令牌查询，而不仅仅是查账号额度

### ISSUE THREAD

**Issue by Jungley8** [songquanpeng/one-api#445]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

在 令牌上 增加额度查询方式，独立查询额度，还是按账号查询额度，默认按账号

**应用场景**

下发令牌给 `别人`使用，`别人`无法查询 当前令牌的额度，虽然后台可以看。

**Comment by songquanpeng** [comment]
有这个功能，看一下设置



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月19日(Sat) Early Morning1:25
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 令牌查询余额，支持按令牌查询，而不仅仅是查账号额度 (Issue #445)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，已确定现有版本无法满足需求
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
功能描述
 
在 令牌上 增加额度查询方式，独立查询额度，还是按账号查询额度，默认按账号
 
应用场景
 
下发令牌给 别人使用，别人无法查询 当前令牌的额度，虽然后台可以看。

**Comment by piwawa** [comment]
> 有这个功能，看一下设置
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2023年8月19日(Sat) Early Morning1:25 To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [songquanpeng/one-api] 令牌查询余额，支持按令牌查询，而不仅仅是查账号额度 (Issue #445) 例行检查 我已确认目前没有类似 issue 我已确认我已升级到最新版本 我已完整查看过项目 README，已确定现有版本无法满足需求 我理解并愿意跟进此 issue，协助测试和提供反馈 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 功能描述 在 令牌上 增加额度查询方式，独立查询额度，还是按账号查询额度，默认按账号 应用场景 下发令牌给 别人使用，别人无法查询 当前令牌的额度，虽然后台可以看。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

在哪呢？

**Comment by maple-zhou** [comment]
你好，请问这个问题解决了么，我也有查询令牌余额的需求，但我在设置中没有找到相关内容。谢谢！
