### ISSUE TITLE
渠道 key 余额监控，提醒与自动禁用

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#45]
由于渠道是openai的key，是否可以增加个定时器固定时间扫描key的额度是否用完，用完则删除，这进一步可以增加提醒。

**Comment by songquanpeng** [comment]
余额监控（#11）这个会加上的，目前打算采用邮件提醒的方式。

**Comment by lmuiotctf** [comment]
嗯嗯 ，余额监控还好，就是没余额会支持自动删除key吧

**Comment by songquanpeng** [comment]
目前的打算是没余额自动禁用该 key。

**Comment by lmuiotctf** [comment]
一样的原理！期待

**Comment by songquanpeng** [comment]
OpenAI 的余额查询 API 是私有 API，而且目前貌似发生了修改，见：https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/505

我本地测试返回网页 Bad Request，所以目前余额监控先搁置了。

目前的打算是监控返回结果，如果是因为 key 的原因请求失败则禁用该 key。

**Comment by songquanpeng** [comment]
OpenAI 的文档介绍没有具体的返回例子，我在想怎么区分普通的 429 和因为 Quota 耗尽导致的 429。

https://platform.openai.com/docs/guides/error-codes/error-codes

**Comment by lmuiotctf** [comment]
那只能通过判断error的message来进行区分了，message包含Quota 的关键字就判断是没额度

**Comment by lmuiotctf** [comment]
if (res.error.message.includes("You exceeded your")) {
      message = "KEY 余额已不足,请联系 ";
    }
可以用message来，不然code 确实有时候会误杀

**Comment by songquanpeng** [comment]
有返回示例可以看一下的吗？我需要确认到底用哪一个字段。

**Comment by lmuiotctf** [comment]
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
只要包含这个error message的部分文字即可

**Comment by songquanpeng** [comment]
好的，我主要想找的就是这个具体的返回体格式。

**Comment by mrhaoji** [comment]
> 目前的打算是没余额自动禁用该 key。

建议做成可选，存在上游某些情况没有余额的时候，仍然可以通过 key 完成调用。

**Comment by songquanpeng** [comment]
不考虑这种异常情况。

这个 issue 忘记关了之前。
