### ISSUE TITLE
文心模型连续对话出现的问题

### ISSUE THREAD

**Issue by DUNKILL** [songquanpeng/one-api#452]
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
- 使用文心模型（ERNIE 和 ERNIE-turbo）时，在连续对话大概四五轮后，再次进行提问就会报错，只能重新开始对话

**复现步骤**
- 使用文心模型进行聊天，任意内容对话，大概四轮之后，提问出现报错
 `error unmarshalling stream response: invalid character 'r' looking for beginning of value `

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/91525837/33c0e788-a993-4aec-9ca2-b406fe96c389)

**Comment by DUNKILL** [comment]
- 使用版本：0.5.3-alpha.10
- 经测试，通义千问也有这样的情况出现

**Comment by DUNKILL** [comment]
- 另外在最新版本中 ChatGLM 系列模型的 Token 计算依旧无法计算补全 Token

**Comment by glzjin** [comment]
连续对话给下对话内容。

**Comment by glzjin** [comment]
> * 另外在最新版本中 ChatGLM 系列模型的 Token 计算依旧无法计算补全 Token

不好算哦，，，，官方接口没给，，，只返回了总 Token。。。

**Comment by DUNKILL** [comment]
> 连续对话给下对话内容。

任意内容都会这样，比如说连着发四次“嗨”，或者随便发点话题，大概就是四轮之后开始无法回复了，然后日志就是那个错误

**Comment by glzjin** [comment]
![IMG_3501](https://github.com/songquanpeng/one-api/assets/7975407/11f2a6be-9adb-4fa8-ab0a-61418e090efd)
![IMG_3502](https://github.com/songquanpeng/one-api/assets/7975407/a4ccd569-2a5d-429c-ad8f-b29a4af3cfe2)

**Comment by DUNKILL** [comment]
> 连续对话给下对话内容。

我搜索了一下这个报错，似乎和Redis有关系，请问你用的是OneAPI的哪个版本呀，然后Redis是哪个版本的，之前我更新的时候，Redis似乎也跟着升级了，谢谢啦

**Comment by DUNKILL** [comment]
![image](https://github.com/songquanpeng/one-api/assets/91525837/2bfbc745-d535-45a0-b992-9a4225077d7d)
![image](https://github.com/songquanpeng/one-api/assets/91525837/46f6a9d2-01dc-422f-9369-a758927f4d1a)
![image](https://github.com/songquanpeng/one-api/assets/91525837/d37d08a8-640e-4636-bd31-b1a9d618b43b)

**Comment by DUNKILL** [comment]
是不是和使用的项目有关，我也去试试原生的Next-Web
我部署的 Redis 是 7.2.0 版本

**Comment by DUNKILL** [comment]
使用原生Next-Web确实没问题，看来是二开项目的后端bug，非常感谢开发者认真回复和测试

**Comment by glzjin** [comment]
客气，这个二开的地址方便发下不？

**Comment by DUNKILL** [comment]
> 客气，这个二开的地址方便发下不？

https://github.com/Nanjiren01/AIChatWeb

**Comment by songquanpeng** [comment]
下次问题解决后请顺便把 issue 关了

**Comment by laiganc** [comment]
我也遇到过这个问题，刚开始没问题，多轮问答后出现这个问题：error unmarshalling stream response: invalid character 'r' looking for beginning of value 。产生错误的原因可能是你没有在文心大模型平台开通对应模型的付费，开通付费后没有再出现了。
