### ISSUE TITLE
API调用参数错误:xunfei api does not support non-stream mode

### ISSUE THREAD

**Issue by flashszn** [songquanpeng/one-api#455]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
API调用参数错误:xunfei api does not support non-stream mode

**复现步骤**
直接调用讯飞星火大模型，我用的v2.1

**预期结果**

API调用参数错误:xunfei api does not support non-stream mode

**Comment by songquanpeng** [comment]
他本身就是不支持非stream模式，不过确实可以适配一下



---Original---
From: "Shi ***@***.***&gt;
Sent at: 2023年8月21日(Mon) Evening11:17
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] API调用参数错误:xunfei api does not support non-stream mode (Issue #455)




 
例行检查
  
[ x] 我已确认目前没有类似 issue
 
[ x] 我已确认我已升级到最新版本
 
[ x] 我已完整查看过项目 README，尤其是常见问题部分
 
[ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
 
[ x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
问题描述
 API调用参数错误:xunfei api does not support non-stream mode
 
复现步骤
 直接调用讯飞星火大模型，我用的v2.1
 
预期结果
 
API调用参数错误:xunfei api does not support non-stream mode

**Comment by songquanpeng** [comment]
已经适配了
