### ISSUE TITLE
将国内这些大模型的response格式改成和openai一致。

### ISSUE THREAD

**Issue by flashszn** [songquanpeng/one-api#456]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
将国内这些大模型的response格式改成和openai的/completion接口一致。（建议不用/v1/completion与gpt系列区别）

**应用场景**
在调用国内大模型的时候，由于response返回的结果于openai不一致，导致已有的chatgpt应用适配新的国内模型十分的麻烦。
如果其返回格式能够通过oneapi封装，与openai返回的格式一致的话，就可以通过将已有模型直接改名为国内模型的名字的方式十分优雅的适配新的国内大模型，这对软件的生态无疑是十分重要的。
这样子，调用国内大模型，与调用openai的completion接口的模型，如'text-davinci-003'，request和response就完全一致，为已有应用的拓展可以提供一个十分优雅的解决方式。

**Comment by songquanpeng** [comment]
现在不就是这样的么



---Original---
From: "Shi ***@***.***&gt;
Sent at: 2023年8月22日(Tue) Early Morning0:13
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 将国内这些大模型的response格式改成和openai一致。 (Issue #456)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，已确定现有版本无法满足需求
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
功能描述
 将国内这些大模型的response格式改成和openai的/completion接口一致。（建议不用/v1/completion与gpt系列区别）
 
应用场景
 在调用国内大模型的时候，由于response返回的结果于openai不一致，导致已有的chatgpt应用适配新的国内模型十分的麻烦。
 如果其返回格式能够通过oneapi封装，与openai返回的格式一致的话，就可以通过将已有模型直接改名为国内模型的名字的方式十分优雅的适配新的国内大模型，这对软件的生态无疑是十分重要的。
 这样子，调用国内大模型，与调用openai的completion接口的模型，如'text-davinci-003'，request和response就完全一致，为已有应用的拓展可以提供一个十分优雅的解决方式。

**Comment by flashszn** [comment]
> 现在不就是这样的么
> […](#)
> ---Original--- From: "Shi ***@***.***&gt; Sent at: 2023年8月22日(Tue) Early Morning0:13 To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [songquanpeng/one-api] 将国内这些大模型的response格式改成和openai一致。 (Issue #456) 例行检查 我已确认目前没有类似 issue 我已确认我已升级到最新版本 我已完整查看过项目 README，已确定现有版本无法满足需求 我理解并愿意跟进此 issue，协助测试和提供反馈 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 功能描述 将国内这些大模型的response格式改成和openai的/completion接口一致。（建议不用/v1/completion与gpt系列区别） 应用场景 在调用国内大模型的时候，由于response返回的结果于openai不一致，导致已有的chatgpt应用适配新的国内模型十分的麻烦。 如果其返回格式能够通过oneapi封装，与openai返回的格式一致的话，就可以通过将已有模型直接改名为国内模型的名字的方式十分优雅的适配新的国内大模型，这对软件的生态无疑是十分重要的。 这样子，调用国内大模型，与调用openai的completion接口的模型，如'text-davinci-003'，request和response就完全一致，为已有应用的拓展可以提供一个十分优雅的解决方式。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

现在的response是不一致的，会直接返回国内的sdk的response，已有的直接换名字就会报错

**Comment by songquanpeng** [comment]
哪一个？这些都是适配过的，返回格式已经调整过了



---Original---
From: "Shi ***@***.***&gt;
Sent at: 2023年8月22日(Tue) Early Morning0:16
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 将国内这些大模型的response格式改成和openai一致。 (Issue #456)




  
现在不就是这样的么
 …
 ---Original--- From: "Shi @.&gt; Sent at: 2023年8月22日(Tue) Early Morning0:13 To: @.&gt;; Cc: @.&gt;; Subject: [songquanpeng/one-api] 将国内这些大模型的response格式改成和openai一致。 (Issue #456) 例行检查 我已确认目前没有类似 issue 我已确认我已升级到最新版本 我已完整查看过项目 README，已确定现有版本无法满足需求 我理解并愿意跟进此 issue，协助测试和提供反馈 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 功能描述 将国内这些大模型的response格式改成和openai的/completion接口一致。（建议不用/v1/completion与gpt系列区别） 应用场景 在调用国内大模型的时候，由于response返回的结果于openai不一致，导致已有的chatgpt应用适配新的国内模型十分的麻烦。 如果其返回格式能够通过oneapi封装，与openai返回的格式一致的话，就可以通过将已有模型直接改名为国内模型的名字的方式十分优雅的适配新的国内大模型，这对软件的生态无疑是十分重要的。 这样子，调用国内大模型，与调用openai的completion接口的模型，如'text-davinci-003'，request和response就完全一致，为已有应用的拓展可以提供一个十分优雅的解决方式。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
现在的response是不一致的，会直接返回国内的sdk的response，已有的直接换名字就会报错

**Comment by flashszn** [comment]
智谱GLM,我使用用一下代码使用换名字操作：
class CompletionRequest(RequestBase):
    """调用Completion接口的请求类。
    
    调用方可以一直next completion直到finish_reason为stop。
    """

    model: str
    prompt: str
    kwargs: dict

    stopped: bool = False

    def __init__(
        self,
        model: str,
        messages: list[dict[str, str]],
        **kwargs
    ):
        self.model = model
        self.prompt = ""
        
        for message in messages:
            self.prompt += message["role"] + ": " + message["content"] + "\n"
        
        self.prompt += "assistant: "

        self.kwargs = kwargs

        self.req_func = openai.Completion.acreate

    def __iter__(self):
        return self

    def __next__(self) -> dict:
        """调用Completion接口，返回生成的文本
        
        {
            "id": "id",
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "type": "text",
                        "content": "message"
                    },
                    "finish_reason": "reason"
                }
            ],
            "usage": {
                "prompt_tokens": 10,
                "completion_tokens": 20,
                "total_tokens": 30
            }
        }
        """

        if self.stopped:
            raise StopIteration()

        resp = self._req(
            model=self.model,
            prompt=self.prompt,
            **self.kwargs
        )

        if resp["choices"][0]["finish_reason"] == "stop":
            self.stopped = True

        choice0 = resp["choices"][0]

        self.prompt += choice0["text"]

        return {
            "id": resp["id"],
            "choices": [
                {
                    "index": choice0["index"],
                    "message": {
                        "role": "assistant",
                        "type": "text",
                        "content": choice0["text"]
                    },
                    "finish_reason": choice0["finish_reason"]
                }
            ],
            "usage": resp["usage"]
        }
会报错如下：
Traceback (most recent call last):
  File "/root/qqchat/pkg/qqbot/message.py", line 43, in process_normal_message
    text, finish_reason, funcs = session.query(text_message)
  File "/root/qqchat/pkg/openai/session.py", line 266, in query
    for resp in pkg.utils.context.get_openai_manager().request_completion(prompts):
  File "/root/qqchat/pkg/openai/manager.py", line 54, in request_completion
    for resp in request:
  File "/root/qqchat/pkg/openai/api/completion.py", line 72, in __next__
    if resp["choices"][0]["finish_reason"] == "stop":
KeyError: 'choices'

**Comment by songquanpeng** [comment]
哦你是指completion接口，那确实

**Comment by flashszn** [comment]
> 哦你是指completion接口，那确实

直接用/v1/completion接口会报错如下：
count_chat_completion_tokens() is not implemented for model chatglm_pro. See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.

**Comment by flashszn** [comment]
> > 哦你是指completion接口，那确实
> 
> 直接用/v1/completion接口会报错如下： count_chat_completion_tokens() is not implemented for model chatglm_pro. See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.

能否每个不能确定的接口就直接返回0，这样就能直接适配不用专门写代码

**Comment by flashszn** [comment]
> 已经确定/v1/completion是能用的了，主要原因是已有项目的适配问题，抱歉打扰了作者大大。希望能使配下/completion渠道。[狗头保命]
> 
> > > > 哦你是指completion接口，那确实
> > > 
> > > 
> > > 直接用/v1/completion接口会报错如下： count_chat_completion_tokens() is not implemented for model chatglm_pro. See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.
> > 
> > 
> > 能否每个不能确定的接口就直接返回0，这样就能直接适配不用专门写代码

其实只要在文档中说明国内大模型渠道的调用方法即可，无需再去适配一个新的渠道，这个问题我已经得到了解答。
