### ISSUE TITLE
内存占用异常

### ISSUE THREAD

**Issue by shao0222** [songquanpeng/one-api#459]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在服务刚启动的时候，如果并发较高，会出现内存占用突增
**复现步骤**
1. 重启服务
2. 使用压测工具进行并发测试：如 hey -n 10000 -c 800 -m POST -H "Authorization: Bearer ***" -d '{"model": "gpt-3.5-turbo", "messages": [{"role": "user", "content": "hi"}]}' http://localhost:3000/v1/chat/completions
3. 在压测过程中观察内存占用
4. 压测完后一段时间内存占用会慢慢下降
5. 内存恢复正常后，再次压测不会出现内存占用异常
**预期结果**

**相关截图**
<img width="896" alt="image" src="https://github.com/songquanpeng/one-api/assets/22172112/4c5200f1-976b-48dc-8a12-f68817514814">

**Comment by c121914yu** [comment]
https://github.com/songquanpeng/one-api/issues/414

可能与这个有关

**Comment by songquanpeng** [comment]
我改成了初始化时直接全部初始化，不再使用 lazy initialization

**Comment by songquanpeng** [comment]
可以再试一下，如果仍有异常，请重开
