### ISSUE TITLE
请求大佬添加360智脑

### ISSUE THREAD

**Issue by Timoshao** [songquanpeng/one-api#461]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
添加360智脑api对接
**应用场景**

**Comment by igophper** [comment]
有没有key，能提供key进行测试吗

**Comment by Timoshao** [comment]
> 有没有key，能提供key进行测试吗？可以在群里@我

申请了 还没通过

**Comment by igophper** [comment]
相似问题 #331

**Comment by songquanpeng** [comment]
周末



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月24日(Thu) Evening7:16
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 请求大佬添加360智脑 (Issue #461)




 
相似问题 #331
