### ISSUE TITLE
恢复超token错误提示

### ISSUE THREAD

**Issue by SunnyGPT** [songquanpeng/one-api#468]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
原先超token错误提示是这样的：
{"error":{"message":"This model's maximum context length is 4097 tokens, however you requested 4179 tokens (3965 in your prompt; 214 for the completion). Please reduce your prompt; or completion length.","type":"invalid_request_error","param":"","code":null}} attempt 6
现在是这样的：
 {"error":{"message":"bad status code: 400","type":"one_api_error","param":"","code":"bad_status_code"}} attempt 6

这种错误提示会让客户认为是我们的中转出现问题，而不是他自身的请求出现问题，为避免不必要的误会和频繁向客户解释，建议恢复原样。

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/126902077/e3729ea2-86db-4a3f-bf36-8ce70c0a5583)

**Comment by zwluoqi** [comment]
确实 现在没有详细提示 很蛋疼

**Comment by songquanpeng** [comment]
已修复，测试后反馈一下结果
