### ISSUE TITLE
支持阿里的 embedding 模型

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#469]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
1. 支持增加自定义向量模型，便于接入私有部署的向量模型。

2. 支持目前阿里，glm提供的商业向量模型
**应用场景**

**Comment by c121914yu** [comment]
已测试，自定义模型是可行的。
但是阿里的向量模型接口地址不一致，希望可以增加兼容

**Comment by igophper** [comment]
@c121914yu 
是这个吗？https://help.aliyun.com/zh/dashscope/developer-reference/api-details-15?spm=a2c4g.11186623.0.0.46917abeJqUrA0
是的话，我就今天晚上搞一下

**Comment by c121914yu** [comment]
> @c121914yu 
> 是这个吗？https://help.aliyun.com/zh/dashscope/developer-reference/api-details-15?spm=a2c4g.11186623.0.0.46917abeJqUrA0
> 是的话，我就今天晚上搞一下

是的
