### ISSUE TITLE
希望日志中增加调用渠道显示

### ISSUE THREAD

**Issue by B3nDan** [songquanpeng/one-api#470]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
为日志显示参数中添加"渠道"参数
使得用户可以查看该请求调用了哪个渠道

**应用场景**
便于排查错误，因为有时会出现空回复的情况，但不知道是哪个渠道的问题

**Comment by 520hacker** [comment]
https://github.com/songquanpeng/one-api/issues/249

**Comment by songquanpeng** [comment]
确实重复了，那这个先关了，以早的为准
