### ISSUE TITLE
阿里通义千文 - stream=true下异常

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#471]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用阿里通义千问时候，stream=false，会直接一次性返回 stream 的内容

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/50446880/0dd31d9b-b3a0-4e72-b412-b6c10040e54d)

**Comment by c121914yu** [comment]
上方: data: xxx 是 response 响应的内容。
下方是传给 oneapi 的参数

**Comment by songquanpeng** [comment]
可以把完整的请求和响应以文本的形式贴一下吗

**Comment by c121914yu** [comment]
> 可以把完整的请求和响应以文本的形式贴一下吗

我再找找原因。。奇怪的是，代码用 sdk 会出现这个问题（其他几个模型都正常），但是用apifox是正常的。

**Comment by songquanpeng** [comment]
先关了，如果有进度再 reopen

**Comment by huanglx27** [comment]
> > 可以把完整的请求和响应以文本的形式贴一下吗
> 
> 我再找找原因。。奇怪的是，代码用 sdk 会出现这个问题（其他几个模型都正常），但是用apifox是正常的。

找到了吗。我用postman也有这个问题
