### ISSUE TITLE
删除用户、禁用用户、用户登出等操作后，已下发的SESSION依旧有效

### ISSUE THREAD

**Issue by SrdptsClue** [songquanpeng/one-api#473]

**Comment by songquanpeng** [comment]
但是 key 可以删掉的

**Comment by songquanpeng** [comment]
方便pr么



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月28日(Mon) Evening8:31
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 删除用户、禁用用户、用户登出等操作后，已下发的SESSION依旧有效 (Issue #473)




 
这是一个安全隐患，经过测试，未失效的SESSION同样可以进行数据查询，这在某些情况下，会泄露很多信息。我在查看服务器日志的时候发现了很多渗透记录。感谢开发者提供ONE-API，这个漏洞我已经自己修复了。

**Comment by igophper** [comment]
确实目前的登录存在这种问题。
按道理来说，当用户被更新时，应该被登出。需要其进行重新登录。或者刷新其session信息。
但是目前使用的session机制，其是储存在每个客户端的浏览器中的，无法做到登出指定用户。

考虑使用jwt进行替代？
或者储存session在表中进行后续操作？
或许其他方案？
又或者就保持目前这个BUG？（不确定是否很多人需要这个功能）

@songquanpeng 有什么建议吗？给了建议我可以进行PR

**Comment by songquanpeng** [comment]
我先想一下哈，thx in advance

**Comment by jkhcc11** [comment]
有个建议可以试试这样，就是在这些操作时，只记录用户Id，然后在授权检查的时候，只需要判断这个用户id是否存在这个关系里面，而不用维护存储当前登录过系统的用户Id。如果是退出这种操作，可以把退出当时的sessid存入这个关系。类似！
当然，只是个建议。如果@songquanpeng 有更好的方案，那就更好了。

**Comment by songquanpeng** [comment]
现在删除和禁用会加入一个黑名单了，但是目前的实现仅可用于单机
