### ISSUE TITLE
希望取得联系，并支持 InternLM 

### ISSUE THREAD

**Issue by JimmyMa99** [songquanpeng/one-api#476]
尊敬的 one-api 应用开发者，我是 InternLM 社区开发者&志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现 one-api  的可能性和实现路径，我的微信是 mzm312，希望可以取得联系进行更深度的交流；

**Comment by songquanpeng** [comment]
你可以进群联系我



---Original---
From: "Ma ***@***.***&gt;
Sent at: 2023年8月28日(Mon) PM2:52
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 希望取得联系，并支持 InternLM  (Issue #476)




 
尊敬的 one-api 应用开发者，我是 InternLM 社区开发者&amp;志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现 one-api  的可能性和实现路径，我的微信是 mzm312，希望可以取得联系进行更深度的交流；

**Comment by vansin** [comment]
怎么进群哇~

**Comment by songquanpeng** [comment]
你提 issue 的过程中就能看到

**Comment by songquanpeng** [comment]
828520184
