### ISSUE TITLE
怎样修改web和api请求频率限制

### ISSUE THREAD

**Issue by zhuxindong** [songquanpeng/one-api#477]
只看到代码中有定义https://github.com/songquanpeng/one-api/blob/56b50073798e3930cbccceaf17b6e2a6a68524b8/common/constants.go#L113C1-L113C1  
是否有环境变量支持修改

**Comment by songquanpeng** [comment]
目前还没有，之后可以考虑加一下，默认配置有什么不足吗？



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月28日(Mon) PM4:49
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 怎样修改web和api请求频率限制 (Issue #477)




 
只看到代码中有定义https://github.com/songquanpeng/one-api/blob/56b50073798e3930cbccceaf17b6e2a6a68524b8/common/constants.go#L113C1-L113C1
 是否有环境变量支持修改

**Comment by zhuxindong** [comment]
api请求速率限制似乎有点不够

**Comment by tdouguo** [comment]
openai 有一批账号是可以 做到3500 rpm的 满速，但是这个好像是通过常量配置的，后期是否考虑 在添加渠道地方 去配置这个速率呢

**Comment by songquanpeng** [comment]
已经支持
