### ISSUE TITLE
docker run 无法启动的问题

### ISSUE THREAD

**Issue by Frank-yzd** [songquanpeng/one-api#482]
**例行检查**
 docker logs -f a5df55426876 
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0xd6fefb m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0xd6fefb
stack: frame={sp:0x7fffba2725c0, fp:0x0} stack=[0x7fffb9a73a40,0x7fffba272a50)
/usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc000052740 sp=0xc000052730 pc=0x46b0e8
runtime.main()
/usr/local/go/src/runtime/proc.go:169 +0x6d fp=0xc0000527e0 sp=0xc000052740 pc=0x43d68d
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x46d0c1
[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**解决方式**
官网提供添加一个--privileged=true
部署命令：docker run --name one-api -d --restart always -p 3000:3000 -e TZ=Asia/Shanghai -v /home/ubuntu/data/one-api:/data justsong/one-api

docker run --privileged=true  --name one-api -d --restart always -p 3000:3000 -e TZ=Asia/Shanghai -v /home/ubuntu/data/one-api:/data justsong/one-api

如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
方便的话可以提 PR 修改文档，如果不方便我可以自己改一下。

**Comment by AI-YTG-501** [comment]
[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused

**Comment by PMExtra** [comment]
看起来应该 `--security-opt seccomp=unconfined` 就能解决问题，直接 `--privileged` 有点权限太大了

**Comment by sheepc** [comment]
我的解决方式是在compose文件里面加上user: mysql，指定用户就行啦

![Image](https://github.com/user-attachments/assets/93f7c8f3-2552-49d4-a037-faf894e82219)
