### ISSUE TITLE
为每个模型预设前置role角色

### ISSUE THREAD

**Issue by codesdevs** [songquanpeng/one-api#483]
如这样[
  {
    "role": "system",
    "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/8/30 18:15:26\n"
  },
  {
    "role": "user",
    "content": "1"
  }
]
可以自定义system角色的内容

**Comment by songquanpeng** [comment]
这应该是客户端做的事情
