### ISSUE TITLE
在ChatGPT Next Web 中填写url地址和api key 出现跨域问题

### ISSUE THREAD

**Issue by namezzy** [songquanpeng/one-api#485]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

使用云服务器docker搭建的One API可以正常运行，包括在手机端Opencat 和浏览器插件chathub上可以正常使用，但是在
ChatGPT Next web中无法使用。会提示

{
  "error": true,
  "message": "Failed to fetch"
}
 
其中在您One API 中提供的ChatGPT Next Web 填写相应配置之后也是同样的报错。

![image](https://github.com/songquanpeng/one-api/assets/26276606/50abc7e3-b24d-4f09-abe5-d8f01204ce1f)

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
启用 HTTPS 了么？

**Comment by songquanpeng** [comment]
这不是跨域问题，HTTPS 网站下浏览器阻断了 HTTP 请求。

**Comment by songquanpeng** [comment]
解决办法就是要么都 HTTPS，要么都不要

**Comment by namezzy** [comment]
好的 谢谢您 我尝试一下

**Comment by 6qishi** [comment]
> 这不是跨域问题，HTTPS 网站下浏览器阻断了 HTTP 请求。

您好，我是用的windows端的桌面版next web，和上面遇到的是一样的问题，我的one api同样没有开启HTTPS，请问我该怎么做？

**Comment by songquanpeng** [comment]
只能开https哈，浏览器安全限制
