### ISSUE TITLE
增加日志清理功能

### ISSUE THREAD

**Issue by xswwxx** [songquanpeng/one-api#486]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
增加日志清理功能
**应用场景**
oneapi

**Comment by taurusduan** [comment]
同求，
![image](https://github.com/songquanpeng/one-api/assets/30854760/cb27dd99-f11a-494f-a706-148ce84b6a6a)
都几百兆了，不知道怎么清理日志，拜托了大哥。

**Comment by SuiYunsy** [comment]
为此专门下载了一个数据库管理软件，直接drop table logs😂

**Comment by songquanpeng** [comment]
已支持
