### ISSUE TITLE
支持设置访问 IP 地址白名单

### ISSUE THREAD

**Issue by lmuiotctf** [songquanpeng/one-api#49]
如上这个需求，可以自行定义添加白名单IP

**Comment by songquanpeng** [comment]
应该是仅限制于 API 调用吧？Web 端的请求应该不需要做此限制。

**Comment by lmuiotctf** [comment]
对的，就是请求api的限制，也就是上次我们的那个跨域的配置域名请求的

**Comment by songquanpeng** [comment]
Okay，我先想一想怎么实现简单高效。

**Comment by lmuiotctf** [comment]
config := cors.DefaultConfig()
config.AllowOriginFunc = func(origin string) bool {
    return strings.HasPrefix(origin, "http://example.com")
}
config.AllowCredentials = true
config.AllowMethods = []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
config.AllowHeaders = []string{"Origin", "Content-Length", "Content-Type", "Authorization", "Accept", "Connection"}
return cors.New(config)

可以加个开关，一个 config.AllowAllOrigins = true 等于全部开放，一个false，然后可以进行添加url

**Comment by songquanpeng** [comment]
和这个没有关系吧，这个是 CORS，只能限制浏览器，君子协定。

**Comment by songquanpeng** [comment]
这个还是通过 Nginx 来实现吧，暂时不考虑通过 One API 实现。
