### ISSUE TITLE
mysql 链接格式错误

### ISSUE THREAD

**Issue by bfgngfnfgmnggn** [songquanpeng/one-api#495]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
docker部署链接mysql,docker报错
-bash: syntax error near unexpected token `('

**复现步骤**
docker run --name one-api -d --restart always \
-p 3000:3000 \
-e TZ=Asia/Shanghai \
-e SQL_DSN=root:grtgerg345234@tcp(155.248.198.333:3306)/oneapi \
-v /home/ubuntu/data/one-api:/data justsong/one-api
**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/108604344/b047acb2-acc6-439a-8a75-6b519708b795)

**Comment by songquanpeng** [comment]
加引号
