### ISSUE TITLE
Docker 运行后登录失败

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#5]
登录后 提示403

**Comment by songquanpeng** [comment]
可以让我看一下报错或相关的截图吗？

**Comment by songquanpeng** [comment]
我检查了一下，貌似项目里并没有用到 403 状态码，所以我怀疑是不相干的问题。

如果能提供报错或截图，欢迎重开 issue。

**Comment by aiastia** [comment]
我是在github 上codespaces执行的 。 登陆提示 403 。
在本地服务器正常了…

**Comment by songquanpeng** [comment]
可能和 Codespace 的请求转发有关系。

#10 中是 Nginx 配置出的问题导致的 403
