### ISSUE TITLE
[TypeError: Cannot read properties of undefined (reading 'message')] 'writer error'

### ISSUE THREAD

**Issue by cui8** [songquanpeng/one-api#504]
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用讯飞星火认知免费api，对接one-api，在chatgpt-next-web中使用。
![image](https://github.com/songquanpeng/one-api/assets/70044239/90b671bd-9e4f-468b-bf73-a55d4b23930a)
回复一直都带有如下错误。
```
{
  "error": true,
  "message": "[object Object]"
}
```

**复现步骤**
1.填写好配置
![image](https://github.com/songquanpeng/one-api/assets/70044239/18202d94-5593-4319-91be-8d56fa772a79)
2.选择模型
![image](https://github.com/songquanpeng/one-api/assets/70044239/3869a5f9-fef7-45fe-ae7b-967d250e2f56)
3.使用出错
![image](https://github.com/songquanpeng/one-api/assets/70044239/3605f0c5-2d4d-42d5-aca1-709544d5b62f)

**预期结果**
没有如下错误。
```
{
  "error": true,
  "message": "[object Object]"
}
```

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/70044239/f51f14ab-1250-4342-8204-90d60ae50a64)
![image](https://github.com/songquanpeng/one-api/assets/70044239/6248317d-9cae-427e-8641-4825f72c5fb5)

**Comment by cui8** [comment]
已解决

**Comment by GFDYMS** [comment]
老哥，chat-next-web支持讯飞吗？
