### ISSUE TITLE
增加渠道被禁用通知

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#507]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
渠道余额不足、被禁用通知(原因以及对应名称。

具体有哪些通知渠道可以参考 uptime 这个项目，如下图，我用的是飞书通知，感觉可以挑选一部分常用的渠道。

![Screenshot_20230909_084615_com.ss.android.lark.jpg](https://github.com/songquanpeng/one-api/assets/50446880/a1542568-5a73-4707-a004-9acef7619cb1)

**应用场景**

**Comment by songquanpeng** [comment]
不是已经有邮件通知了么

**Comment by c121914yu** [comment]
> 不是已经有邮件通知了么

新版的？0.55-3没看到通知配置哎

**Comment by songquanpeng** [comment]
你配置好 SMTP 以及绑定好邮箱就可以了，这是很老的功能了

**Comment by c121914yu** [comment]
> 你配置好 SMTP 以及绑定好邮箱就可以了，这是很老的功能了

😂好吧，我还以为那个是注册的。
