### ISSUE TITLE
请问下是不是不支持本地虚拟机部署？

### ISSUE THREAD

**Issue by shellphy** [songquanpeng/one-api#509]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

我尝试在本地虚拟机的docker里面部署，路由器是已经翻墙了的，可以直接连通openai的官网，在渠道那里点击测试之后提示错误：Post \"https://api.openai.com/v1/chat/completions\": dial tcp: lookup api.openai.com on 127.0.0.11:53: server misbehaving

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by shellphy** [comment]
我加上了network_mode: host 就好了

**Comment by BrantonLiu** [comment]
请问下 这个network_mode: host是加到什么位置啊？
