### ISSUE TITLE
删除额度为负数的令牌会增加账号的额度

### ISSUE THREAD

**Issue by 18870** [songquanpeng/one-api#51]
rt

![image](https://github.com/songquanpeng/one-api/assets/22175295/a6b47c05-a477-4833-abb7-6bcecff68b33)

删除后重新创建

![image](https://github.com/songquanpeng/one-api/assets/22175295/99443987-f3ca-4abd-8965-74d23a493173)

**Comment by songquanpeng** [comment]
阿哲，笑死这个 bug

**Comment by songquanpeng** [comment]
明天修复

**Comment by songquanpeng** [comment]
已修复，已推送 `v0.2.2-alpha`。

**Comment by 18870** [comment]
现在是两个问题了
- 删除负数的令牌后重新创建一个新的令牌额度是0，而不是负数
- 删除一个正数额度的令牌重新创建一个新的额度也是0，而不是被删除的数量

**Comment by songquanpeng** [comment]
不应该啊，我看 bug 很简单就没测试。

我试一下。

**Comment by songquanpeng** [comment]
1. 这个确实是 0，确实有问题。
2. 这个我这里测试是正常的，估计是还是第一个相关的 bug 的影响。

**Comment by 18870** [comment]
我的问题（
刚才是在管理员账号上操作的，没注意到创建时有额度这个框

现在在普通用户上测试两个都没问题了

**Comment by songquanpeng** [comment]
Okay，谢谢反馈
