### ISSUE TITLE
用户额度消失

### ISSUE THREAD

**Issue by ye4293** [songquanpeng/one-api#513]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
某一位用户注册后，我通过后台改动了他的余额。系统注册赠送0.1刀，后续我第一次给他改成了5刀。在下午时客户突然找我说余额没了，我还以为是我更改时候选择了错的用户，然后再次给用户通过后台系统更改了余额。然后不到1小时余额又变成了注册赠送。后续我通过兑换码给用户更改额度，暂时未出现问题。
**复现步骤**
所有用户中只有这一位出现了这种问题，影响程度倒是不大，只是好奇为啥
**预期结果**
![W3HM7~F5OESXL{7P%JIHULN](https://github.com/songquanpeng/one-api/assets/137054651/d2e1c852-9565-4b7f-b0be-f572af88393c)
![_W4QBL`S%LUEQWQO86{C5`C](https://github.com/songquanpeng/one-api/assets/137054651/3d348b4e-6c1e-416c-9bf2-a23dbfadf8c0)

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
用 Redis 了么？

**Comment by ye4293** [comment]
没用redis，主要他是第一次出现这种情况，以前我也在后台更改过额度，但都没有这种消失的现象。用兑换码就没事了

**Comment by songquanpeng** [comment]
先稳定复现再说吧，从来没遇到过这个问题

**Comment by ye4293** [comment]
我用兑换码的额度也消失了 woc
