### ISSUE TITLE
兼容OpenAI官方API-KEY

### ISSUE THREAD

**Issue by quantstu** [songquanpeng/one-api#514]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

请求中转接口时，优先匹配数据库中的key，数据库中不存在时，验证key符合OpenAI官方key格式要求后，尝试使用请求提供的key去请求OpenAI官方接口，而不是直接返回

```json
{
    "error": {
        "message": "无效的令牌",
        "type": "one_api_error"
    }
}
```

这种情况下，忽略平台计费相关内容，单纯实现接口代理。同时可以在后台添加选项来实现自主选择是否开启或关闭此功能

**应用场景**

即使不使用中转平台生成的key而使用OpenAI官方的key请求接口也能正常使用。

**Comment by songquanpeng** [comment]
官方 key 你直接用 OpenAI 渠道不就行了，没看懂你这意义何在

**Comment by quantstu** [comment]
> 官方 key 你直接用 OpenAI 渠道不就行了，没看懂你这意义何在

单纯实现接口代理，方便其他人临时使用，而不是必须在后台新增渠道

**Comment by imldy** [comment]
相当于把本项目当成普通的反代使用，分代+分销二合一

**Comment by songquanpeng** [comment]
这样会导致其他没有该需求的渠道失败后必须重试一次，或者专门为此搞一个渠道，ROI 不大
