### ISSUE TITLE
建议随机初始密码

### ISSUE THREAD

**Issue by xiaoWangSec** [songquanpeng/one-api#516]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
当前的默认账户和密码为root / 123456, 建议将密码随机化, 用户初次执行时打印出密码

**应用场景**
部分用户部署在互联网上没有修改密码, 这将导致接口被滥用. 随机化初始密码可以避免这个问题.

**Comment by xiaoWangSec** [comment]
#520

**Comment by songquanpeng** [comment]
我主要的顾虑是有些人并不会看终端，通过 web 界面修改门槛更低。

**Comment by xiaoWangSec** [comment]
那或许可以在初次登陆时强制要求用户修改密码

**Comment by songquanpeng** [comment]
这个作为一个优化项后续处理

**Comment by songquanpeng** [comment]
现在不需要关闭，之后提交对应代码的时候关闭

**Comment by songquanpeng** [comment]
现在管理员用户第一次登录成功后会直接重定向到密码修改界面，并提示修改默认密码
