### ISSUE TITLE
腾讯混元大模型啥时候接进来

### ISSUE THREAD

**Issue by chenweijiSun** [songquanpeng/one-api#519]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by songquanpeng** [comment]
Okay，最近有空接入，https://cloud.tencent.com/document/product/1729/97732

**Comment by songquanpeng** [comment]
需要有人提供测试 key，测试完成之后 revoke

**Comment by chenweijiSun** [comment]
我有，晚点发一个
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月17日 21:43 |
| 收件人 | songquanpeng/one-api ***@***.***> |
| 抄送人 | Wicky ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [songquanpeng/one-api] 腾讯混元大模型啥时候接进来 (Issue #519) |

需要有人提供测试 key，测试完成之后 revoke

**Comment by chenweijiSun** [comment]
给一个邮箱，发 key

**Comment by songquanpeng** [comment]
方便的话加群私聊：828520184

**Comment by songquanpeng** [comment]
已经支持
