### ISSUE TITLE
禁止超额度使用

### ISSUE THREAD

**Issue by 18870** [songquanpeng/one-api#52]
像API2D一样禁止超限使用
提前根据请求的 max_token 判断额度是否足够

> `max_tokens`：如果不指定，每次请求会预先冻结 模型支持的最大个数 Token，如果是 3.5 也就是 41P ，在请求完成后按 usage 字段多退少补。如果账户余额少于 41P 就会报错，此时可以指定 max_tokens，这样就会按 max_tokens 来冻结 - https://api2d.com/doc/doc

另外，考虑到 #53，GPT-4 应该按照补全（或最高的）的倍率冻结额度。

related issue #51

**Comment by songquanpeng** [comment]
Okay，之后搞一下

**Comment by songquanpeng** [comment]
已经支持在后台设置预扣费的额度，该额度会乘上后台设置的不同模型的比率，算出实际上的预扣费额度。
