### ISSUE TITLE
GPT-4 提示和补全的倍率分层

### ISSUE THREAD

**Issue by 18870** [songquanpeng/one-api#53]
补全的价格是提示的两倍，但是现在实际计算的时候是按照 tokens 的总和扣除额度

```json
  "usage": {
    "completion_tokens": 13,
    "prompt_tokens": 17,
    "total_tokens": 30
  }
```

目前倍率设置为15的情况下，扣除了450额度
正确的情况是扣除 (17+13*2)*15=645

或者提示和补全可以分别自定义倍率

**Comment by songquanpeng** [comment]
Okay，主要是不同模型 token 消耗计算方式不一样，为了省事这样搞的。

我先想一想怎么处理比较方便。

**Comment by songquanpeng** [comment]
已修复，已推送 `v0.2.2`，期待测试反馈。
