### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by alexxchen** [songquanpeng/one-api#537]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在一些客户端上都出现的相同的Error: list index out of range问题。比如gpt_academic和chuanghuChatGPT。辛苦作者了！

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/15705569/1659a4f0-4e63-4ced-b987-33597006746a)

![image](https://github.com/songquanpeng/one-api/assets/15705569/8820ec43-853e-4d27-afd4-a560f44f1bf7)

**Comment by alexxchen** [comment]
`def steam_askChatGPT(messages):
    MODEL = "gpt-3.5-turbo"
    response = openai.ChatCompletion.create(
    model='gpt-3.5-turbo',
    messages=[
        {'role': 'user', 'content': "What's 1+1? Answer in one word."}
    ],
    temperature=0,
    stream=True  # this time, we set stream=True
    )

    for chunk in response:
        print(chunk)

messages=[
        {"role": "system","content":"无论我说什么都回到我，你好"},
        {"role": "user", "content": "人为什么要吃饭"},
    ]
steam_askChatGPT(messages)`
运行结果如下：
‘
{
  "id": "",
  "object": "",
  "created": 0,
  "model": "",
  "prompt_filter_results": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "choices": [],
  "usage": null
}
{
  "id": "chatcmpl-809DWQhwTmny9KKfEDjXyzRNaE9sh",
  "object": "chat.completion.chunk",
  "created": 1695046122,
  "model": "gpt-35-turbo",
  "choices": [
    {
      "index": 0,
      "finish_reason": null,
      "delta": {
        "role": "assistant"
      },
      "content_filter_results": {}
    }
  ],
  "usage": null
}
{
  "id": "chatcmpl-809DWQhwTmny9KKfEDjXyzRNaE9sh",
  "object": "chat.completion.chunk",
  "created": 1695046122,
  "model": "gpt-35-turbo",
  "choices": [
    {
      "index": 0,
      "finish_reason": null,
      "delta": {
        "content": "2"
      },
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "usage": null
}
{
  "id": "chatcmpl-809DWQhwTmny9KKfEDjXyzRNaE9sh",
  "object": "chat.completion.chunk",
  "created": 1695046122,
  "model": "gpt-35-turbo",
  "choices": [
    {
      "index": 0,
      "finish_reason": "stop",
      "delta": {},
      "content_filter_results": {}
    }
  ],
  "usage": null
}’

运行结果相比官方多了一个空开头：
‘{
  "id": "",
  "object": "",
  "created": 0,
  "model": "",
  "prompt_filter_results": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "choices": [],
  "usage": null
}’

**Comment by songquanpeng** [comment]
上游是啥来着，是 OpenAI 官方接口吗？

**Comment by alexxchen** [comment]
版本问题

**Comment by cleven1** [comment]
使用的one-api版本是0.6.8,  通义千问模型qwen-max也报同样的错误{"error":{"code":"internal_server_error","param":null,"message":"<500> InternalError.Algo: list index out of range","type":"internal_server_error"},"id":"chatcmpl-518d7dbb-2054-977b-8a1c-8a91a6a176f7","request_id":"518d7dbb-2054-977b-8a1c-8a91a6a176f7"}

该怎么解决呢?

**Comment by cleven1** [comment]
测试发现, 添加了qwen-max函数调用就会报list index out of range, 是one-api和qwen不兼容吗?
