### ISSUE TITLE
增加 gpt-3.5-turbo-instruct 模型

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#545]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by mmwong1984** [comment]
嗯嗯，我會提pr

**Comment by songquanpeng** [comment]
已经支持，但是 
![U`L(6MC`ND1Z`WI8_SZV53A](https://github.com/songquanpeng/one-api/assets/39998050/a0172a6f-5dba-4b80-9751-bd3fd1a78ba7)

**Comment by songquanpeng** [comment]
可能和我的 key 有关系吧

**Comment by bfgngfnfgmnggn** [comment]
> 可能和我的关键有关系吧

普通chatgpt3.5也能用这个模型,跟key没关系

目前这个项目用这个模型报错
