### ISSUE TITLE
请求支持baichuan2模型！

### ISSUE THREAD

**Issue by chenhaoqiang** [songquanpeng/one-api#559]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

9月6号发布的百川2大模型：https://mp.weixin.qq.com/s/-r2KzTbHp6l-OPoRvM7gzQ?from=singlemessage&isappinstalled=0&scene=1&clicktime=1695656634&enterid=1695656634

希望作者有时间了的话支持一下这个模型！作者辛苦了！💕

**应用场景**
FastGPT接入one-api，目前使用的是微软azure openai，想有一个支持本地化部署的大模型baichuan2，提高数据隐私！

**Comment by songquanpeng** [comment]
okay

**Comment by c121914yu** [comment]
https://www.baichuan-ai.com/home
53B有接口了，可直接接入。

**Comment by TangSY** [comment]
> https://www.baichuan-ai.com/home 53B有接口了，可直接接入。

嗯，这个也可以接入一下

**Comment by songquanpeng** [comment]
https://github.com/songquanpeng/one-api/issues/1057
