### ISSUE TITLE
[Tutorial] 本地部署教程、案例

### ISSUE THREAD

**Issue by yhyu13** [songquanpeng/one-api#560]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

我需要部署一些gguf格式的模型，但是发现oneapi好像没有先例，或本地部署的教程

issue里面找到一些本地部署的提问
https://github.com/songquanpeng/one-api/issues/540

chatglm因为有清华官方的openai api adapter，所以很方便就集成了？
https://github.com/songquanpeng/one-api/issues/453
https://github.com/songquanpeng/one-api/issues/377

其它的模型也只需要实现这样一套就行了？

谢谢！

**Comment by songquanpeng** [comment]
Yes，需要 adaptor，之后配合自定义渠道和自定义模型名称以及模型映射即可。
