### ISSUE TITLE
chatglm在回答第三个问题时报错

### ISSUE THREAD

**Issue by ManJieqi** [songquanpeng/one-api#561]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
![S30925-03162038_com.quark.browser.png](https://github.com/songquanpeng/one-api/assets/40858189/816a0dc8-7a3d-489a-976c-d390169a0fce)

![S30925-03124365_com.quark.browser.png](https://github.com/songquanpeng/one-api/assets/40858189/5c713e73-eeec-4403-847d-007326554210)

**复现步骤**
![S30926-01025858_com.quark.browser.png](https://github.com/songquanpeng/one-api/assets/40858189/af750ef8-dde9-4aab-a1cd-a2d5e94ec3ce)

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
近期处理

**Comment by songquanpeng** [comment]
没能复现，抓包提供一下请求体和响应

**Comment by qingju32** [comment]
**是这个吗？预览响应什么也没有**
![image](https://github.com/songquanpeng/one-api/assets/40858189/dc97150b-e474-46d0-b340-5ec4126342a5)

**下面这个是第二个问题的回答情况**
![image](https://github.com/songquanpeng/one-api/assets/40858189/ec6037bf-3016-43f0-8b53-dff6726a3d5b)
![image](https://github.com/songquanpeng/one-api/assets/40858189/65a1df0c-97dc-4938-a1e2-4497dc2b7cb2)

**好像和数字有关系，附带信息3的时候就会**
![image](https://github.com/songquanpeng/one-api/assets/40858189/175f31e6-ae3b-4634-bb9f-8e1d35cd16c7)

Next Web的问题？

**Comment by qingju32** [comment]
附带历史消息数为奇数的时候，就会在对话轮数到的时候报错

**Comment by kuangxiaoye** [comment]
同样遇到这个问题

**Comment by songquanpeng** [comment]
Okay，我近期处理

**Comment by kuangxiaoye** [comment]
我用的模型是gpt4，并不是题主的模型，但是问题相似

我如果不传入prompt，直接问答，就不会出现奇数报错的问题。hhhh很奇怪

**Comment by kuangxiaoye** [comment]
> 我用的模型是gpt4，并不是题主的模型，但是问题相似
> 
> 我如果不传入prompt，直接问答，就不会出现奇数报错的问题。hhhh很奇怪

更新到最新版后这个问题已解决

**Comment by songquanpeng** [comment]
@qingju32 你用的是最新版本么？

**Comment by qingju32** [comment]
是的
