### ISSUE TITLE
请求支持Cloudflare AI Gateway

### ISSUE THREAD

**Issue by YangQiGuiKong** [songquanpeng/one-api#565]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
cloudflare刚刚上线了AI功能，其中AI Gateway可以对来自应用的请求进行限速和缓存。缓存可以节省相同问题的Token消耗。这个是cloudflare ai的文档https://developers.cloudflare.com/ai-gateway/   。目前其Endpoints的格式是（以openai为例）https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai ，其已自动包含了v1路径，所以使用目前one-api已有的渠道（openai官方或者自定义渠道）都无法正常使用gateway调用。希望可以增加一个渠道用于通过Cloudflare AI Gateway进行模型的调用。
**应用场景**

**Comment by YangQiGuiKong** [comment]
![image](https://github.com/songquanpeng/one-api/assets/101174061/a88462ee-4973-48fb-a501-ac23852afaaa)
![image](https://github.com/songquanpeng/one-api/assets/101174061/fe30d310-72f2-4cfe-ba27-dcd39db3e0ee)

**Comment by songquanpeng** [comment]
Okay

**Comment by JamesFlare1212** [comment]
我写了一个小小的CF Workers代理，其实就是反代一下路径：

```js
addEventListener("fetch", (event) => {
  let url = new URL(event.request.url);

  if (url.pathname.startsWith("/v1/chat/completions")) {
    // Update the hostname for the new URL
    url.hostname = "gateway.ai.cloudflare.com";
    
    // Update the pathname, removing the initial "/v1" and appending the rest to the new path
    url.pathname = "/v1/245a88b0a36c8f04e7a706725537055b/one-api/openai" + url.pathname.substr(3);

    let proxyRequest = new Request(url, {
      method: event.request.method,
      headers: event.request.headers,
      body: event.request.body,
    });

    event.respondWith(fetch(proxyRequest));
  } else {
    event.respondWith(fetch(event.request));
  }
});
```

把 `/v1/245a88b0a36c8f04e7a706725537055b/one-api/openai` 换成你的就可以用了（用我的也无所谓）。

**Comment by YangQiGuiKong** [comment]
> 我写了一个小小的CF Workers代理，其实就是反代一下路径：
> 
> ```js
> addEventListener("fetch", (event) => {
>   let url = new URL(event.request.url);
> 
>   if (url.pathname.startsWith("/v1/chat/completions")) {
>     // Update the hostname for the new URL
>     url.hostname = "gateway.ai.cloudflare.com";
>     
>     // Update the pathname, removing the initial "/v1" and appending the rest to the new path
>     url.pathname = "/v1/245a88b0a36c8f04e7a706725537055b/one-api/openai" + url.pathname.substr(3);
> 
>     let proxyRequest = new Request(url, {
>       method: event.request.method,
>       headers: event.request.headers,
>       body: event.request.body,
>     });
> 
>     event.respondWith(fetch(proxyRequest));
>   } else {
>     event.respondWith(fetch(event.request));
>   }
> });
> ```
> 
> 把 `/v1/245a88b0a36c8f04e7a706725537055b/one-api/openai` 换成你的就可以用了（用我的也无所谓）。

好的，我试试，感谢！

**Comment by songquanpeng** [comment]
已经支持，请参考 README 设置。

**Comment by mwnu** [comment]
> 已经支持，请参考 README 设置。

问题英国还在，版本v0.5.7-alpha.7
