### ISSUE TITLE
仅初始化已经添加的模型的Encoder

### ISSUE THREAD

**Issue by cmj2002** [songquanpeng/one-api#566]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

从 0.5.4 开始，提交 [`fdb2ccc`](https://github.com/songquanpeng/one-api/commit/fdb2cccf65f3d27f56a05b91c48aed393c7ed9c9) 使得程序在启动时会初始化所有 Encoder，以修复[并发问题](https://github.com/songquanpeng/one-api/issues/459)。但是这样会极大地浪费机器上的内存，因为很多时候这些 Encoder 中的大多数并不会被使用。在我的设置中，0.5.4 或 0.5.5 版本占用了之前版本约 15 倍的内存。

希望将行为更改为：
- 开机时仅初始化已经添加的模型的 Encoder
- 添加新模型时初始化对应 Encoder

如果有困难，也可以提供一个环境变量来允许专业用户自行设定启动时要初始化的 Encoder，若未设置时仍初始化全部。

**应用场景**

对低内存机器较为重要，尤其是考虑到该程序正在不断添加新的模型和 Encoder。

**Comment by songquanpeng** [comment]
确实哦，现在修一下

**Comment by cmj2002** [comment]
此外我还发现不同模型如果使用了同样的 Encoder，似乎不会进行复用，而是会创建多个对象。也可以考虑在此方向上进行优化。（该优化点一直存在，并不是 0.5.4 引入的）

**Comment by songquanpeng** [comment]
内存占用情况有量化数据么？

**Comment by songquanpeng** [comment]
> 此外我还发现不同模型如果使用了同样的 Encoder，似乎不会进行复用，而是会创建多个对象。也可以考虑在此方向上进行优化。（该优化点一直存在，并不是 0.5.4 引入的）

这个应该是上游的问题

**Comment by cmj2002** [comment]
> 内存占用情况有量化数据么？

我的用例中，只通过 Azure openai 添加了 gpt3.5 和 gpt4 模型（包括它们的长上下文版本），0.5.3 内存占用为 15 MB，0.5.4 的内存占用可以高达 250 MB

**Comment by songquanpeng** [comment]
修复了，请测试

**Comment by cmj2002** [comment]
> 修复了，请测试

v0.5.6-alpha.9 消耗了 50MB 的内存。我对 gpt3.5 和 gpt4 模型进行了测试，没有发现问题。

**Comment by songquanpeng** [comment]
还没搞清楚为什么 v0.5.3 会这么少，当前版本只预先初始化了 4 和 3.5

**Comment by cmj2002** [comment]
我的问题，我前面给你数据的时候是随手从正在运行的实例上拿下来的，它当时可能还没有接受任何请求所以内存占用很低。我重新对 0.5.3 进行了测试，开机后为 10~15MB ，发出 GPT3 的请求后变为 47MB，发出 GPT4 的请求后变为 54MB。这就和 0.5.6-alpha.9 基本相符了。很抱歉提供了错误的数据。
