### ISSUE TITLE
Azure OpenAI API

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#57]
想问下有无提上议程

**Comment by songquanpeng** [comment]
我还没拿到权限，如果能搞清楚请求体和返回体格式，并能协助测试的话，当然可以搞。

和 #48 重复。

**Comment by how1ewu** [comment]
> 我还没拿到权限，如果能搞清楚请求体和返回体格式，并能协助测试的话，当然可以搞。
> 
> 和 #48 重复。

我拥有权限，可以协助进行测试

**Comment by how1ewu** [comment]
```python
#Note: The openai-python library support for Azure OpenAI is in preview.
import os
import openai
openai.api_type = "azure"
openai.api_base = "个人资源的域名"
openai.api_version = "2023-03-15-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")

response = openai.ChatCompletion.create(
  engine="gpt35",# 这里是部署节点名称，为用户自定义的，az openai获取资源包后需要自行部署模型，比如gpt3.5、text之类的，然后给部署的模型起个名字，这里就是自己起的名字
  messages = [{"role":"system","content":"You are an AI assistant that helps people find information."},{"role":"user","content":"你好"},{"role":"assistant","content":"你好！有什么我可以帮您的吗？"},{"role":"user","content":"你叫什么名字"},{"role":"assistant","content":"我是一个AI助手，您可以称呼我为“AI助手”或者“机器人”。"},{"role":"user","content":"你属于哪一家公司"}],
  temperature=0.7,
  max_tokens=800,
  top_p=0.95,
  frequency_penalty=0,
  presence_penalty=0,
  stop=None)
```

**Comment by songquanpeng** [comment]
好的，我有以下需要搞清楚的问题：
1. API 端点是什么？
2. 请求体的 JSON 格式定义。
3. 返回体的 JSON 格式定义。

**Comment by how1ewu** [comment]
> 好的，我有以下需要搞清楚的问题：
> 
> 1. API 端点是什么？
> 2. 请求体的 JSON 格式定义。
> 3. 返回体的 JSON 格式定义。

ok我来逐个进行回复

**Comment by how1ewu** [comment]
1、API端点：
https://自定义资源名.openai.azure.com/openai/deployments/自定义部署名/chat/completions?api-version=2023-03-15-preview

**Comment by how1ewu** [comment]
整体结构如下：（curl）
curl https://资源名.openai.azure.com/openai/deployments/部署名/chat/completions?api-version=2023-03-15-preview \
  -H "Content-Type: application/json" \
  -H "api-key: YOUR_API_KEY" \
  -d '{
  "messages": "[{\"role\":\"system\",\"content\":\"You are an AI assistant that helps people find information.\"},{\"role\":\"user\",\"content\":\"你好\"},{\"role\":\"assistant\",\"content\":\"你好！有什么我可以帮您的吗？\"},{\"role\":\"user\",\"content\":\"你叫什么名字\"},{\"role\":\"assistant\",\"content\":\"我是一个AI助手，您可以称呼我为“AI助手”或者“机器人”。\"},{\"role\":\"user\",\"content\":\"你属于哪一家公司\"},{\"role\":\"assistant\",\"content\":\"我是一个虚拟的AI助手，不属于任何一家具体的公司。我被设计用于帮助人们查找信息和回答问题。\"}]",
  "max_tokens": 800,
  "temperature": 0.7,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "top_p": 0.95,
  "stop": null
}'

**Comment by how1ewu** [comment]
这是官方的部署文档：
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/tutorials/embeddings?tabs=command-line

**Comment by songquanpeng** [comment]
好的，我现在开始搞。

**Comment by how1ewu** [comment]
> 好的，我现在开始搞。

辛苦了

**Comment by songquanpeng** [comment]
看文档，貌似非 stream 模式下，返回体格式是一致的：
1. https://platform.openai.com/docs/guides/chat/response-format
2. https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?pivots=rest-api&tabs=command-line#output

但是 steam 模式下没明说，我这里姑且认为也是一致的。

**Comment by songquanpeng** [comment]
这个是可选的吗？`?api-version=2023-03-15-preview`

**Comment by how1ewu** [comment]
> 这个是可选的吗？`?api-version=2023-03-15-preview`

稍等我查阅一下

**Comment by how1ewu** [comment]
我发现文档中好像并没有写明具体的情况，我认为他是可选的，我查阅了其他没有备注版本的模型，他们会把版本标记为2022-12-01
completions?api-version=2022-12-01

**Comment by songquanpeng** [comment]
可以试一下不填会报错吗？

**Comment by how1ewu** [comment]
我正在尝试

**Comment by how1ewu** [comment]
> 可以试一下不填会报错吗？

证实，是不可缺省的https://zhuanlan.zhihu.com/p/618541541

**Comment by songquanpeng** [comment]
Okay，目前先硬编码一个默认版本。

**Comment by songquanpeng** [comment]
已推送版本 `v0.2.3-alpha`，期待测试反馈。

**Comment by how1ewu** [comment]
> 已推送版本 `v0.2.3-alpha`，期待测试反馈。

目前来看不太行，要不您给我一个邮件地址，我给你一个API密钥便于测试？

**Comment by songquanpeng** [comment]
好的，`i#justsong.cn`，# 替换为 @

**Comment by how1ewu** [comment]
> i#justsong.c

已经发送，请查收

**Comment by songquanpeng** [comment]
是 `i#justsong.cn`，暂时还没收到。

**Comment by songquanpeng** [comment]
已收到。

**Comment by how1ewu** [comment]
> 已收到。

ok

**Comment by songquanpeng** [comment]
我还没试，不过我感觉是你部署名称的问题，需要和 OpenAI 的模型名称保持一致，部署名称可以换成 `gpt-3.5-turbo` 吗？

**Comment by how1ewu** [comment]
> 我还没试，不过我感觉是你部署名称的问题，需要和 OpenAI 的模型名称保持一致，部署名称可以换成 `gpt-3.5-turbo` 吗？
我试试

**Comment by how1ewu** [comment]
> 我还没试，不过我感觉是你部署名称的问题，需要和 OpenAI 的模型名称保持一致，部署名称可以换成 `gpt-3.5-turbo` 吗？
![image](https://github.com/songquanpeng/one-api/assets/98788152/1daff9a5-41b0-4513-aa6d-281bd5b4907c)
![](https://s2.loli.net/2023/05/13/q6oD7CvGZueznJa.png)
我尝试了修改部署名称，但是没有成功，如果加入（version.....）之类的后缀就无法命名了

**Comment by how1ewu** [comment]
<img width="536" alt="截屏2023-05-13 12 15 20" src="https://github.com/songquanpeng/one-api/assets/98788152/2115fa0d-2074-4bfe-86e3-63489f95bea2">
这是现在的三个模型命名

**Comment by songquanpeng** [comment]
了解了，我先手动修改名称试一下。

**Comment by songquanpeng** [comment]
可以了，stream 模式和非 stream 模式都 Okay：
![image](https://github.com/songquanpeng/one-api/assets/39998050/02b41c7a-bf14-4da2-b7e1-92f174962d49)

**Comment by songquanpeng** [comment]
目前看他只是把点给去掉了，我能看一下完整的模型名称列表吗？

**Comment by how1ewu** [comment]
> 目前看他只是把点给去掉了，我能看一下完整的模型名称列表吗？

ok我截个图，GPT4需要单独申请，我还没通过
<img width="355" alt="截屏2023-05-13 12 20 41" src="https://github.com/songquanpeng/one-api/assets/98788152/d389cc9d-5344-4cc1-bde0-5750c182267f">
<img width="393" alt="截屏2023-05-13 12 20 31" src="https://github.com/songquanpeng/one-api/assets/98788152/ff6e06af-705e-446e-b6a9-208d02b05448">

**Comment by songquanpeng** [comment]
Okay，目前打算自动把用户传入的模型名称中的点剔除掉，这样就能兼容已有的 API 了。

**Comment by how1ewu** [comment]
> Okay，目前打算自动把用户传入的模型名称中的点剔除掉，这样就能兼容已有的 API 了。

目前来看az基本在复用openai的那些东西

**Comment by songquanpeng** [comment]
但是还是有点不兼容的地方。

已推送 `v0.2.3-alpha.1`。

**Comment by how1ewu** [comment]
> 但是还是有点不兼容的地方。
> 
> 已推送 `v0.2.3-alpha.1`。

请问下您用的什么客户端，我使用utools的插件会报错 Unexpected token ‘D’, "[DONE] " is not valid JSON

**Comment by songquanpeng** [comment]
Postman，看来你的插件不支持 SSE，stream 模式下返回内容并不是 JSON。

**Comment by how1ewu** [comment]
> Postman，看来你的插件不支持 SSE，stream 模式下返回内容并不是 JSON，你可以把参数里的 stream 去掉，这样就是返回 JSON 了。
明白了谢谢

**Comment by songquanpeng** [comment]
已支持配置默认 API 版本，已推送 `v0.2.3`。

**Comment by songquanpeng** [comment]
如果接下来测试没问题，该 issue 就可以关掉了。

**Comment by aiastia** [comment]
大佬这么快就搞定了呀👍
话说能否添加一个渠道可用性的检测。
目前是禁用其他的来解决的

**Comment by songquanpeng** [comment]
> 大佬这么快就搞定了呀👍 话说能否添加一个渠道可用性的检测。 目前是禁用其他的来解决的

新开 issue 吧。

**Comment by songquanpeng** [comment]
如果 Azure 渠道有问题，欢迎重开此 issue。

**Comment by aiastia** [comment]
> 如果接下来测试没问题，该 issue 就可以关掉了。

好像不行 名称是写 gpt-35-turbo 吗 api 版本0301

**Comment by songquanpeng** [comment]
不应该啊，这个我是测试过的，Azure 控制台那里的部署名称是这样的吗？
![image](https://github.com/songquanpeng/one-api/assets/39998050/d1804c6e-0544-420b-b73e-03c1d1412a84)

**Comment by aiastia** [comment]
用的是ioa 的Openchat

**Comment by songquanpeng** [comment]
其他通道类型 Okay 吗？

**Comment by aiastia** [comment]
> 其他通道类型 Okay 吗？

是的 openai sb 和 自定义反代的openai 还有api2d 都可以

**Comment by songquanpeng** [comment]
可以试一下其他客户端吗？我没有自己的  token，不方便测试。

**Comment by aiastia** [comment]
![截图_20230513154708](https://github.com/songquanpeng/one-api/assets/19776350/573e0cad-bf9e-471a-a330-996144f08e1d)

**Comment by songquanpeng** [comment]
可以用 Postman 手动测试一下吗？或者 OpenChat 如果有报错信息的话最好发一下。

**Comment by aiastia** [comment]
Postman  要怎么……

**Comment by aiastia** [comment]
![image](https://github.com/songquanpeng/one-api/assets/19776350/a9a9b7f0-7c52-4f30-8798-348f283e5eab)

**Comment by songquanpeng** [comment]
POST: `http://localhost:3000/v1/chat/completions`

格式选 raw，内容为：
```json
{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "hi"}]
}
```
![image](https://github.com/songquanpeng/one-api/assets/39998050/a29ce380-1a0d-4a16-aff5-b9087a8032d4)

这里设置 token，注意指定使用 Azure 通道：
![image](https://github.com/songquanpeng/one-api/assets/39998050/b3fc1712-4fb6-4731-b537-20db63a149b5)

**Comment by aiastia** [comment]
{
    "error": {
        "code": "404",
        "message": "Resource not found"
    }
}

**Comment by aiastia** [comment]
如果禁用azure 模型 提示 的 就是 {
    "error": {
        "message": "you must provide a model parameter",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by songquanpeng** [comment]
看一下请求体，我怀疑 model 参数没加。

**Comment by aiastia** [comment]
body 里面的吗 我就复制你的 {
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "hi"}]
}

**Comment by aiastia** [comment]
headers 我没有添加

**Comment by songquanpeng** [comment]
这就离谱了，Header 不用加，只需要设置 authorization token 就好。

请求路径正确吗？

**Comment by aiastia** [comment]
> 这就离谱了，Header 不用加，只需要设置 authorization token 就好。
> 
> 请求路径正确吗？
你给我的是  POST: http://localhost:3000/v1/chat/completions


我把 localhost:3000 改成自己的域名了 https://***.xyz/v1/chat/completions

**Comment by aiastia** [comment]
![image](https://github.com/songquanpeng/one-api/assets/19776350/501655bc-47bd-4acc-904e-6f84e6a99d03)

**Comment by songquanpeng** [comment]
这个配置了吗？
![image](https://github.com/songquanpeng/one-api/assets/39998050/cb6629f0-812f-469e-a2bd-a9d5b5e398f2)

AZURE_OPENAI_ENDPOINT 是这样的格式吗？
![image](https://github.com/songquanpeng/one-api/assets/39998050/99a015be-92ad-4e2c-8b8b-a33e711fd61c)

**Comment by aiastia** [comment]
> 这个配置了吗？ ![image](https://user-images.githubusercontent.com/39998050/238123291-cb6629f0-812f-469e-a2bd-a9d5b5e398f2.png)
> 
> AZURE_OPENAI_ENDPOINT 是这样的格式吗？ ![image](https://user-images.githubusercontent.com/39998050/238123326-99a015be-92ad-4e2c-8b8b-a33e711fd61c.png)

默认 API 版本
 写的是 0301
AZURE_OPENAI_ENDPOINT
写的是azure 上复制的域名 https://hj***.openai.azure.com

**Comment by songquanpeng** [comment]
写错了，目前必须填 2023-03-15-preview。

**Comment by aiastia** [comment]
已经改了  现在换了一个提示 

{
    "error": {
        "message": "Invalid Content-Type header (text/plain), expected application/json. (HINT: If you're using curl, you can pass -H 'Content-Type: application/json')",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by songquanpeng** [comment]
请求体格式没选对：
![image](https://github.com/songquanpeng/one-api/assets/39998050/99f04e04-ac3e-450f-be59-4b677a95c250)

**Comment by aiastia** [comment]
{
    "id": "chatcmpl-7FepLXnl9gryYFYQIMlbmx554gV5e",
    "object": "chat.completion",
    "created": 1683966215,
    "model": "gpt-35-turbo",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "Hello! How can I assist you today?"
            }
        }
    ],
    "usage": {
        "completion_tokens": 9,
        "prompt_tokens": 9,
        "total_tokens": 18
    }
}

**Comment by songquanpeng** [comment]
这已经 Okay 了，现在再试一下 OpenChat。

**Comment by aiastia** [comment]
> 这已经 Okay 了，现在再试一下 OpenChat。

都一样的报错 …… 

![image](https://github.com/songquanpeng/one-api/assets/19776350/4dabda19-63ff-4165-9e1a-d07bab00b343)


这个是我用 官网的 api （禁用了azure 的提示）


{
    "id": "chatcmpl-7FeqJUpHWoo5bjjGpibEOHQ410Yjn",
    "object": "chat.completion",
    "created": 1683966275,
    "model": "gpt-3.5-turbo-0301",
    "usage": {
        "prompt_tokens": 9,
        "completion_tokens": 9,
        "total_tokens": 18
    },
    "choices": [
        {
            "message": {
                "role": "assistant",
                "content": "Hello! How can I assist you today?"
            },
            "finish_reason": "stop",
            "index": 0
        }
    ]
}

**Comment by songquanpeng** [comment]
Okay，那现在使用 Azure 通道进行请求，Postman 中的返回内容是什么呢？

**Comment by aiastia** [comment]
````
{
    "id": "chatcmpl-7FeuwyXuYsjrJHv17jN6z4k1o7t30",
    "object": "chat.completion",
    "created": 1683966562,
    "model": "gpt-3.5-turbo-0301",
    "usage": {
        "prompt_tokens": 9,
        "completion_tokens": 9,
        "total_tokens": 18
    },
    "choices": [
        {
            "message": {
                "role": "assistant",
                "content": "Hello! How can I assist you today?"
            },
            "finish_reason": "stop",
            "index": 0
        }
    ]
}
````
azure 的

**Comment by aiastia** [comment]
````
{
    "id": "chatcmpl-7FeuQLPZxsNVAduoMqC2jjAnPOH0e",
    "object": "chat.completion",
    "created": 1683966530,
    "model": "gpt-35-turbo",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "Hello! How may I assist you today?"
            }
        }
    ],
    "usage": {
        "completion_tokens": 9,
        "prompt_tokens": 9,
        "total_tokens": 18
    }
}
````

azure 的

**Comment by aiastia** [comment]
然后我测试了一下 openchat 里面 如果模型是有0301 的时候 就提示 上面的图片

如果模型是没有0301 的就先回房消息然后 在提示那个图片

**Comment by aiastia** [comment]
chatbox
 就是 选择 没有0301后缀 的模型 就提示 Unexpected token 'D', "[DONE]
" is not valid JSON

如果有 就是卡住不回复

**Comment by songquanpeng** [comment]
Azure 的模型列表里面并没有带 0301 后缀的，所以这个出错正常。

我感觉是因为 OpenAI 和 Azure 的 stream 模式下格式有差异。

**Comment by aiastia** [comment]
![image](https://github.com/songquanpeng/one-api/assets/19776350/b537c6a4-de98-4213-b625-1b83de1ec42b)
然后我发现我模型没有上面老哥那个模型多……

**Comment by aiastia** [comment]
> Azure 的模型列表里面并没有带 0301 后缀的，所以这个出错正常。
> 
> 我感觉是因为 OpenAI 和 Azure 的 stream 模式下格式有差异。

看来是没办法兼容了吗？
感觉现有的app 很少有支援azure 的ai

**Comment by songquanpeng** [comment]
肯定可以兼容的，我现在需要确定究竟是不是 stream 下格式的问题。

@how1ewu 请问你有遇到类似的情况吗？

**Comment by aiastia** [comment]
> 

https://github.com/haibbo/cf-openai-azure-proxy/blob/main/cf-openai-azure-proxy.js 我看有个这个 项目 您看看？

**Comment by songquanpeng** [comment]
Okay，等我有 token 测试或者 @how1ewu 允许我继续用他那个 token 测试后再看一下这个问题。

**Comment by aiastia** [comment]
> Okay，等我有 token 测试或者 @how1ewu 允许我继续用他那个 token 测试后再看一下这个问题。

目前用上面的cf 反代 然后  在open api 添加自定义  然后就曲线救国了

**Comment by how1ewu** [comment]
> 下

![image](https://github.com/songquanpeng/one-api/assets/98788152/52c21145-85cf-4642-abdb-38d78388856f)

**Comment by how1ewu** [comment]
> Okay，等我有 token 测试或者 @how1ewu 允许我继续用他那个 token 测试后再看一下这个问题。

![image](https://github.com/songquanpeng/one-api/assets/98788152/042f6b08-91b7-4c27-aed8-08fa10b00062)
我后台又部署了一个text ada模型供你参考

**Comment by how1ewu** [comment]
现在这种方式好像好多插件都不太兼容，我的vscode插件、utools插件、obsidian插件都会提示json错误Unexpected token ‘D’, "[DONE] " is not valid JSON。可以实现为类似cf-openai-azure-proxy.js这种代理模式吗

**Comment by songquanpeng** [comment]
当然可以，我现在调查一下原因。

**Comment by songquanpeng** [comment]
我已经定位到问题了，问题在于 Azure 的 stream 模式下，输出的结尾标识符 [DONE] 后面多了一个空格，而且他不会主动结束 stream。

**Comment by songquanpeng** [comment]
是多了一个换行符。

**Comment by songquanpeng** [comment]
`v0.2.5-alpha` 已推送。

我已经用 ChatGPT Next 测试过了，测试 Okay。

@aiastia @how1ewu

**Comment by aiastia** [comment]
高产……Opencat 正常  不过模型要选gpt-3.5-turbo 

如果选择 gpt-3.5-turbo-0301 就报错

但是 azure 的open ai gpt-3.5-turbo 就是 gpt-3.5-turbo-0301 吧……

能否配置一个映射 像这样 
````// The deployment name you chose when you deployed the model.
const mapper = {
    'gpt-3.5-turbo': DEPLOY_NAME_GPT35,
    'gpt-4': DEPLOY_NAME_GPT4
};
````

**Comment by aiastia** [comment]
> > Okay，等我有 token 测试或者 @how1ewu 允许我继续用他那个 token 测试后再看一下这个问题。
> 
> ![image](https://user-images.githubusercontent.com/98788152/238161332-042f6b08-91b7-4c27-aed8-08fa10b00062.png) 我后台又部署了一个text ada模型供你参考

为啥你的可用模型这么多啊……

**Comment by songquanpeng** [comment]
映射这个简单，直接硬编码一个 map 完事。

**Comment by aiastia** [comment]
> 映射这个简单，直接硬编码一个 map 完事。

在渠道添加上面加一个 感觉会更好（
然后能给渠道添加一个备注选项吗

**Comment by aiastia** [comment]
> `v0.2.5-alpha` 已推送。
> 
> 我已经用 ChatGPT Next 测试过了，测试 Okay。
> 
> @aiastia @how1ewu

视乎引入的新的问题  就是使用open ai 的 api 的 就提示 ” 未能读取数据，因为它的格式不正确“

**Comment by songquanpeng** [comment]
不应该啊，我也测试了之前的。具体是什么软件的报的错？

**Comment by aiastia** [comment]
> 不应该啊，我也测试了之前的。具体是什么软件的报的错？

使用的是Openchat ios 的 发送消息 就提示 ” 未能读取数据，因为它的格式不正确“ 不过 他还是可以接受回复 。

**Comment by aiastia** [comment]
![image](https://github.com/songquanpeng/one-api/assets/19776350/6de19c6b-b75d-443c-bbe7-d5d664e257ec)

你看 回复的消息收到了。 但是会提示这个

**Comment by aiastia** [comment]
> 不应该啊，我也测试了之前的。具体是什么软件的报的错？

用open ai 官网的 api 的  他在接受所有的消息后 弹出上面这个提示…… 
如果用azure 的 就不会……

**Comment by aiastia** [comment]
看了一下 非  azure 的 会回复

```
 [DONE
```

azure 的回复 
```
[DONE
]
```

少了个 “]”

**Comment by aiastia** [comment]
````
{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "hi"}],
    "stream": true
}
````

**Comment by how1ewu** [comment]
现在遇到一个bug，新版本使用普通的openai他会正常传输，但是传输结束后会变成
Unexpected token ‘D’, “[DONE” is not valid JSON
![image](https://github.com/songquanpeng/one-api/assets/98788152/8f1d56d3-e4f9-4781-94fe-36199aae3604)
![image](https://github.com/songquanpeng/one-api/assets/98788152/54a6b7f1-ea2a-4720-9eae-ffc635e4774d)

**Comment by songquanpeng** [comment]
@how1ewu Azure 通道会出现这种情况吗？

**Comment by how1ewu** [comment]
> @how1ewu Azure 通道会出现这种情况吗？

az是正常的

**Comment by aiastia** [comment]
> 少了个 “]”

普通的open ai少了个 “]”

**Comment by how1ewu** [comment]
> > 少了个 “]”
> 
> 普通的open ai少了个 “]”

这样的话是不是后端得加个if了

**Comment by songquanpeng** [comment]
已修复，已推送。

**Comment by songquanpeng** [comment]
问题在于我代码没处理好 slice 的 end index。

下面第一个是  Azure 的结束标记，第二个是 OpenAI 的结束标记，第一个多了个换行符。
![image](https://github.com/songquanpeng/one-api/assets/39998050/9082fbf5-2205-406d-a02c-c9712a246c57)
![image](https://github.com/songquanpeng/one-api/assets/39998050/cce5250a-bb1d-4385-8faa-4511fa933c22)

**Comment by songquanpeng** [comment]
还请再测试一下，如果都 Okay，这个 issue 就可以关了。

@aiastia @how1ewu

**Comment by how1ewu** [comment]
> 还请再测试一下，如果都 Okay，这个 issue 就可以关了。
> 
> @aiastia @how1ewu

现在在我这里一切正常期待其他人的表现

**Comment by aiastia** [comment]
> > 还请再测试一下，如果都 Okay，这个 issue 就可以关了。
> > @aiastia @how1ewu
> 
> 现在在我这里一切正常期待其他人的表现

测试了 azure 的和非azure 的 openai 目前都正常 （Openchat）

**Comment by songquanpeng** [comment]
Okay，感谢两位持续的测试反馈哈。

**Comment by how1ewu** [comment]
哈哈哈哈值得一个3.0了

**Comment by songquanpeng** [comment]
`v0.3` 版本目前打算是做完余额监控与可用性检测再放出。`v0.2.5` 的正式版会在解决完 #60 后放出。

**Comment by how1ewu** [comment]
3.0主要是加强管理功能了哈哈哈，我觉得做好了可以作为第三方面板供应方案。就好比cloudreve在网盘、兰空在图床

**Comment by songquanpeng** [comment]
是的，除了管理功能之后也会加入更多运营相关的功能。

**Comment by songquanpeng** [comment]
刚刚修复了一个额度未正常更新的恶性 bug，请更新程序。如果可以的话，请加入 demo 站首页的群。

**Comment by aiastia** [comment]
👍

**Comment by aiastia** [comment]
> 刚刚修复了一个额度未正常更新的恶性 bug，请更新程序。如果可以的话，请加入 demo 站首页的群。
> @aiastia @how1ewu @JeazW @18870 @lmuiotctf

为啥不搞个tg 群

**Comment by songquanpeng** [comment]
也可以，我更新一下。

**Comment by songquanpeng** [comment]
已更新。

**Comment by lmuiotctf** [comment]
ok，已经申请
