### ISSUE TITLE
阿里通义千问增加两个模型枚举

### ISSUE THREAD

**Issue by caotao94** [songquanpeng/one-api#570]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
阿里通义千问增加两个枚举
![image](https://github.com/songquanpeng/one-api/assets/31203266/9da55d42-9eb8-43be-9b05-29c2c746756a)
**应用场景**
有300w免费额度

**Comment by songquanpeng** [comment]
你是用的最新版本么



---Original---
From: ***@***.***&gt;
Sent at: 2023年10月1日(Sun) Noon11:21
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 阿里通义千问增加两个模型枚举 (Issue #570)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，已确定现有版本无法满足需求
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
功能描述
 阿里通义千问增加两个枚举
 
 应用场景
 有300w免费额度

**Comment by caotao94** [comment]
master的 v0.5.5

**Comment by songquanpeng** [comment]
这个最新版已经修复了



---Original---
From: ***@***.***&gt;
Sent at: 2023年10月1日(Sun) Noon11:38
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 阿里通义千问增加两个模型枚举 (Issue #570)




 
master的 v0.5.5

**Comment by caotao94** [comment]
好的，我去试试
