### ISSUE TITLE
添加Azure OpenAI类型的Whisper没有起作用

### ISSUE THREAD

**Issue by oudexin** [songquanpeng/one-api#577]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
选择类型为Azure OpenAI，并添加了Whisper-1模型，但是并没有起作用，docker日志显示查看回应是404。

**Comment by ivanberry** [comment]
请问你解决了吗？

我是找到了这样的报错parse " https://<domain_name>/v1/audio/transcriptions": first path segment in URL cannot contain colon (request id: 2023111920305332838443Exb2Js8S)

**Comment by caoliy3567** [comment]
我也是同样的问题，找不到模型，azure那边的模型是Whisper，one-API这边的模型必须配置为Whisper-1，所以必然有问题。
