### ISSUE TITLE
使用讯飞星火模型配置后，调用oneapi,并发5次请求，报错

### ISSUE THREAD

**Issue by kwz1993** [songquanpeng/one-api#588]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
报错内容
2023/10/11 12:47:47 [Recovery] 2023/10/11 - 12:47:47 panic recovered:
runtime error: index out of range [0] with length 0
/usr/local/go/src/runtime/panic.go:114 (0x438b1b)
/build/controller/relay-xunfei.go:223 (0xc7f25a)
/build/controller/relay-text.go:582 (0xc7a6cf)
/build/controller/relay.go:196 (0xc81c19)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c32a)
/build/middleware/distributor.go:96 (0xc9b7d9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c32a)
/build/middleware/auth.go:123 (0xc9b173)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c32a)
/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 (0xc9c41c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x92817d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x92814c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x91c32a)
/build/middleware/request-id.go:16 (0xc9c835)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x928fd9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x928fc7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x92723a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x926ecd)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x9269fc)
/usr/local/go/src/net/http/server.go:2938 (0x6d448d)
/usr/local/go/src/net/http/server.go:2009 (0x6d0373)
/usr/local/go/src/runtime/asm_amd64.s:1650 (0x46d0e0)
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by aoaostar** [comment]
![image](https://github.com/songquanpeng/one-api/assets/86001674/3ef95e67-d0c9-41ee-b0a2-fdcadd3a11d3)
才两个并发

**Comment by songquanpeng** [comment]
收到，估计是某个地方没处理好，报错日志很清楚，近期处理

**Comment by songquanpeng** [comment]
相关 PR 里没有对数组长度做校验，已修复。

**Comment by kwz1993** [comment]
请问下对应修复的版本推送至dockehub 仓库了吗？刚才尝试拉了下最新版本 justsong/one-api:latest 还是一样的报错问题
