### ISSUE TITLE
rate_limit_usage 字段非法 json 问题

### ISSUE THREAD

**Issue by kuangxiaoye** [songquanpeng/one-api#594]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ✅] 我已确认目前没有类似 issue
+ [ ✅] 我已确认我已升级到最新版本
+ [ ✅] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ✅] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ✅] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
大佬，在会话流中会出现一个字段：“"{\"rate_limit_usage\": {\”。我使用的是官方 apikey，非其他转发
**复现步骤**
任意会话请求
**预期结果**
rate_limit_usage字段不应该出现，因为是一个空 json，并且是一个非法的 json..会引起报错
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/43713316/941916e9-11b7-4016-9f21-5335cd1e92e1)

**Comment by kuangxiaoye** [comment]
JSON.parse()

方法的话就直接报错了，不清楚这个字段是为什么，还是官方返回的呀，佬

**Comment by terobox** [comment]
有佬会修复吗？官方讨论贴在这里：
https://community.openai.com/t/receiving-rate-limit-usage-in-completion-stream/427476

**Comment by kuangxiaoye** [comment]
看来我这里不是个例，看了下跟 j 佬关系不大，纯 openai 返回的字段，如果直接屏蔽掉，万一字段用得到，会出麻烦

还是自己在下游处理下了。。

**Comment by kuangxiaoye** [comment]
此贴终结 openai 已修复
