### ISSUE TITLE
windows版本 无法启动

### ISSUE THREAD

**Issue by 120018425** [songquanpeng/one-api#597]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
windows版本 无法启动   提示  [failed to initialize database: Error 1071: Specified key was too long; max key length is 1000 bytes] 
**复现步骤**
最新版本的exe，版本是从release里下的

**Comment by igophper** [comment]
你用的数据库版本说一下

**Comment by 120018425** [comment]
MySQL 5.5.62



***@***.***
 
发件人： igophper
发送时间： 2023-10-13 10:47
收件人： songquanpeng/one-api
抄送： Icarus; Author
主题： Re: [songquanpeng/one-api] windows版本 无法启动 (Issue #597)
你用的数据库版本说一下

**Comment by igophper** [comment]
数据库执行一下命令后再试一下`set GLOBAL storage_engine='InnoDb';`

**Comment by 120018425** [comment]
可用了，牛逼



***@***.***
 
发件人： igophper
发送时间： 2023-10-13 11:31
收件人： songquanpeng/one-api
抄送： Icarus; Author
主题： Re: [songquanpeng/one-api] windows版本 无法启动 (Issue #597)
数据库执行一下命令后再试一下set GLOBAL storage_engine='InnoDb';
