### ISSUE TITLE
渠道设置cloudflare AI Gateway代理地址出现的问题

### ISSUE THREAD

**Issue by babaohuang** [songquanpeng/one-api#598]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

最近 Cloudflare 推出了 AI Gateway 功能。官方文档：[Cloudflare文档](https://developers.cloudflare.com/ai-gateway/providers/openai/)
当我尝试为某个渠道设置代理时，直接填入 Cloudflare 的代理地址会出现问题。
文档说明：需要将 URL `https://api.openai.com/v1` 替换为 `https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai`。
但是渠道这里的设置的代理地址不应该是带有`v1`的，
所以当把这个渠道的代理地址设置为cloudflare的网关地址的时候，发送请求就会出现以下错误：

```json
{
    "error": {
        "message": "Invalid URL (POST /v1/v1/chat/completions) (request id: 202310132323017562520363iiTFK7q)",
        "type": "invalid_request_error",
        "param": "",
        "code": null
    }
}
```

**复现步骤**
1. 配置代理地址为 `https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai`
2. 尝试通过代理发送请求
3. 观察到上述错误

**预期结果**

希望能正确调用并返回

**实际结果**

得到 "Invalid URL" 错误。

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/559171/ea7e60a6-981f-4005-8379-0520ec68c456)

**Comment by songquanpeng** [comment]
已经支持，请参考 README 设置。

**Comment by babaohuang** [comment]
感谢大佬更新！可以正常使用了，但是测试渠道的时候还会报错
![image](https://github.com/songquanpeng/one-api/assets/559171/fc5672da-5f7d-4370-b7a8-1d906183ed57)

**Comment by befantasy** [comment]
是0.5.6就可以还是需要拉更新的镜像？

**Comment by babaohuang** [comment]
> 已经支持，请参考 README 设置。

渠道设置为Cloudflare AI Gateway之后可以正常使用，但是不能测试渠道 @songquanpeng 

![image](https://github.com/songquanpeng/one-api/assets/559171/919b235b-7f84-49b9-81a8-d82227e66db7)

**Comment by analogpvt** [comment]
same issue for azure openai as well

**Comment by woodchen-ink** [comment]
> > 已经支持，请参考 README 设置。
> 
> 渠道设置为Cloudflare AI Gateway之后可以正常使用，但是不能测试渠道 @songquanpeng
> 
> ![image](https://user-images.githubusercontent.com/559171/275409409-919b235b-7f84-49b9-81a8-d82227e66db7.png)

https://github.com/songquanpeng/one-api/pull/639，已pull，等待合并
