### ISSUE TITLE
额度计算过程中存在一些取整操作导致计算结果偏小

### ISSUE THREAD

**Issue by wzxjohn** [songquanpeng/one-api#599]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在 API 调用的额度计算过程中，存在两次取整（舍去小数）操作，导致最终计算额度消耗略微偏小。
**复现步骤**
调用 API，查看后台日志：
```
gpt-3.5-turbo 123        78        $0.000338        模型倍率 0.75，分组倍率 1.00
```
实际消耗 $0.000338
该数值的计算方式为：
```
78*1.33=103.74，取整保留 103
0.75*1*(123+103)=169.5，取整保留 169
169/500000=0.000338
```

**预期结果**
按照公式，本次调用的消耗应为：
```
0.75*1*(123+78*1.33)=170.055
170.055/500000=0.00034011
```
按照 OpenAPI 官方算法，本次调用的消耗应为：
```
123*0.0015/1000 + 78*0.002/1000=0.0003405
```

**Comment by caoguangxin888** [comment]
你好具体在那个文件内呢？我想去做一下修改
