### ISSUE TITLE
非 HTTPS 网站复制令牌时发生错误：复制失败

### ISSUE THREAD

**Issue by aohun** [songquanpeng/one-api#6]
chrome浏览器复制令牌失败，复制
![image](https://user-images.githubusercontent.com/37433539/233924826-6e8cf32a-30b6-4f81-8086-66bec420b4e8.png)

**Comment by songquanpeng** [comment]
我可以看一下控制台的输出吗？这个很奇怪。

**Comment by aohun** [comment]
使用docker部署的，docker logs中没用报错信息

**Comment by songquanpeng** [comment]
浏览器的控制台

**Comment by aohun** [comment]
![image](https://user-images.githubusercontent.com/37433539/233926209-391d3797-ec1e-4a75-821e-74ee81f735cb.png)

**Comment by songquanpeng** [comment]
请问 Chrome 的版本是多少？

**Comment by songquanpeng** [comment]
我用的是这个 API：
![image](https://user-images.githubusercontent.com/39998050/233926495-c6d47e0f-cd01-4f6b-87e5-61956f829793.png)

**Comment by aohun** [comment]
版本 112.0.5615.138（正式版本） （64 位）

**Comment by songquanpeng** [comment]
那这个就很离谱了，我用的也是这个版本，浏览器有禁用网站的剪切板读写权限吗？

**Comment by aohun** [comment]
![image](https://user-images.githubusercontent.com/37433539/233927784-38a9aa09-95d2-42dd-b835-570f69ac1b85.png)
好像是非https网站，chrome浏览器有限制

**Comment by songquanpeng** [comment]
原来是这样，我看有没有什么兼容的途径，感谢反馈。

**Comment by songquanpeng** [comment]
现在的兼容方案是将 token 放入了搜索框，这样可以手动复制。
