### ISSUE TITLE
点击首页会先显示一下原首页

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#60]
时间很短，但是能看到

**Comment by songquanpeng** [comment]
明天处理一下这个问题。

**Comment by songquanpeng** [comment]
已修复 & 已推送，另外添加了通过独立的网页来充当首页的功能。

**Comment by songquanpeng** [comment]
可以达成这样的效果：
![image](https://github.com/songquanpeng/one-api/assets/39998050/6ee9bd9d-5d8c-4f37-80d7-98e964700b4a)

**Comment by ilay1678** [comment]
关于页面也是这样

**Comment by songquanpeng** [comment]
> 关于页面也是这样

确实，感觉这样好玩一些会。

**Comment by songquanpeng** [comment]
已实现，已重新推送 `v0.2.5`。

**Comment by songquanpeng** [comment]
已支持自定义系统名称和 logo，已推送 `v0.2.6-alpha`。
