### ISSUE TITLE
令牌余额列表希望支持排序

### ISSUE THREAD

**Issue by mushan0x0** [songquanpeng/one-api#602]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

希望支持点击表头按余额排序，如果以管理员身份创建了很多令牌的话，这样就知道谁的用量最多

<img width="1010" alt="image" src="https://github.com/songquanpeng/one-api/assets/29084441/8b5be9c1-4ece-40bc-96e1-e4e160773eaf">

**应用场景**

**Comment by mrhaoji** [comment]
已支持 #1178
