### ISSUE TITLE
捐赠收款异常了

### ISSUE THREAD

**Issue by mushan0x0** [songquanpeng/one-api#603]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

大佬，可以给个别的方式支持一波不

**相关截图**
![IMG_2354](https://github.com/songquanpeng/one-api/assets/29084441/ca04e84e-63c0-4efa-9268-4307b5cffee8)

**Comment by songquanpeng** [comment]
感谢你的支持，请直接 QQ 私聊我谢谢！
