### ISSUE TITLE
请求支持 文心大模型4 ERNIE-Bot-4

### ISSUE THREAD

**Issue by renwofei423** [songquanpeng/one-api#608]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
文心大模型4（模型名称 ERNIE-Bot-4）已发布，请求支持
https://cloud.baidu.com/product/wenxinworkshop
**应用场景**

**Comment by jiusheng6** [comment]
加一

**Comment by onenov** [comment]
+1

**Comment by erdurisheng1ww** [comment]
+1

**Comment by jiumengs** [comment]
+1

**Comment by songquanpeng** [comment]
别刷 +1，直接点赞不行么，这样会导致给我发很多没有意义的邮件

**Comment by yanshan2023** [comment]
+1

**Comment by zhukunpenglinyutong** [comment]
+1

**Comment by songquanpeng** [comment]
已经按照文档进行了支持，不过之前别人给我提供的 key 调用不了，请测试一下。

**Comment by Donglong** [comment]
error unmarshalling stream response: invalid character 'r' looking for beginning of value  @songquanpeng
