### ISSUE TITLE
failed to get gpt-3.5-turbo token encoder:

### ISSUE THREAD

**Issue by jsubnew** [songquanpeng/one-api#609]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
      main.go会调用controller.InitTokenEncoders()方法，该方法会发起互联网访问获取TokenEncoders，获取异常直接退出启动了，这样的设计会导致整个项目能不能启动完全交给了网络，断网了情况服务无法启动，这样设计是否有问题？
    是否可以考虑内置呢，或者可配置。

**复现步骤**
    断网，启动项目
**预期结果**
    能启动成功

**Comment by jsubnew** [comment]
14. 缓存设置：
    + `TIKTOKEN_CACHE_DIR`：默认程序启动时会联网下载一些通用的词元的编码，如：[gpt-3.5-turbo](https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken),在一些网络环境不稳定，或者离线情况，可能会导致启动有问题，可以配置此目录缓存数据，可迁移到离线环境。
    + `DATA_GYM_CACHE_DIR`：目前该配置作用与`TIKTOKEN_CACHE_DIR`一致，但是优先级没有它高。

**Comment by shikeqiang** [comment]
同问咋解决

**Comment by password36** [comment]
这个怎么配置，离线环境过不去了。

**Comment by yixian3500** [comment]
同问怎么解决

**Comment by password36** [comment]
> 同问怎么解决

看了别的issues解决了，找一个能上网的机器，先run起来，然后从容器里把/tmp/data-gym-cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4 这个文件copy出来，再复制到内网容器中同样位置，这个是默认下载的分词文件。或者直接把外网的容器export出来也可以。

**Comment by XiongjieDai** [comment]
docker下载oneapi这步（docker-compose up -d）的时候梯子挂全局就行了！！！md拿GPT折腾了一晚上
