### ISSUE TITLE
在合适的地方显示发卡链接

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#61]
后台设置了发卡链接，点了一圈没有找到。如果写在自定义界面不够明显，可否加在充值弹窗：
![image](https://github.com/songquanpeng/one-api/assets/75829171/b12098e7-7744-4c8a-a273-3bfbf9d11d4c)

**Comment by songquanpeng** [comment]
会显示的，你刷新一下就好了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songquanpeng/one-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月13日(星期六) 晚上10:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[songquanpeng/one-api] 在合适的地方显示发卡链接 (Issue #61)





 
后台设置了发卡链接，点了一圈没有找到。如果写在自定义界面不够明显，可否加在充值弹窗：
