### ISSUE TITLE
OpenAI chat completion stop好像没有用

### ISSUE THREAD

**Issue by yhao-wang** [songquanpeng/one-api#613]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
![image](https://github.com/songquanpeng/one-api/assets/107921246/4a5cea4c-2f46-44f2-b8d6-866b6b8d9b9a)
![image](https://github.com/songquanpeng/one-api/assets/107921246/1a359a57-b9e4-486e-917a-e312229ff89f)

**应用场景**
加入stop后，输出到指定的序列就会停止输出
例如[ReAct HotpotQA](https://github.com/ysymyth/ReAct/blob/master/hotpotqa.ipynb)

**Comment by ye7love7** [comment]
我也发现了这个问题，现在还没解决吗？

**Comment by igophper** [comment]
请求openai渠道没发现问题
![image](https://github.com/songquanpeng/one-api/assets/34326532/a82914db-aefe-49d7-a788-ee6141d4d33e)
