### ISSUE TITLE
能否添加用户等级限制

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#62]
比如不同用户等级 调用频率不一样 可使用的模型范围不一样

**Comment by songquanpeng** [comment]
之后会结合用户组（#38）来实现这一机制。

**Comment by songquanpeng** [comment]
参考：[V2board ](https://github.com/v2board/v2board)

**Comment by aiastia** [comment]
感觉 可以这么搞  用户用 余额 购买套餐 - 然后套餐设置 - 不同权限  （比如token 个数 和 渠道 、模型）然后 有套餐就可以创建token。然后 token 可以在创建的时候指定使用的渠道 或者均衡。 计数统一在 用户上（算上倍率） 。token 只计数实际消耗 ，然后渠道也加上消耗 在搞个每日图表。😍 （然后看有没有必要接入当面付 之类的 。

**Comment by songquanpeng** [comment]
收到。
