### ISSUE TITLE
请求百川大模型对接

### ISSUE THREAD

**Issue by ahkimkoo** [songquanpeng/one-api#626]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
对接百川大模型（商业版），文档：https://platform.baichuan-ai.com/docs/api

**应用场景**

**Comment by songquanpeng** [comment]
Okay，近期处理，期待 PR

**Comment by songquanpeng** [comment]
https://github.com/songquanpeng/one-api/issues/1057
