### ISSUE TITLE
如何指定渠道 ID

### ISSUE THREAD

**Issue by vastxie** [songquanpeng/one-api#63]
可以通过在令牌后面添加渠道 ID 的方式指定使用哪一个渠道处理本次请求，例如：Authorization: Bearer ONE_API_KEY-CHANNEL_ID。 注意，需要是管理员用户创建的令牌才能指定渠道 ID。

这个是在哪加，方便给个示例？

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/432cc43f-a2b7-4278-a99a-3a1193c427ba)

**Comment by vastxie** [comment]
万分感谢🙇‍

**Comment by ocpinfo** [comment]
请问这个bearer直接在one api的渠道里面配置吗？比如我想通过Fastgpt调用这个渠道，如果能直接把Authorization: Bearer <token>写在渠道里面就方便了
