### ISSUE TITLE
Error 1406: Data too long for column 'key' at row 1

### ISSUE THREAD

**Issue by muxinxy** [songquanpeng/one-api#644]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
网页版ChatGPT转为API，添加渠道时使用accessToken作为API Key，其长度超出了MySQL数据库中channels表的key字段的长度限制。
**复现步骤**
程序运行时使用MySQL数据库。
**预期结果**
accessToken能完整存入key字段。

**Comment by We1eVen** [comment]
同样的问题。我尝试将mysql数据库中的“key”类型改为text，并重建索引，起初工作良好，但重启docker容器后同样报错 
```
[failed to initialize database: Error 1406: Data too long for column 'key' at row 1]
```

**Comment by 2guan** [comment]
能否去掉这个字段的索引。给key字段的充足的长度。以支持使用token模拟的方式？

**Comment by wu-shanglin** [comment]
https://github.com/wu-shanglin/accessToken-to-apiKey
希望对你有帮助

**Comment by JimmyLv** [comment]
添加 MiniMax JWT token 时也有报这个错， #354

**Comment by songquanpeng** [comment]
更新到最新版本后手动执行：`DROP INDEX idx_channels_key ON channels;`
