### ISSUE TITLE
one-api渠道增加chatglm2和m3e模型的时候报错

### ISSUE THREAD

**Issue by AiLiMeN** [songquanpeng/one-api#653]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
所有的项目均在本地服务器中，在one-api渠道中增加chatglm2和m3e模型渠道的时候点测试有报错，内容是：
错误：type，code<nil>，message，本地用curl调用模型的时候是对的，请问这个报错可能是什么原因？
**复现步骤**

**预期结果**

**相关截图**
![1](https://github.com/songquanpeng/one-api/assets/149573498/402b0731-8af8-446e-807b-9a48d397658f)

![2](https://github.com/songquanpeng/one-api/assets/149573498/92e8a612-a396-4a88-92da-96126e87e257)

![3](https://github.com/songquanpeng/one-api/assets/149573498/0cdd5fa0-14ad-4c19-8bd5-162b3c12847d)
![image](https://github.com/songquanpeng/one-api/assets/149573498/9151a09d-0cc8-4718-a979-bc02bccf7be9)

如果没有的话，请删除此节。

**Comment by gagakou** [comment]
有解决方法吗？
