### ISSUE TITLE
请求支持官方最新的定价

### ISSUE THREAD

**Issue by wzxjohn** [songquanpeng/one-api#674]
**功能描述**
https://openai.com/blog/new-models-and-developer-products-announced-at-devday

GPT-4 Turbo 128K
Input: $0.01
Output: $0.03

GPT-3.5 Turbo 16K
Input: $0.001
Output: $0.002

GPT-4 Turbo with vision
Input: $0.01
Output: $0.03

Base Token 85
Tile Token 170/tile(512x512)

**应用场景**
1. 新增对 GPT-4 Turbo GPT-4 V 的计费支持
2. 调整 GPT-3.5 模型的费用
3. 模型倍率适配官方新定价模型（GPT-3.5 Turbo 补全 1:2，GPT-4 Turbo 补全 1:3）

**Comment by ahkimkoo** [comment]
```json
{
  "360GPT_S2_V9": 0.8572,
  "ERNIE-Bot": 0.8572,
  "ERNIE-Bot-4": 8.572,
  "ERNIE-Bot-turbo": 0.5715,
  "Embedding-V1": 0.1429,
  "PaLM-2": 1,
  "SparkDesk": 1.2858,
  "ada": 10,
  "babbage": 10,
  "chatglm_lite": 0.1429,
  "chatglm_pro": 0.7143,
  "chatglm_std": 0.3572,
  "chatglm_turbo": 0.3572,
  "claude-2": 5.51,
  "claude-instant-1": 0.815,
  "code-davinci-edit-001": 10,
  "curie": 10,
  "dall-e": 8,
  "davinci": 10,
  "embedding-bert-512-v1": 0.0715,
  "embedding_s1_v1": 0.0715,
  "gpt-3.5-turbo": 0.75,
  "gpt-3.5-turbo-0301": 0.75,
  "gpt-3.5-turbo-0613": 0.75,
  "gpt-3.5-turbo-16k": 1.5,
  "gpt-3.5-turbo-16k-0613": 1.5,
  "gpt-3.5-turbo-instruct": 0.75,
  "gpt-3.5-turbo-1106":0.5,
  "gpt-3.5-turbo-instruct":0.75,
  "gpt-4": 15,
  "gpt-4-0314": 15,
  "gpt-4-0613": 15,
  "gpt-4-32k": 30,
  "gpt-4-32k-0314": 30,
  "gpt-4-32k-0613": 30,
  "gpt-4-1106-preview": 5,
  "gpt-4-1106-vision-preview":5,
  "hunyuan": 7.143,
  "qwen-plus": 10,
  "qwen-turbo": 0.8572,
  "semantic_similarity_s1_v1": 0.0715,
  "text-ada-001": 0.2,
  "text-babbage-001": 0.25,
  "text-curie-001": 1,
  "text-davinci-002": 10,
  "text-davinci-003": 10,
  "text-davinci-edit-001": 10,
  "text-embedding-ada-002": 0.05,
  "text-embedding-v1": 0.05,
  "text-moderation-latest": 0.1,
  "text-moderation-stable": 0.1,
  "text-search-ada-doc-001": 10,
  "whisper-1": 15
}
```

以上是我计算出的模型倍率，增加了最新的gpt模型倍率，计算方法是以0.002为基准，官方价格除以这个基准。不知道对不对，欢迎大家指正。

**Comment by wzxjohn** [comment]
> ```json
> {
>   "360GPT_S2_V9": 0.8572,
>   "ERNIE-Bot": 0.8572,
>   "ERNIE-Bot-4": 8.572,
>   "ERNIE-Bot-turbo": 0.5715,
>   "Embedding-V1": 0.1429,
>   "PaLM-2": 1,
>   "SparkDesk": 1.2858,
>   "ada": 10,
>   "babbage": 10,
>   "chatglm_lite": 0.1429,
>   "chatglm_pro": 0.7143,
>   "chatglm_std": 0.3572,
>   "chatglm_turbo": 0.3572,
>   "claude-2": 5.51,
>   "claude-instant-1": 0.815,
>   "code-davinci-edit-001": 10,
>   "curie": 10,
>   "dall-e": 8,
>   "davinci": 10,
>   "embedding-bert-512-v1": 0.0715,
>   "embedding_s1_v1": 0.0715,
>   "gpt-3.5-turbo": 0.75,
>   "gpt-3.5-turbo-0301": 0.75,
>   "gpt-3.5-turbo-0613": 0.75,
>   "gpt-3.5-turbo-16k": 1.5,
>   "gpt-3.5-turbo-16k-0613": 1.5,
>   "gpt-3.5-turbo-instruct": 0.75,
>   "gpt-3.5-turbo-1106":0.5,
>   "gpt-3.5-turbo-instruct":0.75,
>   "gpt-4": 15,
>   "gpt-4-0314": 15,
>   "gpt-4-0613": 15,
>   "gpt-4-32k": 30,
>   "gpt-4-32k-0314": 30,
>   "gpt-4-32k-0613": 30,
>   "gpt-4-1106-preview": 5,
>   "gpt-4-1106-vision-preview":5,
>   "hunyuan": 7.143,
>   "qwen-plus": 10,
>   "qwen-turbo": 0.8572,
>   "semantic_similarity_s1_v1": 0.0715,
>   "text-ada-001": 0.2,
>   "text-babbage-001": 0.25,
>   "text-curie-001": 1,
>   "text-davinci-002": 10,
>   "text-davinci-003": 10,
>   "text-davinci-edit-001": 10,
>   "text-embedding-ada-002": 0.05,
>   "text-embedding-v1": 0.05,
>   "text-moderation-latest": 0.1,
>   "text-moderation-stable": 0.1,
>   "text-search-ada-doc-001": 10,
>   "whisper-1": 15
> }
> ```
> 
> 以上是我计算出的模型倍率，增加了最新的gpt模型倍率，计算方法是以0.002为基准，官方价格除以这个基准。不知道对不对，欢迎大家指正。

不完全对，因为 OpenAI 更改了补全和提示的收费比例，代码里写死了比例，所以结果就不对了。
