### ISSUE TITLE
mysql部署有问题

### ISSUE THREAD

**Issue by yuanjie-ai** [songquanpeng/one-api#677]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
mysql部署有问题
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

[FATAL] 2023/11/07 - 14:08:22 | [Error 1045: Access denied for user 'root'@'172.17.0.2' (using password: YES)]

**Comment by yuanjie-ai** [comment]
[FATAL] 2023/11/07 - 14:08:22 | [Error 1045: Access denied for user 'root'@'172.17.0.2' (using password: YES)]

**Comment by wzxjohn** [comment]
这个提示说明你的数据库拒绝了程序的连接，看下是不是用户名密码配错了。

**Comment by yuanjie-ai** [comment]
```
docker run --name oneapi \
  -d --restart always \
  -p 39001:3000 \
  --add-host="host.docker.internal:host-gateway" \
  -e SQL_DSN="root:xxxxxxxxxxxxxxxx@tcp(host.docker.internal:3306)/oneapi" -e TZ=Asia/Shanghai \
  -v /root/data/oneapi:/data \
  justsong/one-api
```

**Comment by zhang570221322** [comment]
> ```
> docker run --name oneapi \
>   -d --restart always \
>   -p 39001:3000 \
>   --add-host="host.docker.internal:host-gateway" \
>   -e SQL_DSN="root:xxxxxxxxxxxxxxxx@tcp(host.docker.internal:3306)/oneapi" -e TZ=Asia/Shanghai \
>   -v /root/data/oneapi:/data \
>   justsong/one-api
> ```

我也遇到这个错误了，答案是把双引号去掉  SQL_DSN=root:xxxxxxxxxxxxxxxx@tcp(host.docker.internal:3306)/oneapi

**Comment by austincityu** [comment]
你好，这个问题解决了吗，我也遇到了

**Comment by yuanjie-ai** [comment]
解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月26日(周五) 中午12:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [songquanpeng/one-api] mysql部署有问题 (Issue #677)




 
你好，这个问题解决了吗，我也遇到了

**Comment by austincityu** [comment]
求指导，请教解决方法。

**Comment by austincityu** [comment]
> > ```
> > docker run --name oneapi \
> >   -d --restart always \
> >   -p 39001:3000 \
> >   --add-host="host.docker.internal:host-gateway" \
> >   -e SQL_DSN="root:xxxxxxxxxxxxxxxx@tcp(host.docker.internal:3306)/oneapi" -e TZ=Asia/Shanghai \
> >   -v /root/data/oneapi:/data \
> >   justsong/one-api
> > ```
> 
> 我也遇到这个错误了，答案是把双引号去掉 SQL_DSN=root:xxxxxxxxxxxxxxxx@tcp(host.docker.internal:3306)/oneapi

去掉引号反而报以下错误了：

**Comment by austincityu** [comment]
> > ```
> > docker run --name oneapi \
> >   -d --restart always \
> >   -p 39001:3000 \
> >   --add-host="host.docker.internal:host-gateway" \
> >   -e SQL_DSN="root:xxxxxxxxxxxxxxxx@tcp(host.docker.internal:3306)/oneapi" -e TZ=Asia/Shanghai \
> >   -v /root/data/oneapi:/data \
> >   justsong/one-api
> > ```
> 
> 我也遇到这个错误了，答案是把双引号去掉 SQL_DSN=root:xxxxxxxxxxxxxxxx@tcp(host.docker.internal:3306)/oneapi

去掉引号反而报错了 -bash: syntax error near unexpected token `('

**Comment by hongkungogo** [comment]
> 解决了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月26日(周五) 中午12:01 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [songquanpeng/one-api] mysql部署有问题 (Issue #677) 你好，这个问题解决了吗，我也遇到了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

我在访问外部mysql库的时候也遇到了相同的问题，请问您是如何解决的呢
