### ISSUE TITLE
请求添加智谱向量模型

### ISSUE THREAD

**Issue by z1073** [songquanpeng/one-api#682]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

智谱Embedding模型：
https://open.bigmodel.cn/dev/api#text_embedding

我尝试了下自定义添加无法成功调用，不知道我的方法是否正确：
![image](https://github.com/songquanpeng/one-api/assets/50789523/74ee929f-6393-4f97-9b18-fd867bf7a238)

**Comment by igophper** [comment]
标记一下，有空PR
