### ISSUE TITLE
求支持 gpt-4-vision

### ISSUE THREAD

**Issue by zion-c** [songquanpeng/one-api#683]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
新模型的 api 结构发生了变化，messages.content 由 string 变为了数组。
此时 oneapi 会报错：
json: cannot unmarshal array into Go struct field Message.messages.content of type string 
希望大佬支持一下
**应用场景**
gpt-4-vision

**Comment by samzong** [comment]
request +1

**Comment by 13105005020** [comment]
request +1

**Comment by lijie97** [comment]
Same problem

**Comment by QichangZheng** [comment]
same problem
