### ISSUE TITLE
修改了系统名称后页面标题没有改变

### ISSUE THREAD

**Issue by songquanpeng** [songquanpeng/one-api#69]
修改了系统名称后 页面标题没有改变。

_Originally posted by @Aiayw in https://github.com/songquanpeng/one-api/issues/65#issuecomment-1547827689_

**Comment by songquanpeng** [comment]
@Aiayw 我帮你新建 issue 了

**Comment by songquanpeng** [comment]
搞好了：
![image](https://github.com/songquanpeng/one-api/assets/39998050/afb229ca-f5fb-4b3c-a00b-afc7e6d2b95a)

你要是不急的话，我就之后和其他功能一起推送版本哈。

**Comment by Aiayw** [comment]
不急不急..只是一个小问题反馈，感谢大佬~
