### ISSUE TITLE
chatGTP渠道的/v1/chat/completions接口偶尔会404

### ISSUE THREAD

**Issue by shawnWXN** [songquanpeng/one-api#690]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
one-api: ghcr.io/songquanpeng/one-api:v0.5.7
linux: Ubuntu 20.04 LTS

我的客户端程序，在POST http://ip:3000/v1/chat/completions时，偶尔会报错404
**复现步骤**
```python
import requests
headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + 令牌,
    }

    json_data = {
        'model': 'gpt-3.5-turbo-1106',
        'messages': messages,
        'temperature': 0.1
    }

response = requests.post(url='http://ip:3000/v1/chat/completions', headers=headers, json=json_data)
logger.info(f"OpenAI Response[{response.status_code}] ==> {response.json()}")
```
**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/47786182/05f0c446-0bc7-470a-a2e0-1f1feb3243d8)

**Comment by mouxangithub** [comment]
你可以尝试在你的linux终端运行检测openai环境试试，运行指令在下面
`bash <(curl -Ls https://cdn.jsdelivr.net/gh/missuo/OpenAI-Checker/openai.sh)`

**Comment by shawnWXN** [comment]
我发现是偶尔问题，有可能跟openai自身有关。这个问题准备关闭了。
I've found that it's an occasional issue, which might be related to OpenAI itself. I'm ready to close this issue.

**Comment by shawnWXN** [comment]
我发现是偶尔问题，有可能跟openai自身有关。这个问题准备关闭了。
I've found that it's an occasional issue, which might be related to OpenAI itself. I'm ready to close this issue.
