### ISSUE TITLE
允许自定义顶栏菜单的标题和页面

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#70]
在当前的关于页面中，我们可以通过插入Markdown、HTML代码或链接来实现内嵌。
如果加入可自定义添加的页面和标题
这样一来，我们可以自定义多个页面，比如教程页面或外链跳转，又或者内嵌一些由网站运营者自建的ChatGPT网页服务。

**Comment by songquanpeng** [comment]
有这个打算，近期实现吧



---Original---
From: "Oliver ***@***.***&gt;
Sent at: 2023年5月15日(Mon) Evening11:09
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 自定义顶栏菜单的标题和页面 (Issue #70)




 
在当前的关于页面中，我们可以通过插入Markdown、HTML代码或链接来实现内嵌。
 如果加入可自定义添加的页面和标题
 这样一来，我们可以自定义多个页面，比如教程页面或外链跳转，又或者内嵌一些由网站运营者自建的ChatGPT网页服务。

**Comment by songquanpeng** [comment]
目前支持了自定义 Chat 页面，应该足以应付大部分场景了。
