### ISSUE TITLE
加了 --network="host"  后无法指定端口了

### ISSUE THREAD

**Issue by 120018425** [songquanpeng/one-api#701]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
要使用mysql做外网，根据文档的写的 需要在dorcker命令里增加--network="host"   并且用-p 3000:3000 来指定端口，但是他会提示因为用了--network="host"  在使用端口没有意义。
具体提示：
WARNING: Published ports are discarded when using host network mode
大概意思就是 主机用了这个模式会把端口给自动放弃，那如何来指定这个oneapi的端口呢。默认是3000 如果我想改成4000该怎么做
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by AkashiCoin** [comment]
host模式是和主机共享网络的模式，也就是这个docker和主机在同一网络下，`-p`是对docker端口映射到主机，而你和主机共享网络是不能进行映射的
你若是需要修改端口可以添加`-e PORT=4000`，这个环节变量可以修改oneapi监听的端口
