### ISSUE TITLE
求支持chatgpt api接口中的seed参数

### ISSUE THREAD

**Issue by JOHNNY-fans** [songquanpeng/one-api#708]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
求支持chatgpt api接口，seed参数。
在当前api接口使用中，完成确定性较强、时序依赖关系强的任务，例如多步多选，发现将温度设置为0还是不能稳定执行。
根据最新的openai发布会，他们提到接口中支持了seed参数用来稳定复现模型生成结果，求支持。

**应用场景**
确定性较强、时序依赖关系强的任务，需要稳定复现模型生成结果的场景。

**Comment by songquanpeng** [comment]
okay

**Comment by songquanpeng** [comment]
实际上如果你没有使用模型映射功能的话，请求体是透传的哈
