### ISSUE TITLE
使用openai生成图片的接口,日志处没有记录

### ISSUE THREAD

**Issue by wmc1125** [songquanpeng/one-api#709]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用OpenAI的图片生成接口( /v1/images/generations )
请求后可以获取图片数据,但是oneapi的日志中没有记录

**复现步骤**
请求地址: 域名+/v1/images/generations
```
$open_ai = new \lib\OpenAi($apikey);
$open_ai->setBaseURL($ai_gpt_host);
$_gpt_init = [
    'prompt' => $text,
    'num_images' => 1,
    'size' => '1024x1024',
];
$complete = $open_ai->image($_gpt_init);
```

**Comment by mouxangithub** [comment]
你没有添加dall-e模型吧，添加了就能在日志中查到dall-e的调用

**Comment by roamerxv** [comment]
同样问题。
日志不记录。
在 one api 里面自定义了一个 dall-e-3

**Comment by wmc1125** [comment]
> 同样问题。 日志不记录。 在 one api 里面自定义了一个 dall-e-3 <img alt="image" width="959" src="https://user-images.githubusercontent.com/1702265/283289588-82d87277-7b08-491a-b9f0-3d845a126345.png">

这个我加过,日志那里也没有记录

**Comment by mouxangithub** [comment]
> > 同样问题。 日志不记录。 在 one api 里面自定义了一个 dall-e-3 <img alt="image" width="959" src="https://user-images.githubusercontent.com/1702265/283289588-82d87277-7b08-491a-b9f0-3d845a126345.png">
> 
> 这个我加过,日志那里也没有记录

![1700122733333](https://github.com/songquanpeng/one-api/assets/48978046/149aabdb-6be4-4da4-a209-fb928ed7adaf)

**Comment by songquanpeng** [comment]
之前是没有适配，现在再试一下呢
