### ISSUE TITLE
兑换码充值成功未实时刷新状态

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#71]
![image](https://github.com/songquanpeng/one-api/assets/11790369/e015a16c-9f46-4dd6-ae94-1555f2eba4b8)
如图，充值了余额但还显示”已耗尽“提示

**Comment by songquanpeng** [comment]
需要手动启用。

**Comment by songquanpeng** [comment]
我之后加一下充值后自动启用吧。

**Comment by songquanpeng** [comment]
目前打算改动额度绑定在令牌上的做法，改为绑定在账户，这样设计会更加合理一些。

同时，允许用户给令牌设置配额，但是该配额仅供用户二次分发其令牌用，真正的额度消耗是消耗账户的配额。

**Comment by songquanpeng** [comment]
现在额度已绑定到账户上了，令牌的额度现在可以随意修改，在这种情况下感觉还是让用户手动启用好一些。

**Comment by Aiayw** [comment]
很棒的想法，这样用户可以给不同的令牌分配额度，拓展多种用途，例如不同的应用或网站使用不同的令牌，防止令牌泄露。

管理员应该在后台可以直接看到该用户的余额，也可以直接增加或减少余额，如果有Api还能自行对接开发其他充值渠道，不局限于兑换码形式。

**Comment by songquanpeng** [comment]
管理员可以看到额度，但是现在还没办法修改余额，这个请提新 issue。

其他充值渠道的对接也请提新 issue，我们可以就具体细节 & 流程进一步讨论。
