### ISSUE TITLE
错误：invalid character'<'looking for beginning of value

### ISSUE THREAD

**Issue by Cherry291** [songquanpeng/one-api#711]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
服务器可以ping通api.openai.com，但是渠道测试全部不通过
**复现步骤**
点击任意渠道测试，返回报错信息，已经测试阿里云香港和微软云jp，都能ping通api.openai.com，但是都无法测试渠道
**预期结果**
点击任意渠道测试，应该返回测试结果
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/71474660/9d3218f0-f858-4b51-9f84-2075e7c517ef)

如果没有的话，请删除此节。

**Comment by QAbot-zh** [comment]
发curl请求呢？
```
curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"
```

**Comment by ly1998117** [comment]
这个表示你的 ip 被 openai 封禁了

**Comment by zhiqiangwong** [comment]
被 ban 了，我这边也是换台代理服务器吧。

**Comment by songquanpeng** [comment]
是的，这是请求得到的响应是 HTML 页面所致，一般就是被 ban 了
