### ISSUE TITLE
Cloudflare AI Gateway 依然无法使用

### ISSUE THREAD

**Issue by mwnu** [songquanpeng/one-api#717]
版本已经升级到 v0.5.8

按文档添加渠道：
类型：OpenAI
代理：https://gateway.ai.cloudflare.com/v1/xxx/xxx/openai

测试的结果是：
错误：type invalid request_error,code <nil>,message Invalid URL(POST /v1/v1/chat/completions)

跟几周前是一样的。

**Comment by tshu-w** [comment]
可能需要等这个 PR 合并 https://github.com/songquanpeng/one-api/pull/666

**Comment by songquanpeng** [comment]
再试一下呢，如果还不行重开 issue
