### ISSUE TITLE
支持渠道分组

### ISSUE THREAD

**Issue by JeazW** [songquanpeng/one-api#72]
最终目的是toekn可以选择性在特定一些渠道中轮询，也可以在全部渠道中轮询。
例如管理员可以用此功能设置gpt4-key的渠道是一组，普通渠道key是一组，openai账号绑卡的key（官方设置绑卡后速率为3500次/min，否则为3次/min）渠道是一组。或者处于其他目的考虑，需要特定token去轮询特定的几个渠道。

**Comment by songquanpeng** [comment]
我先想一下怎么设计合理，等搞定了其他优先级更高的问题再来处理。
