### ISSUE TITLE
没适配cf

### ISSUE THREAD

**Issue by superen7527** [songquanpeng/one-api#725]
`支持 Cloudflare AI Gateway，渠道设置的代理部分填写 https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai 即可。`

CF这个路径是带v1的直接用会报错两个v1 不过没什么人用 建议从主页移除这个说明 不然单独适配匹配关键词去掉v1有点不优雅

**Comment by songquanpeng** [comment]
这个是修复了的哈，我本地测试是 okay 的。

这个功能还是有人需要的哈。

**Comment by fatwang2** [comment]
我这是可以正常使用，但是点击测试会报这个错误
