### ISSUE TITLE
【讨论】如何查看用户使用one-api

### ISSUE THREAD

**Issue by winter2399** [songquanpeng/one-api#726]
打扰大佬了。非常抱歉。这个问题会叨扰到作者，希望多多包涵。大佬的项目很好用。
本人最近使用one-api项目给用户提供免费服务，但不想让用户使用我提供的API再来对接one-api。
能通过查看Docker容器日志发现吗？我有时间看日志。
使用one-api与使用ChatGPT-next-Web、bettergpt这类项目在调用上有什么区别、特征？
比如：one-api渠道那里查询余额的与其他项目有什么区别？或者只要那个人使用one-api里的渠道测试功能，我这边容器日志会记录什么特征吗？
求各位大佬提供思路，摆脱各位大佬帮帮我。

**Comment by songquanpeng** [comment]
你可以通过 header 来判断，如果是浏览器访问 User Agent 会不一样哈

**Comment by winter2399** [comment]
![](https://github.com/songquanpeng/one-api/assets/144533817/5865e4a3-d9ce-4b34-a7be-85e94f4c3b43)

docker容器日志查不到请求的详细信息，有什么办法吗？求大佬解答
