### ISSUE TITLE
点击跳转到日志第一页和最后一页无效果

### ISSUE THREAD

**Issue by gptapius** [songquanpeng/one-api#727]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
日志的跳转到第一个页面和最后一个页面无效果，好像好多个版本了都没解决这个BUG
**复现步骤**
点击«和»实际上都只翻了一页，没有跳转到第一页和最后一页

**Comment by songquanpeng** [comment]
因为后面的没有加载，之后有时间就优化一下

**Comment by gptapius** [comment]
> 因为后面的没有加载，之后有时间就优化一下

好的大佬，确实是，加载了的点击是有效果的
另外修复whisper-1的问题能把在线镜像推送更新一下吗，下面这个命令检测不到更新
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR`

**Comment by songquanpeng** [comment]
刚刚推送了，等打包好之后再试一下。

**Comment by gptapius** [comment]
> 刚刚推送了，等打包好之后再试一下。

好的谢谢，那我就关了，后续有空您再优化翻页吧
