### ISSUE TITLE
请求添加钱多多API

### ISSUE THREAD

**Issue by E-sion** [songquanpeng/one-api#733]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+  我已确认目前没有类似 issue
+ 我已确认我已升级到最新版本
+ 我已完整查看过项目 README，已确定现有版本无法满足需求
+ 我理解并愿意跟进此 issue，协助测试和提供反馈
+ 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
https://api.aigcbest.top/
希望可以添加更多的API地址

**应用场景**

**Comment by KamiPasi** [comment]
在这打广告?

**Comment by mouxangithub** [comment]
直接选openai配代理不就行？？还是说是在打广告？

**Comment by Moneymore1998** [comment]
我是钱多多本人，这个帖子不是我发的，请作者删除即可，我们也不会在这些地方打广告，给大家造成不便，敬请谅解！
