### ISSUE TITLE
访问令牌必须把部署地址作为API BASE一起使用吗，可以用自己另外搭建的API BASE吗？国内服务器

### ISSUE THREAD

**Issue by ladypiapia** [songquanpeng/one-api#734]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我看项目的使用方法里面，有这么一段```你需要在各种用到 OpenAI API 的地方设置 API Base 为你的 One API 的部署地址，例如：https://openai.justsong.cn，API Key 则为你在 One API 中生成的令牌。```，是否意味着API BASE必须使用项目部署的地址呢，而不能用其他已经搭建好的API BASE地址？
**复现步骤**
我是用的国内的服务器，已经通过docker部署了one-api，并添加了渠道，测试时用了自己另外搭建的API BASE代理地址 **https://openai-proxy.xxxx.com** ，测试成功，而不是用的部署地址 **https://xx.xx.xx.xx:3000/v1** ；然后添加了令牌，在使用令牌时，我是测试的chat-on-wechat项目，OPEN_AI_API_KEY是填的令牌，OPEN_AI_API_BASE是填的 **https://openai-proxy.xxxx.com** ，然后就提示以下报错
**预期结果**
```python
[ERROR][2023-11-21 03:46:17][chat_gpt_bot.py:154] - [CHATGPT] Exception: Incorrect API key provided: sk-YVlSh***************************************56C7. You can find your API key at https://platform.openai.com/account/api-keys.
```

**Comment by QAbot-zh** [comment]
谁生成的令牌，填谁的url。渠道里key填人家的url，你生成的令牌跟你部署的地址配对。

**Comment by ladypiapia** [comment]
> 谁生成的令牌，填谁的url。渠道里key填人家的url，你生成的令牌跟你部署的地址配对。

感谢解答，唉，主要是自己的服务器是国内的，用部署的地址是国内ip，访问不了OpenAI

**Comment by seven2202** [comment]
你的渠道填写别人的中转地址和中转key就行啦，套娃！

**Comment by seven2202** [comment]
还是不行，加我Q，远程给你看看。252519042

**Comment by roamerxv** [comment]
套娃。套娃。我这里都套了 3 层娃了。 最后一层是不是还是套的，还不知道

**Comment by songquanpeng** [comment]
看起来问题已经解决了哈，先关了
