### ISSUE TITLE
whisper模型报错

### ISSUE THREAD

**Issue by BenedictKing** [songquanpeng/one-api#735]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当前版本One API v0.5.8-alpha.4，openai API版本是1.3.3，我用whisper模型转录MP3，如果直接调用官方api key就没有问题，如果用one-api中转就会报这个错误
`
InternalServerError: Error code: 500 - {'error': {'message': "invalid character 'å' looking for beginning of value (request id: 20231121193930285582120Q0aH46sB)", 'type': 'one_api_error', 'param': '', 'code': 'unmarshal_response_body_failed'}}
`

**复现步骤**
api调用方法
```
client = OpenAI(api_key=,base_url=)
audio_file = open("tmp.mp3", "rb")
transcript = client.audio.transcriptions.create(
  model="whisper-1", 
  file=audio_file, 
  response_format="text"
)
```

**Comment by igophper** [comment]
可以给个key给我复现吗？没办法复现，没办法解决

**Comment by BenedictKing** [comment]
> 可以给个key给我复现吗？没办法复现，没办法解决

好的，麻烦了，我把整个测试代码给你：
```
from openai import OpenAI
client = OpenAI(
    api_key="sk-UVCGQMhjPJ3Oz22X74E382B44e1c487287B71b8aA8EfAb5c",
    base_url="https://xh.xiaohuiai.top/v1"
)
chat_completion = client.chat.completions.create(
    model="gpt-3.5-turbo-16k",
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
)

print(chat_completion.choices[0].message)

response = client.audio.speech.create(
                model="tts-1",
                voice="alloy",
                input="""
                "几个"是一个中文词语，可以有不同的意思，具体要根据上下文来判断。以下是几个可能的意思：

1. 表示数量：通常用来询问或确定一个数量。例如，“你有几个兄弟姐妹？”意思是询问对方有几个兄弟姐妹。

2. 表示程度：有时用来表示程度或数量的不确定性。例如，“这个问题有几个答案。”意思是这个问题可能有多个答案。

3. 表示时间：在一些方言中，可以用来表示一段时间。例如，“他在这里等了几个小时。”意思是他在这里等了几个小时。
                """
            )
response.stream_to_file("tmp.mp3")

audio_file = open("tmp.mp3", "rb")
transcript = client.audio.transcriptions.create(
  model="whisper-1", 
  file=audio_file, 
  response_format="text"
)

print(transcript)
```

**Comment by igophper** [comment]
你把format改为json，one-api现在支持json

**Comment by GodBlessNoBugs** [comment]
大哥啥有空能适配一下whisper模型的srt返回格式不，做视频字幕不能srt格式返回好难受QAQ

**Comment by GodBlessNoBugs** [comment]
> > 大哥啥有空能适配一下whisper模型的srt返回格式不，做视频字幕不能srt格式返回好难受QAQ
> 
> 今天有空就提PR

谢谢大哥

**Comment by terobox** [comment]
> 你把format改为json，one-api现在只支持json
> 
> ```
> transcript = client.audio.transcriptions.create(
>   model="whisper-1", 
>   file=audio_file, 
>   response_format="json"
> )
> ```

我佬有空可以帮忙补全一下format格式吗

**Comment by igophper** [comment]
> > 你把format改为json，one-api现在只支持json
> > ```
> > transcript = client.audio.transcriptions.create(
> >   model="whisper-1", 
> >   file=audio_file, 
> >   response_format="json"
> > )
> > ```
> 
> 我佬有空可以帮忙补全一下format格式吗

好的，我今天会提PR，你有一些MP3的文件可以提供给我试试吗？我需要测试文件。

**Comment by GodBlessNoBugs** [comment]
> > > 你把format改为json，one-api现在只支持json
> > > ```
> > > transcript = client.audio.transcriptions.create(
> > >   model="whisper-1", 
> > >   file=audio_file, 
> > >   response_format="json"
> > > )
> > > ```
> > 
> > 
> > 我佬有空可以帮忙补全一下format格式吗
> 
> 好的，我今天会提PR，你有一些MP3的文件可以提供给我试试吗？我需要测试文件。

大哥，给个邮箱，我这儿有mp3文件，最近都在使用whisper接口转文字。

**Comment by igophper** [comment]
> > > > 你把format改为json，one-api现在只支持json
> > > > ```
> > > > transcript = client.audio.transcriptions.create(
> > > >   model="whisper-1", 
> > > >   file=audio_file, 
> > > >   response_format="json"
> > > > )
> > > > ```
> > > 
> > > 
> > > 我佬有空可以帮忙补全一下format格式吗
> > 
> > 
> > 好的，我今天会提PR，你有一些MP3的文件可以提供给我试试吗？我需要测试文件。
> 
> 大哥，给个邮箱，我这儿有mp3文件，最近都在使用whisper接口转文字。

admin@jialigu.cn

**Comment by GodBlessNoBugs** [comment]
> > > > > 你把format改为json，one-api现在只支持json
> > > > > ```
> > > > > transcript = client.audio.transcriptions.create(
> > > > >   model="whisper-1", 
> > > > >   file=audio_file, 
> > > > >   response_format="json"
> > > > > )
> > > > > ```
> > > > 
> > > > 
> > > > 我佬有空可以帮忙补全一下format格式吗
> > > 
> > > 
> > > 好的，我今天会提PR，你有一些MP3的文件可以提供给我试试吗？我需要测试文件。
> > 
> > 
> > 大哥，给个邮箱，我这儿有mp3文件，最近都在使用whisper接口转文字。
> 
> [admin@jialigu.cn](mailto:admin@jialigu.cn)

已发送，请查收

**Comment by igophper** [comment]
> > > > > > 你把format改为json，one-api现在只支持json
> > > > > > ```
> > > > > > transcript = client.audio.transcriptions.create(
> > > > > >   model="whisper-1", 
> > > > > >   file=audio_file, 
> > > > > >   response_format="json"
> > > > > > )
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 我佬有空可以帮忙补全一下format格式吗
> > > > 
> > > > 
> > > > 好的，我今天会提PR，你有一些MP3的文件可以提供给我试试吗？我需要测试文件。
> > > 
> > > 
> > > 大哥，给个邮箱，我这儿有mp3文件，最近都在使用whisper接口转文字。
> > 
> > 
> > [admin@jialigu.cn](mailto:admin@jialigu.cn)
> 
> 已发送，请查收

好的，收到了

**Comment by igophper** [comment]
最新版本已经支持各种格式 @GodBlessNoBugs @terobox @BenedictKing

**Comment by GodBlessNoBugs** [comment]
> 最新版本已经支持各种格式 @GodBlessNoBugs @terobox @BenedictKing

谢谢大哥
