### ISSUE TITLE
Anthropic Cluade 2.1 Support

### ISSUE THREAD

**Issue by JamesFlare1212** [songquanpeng/one-api#736]
Anthropic just released[ Cluade 2.1 API Calling](https://docs.anthropic.com/claude/reference/selecting-a-model), they recommand use `claude-2.1` and `claude-2.0` to call the model, instead of `claude-2`.

Also, it [support system prompt](https://docs.anthropic.com/claude/docs/claude-2p1-guide), so, may be we can process it as asme as OpenAI API.

it looks like:

```text
You are a fashion industry expert. Your task is to help users by answering questions related to the fashion industry or by excuting tasks requested of you. If the task is unrelated to the fashion industry, then say "I cannot help with anything not related to fashion."

Human: Provide three potential names for a handbag startup targeting luxury consumers and explain your choices.

Assistant:
```

**Comment by JamesFlare1212** [comment]
Also, it [support system prompt](https://docs.anthropic.com/claude/docs/claude-2p1-guide), so, may be we can process it as asme as OpenAI API.

**Comment by songquanpeng** [comment]
Done
