### ISSUE TITLE
关于支持 OpenAPI 协议的问题

### ISSUE THREAD

**Issue by zhaoyii** [songquanpeng/one-api#744]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
请求增加开放 API（OpenAPI）功能，以满足我的后端服务与 OneAPI 接口集成。翻看了OneAPI，好像近期没有支持计划。

**应用场景**
我开发了一个应用，我的后端有一套用户服务，想调用 OneAPI 的额度管理接口，完成付费充值、调用时检查剩余额度等功能。

**Comment by songquanpeng** [comment]
有修改额度的接口的，你抓包就好了，然后用系统访问令牌鉴权即可：
![image](https://github.com/songquanpeng/one-api/assets/39998050/424e1270-f26c-4668-8644-f542bd07bfbe)

**Comment by zhaoyii** [comment]
@songquanpeng 感谢 ♪(･ω･)ﾉ
