### ISSUE TITLE
增加用户邀请与奖励

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#75]
用户可生成邀请码，通过邀请码和邀请链接成功邀请其他用户注册后对双方给予奖励。

1、注册成功即奖励
2、根据被邀请用户的充值额度进行不同比例的额度奖励。

**Comment by songquanpeng** [comment]
目前打算，
1. 邀请人的收益是每次被邀请人充值时获取一定比例的额度。
2. 被邀请人在创建账号时获取一次性的奖励额度。

**Comment by Aiayw** [comment]
但是目前没接入支付系统，第一个想法是通过兑换码的数量进行比例分配么？
第二个想法是被邀请人注册成功后，推荐人获得一次性奖励？

**Comment by songquanpeng** [comment]
1. 是，
2. 被邀请人获得奖励额度

**Comment by Aiayw** [comment]
感觉这样对推荐人吸引力不够大，比较合理的邀请系统应该是主要奖励推荐人，如何吸引被邀请用户的难题交给推荐人。
例如拼多多，砍一刀对被邀请人几乎没有奖励，但是推荐人会想方设法去实现推广。

**Comment by Aiayw** [comment]
毕竟推荐人也不能保证推荐的用户能够充值，奖励反馈太慢就没动力推广了

**Comment by songquanpeng** [comment]
也确实，那就改成双方各获得一定比例的额度。

**Comment by songquanpeng** [comment]
已实现，已推送。
