### ISSUE TITLE
DALL-E-3 生成图片报错

### ISSUE THREAD

**Issue by ShinChven** [songquanpeng/one-api#751]
**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，尤其是常见问题部分
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

我使用的是 Azure OpenAI 的渠道，在使用 Python OpenAI 客户端或第三方客户端调用 One-API 的 DALL-E-3 模型生成图片时报错，
在错误信息为 

```
API Error: Status Code 400, {"error":{"message":"relay error (request id: <ID>)","type":"one_api_error","param":"","code":"n_not_within_range"}}"。
```

第三方客户端的仓库那边也有人报告用 One-API 生成图片遇到的相同的错误：https://github.com/Bin-Huang/chatbox/issues/1049

**复现步骤**

1. 使用 Python OpenAI 客户端或第三方客户端尝试调用 DALL-E-3。
2. 观察到 API 返回错误信息。

**预期结果**

成功调用 DALL-E-3 并生成图片，而不是收到错误信息。

**相关截图**

（如果您有错误信息的截图，请附上。如果没有，请删除此节。）

**Comment by QAbot-zh** [comment]
参数传对了吗？我使用是正常的

**Comment by xueycn** [comment]
第三方API为：[https://api.aigcapi.io](https://aigcapi.io/)
联系第三方在线客服，反馈该api经测试可以生成图片。实测用Chatbox会发生如下报错：

![屏幕截图 2023-11-28 111530](https://github.com/songquanpeng/one-api/assets/42319169/4579f134-dcfb-473c-aa6e-43e137ea1122)
```
遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 400, {"error":{"message":"relay error (request id: 20231128031447596282495QuQFC4Ki)","type":"one_api_error","param":"","code":"n_not_within_range"}}
```

**Comment by ShinChven** [comment]
> 参数传对了吗？我使用是正常的

请问能提供一个正确的调用示例吗？

**Comment by QAbot-zh** [comment]
> > 参数传对了吗？我使用是正常的
> 
> 请问能提供一个正确的调用示例吗？

就是用的官方库：
```
response = openai.Image.create(prompt=query, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
image_url = response["data"][0]["url"]
```

**Comment by ShinChven** [comment]
> > > 参数传对了吗？我使用是正常的
> > 
> > 
> > 请问能提供一个正确的调用示例吗？
> 
> 就是用的官方库：
> 
> ```
> response = openai.Image.create(prompt=query, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
> image_url = response["data"][0]["url"]
> ```


```py
from openai import OpenAI


# Set your OpenAI API key and custom domain endpoint
api_key = '<api_key>'
api_base = '<host>/v1/'  # Replace with your custom domain URL
prompt = 'gundam in a ruined cityscape'

client = OpenAI(api_key=api_key, base_url=api_base)

response = client.images.generate(prompt=prompt, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
# image_url = response["data"][0]["url"]

print(response)
```

```
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
```

不太对。 openai==1.3.5

**Comment by QAbot-zh** [comment]
> > > > 参数传对了吗？我使用是正常的
> > > 
> > > 
> > > 请问能提供一个正确的调用示例吗？
> > 
> > 
> > 就是用的官方库：
> > ```
> > response = openai.Image.create(prompt=query, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
> > image_url = response["data"][0]["url"]
> > ```
> 
> ```python
> from openai import OpenAI
> 
> 
> # Set your OpenAI API key and custom domain endpoint
> api_key = '<api_key>'
> api_base = '<host>/v1/'  # Replace with your custom domain URL
> prompt = 'gundam in a ruined cityscape'
> 
> client = OpenAI(api_key=api_key, base_url=api_base)
> 
> response = client.images.generate(prompt=prompt, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
> # image_url = response["data"][0]["url"]
> 
> print(response)
> ```
> 
> ```
> openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
> ```
> 
> 不太对。 openai==1.3.5

404的话检查你的网络问题以及上游代理key的问题
![image](https://github.com/songquanpeng/one-api/assets/40236765/f5dd99aa-46f2-4440-bf11-d6b85e266c3d)

**Comment by ShinChven** [comment]
> > > > > 参数传对了吗？我使用是正常的
> > > > 
> > > > 
> > > > 请问能提供一个正确的调用示例吗？
> > > 
> > > 
> > > 就是用的官方库：
> > > ```
> > > response = openai.Image.create(prompt=query, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
> > > image_url = response["data"][0]["url"]
> > > ```
> > 
> > 
> > ```python
> > from openai import OpenAI
> > 
> > 
> > # Set your OpenAI API key and custom domain endpoint
> > api_key = '<api_key>'
> > api_base = '<host>/v1/'  # Replace with your custom domain URL
> > prompt = 'gundam in a ruined cityscape'
> > 
> > client = OpenAI(api_key=api_key, base_url=api_base)
> > 
> > response = client.images.generate(prompt=prompt, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
> > # image_url = response["data"][0]["url"]
> > 
> > print(response)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不太对。 openai==1.3.5
> 
> 404的话检查你的网络问题以及上游代理key的问题 ![image](https://private-user-images.githubusercontent.com/40236765/286235865-f5dd99aa-46f2-4440-bf11-d6b85e266c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzI4MjAsIm5iZiI6MTcwMTE3MjUyMCwicGF0aCI6Ii80MDIzNjc2NS8yODYyMzU4NjUtZjVkZDk5YWEtNDZmMi00NDQwLWJmMTEtZDZiODVlMjY2YzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExNTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MDliOTU4NTNhYjE0MDlhN2I2ZWE5MGUxNTY2ZDE0NmIwMmJiYjQyYzVlYTEyYzgwNjljOTMyZTA3NzM1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.alM-I0cbU3Livi5AZrkxoK7G_rEbDV4xjGdSwWPFbkg)

[[GetRandomSatisfiedChannel](https://github.com/songquanpeng/one-api/i)](https://github.com/songquanpeng/one-api/blob/main/middleware/distributor.go#L58C4-L58C4)

我把代码拉下来debugger了一下，发现根本就没对 dall-e-3 做支持。你用的是哪个版本？

**Comment by ShinChven** [comment]
https://github.com/songquanpeng/one-api/blob/main/controller/relay-utils.go#L186
	
这一行代码很可疑，好像直接跳过了，没有进去找 Azure 的路由。

**Comment by ShinChven** [comment]
> > > > > 参数传对了吗？我使用是正常的
> > > > 
> > > > 
> > > > 请问能提供一个正确的调用示例吗？
> > > 
> > > 
> > > 就是用的官方库：
> > > ```
> > > response = openai.Image.create(prompt=query, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
> > > image_url = response["data"][0]["url"]
> > > ```
> > 
> > 
> > ```python
> > from openai import OpenAI
> > 
> > 
> > # Set your OpenAI API key and custom domain endpoint
> > api_key = '<api_key>'
> > api_base = '<host>/v1/'  # Replace with your custom domain URL
> > prompt = 'gundam in a ruined cityscape'
> > 
> > client = OpenAI(api_key=api_key, base_url=api_base)
> > 
> > response = client.images.generate(prompt=prompt, model='dall-e-3', size='1024x1024',style='vivid', quality='standard', n=1)
> > # image_url = response["data"][0]["url"]
> > 
> > print(response)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不太对。 openai==1.3.5
> 
> 404的话检查你的网络问题以及上游代理key的问题 ![image](https://private-user-images.githubusercontent.com/40236765/286235865-f5dd99aa-46f2-4440-bf11-d6b85e266c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzQ4NzcsIm5iZiI6MTcwMTE3NDU3NywicGF0aCI6Ii80MDIzNjc2NS8yODYyMzU4NjUtZjVkZDk5YWEtNDZmMi00NDQwLWJmMTEtZDZiODVlMjY2YzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEyMjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDY1MTg0ZDc3ZjliMDRjY2NiZDk2OTI0MzUyOTMyYjFiMjc1NTllMGE5MTk3MTE2ZjIwMThmOTk3N2Y3MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U_-UtepM5rz8k_QSKd2U_n_hUvRpHWfwc0Do0eAO6zM)

https://github.com/songquanpeng/one-api/blob/main/controller/relay-utils.go#L191
	
这一行代码很可疑，好像直接跳过了，没有进去找 Azure 的路由。

因为调用 DALL-E-3 的时候 传入了`requestURL`从而忽略了`openai/deployments`

**Comment by ShinChven** [comment]
我似乎修完了，等下搞个PR
