### ISSUE TITLE
计费问题

### ISSUE THREAD

**Issue by Phfebb** [songquanpeng/one-api#758]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

不理解这个计费方式，算了好久也没对上0.0，求解。

倍率相关使用的默认配置
代理网关：cloudflare，可以看到消耗的token
AI模型：gpt-3.5-Turbo-1106

发送了一条信息进行测试：
cf 后台日志显示 token 提示15，补全69，总共84
one-api 后台日志显示 token 提示15，补全82，额度90

**复现步骤**

**预期结果**

**相关截图**

**Comment by wzxjohn** [comment]
建议补充一下你认为有问题的原始请求和响应，这样也好排查问题。
cf 好像可以把请求和响应都打出来的。
