### ISSUE TITLE
Invalid interpolation format for "healthcheck"

### ISSUE THREAD

**Issue by leoterry-ulrica** [songquanpeng/one-api#759]
docker-compose up -d部署后提示以下错误：

Invalid interpolation format for "healthcheck" option in service "one-api": "wget -q -O - http://localhost:3000/api/status | grep -o '"success":\s*true' | awk -F: '{print $2}'"

**Comment by fatbun** [comment]
same here

**Comment by jjaychen1e** [comment]
same here

**Comment by levie-vans** [comment]
I changed it to this:
`test: ["CMD-SHELL", "curl -s http://localhost:3000/api/status | tee /dev/stderr | grep '\"success\":\\s*true' || exit 1"]`

**Comment by xiaohuakang** [comment]
> I changed it to this: `test: ["CMD-SHELL", "curl -s http://localhost:3000/api/status | tee /dev/stderr | grep '\"success\":\\s*true' || exit 1"]`

有用

**Comment by Belee05** [comment]
> I changed it to this: `test: ["CMD-SHELL", "curl -s http://localhost:3000/api/status | tee /dev/stderr | grep '\"success\":\\s*true' || exit 1"]`

It worked for me.
