### ISSUE TITLE
超级管理员不需要显示在用户表

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#76]
对超级管理员的操作只有密码更改，无需显示在用户表。

前端排除掉管理员的用户组即可。

![image](https://github.com/songquanpeng/one-api/assets/11790369/9a0eb99c-e48e-43f5-967f-a5e14c5a1fd5)

不太清楚原有显示逻辑是否特意设计，所以没创建拉取请求。

**Comment by songquanpeng** [comment]
这是考虑到之后k可能会出现这种场景：
![image](https://github.com/songquanpeng/one-api/assets/39998050/1fbb6d86-0653-46f9-8f22-b3b184305269)

**Comment by songquanpeng** [comment]
如果不显示就没办法控制了。

**Comment by Aiayw** [comment]
> 如果不显示就没办法控制了。

超级管理员不需要单独再授予权限了吧。普通管理员可以正常显示

**Comment by songquanpeng** [comment]
也确实，之后处理一下。
