### ISSUE TITLE
模型倍率是啥意思？咋计算的？

### ISSUE THREAD

**Issue by kenneth-bro** [songquanpeng/one-api#766]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
模型倍率是啥意思啊，咋计算的，没看懂，新手求解释
**复现步骤**

**预期结果**

**Comment by QAbot-zh** [comment]
https://github.com/songquanpeng/one-api#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by kenneth-bro** [comment]
> https://github.com/songquanpeng/one-api#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

就是没懂这个模型倍率

**Comment by Ekko1048** [comment]
同，求解

**Comment by QAbot-zh** [comment]
> 同，求解

我来好好解释一下吧。以下内容暂时忽略分组倍率。
已知：①提示token数即官方的Input，补全token数即官方的Output。②OneAPI默认 1$ = 50w tokens，即0.002$/1k tokens，把这个叫做基准价格。
以gpt-3.5-turbo-1106为例，它的倍率设置如下：
| 模型名称 | 输入价格 | 输出价格 |
|----------|----------|----------|
| gpt-3.5-turbo-1106 | 0.001$/1k tokens   |  0.002$/1k tokens |
|  | 模型倍率=输入价格/基准价格 | 补全倍率=输出价格/输入价格  |
|  | 0.001/0.002=0.5      |  0.002/0.001=2    |

**官方的价格公式：输入价格 \* 输入token数 + 输出价格 \* 输出token数**
**OneAPI的价格公式：
  模型倍率 \* （提示token数  + 补全token数 \* 补全倍率）
= 模型倍率 \* 提示token数 + 模型倍率 \* 补全倍率 \* 补全token数 
= （输入价格/基准价格） \* 输入token数 + （输出价格/基准价格）\* 输出token数
= （输入价格 \* 输入token数 + 输出价格 \* 输出token数)）/ 基准价格**

可以看到，它们只差了一个固定参数，即基准价格，程序后台计算完统一乘上基准价格就好了。
你说为什么基准价格为什么定在1$=50w tokens？那自然是因为最开始基准价格是参考的gpt-3.5-turbo的输入价格0.002$/1k tokens，降价是后来的事情了。
你要问为什么选择倍率体系，不直接使用价格体系，那就得问作者了。

**Comment by Ekko1048** [comment]
> > 同，求解
> 
> 我来好好解释一下吧。以下内容暂时忽略分组倍率。 已知：①提示token数即官方的Input，补全token数即官方的Output。②OneAPI默认 1$ = 50w tokens，即0.002$/1k tokens，把这个叫做基准价格。 以gpt-3.5-turbo-1106为例，它的倍率设置如下：
> 
> **基准价格：0.002$/1k tokens**
> 模型名称	输入价格	输出价格
> gpt-3.5-turbo-1106	0.001$/1k tokens	0.002$/1k tokens
> **模型倍率=输入价格/基准价格**	**补全倍率=输出价格/输入价格**
> 0.001/0.002=0.5	0.002/0.001=2
> **官方的价格公式：输入价格 * 输入token数 + 输出价格 * 输出token数** **OneAPI的价格公式： 模型倍率 * （提示token数 + 补全token数 * 补全倍率） = 模型倍率 * 提示token数 + 模型倍率 * 补全倍率 * 补全token数 = （输入价格/基准价格） * 输入token数 + （输出价格/基准价格）* 输出token数 = （输入价格 * 输入token数 + 输出价格 * 输出token数)）/ 基准价格**
> 
> 可以看到，它们只差了一个固定参数，即基准价格，程序后台计算完统一乘上基准价格就好了。 你说为什么基准价格为什么定在1$=50w tokens？那自然是因为最开始基准价格是参考的gpt-3.5-turbo的输入价格0.002$/1k tokens，降价是后来的事情了。 你要问为什么选择倍率体系，不直接使用价格体系，那就得问作者了。

每个模型的基准价格会变动吗？还是固定的？可以在哪里查看呢？大佬

**Comment by QAbot-zh** [comment]
> > > 同，求解
> > 
> > 
> > 我来好好解释一下吧。以下内容暂时忽略分组倍率。 已知：①提示token数即官方的Input，补全token数即官方的Output。②OneAPI默认 1$ = 50w tokens，即0.002$/1k tokens，把这个叫做基准价格。 以gpt-3.5-turbo-1106为例，它的倍率设置如下：
> > **基准价格：0.002$/1k tokens**
> > 模型名称	输入价格	输出价格
> > gpt-3.5-turbo-1106	0.001$/1k tokens	0.002$/1k tokens
> > **模型倍率=输入价格/基准价格**	**补全倍率=输出价格/输入价格**
> > 0.001/0.002=0.5	0.002/0.001=2
> > **官方的价格公式：输入价格 * 输入token数 + 输出价格 * 输出token数** __OneAPI的价格公式： 模型倍率 * （提示token数 + 补全token数 * 补全倍率） = 模型倍率 * 提示token数 + 模型倍率 * 补全倍率 * 补全token数 = （输入价格/基准价格） * 输入token数 + （输出价格/基准价格）_ 输出token数 = （输入价格 * 输入token数 + 输出价格 * 输出token数)）/ 基准价格_*
> > 可以看到，它们只差了一个固定参数，即基准价格，程序后台计算完统一乘上基准价格就好了。 你说为什么基准价格为什么定在1$=50w tokens？那自然是因为最开始基准价格是参考的gpt-3.5-turbo的输入价格0.002$/1k tokens，降价是后来的事情了。 你要问为什么选择倍率体系，不直接使用价格体系，那就得问作者了。
> 
> 每个模型的基准价格会变动吗？还是固定的？可以在哪里查看呢？大佬

基准价格是统一固定的，就是运营设置里的单位美元额度，每个模型根据官方价格调整模型倍率和补全倍率，就可以和官方价格保持同步。

**Comment by Ekko1048** [comment]
> 是运营设置里的单位美元额度，

我这里后台运营设置里的单位美元额度是500000，那么基准价格是多少呢？

**Comment by QAbot-zh** [comment]
> > 是运营设置里的单位美元额度，
> 
> 我这里后台运营设置里的单位美元额度是500000，那么基准价格是多少呢？

单位美元额度 50w，不就是前面说的 0.002$/1k tokens 吗?

**Comment by QAbot-zh** [comment]
> > 是运营设置里的单位美元额度，
> 
> 我这里后台运营设置里的单位美元额度是500000，那么基准价格是多少呢？

单位美元额度 50w，不就是前面说的 0.002$/1k tokens 吗?

**Comment by jjaychen1e** [comment]
@QAbot-zh 您好。请问 one-api 的模型倍率是在代码中固定的还是会根据官方价格实时更新的？需要在官方价格更新后等仓库更新重新部署新版吗，还是会自动更新？

**Comment by QAbot-zh** [comment]
> @QAbot-zh 您好。请问 one-api 的模型倍率是在代码中固定的还是会根据官方价格实时更新的？需要在官方价格更新后等仓库更新重新部署新版吗，还是会自动更新？

计算公式是固定的，但是模型倍率设置是开放的，官方价格如果有更新但是仓库还没有及时跟踪，可以自行通过模型倍率和补全倍率进行价格的对齐
![image](https://github.com/songquanpeng/one-api/assets/40236765/e3f8c5e8-9ba9-4006-b122-1d0d2f3f1260)

**Comment by Ekko1048** [comment]
> > @QAbot-zh 您好。请问 one-api 的模型倍率是在代码中固定的还是会根据官方价格实时更新的？需要在官方价格更新后等仓库更新重新部署新版吗，还是会自动更新？
> 
> 计算公式是固定的，但是模型倍率设置是开放的，官方价格如果有更新但是仓库还没有及时跟踪，可以自行通过模型倍率和补全倍率进行价格的对齐 ![image](https://private-user-images.githubusercontent.com/40236765/306546662-e3f8c5e8-9ba9-4006-b122-1d0d2f3f1260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTUzNjMsIm5iZiI6MTcwODY1NTA2MywicGF0aCI6Ii80MDIzNjc2NS8zMDY1NDY2NjItZTNmOGM1ZTgtOWJhOS00MDA2LWIxMjItMWQwZDJmM2YxMjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyMjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMWIyYjE1ZjYzMmJhNzg3ZWYzZWYxZGQ1ZDZmZjExZjgyNTc2ZGQ4MTA1MDdkZjdkYjc1Y2VlYmM1OGYwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kkiJT1F3Iglx341GvPt6QsJ7MaaF6h15wPdUi4jFilU)

怎么你会有个补全倍率的输入框

**Comment by QAbot-zh** [comment]
> 怎么你会有个补全倍率的输入框

因为我是新版本

**Comment by shown1985** [comment]
搭车问一下，国内模型相比较GPT的倍率是按照什么汇率算出来的？

**Comment by QAbot-zh** [comment]
> 搭车问一下，国内模型相比较GPT的倍率是按照什么汇率算出来的？

1:7 汇率，也就是国内模型的基准价格是 0.014 ￥/ 1k tokens
![image](https://github.com/songquanpeng/one-api/assets/40236765/18b4376c-6937-463c-98c2-62b22cc9cb2e)

**Comment by ludevica** [comment]
用了2年了，今天才关注到这个。请问如果补全倍率没有设置，默认计算逻辑是什么？

**Comment by QAbot-zh** [comment]
> 用了2年了，今天才关注到这个。请问如果补全倍率没有设置，默认计算逻辑是什么？

默认规则内的按预设计算，不可更改，即程序内规定死了；没有被规则匹配上也没有设置的，默认为1。

https://github.com/songquanpeng/one-api/blob/8df4a2670b98266bd287c698243fff327d9748cf/relay/billing/ratio/model.go#L725C6-L725C24

**Comment by wujohns** [comment]
这个设计是最脑残的设计
