### ISSUE TITLE
自动重试遇到返回包含404的html代码

### ISSUE THREAD

**Issue by Cherry291** [songquanpeng/one-api#769]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我设置了重试次数10，然后当遇到key不可用自动重试的时候，他返回的了包含404的html代码而不是返回的具体问题答案
**复现步骤**
连续多次提问测试，触发单渠道上游饱和，触发透明自动重试
**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/71474660/0c62109d-789d-4366-847d-cb73480f8231)

如果没有的话，请删除此节。

**Comment by Cherry291** [comment]
我请求的地址是https://xxxx/api/openai/v1/chat/completions，自动重试的地址是https://xxxx/v1/chat/completions?retry=4
会不会是因为两个地址不一样呢，群里有人说是nextweb和one-api不兼容，需要改nextweb或者one-api的代码，上面是自动重试的会回复内容，请问怎么解决呢？

**Comment by songquanpeng** [comment]
自动重试的实现会更新，改成客户端无感的，相关 PR：https://github.com/songquanpeng/one-api/pull/770

这个问题之后会处理的

**Comment by songquanpeng** [comment]
已经解决了，现在是内置重试了
