### ISSUE TITLE
用户消耗量统计

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#77]
为用户提供个人消耗量统计显示，显示他们的总消费和当前余额。
管理后台可以查看所有用户的消费和余额情况，全平台的总消费显示。
可以对用户的消费情况进行排序、以便管理员更好地了解用户的消费行为。

**Comment by songquanpeng** [comment]
已支持个人消耗量统计。

**Comment by mrhaoji** [comment]
已增加对用户消费情况进行排序 #1178
