### ISSUE TITLE
使用新版本oneapi 4v模型 报错

### ISSUE THREAD

**Issue by a37836323** [songquanpeng/one-api#772]
响应:
{"error":{"message":"fail to decode image config(webp): webpGetInfo: bad arguments, data is empty (request id: 20231202161502960225813vjRxCoOr)","type":"one_api_error","param":"","code":"count_token_messages_failed"}}

模型名称 gpt-4-vision-preview

请求msg数据
array(1) {
  [0]=>
  array(2) {
    ["role"]=>
    string(4) "user"
    ["content"]=>
    array(2) {
      [0]=>
      array(2) {
        ["type"]=>
        string(4) "text"
        ["text"]=>
        string(15) "这是什么?

"
      }
      [1]=>
      array(2) {
        ["type"]=>
        string(9) "image_url"
        ["image_url"]=>
        array(1) {
          ["url"]=>
          string(115) "https://baga-1317914855.cos.ap-chongqing.myqcloud.com/images/202312/02/xxxxx.jpg"
        }
      }
    }
  }
}

**Comment by sotowang** [comment]
+1  部分图片使用4v模型报错,举例:https://i.imgs.ovh/2023/12/08/fHZUK.jpeg

**Comment by songquanpeng** [comment]
这个报错是不是 One API 的报错哈，当前版本没有解析图片
