### ISSUE TITLE
代码重构，解耦relay，模块化AI供应商

### ISSUE THREAD

**Issue by MartialBE** [songquanpeng/one-api#779]
**功能描述**

由于之前该项目只是用来中转聊天使用，所以代码通过一个 [relay-text.go](https://github.com/songquanpeng/one-api/blob/main/controller/relay-text.go)即可满足需求。

但是随着现在越来越多的 AI 厂家，`relayTextHelper` 函数规模越来越庞大，维护起来很不方便，并且各个AI厂家都开始支持音频、图片的生成功能，现有的代码维护起来我觉得很吃力。

所以我觉得可以进行一次重构，这样能更好的进行代码维护。

这是我重构的代码：

https://github.com/MartialBE/one-api/tree/new  

1. 拆分relay， 针对每个接口一个控制器。
2. 每个AI厂家封装成 供应商插件模块， 实现工厂封装，每个供应商只要写有的功能即可。
3. 独立计费模块，只要实现token计算函数即可。
4. 由于模块化的实现，现在 测试通道 可以直接复用 chat 接口函数，基本所有的渠道都可以进行测试。

代码还不够完善，因为只是个人使用，很多供应商我没有，无法进行测试。
由于精力有限，看是否可以新建一个分支，一起完善？

**Comment by waltcow** [comment]
感觉这个维护成本好很多
