### ISSUE TITLE
Azure 的 dalle3  返回404 

### ISSUE THREAD

**Issue by henryhu55** [songquanpeng/one-api#781]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
最新版本上部署的，v0.5.9-alpha.2
请求dalle-3 返回404

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/128961310/2a34259c-186b-43b4-bf6b-4971360dce53)

**Comment by songquanpeng** [comment]
这个报错不是 One API 的报错，检查一下你的 Azure 账号支不支持这个模型

**Comment by henryhu55** [comment]
> 这个报错不是 One API 的报错，检查一下你的 Azure 账号支不支持这个模型

我刚又对比测试了一下，我知道问题原因了，不是azure账号的问题，是我的默认版本填错了应该是2023-12-01-preview，如果填2023-07-01-preview，或者不填则会报404的错误。

**Comment by henryhu55** [comment]
默认API版本要对应上，和gpt那边的不一致要注意。

**Comment by henryhu55** [comment]
不过还有个问题，就是当填错的时候，没有返回结果，额度还是扣了的

**Comment by songquanpeng** [comment]
这个请新开 issue 哈

**Comment by henryhu55** [comment]
好的
