### ISSUE TITLE
Bug can't deploy zeabur

### ISSUE THREAD

**Issue by H0llyW00dzZ** [songquanpeng/one-api#786]
anyone here know how to fix this a issue ?

![image](https://github.com/songquanpeng/one-api/assets/17626300/4cb19fb1-820f-47a4-aff4-7e71369aa4c2)

**Comment by songquanpeng** [comment]
I need a full screenshot of your error message.

**Comment by H0llyW00dzZ** [comment]
> I need a full screenshot of your error message.

it was fixed I forgot to close this issue
