### ISSUE TITLE
SQL表单独拆分

### ISSUE THREAD

**Issue by kenneth-bro** [songquanpeng/one-api#789]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
能否把系统用到的表单独拆分，不自动创建，同时增加 one_api_表名前缀

**应用场景**
企业上应用可能没那么多库，会有和其他应用用同个库的情况，所以从表名上区分

**Comment by songquanpeng** [comment]
共用数据库吗？小众需求可能需要先自行二开了

**Comment by kenneth-bro** [comment]
> 共用数据库吗？小众需求可能需要先自行二开了

能否把用到的表新建一个.sql文件？
