### ISSUE TITLE
API Key 余额信息查询

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#79]
目前通过接口可以查询到部分Key信息，而无需对话请求。
可以在后台对Key测试后记录并显示当前查询到的信息。

以下是从代码中提取出的OpenAI官方API接口：

`https://api.openai.com/dashboard/billing/subscription`
用于获取OpenAI订阅信息的API接口。调用方式和官方其他API一样，该接口需要在请求的Authorization标头中包含密钥。

`https://api.openai.com/dashboard/billing/usage`
用于获取OpenAI使用情况的API接口。该接口也需要在请求的Authorization标头中包含密钥。
此外，还需要在URL的查询参数中提供起始日期和结束日期，以指定要获取的使用情况的时间范围（例如最近两个月）
```
formatDate := func(d time.Time) string {
			return fmt.Sprintf("%d-%02d-%02d", d.Year(), d.Month(), d.Day())
		}
		startDate := formatDate(time.Now().AddDate(0, -1, 0))
		endDate := formatDate(time.Now().AddDate(0, 1, 0))
		usageURL := fmt.Sprintf("https://api.openai.com/dashboard/billing/usage?start_date=%s&end_date=%s", startDate, endDate)
```

![image](https://github.com/songquanpeng/one-api/assets/11790369/e3e52011-ed0b-4789-ba35-3a7ade8cb0d5)

**Comment by Aiayw** [comment]
是需要绑卡用户的响应内容么？

`{
  "object": "billing_subscription",
  "has_payment_method": true,
  "canceled": false,
  "canceled_at": null,
  "delinquent": null,
  "access_until": 1685577600,
  "soft_limit": 300000,
  "hard_limit": 333333,
  "system_hard_limit": 50000000,
  "soft_limit_usd": 18.0,
  "hard_limit_usd": 19.99998,
  "system_hard_limit_usd": 3000.0,
  "plan": {
    "title": "Pay-as-you-go",
    "id": "payg"
  },
  "account_name": "OO",
  "po_number": null,
  "billing_email": null,
  "tax_ids": null,
  "billing_address": {
    "city": "Montana",
    "line1": "1234  Meadow Drive",
    "line2": null,
    "state": "MT",
    "country": "US",
    "postal_code": "59801"
  },
  "business_address": null
}`

**Comment by songquanpeng** [comment]
这几个字段我不太清楚到底干嘛的：
```
  "soft_limit": 300000,
  "hard_limit": 333333,
  "system_hard_limit": 50000000,
  "soft_limit_usd": 18.0,
  "hard_limit_usd": 19.99998,
  "system_hard_limit_usd": 3000.0,
```

**Comment by Aiayw** [comment]
"soft_limit": 这个是OpenAI给的授权额度*100,
  "hard_limit": 这个可能是可以超额一定范围使用,
  "system_hard_limit": 这个应该是目前单账户的付费上限,
  "soft_limit_usd": 这个是自行设定的软限制（当您的组织每月达到此使用量阈值时，将发送通知电子邮件。）
  "hard_limit_usd": 这个是自行设定的硬限制（当您的组织每月达到此使用量阈值时，后续请求将被拒绝。）
  "system_hard_limit_usd": 这个是当前账户可调整的最高额度,

**Comment by songquanpeng** [comment]
Okay，另外这里也有注释可以参考：view-source:https://openai-billing.vercel.app/

**Comment by Aiayw** [comment]
日期查询的结果参数 "total_usage": 12345.9512 这是查询日期范围内使用的额度，值/100就是当前美元消费

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/cb8d0f6c-ecfd-4407-bdaa-dd5b71608972)

这个刷新日期是固定的吗？

**Comment by songquanpeng** [comment]
看来是固定的：
![image](https://github.com/songquanpeng/one-api/assets/39998050/20eaa42d-067a-4daa-968a-6a04a0140c75)

**Comment by songquanpeng** [comment]
已实现。
