### ISSUE TITLE
model ratio not found: chatglm3

### ISSUE THREAD

**Issue by swingsun888** [songquanpeng/one-api#790]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
后台日志中有很多model ratio not found: chatglm3，请问这个是什么问题
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
这个是你的模型倍率没更新哈，加一下就好了：
![image](https://github.com/songquanpeng/one-api/assets/39998050/c62f2977-8885-4ad3-b0e8-1a1ba81b4471)

**Comment by beijingtl** [comment]
在设置完自定义渠道后，需要在“设置”-“运营设置”中，新增自定义渠道模型的倍率。

**Comment by ipv6next** [comment]
我也遇到类似的问题，详情见下图。在联网运行时，一切正常。断网离线，就报错model ratio not found: m3e
![微信图片_20240423094020](https://github.com/songquanpeng/one-api/assets/135030220/135d6bb0-3608-437b-afa6-548600130bee)
