### ISSUE TITLE
希望能加一个禁止用户自己删除个人账户

### ISSUE THREAD

**Issue by PasiKami** [songquanpeng/one-api#791]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
前端后端禁止用户自己删除个人账户

**应用场景**
如果开启新用户注册和邀请奖励, 用户删除账号再重新注册会再次获得奖励
也就是说, 现在可以重复注册删除账号, 来让邀请者获得无限奖励

**Comment by woodchen-ink** [comment]
自己把删除账户按钮给删了就好了😂

**Comment by PasiKami** [comment]
> 自己把删除账户按钮给删了就好了😂

没用, 直接发送请求还是能删

**Comment by woodchen-ink** [comment]
> > 自己把删除账户按钮给删了就好了😂
> 
> 没用, 直接发送请求还是能删

nginx禁止请求

**Comment by songquanpeng** [comment]
该问题之后会解决，谢谢反馈，workaround：
```
server {
    listen 80;
    server_name your_server_name;

    location /api/user/self {
        if ($request_method = DELETE ) {
            return 405;
        }

        # 其他配置...
    }

    # 其他 server 配置...
}

```

**Comment by songquanpeng** [comment]
现在所有的删除都是软删除了
