### ISSUE TITLE
使用root无法登录，提示“管理员关闭密码登录”，如何修改？

### ISSUE THREAD

**Issue by leoncool23** [songquanpeng/one-api#796]
通过宝塔 docker部署的oneapi，运行良好，浏览器一直有缓存，一直可以登录。
今天上去发现无法登录后台了，想想可能是之前设置不允许外部用户注册登录的原因（？不确定），请问如何修改补救？

**Comment by leoncool23** [comment]
已经解决 更改db

**Comment by songquanpeng** [comment]
是的，现在禁用密码登录时是有提醒的

**Comment by tiefengsun** [comment]
> 已经解决 更改db

如何修改数据库？我也遇到的相同的问题。
