### ISSUE TITLE
阿里云同义千问 plugin支持

### ISSUE THREAD

**Issue by assassinliujie** [songquanpeng/one-api#797]
但是oneapi没有提供相应支持，能否适配，应该是只需要多传入一个允许插件列表参数即可
![536d2a728e6eac8eace1b6cba311b292](https://github.com/songquanpeng/one-api/assets/68693675/ae040212-9726-4892-80cf-e8fcaca6ef36)
功能都ti挺有用的，除了chatgpt plus应该没别的模型有这个官方支持了

**Comment by assassinliujie** [comment]
https://help.aliyun.com/zh/dashscope/developer-reference/invoke-model-plugins

**Comment by assassinliujie** [comment]
只需要加一个请求头就好了，但是我不会前端没法做到前端输入支持插件列表，所以没法commit然后合并到docker，请问作者可以增加一下这个可选功能吗
curl -v --location --request POST 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation' \
--header 'Authorization: Bearer <your-dashscope-api-key>' \
--header 'Content-Type: application/json' \
--header 'X-DashScope-Plugin: {"ocr":{}}' \
--data-raw '{
  "model": "qwen-plus",
  "input": {
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "识别一下这个图片上的文字：https://dashscope.oss-cn-beijing.aliyuncs.com/samples/plugin/20231124161643.jpg"
      }
    ]
  },
  "parameters": {
    "result_format": "message",
    "seed": 42
  }
}'
添加X-dashscope-plugin请求头就好

**Comment by assassinliujie** [comment]
我弄了个demo，只用添加一行请求头，就能正常得到结果了
![image](https://github.com/songquanpeng/one-api/assets/68693675/8fe36cd7-7009-41a9-a0db-872af1aea72d)

**Comment by songquanpeng** [comment]
已支持
