### ISSUE TITLE
调用后返回 tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ait666** [songquanpeng/one-api#8]
Post "https://api.openai-asia.com/v1/chat/completions": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by songquanpeng** [comment]
Docker 镜像的证书问题，启动时有设置`-v /etc/ssl/certs:/etc/ssl/certs:ro`吗？

**Comment by ait666** [comment]
启动的时候按照教程执行  docker run -d --restart always -p 3000:3000 -v /home/ubuntu/data/one-api:/data -v /etc/ssl/certs:/etc/ssl/certs:ro justsong/one-api

**Comment by songquanpeng** [comment]
宿主机执行 `curl https://api.openai-asia.com/v1/chat/completions` 会报证书错误吗？

**Comment by ait666** [comment]
[root@ecs-2igyL one-api]# curl https://api.openai-asia.com/v1/chat/completions
404 page not found

**Comment by ait666** [comment]
[root@ecs-2igyL one-api]# curl https://openai.api2d.net/v1/chat/completions
{"object":"error","message":"No model in args","code":40302}[root@ecs-2igyL one-api]#

**Comment by ait666** [comment]
d[root@ecs-2igyL one-api]# curl https://api.openai-asia.com/v1/chat/completions
404 page not found

**Comment by songquanpeng** [comment]
这有点奇怪了，请问系统的版本：`uname -ra` 以及 `/etc/ssl/certs` 目录下有内容吗？

**Comment by ait666** [comment]
[root@ecs-2igyL one-api]# uname -ra
Linux ecs-2igyL 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


[root@ecs-2igyL one-api]# cd /etc/ssl/certs
[root@ecs-2igyL certs]# ls
ca-bundle.crt  ca-bundle.trust.crt  make-dummy-cert  Makefile  renew-dummy-cert
[root@ecs-2igyL certs]#

**Comment by songquanpeng** [comment]
好的，明天我再调查一下，感谢反馈～



---Original---
From: ***@***.***&gt;
Sent at: 2023年4月25日(Tue) Early Morning0:45
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 调用后返回 tls: failed to verify certificate: x509: certificate signed by unknown authority (Issue #8)




 
***@***.*** one-api]# uname -ra
 Linux ecs-2igyL 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 
***@***.*** one-api]# cd /etc/ssl/certs
 ***@***.*** certs]# ls
 ca-bundle.crt  ca-bundle.trust.crt  make-dummy-cert  Makefile  renew-dummy-cert
 ***@***.*** certs]#

**Comment by songquanpeng** [comment]
可以测试一下去掉 `-v /etc/ssl/certs:/etc/ssl/certs:ro` 的情况吗？镜像打包时实际上已经有打包证书，我怀疑是宿主机的证书与 Alpine 不匹配。

**Comment by songquanpeng** [comment]
我自己测试了一下，去掉 `-v /etc/ssl/certs:/etc/ssl/certs:ro` 后我这里依然是可以的，说明镜像内打包好的证书已经足够了。

**Comment by ait666** [comment]
去掉  -v /etc/ssl/certs:/etc/ssl/certs:ro 后可以使用了  感谢作者

**Comment by songquanpeng** [comment]
也感谢你的测试和反馈，README 已更新。
