### ISSUE TITLE
限制后端和前端的昵称和用户名长度

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#80]
长度太长会出现显示问题，可以做显示长度限制（超过多少字后的显示为...）或直接硬限制昵称和用户名长度。

![image](https://github.com/songquanpeng/one-api/assets/11790369/17c79817-5d6f-4f00-b103-decb68d1e8c1)

**Comment by songquanpeng** [comment]
我记得有做限制哈，但是看来没生效：
![image](https://github.com/songquanpeng/one-api/assets/39998050/79ff0624-5995-4e1d-a6a1-1e8a361dde5c)

今天修复。

**Comment by songquanpeng** [comment]
我检查了，用户自己是没办法改到这么长的，只有管理员在后台可以搞到这么长，我加一下管理员的限制。

**Comment by Aiayw** [comment]
但是后台显示例如 “一个热爱数码的男孩” 就会显示异常，是否将显示字数限定一下

**Comment by Aiayw** [comment]
那记得昵称 用户名 邮箱都要加上长度限制

**Comment by songquanpeng** [comment]
显示名称直接不显示了，目前这个没啥用。

邮箱这个确实，谢谢提醒。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月16日(星期二) 晚上8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [songquanpeng/one-api] 限制后端和前端的昵称和用户名长度 (Issue #80)





 
那记得昵称 用户名 邮箱都要加上长度限制

**Comment by songquanpeng** [comment]
算了，还是留着显示名称吧。

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/d1750d4e-8a72-4ea0-bfc5-2b37b8d581ca)

鼠标悬停用户名可以看显示名称。

已经做了长度限制，但是中文字符的渲染长度比较大，如果限制设置太小会误伤纯字母账户名。
