### ISSUE TITLE
通义千问新模型

### ISSUE THREAD

**Issue by woodchen-ink** [songquanpeng/one-api#802]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
描述：https://help.aliyun.com/zh/dashscope/developer-reference/api-details?disableWebsiteRedirect=true
计费：https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-thousand-questions-metering-and-billing?spm=a2c4g.11186623.0.i1
![image](https://github.com/songquanpeng/one-api/assets/95951386/6d5f731e-b6ae-43ef-9a92-2349fbe2041e)

**应用场景**

**Comment by austingg** [comment]
want more qwen model ,and Qwen-vl-plus

**Comment by songquanpeng** [comment]
已经处理
