### ISSUE TITLE
渠道优先级问题

### ISSUE THREAD

**Issue by popdo** [songquanpeng/one-api#803]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

高优先级的渠道出错后不会自动请求低优先级的渠道，而是直接返回了错误。

**复现步骤**

主要渠道优先级设置为1
备用渠道优先级设置为0

我设置了渠道出错后不自动禁用，在这种情况下不会走低优先级渠道，直接抛出了错误。

是否必须设置为自动禁用，才会走低优先级。

**Comment by ye4293** [comment]
是的，必须要高优先级的渠道自动禁用后，低优先级的渠道才会进行调用。不是抛出错误就切换
