### ISSUE TITLE
申请接入「月之暗面」API

### ISSUE THREAD

**Issue by zhangdszq** [songquanpeng/one-api#804]
**功能描述**

月之暗面是红杉投资的清华系大模型，可以提供 API KEY~

**Comment by zhangdszq** [comment]
https://moonshot.feishu.cn/docx/RnkWdeFo8oQabzxYFVwcNg1Mn9g

文档地址

**Comment by songquanpeng** [comment]
好的，请加群私聊我谢谢

**Comment by zhangdszq** [comment]
> 好的，请加群私聊我谢谢

QQ 上已经私聊你了, 辛苦关注~

**Comment by cnbeining** [comment]
模型格式和OpenAI一样 直接设成上游装作代理站即可？

**Comment by songquanpeng** [comment]
已经支持
