### ISSUE TITLE
可以用openai账号的 session 登入吗？

### ISSUE THREAD

**Issue by vbskycn** [songquanpeng/one-api#809]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
目前使用key会有限速和限额，可否使用  账号的 session 登入，这样不限速不限额那就帮好了，pandora项目可以用session 登入或是账号登入，代理转发，但是pandora作者又限制了，只能用他的服务器中转，数量也受他的服务器限制

**应用场景**
真正意义上的代理了

**Comment by takestairs** [comment]
侧重点不同，感觉没什么必要。你要用pandora就自己搭一个proxy模式，然后自己弄个pandora的sharetoken或是pooltoken，再接入one api。

**Comment by takestairs** [comment]
不过借你这条issue，我倒想提一下，放开api key的字段长度限制，多长的key都可以。这样更好集成三方的open ai代理。集成pandora也就更方便，直接拿session token当key接入one就ok。

**Comment by vbskycn** [comment]
在pandora转一圈不但受作者限制，还不稳定，根本就不需要pandora代理啊，只要one支持session登入，那就一切ok
