### ISSUE TITLE
POST /v1/images/generations  缺少参数n就请求报错400

### ISSUE THREAD

**Issue by ccyuvin** [songquanpeng/one-api#811]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
v0.5.9 版本

curl --location --request POST --X POST 'https://xxxxxxxx/v1/images/generations' \
--header 'Authorization: Bearer sk-xxxxxxxxxxx' \
--header 'Content-Type: application/json' \
--data '{
	"prompt": "cat",
	"response_format": "b64_json",
	"model": "dall-e-3"
}'

返回结果
{
	"error": {
		"message": "invalid value of n (request id: 20231212101636591765467wdxCKhPR)",
		"type": "one_api_error",
		"param": "",
		"code": "n_not_within_range"
	}
}

我确认渠道中的KEY能正常使用dall-e-3，并且将域名和KEY更换为官网api.openai.com后，用同样的请求测试过是正常返回的。

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/85599321/3f4bd7e2-22c4-4a6d-8239-68987d2aaec2)

补充：
![image](https://github.com/songquanpeng/one-api/assets/85599321/96df670c-786b-4e08-88b3-d020cd323c30)

请求参数参数加上n就正常了，查阅官网文档，n是可选项，应该要可以不传。

**Comment by ye4293** [comment]
差一个参数n 就是图像的数量，要设置为1

**Comment by ye4293** [comment]
这是我用oneapi测试的结果图一是有参数n，图二是没有。你是加了n后还是报错400吗？
![c01f94e2e2704cc79b5ebeea8822eaf](https://github.com/songquanpeng/one-api/assets/137054651/05fd09e6-bb30-400f-95a9-008cae1abd3e)
![759a65747fcd567bf0f5992fcc6c4bb](https://github.com/songquanpeng/one-api/assets/137054651/0af2e797-b44d-4357-b100-2b50230c7b11)

**Comment by ye4293** [comment]
官网的可以好像是默认了等于1.按道理加上n后是没有问题的，考虑下是不是网络之类的问题
![e2b82265933e1a2b8d25bed6724d989](https://github.com/songquanpeng/one-api/assets/137054651/a2360e54-4bbe-4f8d-a147-cea51c6738db)
