### ISSUE TITLE
使用PandoraNext的web2api报错

### ISSUE THREAD

**Issue by bfchengnuo** [songquanpeng/one-api#813]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用自定义渠道设置 PandoraNext 的 key 和 Base URL，测试会报错：
``` json
{
    "message": "type , code \u003cnil\u003e, message 补全 tokens 非预期返回 0",
    "success": false,
    "time": 1.481
}
```
使用 ChatGpt Next Web 直接调用 PandoraNext 是正常的；
换成 one-api 的 key 的方式调用 PandoraNext 渠道是失败的，提示为：
``` json
{
  "error": {
    "message": "Incorrect API key provided: fk--61GT**********************************7kGQ. You can find your API key at https://platform.openai.com/account/api-keys. (request id: 20231213004h)",
    "type": "invalid_request_error",
    "param": "",
    "code": "invalid_api_key"
  }
}
```

**复现步骤**
任一 PandoraNext web2api key 测试

**预期结果**
渠道使用 PandoraNext web2api 正常调用。

**Comment by ceozero** [comment]
这个问题一直有，我现在是直接用OPENAI的渠道，然后下面的代理用PandoraNext的地址，测试会显示非预期返回0 。但是实际是可以使用的。

**Comment by bfchengnuo** [comment]
使用 OpenAI 渠道实际测试确实可用

**Comment by ceozero** [comment]
咋关了.../" 非预期返回 0" 还是可以修复一下不是。
