### ISSUE TITLE
API接口请求不检查SSL证书

### ISSUE THREAD

**Issue by fengjisheng** [songquanpeng/one-api#816]
**例行检查**
智普请求报错提示: 2025 s!30n.agora nagaes v3/mode-ap/chatglm turbo/sse-nvoke" ts: faled to vertly certficate. x509: certfcate signed by unknown authorty 

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√ ] 我已确认我已升级到最新版本
+ [√ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [√ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [√ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
智普SSL证书过期或出问题, 导致请求出错, CURL请求的时候应该忽略检查SSL, 我测试过, 跳过SSL检查可以正常请求. 

**复现步骤**
CURL请求不检查SSL证书

**Comment by songquanpeng** [comment]
那这是智谱的问题哈，不能因噎废食，如果智谱这种情况很常出现的话，会考虑的
