### ISSUE TITLE
错误提示按上游返回的信息原样展示

### ISSUE THREAD

**Issue by SailFlorve** [songquanpeng/one-api#817]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
如果非官方渠道上游返回错误，例如500，则One API只会显示
Error: Error: 500 (request id: 20231213161230862520860XuuLv51b)
但上游会附加一个Json用于提示错误内容，能否显示出
**应用场景**

**Comment by songquanpeng** [comment]
你的上游的报错具体是什么格式？不能原样展示，因为 One API 保证错误信息也是 OpenAI 格式的。

我刚刚做了处理，兼容了大部分错误信息，如果依然不行，提供在你的场景下的错误信息的格式。
