### ISSUE TITLE
请求自定义 key 生成格式

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/one-api#82]
比如自定义前缀、位数 、后缀。

**Comment by songquanpeng** [comment]
别的 APP 还检查位数吗？这个就不好搞了

**Comment by songquanpeng** [comment]
自定义前缀意义不大哈，如果是强制使用 OpenAI 的 key，前缀肯定固定为 sk-

**Comment by aiastia** [comment]
有部分有 > 别的 APP 还检查位数吗？这个就不好搞了

**Comment by songquanpeng** [comment]
现在支持 sk- 前缀了，系统在验证 token 的时候会自动去除该 token。

自定义格式目前不考虑哈，改动太大而受众太少。

**Comment by imldy** [comment]
key由`-`分割，也许可以允许`-`之前为任意字符

后端token认证代码：
https://github.com/songquanpeng/one-api/blob/6215d2e71c6bb904865514c49ac9759f3bba4458/middleware/auth.go#L87-L91

前端复制token代码：
https://github.com/songquanpeng/one-api/blob/6215d2e71c6bb904865514c49ac9759f3bba4458/web/src/components/TokensTable.js#L242
