### ISSUE TITLE
讯飞星火V3偶线Panic detected index out of range

### ISSUE THREAD

**Issue by luomo-pro** [songquanpeng/one-api#820]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用讯飞星火V3(添加渠道时填写的接口地址版本是v3.1)，发现会偶线这样的报错：
 Panic detected, error: runtime error: index out of range [0] with length 0. Please submit a issue here: https://github.com/songquanpeng/one-api
查看日志看到如下信息：
[SYS] 2023/12/14 - 16:57:49 | error reading stream response: websocket: close 1000 (normal): close this ws conn 
[SYS] 2023/12/14 - 16:57:49 | panic detected: runtime error: index out of range [0] with length 0 
除此之外并没有更多的日志信息了，我查看的是数据目录里的日志文件。
这个问题并不是百分百重现的，偶尔请求就会有，所以不太找得出是什么原因。
也不知道是否是遇到了QPS限制，如果确认是的话，那能否直接提示QPS限制？
**复现步骤**
直接正常发起请求
**预期结果**
正常返回结果

**Comment by songquanpeng** [comment]
确定是最新版本吗？

**Comment by songquanpeng** [comment]
有一个地方没有做校验，已经处理
