### ISSUE TITLE
为何功能上点击令牌复制，并不做成直接复制到粘贴板，而是需要人工再次复制

### ISSUE THREAD

**Issue by leoterry-ulrica** [songquanpeng/one-api#827]
如题所示：
![1702714240162](https://github.com/songquanpeng/one-api/assets/18339429/e27fda18-1aa1-4743-ba5a-60b784e3af70)

![T@M$7`AZY74N_9 _EFG(ZLR](https://github.com/songquanpeng/one-api/assets/18339429/37e37615-7019-445b-944a-566719fbf7c1)

**Comment by takestairs** [comment]
开启https

**Comment by leoterry-ulrica** [comment]
> 开启https

只有在https协议下才行吗？

**Comment by songquanpeng** [comment]
因为 http 协议下浏览器不让调用写入剪贴板的 api

**Comment by leoterry-ulrica** [comment]
> 因为 http 协议下浏览器不让调用写入剪贴板的 api

收到
