### ISSUE TITLE
Sir Please Add English Language

### ISSUE THREAD

**Issue by Niansuh** [songquanpeng/one-api#828]
Sir Please Add English Language

Sit I like your One API

**Comment by songquanpeng** [comment]
You can use this docker image: `justsong/one-api-en`.

**Comment by Niansuh** [comment]
give me full dockert file like this









<html>
<body>

FROM justsong/one-api-en:main
--
  | EXPOSE 3000
  | ENV PORT 3000
  | ENV BATCH_UPDATE_ENABLED=true
  | ENV BATCH_UPDATE_INTERVAL=120
  | ENV GLOBAL_WEB_RATE_LIMIT=600
  | ENV GLOBAL_API_RATE_LIMIT=1800
  | WORKDIR /data
  | RUN mkdir /data/logs && chmod 777 /data/logs
  | ENTRYPOINT ["/one-api"]


</body>
</html>

**Comment by Niansuh** [comment]
How to make channels please make a video sir and thanks for one Api english

**Comment by Niansuh** [comment]
reply me
