### ISSUE TITLE
gemini-pro偶线Panic detected index out of range

### ISSUE THREAD

**Issue by luomo-pro** [songquanpeng/one-api#833]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
这问题跟
#820
非常类似，都是一样的报错。
而且我已经升级到了最新的版本：v0.5.10-alpha.4
日志里面的话只能看到这一条信息：
[SYS] 2023/12/17 - 22:57:22 | panic detected: runtime error: index out of range [0] with length 0 
**复现步骤**
就正常发起请求，偶尔就会出现，并不是百分百
**预期结果**
正常返回结果

**Comment by songquanpeng** [comment]
已经修复

**Comment by luomo-pro** [comment]
@songquanpeng
我更新到了最新版，虽然不会报这个错误了，但是，现在会出现返回空内容的情况，也就是json是这样的：
{"id":"chatcmpl-1f5aa84a6a7141e285ca51e220a60f57","object":"chat.completion","created":1702828800,"choices":[{"index":0,"message":{"role":"assistant","content":""},"finish_reason":"stop"}],"usage":{"prompt_tokens":11,"completion_tokens":0,"total_tokens":11}}
我提问的内容就是“你是谁”这三个字。
连续问了两次都返回空内容，问第三次的时候就正常返回了。
查看one-api的日志里面也没有报错，还有正常的输出信息：
[INFO] 2023/12/18 - 00:00:00 | 20231217235957458521930gmsdF0zk | record consume log: userId=1, channelId=8, promptTokens=11, completionTokens=0, modelName=gemini-pro, tokenName=秘钥, quota=1, content=模型倍率 0.01，分组倍率 1.00

**Comment by songquanpeng** [comment]
这个就是Google的问题，我测试也是这样，之后优化一下报错提示，不让用户困惑（如果可以的话，请为此提新issue）

**Comment by luomo-pro** [comment]
ok，我已经提交了个新的issue #835
