### ISSUE TITLE
错误响应能否模拟Openai的响应，将错误输出到消息。

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#84]
根据请求的类型做对应的响应返回。
将错误信息通过模拟消息返回的格式放进content里面。

`{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}
`

**Comment by songquanpeng** [comment]
我感觉这样不好哈，你这样搞，怎么告诉客户端请求失败了呢？

**Comment by songquanpeng** [comment]
没这么好处理，因为要考虑到 stream 模式，我还是感觉直接返回错误消息好一些。

目前返回的错误消息格式和 OpenAI 的保持一致，所以只要客户端对错误进行处理 & 并展示消息，是可以看到具体的报错的。

**Comment by Aiayw** [comment]
好的，收到，感谢大佬。
现有方案如果是模拟官方报错的响应那就是正确的。
