### ISSUE TITLE
缺失健康检查接口

### ISSUE THREAD

**Issue by seven-yu** [songquanpeng/one-api#844]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
健康检查接口
**应用场景**
没有健康检查接口，在K8s 环境部署下，做滚动升级的时候，无法判断服务是否就绪，导致部分请求会失败

**Comment by songquanpeng** [comment]
如 PR 里已经解释了一些，已经有一个 /api/status 接口
