### ISSUE TITLE
用户分组以及渠道分组

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#85]
`可以通过在令牌后面添加渠道 ID 的方式指定使用哪一个渠道处理本次请求
例如：Authorization: Bearer ONE_API_KEY-CHANNEL_ID。 
注意，需要是管理员用户创建的令牌才能指定渠道 ID。`

将这个功能改成给用户增加不同的分组，后台通过分组限制用户可以使用的模型和渠道，用户前端生成令牌的时候根据所在分组的权限进行选择令牌可用模型或不限制。

**Comment by songquanpeng** [comment]
分组功能和指定渠道 ID 的功能不相干哈。

分组功能最近会实现，实现前会先发方案到群里供大家讨论 & 反馈。
#17，#72

**Comment by Aiayw** [comment]
好的👌🏻静候佳音

**Comment by songquanpeng** [comment]
QQ 群哈，你难道不在吗？主页有链接：
https://openai.justsong.cn/

**Comment by songquanpeng** [comment]
目前用户分组打算以添加一个 priority 字段的方式进行实现。
