### ISSUE TITLE
为什么启动整个画面都是白色的？

### ISSUE THREAD

**Issue by loks666** [songquanpeng/one-api#851]
请问下为什么项目在启动第一遍的时候，打开端口整个画面都是白色的，什么都没有，但同时网页的标签是正常加载的，当我再启动一次项目，会提示原有端口已经使用，使用另外一个端口启动后，访问后面启动的端口，才能正常看到页面？

代码先启动后端，然后再执行npm run dev命令，第一次启动的时候是整个白色，启动第二遍换一个端口后，才能看到页面，为什么会这样？

**Comment by loks666** [comment]
本地部署时，出现白屏，重新启动提示端口已被占用，改为3001才正常，非常希望解决这个问题
![@{ )BIWC50I)FRJAKM$YWKN](https://github.com/songquanpeng/one-api/assets/33214035/d88ee95b-e408-47ac-86c9-b9aac8a7f81b)

**Comment by songquanpeng** [comment]
大概率你本地有啥程序占用端口了，One API 是本身是不依赖端口号的具体取值的
