### ISSUE TITLE
使用docker部署之后，调用API到Dify 的有报错（The server is overloaded or not ready yet.）

### ISSUE THREAD

**Issue by Hooke-L** [songquanpeng/one-api#854]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用docker部署之后，调用API到Dify 的有报错（The server is overloaded or not ready yet.）

**相关截图**
![1](https://github.com/songquanpeng/one-api/assets/148961221/7581323f-970c-4168-869f-0c425111567c)

**Comment by songquanpeng** [comment]
不清楚 Dify 是如何测试的，如果能抓包看一下再好不过了

**Comment by Hooke-L** [comment]
Hi，JustSong,


谢谢，这个问题已经解决了。




♂珉♂珉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songquanpeng/one-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月1日(星期一) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [songquanpeng/one-api] 使用docker部署之后，调用API到Dify 的有报错（The server is overloaded or not ready yet.） (Issue #854)





 
不清楚 Dify 是如何测试的，如果能抓包看一下再好不过了

**Comment by songquanpeng** [comment]
好的，如果能说一下是怎么解决的就再好不过了

**Comment by Hooke-L** [comment]
你好，JustSong，


好像是我把one-api的渠道里面的那些OpenAI 或者Azure OpenAI的API放到default组里面就可以了，之前我测试是放到vip或者是svip组，发现是无法使用的，后面我重新部署了一遍dify以及one-api，把它们换到default组就可以正常使用了。


希望对你有所帮助。


♂珉♂珉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songquanpeng/one-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月1日(星期一) 下午5:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [songquanpeng/one-api] 使用docker部署之后，调用API到Dify 的有报错（The server is overloaded or not ready yet.） (Issue #854)





 
好的，如果能说一下是怎么解决的就再好不过了
