### ISSUE TITLE
After setting up what will be the url to access api 

### ISSUE THREAD

**Issue by analogpvt** [songquanpeng/one-api#86]
for openai endpoint is api.openai.com  but for this one what is the endpoint @songquanpeng

**Comment by songquanpeng** [comment]
If you assign a domain for it, it's your domain. For example: ![image](https://github.com/songquanpeng/one-api/assets/39998050/d9defed7-64d5-4de9-a11c-2e398645e7b6)

If not, use domain & port, such as: 127.0.0.1:3000

**Comment by analogpvt** [comment]
also where users data is stored is that in any file or which db used in this

**Comment by songquanpeng** [comment]
It uses SQLite as database by default. If you specify the SQL_DSN environment variable at startup, the program will use the specified database.

**Comment by songquanpeng** [comment]
You can check out the corresponding docs here: https://github.com/songquanpeng/one-api#环境变量 (in Chinese)
