### ISSUE TITLE
关于国产大模型的流式调用的问题。

### ISSUE THREAD

**Issue by taomas** [songquanpeng/one-api#861]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我尝试使用流式调用的方式来调用国产的几个大模型，目前调用的几个国产大模型有：通义千问、文心一言、讯飞星火、智谱AI，分别调用的json格式和流式调用格式，调用接口是v1/chat/completions，目前测试的结果是：
1、json格式调用全都正常
2、stream格式调用，只有通义千问的模型正常调用，文兴一言、讯飞星火还是会返回json格式，不会实现stream效果，智谱AI会调用失败。

**复现步骤**
使用apifox直接请求部署之后的one-api的文本补全接口：https://{one_api_url}/v1/chat/completions，请求头的Accept修改成text/event-stream格式。

Stream调用请求头格式：
![image](https://github.com/songquanpeng/one-api/assets/17002702/0940b32e-7ae5-49f4-ba44-72aa532c8b23)

**预期结果**
应该都和通义千问一样的可以流式返回相关的信息。

**相关截图**

通义千问Stream调用结果：
![image](https://github.com/songquanpeng/one-api/assets/17002702/764f70f8-58a8-4940-a962-1297b56bb999)

文兴一言Stream调用结果：
![image](https://github.com/songquanpeng/one-api/assets/17002702/f1cb9252-b2c5-4348-8ca6-03fbdfc21b5f)

讯飞星火Stream调用结果：
![image](https://github.com/songquanpeng/one-api/assets/17002702/0a6c978d-af5a-4081-9bdd-0195a3a8d505)

智谱AIStream调用结果：
![image](https://github.com/songquanpeng/one-api/assets/17002702/7841280c-642b-4137-9ffa-809e570d83fe)

**Comment by songquanpeng** [comment]
对于 OpenAI 的 API，如果你不显式指定 stream 为 true 本来就不是流式返回的。

**Comment by songquanpeng** [comment]
已经再 PR 里解释过了哈：https://github.com/songquanpeng/one-api/pull/864
