### ISSUE TITLE
项目本地启动白屏

### ISSUE THREAD

**Issue by loks666** [songquanpeng/one-api#863]
自己down下来项目后执行readme文件中的启动命令进行启动，能确定的是配置都是正常的，也没有任何报错
但是访问端口就是整个白色的页面，想问下到底如何能看到正常页面？非常重要！！！
因为我自己打了一个镜像包运行之后，也是一个纯白的页面，这不属于异常范围，但是看过源码之后我发现我不知道如何去看到正常显示的页面，希望群主大大能够指点一二，不胜感激！
![image](https://github.com/songquanpeng/one-api/assets/33214035/ba59eac6-5554-4c1b-870d-9742503aae0b)

**Comment by loks666** [comment]
部署后访问出现空白页面,在文档里，那个issue 404了，目前没有解决方案！

**Comment by loks666** [comment]
fixed

**Comment by zhangbinhui** [comment]
> fixed

请问，后来是怎么解决的？我也碰到了这个问题

**Comment by uhnjk** [comment]
请问，是怎么解决的  我也遇到了相同问题
