### ISSUE TITLE
希望增加对gemini安全审查的参数传入

### ISSUE THREAD

**Issue by kuziTony** [songquanpeng/one-api#866]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
在代码中被注释的
//SafetySettings: []GeminiChatSafetySettings{
		//	{
		//		Category:  "HARM_CATEGORY_HARASSMENT",
		//		Threshold: "BLOCK_ONLY_HIGH",
		//	},
		//	{
		//		Category:  "HARM_CATEGORY_HATE_SPEECH",
		//		Threshold: "BLOCK_ONLY_HIGH",
		//	},
		//	{
		//		Category:  "HARM_CATEGORY_SEXUALLY_EXPLICIT",
		//		Threshold: "BLOCK_ONLY_HIGH",
		//	},
		//	{
		//		Category:  "HARM_CATEGORY_DANGEROUS_CONTENT",
		//		Threshold: "BLOCK_ONLY_HIGH",
		//	},
		//},
是否可以考虑重新加入为  Threshold：BLOCK_NONE
在官方测试接口中默认的的限制会很多，比如输入字符1  会被block掉，因为判定为骚扰信息。
**应用场景**

**Comment by nekomiya-hinata** [comment]
虽然谷歌官方是这样提示的：
**注意 ：调整到较低的安全设置将触发对您的应用进行更深入的审核流程。**

**Comment by songquanpeng** [comment]
是的，所以我打算设置为环境变量，允许用户设置
