### ISSUE TITLE
增加对gemini-pro向量模型models/embedding-001的支持

### ISSUE THREAD

**Issue by qingyanbaby** [songquanpeng/one-api#868]
例行检查

 我已确认目前没有类似 issue
 我已确认我已升级到最新版本
 我已完整查看过项目 README，已确定现有版本无法满足需求
 我理解并愿意跟进此 issue，协助测试和提供反馈
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
功能描述
增加对 gemini-pro向量模型models/embedding-001的支持

应用场景
增加对 gemini-pro向量模型models/embedding-001的支持，向量接口应用还是比较多的

**Comment by songquanpeng** [comment]
会支持，需要时间，希望理解，期待 PR

**Comment by shown1985** [comment]
嗯，支持。也支持作者幸苦劳动，是需要花时间，应该也是要增加EmbeddingConvert方法。如果实在急，就自己动手然后pull request了
