### ISSUE TITLE
增加ollama API支持

### ISSUE THREAD

**Issue by highjim** [songquanpeng/one-api#870]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

ollama 支持很多开源的模型，但是接口和openai的不兼容，希望您这边能支持接入ollama的api

**Comment by songquanpeng** [comment]
对于本地部署的模型的支持是肯定的，但是需要时间，issue 先留着需要时间处理，期待有人 PR：https://github.com/jmorganca/ollama

**Comment by tisfeng** [comment]
ollama 跑本地模型很好用，期待支持。

**Comment by yongman** [comment]
期待。

**Comment by mrhaoji** [comment]
https://ollama.com/blog/openai-compatibility

好像可以躺平了，Ollama 自己兼容 OpenAI 那套了。

**Comment by tisfeng** [comment]
还是希望 one-api 能原生支持 ollama，作为一个单独的渠道，另外管理模型更方便一些。

**Comment by yongman** [comment]
如果兼容了就可以直接接入oneapi了😋

**Comment by songquanpeng** [comment]
已经原生支持

**Comment by katfionn** [comment]
> 已经原生支持

大佬，根据咱们帖子，我找到了一个[教程](https://zhuanlan.zhihu.com/p/678844914)，是和我们帖子相符合的，可以接入了；
但是我根据装的oneapi(基于容器实现的)最新版，却没有OpenAI API的渠道选项，可以分享下您是怎么弄的吗，自定义渠道反复报错

### 报错信息
这是测试渠道时产生的接口报错：
`message: "do request failed: Post \"http://192.168.1.3:11434/api/generate/v1/chat/completions\": dial tcp 192.168.1.3:11434: connect: connection refused"
success: false
time: 0`

### oneapi配置
![image](https://github.com/songquanpeng/one-api/assets/136874302/0c61af23-5726-48eb-9f3f-829daf86550c)

**Comment by ccyyhh2024** [comment]
我遇到同样的问题，搞定了。

base URL 不能用127.0.0.1，应该使用实际ip地址。

否则One-API认为是docker 容器自己。这就是为什么使用curl或者postman在外面调用是可以的。
