### ISSUE TITLE
星火模型设置v3.1无效

### ISSUE THREAD

**Issue by zhang570221322** [songquanpeng/one-api#876]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
星火模型设置v3.1无效，仍需要使用http://xxxx/v1 请求
**复现步骤**
README中的 docker部署
添加
<img width="1132" alt="image" src="https://github.com/songquanpeng/one-api/assets/25928906/4a4f2ae1-0c42-4c8a-b9fd-0f6832132414">

```python
from openai import OpenAI
import os
os.environ["OPENAI_API_KEY"]="xxxxxx"
client = OpenAI()
client.base_url = "http://xxxxxxxxx/v1" # 此处设置v3.1不起作用，设置为v1才有效了
stream = client.chat.completions.create(
    model="SparkDesk",
    messages=[{"role": "user", "content": "你是谁？"}],
    stream=True,
)

for chunk in stream:
    # print(chunk)
    if chunk.choices[0].delta.content is not None:
        print(chunk.choices[0].delta.content, end="")

```
**预期结果**
client.base_url = "http://xxxxxxxxx/v3.1" # 此处设置v3.1不起作用，设置为v1才有效了

**Comment by QAbot-zh** [comment]
不是bug，这就是oneapi的设计，一切端点向openai靠拢，使用时只需要更换model名称就能一套代码复用。
至于讯飞版本，你在设置渠道的时候已经提供了。

**Comment by songquanpeng** [comment]
是的，参照 @QAbot-zh 的解释

**Comment by zhang570221322** [comment]
ok。了解了
