### ISSUE TITLE
支持从服务器同步配置

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#88]
如果有配置Redis环境变量，则将配置数据缓存到Redis。

**Comment by songquanpeng** [comment]
改动过多。

目前打算设置定期从数据库中重新加载配置文件，你赶紧如何？加载频率可以用命令行参数指定。

**Comment by Aiayw** [comment]
可以，其实主要问题就是之前多个服务器配置缓存不同步，只要能解决这个问题，都行的，辛苦大佬。

**Comment by songquanpeng** [comment]
已支持，已推送，详见 README。

**Comment by songquanpeng** [comment]
期待反馈。

**Comment by Aiayw** [comment]
测试了多机部署和主从同步，暂时没发现问题~
很棒！

**Comment by songquanpeng** [comment]
Okay，感谢反馈~
