### ISSUE TITLE
dall-e-3 因账户rate limit 为 0 导致出错，但oneapi记录为成功调用

### ISSUE THREAD

**Issue by kflyfly** [songquanpeng/one-api#881]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本，docker版： v0.5.11-alpha 
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
openai目前关闭了5$ 新用户使用dall-e-3的权限，实现方式是把rate limit=0/min

如果账户调用，就会显示出错，返回报错：
````
- Rate limit exceeded for images per minute in organization org-ToDJZKfhy1BqRrAohva3yiai. Limit: 0/1min. Current: 1/1min. Please visit https://platform.openai.com/docs/guides/rate-limits to learn how to increase your rate limit.

````
**复现步骤**
使用5$ 新用户调用 dall-e-3会出错。报错如上所示。
但此时oneapi记录的数据显示调用成功。并不会切换渠道。
**希望改进**
dall-e-3 希望返回报错类型也改成想gpt3.5或者gpt-4之类的，也就是rate limit=0 失败后，换其他渠道。
 一个渠道调用失败，自动切换到其他可用渠道。

**Comment by QAbot-zh** [comment]
建议从3.5渠道里删除dall-e-3，要不然切换到其他的3.5重试也没用。

**Comment by ye4293** [comment]
3.5目前关闭了dalle3的权限，所以你应该用4的api去请求。

**Comment by songquanpeng** [comment]
确实图像中继这里有问题，我先修了吧，之后中继模块要重构，越来越乱了

**Comment by kflyfly** [comment]
非常感谢回复
