### ISSUE TITLE
【咨询】dall-e-3重定向dall-e-2不起作用，不知道是不是我的问题，求论证。

### ISSUE THREAD

**Issue by taurusduan** [songquanpeng/one-api#884]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
{
  "dall-e-3": "dall-e-2"
}

dall-e-3重定向dall-e-2不起作用，不知道是不是我的问题，求论证。
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by QAbot-zh** [comment]
它们的参数本来就不完全对标，直接重定向肯定会出错，而且以2充3也不道德。
https://cookbook.openai.com/articles/what_is_new_with_dalle_3
![image](https://github.com/songquanpeng/one-api/assets/40236765/1e415ca2-96f3-4b0b-931b-c8f5f0a87fd7)

**Comment by songquanpeng** [comment]
对于参数不兼容的模型，不能重定向
