### ISSUE TITLE
可通过环境变量控制服务是否启动前端

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#89]
例如多服务器部署的话，除了主站节点需要前端访问，其他服务器节点都不需要。
通过环境变量控制如果访问的是非接口页面都跳转到对应的主站链接。
例如主站为：https://openai.justsong.cn  子站点为：https://api1.justsong.cn 、https://api2.justsong.cn
只要访问https://api1.justsong.cn 或 https://api2.justsong.cn 前端页面都重定向到 https://openai.justsong.cn 所对应的页面

设置环境变量：
SITE_TYPE=main 或 subsite //设置站点类型
MAIN_SITE_URL=https://openai.justsong.cn  //如果设置为subsite 需要填写该环境变量
（或者这个在数据库里取？刚好有个服务器地址的参数）

**Comment by songquanpeng** [comment]
感觉意义不大？而且这些 Nginx 就可以做了。

**Comment by Aiayw** [comment]
部署到某些云服务商（例如https://fly.io）的容器平台，不太好设置Nginx

**Comment by songquanpeng** [comment]
Okay

**Comment by songquanpeng** [comment]
只能环境变量哈，数据库中的 URL 也是管理员手动输入的，既然都共享数据库了也导致没办法区分设置。

不过我比较好奇，你的多机部署访问数据库不会卡吗？还是说都放在了一个内网内。

**Comment by songquanpeng** [comment]
我比较好奇业界那种跨区域的分布式部署是怎么搞得。

**Comment by Aiayw** [comment]
其实按现在的做就已经在接近分布式部署了，无非数据再加上主备同步，各个组件和节点分散到多个机器上。
毕竟是单应用项目，也没太复杂。

**Comment by songquanpeng** [comment]
但是这种数据库用一个的话，不会导致某些机器访问数据库延迟比较大吗？

**Comment by Aiayw** [comment]
数据库做在主-从复制，主数据库负责处理所有的写操作，然后将这些更改复制到一个或多个从数据库。
从数据库处理读操作，这样可以分散负载并减少延迟。

**Comment by Aiayw** [comment]
现在还好吧，当需要考虑数据库的问题的时候，用户量应该也很大了，到时候再做优化就行。

**Comment by songquanpeng** [comment]
确实，写操作并不多。

**Comment by songquanpeng** [comment]
讲道理不应该用一个域名解析多个 IP 吗？不然你暴露给用户的 API 端点岂不是有很多个？

**Comment by Aiayw** [comment]
如果单域名很容易被墙，参考机场，子站点的域名随时变化，设置一个主API接口，一堆从API接口。

**Comment by songquanpeng** [comment]
了解了。

**Comment by songquanpeng** [comment]
已支持，已推送，详见 README 的环境变量一节。
