### ISSUE TITLE
连接不上千问api

### ISSUE THREAD

**Issue by ccculing** [songquanpeng/one-api#891]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
连接本地的chatglm3没问题
oneapi是docker部署的
192.168.2.168是我本机的ip
**复现步骤**

**预期结果**
好像大家都能连到千问，是我哪里设置的不对嘛？
**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/103477836/3ed5db3b-eb81-41e5-a385-4d2c78a2b0a6)
![image](https://github.com/songquanpeng/one-api/assets/103477836/c2c0cec1-c863-4c0f-bf67-8ace14f02e37)
![image](https://github.com/songquanpeng/one-api/assets/103477836/13965b60-2325-4996-b3b1-492397921e07)

如果没有的话，请删除此节。

**Comment by ccculing** [comment]
![image](https://github.com/songquanpeng/one-api/assets/103477836/1d517f51-f467-43fd-8e8a-737e2bf9636b)

**Comment by xueshuai0922** [comment]
> ![image](https://private-user-images.githubusercontent.com/103477836/293604963-1d517f51-f467-43fd-8e8a-737e2bf9636b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzA2NTcsIm5iZiI6MTcwOTYzMDM1NywicGF0aCI6Ii8xMDM0Nzc4MzYvMjkzNjA0OTYzLTFkNTE3ZjUxLWY0NjctNDNmZC04ZThhLTczN2UyYmY5NjM2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwOTE5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWI5ZDY4Zjk2NzIzMjA4YjY3ZGE2ZTk0YjM4OTQ2NzA0ZDc2Y2E1YWNmOTU2ZGRiMTE2NTk1Yjk3N2UwZjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kckDzWdkccO1CirX404bXVsLiron24Oek-LzqMO10F8)

意思是修改成基础模型，就可以了吗
