### ISSUE TITLE
最新版，使用dockerfile部署后`version`是空值造成重复消息弹窗。

### ISSUE THREAD

**Issue by popdo** [songquanpeng/one-api#894]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

通过dockerfile部署最新版本后 status这个api读出来的`version`是空值，造成页面切换就无脑的弹出提示

```
新版本可用：，请使用快捷键 Shift + F5 刷新页面
```

```
新版本可用：，请使用快捷键 Shift + F5 刷新页面
```

```
新版本可用：，请使用快捷键 Shift + F5 刷新页面
```

怎么关都关不掉，源码中我把app.js中这个弹窗都注释掉，打包后依然弹出这个提示。

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
周末处理
