### ISSUE TITLE
请求completions接口提示insufficient_user_quota

### ISSUE THREAD

**Issue by bknds** [songquanpeng/one-api#898]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
令牌设置：
额度设置为无限制，过期时间设置为永不过期，现在请求completions接口提示user quota is not enough，已确认openai账户余额充足，使用官方api调用地址也可以成功。
**复现步骤**

**预期结果**
正常调用

**Comment by QAbot-zh** [comment]
截图看看，余额充足不会是指openai送的有保质期的5刀余额吧

**Comment by bknds** [comment]
不是的，现在余额还有600多刀，之前这300多刀就是这些天使用了咱们oneapi消耗的，之前都是正常调用的，突然现在调用就变成user quota is not enough了。













在 2024-01-06 15:16:23，"Q.A.zh" ***@***.***> 写道：

截图看看，余额充足不会是指openai送的有保质期的5刀余额吧

**Comment by shenmadouyaowen** [comment]
需要充值
![image](https://github.com/songquanpeng/one-api/assets/12426724/e0d971f6-5df4-4e77-84b8-ebe4d7f2cef1)

**Comment by bknds** [comment]
> 需要充值 ![image](https://private-user-images.githubusercontent.com/12426724/295755204-e0d971f6-5df4-4e77-84b8-ebe4d7f2cef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDUwMjAsIm5iZiI6MTcwNDk0NDcyMCwicGF0aCI6Ii8xMjQyNjcyNC8yOTU3NTUyMDQtZTBkOTcxZjYtNWRmNC00ZTc3LTg0YjgtZWJlNGQ3ZjJjZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzNDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YmJlZGU5OTdlZjc1Nzc5NjNkODE0NGNjYTMzOWUzZjAxZTU3MmQ2ZjRkMWQ1YmI5MDEwZWJiN2EzYWJmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9hGXA3vKpaJs1g8lAs7lkGkHB54ZmB5JhVPVZQoNGck)

卧槽明白了，可以了，感谢感谢

**Comment by chen198328** [comment]
> 需要充值 ![image](https://private-user-images.githubusercontent.com/12426724/295755204-e0d971f6-5df4-4e77-84b8-ebe4d7f2cef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDY4MDgsIm5iZiI6MTcwNjcwNjUwOCwicGF0aCI6Ii8xMjQyNjcyNC8yOTU3NTUyMDQtZTBkOTcxZjYtNWRmNC00ZTc3LTg0YjgtZWJlNGQ3ZjJjZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YTVmMjhmODc0NjNlZDY5NTFiMDNkOTIzMmVjYTJhMjhhMmQ2Y2NiMzRlOWZhMzk0MWZjMzkwZjQyNTRhNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5PZP9HRbZ_cAbcR2sPutLzojTyDpuuJBcWQg8s1PPmY)

请问如何充值呢？

**Comment by bknds** [comment]
兑换里添加新的兑换码，然后拿着新的兑换码在充值里给自己充值

---- 回复的原邮件 ----
| 发件人 | Row ***@***.***> |
| 发送日期 | 2024年01月31日 21:10 |
| 收件人 | songquanpeng/one-api ***@***.***> |
| 抄送人 | Bknds ***@***.***>,
State ***@***.***> |
| 主题 | Re: [songquanpeng/one-api] 请求completions接口提示insufficient_user_quota (Issue #898) |

需要充值

卧槽明白了，可以了，感谢感谢

怎么充值的，我也遇到相同的问题了

**Comment by QAbot-zh** [comment]
> 兑换里添加新的兑换码，然后拿着新的兑换码在充值里给自己充值
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Row ***@***.***> | | 发送日期 | 2024年01月31日 21:10 | | 收件人 | songquanpeng/one-api ***@***.***> | | 抄送人 | Bknds ***@***.***>, State ***@***.***> | | 主题 | Re: [songquanpeng/one-api] 请求completions接口提示insufficient_user_quota (Issue #898) | 需要充值 卧槽明白了，可以了，感谢感谢 怎么充值的，我也遇到相同的问题了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

直接进“用户”里给root加余额更快哈哈

**Comment by bknds** [comment]
我以后也这样试试

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月31日 22:34 |
| 收件人 | songquanpeng/one-api ***@***.***> |
| 抄送人 | Bknds ***@***.***>,
State ***@***.***> |
| 主题 | Re: [songquanpeng/one-api] 请求completions接口提示insufficient_user_quota (Issue #898) |

兑换里添加新的兑换码，然后拿着新的兑换码在充值里给自己充值
…
---- 回复的原邮件 ---- | 发件人 | Row @.> | | 发送日期 | 2024年01月31日 21:10 | | 收件人 | songquanpeng/one-api @.> | | 抄送人 | Bknds @.>, State @.> | | 主题 | Re: [songquanpeng/one-api] 请求completions接口提示insufficient_user_quota (Issue #898) | 需要充值 卧槽明白了，可以了，感谢感谢 怎么充值的，我也遇到相同的问题了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***>

直接进“用户”里给root加余额更快哈哈
