### ISSUE TITLE
请求支持 Huggingface TGI 推理框架 API

### ISSUE THREAD

**Issue by SirlyDreamer** [songquanpeng/one-api#899]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

添加对 [HuggingFace TGI](https://github.com/huggingface/text-generation-inference.git) 框架部署模型的支持

**应用场景**

使用 TGI 框架自建模型推理后端

按照官方文档，TGI API的请求格式为

```JSON
{
    "inputs":"What is Deep Learning?",
    "parameters": {
        "max_new_tokens":20
    }
}
```

**Comment by SirlyDreamer** [comment]
官方文档：https://huggingface.co/docs/text-generation-inference/quicktour

**Comment by RexWzh** [comment]
TGI 文档：https://huggingface.co/docs/text-generation-inference/messages_api

这里提到支持 OpenAI 了：

Text Generation Inference (TGI) now supports the Messages API, which is fully compatible with the OpenAI Chat Completion API. This feature is available starting from version 1.4.0. You can use OpenAI’s client libraries or third-party libraries expecting OpenAI schema to interact with TGI’s Messages API. Below are some examples of how to utilize this compatibility.

> ***Note***: *The Messages API is supported from TGI version 1.4.0 and above. Ensure you are using a compatible version to access this feature.*

**Comment by SirlyDreamer** [comment]
I will close this issue.

**Comment by ENg-122** [comment]
one-api好像还不能支持连接Huggingface TGI 推理框架 API吧？

**Comment by USTCcgg** [comment]
> one-api好像还不能支持连接Huggingface TGI 推理框架 API吧？

一样的问题，发现one-api不支持TGI
