### ISSUE TITLE
限制普通用户对于令牌的设置能力

### ISSUE THREAD

**Issue by aohun** [songquanpeng/one-api#9]
建议令牌生成，过期时间和剩余次数由管理员权限生成和控制，普通用户只保留查看或充值令牌的权限。openaimax等三方代理也是如此设置，感觉这样才符合权限管理。

**Comment by songquanpeng** [comment]
生成，设置过期时间的权限留给用户感觉没啥问题，剩余次数这个确实要有所限制。

我先去调查一下第三方代理一般是怎么做的。

感谢反馈。

**Comment by aohun** [comment]
看了很多三方代理，是用户仅有查看和充值令牌功能，通过兑换码充值“使用量”，就是one-api的使用次数。跟你上面说的一样，剩余次数应该由管理员配置。个人用户不应该有这个权限， 不然会无限制调用接口。

**Comment by songquanpeng** [comment]
确实，兑换码是个好主意，我尽快实现。

**Comment by aohun** [comment]
刚看到更新，普通用户取消了设置令牌次数的能力，但是管理员端也不显示其他用户的令牌，无法设置次数，这样设计是只允许未来的兑换码修改使用次数吗？

**Comment by songquanpeng** [comment]
是的，后端部分我已经完成了，在写前端。

**Comment by aohun** [comment]
好的，目前大家都在使用 tokens为基础的使用量，而非使用次数为单位。

**Comment by songquanpeng** [comment]
确实次数并不是很合理。

**Comment by songquanpeng** [comment]
已改为额度，token 计数下个版本再改，当前版本暂时使用 API 请求次数。

**Comment by songquanpeng** [comment]
兑换码功能已完成。

**Comment by songquanpeng** [comment]
已改为 token 计数，下个版本发布。
