### ISSUE TITLE
区别对待接口返回的错误，选择性禁用

### ISSUE THREAD

**Issue by ccyuvin** [songquanpeng/one-api#90]
测试发现，当自定义的openai接口返回 Rate Limit 和 The model: `gpt-4` does not exist 的错误时， 都会把该条渠道自动禁用。这两种报错是普遍的（免费的APIKEY频率限制一分钟3次，用户选错模型等），并非渠道不能用，不应该自动禁用掉渠道。这会导致后面把所有渠道都自动禁用掉了。
{
  "error": {
    "message": "type invalid_request_error, code model_not_found, message The model: `gpt-4` does not exist",
    "type": "one_api_error"
  }
}

另外能否把openai响应的状态码也暴露出来，现在即使openai接口返回429、401之类的HTTP响应码，one-api返回的都是200响应码。

**Comment by songquanpeng** [comment]
先关掉这个：
![image](https://github.com/songquanpeng/one-api/assets/39998050/43defb97-9e8d-41f5-aa7d-4fb29d2dd852)

这个功能确实还在优化。

**Comment by songquanpeng** [comment]
我记得这个是默认关闭的哈，难道你那里是默认开启的吗？如果是的话这就是另外的 bug 了。

**Comment by songquanpeng** [comment]
那个默认就开启禁用哈。确实描述不够清楚，之后我改一下。

**Comment by songquanpeng** [comment]
我比较好奇，如果是 stream 模式，OpenAI 的错误相应是什么格式的？

**Comment by songquanpeng** [comment]
> 我比较好奇，如果是 stream 模式，OpenAI 的错误相应是什么格式的？

是一样的格式，他貌似并不会在 stream 的返回过程中报错。

**Comment by songquanpeng** [comment]
已修复，已推送 `v0.3.1-alpha.2`
