### ISSUE TITLE
temperature 传递 0 ，发现不生效

### ISSUE THREAD

**Issue by lyn-my** [songquanpeng/one-api#904]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
调用api接口，传递 temperature = 0.0 ， 渠道端日志打印发现temperature  是 0.8 ，我传递的0.0 未生效

**相关截图**

![image](https://github.com/songquanpeng/one-api/assets/47772644/757aa22b-5f6e-4949-a39b-80d00e1ed704)

渠道大模型接收到的日志：
![image](https://github.com/songquanpeng/one-api/assets/47772644/4c4a5bcb-1c4f-43a6-af98-b84106b02382)

**Comment by zx3777** [comment]
这个bug现在还有吗？

**Comment by lyn-my** [comment]
> 这个bug现在还有吗？

有，我现在还没法升级版本，好像最新的版本max_tokens不能超过2000

**Comment by lyn-my** [comment]
> 你好，是什么情况下会失效？调用的什么渠道

我注册是自定义渠道，使用的是自己部署的vllm 运行的qwen大模型。 接口调用如图

**Comment by igophper** [comment]
好的，我会在本地尝试复现一下

**Comment by zx3777** [comment]
我是代理gemini，然后用于沉浸式翻译，发现不传递0，但是设为0.1就能传递了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lyn-my** [comment]
这问题还有人解决吗，感觉我报了快一年了。。。现在饱受这个 temperature 不能为0的问题，导致生产使用结果偶尔变换一下
