### ISSUE TITLE
python openai library can response correctly but oneapi can not.

### ISSUE THREAD

**Issue by panxiaoguang** [songquanpeng/one-api#908]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ x 我已确认目前没有类似 issue
+ x 我已确认我已升级到最新版本
+ x 我已完整查看过项目 README，尤其是常见问题部分
+ x 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ x 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
when I use openai official python library, it gives me right reply.
```python
from openai import OpenAI

client = OpenAI(
    api_key="/key",
    base_url="https://api.hentaigpt.xyz/v1/"
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Hey!",
        }
    ],
    model="gpt-4"
)

print(chat_completion.model_dump_json())

{"id":"chatcmpl-QVrrCPLMODBvevvxPgnN2NG1xqoE","choices":[{"finish_reason":"stop","index":0,"logprobs":null,"message":{"content":"Hello! How can I assist you today?","role":"assistant","function_call":null,"tool_calls":null}}],"created":1704537901,"model":"gpt-4","object":"chat.completion","system_fingerprint":null,"usage":{"completion_tokens":9,"prompt_tokens":2,"total_tokens":11}}
```

but If I add the base_url and apikey into oneapi, it raise errors:
```text
Error: invalid character '<' looking for beginning of value
Resp body: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "api.hentaigpt.xyz",cType: 'managed',cNounce: '81297',cRay: '84134235c904c678',cHash: '3ca331c9cc719c3',cUPMDTk: "\/v1\/chat\/completions?__cf_chl_tk=boQuJ3wZ.CvY5DmxN2_2M1GeYQRxm.tjqGEwsVLLvn8-1704536743-0-gaNycGzNCrs",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/v1\/chat\/completions?__cf_chl_f_tk=boQuJ3wZ.CvY5DmxN2_2M1GeYQRxm.tjqGEwsVLLvn8-1704536743-0-gaNycGzNCrs",md: "pPlg1zZJS8.6kQT5cX3Q.8Ld7sWcxI9ANYUX5MEa5Yc-1704536743-1-AeSEfViIxyHCOdOJ4dBW16kuNW1Gmk0K77VAQdwPlknn278PdxVdMY8ujmAc9vzhjbDr5PzTI3rnaWe0k9mdrf4e120v9FxKi1sxcJTt7rYVy4ry8ZPTyFSnMT4w6bcXj93VrtXU_nXIv2toyTf7tnGmSwz8pge5Yf4l12Yne5YoPhXy1UOBVV1UdOcMb6TmIEPQTgh8vnN38BgwDsc9Qxz9oSWiPTQ-5rjKNbT9qMreAlaXFkxoYi1qYpGwpMQoa6UQ_ceRJCaZGONJvs3wox73uUgxpAuCJYiYw5Sw4Sf0sDLLqitDEQSJ4c9tvi6G7aZVkZZmzswyUZ2DF0WpcSSKby_yTu9DRENIuEyOueNTsKXoEtLKrotBJtHfaG_LrYnLdxZZURiJqysYG6bGfgmSnyjr-BKkALflVnw8Sa8TUVYSTgkYi3ZSREKf0Jxw-zZqzcBOOLqZNZWsEc_uli7L_GrESEteaHfp7FCqm4cbjIv37X5XwY6lkzQdj-jq0DdplqIJmU5z3f3S___sSYM1Hi50IlDdXiAevcsSEpBpp6SSI_DMLAid9PLMrM-nEsCwddPURLAmjm67OQ4IIM8DHdxgKC_V8flDzMbfITSAwFzgSFPPb1omTTKHhf8H-C73KuL0dNgoDdHOvdqWOWEkBa8t2CXWh9u5VBOYnXQcwHTs1Zq6d9tOOfKF0Qhj0ENAF9v76vvOXi6qV4jR9zrT-lAgAZzpp6Y-RHqQF1gN47ECcRzFkmsiYmJXG382-bPXKET5ctKLujWly_VhOjsywK7UbaP-2OWrqcIMuN4cIW4XRby5rHc8KJjTkyeIuvMfZFChJe5F9N8o8ghgAJGa59T9WMNId00PPN6gf8iJh8uL1rskLgGSBOV_rL7sHRh93XXVxNTBFdyQHbHLalrOsTDXz0oKO5jKOajLWEoBiNZ8-iMmzqobXqgW9IlG6oaZJFGNuy4YGo3ZLfc_auUcoTEodEvylbWzRrDBkhmIRLRLkEEgMk-pHETwZKQXH-e5TW72MMwnop_fY-zBty1uYdzin0Pm3GExzBhZbqSNuFXdkjhioWVchyLMxtrtxW_qq7N8WVJ6XxI9iT-ELyoiFjKmYCbYks8i-yX8nwjLOXTvC6DQxsuLxnoPgnp2IBjK2UfwbqTS11DPxUwAgcG5BotokZzFP79QFdfQQsjp3LdT8AOq8Y4JAKoU6JJMEW3F-mt2qbNsjLnR55XlG0k5s58Lj9UhI5j1gmWYe3N36JtBpABmIrDlDuSW-zLzYCbUhO7hqsrLOk_KEIbCSo4XgfpFUqNyfVDRxz8Z0g4dQ2g_8f0rsKW7zKYu2-gyiZa2zesc2Q9Yg01qRhsu_6T6d2_z6InlF0AxdnEUKfbS6BHUu6vp2-kc9Dy-wfWdtw9pzr8BFgfdHsT6PETyCANYYedV6mQdXzXu6s2T-Y7sRFlW95V7_FfFqgGHWGd_ZNRvRYo-0wMIrIDcfcYw2E27qGcgR4nBYYHqArNLe2tUnoX5E6rG5dsqnf5k4Y_xPyRwYmIZnblrXWWP_Hx4ENvHGHUb0svuqWZ-Q6feqq9DC9kTUivtqNl90N2E9GtOHXGuOVRFHhwZ8Vp9nb41xgH8tVdaW8mw3Wb5FxigE43L1YmxQV16xYb2L1eKzBpW4XX3hmaVq6XTVEltZzq6TlcDnpUhDayn6JWl3BY6uQVSbGbDQ5tG9dXEY9cS6jpp-VtCc8ZAg4NDmpNli_26Pb0noMS_Wofm4oPSFC5uwD0JBPQJsO6FpVBSsG_kk-fKv7-4lusbgz5eu4z5dWXxhraWQgOIkIOlevEYIjwoQ1W8TiNMgWxs8VUC_sbrOeCwloRFepCp2lpM45UFlCYGezGd3gvcrXmyfAHSPiXnNQWgMpH819jbgq8ARI44IaUMk4sXFYa-PUB3jQHegvA-85fNFxgVp4sOpOz0kFDGK_XT42Rxp1Xpvk3nZTjfDs_1yUh_L3gmnOiCEEuZxN_4qiwA5FswUOUIINMo5EzWX_u0-9RHpGApiv6HDTAxYy6as_fpBuBCW_Q5izjyYpRTvCFVT8IyhPBgUSDQ7IJ8Gf1KUrsNkFtK0pg_5VkCA9Zy4Tss3AUORNGQHAsR6Dtya-wcUGsIma3N2GwTYXoEb8C-o28ukNZs2KcIzEw5mHZgUVpAQd-i6NzmRL9XhG_yoXuzu1ANXKo-ol8q8zVNnR_FoXllEwl7SpQ-t2S6HzQtzc-_HKEkRrPH0AFH7EgnVgGPfR9ROiOuesdxNk6NlunF4MfZ3fKKOYwPGembJ8YHEPnqHjAkWx_P-KDTMtlKBgKV2Y8bmg6LE2RF0NTsm6bZJqhtI--Z8aA99LUa-YV1SrxadCIx86WWD-GJ0g_aBCNMDep3gYh6JSHbRmA4tn_g6GQFO2XxmNfzUsiY6_T0THvfi-AJ7nTLdyFYfQ7PDkkhx74p965fxSroUUoGnqj7l9B5Huov7vIEo-L2oHA0br5HyIvjM0Fv1K2Fas9FRTVmMoSmrQCzm6oQUvd8DmAQfDAGTj2eHphe_ygi0yIVkysijFSM8gzsaac_zPDklVeWUjBrGnAJexl9hVHKhGz3R7Y6M0UzhCYKa2h9RWS4A_jFrvhYe2OKRjwaZea1IKJLn6qtP_xRX3CYuVLYjSOSk7DU9GSavQKaXZcn9-ToBw",cRq: {ru: 'aHR0cHM6Ly9hcGkuaGVudGFpZ3B0Lnh5ei92MS9jaGF0L2NvbXBsZXRpb25z',ra: 'R28taHR0cC1jbGllbnQvMi4w',rm: 'UE9TVA==',d: 'BOkBxeT7GUiQlr/Y9tlXERXqVepbcIwdcr7ozRnk/j/cbWTZRnci/m93DpHPj8WhvwbNVfocHXyb7ri4bgEnWCt6uQAVFhsUOkrFZUSaVgxerRHc84YIpYRbXT9UR7qEh/1ihEp45VUznOqWEvhMd5qMWUDfogESo+Y4xh7jyAJ1dN7IkEVe+mGEBrDXzqDk+sc08RFPsGbDTv9xdfzWwvQ7zTLHWod4KSOiScb+GkiD7QHYYNiE06NLTYz+jhPFHBeOpg9Lg7PYEsCBIzyIYZegRxpfvMP3drCv3bRh9mnaw0HuzYEripU+9xbXboOIKJBAEMOSybl4vH8TcsvK0jajGNl1OrcVea8LA/s5Sa1Do4ZGWKxfcTjq7CW4Febao+tSGBWC73I9WnCrV5SBora0TnFgeKUGIaZ1tqMPsyhA10a8rIL1y0rwVbKgQLg4QYeuhpzZDVHDabTG+IoZuFxI/KnR6KOHb0fqQvt39z+dg55qMDX83MN996ii+gVjBze4aDGx3r+VzDXJwXybZ8he2bF9vZEUrPnqi/UsC6Y=',t: 'MTcwNDUzNjc0My4zMjgwMDA=',cT: Math.floor(Date.now() / 1000),m: 'LwneD65bmvCdHmHtpPTc/FyatdTbPpQnTqKP/hLf/jk=',i1: '3H51deB1JrYFtylp8m9cmg==',i2: 't/MiQshaIAqiYHbtruDHsA==',zh: 'FHf8f5YsKIAfG4FrSFFeGj0qAJLc3N5lj/Bb16TWenc=',uh: 'AN+5vvENMpdOACvuRa1plLx7uNq9y3wYG+zurIv4jHM=',hh: 'epvhpZpOeHciUXRAHnLm2e6YJGUPYFJWGJ86VKpHMxc=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=84134235c904c678';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/v1\/chat\/completions?__cf_chl_rt_tk=boQuJ3wZ.CvY5DmxN2_2M1GeYQRxm.tjqGEwsVLLvn8-1704536743-0-gaNycGzNCrs" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
```
It's should not be a bug in oneapi. but it's really strange.

**Comment by muxinxy** [comment]
Me too.

**Comment by panxiaoguang** [comment]
I See, I should use API2D mode

**Comment by muxinxy** [comment]
> I See, I should use API2D mode

How to use API2D mode

**Comment by panxiaoguang** [comment]
> > I See, I should use API2D mode
> 
> How to use API2D mode

I'm sorry, I have been misleaded by the new version with New ui, it has beed tested passed but could be not used.

**Comment by panxiaoguang** [comment]
> > I See, I should use API2D mode
> 
> How to use API2D mode

and It probably not a bug on one-api, it maybe the caused by blocks on ip address.

**Comment by muxinxy** [comment]
Based on the error message "Enable JavaScript and cookies to continue," it seems that this API may have rejected the call from one-api. Therefore, I deployed a proxy through Cloudflare workers to simulate a browser sending requests to the upstream API, and successfully called this API by filling in the proxy address in one-api.
```
const MY_URL = 'https://API';

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  const url = new URL(request.url);
  const headers_Origin = request.headers.get("Access-Control-Allow-Origin") || "*";
  url.host = MY_URL.replace(/^https?:\/\//, '');

  // Clone the original request headers and modify User-Agent and Accept
  const newHeaders = new Headers(request.headers);
  newHeaders.set('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3');
  newHeaders.set('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8');

  const modifiedRequest = new Request(url.toString(), {
    headers: newHeaders,
    method: request.method,
    body: request.body,
    redirect: 'manual' // Set redirect mode to manual for custom handling
  });

  let response = await fetch(modifiedRequest);

  // Handle redirection
  if (response.redirected) {
    return Response.redirect(response.url, response.status);
  }

  const modifiedResponse = new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers
  });

  // Add the Access-Control-Allow-Origin header for cross-origin access
  modifiedResponse.headers.set('Access-Control-Allow-Origin', headers_Origin);

  return modifiedResponse;
}
```

**Comment by panxiaoguang** [comment]
> Based on the error message "Enable JavaScript and cookies to continue", it seems that this API may have rejected the call from one-api. Therefore, I deployed a proxy through Cloudflare workers to simulate a browser sending requests to the upstream API, and successfully called this API by filling in the proxy address in one-api.根据错误消息“启用 JavaScript 和 cookie 以继续”，似乎此 API 可能拒绝了来自 one-api 的调用。因此，我通过 Cloudflare workers 部署了一个代理来模拟浏览器向上游 API 发送请求，并通过在 one-api 中填写代理地址成功调用了这个 API。
> 
> ```
> const MY_URL = 'https://API';
> 
> addEventListener('fetch', event => {
>   event.respondWith(handleRequest(event.request))
> })
> 
> async function handleRequest(request) {
>   const url = new URL(request.url);
>   const headers_Origin = request.headers.get("Access-Control-Allow-Origin") || "*";
>   url.host = MY_URL.replace(/^https?:\/\//, '');
> 
>   // Clone the original request headers and modify User-Agent and Accept
>   const newHeaders = new Headers(request.headers);
>   newHeaders.set('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3');
>   newHeaders.set('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8');
> 
>   const modifiedRequest = new Request(url.toString(), {
>     headers: newHeaders,
>     method: request.method,
>     body: request.body,
>     redirect: 'manual' // Set redirect mode to manual for custom handling
>   });
> 
>   let response = await fetch(modifiedRequest);
> 
>   // Handle redirection
>   if (response.redirected) {
>     return Response.redirect(response.url, response.status);
>   }
> 
>   const modifiedResponse = new Response(response.body, {
>     status: response.status,
>     statusText: response.statusText,
>     headers: response.headers
>   });
> 
>   // Add the Access-Control-Allow-Origin header for cross-origin access
>   modifiedResponse.headers.set('Access-Control-Allow-Origin', headers_Origin);
> 
>   return modifiedResponse;
> }
> ```

That's a good method to fix the problem, and I thank you so much for giving such good solutions beyond the project itself. I recommend that you add this method to README, as I think some other people will encounter the same issues.

**Comment by panxiaoguang** [comment]
> Based on the error message "Enable JavaScript and cookies to continue", it seems that this API may have rejected the call from one-api. Therefore, I deployed a proxy through Cloudflare workers to simulate a browser sending requests to the upstream API, and successfully called this API by filling in the proxy address in one-api.根据错误消息“启用 JavaScript 和 cookie 以继续”，似乎此 API 可能拒绝了来自 one-api 的调用。因此，我通过 Cloudflare workers 部署了一个代理来模拟浏览器向上游 API 发送请求，并通过在 one-api 中填写代理地址成功调用了这个 API。
> 
> ```
> const MY_URL = 'https://API';
> 
> addEventListener('fetch', event => {
>   event.respondWith(handleRequest(event.request))
> })
> 
> async function handleRequest(request) {
>   const url = new URL(request.url);
>   const headers_Origin = request.headers.get("Access-Control-Allow-Origin") || "*";
>   url.host = MY_URL.replace(/^https?:\/\//, '');
> 
>   // Clone the original request headers and modify User-Agent and Accept
>   const newHeaders = new Headers(request.headers);
>   newHeaders.set('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3');
>   newHeaders.set('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8');
> 
>   const modifiedRequest = new Request(url.toString(), {
>     headers: newHeaders,
>     method: request.method,
>     body: request.body,
>     redirect: 'manual' // Set redirect mode to manual for custom handling
>   });
> 
>   let response = await fetch(modifiedRequest);
> 
>   // Handle redirection
>   if (response.redirected) {
>     return Response.redirect(response.url, response.status);
>   }
> 
>   const modifiedResponse = new Response(response.body, {
>     status: response.status,
>     statusText: response.statusText,
>     headers: response.headers
>   });
> 
>   // Add the Access-Control-Allow-Origin header for cross-origin access
>   modifiedResponse.headers.set('Access-Control-Allow-Origin', headers_Origin);
> 
>   return modifiedResponse;
> }
> ```

Yes, that's a good idea
