### ISSUE TITLE
以容器的形式跑一晚之后会报错：java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by formero009** [songquanpeng/one-api#91]
用docker的形式挂了一晚上，第二天早上所有的请求都会报
java.net.ProtocolException: unexpected end of stream
重启了oneapi的容器后就正常了。
我用的是okhttp3,百度这个错误说是服务器返回的length 和实际的length不一致导致的。
不知道是不是这个原因，对了，我是用stream的形式请求的服务。

**Comment by songquanpeng** [comment]
有更详细的报错吗？

**Comment by songquanpeng** [comment]
Demo 站挂好久了也没啥问题哈

**Comment by formero009** [comment]
![image](https://github.com/songquanpeng/one-api/assets/25760739/c2be3701-a4d1-47f9-bb84-cc76bfe83236)
我是用java的调的，现在复现不了了。。。
等我晚点再看看

**Comment by songquanpeng** [comment]
好的，期待进一步的反馈。

**Comment by formero009** [comment]
应该是网络问题

**Comment by songquanpeng** [comment]
Oka，暂时也没有遇到其他人复现该问题。
