### ISSUE TITLE
为 One API 依照 OpenAI 格式实现余额查询相关接口

### ISSUE THREAD

**Issue by ickacn** [songquanpeng/one-api#92]
目前前端是用的ChatGPT-Next-Web，後端用ONE-API，然後接到AZ，沒有使用openai的，然後在web頁面手動填寫one api產生的KEY使用。
發現在ChatGPT-Next-Web的log中會顯示類似下面的內容
[User IP]  *.*.*.*
[Time]  5/16/2023, 10:51:21 AM
[Auth] use user api key
[Proxy]  dashboard/billing/subscription?path=dashboard&path=billing&path=subscription
[Base Url] https://one-api-ip
[OpenAI Request] invalid api key provided Bearer 5971a218b241415aa7159248af2e20ba
[OpenAI Route] params  { path: [ 'dashboard', 'billing', 'usage' ] }
[Auth] allowed hashed codes:  [ '4c9184f37cff01bcdc32dc486ec36961' ]
[Auth] hashed access code: d41d8cd98f00b204e9800998ecf8427e
[Auth] got access code: 
[User IP]  *.*.*.*
[User IP]  *.*.*.*
[Proxy]  dashboard/billing/usage?start_date=2023-05-01&end_date=2023-05-17&path=dashboard&path=billing&path=usage
[OpenAI Parse]  [SyntaxError: Unexpected token < in JSON at position 0]
[OpenAI Route] params  { path: [ 'dashboard', 'billing', 'subscription' ] }

是不是這樣的可以直接返回當前令牌的剩餘額度之類的，畢竟那個key是one-api產生的。

**Comment by songquanpeng** [comment]
是的，本来就是要这样搞，还没来得及实现。

**Comment by songquanpeng** [comment]
已实现，返回的是用户账户的剩余额度。
