### ISSUE TITLE
用户一旦忘记用户名将无法登录

### ISSUE THREAD

**Issue by by123456by** [songquanpeng/one-api#921]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
用户一旦忘记用户名将无法登录
用户忘记用户名，不能用邮箱登录，重置密码不显示用户名
**复现步骤**
使用邮箱作为账号无法登录，重置密码后没有用户名显示
**预期结果**
可以使用邮箱作为用户名或重置密码后回显用户名

**Comment by popdo** [comment]
希望支持邮箱登录+1.

每天都有用户把邮箱当用户名注册不上
要么就是总忘记用户名。

每天要处理很多这种不必要的售后问题。

**Comment by songquanpeng** [comment]
确实这个设计的不合理，邮箱应该直接可以作为用户名使用

**Comment by songquanpeng** [comment]
已经支持邮箱登录

**Comment by popdo** [comment]
> 已经支持邮箱登录

虽然支持邮箱登录，但限制了12个字符。一个@gmail.com后缀就占了10个。🤦🏻‍♀️

如果仅仅只是担心太长影响前端的展示：
1、我看有个“显示名称”的字段，可以截取部分长度赋值给这个字段，在前端使用这个字段来展示。
2、也完全可以通过css设置超出隐藏 或鼠标滑过tooltip展示完整邮箱地址。

我觉得合理的长度限制应该在20-30。有域名白名单应该也不会存在恶意的机器号注册。
