### ISSUE TITLE
大佬能出个详细的配置接入其他网站的教程吗，我部署成功了，想把chatgpt next web页面嵌入进来，，但是奈何本人干后端的，搞不定

### ISSUE THREAD

**Issue by lobmoo** [songquanpeng/one-api#928]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by QAbot-zh** [comment]
这不难啊，如果你是同一个服务器部署的，就用readme里的docker指令，如果是两个平台，就在设置里添加聊天链接：
![image](https://github.com/songquanpeng/one-api/assets/40236765/3f7187b7-add7-47f4-bc40-cdb90391b6d7)
