### ISSUE TITLE
注册限制弱密码

### ISSUE THREAD

**Issue by Aiayw** [songquanpeng/one-api#93]
当前只限制了位数，大部分用户设置密码都是12345678这类弱密码，加上正则判断密码是否包含字母和数字是不是会更安全一些。
或者加个选项？后台可以控制密码设置的难度
例如：
1、限制位数
2、限制数字+字母+位数
3、限制数字+大小写字母+位数
4、限制数字+大小写字母+特殊符号+位数

仅供参考，哪怕只限制第二个选项，也能极大增强用户密码安全性。

**Comment by songquanpeng** [comment]
Okay，这个好搞，之后解决。

**Comment by songquanpeng** [comment]
我感觉没太大必要，登录界面是有 Cloudflare Turnstile 用户校验的，不必担心爆破。
