### ISSUE TITLE
使用自动化更新key的时候，想通过数据直接精准更新，结果触发数据库一致性报错

### ISSUE THREAD

**Issue by Adsryen** [songquanpeng/one-api#930]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ √] 我已确认目前没有类似 issue
+ [ √] 我已确认我已升级到最新版本
+ [ √] 我已完整查看过项目 README，尤其是常见问题部分
+ [ √] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ √] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

```json
{
  "error": {
    "message": "数据库一致性已被破坏，请联系管理员 (request id: 2024011223333990037951xuUR86KP)",
    "type": "one_api_error"
  }
}
```

**复现步骤**

**预期结果**
期望脚本修改数据的渠道信息能继续正常使用接口

**Comment by songquanpeng** [comment]
参考 readme：
![image](https://github.com/songquanpeng/one-api/assets/39998050/0210d0e4-fc51-4262-9290-7c48df2b29bd)
