### ISSUE TITLE
render部署重启后数据丢失

### ISSUE THREAD

**Issue by 1715819** [songquanpeng/one-api#939]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
部署到render平台上，容器重启后数据丢失。请问可以使用环境变量接入数据库吗
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by QAbot-zh** [comment]
当然可以，设置SQL_DSN

**Comment by chendonghp** [comment]
需要另外开一个postgres数据库实例，然后主服务连到这个数据库

**Comment by molezz** [comment]
render的免费数据库90天会清空一次，有什么方法导出导入一次吗？
