### ISSUE TITLE
智普GLM支持chatglm4了,希望增加这个模型

### ISSUE THREAD

**Issue by fengjisheng** [songquanpeng/one-api#943]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
chatglm4模型已经开放API支持了, 支持系统角色, 可以像openai带上系统角色调教. 这个很期待...

**Comment by Mrxyy** [comment]
系统添加

**Comment by kuziTony** [comment]
还有function call之类的功能似乎都更新了   当前的V3接口可以直接调用  但是似乎功能不全  更新到V4应该可以

**Comment by gp109428** [comment]
希望添加+1

**Comment by Joy0934** [comment]
希望增加+1

**Comment by realreus319** [comment]
希望+1

**Comment by shentong0722** [comment]
现在就可以用啊，直接自己加glm-4模型不就可以吗

**Comment by onewesong** [comment]
![image](https://github.com/songquanpeng/one-api/assets/17920822/f8f8b0a7-7e41-4516-b66b-deb10356d769)
这样配置不知道行不行

**Comment by gp109428** [comment]
<img width="861" alt="image" src="https://github.com/songquanpeng/one-api/assets/48469710/1e72d07a-bf17-4f47-ad10-04bfe1a157f1">
直接这样配置是可以用的，但是现在对话会报top_p参数错误，用的FastGPT，貌似是这个参数值写死1导致的

**Comment by zmlstc** [comment]
> <img alt="image" width="861" src="https://private-user-images.githubusercontent.com/48469710/298892468-1e72d07a-bf17-4f47-ad10-04bfe1a157f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTE4NDksIm5iZiI6MTcwNjUxMTU0OSwicGF0aCI6Ii80ODQ2OTcxMC8yOTg4OTI0NjgtMWU3MmQwN2EtYmYxNy00ZjQ3LWFkMTAtMDRiZmUxYTE1N2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA2NTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTg2ZjFkZjRkM2I0MjA0MzY5Nzk3ZmE5N2EzNjVjNGVlZjFlNDNmYWM4YTc1NzcyMmE2YzdjNTdhOTEwMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9W8LAd9TIbVd2nFnHAWZflc8IHTdIKJdfqLiWsOGlE"> 直接这样配置是可以用的，但是现在对话会报top_p参数错误，用的FastGPT，貌似是这个参数值写死1导致的

+1，碰到一样的问题

**Comment by ryoung-sh** [comment]
> <img alt="image" width="861" src="https://private-user-images.githubusercontent.com/48469710/298892468-1e72d07a-bf17-4f47-ad10-04bfe1a157f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjY0OTAsIm5iZiI6MTcwNzcyNjE5MCwicGF0aCI6Ii80ODQ2OTcxMC8yOTg4OTI0NjgtMWU3MmQwN2EtYmYxNy00ZjQ3LWFkMTAtMDRiZmUxYTE1N2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4MjMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGI4YmIxNzg2MTZiMzZmOTg5MTY1YzA5ZGQ0NzZiYzc0NWJhYTI4MjYwOGZiYjhiMWNlZjA1MGMyYWM5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUD-8Wp9h5HwK6ODlYGdpd2MTSIXo7Vod5sPv68pURM"> 直接这样配置是可以用的，但是现在对话会报top_p参数错误，用的FastGPT，貌似是这个参数值写死1导致的

直接改参到0.7不行吗？glm-4文档写了是不能是0或1的。
