### ISSUE TITLE
查看模型调用历史

### ISSUE THREAD

**Issue by how1ewu** [songquanpeng/one-api#95]
能够查看用户模型调用的历史

**Comment by songquanpeng** [comment]
Okay



---Original---
From: ***@***.***&gt;
Sent at: 2023年5月18日(Thu) PM2:44
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 查看模型调用历史 (Issue #95)




 
能够查看用户模型调用的历史

**Comment by songquanpeng** [comment]
相关 issue：#77
