### ISSUE TITLE
智谱更新glm4了，会考虑添加支持吗

### ISSUE THREAD

**Issue by yueliang-x** [songquanpeng/one-api#952]

**Comment by QAbot-zh** [comment]
直接在原来的api资源包里添加模型好像调用是可以的
![image](https://github.com/songquanpeng/one-api/assets/40236765/d79084fd-a343-46a7-91d4-01a12a31927b)

**Comment by kuziTony** [comment]
暂时是可以用的  但是会有奇怪的问题引入

**Comment by ShanySky** [comment]
我调用的时候会出现错误：[1214][top_p参数非法。请检查文档。]
<img width="577" alt="调用智谱接口出错" src="https://github.com/songquanpeng/one-api/assets/61485912/c321f770-2973-4af1-9192-b4ecd135a143">

**Comment by QAbot-zh** [comment]
> 我调用的时候会出现错误：[1214][top_p参数非法。请检查文档。] <img alt="调用智谱接口出错" width="577" src="https://private-user-images.githubusercontent.com/61485912/298375314-c321f770-2973-4af1-9192-b4ecd135a143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzI1NjcsIm5iZiI6MTcwNTgzMjI2NywicGF0aCI6Ii82MTQ4NTkxMi8yOTgzNzUzMTQtYzMyMWY3NzAtMjk3My00YWYxLTkxOTItYjRlY2QxMzVhMTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEwMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YWUzYTQ2NWNjNmI2OWZkNjIzYzk5NjJlYmQ2YWYxNjczZjNmNTg3ZDc0ZDgzYWUzYzgxYmFhZmYwYjljMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D80yRcf_gPXf2WHWQ7FuIxvwVREweW7gkG132R3VSm4">

这是聊天前端的问题，把top_p参数设置调整一下就好了，智谱api的调用文档对参数进行了调整，top_p不能等于0或者1
![image](https://github.com/songquanpeng/one-api/assets/40236765/ac099d39-a1f5-4f10-b842-5f9d0c6e8f72)

**Comment by ShanySky** [comment]
还有一个很奇怪

> > 我调用的时候会出现错误：[1214][top_p参数非法。请检查文档。] <img alt="调用智谱接口出错" width="577" src="https://private-user-images.githubusercontent.com/61485912/298375314-c321f770-2973-4af1-9192-b4ecd135a143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzI1NjcsIm5iZiI6MTcwNTgzMjI2NywicGF0aCI6Ii82MTQ4NTkxMi8yOTgzNzUzMTQtYzMyMWY3NzAtMjk3My00YWYxLTkxOTItYjRlY2QxMzVhMTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEwMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YWUzYTQ2NWNjNmI2OWZkNjIzYzk5NjJlYmQ2YWYxNjczZjNmNTg3ZDc0ZDgzYWUzYzgxYmFhZmYwYjljMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D80yRcf_gPXf2WHWQ7FuIxvwVREweW7gkG132R3VSm4">
> 
> 这是聊天前端的问题，把top_p参数设置调整一下就好了，智谱api的调用文档对参数进行了调整，top_p不能等于0或者1 ![image](https://private-user-images.githubusercontent.com/40236765/298375459-ac099d39-a1f5-4f10-b842-5f9d0c6e8f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzI3MzAsIm5iZiI6MTcwNTgzMjQzMCwicGF0aCI6Ii80MDIzNjc2NS8yOTgzNzU0NTktYWMwOTlkMzktYTFmNS00ZjEwLWI4NDItNWY5ZDBjNmU4ZjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEwMjAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMGRkOWM5ZWVlZjZiOGQwMTViMGY5NjljYWFkNjAzZDBmNDVmNGQxNGEzNDVhNWFhMDRlNWZkMDAzMmM5OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws887jteDry4fTz8d58t2G8JpEXgSGQUL3amgRhLpnk)

有效，感谢指导！

**Comment by zerotwotnt** [comment]
现在支持了智谱的glm4了吗🤔🤔🤔

**Comment by songquanpeng** [comment]
v0.6.1-alpha.2 已经支持
