### ISSUE TITLE
访问控制台也会429,这是什么原因

### ISSUE THREAD

**Issue by hlovingness** [songquanpeng/one-api#963]
![image](https://github.com/songquanpeng/one-api/assets/16331459/9bc02f27-0683-4047-8936-9f4626daa1f3)

**Comment by songquanpeng** [comment]
访问太频繁被频控了，一般出现在多次强制刷新的情况下

**Comment by hlovingness** [comment]
这个频率有参数控制吗，我是在频繁的切换页面下出现的

**Comment by helloxz** [comment]
> 这个频率有参数控制吗，我是在频繁的切换页面下出现的

添加这个环境变量：GLOBAL_WEB_RATE_LIMIT，说明里面有。

**Comment by hlovingness** [comment]
看到了，谢谢
