### ISSUE TITLE
分享一下有refresh token实现自动更新access token的脚本并发送通知到微信

### ISSUE THREAD

**Issue by spacex-3** [songquanpeng/one-api#967]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
有refresh token的情况，可以直接在vps上面定期跑这个脚本实现自动更新access token并发送通知到微信，其中日志脚本没有怎么设置，忽略即可

**复现步骤**

>#!/bin/bash
>
>#sudo apt-get update
>#sudo apt-get install jq 安装jq组件
>#sqlite3 /真实路径/one-api.db "SELECT key FROM channels;" 查询当前access token
>#0 5 * * 1 /真实路径/token_oneapi_test.sh 定时每周一5点执行
>
>
># 定义日志文件
>LOGFILE="$(pwd)/script_log_$(date +%Y%m%d_%H%M%S).log"
>
># 官网获取access_token，来源始皇
>result1=$(curl -s -X POST "https://auth0.openai.com/oauth/token" \
>    -H "Content-Type: application/json" \
>     -d '{
>        "redirect_uri": "com.openai.chat://auth0.openai.com/ios/com.openai.chat/callback",
>        "grant_type": "refresh_token",
>        "client_id": "pdlLIX2Y72MIl2rhLhTE9VV9bN905kBh",
>        "refresh_token": "替换我"
>     }') &>> $LOGFILE
>
># 从result1中提取access_token
>access_token=$(echo "$result1" | jq -r '.access_token')
>
># 检查access_token是否为空
>if [ -z "$access_token" ]; then
>    echo "Error: Failed to obtain access token." >> $LOGFILE
>    exit 1
>fi
>
># 更新序号为1的数据库中的token
>sqlite3 /真实路径/one-api.db "UPDATE channels SET key = \"$access_token\" WHERE id = 1;" &>> $LOGFILE
>
># 检查SQLite命令执行状态
>if [ $? -ne 0 ]; then
>    echo "Error: Failed to update database." >> $LOGFILE
>    exit 1
>fi
>
># 微信通知
>pushURL="http://www.pushplus.plus/send"
>title="update%20access%20token"
>content=$(echo -e "$access_token" | jq -sRr @uri)
>curl -s "$pushURL?token=替换我发通知&title=$title&content=$content&template=html" >> $LOGFILE
>
># 检查CURL命令执行状态
>if [ $? -ne 0 ]; then
>   echo "Error: Failed to send WeChat notification." >> $LOGFILE
>    exit 1
>fi
>
>echo "Script executed successfully." >> $LOGFILE

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by spacex-3** [comment]
诶格式不知道怎么搞，大概意思看懂就行了吧

**Comment by QAbot-zh** [comment]
> 诶格式不知道怎么搞，大概意思看懂就行了吧

使用“```”包裹代码，而不是引用格式，代码格式才不会乱掉

**Comment by Payne-Wang** [comment]
> 诶格式不知道怎么搞，大概意思看懂就行了吧

老哥，oneapi.db的路径一般在哪里啊？找了一圈没找到
