### ISSUE TITLE
[ 定价错误 ] 3.5-turbo 和 3.5-turbo-16k 的 输出定价 错误 ！

### ISSUE THREAD

**Issue by B3nDan** [songquanpeng/one-api#968]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我看代码时，注意到您写了这么一段

![Screenshot_20240126_084832](https://github.com/songquanpeng/one-api/assets/129975925/7ef3752c-339a-450f-80d2-10d7ebe1c244)

我不理解为什么你要在这个 时间点 改成 2 倍

这样算下来：

gpt-3.5-turbo 输入价格 0.0015 输出价格 0.0030

但实际上：

gpt-3.5-turbo 输入价格 0.0015 输出价格 0.0020

![Screenshot_20240126_084749](https://github.com/songquanpeng/one-api/assets/129975925/a9ca42a2-8e11-4cb6-87cd-87ade8b04b5d)
![image](https://github.com/songquanpeng/one-api/assets/129975925/26559a18-feb5-4539-a8bc-88e5d3162ec9)

我也注意到你在代码里贴了一个链接

https://platform.openai.com/docs/models/continuous-model-upgrades

但我看了这整个文章，也没看到 OpenAI 说要涨价的事情

那这到底是为什么呢？

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/9ca0c070-0b2a-4a07-84c6-245749552aec)
#696

**Comment by songquanpeng** [comment]
首先你要知道的是这种不带版本号的模型实际上是动态替换的，我记得是因为在这个时间点之后其背后的模型倍率发生了变化。

**Comment by songquanpeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/39998050/76e9ea31-7f91-43d4-914e-905e32bec301)

**Comment by dirname** [comment]
> > ![image](https://private-user-images.githubusercontent.com/39998050/300239074-9ca0c070-0b2a-4a07-84c6-245749552aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjkxNTUsIm5iZiI6MTcwNjQyODg1NSwicGF0aCI6Ii8zOTk5ODA1MC8zMDAyMzkwNzQtOWNhMGMwNzAtMGIyYS00YTA3LTg0YzYtMjQ1NzQ5NTUyYWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA4MDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YjZiODRhYzRmNDY1OWY3NjQ3MjNhY2VhNTQxZjJhN2M1ZmU3YjU5YTczOTU0NzgwODQ2N2IxNDk2YjY4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0dvuKQdeQ0Xm75qwjA8bRZGjRlT_zAv-3BL4ZXbkw4w) #696
> 
> 原始pr的第二个链接 model update，也写明了那是指向 0613 ，而不是 1106。什么时候指向1106,官方还未明确表示吧？
> 
> 包括todo后面的那个链接，也只是官方说会指向最新的，但是没有定时间。 他这个2023.12.11这个时间点是怎么得出的，我就觉得很奇怪。难道官方之前写了预测时间，然后删了？
> 
> 事实也证明，现在还是 0613 ![Screenshot_20240128_160835](https://private-user-images.githubusercontent.com/129975925/300247132-80062303-a017-4255-beea-7f39cd723e4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Mjk4NDMsIm5iZiI6MTcwNjQyOTU0MywicGF0aCI6Ii8xMjk5NzU5MjUvMzAwMjQ3MTMyLTgwMDYyMzAzLWEwMTctNDI1NS1iZWVhLTdmMzljZDcyM2U0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwODEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzgzMmIwMjRhN2VhNzhhYzM1OThkMGJjNzkwZTk4ZjcxMTJiOWE2Yjk2ZmRmYTBjMjFhODZjOWQ0ZjUzMjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gXpI4_TRGmuMN4vYzRHwphROqBB5ctZpJCP_K691RLU)
> 
> ![Screenshot_20240128_160942](https://private-user-images.githubusercontent.com/129975925/300247195-b7c69ea3-f2e7-4d5c-b6ac-31cab3081813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Mjk4NDMsIm5iZiI6MTcwNjQyOTU0MywicGF0aCI6Ii8xMjk5NzU5MjUvMzAwMjQ3MTk1LWI3YzY5ZWEzLWYyZTctNGQ1Yy1iNmFjLTMxY2FiMzA4MTgxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwODEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGNhNjkwNjE0MDJmMzZlMTEyM2NjMTEyM2I0OGUxZDM4M2Y1NDQzMzQzNTA2M2ZjOTNiMDc2NDNjMDBjNTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xq2jdT-BQEJdKBl3G5_m7ryqscI-VA4KItfOw3-vYtY)

实际上就是你想的这样，后面 OpenAI 更新了文档，在 PR 合并前后的一段时间内，文档中表明了具体的时间。我尝试在 [web.archive.org](https://web.archive.org/web/20230601000000*/https://platform.openai.com/docs/models/continuous-model-upgrades) 查看快照，但可能由于 WAF 或其他原因，无法预览具体内容。另外，我找到了以下相关的信息

https://community.openai.com/t/gpt-3-5-4-model-documentation-nov-7-2023-still-has-inaccuracies-about-snapshots/462172

从上可得知，文档的更新时间是 2023-11-07，当时文档中包含了具体的时间。另附，review 时的截图


![20240128162801](https://github.com/songquanpeng/one-api/assets/18101258/b8b45703-17d2-442f-b09d-072226d4ac09)

**Comment by songquanpeng** [comment]
已经支持了自定义补全比例，在运营设置里：
![image](https://github.com/songquanpeng/one-api/assets/39998050/e627aef5-135e-4317-ba97-109c9adf3d66)
