### ISSUE TITLE
宝塔部署出现空白界面的解决方案

### ISSUE THREAD

**Issue by LanQian528** [songquanpeng/one-api#97]
在宝塔界面的网站一栏中，找到你部署的对应网站，打开配置文件
![image](https://github.com/songquanpeng/one-api/assets/5499636/6b5d4b10-74f8-4002-af46-77cb901965c6)
在配置文件的末尾，删除如下部分内容后保存
![image](https://github.com/songquanpeng/one-api/assets/5499636/346d4ee5-58f7-4107-9c97-04d4b4827fe8)

**Comment by zhtest000** [comment]
curl 127.0.0.1:3000/
返回的没有BODY
