### ISSUE TITLE
Add MongoDB and MySQL support

### ISSUE THREAD

**Issue by analogpvt** [songquanpeng/one-api#98]
Add MongoDB if possible to make it robust and Serverless as well

**Comment by songquanpeng** [comment]
MySQL support is already here.

But why we need MongoDB here?

**Comment by analogpvt** [comment]
also where to configure environment variables

**Comment by songquanpeng** [comment]
It's already scalable. Check out #88。



> also where to configure environment variables

If you are using Docker, like this: 
```
docker run -d -e ENV_VAR_NAME=VALUE -e ENV_VAR_NAME2=VALUE2 --restart always -p 3000:3000 -v /home/ubuntu/data/one-api:/data justsong/one-api
```

**Comment by analogllp** [comment]
If not using docker then ?

**Comment by songquanpeng** [comment]
If you are using Linux or macOS:
```
ENV_VAR_NAME=VALUE ./one-api
```

**Comment by analogllp** [comment]
If possible please add .env file or any script for it where it will be easy to add all things like database and secret keys etc

**Comment by songquanpeng** [comment]
Docker is recommended.

And it's simple to write a launch script for it if you want to deploy the built binary directly.

Later I will add .env support.

Related issue: #23

**Comment by analogllp** [comment]
Also if possible add option for English menu or set custom from admin panel that will be good to make it internationally available

**Comment by songquanpeng** [comment]
i18n will be supported. But currently I don't have too much time for it.



---Original---
From: ***@***.***&gt;
Date: Fri, May 19, 2023 14:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] Add MongoDB and MySQL support (Issue #98)




 
Also if possible add option for English menu or set custom from admin panel that will be good to make it internationally available

**Comment by analogpvt** [comment]
also azure openai api request is not streaming its just showing full response

**Comment by songquanpeng** [comment]
> also azure openai api request is not streaming its just showing full response

Thanks for reporting this, but it's working in my case:
![image](https://github.com/songquanpeng/one-api/assets/39998050/3483dd5e-96bd-4b61-8ba0-7eba3c89d6b2)
