### ISSUE TITLE
添加 AI.LS API

### ISSUE THREAD

**Issue by airyland** [songquanpeng/one-api#99]
Hi，希望能添加我们的服务 AI.LS：

网址：https://ai.ls (备用 https://2.gpt01.xyz/)
API 地址：https://api.caipacity.com

接口上兼容 OpenAI API 接口，支持 gpt-3.5 及 gpt-4。

**Comment by songquanpeng** [comment]
可以的，最近适配。

考虑到工作量和 README 中要添加的链接，也希望可以对等宣传一下。

**Comment by airyland** [comment]
> 可以的，最近适配。
> 
> 考虑到工作量和 README 中要添加的链接，如果可以在贵站的群里宣传一下最好不过。

没问题。回头也会添加到我们的文档中。

**Comment by songquanpeng** [comment]
接口至少有两个不兼容的地方：
1. 流式传输的接口在输出 [DONE] 后是不是多了点东西？
2. 第二个我还没找到到底为什么，会发现有时候你的接口返回的内容不是 JSON，而是直接的内容，如下图所示，前两个输出是别的通道，第三个是 AL.lS 的输出：
![image](https://github.com/songquanpeng/one-api/assets/39998050/9d316d3f-90a1-4a66-aecf-663e87ab1194)

**Comment by songquanpeng** [comment]
第二个我用 Postman 测试发现是正常的，这就很离谱了，还在调查中。

**Comment by airyland** [comment]
网页上的免费使用做了优化，为了加快传输只会输出文字。

我们有 10000 token 的免费额度，你也可以使用下面配置：

key: B698CA6D-4C47-493C-9B3F-6A4D41DEFF32
api endpoint: https://api.caipacity.com

**Comment by songquanpeng** [comment]
如果我想返回正常的格式，需要设置什么？

**Comment by airyland** [comment]
我的逻辑里只有加了 ?full=false 参数会是以纯文字返回。如果有没有加这个参数，应该是会完全返回的。

**Comment by songquanpeng** [comment]
我没有加这个参数，现在的情况是，通道可以使用，流式和非流式都没问题。

但是通道测试的时候会发现返回变成了上述的纯文字，导致接口无法进行测试。

**Comment by songquanpeng** [comment]
所谓的通道测试实际上就是发送一个简单的 hi 消息，按理说不该这样，还在调查中。

**Comment by airyland** [comment]
奇怪，我也去测试了下，看起来是正常的，没有出现纯文字返回的情况。

**Comment by songquanpeng** [comment]
找到问题了，你应该做了缓存。

**Comment by songquanpeng** [comment]
我换个提示词就是正常的，你的缓存机制没有考虑到 ?full=false 参数。

**Comment by songquanpeng** [comment]
Postman 复现了：
![image](https://github.com/songquanpeng/one-api/assets/39998050/8828bfd7-b484-4c6d-890c-c28c38d0cb21)

**Comment by airyland** [comment]
明白了，我的 bug，我去修复下。

**Comment by songquanpeng** [comment]
stream 模式的返回实现的也有问题哈。
正常的：
![image](https://github.com/songquanpeng/one-api/assets/39998050/1bcfba81-9e6c-4911-9563-7160f434de5a)

AI.LS 的：
![image](https://github.com/songquanpeng/one-api/assets/39998050/1e0a74db-9fb8-4205-b7b2-068e7bf5bc76)

**Comment by songquanpeng** [comment]
第二个 bug 对 One API 没影响，因为我做了适配。

但是推荐也修复一下哈，不然肯定会出现部分 APP 用不了的情况。

**Comment by airyland** [comment]
上面返回纯文字的逻辑已经修复。下面的不一致是指 id 和 created 格式么。咦，后面多出了两个 empty。

**Comment by songquanpeng** [comment]
那是前面多个两个 Empty，而且后面没有 [DONE] 结尾。

**Comment by songquanpeng** [comment]
确实，created 的格式也有问题，推荐还是搞成兼容的哈。

**Comment by airyland** [comment]
诡异，应该是这两天处理后端多数据源导致的 bug，我去处理下。格式我也处理下。
感谢！

**Comment by songquanpeng** [comment]
没有 aff 系统吗？我想在 README 链接上加上我的推荐码。。。

**Comment by airyland** [comment]
刚想请你喝个咖啡，没有找到赞赏入口

**Comment by airyland** [comment]
> 没有 aff 系统吗？我想在 README 链接上加上我的推荐码。。。

正在测试中，即将上线。

**Comment by songquanpeng** [comment]
有的哈：
![image](https://github.com/songquanpeng/one-api/assets/39998050/350ddb82-9e89-4982-a070-958b38275a0f)

感谢~

**Comment by songquanpeng** [comment]
已支持，README 也已更新。AFF 系统上线后我再来加我的推荐码。

**Comment by airyland** [comment]
已经看到，感谢。

**Comment by airyland** [comment]
Hi。今天注意到 AI.LS 已经从首页移除，疑惑是因为什么原因？

**Comment by songquanpeng** [comment]
README 上太多了就清理了一波，留了几个大站。

如果贵站支持了 aff，可以考虑再放上去。
