### ISSUE TITLE
能否增加 /v1/models对已映射模型的动态返回？

### ISSUE THREAD

**Issue by zhangmjcn** [songquanpeng/one-api#991]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ #] 我已确认目前没有类似 issue
+ [ #] 我已确认我已升级到最新版本
+ [ #] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [# ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ #] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
能否增加 /v1/models对已映射模型的动态返回？
目前v1/models这个api是通的，但是返回的数据似乎是静态的模型列表。
能否根据OneAPI配置接口、账户权限的情况，动态返回当前可用的models列表？

**应用场景**
让后端应用程序知道当前有哪些LLM通过OneAPI可用。

**Comment by songquanpeng** [comment]
是的，这个是之后要解决的问题，做到针对某个 key 只返回该 key 可用的模型列表。

**Comment by ChiayenGu** [comment]
> 是的，这个是之后要解决的问题，做到针对某个 key 只返回该 key 可用的模型列表。

您好，请问这个目前有计划解决吗？

**Comment by GalileoFe** [comment]
> 是的，这个是之后要解决的问题，做到针对某个 key 只返回该 key 可用的模型列表。

您好，如果我提交一个有关这个功能的PR可以得到通过吗？

**Comment by RexWzh** [comment]
@ChiayenGu 我也想提这个问题，这块需求确实挺多的。

我看去年六月 @ckt1031 提到下边这段代码，用这个逻辑能直接得到模型列表，但比较低效暂不考虑。

https://github.com/songquanpeng/one-api/blob/4ae311e964ba9a3a838b789ca7d21b9504cfff9e/middleware/distributor.go#L71

比起调模型跑数据，调用 `v1/models` 的次数非常非常少，尽管低效但不影响使用。

> 是的，这个是之后要解决的问题，做到针对某个 key 只返回该 key 可用的模型列表。

@songquanpeng 大佬可以考虑先用简单方法填上，后续再做更加系统的处理？


---

补充下使用场景和原因：
1. 基于 OneAPI 的项目需主动编写 API 手册，用户才能知道模型列表，而无法直接通过代码获取（比如 https://4.0.wokaai.com/about ）
2. 个人搭建给实验室内部用，陆续将本地模型添加到 OneAPI 中，如果成员能通过 `v1/models` 获知支持列表会更方便
3. 接口返回 OneAPI 支持的所有模型，这对维护者有帮助，但对使用者用处不大
4. 有不少 Issue 也提到这个问题了：
   - https://github.com/songquanpeng/one-api/issues/1060
   - https://github.com/songquanpeng/one-api/issues/366
   - https://github.com/songquanpeng/one-api/pull/307
   - https://github.com/songquanpeng/one-api/issues/142

**Comment by songquanpeng** [comment]
已经支持了
