### ISSUE TITLE
docker离线部署的时候启动不了

### ISSUE THREAD

**Issue by xxch** [songquanpeng/one-api#996]
在离线的情况下，使用docker启动时，启动不了。
报错： failed to get gpt-3.5-turbo token encoder: Get "https:/jopenaipublic.
.blob.core.windows.net/encodings/cl1gak base.tiktoken": dial tcp

**Comment by ImYrS** [comment]
未能成功下载用于计算令牌数的文件, 可以配置 TIKTOKEN 缓存目录并手动下载保存至目录中.

**Comment by songquanpeng** [comment]
是的，参见这里：https://github.com/pkoukk/tiktoken-go/blob/main/README_zh-hans.md#%E7%BC%93%E5%AD%98
